# 1:1 Port of FallAlertConfig.kt

BACKEND_BASE_URL = "http://172.16.2.156:5173/api"
PATIENT_ID = "REPLACE_WITH_PATIENT_ID"
DEVICE_ID = "edge-ai-camera-01"
INTEGRATION_KEY = ""
COOLDOWN_MS = 60_000

# Constants from CameraFragment
LOG_COOLDOWN_MS = 3000

# MediaPipe Defaults
MIN_POSE_DETECTION_CONFIDENCE = 0.5
MIN_POSE_TRACKING_CONFIDENCE = 0.5
MIN_POSE_PRESENCE_CONFIDENCE = 0.5
