using System.Diagnostics;
using System.Reflection;
using System.Resources;
using System.Runtime.CompilerServices;
using System.Runtime.Versioning;
using NHL.Views;
using Xamarin.Forms.Xaml;

[assembly: AssemblyTitle("NHL")]
[assembly: AssemblyDescription("")]
[assembly: AssemblyConfiguration("")]
[assembly: AssemblyCompany("")]
[assembly: AssemblyProduct("NHL")]
[assembly: AssemblyCopyright("Copyright ©  2014")]
[assembly: AssemblyTrademark("")]
[assembly: NeutralResourcesLanguage("en")]
[assembly: AssemblyFileVersion("1.0.0.0")]
[assembly: XamlResourceId("NHL.Views.BodyCompositionMeasurementView.xaml", "Views/BodyCompositionMeasurementView.xaml", typeof(BodyCompositionMeasurementView))]
[assembly: XamlResourceId("NHL.Views.CompositionMeterDetailView.xaml", "Views/CompositionMeterDetailView.xaml", typeof(CompositionMeterDetailView))]
[assembly: XamlResourceId("NHL.Views.CompositionMeterChartView.xaml", "Views/CompositionMeterChartView.xaml", typeof(CompositionMeterChartView))]
[assembly: XamlResourceId("NHL.Views.FirstMeterSelectView.xaml", "Views/FirstMeterSelectView.xaml", typeof(FirstMeterSelectView))]
[assembly: XamlResourceId("NHL.Views.HomeView.xaml", "Views/HomeView.xaml", typeof(HomeView))]
[assembly: XamlResourceId("NHL.Views.MasterDetailRootView.xaml", "Views/MasterDetailRootView.xaml", typeof(MasterDetailRootView))]
[assembly: XamlResourceId("NHL.Views.NoticeDetailView.xaml", "Views/NoticeDetailView.xaml", typeof(NoticeDetailView))]
[assembly: XamlResourceId("NHL.Views.NoticeListView.xaml", "Views/NoticeListView.xaml", typeof(NoticeListView))]
[assembly: XamlResourceId("NHL.Views.SettingView.xaml", "Views/SettingView.xaml", typeof(SettingView))]
[assembly: XamlResourceId("NHL.Views.MeasurementResultView.xaml", "Views/MeasurementResultView.xaml", typeof(MeasurementResultView))]
[assembly: XamlResourceId("NHL.Views.MeterView.xaml", "Views/MeterView.xaml", typeof(MeterView))]
[assembly: XamlResourceId("NHL.Views.MeterDetailView.xaml", "Views/MeterDetailView.xaml", typeof(MeterDetailView))]
[assembly: XamlResourceId("NHL.Views.MeterScanView.xaml", "Views/MeterScanView.xaml", typeof(MeterScanView))]
[assembly: XamlResourceId("NHL.Views.InformationView.xaml", "Views/InformationView.xaml", typeof(InformationView))]
[assembly: XamlResourceId("NHL.Views.SphygmomanometerChartView.xaml", "Views/SphygmomanometerChartView.xaml", typeof(SphygmomanometerChartView))]
[assembly: XamlResourceId("NHL.Views.StepChartView.xaml", "Views/StepChartView.xaml", typeof(StepChartView))]
[assembly: XamlResourceId("NHL.Views.TemperatureChartView.xaml", "Views/TemperatureChartView.xaml", typeof(TemperatureChartView))]
[assembly: XamlResourceId("NHL.Views.TermsOfServiceView.xaml", "Views/TermsOfServiceView.xaml", typeof(TermsOfServiceView))]
[assembly: XamlResourceId("NHL.Views.ChangeTimeZoneView.xaml", "Views/ChangeTimeZoneView.xaml", typeof(ChangeTimeZoneView))]
[assembly: XamlResourceId("NHL.Views.HospitalRegistrationView.xaml", "Views/HospitalRegistrationView.xaml", typeof(HospitalRegistrationView))]
[assembly: XamlResourceId("NHL.Views.HospitalDetailView.xaml", "Views/HospitalDetailView.xaml", typeof(HospitalDetailView))]
[assembly: XamlResourceId("NHL.Views.UnregisterHospitalView.xaml", "Views/UnregisterHospitalView.xaml", typeof(UnregisterHospitalView))]
[assembly: XamlResourceId("NHL.Views.TimeZoneRegistView.xaml", "Views/TimeZoneRegistView.xaml", typeof(TimeZoneRegistView))]
[assembly: XamlResourceId("NHL.Views.UserInfoRegistView.xaml", "Views/UserInfoRegistView.xaml", typeof(UserInfoRegistView))]
[assembly: XamlResourceId("NHL.Views.SetupView.xaml", "Views/SetupView.xaml", typeof(SetupView))]
[assembly: XamlResourceId("NHL.Views.TakePhotoView.xaml", "Views/TakePhotoView.xaml", typeof(TakePhotoView))]
[assembly: XamlResourceId("NHL.Views.PickPhotoView.xaml", "Views/PickPhotoView.xaml", typeof(PickPhotoView))]
[assembly: XamlResourceId("NHL.Views.TimeZoneUpdateView.xaml", "Views/TimeZoneUpdateView.xaml", typeof(TimeZoneUpdateView))]
[assembly: XamlResourceId("NHL.Views.UserInfoUpdateView.xaml", "Views/UserInfoUpdateView.xaml", typeof(UserInfoUpdateView))]
[assembly: XamlResourceId("NHL.Views.ImageTimezoneChangeView.xaml", "Views/ImageTimezoneChangeView.xaml", typeof(ImageTimezoneChangeView))]
[assembly: XamlResourceId("NHL.Views.ContactUsView.xaml", "Views/ContactUsView.xaml", typeof(ContactUsView))]
[assembly: XamlResourceId("NHL.Views.BackupCodeDisplayView.xaml", "Views/BackupCodeDisplayView.xaml", typeof(BackupCodeDisplayView))]
[assembly: XamlResourceId("NHL.Views.RestoreView.xaml", "Views/RestoreView.xaml", typeof(RestoreView))]
[assembly: XamlResourceId("NHL.Views.LogView.xaml", "Views/LogView.xaml", typeof(LogView))]
[assembly: XamlResourceId("NHL.Views.GlucoseTargetRegistView.xaml", "Views/GlucoseTargetRegistView.xaml", typeof(GlucoseTargetRegistView))]
[assembly: XamlResourceId("NHL.Views.GlucoseTargetUpdateView.xaml", "Views/GlucoseTargetUpdateView.xaml", typeof(GlucoseTargetUpdateView))]
[assembly: XamlResourceId("NHL.Views.EditDailyCommentView.xaml", "Views/EditDailyCommentView.xaml", typeof(EditDailyCommentView))]
[assembly: XamlResourceId("NHL.Views.MeasurementCalendarView.xaml", "Views/MeasurementCalendarView.xaml", typeof(MeasurementCalendarView))]
[assembly: XamlResourceId("NHL.Views.HomeImageTimezoneChangeView.xaml", "Views/HomeImageTimezoneChangeView.xaml", typeof(HomeImageTimezoneChangeView))]
[assembly: XamlResourceId("NHL.Views.GlucoseChartView.xaml", "Views/GlucoseChartView.xaml", typeof(GlucoseChartView))]
[assembly: XamlResourceId("NHL.Views.ChartCalendarView.xaml", "Views/ChartCalendarView.xaml", typeof(ChartCalendarView))]
[assembly: XamlResourceId("NHL.Views.ChartSettingView.xaml", "Views/ChartSettingView.xaml", typeof(ChartSettingView))]
[assembly: XamlResourceId("NHL.Views.GlucoseDataView.xaml", "Views/GlucoseDataView.xaml", typeof(GlucoseDataView))]
[assembly: XamlResourceId("NHL.Views.ColorSelectionView.xaml", "Views/ColorSelectionView.xaml", typeof(ColorSelectionView))]
[assembly: XamlResourceId("NHL.Views.SharerIntroductionView.xaml", "Views/SharerIntroductionView.xaml", typeof(SharerIntroductionView))]
[assembly: XamlResourceId("NHL.Views.SharerRegisterView.xaml", "Views/SharerRegisterView.xaml", typeof(SharerRegisterView))]
[assembly: XamlResourceId("NHL.Views.SharerInformationView.xaml", "Views/SharerInformationView.xaml", typeof(SharerInformationView))]
[assembly: XamlResourceId("NHL.Views.TimeZoneOtherRegistrationView.xaml", "Views/TimeZoneOtherRegistrationView.xaml", typeof(TimeZoneOtherRegistrationView))]
[assembly: XamlResourceId("NHL.Views.TimeZoneOtherUpdateView.xaml", "Views/TimeZoneOtherUpdateView.xaml", typeof(TimeZoneOtherUpdateView))]
[assembly: XamlResourceId("NHL.Views.ManualDataSyncView.xaml", "Views/ManualDataSyncView.xaml", typeof(ManualDataSyncView))]
[assembly: XamlResourceId("NHL.Views.TemperatureDataView.xaml", "Views/TemperatureDataView.xaml", typeof(TemperatureDataView))]
[assembly: XamlResourceId("NHL.Views.CompositionMeterDataView.xaml", "Views/CompositionMeterDataView.xaml", typeof(CompositionMeterDataView))]
[assembly: XamlResourceId("NHL.Views.SphygmomanometerDataView.xaml", "Views/SphygmomanometerDataView.xaml", typeof(SphygmomanometerDataView))]
[assembly: XamlResourceId("NHL.Views.RecordView.xaml", "Views/RecordView.xaml", typeof(RecordView))]
[assembly: XamlResourceId("NHL.Views.RecordEditView.xaml", "Views/RecordEditView.xaml", typeof(RecordEditView))]
[assembly: XamlResourceId("NHL.Views.StepDataView.xaml", "Views/StepDataView.xaml", typeof(StepDataView))]
[assembly: AssemblyVersion("1.0.0.0")]
