using System;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Reflection;
using BLELib.Common;
using Caliburn.Micro.Xamarin.Forms;
using NHL.Views.Effect;
using Xamarin.Forms;
using Xamarin.Forms.Internals;
using Xamarin.Forms.Xaml;
using Xamarin.Forms.Xaml.Diagnostics;
using Xamarin.Forms.Xaml.Internals;

namespace NHL.Views;

[XamlCompilation(XamlCompilationOptions.Compile)]
[XamlFilePath("Views/BodyCompositionMeasurementView.xaml")]
public class BodyCompositionMeasurementView : ContentPage
{
	public BodyCompositionMeasurementView()
	{
		InitializeComponent();
	}

	[GeneratedCode("Xamarin.Forms.Build.Tasks.XamlG", "2.0.0.0")]
	private void InitializeComponent()
	{
		if (ResourceLoader.CanProvideContentFor(new ResourceLoader.ResourceLoadingQuery
		{
			AssemblyName = typeof(BodyCompositionMeasurementView).GetTypeInfo().Assembly.GetName(),
			ResourcePath = "Views/BodyCompositionMeasurementView.xaml",
			Instance = this
		}))
		{
			__InitComponentRuntime();
			return;
		}
		if (XamlLoader.XamlFileProvider != null && XamlLoader.XamlFileProvider(GetType()) != null)
		{
			__InitComponentRuntime();
			return;
		}
		RowDefinition rowDefinition = new RowDefinition();
		RowDefinition rowDefinition2 = new RowDefinition();
		RowDefinition rowDefinition3 = new RowDefinition();
		RowDefinition rowDefinition4 = new RowDefinition();
		RowDefinition rowDefinition5 = new RowDefinition();
		BindingExtension bindingExtension = new BindingExtension();
		Setter setter = new Setter();
		DataTrigger dataTrigger = new DataTrigger(typeof(Image));
		BindingExtension bindingExtension2 = new BindingExtension();
		Setter setter2 = new Setter();
		DataTrigger dataTrigger2 = new DataTrigger(typeof(Image));
		Image image = new Image();
		FixedFontSizeLabelEffect fixedFontSizeLabelEffect = new FixedFontSizeLabelEffect();
		Label label = new Label();
		Grid grid = new Grid();
		RowDefinition rowDefinition6 = new RowDefinition();
		RowDefinition rowDefinition7 = new RowDefinition();
		RowDefinition rowDefinition8 = new RowDefinition();
		FixedFontSizeLabelEffect fixedFontSizeLabelEffect2 = new FixedFontSizeLabelEffect();
		BindingExtension bindingExtension3 = new BindingExtension();
		Setter setter3 = new Setter();
		DataTrigger dataTrigger3 = new DataTrigger(typeof(Label));
		BindingExtension bindingExtension4 = new BindingExtension();
		Setter setter4 = new Setter();
		DataTrigger dataTrigger4 = new DataTrigger(typeof(Label));
		BindingExtension bindingExtension5 = new BindingExtension();
		Setter setter5 = new Setter();
		DataTrigger dataTrigger5 = new DataTrigger(typeof(Label));
		BindingExtension bindingExtension6 = new BindingExtension();
		Setter setter6 = new Setter();
		DataTrigger dataTrigger6 = new DataTrigger(typeof(Label));
		Label label2 = new Label();
		FixedFontSizeLabelEffect fixedFontSizeLabelEffect3 = new FixedFontSizeLabelEffect();
		BindingExtension bindingExtension7 = new BindingExtension();
		Setter setter7 = new Setter();
		DataTrigger dataTrigger7 = new DataTrigger(typeof(Label));
		BindingExtension bindingExtension8 = new BindingExtension();
		Setter setter8 = new Setter();
		DataTrigger dataTrigger8 = new DataTrigger(typeof(Label));
		BindingExtension bindingExtension9 = new BindingExtension();
		Setter setter9 = new Setter();
		DataTrigger dataTrigger9 = new DataTrigger(typeof(Label));
		BindingExtension bindingExtension10 = new BindingExtension();
		Setter setter10 = new Setter();
		DataTrigger dataTrigger10 = new DataTrigger(typeof(Label));
		Label label3 = new Label();
		Grid grid2 = new Grid();
		BindingExtension bindingExtension11 = new BindingExtension();
		BLELibStatus bLELibStatus = BLELibStatus.NBCM_RCV_END;
		Setter setter11 = new Setter();
		DataTrigger dataTrigger11 = new DataTrigger(typeof(Grid));
		FixedFontSizeLabelEffect fixedFontSizeLabelEffect4 = new FixedFontSizeLabelEffect();
		Label label4 = new Label();
		Grid grid3 = new Grid();
		FixedFontSizeButtonEffect fixedFontSizeButtonEffect = new FixedFontSizeButtonEffect();
		Button button = new Button();
		Grid grid4 = new Grid();
		Grid grid5 = new Grid();
		BodyCompositionMeasurementView bodyCompositionMeasurementView;
		NameScope nameScope = (NameScope)(NameScope.GetNameScope(bodyCompositionMeasurementView = this) ?? new NameScope());
		NameScope.SetNameScope(bodyCompositionMeasurementView, nameScope);
		bodyCompositionMeasurementView.SetValue(NavigationPage.HasBackButtonProperty, true);
		bodyCompositionMeasurementView.SetValue(NavigationPage.BackButtonTitleProperty, "戻る");
		bodyCompositionMeasurementView.SetValue(Page.TitleProperty, "体組成計測定");
		rowDefinition.SetValue(RowDefinition.HeightProperty, new GridLengthTypeConverter().ConvertFromInvariantString("Auto"));
		((DefinitionCollection<RowDefinition>)grid4.GetValue(Grid.RowDefinitionsProperty)).Add(rowDefinition);
		rowDefinition2.SetValue(RowDefinition.HeightProperty, new GridLengthTypeConverter().ConvertFromInvariantString("Auto"));
		((DefinitionCollection<RowDefinition>)grid4.GetValue(Grid.RowDefinitionsProperty)).Add(rowDefinition2);
		rowDefinition3.SetValue(RowDefinition.HeightProperty, new GridLengthTypeConverter().ConvertFromInvariantString("Auto"));
		((DefinitionCollection<RowDefinition>)grid4.GetValue(Grid.RowDefinitionsProperty)).Add(rowDefinition3);
		rowDefinition4.SetValue(RowDefinition.HeightProperty, new GridLengthTypeConverter().ConvertFromInvariantString("Auto"));
		((DefinitionCollection<RowDefinition>)grid4.GetValue(Grid.RowDefinitionsProperty)).Add(rowDefinition4);
		rowDefinition5.SetValue(RowDefinition.HeightProperty, new GridLengthTypeConverter().ConvertFromInvariantString("*"));
		((DefinitionCollection<RowDefinition>)grid4.GetValue(Grid.RowDefinitionsProperty)).Add(rowDefinition5);
		image.SetValue(Grid.RowProperty, 0);
		image.SetValue(Grid.RowSpanProperty, 5);
		image.SetValue(Xamarin.Forms.View.HorizontalOptionsProperty, LayoutOptions.FillAndExpand);
		image.SetValue(Xamarin.Forms.View.VerticalOptionsProperty, LayoutOptions.FillAndExpand);
		image.SetValue(Image.AspectProperty, Aspect.AspectFill);
		bindingExtension.Path = "IsiPad";
		BindingBase target = (dataTrigger.Binding = ((IMarkupExtension<BindingBase>)bindingExtension).ProvideValue((IServiceProvider)null));
		VisualDiagnostics.RegisterSourceInfo(target, new Uri("Views/BodyCompositionMeasurementView.xaml", UriKind.RelativeOrAbsolute), 24, 53);
		dataTrigger.Value = "true";
		setter.Property = Image.SourceProperty;
		setter.Value = "bg_ipad.png";
		setter.Value = new ImageSourceConverter().ConvertFromInvariantString("bg_ipad.png");
		dataTrigger.Setters.Add(setter);
		VisualDiagnostics.RegisterSourceInfo(setter, new Uri("Views/BodyCompositionMeasurementView.xaml", UriKind.RelativeOrAbsolute), 25, 26);
		((ICollection<TriggerBase>)image.GetValue(VisualElement.TriggersProperty)).Add((TriggerBase)dataTrigger);
		bindingExtension2.Path = "IsiPad";
		BindingBase target2 = (dataTrigger2.Binding = ((IMarkupExtension<BindingBase>)bindingExtension2).ProvideValue((IServiceProvider)null));
		VisualDiagnostics.RegisterSourceInfo(target2, new Uri("Views/BodyCompositionMeasurementView.xaml", UriKind.RelativeOrAbsolute), 27, 53);
		dataTrigger2.Value = "false";
		setter2.Property = Image.SourceProperty;
		setter2.Value = "bg.png";
		setter2.Value = new ImageSourceConverter().ConvertFromInvariantString("bg.png");
		dataTrigger2.Setters.Add(setter2);
		VisualDiagnostics.RegisterSourceInfo(setter2, new Uri("Views/BodyCompositionMeasurementView.xaml", UriKind.RelativeOrAbsolute), 28, 26);
		((ICollection<TriggerBase>)image.GetValue(VisualElement.TriggersProperty)).Add((TriggerBase)dataTrigger2);
		grid4.Children.Add(image);
		VisualDiagnostics.RegisterSourceInfo(image, new Uri("Views/BodyCompositionMeasurementView.xaml", UriKind.RelativeOrAbsolute), 22, 14);
		grid.SetValue(Grid.RowProperty, 0);
		grid.SetValue(VisualElement.BackgroundColorProperty, Color.White);
		grid.SetValue(Xamarin.Forms.View.MarginProperty, new Thickness(10.0, 10.0, 10.0, 10.0));
		label.SetValue(Xamarin.Forms.View.MarginProperty, new Thickness(10.0, 10.0, 10.0, 10.0));
		label.SetValue(Label.TextColorProperty, Color.Black);
		label.SetValue(Label.HorizontalTextAlignmentProperty, new TextAlignmentConverter().ConvertFromInvariantString("Center"));
		label.SetValue(VisualElement.BackgroundColorProperty, Color.Transparent);
		label.SetValue(Label.TextProperty, "【注意】\r\n体組成計専用の画面です。\r\nその他の機器はご利用になれません。");
		label.Effects.Add(fixedFontSizeLabelEffect);
		VisualDiagnostics.RegisterSourceInfo(fixedFontSizeLabelEffect, new Uri("Views/BodyCompositionMeasurementView.xaml", UriKind.RelativeOrAbsolute), 37, 26);
		grid.Children.Add(label);
		VisualDiagnostics.RegisterSourceInfo(label, new Uri("Views/BodyCompositionMeasurementView.xaml", UriKind.RelativeOrAbsolute), 34, 18);
		grid4.Children.Add(grid);
		VisualDiagnostics.RegisterSourceInfo(grid, new Uri("Views/BodyCompositionMeasurementView.xaml", UriKind.RelativeOrAbsolute), 33, 14);
		grid2.SetValue(Grid.RowProperty, 1);
		grid2.SetValue(VisualElement.BackgroundColorProperty, Color.White);
		grid2.SetValue(Xamarin.Forms.View.MarginProperty, new Thickness(10.0, 10.0, 10.0, 10.0));
		rowDefinition6.SetValue(RowDefinition.HeightProperty, new GridLengthTypeConverter().ConvertFromInvariantString("Auto"));
		((DefinitionCollection<RowDefinition>)grid2.GetValue(Grid.RowDefinitionsProperty)).Add(rowDefinition6);
		rowDefinition7.SetValue(RowDefinition.HeightProperty, new GridLengthTypeConverter().ConvertFromInvariantString("Auto"));
		((DefinitionCollection<RowDefinition>)grid2.GetValue(Grid.RowDefinitionsProperty)).Add(rowDefinition7);
		rowDefinition8.SetValue(RowDefinition.HeightProperty, new GridLengthTypeConverter().ConvertFromInvariantString("*"));
		((DefinitionCollection<RowDefinition>)grid2.GetValue(Grid.RowDefinitionsProperty)).Add(rowDefinition8);
		label2.SetValue(Grid.RowProperty, 0);
		label2.SetValue(Xamarin.Forms.View.MarginProperty, new Thickness(0.0, 10.0, 0.0, 10.0));
		label2.SetValue(Label.HorizontalTextAlignmentProperty, new TextAlignmentConverter().ConvertFromInvariantString("Center"));
		label2.SetValue(Label.TextColorProperty, Color.MediumBlue);
		BindableProperty fontSizeProperty = Label.FontSizeProperty;
		FontSizeConverter fontSizeConverter = new FontSizeConverter();
		XamlServiceProvider xamlServiceProvider = new XamlServiceProvider();
		Type typeFromHandle = typeof(IProvideValueTarget);
		object[] array = new object[0 + 5];
		array[0] = label2;
		array[1] = grid2;
		array[2] = grid4;
		array[3] = grid5;
		array[4] = bodyCompositionMeasurementView;
		object service;
		xamlServiceProvider.Add(typeFromHandle, service = new SimpleValueTargetProvider(array, Label.FontSizeProperty, nameScope));
		xamlServiceProvider.Add(typeof(IReferenceProvider), service);
		Type typeFromHandle2 = typeof(IXamlTypeResolver);
		XmlNamespaceResolver xmlNamespaceResolver = new XmlNamespaceResolver();
		xmlNamespaceResolver.Add("", "http://xamarin.com/schemas/2014/forms");
		xmlNamespaceResolver.Add("x", "http://schemas.microsoft.com/winfx/2009/xaml");
		xmlNamespaceResolver.Add("calx", "clr-namespace:Caliburn.Micro.Xamarin.Forms;assembly=Caliburn.Micro.Platform.Xamarin.Forms");
		xmlNamespaceResolver.Add("effect", "clr-namespace:NHL.Views.Effect");
		xmlNamespaceResolver.Add("blelib", "clr-namespace:BLELib.Common;assembly=BLELib");
		xamlServiceProvider.Add(typeFromHandle2, new XamlTypeResolver(xmlNamespaceResolver, typeof(BodyCompositionMeasurementView).GetTypeInfo().Assembly));
		xamlServiceProvider.Add(typeof(IXmlLineInfoProvider), new XmlLineInfoProvider(new XmlLineInfo(49, 112)));
		label2.SetValue(fontSizeProperty, ((IExtendedTypeConverter)fontSizeConverter).ConvertFromInvariantString("Medium", (IServiceProvider)xamlServiceProvider));
		label2.SetValue(Label.FontAttributesProperty, new FontAttributesConverter().ConvertFromInvariantString("Bold"));
		label2.SetValue(VisualElement.BackgroundColorProperty, Color.Transparent);
		label2.Effects.Add(fixedFontSizeLabelEffect2);
		VisualDiagnostics.RegisterSourceInfo(fixedFontSizeLabelEffect2, new Uri("Views/BodyCompositionMeasurementView.xaml", UriKind.RelativeOrAbsolute), 51, 26);
		bindingExtension3.Path = "DeviceStatus";
		BindingBase target3 = (dataTrigger3.Binding = ((IMarkupExtension<BindingBase>)bindingExtension3).ProvideValue((IServiceProvider)null));
		VisualDiagnostics.RegisterSourceInfo(target3, new Uri("Views/BodyCompositionMeasurementView.xaml", UriKind.RelativeOrAbsolute), 54, 57);
		dataTrigger3.Value = "RCV_WAIT_START";
		setter3.Property = Label.TextProperty;
		setter3.Value = "探索中";
		setter3.Value = "探索中";
		dataTrigger3.Setters.Add(setter3);
		VisualDiagnostics.RegisterSourceInfo(setter3, new Uri("Views/BodyCompositionMeasurementView.xaml", UriKind.RelativeOrAbsolute), 55, 30);
		((ICollection<TriggerBase>)label2.GetValue(VisualElement.TriggersProperty)).Add((TriggerBase)dataTrigger3);
		bindingExtension4.Path = "DeviceStatus";
		BindingBase target4 = (dataTrigger4.Binding = ((IMarkupExtension<BindingBase>)bindingExtension4).ProvideValue((IServiceProvider)null));
		VisualDiagnostics.RegisterSourceInfo(target4, new Uri("Views/BodyCompositionMeasurementView.xaml", UriKind.RelativeOrAbsolute), 57, 57);
		dataTrigger4.Value = "NBCM_STEP_ON";
		setter4.Property = Label.TextProperty;
		setter4.Value = "待機中";
		setter4.Value = "待機中";
		dataTrigger4.Setters.Add(setter4);
		VisualDiagnostics.RegisterSourceInfo(setter4, new Uri("Views/BodyCompositionMeasurementView.xaml", UriKind.RelativeOrAbsolute), 58, 30);
		((ICollection<TriggerBase>)label2.GetValue(VisualElement.TriggersProperty)).Add((TriggerBase)dataTrigger4);
		bindingExtension5.Path = "DeviceStatus";
		BindingBase target5 = (dataTrigger5.Binding = ((IMarkupExtension<BindingBase>)bindingExtension5).ProvideValue((IServiceProvider)null));
		VisualDiagnostics.RegisterSourceInfo(target5, new Uri("Views/BodyCompositionMeasurementView.xaml", UriKind.RelativeOrAbsolute), 60, 57);
		dataTrigger5.Value = "NBCM_STEP_OFF";
		setter5.Property = Label.TextProperty;
		setter5.Value = "測定完了";
		setter5.Value = "測定完了";
		dataTrigger5.Setters.Add(setter5);
		VisualDiagnostics.RegisterSourceInfo(setter5, new Uri("Views/BodyCompositionMeasurementView.xaml", UriKind.RelativeOrAbsolute), 61, 30);
		((ICollection<TriggerBase>)label2.GetValue(VisualElement.TriggersProperty)).Add((TriggerBase)dataTrigger5);
		bindingExtension6.Path = "DeviceStatus";
		BindingBase target6 = (dataTrigger6.Binding = ((IMarkupExtension<BindingBase>)bindingExtension6).ProvideValue((IServiceProvider)null));
		VisualDiagnostics.RegisterSourceInfo(target6, new Uri("Views/BodyCompositionMeasurementView.xaml", UriKind.RelativeOrAbsolute), 63, 57);
		dataTrigger6.Value = "NBCM_RCV_END";
		setter6.Property = Label.TextProperty;
		setter6.Value = "通信中";
		setter6.Value = "通信中";
		dataTrigger6.Setters.Add(setter6);
		VisualDiagnostics.RegisterSourceInfo(setter6, new Uri("Views/BodyCompositionMeasurementView.xaml", UriKind.RelativeOrAbsolute), 64, 30);
		((ICollection<TriggerBase>)label2.GetValue(VisualElement.TriggersProperty)).Add((TriggerBase)dataTrigger6);
		grid2.Children.Add(label2);
		VisualDiagnostics.RegisterSourceInfo(label2, new Uri("Views/BodyCompositionMeasurementView.xaml", UriKind.RelativeOrAbsolute), 49, 18);
		label3.SetValue(Grid.RowProperty, 1);
		label3.SetValue(Xamarin.Forms.View.MarginProperty, new Thickness(0.0, 0.0, 0.0, 10.0));
		label3.SetValue(Label.HorizontalTextAlignmentProperty, new TextAlignmentConverter().ConvertFromInvariantString("Center"));
		label3.SetValue(Label.TextColorProperty, Color.MediumBlue);
		BindableProperty fontSizeProperty2 = Label.FontSizeProperty;
		FontSizeConverter fontSizeConverter2 = new FontSizeConverter();
		XamlServiceProvider xamlServiceProvider2 = new XamlServiceProvider();
		Type typeFromHandle3 = typeof(IProvideValueTarget);
		object[] array2 = new object[0 + 5];
		array2[0] = label3;
		array2[1] = grid2;
		array2[2] = grid4;
		array2[3] = grid5;
		array2[4] = bodyCompositionMeasurementView;
		object service2;
		xamlServiceProvider2.Add(typeFromHandle3, service2 = new SimpleValueTargetProvider(array2, Label.FontSizeProperty, nameScope));
		xamlServiceProvider2.Add(typeof(IReferenceProvider), service2);
		Type typeFromHandle4 = typeof(IXamlTypeResolver);
		XmlNamespaceResolver xmlNamespaceResolver2 = new XmlNamespaceResolver();
		xmlNamespaceResolver2.Add("", "http://xamarin.com/schemas/2014/forms");
		xmlNamespaceResolver2.Add("x", "http://schemas.microsoft.com/winfx/2009/xaml");
		xmlNamespaceResolver2.Add("calx", "clr-namespace:Caliburn.Micro.Xamarin.Forms;assembly=Caliburn.Micro.Platform.Xamarin.Forms");
		xmlNamespaceResolver2.Add("effect", "clr-namespace:NHL.Views.Effect");
		xmlNamespaceResolver2.Add("blelib", "clr-namespace:BLELib.Common;assembly=BLELib");
		xamlServiceProvider2.Add(typeFromHandle4, new XamlTypeResolver(xmlNamespaceResolver2, typeof(BodyCompositionMeasurementView).GetTypeInfo().Assembly));
		xamlServiceProvider2.Add(typeof(IXmlLineInfoProvider), new XmlLineInfoProvider(new XmlLineInfo(69, 111)));
		label3.SetValue(fontSizeProperty2, ((IExtendedTypeConverter)fontSizeConverter2).ConvertFromInvariantString("Default", (IServiceProvider)xamlServiceProvider2));
		label3.SetValue(VisualElement.BackgroundColorProperty, Color.Transparent);
		label3.Effects.Add(fixedFontSizeLabelEffect3);
		VisualDiagnostics.RegisterSourceInfo(fixedFontSizeLabelEffect3, new Uri("Views/BodyCompositionMeasurementView.xaml", UriKind.RelativeOrAbsolute), 71, 26);
		bindingExtension7.Path = "DeviceStatus";
		BindingBase target7 = (dataTrigger7.Binding = ((IMarkupExtension<BindingBase>)bindingExtension7).ProvideValue((IServiceProvider)null));
		VisualDiagnostics.RegisterSourceInfo(target7, new Uri("Views/BodyCompositionMeasurementView.xaml", UriKind.RelativeOrAbsolute), 74, 57);
		dataTrigger7.Value = "RCV_WAIT_START";
		setter7.Property = Label.TextProperty;
		setter7.Value = "体組成計を探しています。\r\n体組成計の近くに\r\n移動してください。";
		setter7.Value = "体組成計を探しています。\r\n体組成計の近くに\r\n移動してください。";
		dataTrigger7.Setters.Add(setter7);
		VisualDiagnostics.RegisterSourceInfo(setter7, new Uri("Views/BodyCompositionMeasurementView.xaml", UriKind.RelativeOrAbsolute), 75, 30);
		((ICollection<TriggerBase>)label3.GetValue(VisualElement.TriggersProperty)).Add((TriggerBase)dataTrigger7);
		bindingExtension8.Path = "DeviceStatus";
		BindingBase target8 = (dataTrigger8.Binding = ((IMarkupExtension<BindingBase>)bindingExtension8).ProvideValue((IServiceProvider)null));
		VisualDiagnostics.RegisterSourceInfo(target8, new Uri("Views/BodyCompositionMeasurementView.xaml", UriKind.RelativeOrAbsolute), 77, 57);
		dataTrigger8.Value = "NBCM_STEP_ON";
		setter8.Property = Label.TextProperty;
		setter8.Value = "体組成計からの\r\n受信を待っています。\r\n体組成計の表示に従って\r\n測定を行ってください。";
		setter8.Value = "体組成計からの\r\n受信を待っています。\r\n体組成計の表示に従って\r\n測定を行ってください。";
		dataTrigger8.Setters.Add(setter8);
		VisualDiagnostics.RegisterSourceInfo(setter8, new Uri("Views/BodyCompositionMeasurementView.xaml", UriKind.RelativeOrAbsolute), 78, 30);
		((ICollection<TriggerBase>)label3.GetValue(VisualElement.TriggersProperty)).Add((TriggerBase)dataTrigger8);
		bindingExtension9.Path = "DeviceStatus";
		BindingBase target9 = (dataTrigger9.Binding = ((IMarkupExtension<BindingBase>)bindingExtension9).ProvideValue((IServiceProvider)null));
		VisualDiagnostics.RegisterSourceInfo(target9, new Uri("Views/BodyCompositionMeasurementView.xaml", UriKind.RelativeOrAbsolute), 80, 57);
		dataTrigger9.Value = "NBCM_STEP_OFF";
		setter9.Property = Label.TextProperty;
		setter9.Value = "測定が完了しました。\r\n体組成計から降りて\r\nお待ちください。";
		setter9.Value = "測定が完了しました。\r\n体組成計から降りて\r\nお待ちください。";
		dataTrigger9.Setters.Add(setter9);
		VisualDiagnostics.RegisterSourceInfo(setter9, new Uri("Views/BodyCompositionMeasurementView.xaml", UriKind.RelativeOrAbsolute), 81, 30);
		((ICollection<TriggerBase>)label3.GetValue(VisualElement.TriggersProperty)).Add((TriggerBase)dataTrigger9);
		bindingExtension10.Path = "DeviceStatus";
		BindingBase target10 = (dataTrigger10.Binding = ((IMarkupExtension<BindingBase>)bindingExtension10).ProvideValue((IServiceProvider)null));
		VisualDiagnostics.RegisterSourceInfo(target10, new Uri("Views/BodyCompositionMeasurementView.xaml", UriKind.RelativeOrAbsolute), 83, 57);
		dataTrigger10.Value = "NBCM_RCV_END";
		setter10.Property = Label.TextProperty;
		setter10.Value = "体組成計と通信しています。\r\nアプリはこのままの状態で\r\nお待ちください。";
		setter10.Value = "体組成計と通信しています。\r\nアプリはこのままの状態で\r\nお待ちください。";
		dataTrigger10.Setters.Add(setter10);
		VisualDiagnostics.RegisterSourceInfo(setter10, new Uri("Views/BodyCompositionMeasurementView.xaml", UriKind.RelativeOrAbsolute), 84, 30);
		((ICollection<TriggerBase>)label3.GetValue(VisualElement.TriggersProperty)).Add((TriggerBase)dataTrigger10);
		grid2.Children.Add(label3);
		VisualDiagnostics.RegisterSourceInfo(label3, new Uri("Views/BodyCompositionMeasurementView.xaml", UriKind.RelativeOrAbsolute), 69, 18);
		grid4.Children.Add(grid2);
		VisualDiagnostics.RegisterSourceInfo(grid2, new Uri("Views/BodyCompositionMeasurementView.xaml", UriKind.RelativeOrAbsolute), 42, 14);
		grid3.SetValue(Grid.RowProperty, 2);
		grid3.SetValue(VisualElement.BackgroundColorProperty, Color.Orange);
		grid3.SetValue(Xamarin.Forms.View.MarginProperty, new Thickness(10.0, 10.0, 10.0, 10.0));
		grid3.SetValue(VisualElement.OpacityProperty, 0.0);
		bindingExtension11.Path = "DeviceStatus";
		BindingBase target11 = (dataTrigger11.Binding = ((IMarkupExtension<BindingBase>)bindingExtension11).ProvideValue((IServiceProvider)null));
		VisualDiagnostics.RegisterSourceInfo(target11, new Uri("Views/BodyCompositionMeasurementView.xaml", UriKind.RelativeOrAbsolute), 94, 34);
		dataTrigger11.Value = bLELibStatus;
		setter11.Property = VisualElement.OpacityProperty;
		setter11.Value = "1";
		setter11.Value = 1.0;
		dataTrigger11.Setters.Add(setter11);
		VisualDiagnostics.RegisterSourceInfo(setter11, new Uri("Views/BodyCompositionMeasurementView.xaml", UriKind.RelativeOrAbsolute), 96, 26);
		((ICollection<TriggerBase>)grid3.GetValue(VisualElement.TriggersProperty)).Add((TriggerBase)dataTrigger11);
		VisualDiagnostics.RegisterSourceInfo(dataTrigger11, new Uri("Views/BodyCompositionMeasurementView.xaml", UriKind.RelativeOrAbsolute), 93, 22);
		label4.SetValue(Grid.RowProperty, 0);
		label4.SetValue(Xamarin.Forms.View.MarginProperty, new Thickness(2.0, 2.0, 2.0, 2.0));
		label4.SetValue(Label.HorizontalTextAlignmentProperty, new TextAlignmentConverter().ConvertFromInvariantString("Center"));
		label4.SetValue(Label.TextColorProperty, Color.MediumBlue);
		BindableProperty fontSizeProperty3 = Label.FontSizeProperty;
		FontSizeConverter fontSizeConverter3 = new FontSizeConverter();
		XamlServiceProvider xamlServiceProvider3 = new XamlServiceProvider();
		Type typeFromHandle5 = typeof(IProvideValueTarget);
		object[] array3 = new object[0 + 5];
		array3[0] = label4;
		array3[1] = grid3;
		array3[2] = grid4;
		array3[3] = grid5;
		array3[4] = bodyCompositionMeasurementView;
		object service3;
		xamlServiceProvider3.Add(typeFromHandle5, service3 = new SimpleValueTargetProvider(array3, Label.FontSizeProperty, nameScope));
		xamlServiceProvider3.Add(typeof(IReferenceProvider), service3);
		Type typeFromHandle6 = typeof(IXamlTypeResolver);
		XmlNamespaceResolver xmlNamespaceResolver3 = new XmlNamespaceResolver();
		xmlNamespaceResolver3.Add("", "http://xamarin.com/schemas/2014/forms");
		xmlNamespaceResolver3.Add("x", "http://schemas.microsoft.com/winfx/2009/xaml");
		xmlNamespaceResolver3.Add("calx", "clr-namespace:Caliburn.Micro.Xamarin.Forms;assembly=Caliburn.Micro.Platform.Xamarin.Forms");
		xmlNamespaceResolver3.Add("effect", "clr-namespace:NHL.Views.Effect");
		xmlNamespaceResolver3.Add("blelib", "clr-namespace:BLELib.Common;assembly=BLELib");
		xamlServiceProvider3.Add(typeFromHandle6, new XamlTypeResolver(xmlNamespaceResolver3, typeof(BodyCompositionMeasurementView).GetTypeInfo().Assembly));
		xamlServiceProvider3.Add(typeof(IXmlLineInfoProvider), new XmlLineInfoProvider(new XmlLineInfo(100, 110)));
		label4.SetValue(fontSizeProperty3, ((IExtendedTypeConverter)fontSizeConverter3).ConvertFromInvariantString("Small", (IServiceProvider)xamlServiceProvider3));
		label4.SetValue(Label.FontAttributesProperty, new FontAttributesConverter().ConvertFromInvariantString("Bold"));
		label4.SetValue(VisualElement.BackgroundColorProperty, Color.White);
		label4.SetValue(Label.TextProperty, "体組成計の中央ガラス部分を\r\n軽く踏み込んで\r\n本体の液晶をオフにしてください。");
		label4.Effects.Add(fixedFontSizeLabelEffect4);
		VisualDiagnostics.RegisterSourceInfo(fixedFontSizeLabelEffect4, new Uri("Views/BodyCompositionMeasurementView.xaml", UriKind.RelativeOrAbsolute), 103, 26);
		grid3.Children.Add(label4);
		VisualDiagnostics.RegisterSourceInfo(label4, new Uri("Views/BodyCompositionMeasurementView.xaml", UriKind.RelativeOrAbsolute), 100, 18);
		grid4.Children.Add(grid3);
		VisualDiagnostics.RegisterSourceInfo(grid3, new Uri("Views/BodyCompositionMeasurementView.xaml", UriKind.RelativeOrAbsolute), 90, 14);
		button.SetValue(Grid.RowProperty, 3);
		button.SetValue(Xamarin.Forms.View.MarginProperty, new Thickness(10.0, 10.0, 10.0, 10.0));
		button.SetValue(Button.TextProperty, "測定を終了");
		button.SetValue(Message.AttachProperty, "GoBackHome");
		BindableProperty fontSizeProperty4 = Button.FontSizeProperty;
		FontSizeConverter fontSizeConverter4 = new FontSizeConverter();
		XamlServiceProvider xamlServiceProvider4 = new XamlServiceProvider();
		Type typeFromHandle7 = typeof(IProvideValueTarget);
		object[] array4 = new object[0 + 4];
		array4[0] = button;
		array4[1] = grid4;
		array4[2] = grid5;
		array4[3] = bodyCompositionMeasurementView;
		object service4;
		xamlServiceProvider4.Add(typeFromHandle7, service4 = new SimpleValueTargetProvider(array4, Button.FontSizeProperty, nameScope));
		xamlServiceProvider4.Add(typeof(IReferenceProvider), service4);
		Type typeFromHandle8 = typeof(IXamlTypeResolver);
		XmlNamespaceResolver xmlNamespaceResolver4 = new XmlNamespaceResolver();
		xmlNamespaceResolver4.Add("", "http://xamarin.com/schemas/2014/forms");
		xmlNamespaceResolver4.Add("x", "http://schemas.microsoft.com/winfx/2009/xaml");
		xmlNamespaceResolver4.Add("calx", "clr-namespace:Caliburn.Micro.Xamarin.Forms;assembly=Caliburn.Micro.Platform.Xamarin.Forms");
		xmlNamespaceResolver4.Add("effect", "clr-namespace:NHL.Views.Effect");
		xmlNamespaceResolver4.Add("blelib", "clr-namespace:BLELib.Common;assembly=BLELib");
		xamlServiceProvider4.Add(typeFromHandle8, new XamlTypeResolver(xmlNamespaceResolver4, typeof(BodyCompositionMeasurementView).GetTypeInfo().Assembly));
		xamlServiceProvider4.Add(typeof(IXmlLineInfoProvider), new XmlLineInfoProvider(new XmlLineInfo(108, 101)));
		button.SetValue(fontSizeProperty4, ((IExtendedTypeConverter)fontSizeConverter4).ConvertFromInvariantString("Medium", (IServiceProvider)xamlServiceProvider4));
		button.SetValue(Button.FontAttributesProperty, new FontAttributesConverter().ConvertFromInvariantString("Bold"));
		button.SetValue(Button.TextColorProperty, Color.Blue);
		button.SetValue(VisualElement.BackgroundColorProperty, Color.White);
		button.SetValue(Button.BorderWidthProperty, 1.0);
		button.SetValue(Button.BorderColorProperty, Color.Black);
		button.Effects.Add(fixedFontSizeButtonEffect);
		VisualDiagnostics.RegisterSourceInfo(fixedFontSizeButtonEffect, new Uri("Views/BodyCompositionMeasurementView.xaml", UriKind.RelativeOrAbsolute), 110, 22);
		grid4.Children.Add(button);
		VisualDiagnostics.RegisterSourceInfo(button, new Uri("Views/BodyCompositionMeasurementView.xaml", UriKind.RelativeOrAbsolute), 108, 14);
		grid5.Children.Add(grid4);
		VisualDiagnostics.RegisterSourceInfo(grid4, new Uri("Views/BodyCompositionMeasurementView.xaml", UriKind.RelativeOrAbsolute), 13, 10);
		bodyCompositionMeasurementView.SetValue(ContentPage.ContentProperty, grid5);
		VisualDiagnostics.RegisterSourceInfo(grid5, new Uri("Views/BodyCompositionMeasurementView.xaml", UriKind.RelativeOrAbsolute), 12, 6);
		VisualDiagnostics.RegisterSourceInfo(bodyCompositionMeasurementView, new Uri("Views/BodyCompositionMeasurementView.xaml", UriKind.RelativeOrAbsolute), 2, 2);
	}

	private void __InitComponentRuntime()
	{
		this.LoadFromXaml(typeof(BodyCompositionMeasurementView));
	}
}
