using System;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Reflection;
using NHL.Views.Converters;
using NHL.Views.Effect;
using NHL.Views.Renderer;
using Xamarin.Forms;
using Xamarin.Forms.Internals;
using Xamarin.Forms.Xaml;
using Xamarin.Forms.Xaml.Diagnostics;
using Xamarin.Forms.Xaml.Internals;

namespace NHL.Views;

[XamlCompilation(XamlCompilationOptions.Compile)]
[XamlFilePath("Views/ChangeTimeZoneView.xaml")]
public class ChangeTimeZoneView : ContentPage
{
	public ChangeTimeZoneView()
	{
		InitializeComponent();
	}

	[GeneratedCode("Xamarin.Forms.Build.Tasks.XamlG", "2.0.0.0")]
	private void InitializeComponent()
	{
		if (ResourceLoader.CanProvideContentFor(new ResourceLoader.ResourceLoadingQuery
		{
			AssemblyName = typeof(ChangeTimeZoneView).GetTypeInfo().Assembly.GetName(),
			ResourcePath = "Views/ChangeTimeZoneView.xaml",
			Instance = this
		}))
		{
			__InitComponentRuntime();
			return;
		}
		if (XamlLoader.XamlFileProvider != null && XamlLoader.XamlFileProvider(GetType()) != null)
		{
			__InitComponentRuntime();
			return;
		}
		Color color = Color.FromHex("#999999");
		BooleanSwitchConverter value = new BooleanSwitchConverter();
		ResourceDictionary resourceDictionary = new ResourceDictionary();
		OnPlatform<Thickness> onPlatform = new OnPlatform<Thickness>();
		RowDefinition rowDefinition = new RowDefinition();
		RowDefinition rowDefinition2 = new RowDefinition();
		RowDefinition rowDefinition3 = new RowDefinition();
		RowDefinition rowDefinition4 = new RowDefinition();
		RowDefinition rowDefinition5 = new RowDefinition();
		RowDefinition item = new RowDefinition();
		BindingExtension bindingExtension = new BindingExtension();
		FixedFontSizeLabelEffect fixedFontSizeLabelEffect = new FixedFontSizeLabelEffect();
		Label label = new Label();
		ColumnDefinition columnDefinition = new ColumnDefinition();
		ColumnDefinition item2 = new ColumnDefinition();
		ColumnDefinition columnDefinition2 = new ColumnDefinition();
		BindingExtension bindingExtension2 = new BindingExtension();
		FixedFontSizeLabelEffect fixedFontSizeLabelEffect2 = new FixedFontSizeLabelEffect();
		Label label2 = new Label();
		BindingExtension bindingExtension3 = new BindingExtension();
		Setter setter = new Setter();
		DataTrigger dataTrigger = new DataTrigger(typeof(Image));
		Image image = new Image();
		BindingExtension bindingExtension4 = new BindingExtension();
		Setter setter2 = new Setter();
		DataTrigger dataTrigger2 = new DataTrigger(typeof(Image));
		Image image2 = new Image();
		BindingExtension bindingExtension5 = new BindingExtension();
		Setter setter3 = new Setter();
		DataTrigger dataTrigger3 = new DataTrigger(typeof(Image));
		Image image3 = new Image();
		Grid grid = new Grid();
		StaticResourceExtension staticResourceExtension = new StaticResourceExtension();
		BindingExtension bindingExtension6 = new BindingExtension();
		RadiusBoxView radiusBoxView = new RadiusBoxView();
		BindingExtension bindingExtension7 = new BindingExtension();
		BindingExtension bindingExtension8 = new BindingExtension();
		BindingExtension bindingExtension9 = new BindingExtension();
		BindingExtension bindingExtension10 = new BindingExtension();
		FlatEntryEffect item3 = new FlatEntryEffect();
		FlatPickerEffect item4 = new FlatPickerEffect();
		FixedFontSizeTextBoxEffect item5 = new FixedFontSizeTextBoxEffect();
		Picker picker = new Picker();
		StaticResourceExtension staticResourceExtension2 = new StaticResourceExtension();
		StaticResourceExtension staticResourceExtension3 = new StaticResourceExtension();
		BindingExtension bindingExtension11 = new BindingExtension();
		RadiusBoxView radiusBoxView2 = new RadiusBoxView();
		BindingExtension bindingExtension12 = new BindingExtension();
		BindingExtension bindingExtension13 = new BindingExtension();
		BindingExtension bindingExtension14 = new BindingExtension();
		StaticResourceExtension staticResourceExtension4 = new StaticResourceExtension();
		BindingExtension bindingExtension15 = new BindingExtension();
		FlatEntryEffect item6 = new FlatEntryEffect();
		FlatPickerEffect item7 = new FlatPickerEffect();
		FixedFontSizeTextBoxEffect item8 = new FixedFontSizeTextBoxEffect();
		Picker picker2 = new Picker();
		Grid grid2 = new Grid();
		ChangeTimeZoneView changeTimeZoneView;
		NameScope nameScope = (NameScope)(NameScope.GetNameScope(changeTimeZoneView = this) ?? new NameScope());
		NameScope.SetNameScope(changeTimeZoneView, nameScope);
		changeTimeZoneView.Resources = resourceDictionary;
		VisualDiagnostics.RegisterSourceInfo(resourceDictionary, new Uri("Views/ChangeTimeZoneView.xaml", UriKind.RelativeOrAbsolute), 16, 10);
		resourceDictionary.Add("InputFrameColor", color);
		resourceDictionary.Add("BooleanSwitchConverter", value);
		changeTimeZoneView.SetValue(NavigationPage.HasBackButtonProperty, true);
		changeTimeZoneView.SetValue(NavigationPage.BackButtonTitleProperty, "戻る");
		changeTimeZoneView.SetValue(Page.TitleProperty, "");
		changeTimeZoneView.Resources = resourceDictionary;
		VisualDiagnostics.RegisterSourceInfo(resourceDictionary, new Uri("Views/ChangeTimeZoneView.xaml", UriKind.RelativeOrAbsolute), 16, 10);
		onPlatform.iOS = new Thickness(20.0, 10.0, 20.0, 10.0);
		onPlatform.Android = new Thickness(20.0, 10.0, 20.0, 10.0);
		changeTimeZoneView.SetValue(Page.PaddingProperty, (Thickness)onPlatform);
		VisualDiagnostics.RegisterSourceInfo(onPlatform, new Uri("Views/ChangeTimeZoneView.xaml", UriKind.RelativeOrAbsolute), 27, 10);
		grid2.SetValue(View.VerticalOptionsProperty, LayoutOptions.FillAndExpand);
		rowDefinition.SetValue(RowDefinition.HeightProperty, new GridLengthTypeConverter().ConvertFromInvariantString("Auto"));
		((DefinitionCollection<RowDefinition>)grid2.GetValue(Grid.RowDefinitionsProperty)).Add(rowDefinition);
		rowDefinition2.SetValue(RowDefinition.HeightProperty, new GridLengthTypeConverter().ConvertFromInvariantString("10"));
		((DefinitionCollection<RowDefinition>)grid2.GetValue(Grid.RowDefinitionsProperty)).Add(rowDefinition2);
		rowDefinition3.SetValue(RowDefinition.HeightProperty, new GridLengthTypeConverter().ConvertFromInvariantString("Auto"));
		((DefinitionCollection<RowDefinition>)grid2.GetValue(Grid.RowDefinitionsProperty)).Add(rowDefinition3);
		rowDefinition4.SetValue(RowDefinition.HeightProperty, new GridLengthTypeConverter().ConvertFromInvariantString("Auto"));
		((DefinitionCollection<RowDefinition>)grid2.GetValue(Grid.RowDefinitionsProperty)).Add(rowDefinition4);
		rowDefinition5.SetValue(RowDefinition.HeightProperty, new GridLengthTypeConverter().ConvertFromInvariantString("Auto"));
		((DefinitionCollection<RowDefinition>)grid2.GetValue(Grid.RowDefinitionsProperty)).Add(rowDefinition5);
		((DefinitionCollection<RowDefinition>)grid2.GetValue(Grid.RowDefinitionsProperty)).Add(item);
		label.SetValue(Grid.RowProperty, 0);
		bindingExtension.StringFormat = "{0:MM/d(ddd) HH:mm}";
		bindingExtension.Path = "MeasurementResult.RegistDate";
		BindingBase binding = ((IMarkupExtension<BindingBase>)bindingExtension).ProvideValue((IServiceProvider)null);
		label.SetBinding(Label.TextProperty, binding);
		BindableProperty fontSizeProperty = Label.FontSizeProperty;
		FontSizeConverter fontSizeConverter = new FontSizeConverter();
		XamlServiceProvider xamlServiceProvider = new XamlServiceProvider();
		Type typeFromHandle = typeof(IProvideValueTarget);
		object[] array = new object[0 + 3];
		array[0] = label;
		array[1] = grid2;
		array[2] = changeTimeZoneView;
		object service;
		xamlServiceProvider.Add(typeFromHandle, service = new SimpleValueTargetProvider(array, Label.FontSizeProperty, nameScope));
		xamlServiceProvider.Add(typeof(IReferenceProvider), service);
		Type typeFromHandle2 = typeof(IXamlTypeResolver);
		XmlNamespaceResolver xmlNamespaceResolver = new XmlNamespaceResolver();
		xmlNamespaceResolver.Add("", "http://xamarin.com/schemas/2014/forms");
		xmlNamespaceResolver.Add("x", "http://schemas.microsoft.com/winfx/2009/xaml");
		xmlNamespaceResolver.Add("calx", "clr-namespace:Caliburn.Micro.Xamarin.Forms;assembly=Caliburn.Micro.Platform.Xamarin.Forms");
		xmlNamespaceResolver.Add("carousel", "clr-namespace:CarouselView.FormsPlugin.Abstractions;assembly=CarouselView.FormsPlugin.Abstractions");
		xmlNamespaceResolver.Add("converter", "clr-namespace:NHL.Views.Converters");
		xmlNamespaceResolver.Add("effect", "clr-namespace:NHL.Views.Effect");
		xmlNamespaceResolver.Add("nhl", "clr-namespace:NHL.Views.Controls");
		xmlNamespaceResolver.Add("renderer", "clr-namespace:NHL.Views.Renderer");
		xamlServiceProvider.Add(typeFromHandle2, new XamlTypeResolver(xmlNamespaceResolver, typeof(ChangeTimeZoneView).GetTypeInfo().Assembly));
		xamlServiceProvider.Add(typeof(IXmlLineInfoProvider), new XmlLineInfoProvider(new XmlLineInfo(42, 113)));
		label.SetValue(fontSizeProperty, ((IExtendedTypeConverter)fontSizeConverter).ConvertFromInvariantString("25", (IServiceProvider)xamlServiceProvider));
		fixedFontSizeLabelEffect.FixedSize = 18;
		label.Effects.Add(fixedFontSizeLabelEffect);
		VisualDiagnostics.RegisterSourceInfo(fixedFontSizeLabelEffect, new Uri("Views/ChangeTimeZoneView.xaml", UriKind.RelativeOrAbsolute), 44, 18);
		grid2.Children.Add(label);
		VisualDiagnostics.RegisterSourceInfo(label, new Uri("Views/ChangeTimeZoneView.xaml", UriKind.RelativeOrAbsolute), 42, 10);
		grid.SetValue(Grid.RowProperty, 2);
		columnDefinition.SetValue(ColumnDefinition.WidthProperty, new GridLengthTypeConverter().ConvertFromInvariantString("Auto"));
		((DefinitionCollection<ColumnDefinition>)grid.GetValue(Grid.ColumnDefinitionsProperty)).Add(columnDefinition);
		((DefinitionCollection<ColumnDefinition>)grid.GetValue(Grid.ColumnDefinitionsProperty)).Add(item2);
		columnDefinition2.SetValue(ColumnDefinition.WidthProperty, new GridLengthTypeConverter().ConvertFromInvariantString("Auto"));
		((DefinitionCollection<ColumnDefinition>)grid.GetValue(Grid.ColumnDefinitionsProperty)).Add(columnDefinition2);
		label2.SetValue(Grid.ColumnProperty, 2);
		bindingExtension2.Path = "MeasurementResult.DisplayMeasurementValue";
		BindingBase binding2 = ((IMarkupExtension<BindingBase>)bindingExtension2).ProvideValue((IServiceProvider)null);
		label2.SetBinding(Label.TextProperty, binding2);
		BindableProperty fontSizeProperty2 = Label.FontSizeProperty;
		FontSizeConverter fontSizeConverter2 = new FontSizeConverter();
		XamlServiceProvider xamlServiceProvider2 = new XamlServiceProvider();
		Type typeFromHandle3 = typeof(IProvideValueTarget);
		object[] array2 = new object[0 + 4];
		array2[0] = label2;
		array2[1] = grid;
		array2[2] = grid2;
		array2[3] = changeTimeZoneView;
		object service2;
		xamlServiceProvider2.Add(typeFromHandle3, service2 = new SimpleValueTargetProvider(array2, Label.FontSizeProperty, nameScope));
		xamlServiceProvider2.Add(typeof(IReferenceProvider), service2);
		Type typeFromHandle4 = typeof(IXamlTypeResolver);
		XmlNamespaceResolver xmlNamespaceResolver2 = new XmlNamespaceResolver();
		xmlNamespaceResolver2.Add("", "http://xamarin.com/schemas/2014/forms");
		xmlNamespaceResolver2.Add("x", "http://schemas.microsoft.com/winfx/2009/xaml");
		xmlNamespaceResolver2.Add("calx", "clr-namespace:Caliburn.Micro.Xamarin.Forms;assembly=Caliburn.Micro.Platform.Xamarin.Forms");
		xmlNamespaceResolver2.Add("carousel", "clr-namespace:CarouselView.FormsPlugin.Abstractions;assembly=CarouselView.FormsPlugin.Abstractions");
		xmlNamespaceResolver2.Add("converter", "clr-namespace:NHL.Views.Converters");
		xmlNamespaceResolver2.Add("effect", "clr-namespace:NHL.Views.Effect");
		xmlNamespaceResolver2.Add("nhl", "clr-namespace:NHL.Views.Controls");
		xmlNamespaceResolver2.Add("renderer", "clr-namespace:NHL.Views.Renderer");
		xamlServiceProvider2.Add(typeFromHandle4, new XamlTypeResolver(xmlNamespaceResolver2, typeof(ChangeTimeZoneView).GetTypeInfo().Assembly));
		xamlServiceProvider2.Add(typeof(IXmlLineInfoProvider), new XmlLineInfoProvider(new XmlLineInfo(56, 95)));
		label2.SetValue(fontSizeProperty2, ((IExtendedTypeConverter)fontSizeConverter2).ConvertFromInvariantString("24", (IServiceProvider)xamlServiceProvider2));
		label2.SetValue(Label.VerticalTextAlignmentProperty, new TextAlignmentConverter().ConvertFromInvariantString("Center"));
		label2.SetValue(View.HorizontalOptionsProperty, LayoutOptions.End);
		fixedFontSizeLabelEffect2.FixedSize = 30;
		label2.Effects.Add(fixedFontSizeLabelEffect2);
		VisualDiagnostics.RegisterSourceInfo(fixedFontSizeLabelEffect2, new Uri("Views/ChangeTimeZoneView.xaml", UriKind.RelativeOrAbsolute), 58, 22);
		grid.Children.Add(label2);
		VisualDiagnostics.RegisterSourceInfo(label2, new Uri("Views/ChangeTimeZoneView.xaml", UriKind.RelativeOrAbsolute), 56, 14);
		image.SetValue(Grid.ColumnProperty, 0);
		image.SetValue(Image.SourceProperty, new ImageSourceConverter().ConvertFromInvariantString("icon_glucose_on"));
		image.SetValue(VisualElement.WidthRequestProperty, 70.0);
		image.SetValue(VisualElement.IsVisibleProperty, new VisibilityConverter().ConvertFromInvariantString("False"));
		bindingExtension3.Path = "MeasurementResult.DisplayCategory";
		BindingBase target = (dataTrigger.Binding = ((IMarkupExtension<BindingBase>)bindingExtension3).ProvideValue((IServiceProvider)null));
		VisualDiagnostics.RegisterSourceInfo(target, new Uri("Views/ChangeTimeZoneView.xaml", UriKind.RelativeOrAbsolute), 64, 53);
		dataTrigger.Value = "血糖";
		setter.Property = VisualElement.IsVisibleProperty;
		setter.Value = "True";
		setter.Value = new VisibilityConverter().ConvertFromInvariantString("True");
		dataTrigger.Setters.Add(setter);
		VisualDiagnostics.RegisterSourceInfo(setter, new Uri("Views/ChangeTimeZoneView.xaml", UriKind.RelativeOrAbsolute), 65, 26);
		((ICollection<TriggerBase>)image.GetValue(VisualElement.TriggersProperty)).Add((TriggerBase)dataTrigger);
		VisualDiagnostics.RegisterSourceInfo(dataTrigger, new Uri("Views/ChangeTimeZoneView.xaml", UriKind.RelativeOrAbsolute), 64, 22);
		grid.Children.Add(image);
		VisualDiagnostics.RegisterSourceInfo(image, new Uri("Views/ChangeTimeZoneView.xaml", UriKind.RelativeOrAbsolute), 62, 14);
		image2.SetValue(Grid.ColumnProperty, 0);
		image2.SetValue(Image.SourceProperty, new ImageSourceConverter().ConvertFromInvariantString("icon_temperature_on"));
		image2.SetValue(VisualElement.WidthRequestProperty, 90.0);
		image2.SetValue(VisualElement.IsVisibleProperty, new VisibilityConverter().ConvertFromInvariantString("False"));
		bindingExtension4.Path = "MeasurementResult.DisplayCategory";
		BindingBase target2 = (dataTrigger2.Binding = ((IMarkupExtension<BindingBase>)bindingExtension4).ProvideValue((IServiceProvider)null));
		VisualDiagnostics.RegisterSourceInfo(target2, new Uri("Views/ChangeTimeZoneView.xaml", UriKind.RelativeOrAbsolute), 71, 53);
		dataTrigger2.Value = "体温";
		setter2.Property = VisualElement.IsVisibleProperty;
		setter2.Value = "True";
		setter2.Value = new VisibilityConverter().ConvertFromInvariantString("True");
		dataTrigger2.Setters.Add(setter2);
		VisualDiagnostics.RegisterSourceInfo(setter2, new Uri("Views/ChangeTimeZoneView.xaml", UriKind.RelativeOrAbsolute), 72, 26);
		((ICollection<TriggerBase>)image2.GetValue(VisualElement.TriggersProperty)).Add((TriggerBase)dataTrigger2);
		VisualDiagnostics.RegisterSourceInfo(dataTrigger2, new Uri("Views/ChangeTimeZoneView.xaml", UriKind.RelativeOrAbsolute), 71, 22);
		grid.Children.Add(image2);
		VisualDiagnostics.RegisterSourceInfo(image2, new Uri("Views/ChangeTimeZoneView.xaml", UriKind.RelativeOrAbsolute), 69, 14);
		image3.SetValue(Grid.ColumnProperty, 0);
		image3.SetValue(Image.SourceProperty, new ImageSourceConverter().ConvertFromInvariantString("icon_bloodpressure_on"));
		image3.SetValue(VisualElement.WidthRequestProperty, 70.0);
		image3.SetValue(VisualElement.IsVisibleProperty, new VisibilityConverter().ConvertFromInvariantString("False"));
		bindingExtension5.Path = "MeasurementResult.DisplayCategory";
		BindingBase target3 = (dataTrigger3.Binding = ((IMarkupExtension<BindingBase>)bindingExtension5).ProvideValue((IServiceProvider)null));
		VisualDiagnostics.RegisterSourceInfo(target3, new Uri("Views/ChangeTimeZoneView.xaml", UriKind.RelativeOrAbsolute), 78, 53);
		dataTrigger3.Value = "血圧";
		setter3.Property = VisualElement.IsVisibleProperty;
		setter3.Value = "True";
		setter3.Value = new VisibilityConverter().ConvertFromInvariantString("True");
		dataTrigger3.Setters.Add(setter3);
		VisualDiagnostics.RegisterSourceInfo(setter3, new Uri("Views/ChangeTimeZoneView.xaml", UriKind.RelativeOrAbsolute), 79, 26);
		((ICollection<TriggerBase>)image3.GetValue(VisualElement.TriggersProperty)).Add((TriggerBase)dataTrigger3);
		VisualDiagnostics.RegisterSourceInfo(dataTrigger3, new Uri("Views/ChangeTimeZoneView.xaml", UriKind.RelativeOrAbsolute), 78, 22);
		grid.Children.Add(image3);
		VisualDiagnostics.RegisterSourceInfo(image3, new Uri("Views/ChangeTimeZoneView.xaml", UriKind.RelativeOrAbsolute), 76, 14);
		grid2.Children.Add(grid);
		VisualDiagnostics.RegisterSourceInfo(grid, new Uri("Views/ChangeTimeZoneView.xaml", UriKind.RelativeOrAbsolute), 48, 10);
		radiusBoxView.SetValue(Grid.RowProperty, 3);
		staticResourceExtension.Key = "InputFrameColor";
		XamlServiceProvider xamlServiceProvider3 = new XamlServiceProvider();
		Type typeFromHandle5 = typeof(IProvideValueTarget);
		object[] array3 = new object[0 + 3];
		array3[0] = radiusBoxView;
		array3[1] = grid2;
		array3[2] = changeTimeZoneView;
		object service3;
		xamlServiceProvider3.Add(typeFromHandle5, service3 = new SimpleValueTargetProvider(array3, typeof(RadiusBoxView).GetRuntimeProperty("StrokeColor"), nameScope));
		xamlServiceProvider3.Add(typeof(IReferenceProvider), service3);
		Type typeFromHandle6 = typeof(IXamlTypeResolver);
		XmlNamespaceResolver xmlNamespaceResolver3 = new XmlNamespaceResolver();
		xmlNamespaceResolver3.Add("", "http://xamarin.com/schemas/2014/forms");
		xmlNamespaceResolver3.Add("x", "http://schemas.microsoft.com/winfx/2009/xaml");
		xmlNamespaceResolver3.Add("calx", "clr-namespace:Caliburn.Micro.Xamarin.Forms;assembly=Caliburn.Micro.Platform.Xamarin.Forms");
		xmlNamespaceResolver3.Add("carousel", "clr-namespace:CarouselView.FormsPlugin.Abstractions;assembly=CarouselView.FormsPlugin.Abstractions");
		xmlNamespaceResolver3.Add("converter", "clr-namespace:NHL.Views.Converters");
		xmlNamespaceResolver3.Add("effect", "clr-namespace:NHL.Views.Effect");
		xmlNamespaceResolver3.Add("nhl", "clr-namespace:NHL.Views.Controls");
		xmlNamespaceResolver3.Add("renderer", "clr-namespace:NHL.Views.Renderer");
		xamlServiceProvider3.Add(typeFromHandle6, new XamlTypeResolver(xmlNamespaceResolver3, typeof(ChangeTimeZoneView).GetTypeInfo().Assembly));
		xamlServiceProvider3.Add(typeof(IXmlLineInfoProvider), new XmlLineInfoProvider(new XmlLineInfo(85, 46)));
		object obj = ((IMarkupExtension)staticResourceExtension).ProvideValue((IServiceProvider)xamlServiceProvider3);
		radiusBoxView.StrokeColor = (Color)obj;
		VisualDiagnostics.RegisterSourceInfo(obj, new Uri("Views/ChangeTimeZoneView.xaml", UriKind.RelativeOrAbsolute), 85, 46);
		radiusBoxView.FillColor = Color.White;
		radiusBoxView.Radius = 2f;
		radiusBoxView.LineWidth = 2;
		radiusBoxView.SetValue(View.MarginProperty, new Thickness(10.0, 10.0, 10.0, 10.0));
		bindingExtension6.Path = "FlgList";
		BindingBase binding3 = ((IMarkupExtension<BindingBase>)bindingExtension6).ProvideValue((IServiceProvider)null);
		radiusBoxView.SetBinding(VisualElement.IsVisibleProperty, binding3);
		grid2.Children.Add(radiusBoxView);
		VisualDiagnostics.RegisterSourceInfo(radiusBoxView, new Uri("Views/ChangeTimeZoneView.xaml", UriKind.RelativeOrAbsolute), 85, 10);
		picker.SetValue(Grid.RowProperty, 3);
		bindingExtension7.Path = "TimezoneList";
		BindingBase binding4 = ((IMarkupExtension<BindingBase>)bindingExtension7).ProvideValue((IServiceProvider)null);
		picker.SetBinding(Picker.ItemsSourceProperty, binding4);
		bindingExtension8.Path = "Name";
		BindingBase target4 = (picker.ItemDisplayBinding = ((IMarkupExtension<BindingBase>)bindingExtension8).ProvideValue((IServiceProvider)null));
		VisualDiagnostics.RegisterSourceInfo(target4, new Uri("Views/ChangeTimeZoneView.xaml", UriKind.RelativeOrAbsolute), 86, 67);
		bindingExtension9.Mode = BindingMode.TwoWay;
		bindingExtension9.Path = "SelectedTimeZone";
		BindingBase binding5 = ((IMarkupExtension<BindingBase>)bindingExtension9).ProvideValue((IServiceProvider)null);
		picker.SetBinding(Picker.SelectedItemProperty, binding5);
		picker.SetValue(View.MarginProperty, new Thickness(15.0, 0.0, 0.0, 0.0));
		bindingExtension10.Path = "FlgList";
		BindingBase binding6 = ((IMarkupExtension<BindingBase>)bindingExtension10).ProvideValue((IServiceProvider)null);
		picker.SetBinding(VisualElement.IsVisibleProperty, binding6);
		picker.Effects.Add(item3);
		picker.Effects.Add(item4);
		picker.Effects.Add(item5);
		grid2.Children.Add(picker);
		VisualDiagnostics.RegisterSourceInfo(picker, new Uri("Views/ChangeTimeZoneView.xaml", UriKind.RelativeOrAbsolute), 86, 10);
		radiusBoxView2.SetValue(Grid.RowProperty, 3);
		staticResourceExtension2.Key = "InputFrameColor";
		XamlServiceProvider xamlServiceProvider4 = new XamlServiceProvider();
		Type typeFromHandle7 = typeof(IProvideValueTarget);
		object[] array4 = new object[0 + 3];
		array4[0] = radiusBoxView2;
		array4[1] = grid2;
		array4[2] = changeTimeZoneView;
		object service4;
		xamlServiceProvider4.Add(typeFromHandle7, service4 = new SimpleValueTargetProvider(array4, typeof(RadiusBoxView).GetRuntimeProperty("StrokeColor"), nameScope));
		xamlServiceProvider4.Add(typeof(IReferenceProvider), service4);
		Type typeFromHandle8 = typeof(IXamlTypeResolver);
		XmlNamespaceResolver xmlNamespaceResolver4 = new XmlNamespaceResolver();
		xmlNamespaceResolver4.Add("", "http://xamarin.com/schemas/2014/forms");
		xmlNamespaceResolver4.Add("x", "http://schemas.microsoft.com/winfx/2009/xaml");
		xmlNamespaceResolver4.Add("calx", "clr-namespace:Caliburn.Micro.Xamarin.Forms;assembly=Caliburn.Micro.Platform.Xamarin.Forms");
		xmlNamespaceResolver4.Add("carousel", "clr-namespace:CarouselView.FormsPlugin.Abstractions;assembly=CarouselView.FormsPlugin.Abstractions");
		xmlNamespaceResolver4.Add("converter", "clr-namespace:NHL.Views.Converters");
		xmlNamespaceResolver4.Add("effect", "clr-namespace:NHL.Views.Effect");
		xmlNamespaceResolver4.Add("nhl", "clr-namespace:NHL.Views.Controls");
		xmlNamespaceResolver4.Add("renderer", "clr-namespace:NHL.Views.Renderer");
		xamlServiceProvider4.Add(typeFromHandle8, new XamlTypeResolver(xmlNamespaceResolver4, typeof(ChangeTimeZoneView).GetTypeInfo().Assembly));
		xamlServiceProvider4.Add(typeof(IXmlLineInfoProvider), new XmlLineInfoProvider(new XmlLineInfo(94, 46)));
		object obj2 = ((IMarkupExtension)staticResourceExtension2).ProvideValue((IServiceProvider)xamlServiceProvider4);
		radiusBoxView2.StrokeColor = (Color)obj2;
		VisualDiagnostics.RegisterSourceInfo(obj2, new Uri("Views/ChangeTimeZoneView.xaml", UriKind.RelativeOrAbsolute), 94, 46);
		radiusBoxView2.FillColor = Color.White;
		radiusBoxView2.Radius = 2f;
		radiusBoxView2.LineWidth = 2;
		radiusBoxView2.SetValue(View.MarginProperty, new Thickness(10.0, 10.0, 10.0, 10.0));
		staticResourceExtension3.Key = "BooleanSwitchConverter";
		XamlServiceProvider xamlServiceProvider5 = new XamlServiceProvider();
		Type typeFromHandle9 = typeof(IProvideValueTarget);
		object[] array5 = new object[0 + 4];
		array5[0] = bindingExtension11;
		array5[1] = radiusBoxView2;
		array5[2] = grid2;
		array5[3] = changeTimeZoneView;
		object service5;
		xamlServiceProvider5.Add(typeFromHandle9, service5 = new SimpleValueTargetProvider(array5, typeof(BindingExtension).GetRuntimeProperty("Converter"), nameScope));
		xamlServiceProvider5.Add(typeof(IReferenceProvider), service5);
		Type typeFromHandle10 = typeof(IXamlTypeResolver);
		XmlNamespaceResolver xmlNamespaceResolver5 = new XmlNamespaceResolver();
		xmlNamespaceResolver5.Add("", "http://xamarin.com/schemas/2014/forms");
		xmlNamespaceResolver5.Add("x", "http://schemas.microsoft.com/winfx/2009/xaml");
		xmlNamespaceResolver5.Add("calx", "clr-namespace:Caliburn.Micro.Xamarin.Forms;assembly=Caliburn.Micro.Platform.Xamarin.Forms");
		xmlNamespaceResolver5.Add("carousel", "clr-namespace:CarouselView.FormsPlugin.Abstractions;assembly=CarouselView.FormsPlugin.Abstractions");
		xmlNamespaceResolver5.Add("converter", "clr-namespace:NHL.Views.Converters");
		xmlNamespaceResolver5.Add("effect", "clr-namespace:NHL.Views.Effect");
		xmlNamespaceResolver5.Add("nhl", "clr-namespace:NHL.Views.Controls");
		xmlNamespaceResolver5.Add("renderer", "clr-namespace:NHL.Views.Renderer");
		xamlServiceProvider5.Add(typeFromHandle10, new XamlTypeResolver(xmlNamespaceResolver5, typeof(ChangeTimeZoneView).GetTypeInfo().Assembly));
		xamlServiceProvider5.Add(typeof(IXmlLineInfoProvider), new XmlLineInfoProvider(new XmlLineInfo(94, 157)));
		object target5 = (bindingExtension11.Converter = (IValueConverter)((IMarkupExtension)staticResourceExtension3).ProvideValue((IServiceProvider)xamlServiceProvider5));
		VisualDiagnostics.RegisterSourceInfo(target5, new Uri("Views/ChangeTimeZoneView.xaml", UriKind.RelativeOrAbsolute), 94, 157);
		bindingExtension11.Path = "FlgList";
		BindingBase binding7 = ((IMarkupExtension<BindingBase>)bindingExtension11).ProvideValue((IServiceProvider)null);
		radiusBoxView2.SetBinding(VisualElement.IsVisibleProperty, binding7);
		grid2.Children.Add(radiusBoxView2);
		VisualDiagnostics.RegisterSourceInfo(radiusBoxView2, new Uri("Views/ChangeTimeZoneView.xaml", UriKind.RelativeOrAbsolute), 94, 10);
		picker2.SetValue(Grid.RowProperty, 3);
		bindingExtension12.Path = "TimezoneOtherList";
		BindingBase binding8 = ((IMarkupExtension<BindingBase>)bindingExtension12).ProvideValue((IServiceProvider)null);
		picker2.SetBinding(Picker.ItemsSourceProperty, binding8);
		bindingExtension13.Path = "Name";
		BindingBase target6 = (picker2.ItemDisplayBinding = ((IMarkupExtension<BindingBase>)bindingExtension13).ProvideValue((IServiceProvider)null));
		VisualDiagnostics.RegisterSourceInfo(target6, new Uri("Views/ChangeTimeZoneView.xaml", UriKind.RelativeOrAbsolute), 95, 72);
		bindingExtension14.Mode = BindingMode.TwoWay;
		bindingExtension14.Path = "SelectedTimeZoneOther";
		BindingBase binding9 = ((IMarkupExtension<BindingBase>)bindingExtension14).ProvideValue((IServiceProvider)null);
		picker2.SetBinding(Picker.SelectedItemProperty, binding9);
		picker2.SetValue(View.MarginProperty, new Thickness(15.0, 0.0, 0.0, 0.0));
		staticResourceExtension4.Key = "BooleanSwitchConverter";
		XamlServiceProvider xamlServiceProvider6 = new XamlServiceProvider();
		Type typeFromHandle11 = typeof(IProvideValueTarget);
		object[] array6 = new object[0 + 4];
		array6[0] = bindingExtension15;
		array6[1] = picker2;
		array6[2] = grid2;
		array6[3] = changeTimeZoneView;
		object service6;
		xamlServiceProvider6.Add(typeFromHandle11, service6 = new SimpleValueTargetProvider(array6, typeof(BindingExtension).GetRuntimeProperty("Converter"), nameScope));
		xamlServiceProvider6.Add(typeof(IReferenceProvider), service6);
		Type typeFromHandle12 = typeof(IXamlTypeResolver);
		XmlNamespaceResolver xmlNamespaceResolver6 = new XmlNamespaceResolver();
		xmlNamespaceResolver6.Add("", "http://xamarin.com/schemas/2014/forms");
		xmlNamespaceResolver6.Add("x", "http://schemas.microsoft.com/winfx/2009/xaml");
		xmlNamespaceResolver6.Add("calx", "clr-namespace:Caliburn.Micro.Xamarin.Forms;assembly=Caliburn.Micro.Platform.Xamarin.Forms");
		xmlNamespaceResolver6.Add("carousel", "clr-namespace:CarouselView.FormsPlugin.Abstractions;assembly=CarouselView.FormsPlugin.Abstractions");
		xmlNamespaceResolver6.Add("converter", "clr-namespace:NHL.Views.Converters");
		xmlNamespaceResolver6.Add("effect", "clr-namespace:NHL.Views.Effect");
		xmlNamespaceResolver6.Add("nhl", "clr-namespace:NHL.Views.Controls");
		xmlNamespaceResolver6.Add("renderer", "clr-namespace:NHL.Views.Renderer");
		xamlServiceProvider6.Add(typeFromHandle12, new XamlTypeResolver(xmlNamespaceResolver6, typeof(ChangeTimeZoneView).GetTypeInfo().Assembly));
		xamlServiceProvider6.Add(typeof(IXmlLineInfoProvider), new XmlLineInfoProvider(new XmlLineInfo(95, 186)));
		object target7 = (bindingExtension15.Converter = (IValueConverter)((IMarkupExtension)staticResourceExtension4).ProvideValue((IServiceProvider)xamlServiceProvider6));
		VisualDiagnostics.RegisterSourceInfo(target7, new Uri("Views/ChangeTimeZoneView.xaml", UriKind.RelativeOrAbsolute), 95, 186);
		bindingExtension15.Path = "FlgList";
		BindingBase binding10 = ((IMarkupExtension<BindingBase>)bindingExtension15).ProvideValue((IServiceProvider)null);
		picker2.SetBinding(VisualElement.IsVisibleProperty, binding10);
		picker2.Effects.Add(item6);
		picker2.Effects.Add(item7);
		picker2.Effects.Add(item8);
		grid2.Children.Add(picker2);
		VisualDiagnostics.RegisterSourceInfo(picker2, new Uri("Views/ChangeTimeZoneView.xaml", UriKind.RelativeOrAbsolute), 95, 10);
		changeTimeZoneView.SetValue(ContentPage.ContentProperty, grid2);
		VisualDiagnostics.RegisterSourceInfo(grid2, new Uri("Views/ChangeTimeZoneView.xaml", UriKind.RelativeOrAbsolute), 32, 6);
		VisualDiagnostics.RegisterSourceInfo(changeTimeZoneView, new Uri("Views/ChangeTimeZoneView.xaml", UriKind.RelativeOrAbsolute), 2, 2);
	}

	private void __InitComponentRuntime()
	{
		this.LoadFromXaml(typeof(ChangeTimeZoneView));
	}
}
