using System;
using System.CodeDom.Compiler;
using System.Reflection;
using C1.Xamarin.Forms.Chart;
using Caliburn.Micro;
using Caliburn.Micro.Xamarin.Forms;
using NHL.Models;
using NHL.Views.Effect;
using Xamarin.Forms;
using Xamarin.Forms.Internals;
using Xamarin.Forms.Xaml;
using Xamarin.Forms.Xaml.Diagnostics;
using Xamarin.Forms.Xaml.Internals;

namespace NHL.Views;

[XamlCompilation(XamlCompilationOptions.Compile)]
[XamlFilePath("Views/CompositionMeterChartView.xaml")]
public class CompositionMeterChartView : ContentPage
{
	[GeneratedCode("Xamarin.Forms.Build.Tasks.XamlG", "2.0.0.0")]
	private Label Dates;

	[GeneratedCode("Xamarin.Forms.Build.Tasks.XamlG", "2.0.0.0")]
	private FlexChart Chart;

	[GeneratedCode("Xamarin.Forms.Build.Tasks.XamlG", "2.0.0.0")]
	private ChartSeries WeightLine;

	[GeneratedCode("Xamarin.Forms.Build.Tasks.XamlG", "2.0.0.0")]
	private ChartSeries BmiLine;

	[GeneratedCode("Xamarin.Forms.Build.Tasks.XamlG", "2.0.0.0")]
	private ChartSeries FatPercentageLine;

	public CompositionMeterChartView()
	{
		InitializeComponent();
	}

	public void ChartView(double min, double max)
	{
		Chart.AxisY.Min = min;
		Chart.AxisY.Max = max;
	}

	public BindableCollection<ChartSettingModel> ChartVisible(BindableCollection<ChartSettingModel> chartSettings)
	{
		if (chartSettings == null || chartSettings.Count < 1)
		{
			chartSettings = new BindableCollection<ChartSettingModel>();
			string[] array = new string[3] { "体重", "BMI", "体脂肪率" };
			foreach (string setting in array)
			{
				ChartSettingModel item = new ChartSettingModel
				{
					Setting = setting,
					Active = true
				};
				chartSettings.Add(item);
			}
			return chartSettings;
		}
		foreach (ChartSettingModel chartSetting in chartSettings)
		{
			ChartSeriesVisibilityType visibility = ((!chartSetting.Active) ? ChartSeriesVisibilityType.Hidden : ChartSeriesVisibilityType.Visible);
			switch (chartSetting.Setting)
			{
			case "体重":
				WeightLine.Visibility = visibility;
				break;
			case "BMI":
				BmiLine.Visibility = visibility;
				break;
			case "体脂肪率":
				FatPercentageLine.Visibility = visibility;
				break;
			}
		}
		return chartSettings;
	}

	[GeneratedCode("Xamarin.Forms.Build.Tasks.XamlG", "2.0.0.0")]
	private void InitializeComponent()
	{
		if (ResourceLoader.CanProvideContentFor(new ResourceLoader.ResourceLoadingQuery
		{
			AssemblyName = typeof(CompositionMeterChartView).GetTypeInfo().Assembly.GetName(),
			ResourcePath = "Views/CompositionMeterChartView.xaml",
			Instance = this
		}))
		{
			__InitComponentRuntime();
			return;
		}
		if (XamlLoader.XamlFileProvider != null && XamlLoader.XamlFileProvider(GetType()) != null)
		{
			__InitComponentRuntime();
			return;
		}
		RowDefinition rowDefinition = new RowDefinition();
		RowDefinition rowDefinition2 = new RowDefinition();
		RowDefinition rowDefinition3 = new RowDefinition();
		RowDefinition rowDefinition4 = new RowDefinition();
		RowDefinition rowDefinition5 = new RowDefinition();
		RowDefinition rowDefinition6 = new RowDefinition();
		RowDefinition rowDefinition7 = new RowDefinition();
		RowDefinition rowDefinition8 = new RowDefinition();
		RowDefinition rowDefinition9 = new RowDefinition();
		ColumnDefinition item = new ColumnDefinition();
		ColumnDefinition item2 = new ColumnDefinition();
		ColumnDefinition item3 = new ColumnDefinition();
		ColumnDefinition item4 = new ColumnDefinition();
		ColumnDefinition item5 = new ColumnDefinition();
		ColumnDefinition item6 = new ColumnDefinition();
		BindingExtension bindingExtension = new BindingExtension();
		FixedFontSizeLabelEffect fixedFontSizeLabelEffect = new FixedFontSizeLabelEffect();
		Label label = new Label();
		Grid grid = new Grid();
		FixedFontSizeButtonEffect fixedFontSizeButtonEffect = new FixedFontSizeButtonEffect();
		Button button = new Button();
		BindingExtension bindingExtension2 = new BindingExtension();
		ChartStyle chartStyle = new ChartStyle();
		ChartAxis chartAxis = new ChartAxis();
		ChartStyle chartStyle2 = new ChartStyle();
		ChartAxis chartAxis2 = new ChartAxis();
		ChartOptions chartOptions = new ChartOptions();
		ChartStyle chartStyle3 = new ChartStyle();
		ChartSeries chartSeries = new ChartSeries();
		ChartStyle chartStyle4 = new ChartStyle();
		ChartSeries chartSeries2 = new ChartSeries();
		ChartStyle chartStyle5 = new ChartStyle();
		ChartSeries chartSeries3 = new ChartSeries();
		ChartStyle chartStyle6 = new ChartStyle();
		ChartSeries chartSeries4 = new ChartSeries();
		FlexChart flexChart = new FlexChart();
		FixedFontSizeLabelEffect fixedFontSizeLabelEffect2 = new FixedFontSizeLabelEffect();
		Label label2 = new Label();
		Grid grid2 = new Grid();
		Grid grid3 = new Grid();
		FixedFontSizeLabelEffect fixedFontSizeLabelEffect3 = new FixedFontSizeLabelEffect();
		Label label3 = new Label();
		Grid grid4 = new Grid();
		BindingExtension bindingExtension3 = new BindingExtension();
		FixedFontSizeLabelEffect fixedFontSizeLabelEffect4 = new FixedFontSizeLabelEffect();
		Label label4 = new Label();
		Grid grid5 = new Grid();
		FixedFontSizeLabelEffect fixedFontSizeLabelEffect5 = new FixedFontSizeLabelEffect();
		Label label5 = new Label();
		Grid grid6 = new Grid();
		FixedFontSizeLabelEffect fixedFontSizeLabelEffect6 = new FixedFontSizeLabelEffect();
		Label label6 = new Label();
		Grid grid7 = new Grid();
		BindingExtension bindingExtension4 = new BindingExtension();
		FixedFontSizeLabelEffect fixedFontSizeLabelEffect7 = new FixedFontSizeLabelEffect();
		Label label7 = new Label();
		Grid grid8 = new Grid();
		FixedFontSizeLabelEffect fixedFontSizeLabelEffect8 = new FixedFontSizeLabelEffect();
		Label label8 = new Label();
		Grid grid9 = new Grid();
		FixedFontSizeLabelEffect fixedFontSizeLabelEffect9 = new FixedFontSizeLabelEffect();
		Label label9 = new Label();
		Grid grid10 = new Grid();
		BindingExtension bindingExtension5 = new BindingExtension();
		FixedFontSizeLabelEffect fixedFontSizeLabelEffect10 = new FixedFontSizeLabelEffect();
		Label label10 = new Label();
		Grid grid11 = new Grid();
		FixedFontSizeLabelEffect fixedFontSizeLabelEffect11 = new FixedFontSizeLabelEffect();
		Label label11 = new Label();
		Grid grid12 = new Grid();
		FixedFontSizeButtonEffect fixedFontSizeButtonEffect2 = new FixedFontSizeButtonEffect();
		Button button2 = new Button();
		FixedFontSizeButtonEffect fixedFontSizeButtonEffect3 = new FixedFontSizeButtonEffect();
		Button button3 = new Button();
		Grid grid13 = new Grid();
		ScrollView scrollView = new ScrollView();
		Grid grid14 = new Grid();
		CompositionMeterChartView compositionMeterChartView;
		NameScope nameScope = (NameScope)(NameScope.GetNameScope(compositionMeterChartView = this) ?? new NameScope());
		NameScope.SetNameScope(compositionMeterChartView, nameScope);
		((INameScope)nameScope).RegisterName("Dates", (object)label);
		if (label.StyleId == null)
		{
			label.StyleId = "Dates";
		}
		((INameScope)nameScope).RegisterName("Chart", (object)flexChart);
		if (flexChart.StyleId == null)
		{
			flexChart.StyleId = "Chart";
		}
		((INameScope)nameScope).RegisterName("WeightLine", (object)chartSeries);
		((INameScope)nameScope).RegisterName("BmiLine", (object)chartSeries2);
		((INameScope)nameScope).RegisterName("FatPercentageLine", (object)chartSeries3);
		Dates = label;
		Chart = flexChart;
		WeightLine = chartSeries;
		BmiLine = chartSeries2;
		FatPercentageLine = chartSeries3;
		compositionMeterChartView.SetValue(NavigationPage.HasBackButtonProperty, true);
		compositionMeterChartView.SetValue(NavigationPage.BackButtonTitleProperty, "戻る");
		compositionMeterChartView.SetValue(Page.BackgroundImageProperty, "bg.png");
		compositionMeterChartView.SetValue(Page.TitleProperty, "詳細情報");
		rowDefinition.SetValue(RowDefinition.HeightProperty, new GridLengthTypeConverter().ConvertFromInvariantString("50"));
		((DefinitionCollection<RowDefinition>)grid13.GetValue(Grid.RowDefinitionsProperty)).Add(rowDefinition);
		rowDefinition2.SetValue(RowDefinition.HeightProperty, new GridLengthTypeConverter().ConvertFromInvariantString("300"));
		((DefinitionCollection<RowDefinition>)grid13.GetValue(Grid.RowDefinitionsProperty)).Add(rowDefinition2);
		rowDefinition3.SetValue(RowDefinition.HeightProperty, new GridLengthTypeConverter().ConvertFromInvariantString("Auto"));
		((DefinitionCollection<RowDefinition>)grid13.GetValue(Grid.RowDefinitionsProperty)).Add(rowDefinition3);
		rowDefinition4.SetValue(RowDefinition.HeightProperty, new GridLengthTypeConverter().ConvertFromInvariantString("Auto"));
		((DefinitionCollection<RowDefinition>)grid13.GetValue(Grid.RowDefinitionsProperty)).Add(rowDefinition4);
		rowDefinition5.SetValue(RowDefinition.HeightProperty, new GridLengthTypeConverter().ConvertFromInvariantString("Auto"));
		((DefinitionCollection<RowDefinition>)grid13.GetValue(Grid.RowDefinitionsProperty)).Add(rowDefinition5);
		rowDefinition6.SetValue(RowDefinition.HeightProperty, new GridLengthTypeConverter().ConvertFromInvariantString("Auto"));
		((DefinitionCollection<RowDefinition>)grid13.GetValue(Grid.RowDefinitionsProperty)).Add(rowDefinition6);
		rowDefinition7.SetValue(RowDefinition.HeightProperty, new GridLengthTypeConverter().ConvertFromInvariantString("Auto"));
		((DefinitionCollection<RowDefinition>)grid13.GetValue(Grid.RowDefinitionsProperty)).Add(rowDefinition7);
		rowDefinition8.SetValue(RowDefinition.HeightProperty, new GridLengthTypeConverter().ConvertFromInvariantString("Auto"));
		((DefinitionCollection<RowDefinition>)grid13.GetValue(Grid.RowDefinitionsProperty)).Add(rowDefinition8);
		rowDefinition9.SetValue(RowDefinition.HeightProperty, new GridLengthTypeConverter().ConvertFromInvariantString("Auto"));
		((DefinitionCollection<RowDefinition>)grid13.GetValue(Grid.RowDefinitionsProperty)).Add(rowDefinition9);
		((DefinitionCollection<ColumnDefinition>)grid13.GetValue(Grid.ColumnDefinitionsProperty)).Add(item);
		((DefinitionCollection<ColumnDefinition>)grid13.GetValue(Grid.ColumnDefinitionsProperty)).Add(item2);
		((DefinitionCollection<ColumnDefinition>)grid13.GetValue(Grid.ColumnDefinitionsProperty)).Add(item3);
		((DefinitionCollection<ColumnDefinition>)grid13.GetValue(Grid.ColumnDefinitionsProperty)).Add(item4);
		((DefinitionCollection<ColumnDefinition>)grid13.GetValue(Grid.ColumnDefinitionsProperty)).Add(item5);
		((DefinitionCollection<ColumnDefinition>)grid13.GetValue(Grid.ColumnDefinitionsProperty)).Add(item6);
		grid.SetValue(Grid.RowProperty, 0);
		grid.SetValue(Grid.ColumnSpanProperty, 5);
		bindingExtension.Path = "DisplaySelectedDates";
		BindingBase binding = ((IMarkupExtension<BindingBase>)bindingExtension).ProvideValue((IServiceProvider)null);
		label.SetBinding(Label.TextProperty, binding);
		label.SetValue(Label.FontAttributesProperty, new FontAttributesConverter().ConvertFromInvariantString("Bold"));
		label.SetValue(Label.TextColorProperty, Color.Blue);
		BindableProperty fontSizeProperty = Label.FontSizeProperty;
		FontSizeConverter fontSizeConverter = new FontSizeConverter();
		XamlServiceProvider xamlServiceProvider = new XamlServiceProvider();
		Type typeFromHandle = typeof(IProvideValueTarget);
		object[] array = new object[0 + 6];
		array[0] = label;
		array[1] = grid;
		array[2] = grid13;
		array[3] = scrollView;
		array[4] = grid14;
		array[5] = compositionMeterChartView;
		object service;
		xamlServiceProvider.Add(typeFromHandle, service = new SimpleValueTargetProvider(array, Label.FontSizeProperty, nameScope));
		xamlServiceProvider.Add(typeof(IReferenceProvider), service);
		Type typeFromHandle2 = typeof(IXamlTypeResolver);
		XmlNamespaceResolver xmlNamespaceResolver = new XmlNamespaceResolver();
		xmlNamespaceResolver.Add("", "http://xamarin.com/schemas/2014/forms");
		xmlNamespaceResolver.Add("x", "http://schemas.microsoft.com/winfx/2009/xaml");
		xmlNamespaceResolver.Add("calx", "clr-namespace:Caliburn.Micro.Xamarin.Forms;assembly=Caliburn.Micro.Platform.Xamarin.Forms");
		xmlNamespaceResolver.Add("effect", "clr-namespace:NHL.Views.Effect");
		xmlNamespaceResolver.Add("c1", "clr-namespace:C1.Xamarin.Forms.Chart;assembly=C1.Xamarin.Forms.Chart");
		xamlServiceProvider.Add(typeFromHandle2, new XamlTypeResolver(xmlNamespaceResolver, typeof(CompositionMeterChartView).GetTypeInfo().Assembly));
		xamlServiceProvider.Add(typeof(IXmlLineInfoProvider), new XmlLineInfoProvider(new XmlLineInfo(39, 120)));
		label.SetValue(fontSizeProperty, ((IExtendedTypeConverter)fontSizeConverter).ConvertFromInvariantString("20", (IServiceProvider)xamlServiceProvider));
		label.SetValue(Xamarin.Forms.View.VerticalOptionsProperty, LayoutOptions.CenterAndExpand);
		label.SetValue(Xamarin.Forms.View.HorizontalOptionsProperty, LayoutOptions.CenterAndExpand);
		label.Effects.Add(fixedFontSizeLabelEffect);
		VisualDiagnostics.RegisterSourceInfo(fixedFontSizeLabelEffect, new Uri("Views/CompositionMeterChartView.xaml", UriKind.RelativeOrAbsolute), 41, 30);
		grid.Children.Add(label);
		VisualDiagnostics.RegisterSourceInfo(label, new Uri("Views/CompositionMeterChartView.xaml", UriKind.RelativeOrAbsolute), 39, 22);
		grid13.Children.Add(grid);
		VisualDiagnostics.RegisterSourceInfo(grid, new Uri("Views/CompositionMeterChartView.xaml", UriKind.RelativeOrAbsolute), 38, 18);
		button.SetValue(Message.AttachProperty, "OnCalendarTapped");
		button.SetValue(Grid.RowProperty, 0);
		button.SetValue(Grid.ColumnProperty, 5);
		button.SetValue(Button.TextProperty, "選択");
		button.SetValue(Button.FontAttributesProperty, new FontAttributesConverter().ConvertFromInvariantString("Bold"));
		button.SetValue(Button.TextColorProperty, Color.Blue);
		BindableProperty fontSizeProperty2 = Button.FontSizeProperty;
		FontSizeConverter fontSizeConverter2 = new FontSizeConverter();
		XamlServiceProvider xamlServiceProvider2 = new XamlServiceProvider();
		Type typeFromHandle3 = typeof(IProvideValueTarget);
		object[] array2 = new object[0 + 5];
		array2[0] = button;
		array2[1] = grid13;
		array2[2] = scrollView;
		array2[3] = grid14;
		array2[4] = compositionMeterChartView;
		object service2;
		xamlServiceProvider2.Add(typeFromHandle3, service2 = new SimpleValueTargetProvider(array2, Button.FontSizeProperty, nameScope));
		xamlServiceProvider2.Add(typeof(IReferenceProvider), service2);
		Type typeFromHandle4 = typeof(IXamlTypeResolver);
		XmlNamespaceResolver xmlNamespaceResolver2 = new XmlNamespaceResolver();
		xmlNamespaceResolver2.Add("", "http://xamarin.com/schemas/2014/forms");
		xmlNamespaceResolver2.Add("x", "http://schemas.microsoft.com/winfx/2009/xaml");
		xmlNamespaceResolver2.Add("calx", "clr-namespace:Caliburn.Micro.Xamarin.Forms;assembly=Caliburn.Micro.Platform.Xamarin.Forms");
		xmlNamespaceResolver2.Add("effect", "clr-namespace:NHL.Views.Effect");
		xmlNamespaceResolver2.Add("c1", "clr-namespace:C1.Xamarin.Forms.Chart;assembly=C1.Xamarin.Forms.Chart");
		xamlServiceProvider2.Add(typeFromHandle4, new XamlTypeResolver(xmlNamespaceResolver2, typeof(CompositionMeterChartView).GetTypeInfo().Assembly));
		xamlServiceProvider2.Add(typeof(IXmlLineInfoProvider), new XmlLineInfoProvider(new XmlLineInfo(47, 142)));
		button.SetValue(fontSizeProperty2, ((IExtendedTypeConverter)fontSizeConverter2).ConvertFromInvariantString("12", (IServiceProvider)xamlServiceProvider2));
		button.SetValue(VisualElement.BackgroundColorProperty, Color.Transparent);
		button.SetValue(Xamarin.Forms.View.VerticalOptionsProperty, LayoutOptions.CenterAndExpand);
		button.SetValue(Xamarin.Forms.View.HorizontalOptionsProperty, LayoutOptions.EndAndExpand);
		button.Effects.Add(fixedFontSizeButtonEffect);
		VisualDiagnostics.RegisterSourceInfo(fixedFontSizeButtonEffect, new Uri("Views/CompositionMeterChartView.xaml", UriKind.RelativeOrAbsolute), 49, 26);
		grid13.Children.Add(button);
		VisualDiagnostics.RegisterSourceInfo(button, new Uri("Views/CompositionMeterChartView.xaml", UriKind.RelativeOrAbsolute), 47, 18);
		flexChart.SetValue(Grid.RowProperty, 1);
		flexChart.SetValue(Grid.ColumnProperty, 0);
		flexChart.SetValue(Grid.ColumnSpanProperty, 6);
		flexChart.SetValue(VisualElement.BackgroundColorProperty, Color.White);
		flexChart.SetValue(Xamarin.Forms.View.MarginProperty, new Thickness(3.0, 3.0, 3.0, 3.0));
		flexChart.SetValue(Xamarin.Forms.View.HorizontalOptionsProperty, LayoutOptions.FillAndExpand);
		flexChart.SetValue(Xamarin.Forms.View.VerticalOptionsProperty, LayoutOptions.FillAndExpand);
		flexChart.SetValue(ChartBase.LegendPositionProperty, ChartPositionType.Bottom);
		bindingExtension2.Path = "DisplayCompChartData";
		BindingBase binding2 = ((IMarkupExtension<BindingBase>)bindingExtension2).ProvideValue((IServiceProvider)null);
		flexChart.SetBinding(ChartBase.ItemsSourceProperty, binding2);
		flexChart.SetValue(FlexChart.BindingXProperty, "Date");
		chartAxis.SetValue(ChartAxis.TitleProperty, "測定値");
		chartAxis.SetValue(ChartAxis.AxisLineProperty, true);
		chartAxis.SetValue(ChartAxis.MajorTickMarksProperty, ChartTickMarkType.Outside);
		chartAxis.SetValue(ChartAxis.MajorUnitProperty, 2.0);
		chartAxis.SetValue(ChartAxis.MajorGridProperty, true);
		chartStyle.SetValue(ChartStyle.FontSizeProperty, 13.0);
		chartAxis.SetValue(ChartAxis.StyleProperty, chartStyle);
		VisualDiagnostics.RegisterSourceInfo(chartStyle, new Uri("Views/CompositionMeterChartView.xaml", UriKind.RelativeOrAbsolute), 59, 34);
		flexChart.AxisY = chartAxis;
		VisualDiagnostics.RegisterSourceInfo(chartAxis, new Uri("Views/CompositionMeterChartView.xaml", UriKind.RelativeOrAbsolute), 57, 26);
		chartAxis2.SetValue(ChartAxis.TitleProperty, "測定日");
		chartAxis2.SetValue(ChartAxis.AxisLineProperty, true);
		chartAxis2.SetValue(ChartAxis.MajorGridProperty, true);
		chartStyle2.SetValue(ChartStyle.FontSizeProperty, 13.0);
		chartAxis2.SetValue(ChartAxis.StyleProperty, chartStyle2);
		VisualDiagnostics.RegisterSourceInfo(chartStyle2, new Uri("Views/CompositionMeterChartView.xaml", UriKind.RelativeOrAbsolute), 66, 34);
		flexChart.AxisX = chartAxis2;
		VisualDiagnostics.RegisterSourceInfo(chartAxis2, new Uri("Views/CompositionMeterChartView.xaml", UriKind.RelativeOrAbsolute), 64, 26);
		chartOptions.SetValue(ChartOptions.InterpolateNullsProperty, true);
		flexChart.SetValue(FlexChart.OptionsProperty, chartOptions);
		VisualDiagnostics.RegisterSourceInfo(chartOptions, new Uri("Views/CompositionMeterChartView.xaml", UriKind.RelativeOrAbsolute), 71, 26);
		chartSeries.SetValue(ChartSeries.SeriesNameProperty, "体重");
		chartSeries.SetValue(ChartSeries.BindingProperty, "Weight");
		chartSeries.SetValue(ChartSeries.ChartTypeProperty, new ChartType?(ChartType.LineSymbols));
		chartSeries.SetValue(ChartSeries.SymbolSizeProperty, 10);
		chartStyle3.SetValue(ChartStyle.StrokeProperty, new Color(0.9372549057006836, 0.42352941632270813, 0.0, 1.0));
		chartStyle3.SetValue(ChartStyle.FillProperty, new Color(0.9372549057006836, 0.42352941632270813, 0.0, 1.0));
		chartSeries.SetValue(ChartSeries.StyleProperty, chartStyle3);
		VisualDiagnostics.RegisterSourceInfo(chartStyle3, new Uri("Views/CompositionMeterChartView.xaml", UriKind.RelativeOrAbsolute), 77, 34);
		flexChart.Series.Add(chartSeries);
		chartSeries2.SetValue(ChartSeries.SeriesNameProperty, "BMI");
		chartSeries2.SetValue(ChartSeries.BindingProperty, "Bmi");
		chartSeries2.SetValue(ChartSeries.ChartTypeProperty, new ChartType?(ChartType.LineSymbols));
		chartSeries2.SetValue(ChartSeries.SymbolSizeProperty, 10);
		chartStyle4.SetValue(ChartStyle.StrokeProperty, new Color(0.5058823823928833, 0.7803921699523926, 0.5176470875740051, 1.0));
		chartStyle4.SetValue(ChartStyle.FillProperty, new Color(0.5058823823928833, 0.7803921699523926, 0.5176470875740051, 1.0));
		chartSeries2.SetValue(ChartSeries.StyleProperty, chartStyle4);
		VisualDiagnostics.RegisterSourceInfo(chartStyle4, new Uri("Views/CompositionMeterChartView.xaml", UriKind.RelativeOrAbsolute), 82, 34);
		flexChart.Series.Add(chartSeries2);
		chartSeries3.SetValue(ChartSeries.SeriesNameProperty, "体脂肪率");
		chartSeries3.SetValue(ChartSeries.BindingProperty, "FatPercentage");
		chartSeries3.SetValue(ChartSeries.ChartTypeProperty, new ChartType?(ChartType.LineSymbols));
		chartSeries3.SetValue(ChartSeries.SymbolSizeProperty, 10);
		chartStyle5.SetValue(ChartStyle.StrokeProperty, new Color(0.9411764740943909, 0.3843137323856354, 0.572549045085907, 1.0));
		chartStyle5.SetValue(ChartStyle.FillProperty, new Color(0.9411764740943909, 0.3843137323856354, 0.572549045085907, 1.0));
		chartSeries3.SetValue(ChartSeries.StyleProperty, chartStyle5);
		VisualDiagnostics.RegisterSourceInfo(chartStyle5, new Uri("Views/CompositionMeterChartView.xaml", UriKind.RelativeOrAbsolute), 87, 34);
		flexChart.Series.Add(chartSeries3);
		chartSeries4.SetValue(ChartSeries.BindingProperty, "DefaultValue");
		chartSeries4.SetValue(ChartSeries.ChartTypeProperty, new ChartType?(ChartType.LineSymbols));
		chartSeries4.SetValue(ChartSeries.SymbolSizeProperty, 1);
		chartStyle6.SetValue(ChartStyle.StrokeProperty, Color.Transparent);
		chartStyle6.SetValue(ChartStyle.FillProperty, Color.Transparent);
		chartSeries4.SetValue(ChartSeries.StyleProperty, chartStyle6);
		VisualDiagnostics.RegisterSourceInfo(chartStyle6, new Uri("Views/CompositionMeterChartView.xaml", UriKind.RelativeOrAbsolute), 92, 34);
		flexChart.Series.Add(chartSeries4);
		grid13.Children.Add(flexChart);
		VisualDiagnostics.RegisterSourceInfo(flexChart, new Uri("Views/CompositionMeterChartView.xaml", UriKind.RelativeOrAbsolute), 54, 18);
		grid2.SetValue(Grid.RowProperty, 2);
		grid2.SetValue(Grid.ColumnProperty, 0);
		grid2.SetValue(Grid.ColumnSpanProperty, 6);
		grid2.SetValue(Grid.RowSpacingProperty, 0.0);
		grid2.SetValue(VisualElement.BackgroundColorProperty, Color.Transparent);
		grid2.SetValue(Xamarin.Forms.View.MarginProperty, new Thickness(3.0, 3.0, 3.0, 3.0));
		label2.SetValue(Label.TextProperty, " 平均値");
		label2.SetValue(Label.TextColorProperty, Color.Blue);
		label2.SetValue(Xamarin.Forms.View.VerticalOptionsProperty, LayoutOptions.End);
		label2.SetValue(Xamarin.Forms.View.HorizontalOptionsProperty, LayoutOptions.CenterAndExpand);
		BindableProperty fontSizeProperty3 = Label.FontSizeProperty;
		FontSizeConverter fontSizeConverter3 = new FontSizeConverter();
		XamlServiceProvider xamlServiceProvider3 = new XamlServiceProvider();
		Type typeFromHandle5 = typeof(IProvideValueTarget);
		object[] array3 = new object[0 + 6];
		array3[0] = label2;
		array3[1] = grid2;
		array3[2] = grid13;
		array3[3] = scrollView;
		array3[4] = grid14;
		array3[5] = compositionMeterChartView;
		object service3;
		xamlServiceProvider3.Add(typeFromHandle5, service3 = new SimpleValueTargetProvider(array3, Label.FontSizeProperty, nameScope));
		xamlServiceProvider3.Add(typeof(IReferenceProvider), service3);
		Type typeFromHandle6 = typeof(IXamlTypeResolver);
		XmlNamespaceResolver xmlNamespaceResolver3 = new XmlNamespaceResolver();
		xmlNamespaceResolver3.Add("", "http://xamarin.com/schemas/2014/forms");
		xmlNamespaceResolver3.Add("x", "http://schemas.microsoft.com/winfx/2009/xaml");
		xmlNamespaceResolver3.Add("calx", "clr-namespace:Caliburn.Micro.Xamarin.Forms;assembly=Caliburn.Micro.Platform.Xamarin.Forms");
		xmlNamespaceResolver3.Add("effect", "clr-namespace:NHL.Views.Effect");
		xmlNamespaceResolver3.Add("c1", "clr-namespace:C1.Xamarin.Forms.Chart;assembly=C1.Xamarin.Forms.Chart");
		xamlServiceProvider3.Add(typeFromHandle6, new XamlTypeResolver(xmlNamespaceResolver3, typeof(CompositionMeterChartView).GetTypeInfo().Assembly));
		xamlServiceProvider3.Add(typeof(IXmlLineInfoProvider), new XmlLineInfoProvider(new XmlLineInfo(100, 115)));
		label2.SetValue(fontSizeProperty3, ((IExtendedTypeConverter)fontSizeConverter3).ConvertFromInvariantString("Large", (IServiceProvider)xamlServiceProvider3));
		label2.SetValue(Label.FontAttributesProperty, new FontAttributesConverter().ConvertFromInvariantString("Bold"));
		label2.SetValue(VisualElement.BackgroundColorProperty, Color.Transparent);
		label2.Effects.Add(fixedFontSizeLabelEffect2);
		VisualDiagnostics.RegisterSourceInfo(fixedFontSizeLabelEffect2, new Uri("Views/CompositionMeterChartView.xaml", UriKind.RelativeOrAbsolute), 102, 30);
		grid2.Children.Add(label2);
		VisualDiagnostics.RegisterSourceInfo(label2, new Uri("Views/CompositionMeterChartView.xaml", UriKind.RelativeOrAbsolute), 100, 22);
		grid13.Children.Add(grid2);
		VisualDiagnostics.RegisterSourceInfo(grid2, new Uri("Views/CompositionMeterChartView.xaml", UriKind.RelativeOrAbsolute), 99, 18);
		grid3.SetValue(Grid.RowProperty, 3);
		grid3.SetValue(Grid.ColumnProperty, 0);
		grid3.SetValue(Grid.RowSpanProperty, 3);
		grid3.SetValue(Grid.ColumnSpanProperty, 6);
		grid3.SetValue(VisualElement.BackgroundColorProperty, Color.White);
		grid3.SetValue(Xamarin.Forms.View.MarginProperty, new Thickness(3.0, 3.0, 3.0, 3.0));
		grid13.Children.Add(grid3);
		VisualDiagnostics.RegisterSourceInfo(grid3, new Uri("Views/CompositionMeterChartView.xaml", UriKind.RelativeOrAbsolute), 108, 18);
		grid4.SetValue(Grid.RowProperty, 3);
		grid4.SetValue(Grid.ColumnProperty, 0);
		grid4.SetValue(Grid.ColumnSpanProperty, 3);
		grid4.SetValue(VisualElement.BackgroundColorProperty, Color.Transparent);
		grid4.SetValue(Xamarin.Forms.View.MarginProperty, new Thickness(15.0, 0.0, 0.0, 0.0));
		label3.SetValue(Label.TextProperty, "体重");
		label3.SetValue(Label.TextColorProperty, Color.Blue);
		label3.SetValue(Xamarin.Forms.View.VerticalOptionsProperty, LayoutOptions.Center);
		label3.SetValue(Xamarin.Forms.View.HorizontalOptionsProperty, LayoutOptions.StartAndExpand);
		BindableProperty fontSizeProperty4 = Label.FontSizeProperty;
		FontSizeConverter fontSizeConverter4 = new FontSizeConverter();
		XamlServiceProvider xamlServiceProvider4 = new XamlServiceProvider();
		Type typeFromHandle7 = typeof(IProvideValueTarget);
		object[] array4 = new object[0 + 6];
		array4[0] = label3;
		array4[1] = grid4;
		array4[2] = grid13;
		array4[3] = scrollView;
		array4[4] = grid14;
		array4[5] = compositionMeterChartView;
		object service4;
		xamlServiceProvider4.Add(typeFromHandle7, service4 = new SimpleValueTargetProvider(array4, Label.FontSizeProperty, nameScope));
		xamlServiceProvider4.Add(typeof(IReferenceProvider), service4);
		Type typeFromHandle8 = typeof(IXamlTypeResolver);
		XmlNamespaceResolver xmlNamespaceResolver4 = new XmlNamespaceResolver();
		xmlNamespaceResolver4.Add("", "http://xamarin.com/schemas/2014/forms");
		xmlNamespaceResolver4.Add("x", "http://schemas.microsoft.com/winfx/2009/xaml");
		xmlNamespaceResolver4.Add("calx", "clr-namespace:Caliburn.Micro.Xamarin.Forms;assembly=Caliburn.Micro.Platform.Xamarin.Forms");
		xmlNamespaceResolver4.Add("effect", "clr-namespace:NHL.Views.Effect");
		xmlNamespaceResolver4.Add("c1", "clr-namespace:C1.Xamarin.Forms.Chart;assembly=C1.Xamarin.Forms.Chart");
		xamlServiceProvider4.Add(typeFromHandle8, new XamlTypeResolver(xmlNamespaceResolver4, typeof(CompositionMeterChartView).GetTypeInfo().Assembly));
		xamlServiceProvider4.Add(typeof(IXmlLineInfoProvider), new XmlLineInfoProvider(new XmlLineInfo(112, 115)));
		label3.SetValue(fontSizeProperty4, ((IExtendedTypeConverter)fontSizeConverter4).ConvertFromInvariantString("Large", (IServiceProvider)xamlServiceProvider4));
		label3.Effects.Add(fixedFontSizeLabelEffect3);
		VisualDiagnostics.RegisterSourceInfo(fixedFontSizeLabelEffect3, new Uri("Views/CompositionMeterChartView.xaml", UriKind.RelativeOrAbsolute), 114, 30);
		grid4.Children.Add(label3);
		VisualDiagnostics.RegisterSourceInfo(label3, new Uri("Views/CompositionMeterChartView.xaml", UriKind.RelativeOrAbsolute), 112, 22);
		grid13.Children.Add(grid4);
		VisualDiagnostics.RegisterSourceInfo(grid4, new Uri("Views/CompositionMeterChartView.xaml", UriKind.RelativeOrAbsolute), 111, 18);
		grid5.SetValue(Grid.RowProperty, 3);
		grid5.SetValue(Grid.ColumnProperty, 3);
		grid5.SetValue(Grid.ColumnSpanProperty, 2);
		grid5.SetValue(Grid.ColumnSpacingProperty, 0.0);
		grid5.SetValue(VisualElement.BackgroundColorProperty, Color.Transparent);
		bindingExtension3.Path = "WeightAverage";
		BindingBase binding3 = ((IMarkupExtension<BindingBase>)bindingExtension3).ProvideValue((IServiceProvider)null);
		label4.SetBinding(Label.TextProperty, binding3);
		label4.SetValue(Label.TextColorProperty, Color.Blue);
		label4.SetValue(Xamarin.Forms.View.VerticalOptionsProperty, LayoutOptions.EndAndExpand);
		label4.SetValue(Xamarin.Forms.View.HorizontalOptionsProperty, LayoutOptions.End);
		BindableProperty fontSizeProperty5 = Label.FontSizeProperty;
		FontSizeConverter fontSizeConverter5 = new FontSizeConverter();
		XamlServiceProvider xamlServiceProvider5 = new XamlServiceProvider();
		Type typeFromHandle9 = typeof(IProvideValueTarget);
		object[] array5 = new object[0 + 6];
		array5[0] = label4;
		array5[1] = grid5;
		array5[2] = grid13;
		array5[3] = scrollView;
		array5[4] = grid14;
		array5[5] = compositionMeterChartView;
		object service5;
		xamlServiceProvider5.Add(typeFromHandle9, service5 = new SimpleValueTargetProvider(array5, Label.FontSizeProperty, nameScope));
		xamlServiceProvider5.Add(typeof(IReferenceProvider), service5);
		Type typeFromHandle10 = typeof(IXamlTypeResolver);
		XmlNamespaceResolver xmlNamespaceResolver5 = new XmlNamespaceResolver();
		xmlNamespaceResolver5.Add("", "http://xamarin.com/schemas/2014/forms");
		xmlNamespaceResolver5.Add("x", "http://schemas.microsoft.com/winfx/2009/xaml");
		xmlNamespaceResolver5.Add("calx", "clr-namespace:Caliburn.Micro.Xamarin.Forms;assembly=Caliburn.Micro.Platform.Xamarin.Forms");
		xmlNamespaceResolver5.Add("effect", "clr-namespace:NHL.Views.Effect");
		xmlNamespaceResolver5.Add("c1", "clr-namespace:C1.Xamarin.Forms.Chart;assembly=C1.Xamarin.Forms.Chart");
		xamlServiceProvider5.Add(typeFromHandle10, new XamlTypeResolver(xmlNamespaceResolver5, typeof(CompositionMeterChartView).GetTypeInfo().Assembly));
		xamlServiceProvider5.Add(typeof(IXmlLineInfoProvider), new XmlLineInfoProvider(new XmlLineInfo(119, 131)));
		label4.SetValue(fontSizeProperty5, ((IExtendedTypeConverter)fontSizeConverter5).ConvertFromInvariantString("Large", (IServiceProvider)xamlServiceProvider5));
		label4.SetValue(Label.FontAttributesProperty, new FontAttributesConverter().ConvertFromInvariantString("Bold"));
		label4.Effects.Add(fixedFontSizeLabelEffect4);
		VisualDiagnostics.RegisterSourceInfo(fixedFontSizeLabelEffect4, new Uri("Views/CompositionMeterChartView.xaml", UriKind.RelativeOrAbsolute), 122, 30);
		grid5.Children.Add(label4);
		VisualDiagnostics.RegisterSourceInfo(label4, new Uri("Views/CompositionMeterChartView.xaml", UriKind.RelativeOrAbsolute), 119, 22);
		grid13.Children.Add(grid5);
		VisualDiagnostics.RegisterSourceInfo(grid5, new Uri("Views/CompositionMeterChartView.xaml", UriKind.RelativeOrAbsolute), 118, 18);
		grid6.SetValue(Grid.RowProperty, 3);
		grid6.SetValue(Grid.ColumnProperty, 5);
		grid6.SetValue(Grid.ColumnSpacingProperty, 0.0);
		grid6.SetValue(VisualElement.BackgroundColorProperty, Color.Transparent);
		grid6.SetValue(Xamarin.Forms.View.MarginProperty, new Thickness(0.0, 0.0, 5.0, 3.0));
		label5.SetValue(Label.TextProperty, "kg");
		label5.SetValue(Label.TextColorProperty, Color.Black);
		label5.SetValue(Xamarin.Forms.View.VerticalOptionsProperty, LayoutOptions.EndAndExpand);
		label5.SetValue(Xamarin.Forms.View.HorizontalOptionsProperty, LayoutOptions.Start);
		BindableProperty fontSizeProperty6 = Label.FontSizeProperty;
		FontSizeConverter fontSizeConverter6 = new FontSizeConverter();
		XamlServiceProvider xamlServiceProvider6 = new XamlServiceProvider();
		Type typeFromHandle11 = typeof(IProvideValueTarget);
		object[] array6 = new object[0 + 6];
		array6[0] = label5;
		array6[1] = grid6;
		array6[2] = grid13;
		array6[3] = scrollView;
		array6[4] = grid14;
		array6[5] = compositionMeterChartView;
		object service6;
		xamlServiceProvider6.Add(typeFromHandle11, service6 = new SimpleValueTargetProvider(array6, Label.FontSizeProperty, nameScope));
		xamlServiceProvider6.Add(typeof(IReferenceProvider), service6);
		Type typeFromHandle12 = typeof(IXamlTypeResolver);
		XmlNamespaceResolver xmlNamespaceResolver6 = new XmlNamespaceResolver();
		xmlNamespaceResolver6.Add("", "http://xamarin.com/schemas/2014/forms");
		xmlNamespaceResolver6.Add("x", "http://schemas.microsoft.com/winfx/2009/xaml");
		xmlNamespaceResolver6.Add("calx", "clr-namespace:Caliburn.Micro.Xamarin.Forms;assembly=Caliburn.Micro.Platform.Xamarin.Forms");
		xmlNamespaceResolver6.Add("effect", "clr-namespace:NHL.Views.Effect");
		xmlNamespaceResolver6.Add("c1", "clr-namespace:C1.Xamarin.Forms.Chart;assembly=C1.Xamarin.Forms.Chart");
		xamlServiceProvider6.Add(typeFromHandle12, new XamlTypeResolver(xmlNamespaceResolver6, typeof(CompositionMeterChartView).GetTypeInfo().Assembly));
		xamlServiceProvider6.Add(typeof(IXmlLineInfoProvider), new XmlLineInfoProvider(new XmlLineInfo(127, 113)));
		label5.SetValue(fontSizeProperty6, ((IExtendedTypeConverter)fontSizeConverter6).ConvertFromInvariantString("Default", (IServiceProvider)xamlServiceProvider6));
		label5.SetValue(Label.FontAttributesProperty, new FontAttributesConverter().ConvertFromInvariantString("Bold"));
		label5.Effects.Add(fixedFontSizeLabelEffect5);
		VisualDiagnostics.RegisterSourceInfo(fixedFontSizeLabelEffect5, new Uri("Views/CompositionMeterChartView.xaml", UriKind.RelativeOrAbsolute), 129, 30);
		grid6.Children.Add(label5);
		VisualDiagnostics.RegisterSourceInfo(label5, new Uri("Views/CompositionMeterChartView.xaml", UriKind.RelativeOrAbsolute), 127, 22);
		grid13.Children.Add(grid6);
		VisualDiagnostics.RegisterSourceInfo(grid6, new Uri("Views/CompositionMeterChartView.xaml", UriKind.RelativeOrAbsolute), 126, 18);
		grid7.SetValue(Grid.RowProperty, 4);
		grid7.SetValue(Grid.ColumnProperty, 0);
		grid7.SetValue(Grid.ColumnSpanProperty, 3);
		grid7.SetValue(VisualElement.BackgroundColorProperty, Color.Transparent);
		grid7.SetValue(Xamarin.Forms.View.MarginProperty, new Thickness(15.0, 0.0, 0.0, 0.0));
		label6.SetValue(Label.TextProperty, "BMI");
		label6.SetValue(Label.TextColorProperty, Color.Blue);
		label6.SetValue(Xamarin.Forms.View.VerticalOptionsProperty, LayoutOptions.Center);
		label6.SetValue(Xamarin.Forms.View.HorizontalOptionsProperty, LayoutOptions.StartAndExpand);
		BindableProperty fontSizeProperty7 = Label.FontSizeProperty;
		FontSizeConverter fontSizeConverter7 = new FontSizeConverter();
		XamlServiceProvider xamlServiceProvider7 = new XamlServiceProvider();
		Type typeFromHandle13 = typeof(IProvideValueTarget);
		object[] array7 = new object[0 + 6];
		array7[0] = label6;
		array7[1] = grid7;
		array7[2] = grid13;
		array7[3] = scrollView;
		array7[4] = grid14;
		array7[5] = compositionMeterChartView;
		object service7;
		xamlServiceProvider7.Add(typeFromHandle13, service7 = new SimpleValueTargetProvider(array7, Label.FontSizeProperty, nameScope));
		xamlServiceProvider7.Add(typeof(IReferenceProvider), service7);
		Type typeFromHandle14 = typeof(IXamlTypeResolver);
		XmlNamespaceResolver xmlNamespaceResolver7 = new XmlNamespaceResolver();
		xmlNamespaceResolver7.Add("", "http://xamarin.com/schemas/2014/forms");
		xmlNamespaceResolver7.Add("x", "http://schemas.microsoft.com/winfx/2009/xaml");
		xmlNamespaceResolver7.Add("calx", "clr-namespace:Caliburn.Micro.Xamarin.Forms;assembly=Caliburn.Micro.Platform.Xamarin.Forms");
		xmlNamespaceResolver7.Add("effect", "clr-namespace:NHL.Views.Effect");
		xmlNamespaceResolver7.Add("c1", "clr-namespace:C1.Xamarin.Forms.Chart;assembly=C1.Xamarin.Forms.Chart");
		xamlServiceProvider7.Add(typeFromHandle14, new XamlTypeResolver(xmlNamespaceResolver7, typeof(CompositionMeterChartView).GetTypeInfo().Assembly));
		xamlServiceProvider7.Add(typeof(IXmlLineInfoProvider), new XmlLineInfoProvider(new XmlLineInfo(136, 116)));
		label6.SetValue(fontSizeProperty7, ((IExtendedTypeConverter)fontSizeConverter7).ConvertFromInvariantString("Large", (IServiceProvider)xamlServiceProvider7));
		label6.Effects.Add(fixedFontSizeLabelEffect6);
		VisualDiagnostics.RegisterSourceInfo(fixedFontSizeLabelEffect6, new Uri("Views/CompositionMeterChartView.xaml", UriKind.RelativeOrAbsolute), 138, 30);
		grid7.Children.Add(label6);
		VisualDiagnostics.RegisterSourceInfo(label6, new Uri("Views/CompositionMeterChartView.xaml", UriKind.RelativeOrAbsolute), 136, 22);
		grid13.Children.Add(grid7);
		VisualDiagnostics.RegisterSourceInfo(grid7, new Uri("Views/CompositionMeterChartView.xaml", UriKind.RelativeOrAbsolute), 135, 18);
		grid8.SetValue(Grid.RowProperty, 4);
		grid8.SetValue(Grid.ColumnProperty, 3);
		grid8.SetValue(Grid.ColumnSpanProperty, 2);
		grid8.SetValue(Grid.ColumnSpacingProperty, 0.0);
		grid8.SetValue(VisualElement.BackgroundColorProperty, Color.Transparent);
		bindingExtension4.Path = "BmiAverage";
		BindingBase binding4 = ((IMarkupExtension<BindingBase>)bindingExtension4).ProvideValue((IServiceProvider)null);
		label7.SetBinding(Label.TextProperty, binding4);
		label7.SetValue(Label.TextColorProperty, Color.Blue);
		label7.SetValue(Xamarin.Forms.View.VerticalOptionsProperty, LayoutOptions.EndAndExpand);
		label7.SetValue(Xamarin.Forms.View.HorizontalOptionsProperty, LayoutOptions.End);
		BindableProperty fontSizeProperty8 = Label.FontSizeProperty;
		FontSizeConverter fontSizeConverter8 = new FontSizeConverter();
		XamlServiceProvider xamlServiceProvider8 = new XamlServiceProvider();
		Type typeFromHandle15 = typeof(IProvideValueTarget);
		object[] array8 = new object[0 + 6];
		array8[0] = label7;
		array8[1] = grid8;
		array8[2] = grid13;
		array8[3] = scrollView;
		array8[4] = grid14;
		array8[5] = compositionMeterChartView;
		object service8;
		xamlServiceProvider8.Add(typeFromHandle15, service8 = new SimpleValueTargetProvider(array8, Label.FontSizeProperty, nameScope));
		xamlServiceProvider8.Add(typeof(IReferenceProvider), service8);
		Type typeFromHandle16 = typeof(IXamlTypeResolver);
		XmlNamespaceResolver xmlNamespaceResolver8 = new XmlNamespaceResolver();
		xmlNamespaceResolver8.Add("", "http://xamarin.com/schemas/2014/forms");
		xmlNamespaceResolver8.Add("x", "http://schemas.microsoft.com/winfx/2009/xaml");
		xmlNamespaceResolver8.Add("calx", "clr-namespace:Caliburn.Micro.Xamarin.Forms;assembly=Caliburn.Micro.Platform.Xamarin.Forms");
		xmlNamespaceResolver8.Add("effect", "clr-namespace:NHL.Views.Effect");
		xmlNamespaceResolver8.Add("c1", "clr-namespace:C1.Xamarin.Forms.Chart;assembly=C1.Xamarin.Forms.Chart");
		xamlServiceProvider8.Add(typeFromHandle16, new XamlTypeResolver(xmlNamespaceResolver8, typeof(CompositionMeterChartView).GetTypeInfo().Assembly));
		xamlServiceProvider8.Add(typeof(IXmlLineInfoProvider), new XmlLineInfoProvider(new XmlLineInfo(143, 128)));
		label7.SetValue(fontSizeProperty8, ((IExtendedTypeConverter)fontSizeConverter8).ConvertFromInvariantString("Large", (IServiceProvider)xamlServiceProvider8));
		label7.SetValue(Label.FontAttributesProperty, new FontAttributesConverter().ConvertFromInvariantString("Bold"));
		label7.Effects.Add(fixedFontSizeLabelEffect7);
		VisualDiagnostics.RegisterSourceInfo(fixedFontSizeLabelEffect7, new Uri("Views/CompositionMeterChartView.xaml", UriKind.RelativeOrAbsolute), 145, 30);
		grid8.Children.Add(label7);
		VisualDiagnostics.RegisterSourceInfo(label7, new Uri("Views/CompositionMeterChartView.xaml", UriKind.RelativeOrAbsolute), 143, 22);
		grid13.Children.Add(grid8);
		VisualDiagnostics.RegisterSourceInfo(grid8, new Uri("Views/CompositionMeterChartView.xaml", UriKind.RelativeOrAbsolute), 142, 18);
		grid9.SetValue(Grid.RowProperty, 4);
		grid9.SetValue(Grid.ColumnProperty, 5);
		grid9.SetValue(Grid.ColumnSpacingProperty, 0.0);
		grid9.SetValue(VisualElement.BackgroundColorProperty, Color.Transparent);
		grid9.SetValue(Xamarin.Forms.View.MarginProperty, new Thickness(0.0, 0.0, 5.0, 3.0));
		label8.SetValue(Label.TextProperty, "");
		label8.SetValue(Label.TextColorProperty, Color.Black);
		label8.SetValue(Xamarin.Forms.View.VerticalOptionsProperty, LayoutOptions.EndAndExpand);
		label8.SetValue(Xamarin.Forms.View.HorizontalOptionsProperty, LayoutOptions.Start);
		BindableProperty fontSizeProperty9 = Label.FontSizeProperty;
		FontSizeConverter fontSizeConverter9 = new FontSizeConverter();
		XamlServiceProvider xamlServiceProvider9 = new XamlServiceProvider();
		Type typeFromHandle17 = typeof(IProvideValueTarget);
		object[] array9 = new object[0 + 6];
		array9[0] = label8;
		array9[1] = grid9;
		array9[2] = grid13;
		array9[3] = scrollView;
		array9[4] = grid14;
		array9[5] = compositionMeterChartView;
		object service9;
		xamlServiceProvider9.Add(typeFromHandle17, service9 = new SimpleValueTargetProvider(array9, Label.FontSizeProperty, nameScope));
		xamlServiceProvider9.Add(typeof(IReferenceProvider), service9);
		Type typeFromHandle18 = typeof(IXamlTypeResolver);
		XmlNamespaceResolver xmlNamespaceResolver9 = new XmlNamespaceResolver();
		xmlNamespaceResolver9.Add("", "http://xamarin.com/schemas/2014/forms");
		xmlNamespaceResolver9.Add("x", "http://schemas.microsoft.com/winfx/2009/xaml");
		xmlNamespaceResolver9.Add("calx", "clr-namespace:Caliburn.Micro.Xamarin.Forms;assembly=Caliburn.Micro.Platform.Xamarin.Forms");
		xmlNamespaceResolver9.Add("effect", "clr-namespace:NHL.Views.Effect");
		xmlNamespaceResolver9.Add("c1", "clr-namespace:C1.Xamarin.Forms.Chart;assembly=C1.Xamarin.Forms.Chart");
		xamlServiceProvider9.Add(typeFromHandle18, new XamlTypeResolver(xmlNamespaceResolver9, typeof(CompositionMeterChartView).GetTypeInfo().Assembly));
		xamlServiceProvider9.Add(typeof(IXmlLineInfoProvider), new XmlLineInfoProvider(new XmlLineInfo(150, 111)));
		label8.SetValue(fontSizeProperty9, ((IExtendedTypeConverter)fontSizeConverter9).ConvertFromInvariantString("Default", (IServiceProvider)xamlServiceProvider9));
		label8.SetValue(Label.FontAttributesProperty, new FontAttributesConverter().ConvertFromInvariantString("Bold"));
		label8.Effects.Add(fixedFontSizeLabelEffect8);
		VisualDiagnostics.RegisterSourceInfo(fixedFontSizeLabelEffect8, new Uri("Views/CompositionMeterChartView.xaml", UriKind.RelativeOrAbsolute), 152, 30);
		grid9.Children.Add(label8);
		VisualDiagnostics.RegisterSourceInfo(label8, new Uri("Views/CompositionMeterChartView.xaml", UriKind.RelativeOrAbsolute), 150, 22);
		grid13.Children.Add(grid9);
		VisualDiagnostics.RegisterSourceInfo(grid9, new Uri("Views/CompositionMeterChartView.xaml", UriKind.RelativeOrAbsolute), 149, 18);
		grid10.SetValue(Grid.RowProperty, 5);
		grid10.SetValue(Grid.ColumnProperty, 0);
		grid10.SetValue(Grid.ColumnSpanProperty, 3);
		grid10.SetValue(VisualElement.BackgroundColorProperty, Color.Transparent);
		grid10.SetValue(Xamarin.Forms.View.MarginProperty, new Thickness(15.0, 0.0, 0.0, 0.0));
		label9.SetValue(Label.TextProperty, "体脂肪率");
		label9.SetValue(Label.TextColorProperty, Color.Blue);
		label9.SetValue(Xamarin.Forms.View.VerticalOptionsProperty, LayoutOptions.Center);
		label9.SetValue(Xamarin.Forms.View.HorizontalOptionsProperty, LayoutOptions.StartAndExpand);
		BindableProperty fontSizeProperty10 = Label.FontSizeProperty;
		FontSizeConverter fontSizeConverter10 = new FontSizeConverter();
		XamlServiceProvider xamlServiceProvider10 = new XamlServiceProvider();
		Type typeFromHandle19 = typeof(IProvideValueTarget);
		object[] array10 = new object[0 + 6];
		array10[0] = label9;
		array10[1] = grid10;
		array10[2] = grid13;
		array10[3] = scrollView;
		array10[4] = grid14;
		array10[5] = compositionMeterChartView;
		object service10;
		xamlServiceProvider10.Add(typeFromHandle19, service10 = new SimpleValueTargetProvider(array10, Label.FontSizeProperty, nameScope));
		xamlServiceProvider10.Add(typeof(IReferenceProvider), service10);
		Type typeFromHandle20 = typeof(IXamlTypeResolver);
		XmlNamespaceResolver xmlNamespaceResolver10 = new XmlNamespaceResolver();
		xmlNamespaceResolver10.Add("", "http://xamarin.com/schemas/2014/forms");
		xmlNamespaceResolver10.Add("x", "http://schemas.microsoft.com/winfx/2009/xaml");
		xmlNamespaceResolver10.Add("calx", "clr-namespace:Caliburn.Micro.Xamarin.Forms;assembly=Caliburn.Micro.Platform.Xamarin.Forms");
		xmlNamespaceResolver10.Add("effect", "clr-namespace:NHL.Views.Effect");
		xmlNamespaceResolver10.Add("c1", "clr-namespace:C1.Xamarin.Forms.Chart;assembly=C1.Xamarin.Forms.Chart");
		xamlServiceProvider10.Add(typeFromHandle20, new XamlTypeResolver(xmlNamespaceResolver10, typeof(CompositionMeterChartView).GetTypeInfo().Assembly));
		xamlServiceProvider10.Add(typeof(IXmlLineInfoProvider), new XmlLineInfoProvider(new XmlLineInfo(159, 117)));
		label9.SetValue(fontSizeProperty10, ((IExtendedTypeConverter)fontSizeConverter10).ConvertFromInvariantString("Large", (IServiceProvider)xamlServiceProvider10));
		label9.Effects.Add(fixedFontSizeLabelEffect9);
		VisualDiagnostics.RegisterSourceInfo(fixedFontSizeLabelEffect9, new Uri("Views/CompositionMeterChartView.xaml", UriKind.RelativeOrAbsolute), 161, 30);
		grid10.Children.Add(label9);
		VisualDiagnostics.RegisterSourceInfo(label9, new Uri("Views/CompositionMeterChartView.xaml", UriKind.RelativeOrAbsolute), 159, 22);
		grid13.Children.Add(grid10);
		VisualDiagnostics.RegisterSourceInfo(grid10, new Uri("Views/CompositionMeterChartView.xaml", UriKind.RelativeOrAbsolute), 158, 18);
		grid11.SetValue(Grid.RowProperty, 5);
		grid11.SetValue(Grid.ColumnProperty, 3);
		grid11.SetValue(Grid.ColumnSpanProperty, 2);
		grid11.SetValue(Grid.ColumnSpacingProperty, 0.0);
		grid11.SetValue(VisualElement.BackgroundColorProperty, Color.Transparent);
		bindingExtension5.Path = "FatPercentageAverage";
		BindingBase binding5 = ((IMarkupExtension<BindingBase>)bindingExtension5).ProvideValue((IServiceProvider)null);
		label10.SetBinding(Label.TextProperty, binding5);
		label10.SetValue(Label.TextColorProperty, Color.Blue);
		label10.SetValue(Xamarin.Forms.View.VerticalOptionsProperty, LayoutOptions.EndAndExpand);
		label10.SetValue(Xamarin.Forms.View.HorizontalOptionsProperty, LayoutOptions.End);
		BindableProperty fontSizeProperty11 = Label.FontSizeProperty;
		FontSizeConverter fontSizeConverter11 = new FontSizeConverter();
		XamlServiceProvider xamlServiceProvider11 = new XamlServiceProvider();
		Type typeFromHandle21 = typeof(IProvideValueTarget);
		object[] array11 = new object[0 + 6];
		array11[0] = label10;
		array11[1] = grid11;
		array11[2] = grid13;
		array11[3] = scrollView;
		array11[4] = grid14;
		array11[5] = compositionMeterChartView;
		object service11;
		xamlServiceProvider11.Add(typeFromHandle21, service11 = new SimpleValueTargetProvider(array11, Label.FontSizeProperty, nameScope));
		xamlServiceProvider11.Add(typeof(IReferenceProvider), service11);
		Type typeFromHandle22 = typeof(IXamlTypeResolver);
		XmlNamespaceResolver xmlNamespaceResolver11 = new XmlNamespaceResolver();
		xmlNamespaceResolver11.Add("", "http://xamarin.com/schemas/2014/forms");
		xmlNamespaceResolver11.Add("x", "http://schemas.microsoft.com/winfx/2009/xaml");
		xmlNamespaceResolver11.Add("calx", "clr-namespace:Caliburn.Micro.Xamarin.Forms;assembly=Caliburn.Micro.Platform.Xamarin.Forms");
		xmlNamespaceResolver11.Add("effect", "clr-namespace:NHL.Views.Effect");
		xmlNamespaceResolver11.Add("c1", "clr-namespace:C1.Xamarin.Forms.Chart;assembly=C1.Xamarin.Forms.Chart");
		xamlServiceProvider11.Add(typeFromHandle22, new XamlTypeResolver(xmlNamespaceResolver11, typeof(CompositionMeterChartView).GetTypeInfo().Assembly));
		xamlServiceProvider11.Add(typeof(IXmlLineInfoProvider), new XmlLineInfoProvider(new XmlLineInfo(166, 138)));
		label10.SetValue(fontSizeProperty11, ((IExtendedTypeConverter)fontSizeConverter11).ConvertFromInvariantString("Large", (IServiceProvider)xamlServiceProvider11));
		label10.SetValue(Label.FontAttributesProperty, new FontAttributesConverter().ConvertFromInvariantString("Bold"));
		label10.Effects.Add(fixedFontSizeLabelEffect10);
		VisualDiagnostics.RegisterSourceInfo(fixedFontSizeLabelEffect10, new Uri("Views/CompositionMeterChartView.xaml", UriKind.RelativeOrAbsolute), 168, 30);
		grid11.Children.Add(label10);
		VisualDiagnostics.RegisterSourceInfo(label10, new Uri("Views/CompositionMeterChartView.xaml", UriKind.RelativeOrAbsolute), 166, 22);
		grid13.Children.Add(grid11);
		VisualDiagnostics.RegisterSourceInfo(grid11, new Uri("Views/CompositionMeterChartView.xaml", UriKind.RelativeOrAbsolute), 165, 18);
		grid12.SetValue(Grid.RowProperty, 5);
		grid12.SetValue(Grid.ColumnProperty, 5);
		grid12.SetValue(Grid.ColumnSpacingProperty, 0.0);
		grid12.SetValue(VisualElement.BackgroundColorProperty, Color.Transparent);
		grid12.SetValue(Xamarin.Forms.View.MarginProperty, new Thickness(0.0, 0.0, 5.0, 3.0));
		label11.SetValue(Label.TextProperty, "%");
		label11.SetValue(Label.TextColorProperty, Color.Black);
		label11.SetValue(Xamarin.Forms.View.VerticalOptionsProperty, LayoutOptions.EndAndExpand);
		label11.SetValue(Xamarin.Forms.View.HorizontalOptionsProperty, LayoutOptions.Start);
		BindableProperty fontSizeProperty12 = Label.FontSizeProperty;
		FontSizeConverter fontSizeConverter12 = new FontSizeConverter();
		XamlServiceProvider xamlServiceProvider12 = new XamlServiceProvider();
		Type typeFromHandle23 = typeof(IProvideValueTarget);
		object[] array12 = new object[0 + 6];
		array12[0] = label11;
		array12[1] = grid12;
		array12[2] = grid13;
		array12[3] = scrollView;
		array12[4] = grid14;
		array12[5] = compositionMeterChartView;
		object service12;
		xamlServiceProvider12.Add(typeFromHandle23, service12 = new SimpleValueTargetProvider(array12, Label.FontSizeProperty, nameScope));
		xamlServiceProvider12.Add(typeof(IReferenceProvider), service12);
		Type typeFromHandle24 = typeof(IXamlTypeResolver);
		XmlNamespaceResolver xmlNamespaceResolver12 = new XmlNamespaceResolver();
		xmlNamespaceResolver12.Add("", "http://xamarin.com/schemas/2014/forms");
		xmlNamespaceResolver12.Add("x", "http://schemas.microsoft.com/winfx/2009/xaml");
		xmlNamespaceResolver12.Add("calx", "clr-namespace:Caliburn.Micro.Xamarin.Forms;assembly=Caliburn.Micro.Platform.Xamarin.Forms");
		xmlNamespaceResolver12.Add("effect", "clr-namespace:NHL.Views.Effect");
		xmlNamespaceResolver12.Add("c1", "clr-namespace:C1.Xamarin.Forms.Chart;assembly=C1.Xamarin.Forms.Chart");
		xamlServiceProvider12.Add(typeFromHandle24, new XamlTypeResolver(xmlNamespaceResolver12, typeof(CompositionMeterChartView).GetTypeInfo().Assembly));
		xamlServiceProvider12.Add(typeof(IXmlLineInfoProvider), new XmlLineInfoProvider(new XmlLineInfo(173, 112)));
		label11.SetValue(fontSizeProperty12, ((IExtendedTypeConverter)fontSizeConverter12).ConvertFromInvariantString("Default", (IServiceProvider)xamlServiceProvider12));
		label11.SetValue(Label.FontAttributesProperty, new FontAttributesConverter().ConvertFromInvariantString("Bold"));
		label11.Effects.Add(fixedFontSizeLabelEffect11);
		VisualDiagnostics.RegisterSourceInfo(fixedFontSizeLabelEffect11, new Uri("Views/CompositionMeterChartView.xaml", UriKind.RelativeOrAbsolute), 175, 30);
		grid12.Children.Add(label11);
		VisualDiagnostics.RegisterSourceInfo(label11, new Uri("Views/CompositionMeterChartView.xaml", UriKind.RelativeOrAbsolute), 173, 22);
		grid13.Children.Add(grid12);
		VisualDiagnostics.RegisterSourceInfo(grid12, new Uri("Views/CompositionMeterChartView.xaml", UriKind.RelativeOrAbsolute), 172, 18);
		button2.SetValue(Button.TextProperty, "グラフ表示項目設定");
		button2.SetValue(Grid.RowProperty, 6);
		button2.SetValue(Grid.ColumnProperty, 0);
		button2.SetValue(Grid.ColumnSpanProperty, 6);
		button2.SetValue(Xamarin.Forms.View.MarginProperty, new Thickness(5.0, 5.0, 5.0, 5.0));
		button2.SetValue(Button.BorderColorProperty, Color.Black);
		button2.SetValue(Button.BorderWidthProperty, 2.0);
		BindableProperty fontSizeProperty13 = Button.FontSizeProperty;
		FontSizeConverter fontSizeConverter13 = new FontSizeConverter();
		XamlServiceProvider xamlServiceProvider13 = new XamlServiceProvider();
		Type typeFromHandle25 = typeof(IProvideValueTarget);
		object[] array13 = new object[0 + 5];
		array13[0] = button2;
		array13[1] = grid13;
		array13[2] = scrollView;
		array13[3] = grid14;
		array13[4] = compositionMeterChartView;
		object service13;
		xamlServiceProvider13.Add(typeFromHandle25, service13 = new SimpleValueTargetProvider(array13, Button.FontSizeProperty, nameScope));
		xamlServiceProvider13.Add(typeof(IReferenceProvider), service13);
		Type typeFromHandle26 = typeof(IXamlTypeResolver);
		XmlNamespaceResolver xmlNamespaceResolver13 = new XmlNamespaceResolver();
		xmlNamespaceResolver13.Add("", "http://xamarin.com/schemas/2014/forms");
		xmlNamespaceResolver13.Add("x", "http://schemas.microsoft.com/winfx/2009/xaml");
		xmlNamespaceResolver13.Add("calx", "clr-namespace:Caliburn.Micro.Xamarin.Forms;assembly=Caliburn.Micro.Platform.Xamarin.Forms");
		xmlNamespaceResolver13.Add("effect", "clr-namespace:NHL.Views.Effect");
		xmlNamespaceResolver13.Add("c1", "clr-namespace:C1.Xamarin.Forms.Chart;assembly=C1.Xamarin.Forms.Chart");
		xamlServiceProvider13.Add(typeFromHandle26, new XamlTypeResolver(xmlNamespaceResolver13, typeof(CompositionMeterChartView).GetTypeInfo().Assembly));
		xamlServiceProvider13.Add(typeof(IXmlLineInfoProvider), new XmlLineInfoProvider(new XmlLineInfo(181, 144)));
		button2.SetValue(fontSizeProperty13, ((IExtendedTypeConverter)fontSizeConverter13).ConvertFromInvariantString("Large", (IServiceProvider)xamlServiceProvider13));
		button2.SetValue(Button.FontAttributesProperty, new FontAttributesConverter().ConvertFromInvariantString("Bold"));
		button2.SetValue(VisualElement.BackgroundColorProperty, Color.White);
		button2.SetValue(Message.AttachProperty, "OnChartSettingTapped");
		button2.Effects.Add(fixedFontSizeButtonEffect2);
		VisualDiagnostics.RegisterSourceInfo(fixedFontSizeButtonEffect2, new Uri("Views/CompositionMeterChartView.xaml", UriKind.RelativeOrAbsolute), 184, 26);
		grid13.Children.Add(button2);
		VisualDiagnostics.RegisterSourceInfo(button2, new Uri("Views/CompositionMeterChartView.xaml", UriKind.RelativeOrAbsolute), 181, 18);
		button3.SetValue(Grid.RowProperty, 7);
		button3.SetValue(Grid.ColumnSpanProperty, 6);
		button3.SetValue(Xamarin.Forms.View.MarginProperty, new Thickness(5.0, 5.0, 5.0, 5.0));
		button3.SetValue(Button.BorderColorProperty, Color.Black);
		button3.SetValue(Button.BorderWidthProperty, 2.0);
		BindableProperty fontSizeProperty14 = Button.FontSizeProperty;
		FontSizeConverter fontSizeConverter14 = new FontSizeConverter();
		XamlServiceProvider xamlServiceProvider14 = new XamlServiceProvider();
		Type typeFromHandle27 = typeof(IProvideValueTarget);
		object[] array14 = new object[0 + 5];
		array14[0] = button3;
		array14[1] = grid13;
		array14[2] = scrollView;
		array14[3] = grid14;
		array14[4] = compositionMeterChartView;
		object service14;
		xamlServiceProvider14.Add(typeFromHandle27, service14 = new SimpleValueTargetProvider(array14, Button.FontSizeProperty, nameScope));
		xamlServiceProvider14.Add(typeof(IReferenceProvider), service14);
		Type typeFromHandle28 = typeof(IXamlTypeResolver);
		XmlNamespaceResolver xmlNamespaceResolver14 = new XmlNamespaceResolver();
		xmlNamespaceResolver14.Add("", "http://xamarin.com/schemas/2014/forms");
		xmlNamespaceResolver14.Add("x", "http://schemas.microsoft.com/winfx/2009/xaml");
		xmlNamespaceResolver14.Add("calx", "clr-namespace:Caliburn.Micro.Xamarin.Forms;assembly=Caliburn.Micro.Platform.Xamarin.Forms");
		xmlNamespaceResolver14.Add("effect", "clr-namespace:NHL.Views.Effect");
		xmlNamespaceResolver14.Add("c1", "clr-namespace:C1.Xamarin.Forms.Chart;assembly=C1.Xamarin.Forms.Chart");
		xamlServiceProvider14.Add(typeFromHandle28, new XamlTypeResolver(xmlNamespaceResolver14, typeof(CompositionMeterChartView).GetTypeInfo().Assembly));
		xamlServiceProvider14.Add(typeof(IXmlLineInfoProvider), new XmlLineInfoProvider(new XmlLineInfo(189, 111)));
		button3.SetValue(fontSizeProperty14, ((IExtendedTypeConverter)fontSizeConverter14).ConvertFromInvariantString("Large", (IServiceProvider)xamlServiceProvider14));
		button3.SetValue(Message.AttachProperty, "OnCompDataTapped");
		button3.SetValue(Button.TextProperty, "データ表");
		button3.SetValue(Button.FontAttributesProperty, new FontAttributesConverter().ConvertFromInvariantString("Bold"));
		button3.SetValue(VisualElement.BackgroundColorProperty, Color.White);
		button3.Effects.Add(fixedFontSizeButtonEffect3);
		VisualDiagnostics.RegisterSourceInfo(fixedFontSizeButtonEffect3, new Uri("Views/CompositionMeterChartView.xaml", UriKind.RelativeOrAbsolute), 191, 26);
		grid13.Children.Add(button3);
		VisualDiagnostics.RegisterSourceInfo(button3, new Uri("Views/CompositionMeterChartView.xaml", UriKind.RelativeOrAbsolute), 189, 18);
		scrollView.Content = grid13;
		VisualDiagnostics.RegisterSourceInfo(grid13, new Uri("Views/CompositionMeterChartView.xaml", UriKind.RelativeOrAbsolute), 15, 14);
		grid14.Children.Add(scrollView);
		VisualDiagnostics.RegisterSourceInfo(scrollView, new Uri("Views/CompositionMeterChartView.xaml", UriKind.RelativeOrAbsolute), 14, 10);
		compositionMeterChartView.SetValue(ContentPage.ContentProperty, grid14);
		VisualDiagnostics.RegisterSourceInfo(grid14, new Uri("Views/CompositionMeterChartView.xaml", UriKind.RelativeOrAbsolute), 13, 6);
		VisualDiagnostics.RegisterSourceInfo(compositionMeterChartView, new Uri("Views/CompositionMeterChartView.xaml", UriKind.RelativeOrAbsolute), 3, 2);
	}

	private void __InitComponentRuntime()
	{
		this.LoadFromXaml(typeof(CompositionMeterChartView));
		Dates = this.FindByName<Label>("Dates");
		Chart = this.FindByName<FlexChart>("Chart");
		WeightLine = this.FindByName<ChartSeries>("WeightLine");
		BmiLine = this.FindByName<ChartSeries>("BmiLine");
		FatPercentageLine = this.FindByName<ChartSeries>("FatPercentageLine");
	}
}
