using System;
using System.CodeDom.Compiler;
using System.Reflection;
using Caliburn.Micro.Xamarin.Forms;
using NHL.Views.Effect;
using Xamarin.Forms;
using Xamarin.Forms.Internals;
using Xamarin.Forms.Xaml;
using Xamarin.Forms.Xaml.Diagnostics;
using Xamarin.Forms.Xaml.Internals;

namespace NHL.Views;

[XamlCompilation(XamlCompilationOptions.Compile)]
[XamlFilePath("Views/CompositionMeterDetailView.xaml")]
public class CompositionMeterDetailView : ContentPage
{
	public CompositionMeterDetailView()
	{
		InitializeComponent();
	}

	[GeneratedCode("Xamarin.Forms.Build.Tasks.XamlG", "2.0.0.0")]
	private void InitializeComponent()
	{
		if (ResourceLoader.CanProvideContentFor(new ResourceLoader.ResourceLoadingQuery
		{
			AssemblyName = typeof(CompositionMeterDetailView).GetTypeInfo().Assembly.GetName(),
			ResourcePath = "Views/CompositionMeterDetailView.xaml",
			Instance = this
		}))
		{
			__InitComponentRuntime();
			return;
		}
		if (XamlLoader.XamlFileProvider != null && XamlLoader.XamlFileProvider(GetType()) != null)
		{
			__InitComponentRuntime();
			return;
		}
		StaticResourceExtension staticResourceExtension = new StaticResourceExtension();
		Color color = Color.FromHex("#EFEFF4");
		Color color2 = Color.FromHex("#F44336");
		Color color3 = Color.FromHex("#CFCFCF");
		ResourceDictionary resourceDictionary = new ResourceDictionary();
		ColumnDefinition columnDefinition = new ColumnDefinition();
		ColumnDefinition columnDefinition2 = new ColumnDefinition();
		RowDefinition rowDefinition = new RowDefinition();
		RowDefinition rowDefinition2 = new RowDefinition();
		RowDefinition rowDefinition3 = new RowDefinition();
		RowDefinition rowDefinition4 = new RowDefinition();
		RowDefinition rowDefinition5 = new RowDefinition();
		RowDefinition rowDefinition6 = new RowDefinition();
		RowDefinition rowDefinition7 = new RowDefinition();
		RowDefinition rowDefinition8 = new RowDefinition();
		RowDefinition rowDefinition9 = new RowDefinition();
		RowDefinition rowDefinition10 = new RowDefinition();
		RowDefinition rowDefinition11 = new RowDefinition();
		RowDefinition rowDefinition12 = new RowDefinition();
		RowDefinition rowDefinition13 = new RowDefinition();
		RowDefinition rowDefinition14 = new RowDefinition();
		RowDefinition rowDefinition15 = new RowDefinition();
		RowDefinition rowDefinition16 = new RowDefinition();
		RowDefinition rowDefinition17 = new RowDefinition();
		RowDefinition rowDefinition18 = new RowDefinition();
		RowDefinition item = new RowDefinition();
		StaticResourceExtension staticResourceExtension2 = new StaticResourceExtension();
		Grid grid = new Grid();
		StaticResourceExtension staticResourceExtension3 = new StaticResourceExtension();
		Grid grid2 = new Grid();
		StaticResourceExtension staticResourceExtension4 = new StaticResourceExtension();
		Grid grid3 = new Grid();
		StaticResourceExtension staticResourceExtension5 = new StaticResourceExtension();
		Grid grid4 = new Grid();
		StaticResourceExtension staticResourceExtension6 = new StaticResourceExtension();
		Grid grid5 = new Grid();
		StaticResourceExtension staticResourceExtension7 = new StaticResourceExtension();
		Grid grid6 = new Grid();
		StaticResourceExtension staticResourceExtension8 = new StaticResourceExtension();
		Grid grid7 = new Grid();
		StaticResourceExtension staticResourceExtension9 = new StaticResourceExtension();
		Grid grid8 = new Grid();
		StaticResourceExtension staticResourceExtension10 = new StaticResourceExtension();
		Grid grid9 = new Grid();
		Grid grid10 = new Grid();
		Grid grid11 = new Grid();
		Grid grid12 = new Grid();
		Grid grid13 = new Grid();
		Grid grid14 = new Grid();
		Grid grid15 = new Grid();
		Grid grid16 = new Grid();
		Grid grid17 = new Grid();
		Grid grid18 = new Grid();
		BindingExtension bindingExtension = new BindingExtension();
		FixedFontSizeLabelEffect fixedFontSizeLabelEffect = new FixedFontSizeLabelEffect();
		Label label = new Label();
		BindingExtension bindingExtension2 = new BindingExtension();
		FixedFontSizeLabelEffect fixedFontSizeLabelEffect2 = new FixedFontSizeLabelEffect();
		Label label2 = new Label();
		BindingExtension bindingExtension3 = new BindingExtension();
		FixedFontSizeLabelEffect fixedFontSizeLabelEffect3 = new FixedFontSizeLabelEffect();
		Label label3 = new Label();
		BindingExtension bindingExtension4 = new BindingExtension();
		FixedFontSizeLabelEffect fixedFontSizeLabelEffect4 = new FixedFontSizeLabelEffect();
		Label label4 = new Label();
		BindingExtension bindingExtension5 = new BindingExtension();
		FixedFontSizeLabelEffect fixedFontSizeLabelEffect5 = new FixedFontSizeLabelEffect();
		Label label5 = new Label();
		BindingExtension bindingExtension6 = new BindingExtension();
		FixedFontSizeLabelEffect fixedFontSizeLabelEffect6 = new FixedFontSizeLabelEffect();
		Label label6 = new Label();
		BindingExtension bindingExtension7 = new BindingExtension();
		FixedFontSizeLabelEffect fixedFontSizeLabelEffect7 = new FixedFontSizeLabelEffect();
		Label label7 = new Label();
		BindingExtension bindingExtension8 = new BindingExtension();
		FixedFontSizeLabelEffect fixedFontSizeLabelEffect8 = new FixedFontSizeLabelEffect();
		Label label8 = new Label();
		BindingExtension bindingExtension9 = new BindingExtension();
		FixedFontSizeLabelEffect fixedFontSizeLabelEffect9 = new FixedFontSizeLabelEffect();
		Label label9 = new Label();
		BindingExtension bindingExtension10 = new BindingExtension();
		FixedFontSizeLabelEffect fixedFontSizeLabelEffect10 = new FixedFontSizeLabelEffect();
		Label label10 = new Label();
		BindingExtension bindingExtension11 = new BindingExtension();
		FixedFontSizeLabelEffect fixedFontSizeLabelEffect11 = new FixedFontSizeLabelEffect();
		Label label11 = new Label();
		BindingExtension bindingExtension12 = new BindingExtension();
		FixedFontSizeLabelEffect fixedFontSizeLabelEffect12 = new FixedFontSizeLabelEffect();
		Label label12 = new Label();
		BindingExtension bindingExtension13 = new BindingExtension();
		FixedFontSizeLabelEffect fixedFontSizeLabelEffect13 = new FixedFontSizeLabelEffect();
		Label label13 = new Label();
		BindingExtension bindingExtension14 = new BindingExtension();
		FixedFontSizeLabelEffect fixedFontSizeLabelEffect14 = new FixedFontSizeLabelEffect();
		Label label14 = new Label();
		BindingExtension bindingExtension15 = new BindingExtension();
		FixedFontSizeLabelEffect fixedFontSizeLabelEffect15 = new FixedFontSizeLabelEffect();
		Label label15 = new Label();
		BindingExtension bindingExtension16 = new BindingExtension();
		FixedFontSizeLabelEffect fixedFontSizeLabelEffect16 = new FixedFontSizeLabelEffect();
		Label label16 = new Label();
		BindingExtension bindingExtension17 = new BindingExtension();
		FixedFontSizeLabelEffect fixedFontSizeLabelEffect17 = new FixedFontSizeLabelEffect();
		Label label17 = new Label();
		BindingExtension bindingExtension18 = new BindingExtension();
		FixedFontSizeLabelEffect fixedFontSizeLabelEffect18 = new FixedFontSizeLabelEffect();
		Label label18 = new Label();
		Grid grid19 = new Grid();
		StaticResourceExtension staticResourceExtension11 = new StaticResourceExtension();
		FixedFontSizeButtonEffect fixedFontSizeButtonEffect = new FixedFontSizeButtonEffect();
		Button button = new Button();
		StackLayout stackLayout = new StackLayout();
		ScrollView scrollView = new ScrollView();
		CompositionMeterDetailView compositionMeterDetailView;
		NameScope nameScope = (NameScope)(NameScope.GetNameScope(compositionMeterDetailView = this) ?? new NameScope());
		NameScope.SetNameScope(compositionMeterDetailView, nameScope);
		compositionMeterDetailView.Resources = resourceDictionary;
		VisualDiagnostics.RegisterSourceInfo(resourceDictionary, new Uri("Views/CompositionMeterDetailView.xaml", UriKind.RelativeOrAbsolute), 13, 10);
		resourceDictionary.Add("PageBackgroundColor", color);
		resourceDictionary.Add("WarnButtonColor", color2);
		resourceDictionary.Add("LineColor", color3);
		compositionMeterDetailView.SetValue(NavigationPage.HasBackButtonProperty, true);
		compositionMeterDetailView.SetValue(NavigationPage.BackButtonTitleProperty, "戻る");
		compositionMeterDetailView.SetValue(Page.TitleProperty, "体組成計 測定結果画面");
		staticResourceExtension.Key = "PageBackgroundColor";
		XamlServiceProvider xamlServiceProvider = new XamlServiceProvider();
		Type typeFromHandle = typeof(IProvideValueTarget);
		object[] array = new object[0 + 1];
		array[0] = compositionMeterDetailView;
		object service;
		xamlServiceProvider.Add(typeFromHandle, service = new SimpleValueTargetProvider(array, VisualElement.BackgroundColorProperty, nameScope));
		xamlServiceProvider.Add(typeof(IReferenceProvider), service);
		Type typeFromHandle2 = typeof(IXamlTypeResolver);
		XmlNamespaceResolver xmlNamespaceResolver = new XmlNamespaceResolver();
		xmlNamespaceResolver.Add("", "http://xamarin.com/schemas/2014/forms");
		xmlNamespaceResolver.Add("x", "http://schemas.microsoft.com/winfx/2009/xaml");
		xmlNamespaceResolver.Add("effect", "clr-namespace:NHL.Views.Effect");
		xmlNamespaceResolver.Add("calx", "clr-namespace:Caliburn.Micro.Xamarin.Forms;assembly=Caliburn.Micro.Platform.Xamarin.Forms");
		xamlServiceProvider.Add(typeFromHandle2, new XamlTypeResolver(xmlNamespaceResolver, typeof(CompositionMeterDetailView).GetTypeInfo().Assembly));
		xamlServiceProvider.Add(typeof(IXmlLineInfoProvider), new XmlLineInfoProvider(new XmlLineInfo(10, 14)));
		object obj = ((IMarkupExtension)staticResourceExtension).ProvideValue((IServiceProvider)xamlServiceProvider);
		compositionMeterDetailView.BackgroundColor = (Color)obj;
		VisualDiagnostics.RegisterSourceInfo(obj, new Uri("Views/CompositionMeterDetailView.xaml", UriKind.RelativeOrAbsolute), 10, 14);
		compositionMeterDetailView.Resources = resourceDictionary;
		VisualDiagnostics.RegisterSourceInfo(resourceDictionary, new Uri("Views/CompositionMeterDetailView.xaml", UriKind.RelativeOrAbsolute), 13, 10);
		scrollView.SetValue(Xamarin.Forms.View.VerticalOptionsProperty, LayoutOptions.FillAndExpand);
		scrollView.SetValue(Xamarin.Forms.View.HorizontalOptionsProperty, LayoutOptions.FillAndExpand);
		stackLayout.SetValue(StackLayout.OrientationProperty, StackOrientation.Vertical);
		grid19.SetValue(Grid.RowSpacingProperty, 0.0);
		columnDefinition.SetValue(ColumnDefinition.WidthProperty, new GridLengthTypeConverter().ConvertFromInvariantString("Auto"));
		((DefinitionCollection<ColumnDefinition>)grid19.GetValue(Grid.ColumnDefinitionsProperty)).Add(columnDefinition);
		columnDefinition2.SetValue(ColumnDefinition.WidthProperty, new GridLengthTypeConverter().ConvertFromInvariantString("*"));
		((DefinitionCollection<ColumnDefinition>)grid19.GetValue(Grid.ColumnDefinitionsProperty)).Add(columnDefinition2);
		rowDefinition.SetValue(RowDefinition.HeightProperty, new GridLengthTypeConverter().ConvertFromInvariantString("1"));
		((DefinitionCollection<RowDefinition>)grid19.GetValue(Grid.RowDefinitionsProperty)).Add(rowDefinition);
		rowDefinition2.SetValue(RowDefinition.HeightProperty, new GridLengthTypeConverter().ConvertFromInvariantString("Auto"));
		((DefinitionCollection<RowDefinition>)grid19.GetValue(Grid.RowDefinitionsProperty)).Add(rowDefinition2);
		rowDefinition3.SetValue(RowDefinition.HeightProperty, new GridLengthTypeConverter().ConvertFromInvariantString("1"));
		((DefinitionCollection<RowDefinition>)grid19.GetValue(Grid.RowDefinitionsProperty)).Add(rowDefinition3);
		rowDefinition4.SetValue(RowDefinition.HeightProperty, new GridLengthTypeConverter().ConvertFromInvariantString("Auto"));
		((DefinitionCollection<RowDefinition>)grid19.GetValue(Grid.RowDefinitionsProperty)).Add(rowDefinition4);
		rowDefinition5.SetValue(RowDefinition.HeightProperty, new GridLengthTypeConverter().ConvertFromInvariantString("1"));
		((DefinitionCollection<RowDefinition>)grid19.GetValue(Grid.RowDefinitionsProperty)).Add(rowDefinition5);
		rowDefinition6.SetValue(RowDefinition.HeightProperty, new GridLengthTypeConverter().ConvertFromInvariantString("Auto"));
		((DefinitionCollection<RowDefinition>)grid19.GetValue(Grid.RowDefinitionsProperty)).Add(rowDefinition6);
		rowDefinition7.SetValue(RowDefinition.HeightProperty, new GridLengthTypeConverter().ConvertFromInvariantString("1"));
		((DefinitionCollection<RowDefinition>)grid19.GetValue(Grid.RowDefinitionsProperty)).Add(rowDefinition7);
		rowDefinition8.SetValue(RowDefinition.HeightProperty, new GridLengthTypeConverter().ConvertFromInvariantString("Auto"));
		((DefinitionCollection<RowDefinition>)grid19.GetValue(Grid.RowDefinitionsProperty)).Add(rowDefinition8);
		rowDefinition9.SetValue(RowDefinition.HeightProperty, new GridLengthTypeConverter().ConvertFromInvariantString("1"));
		((DefinitionCollection<RowDefinition>)grid19.GetValue(Grid.RowDefinitionsProperty)).Add(rowDefinition9);
		rowDefinition10.SetValue(RowDefinition.HeightProperty, new GridLengthTypeConverter().ConvertFromInvariantString("Auto"));
		((DefinitionCollection<RowDefinition>)grid19.GetValue(Grid.RowDefinitionsProperty)).Add(rowDefinition10);
		rowDefinition11.SetValue(RowDefinition.HeightProperty, new GridLengthTypeConverter().ConvertFromInvariantString("1"));
		((DefinitionCollection<RowDefinition>)grid19.GetValue(Grid.RowDefinitionsProperty)).Add(rowDefinition11);
		rowDefinition12.SetValue(RowDefinition.HeightProperty, new GridLengthTypeConverter().ConvertFromInvariantString("Auto"));
		((DefinitionCollection<RowDefinition>)grid19.GetValue(Grid.RowDefinitionsProperty)).Add(rowDefinition12);
		rowDefinition13.SetValue(RowDefinition.HeightProperty, new GridLengthTypeConverter().ConvertFromInvariantString("1"));
		((DefinitionCollection<RowDefinition>)grid19.GetValue(Grid.RowDefinitionsProperty)).Add(rowDefinition13);
		rowDefinition14.SetValue(RowDefinition.HeightProperty, new GridLengthTypeConverter().ConvertFromInvariantString("Auto"));
		((DefinitionCollection<RowDefinition>)grid19.GetValue(Grid.RowDefinitionsProperty)).Add(rowDefinition14);
		rowDefinition15.SetValue(RowDefinition.HeightProperty, new GridLengthTypeConverter().ConvertFromInvariantString("1"));
		((DefinitionCollection<RowDefinition>)grid19.GetValue(Grid.RowDefinitionsProperty)).Add(rowDefinition15);
		rowDefinition16.SetValue(RowDefinition.HeightProperty, new GridLengthTypeConverter().ConvertFromInvariantString("Auto"));
		((DefinitionCollection<RowDefinition>)grid19.GetValue(Grid.RowDefinitionsProperty)).Add(rowDefinition16);
		rowDefinition17.SetValue(RowDefinition.HeightProperty, new GridLengthTypeConverter().ConvertFromInvariantString("1"));
		((DefinitionCollection<RowDefinition>)grid19.GetValue(Grid.RowDefinitionsProperty)).Add(rowDefinition17);
		rowDefinition18.SetValue(RowDefinition.HeightProperty, new GridLengthTypeConverter().ConvertFromInvariantString("Auto"));
		((DefinitionCollection<RowDefinition>)grid19.GetValue(Grid.RowDefinitionsProperty)).Add(rowDefinition18);
		((DefinitionCollection<RowDefinition>)grid19.GetValue(Grid.RowDefinitionsProperty)).Add(item);
		grid.SetValue(Grid.RowProperty, 2);
		grid.SetValue(Grid.ColumnProperty, 0);
		grid.SetValue(Grid.ColumnSpanProperty, 2);
		staticResourceExtension2.Key = "LineColor";
		XamlServiceProvider xamlServiceProvider2 = new XamlServiceProvider();
		Type typeFromHandle3 = typeof(IProvideValueTarget);
		object[] array2 = new object[0 + 5];
		array2[0] = grid;
		array2[1] = grid19;
		array2[2] = stackLayout;
		array2[3] = scrollView;
		array2[4] = compositionMeterDetailView;
		object service2;
		xamlServiceProvider2.Add(typeFromHandle3, service2 = new SimpleValueTargetProvider(array2, VisualElement.BackgroundColorProperty, nameScope));
		xamlServiceProvider2.Add(typeof(IReferenceProvider), service2);
		Type typeFromHandle4 = typeof(IXamlTypeResolver);
		XmlNamespaceResolver xmlNamespaceResolver2 = new XmlNamespaceResolver();
		xmlNamespaceResolver2.Add("", "http://xamarin.com/schemas/2014/forms");
		xmlNamespaceResolver2.Add("x", "http://schemas.microsoft.com/winfx/2009/xaml");
		xmlNamespaceResolver2.Add("effect", "clr-namespace:NHL.Views.Effect");
		xmlNamespaceResolver2.Add("calx", "clr-namespace:Caliburn.Micro.Xamarin.Forms;assembly=Caliburn.Micro.Platform.Xamarin.Forms");
		xamlServiceProvider2.Add(typeFromHandle4, new XamlTypeResolver(xmlNamespaceResolver2, typeof(CompositionMeterDetailView).GetTypeInfo().Assembly));
		xamlServiceProvider2.Add(typeof(IXmlLineInfoProvider), new XmlLineInfoProvider(new XmlLineInfo(65, 72)));
		object obj2 = ((IMarkupExtension)staticResourceExtension2).ProvideValue((IServiceProvider)xamlServiceProvider2);
		grid.BackgroundColor = (Color)obj2;
		VisualDiagnostics.RegisterSourceInfo(obj2, new Uri("Views/CompositionMeterDetailView.xaml", UriKind.RelativeOrAbsolute), 65, 72);
		grid.SetValue(Grid.RowSpacingProperty, 0.0);
		grid.SetValue(Grid.ColumnSpacingProperty, 0.0);
		grid19.Children.Add(grid);
		VisualDiagnostics.RegisterSourceInfo(grid, new Uri("Views/CompositionMeterDetailView.xaml", UriKind.RelativeOrAbsolute), 65, 18);
		grid2.SetValue(Grid.RowProperty, 4);
		grid2.SetValue(Grid.ColumnProperty, 0);
		grid2.SetValue(Grid.ColumnSpanProperty, 2);
		staticResourceExtension3.Key = "LineColor";
		XamlServiceProvider xamlServiceProvider3 = new XamlServiceProvider();
		Type typeFromHandle5 = typeof(IProvideValueTarget);
		object[] array3 = new object[0 + 5];
		array3[0] = grid2;
		array3[1] = grid19;
		array3[2] = stackLayout;
		array3[3] = scrollView;
		array3[4] = compositionMeterDetailView;
		object service3;
		xamlServiceProvider3.Add(typeFromHandle5, service3 = new SimpleValueTargetProvider(array3, VisualElement.BackgroundColorProperty, nameScope));
		xamlServiceProvider3.Add(typeof(IReferenceProvider), service3);
		Type typeFromHandle6 = typeof(IXamlTypeResolver);
		XmlNamespaceResolver xmlNamespaceResolver3 = new XmlNamespaceResolver();
		xmlNamespaceResolver3.Add("", "http://xamarin.com/schemas/2014/forms");
		xmlNamespaceResolver3.Add("x", "http://schemas.microsoft.com/winfx/2009/xaml");
		xmlNamespaceResolver3.Add("effect", "clr-namespace:NHL.Views.Effect");
		xmlNamespaceResolver3.Add("calx", "clr-namespace:Caliburn.Micro.Xamarin.Forms;assembly=Caliburn.Micro.Platform.Xamarin.Forms");
		xamlServiceProvider3.Add(typeFromHandle6, new XamlTypeResolver(xmlNamespaceResolver3, typeof(CompositionMeterDetailView).GetTypeInfo().Assembly));
		xamlServiceProvider3.Add(typeof(IXmlLineInfoProvider), new XmlLineInfoProvider(new XmlLineInfo(66, 72)));
		object obj3 = ((IMarkupExtension)staticResourceExtension3).ProvideValue((IServiceProvider)xamlServiceProvider3);
		grid2.BackgroundColor = (Color)obj3;
		VisualDiagnostics.RegisterSourceInfo(obj3, new Uri("Views/CompositionMeterDetailView.xaml", UriKind.RelativeOrAbsolute), 66, 72);
		grid2.SetValue(Grid.RowSpacingProperty, 0.0);
		grid2.SetValue(Grid.ColumnSpacingProperty, 0.0);
		grid19.Children.Add(grid2);
		VisualDiagnostics.RegisterSourceInfo(grid2, new Uri("Views/CompositionMeterDetailView.xaml", UriKind.RelativeOrAbsolute), 66, 18);
		grid3.SetValue(Grid.RowProperty, 6);
		grid3.SetValue(Grid.ColumnProperty, 0);
		grid3.SetValue(Grid.ColumnSpanProperty, 2);
		staticResourceExtension4.Key = "LineColor";
		XamlServiceProvider xamlServiceProvider4 = new XamlServiceProvider();
		Type typeFromHandle7 = typeof(IProvideValueTarget);
		object[] array4 = new object[0 + 5];
		array4[0] = grid3;
		array4[1] = grid19;
		array4[2] = stackLayout;
		array4[3] = scrollView;
		array4[4] = compositionMeterDetailView;
		object service4;
		xamlServiceProvider4.Add(typeFromHandle7, service4 = new SimpleValueTargetProvider(array4, VisualElement.BackgroundColorProperty, nameScope));
		xamlServiceProvider4.Add(typeof(IReferenceProvider), service4);
		Type typeFromHandle8 = typeof(IXamlTypeResolver);
		XmlNamespaceResolver xmlNamespaceResolver4 = new XmlNamespaceResolver();
		xmlNamespaceResolver4.Add("", "http://xamarin.com/schemas/2014/forms");
		xmlNamespaceResolver4.Add("x", "http://schemas.microsoft.com/winfx/2009/xaml");
		xmlNamespaceResolver4.Add("effect", "clr-namespace:NHL.Views.Effect");
		xmlNamespaceResolver4.Add("calx", "clr-namespace:Caliburn.Micro.Xamarin.Forms;assembly=Caliburn.Micro.Platform.Xamarin.Forms");
		xamlServiceProvider4.Add(typeFromHandle8, new XamlTypeResolver(xmlNamespaceResolver4, typeof(CompositionMeterDetailView).GetTypeInfo().Assembly));
		xamlServiceProvider4.Add(typeof(IXmlLineInfoProvider), new XmlLineInfoProvider(new XmlLineInfo(67, 72)));
		object obj4 = ((IMarkupExtension)staticResourceExtension4).ProvideValue((IServiceProvider)xamlServiceProvider4);
		grid3.BackgroundColor = (Color)obj4;
		VisualDiagnostics.RegisterSourceInfo(obj4, new Uri("Views/CompositionMeterDetailView.xaml", UriKind.RelativeOrAbsolute), 67, 72);
		grid3.SetValue(Grid.RowSpacingProperty, 0.0);
		grid3.SetValue(Grid.ColumnSpacingProperty, 0.0);
		grid19.Children.Add(grid3);
		VisualDiagnostics.RegisterSourceInfo(grid3, new Uri("Views/CompositionMeterDetailView.xaml", UriKind.RelativeOrAbsolute), 67, 18);
		grid4.SetValue(Grid.RowProperty, 8);
		grid4.SetValue(Grid.ColumnProperty, 0);
		grid4.SetValue(Grid.ColumnSpanProperty, 2);
		staticResourceExtension5.Key = "LineColor";
		XamlServiceProvider xamlServiceProvider5 = new XamlServiceProvider();
		Type typeFromHandle9 = typeof(IProvideValueTarget);
		object[] array5 = new object[0 + 5];
		array5[0] = grid4;
		array5[1] = grid19;
		array5[2] = stackLayout;
		array5[3] = scrollView;
		array5[4] = compositionMeterDetailView;
		object service5;
		xamlServiceProvider5.Add(typeFromHandle9, service5 = new SimpleValueTargetProvider(array5, VisualElement.BackgroundColorProperty, nameScope));
		xamlServiceProvider5.Add(typeof(IReferenceProvider), service5);
		Type typeFromHandle10 = typeof(IXamlTypeResolver);
		XmlNamespaceResolver xmlNamespaceResolver5 = new XmlNamespaceResolver();
		xmlNamespaceResolver5.Add("", "http://xamarin.com/schemas/2014/forms");
		xmlNamespaceResolver5.Add("x", "http://schemas.microsoft.com/winfx/2009/xaml");
		xmlNamespaceResolver5.Add("effect", "clr-namespace:NHL.Views.Effect");
		xmlNamespaceResolver5.Add("calx", "clr-namespace:Caliburn.Micro.Xamarin.Forms;assembly=Caliburn.Micro.Platform.Xamarin.Forms");
		xamlServiceProvider5.Add(typeFromHandle10, new XamlTypeResolver(xmlNamespaceResolver5, typeof(CompositionMeterDetailView).GetTypeInfo().Assembly));
		xamlServiceProvider5.Add(typeof(IXmlLineInfoProvider), new XmlLineInfoProvider(new XmlLineInfo(68, 72)));
		object obj5 = ((IMarkupExtension)staticResourceExtension5).ProvideValue((IServiceProvider)xamlServiceProvider5);
		grid4.BackgroundColor = (Color)obj5;
		VisualDiagnostics.RegisterSourceInfo(obj5, new Uri("Views/CompositionMeterDetailView.xaml", UriKind.RelativeOrAbsolute), 68, 72);
		grid4.SetValue(Grid.RowSpacingProperty, 0.0);
		grid4.SetValue(Grid.ColumnSpacingProperty, 0.0);
		grid19.Children.Add(grid4);
		VisualDiagnostics.RegisterSourceInfo(grid4, new Uri("Views/CompositionMeterDetailView.xaml", UriKind.RelativeOrAbsolute), 68, 18);
		grid5.SetValue(Grid.RowProperty, 10);
		grid5.SetValue(Grid.ColumnProperty, 0);
		grid5.SetValue(Grid.ColumnSpanProperty, 2);
		staticResourceExtension6.Key = "LineColor";
		XamlServiceProvider xamlServiceProvider6 = new XamlServiceProvider();
		Type typeFromHandle11 = typeof(IProvideValueTarget);
		object[] array6 = new object[0 + 5];
		array6[0] = grid5;
		array6[1] = grid19;
		array6[2] = stackLayout;
		array6[3] = scrollView;
		array6[4] = compositionMeterDetailView;
		object service6;
		xamlServiceProvider6.Add(typeFromHandle11, service6 = new SimpleValueTargetProvider(array6, VisualElement.BackgroundColorProperty, nameScope));
		xamlServiceProvider6.Add(typeof(IReferenceProvider), service6);
		Type typeFromHandle12 = typeof(IXamlTypeResolver);
		XmlNamespaceResolver xmlNamespaceResolver6 = new XmlNamespaceResolver();
		xmlNamespaceResolver6.Add("", "http://xamarin.com/schemas/2014/forms");
		xmlNamespaceResolver6.Add("x", "http://schemas.microsoft.com/winfx/2009/xaml");
		xmlNamespaceResolver6.Add("effect", "clr-namespace:NHL.Views.Effect");
		xmlNamespaceResolver6.Add("calx", "clr-namespace:Caliburn.Micro.Xamarin.Forms;assembly=Caliburn.Micro.Platform.Xamarin.Forms");
		xamlServiceProvider6.Add(typeFromHandle12, new XamlTypeResolver(xmlNamespaceResolver6, typeof(CompositionMeterDetailView).GetTypeInfo().Assembly));
		xamlServiceProvider6.Add(typeof(IXmlLineInfoProvider), new XmlLineInfoProvider(new XmlLineInfo(69, 73)));
		object obj6 = ((IMarkupExtension)staticResourceExtension6).ProvideValue((IServiceProvider)xamlServiceProvider6);
		grid5.BackgroundColor = (Color)obj6;
		VisualDiagnostics.RegisterSourceInfo(obj6, new Uri("Views/CompositionMeterDetailView.xaml", UriKind.RelativeOrAbsolute), 69, 73);
		grid5.SetValue(Grid.RowSpacingProperty, 0.0);
		grid5.SetValue(Grid.ColumnSpacingProperty, 0.0);
		grid19.Children.Add(grid5);
		VisualDiagnostics.RegisterSourceInfo(grid5, new Uri("Views/CompositionMeterDetailView.xaml", UriKind.RelativeOrAbsolute), 69, 18);
		grid6.SetValue(Grid.RowProperty, 12);
		grid6.SetValue(Grid.ColumnProperty, 0);
		grid6.SetValue(Grid.ColumnSpanProperty, 2);
		staticResourceExtension7.Key = "LineColor";
		XamlServiceProvider xamlServiceProvider7 = new XamlServiceProvider();
		Type typeFromHandle13 = typeof(IProvideValueTarget);
		object[] array7 = new object[0 + 5];
		array7[0] = grid6;
		array7[1] = grid19;
		array7[2] = stackLayout;
		array7[3] = scrollView;
		array7[4] = compositionMeterDetailView;
		object service7;
		xamlServiceProvider7.Add(typeFromHandle13, service7 = new SimpleValueTargetProvider(array7, VisualElement.BackgroundColorProperty, nameScope));
		xamlServiceProvider7.Add(typeof(IReferenceProvider), service7);
		Type typeFromHandle14 = typeof(IXamlTypeResolver);
		XmlNamespaceResolver xmlNamespaceResolver7 = new XmlNamespaceResolver();
		xmlNamespaceResolver7.Add("", "http://xamarin.com/schemas/2014/forms");
		xmlNamespaceResolver7.Add("x", "http://schemas.microsoft.com/winfx/2009/xaml");
		xmlNamespaceResolver7.Add("effect", "clr-namespace:NHL.Views.Effect");
		xmlNamespaceResolver7.Add("calx", "clr-namespace:Caliburn.Micro.Xamarin.Forms;assembly=Caliburn.Micro.Platform.Xamarin.Forms");
		xamlServiceProvider7.Add(typeFromHandle14, new XamlTypeResolver(xmlNamespaceResolver7, typeof(CompositionMeterDetailView).GetTypeInfo().Assembly));
		xamlServiceProvider7.Add(typeof(IXmlLineInfoProvider), new XmlLineInfoProvider(new XmlLineInfo(70, 73)));
		object obj7 = ((IMarkupExtension)staticResourceExtension7).ProvideValue((IServiceProvider)xamlServiceProvider7);
		grid6.BackgroundColor = (Color)obj7;
		VisualDiagnostics.RegisterSourceInfo(obj7, new Uri("Views/CompositionMeterDetailView.xaml", UriKind.RelativeOrAbsolute), 70, 73);
		grid6.SetValue(Grid.RowSpacingProperty, 0.0);
		grid6.SetValue(Grid.ColumnSpacingProperty, 0.0);
		grid19.Children.Add(grid6);
		VisualDiagnostics.RegisterSourceInfo(grid6, new Uri("Views/CompositionMeterDetailView.xaml", UriKind.RelativeOrAbsolute), 70, 18);
		grid7.SetValue(Grid.RowProperty, 14);
		grid7.SetValue(Grid.ColumnProperty, 0);
		grid7.SetValue(Grid.ColumnSpanProperty, 2);
		staticResourceExtension8.Key = "LineColor";
		XamlServiceProvider xamlServiceProvider8 = new XamlServiceProvider();
		Type typeFromHandle15 = typeof(IProvideValueTarget);
		object[] array8 = new object[0 + 5];
		array8[0] = grid7;
		array8[1] = grid19;
		array8[2] = stackLayout;
		array8[3] = scrollView;
		array8[4] = compositionMeterDetailView;
		object service8;
		xamlServiceProvider8.Add(typeFromHandle15, service8 = new SimpleValueTargetProvider(array8, VisualElement.BackgroundColorProperty, nameScope));
		xamlServiceProvider8.Add(typeof(IReferenceProvider), service8);
		Type typeFromHandle16 = typeof(IXamlTypeResolver);
		XmlNamespaceResolver xmlNamespaceResolver8 = new XmlNamespaceResolver();
		xmlNamespaceResolver8.Add("", "http://xamarin.com/schemas/2014/forms");
		xmlNamespaceResolver8.Add("x", "http://schemas.microsoft.com/winfx/2009/xaml");
		xmlNamespaceResolver8.Add("effect", "clr-namespace:NHL.Views.Effect");
		xmlNamespaceResolver8.Add("calx", "clr-namespace:Caliburn.Micro.Xamarin.Forms;assembly=Caliburn.Micro.Platform.Xamarin.Forms");
		xamlServiceProvider8.Add(typeFromHandle16, new XamlTypeResolver(xmlNamespaceResolver8, typeof(CompositionMeterDetailView).GetTypeInfo().Assembly));
		xamlServiceProvider8.Add(typeof(IXmlLineInfoProvider), new XmlLineInfoProvider(new XmlLineInfo(71, 73)));
		object obj8 = ((IMarkupExtension)staticResourceExtension8).ProvideValue((IServiceProvider)xamlServiceProvider8);
		grid7.BackgroundColor = (Color)obj8;
		VisualDiagnostics.RegisterSourceInfo(obj8, new Uri("Views/CompositionMeterDetailView.xaml", UriKind.RelativeOrAbsolute), 71, 73);
		grid7.SetValue(Grid.RowSpacingProperty, 0.0);
		grid7.SetValue(Grid.ColumnSpacingProperty, 0.0);
		grid19.Children.Add(grid7);
		VisualDiagnostics.RegisterSourceInfo(grid7, new Uri("Views/CompositionMeterDetailView.xaml", UriKind.RelativeOrAbsolute), 71, 18);
		grid8.SetValue(Grid.RowProperty, 16);
		grid8.SetValue(Grid.ColumnProperty, 0);
		grid8.SetValue(Grid.ColumnSpanProperty, 2);
		staticResourceExtension9.Key = "LineColor";
		XamlServiceProvider xamlServiceProvider9 = new XamlServiceProvider();
		Type typeFromHandle17 = typeof(IProvideValueTarget);
		object[] array9 = new object[0 + 5];
		array9[0] = grid8;
		array9[1] = grid19;
		array9[2] = stackLayout;
		array9[3] = scrollView;
		array9[4] = compositionMeterDetailView;
		object service9;
		xamlServiceProvider9.Add(typeFromHandle17, service9 = new SimpleValueTargetProvider(array9, VisualElement.BackgroundColorProperty, nameScope));
		xamlServiceProvider9.Add(typeof(IReferenceProvider), service9);
		Type typeFromHandle18 = typeof(IXamlTypeResolver);
		XmlNamespaceResolver xmlNamespaceResolver9 = new XmlNamespaceResolver();
		xmlNamespaceResolver9.Add("", "http://xamarin.com/schemas/2014/forms");
		xmlNamespaceResolver9.Add("x", "http://schemas.microsoft.com/winfx/2009/xaml");
		xmlNamespaceResolver9.Add("effect", "clr-namespace:NHL.Views.Effect");
		xmlNamespaceResolver9.Add("calx", "clr-namespace:Caliburn.Micro.Xamarin.Forms;assembly=Caliburn.Micro.Platform.Xamarin.Forms");
		xamlServiceProvider9.Add(typeFromHandle18, new XamlTypeResolver(xmlNamespaceResolver9, typeof(CompositionMeterDetailView).GetTypeInfo().Assembly));
		xamlServiceProvider9.Add(typeof(IXmlLineInfoProvider), new XmlLineInfoProvider(new XmlLineInfo(72, 73)));
		object obj9 = ((IMarkupExtension)staticResourceExtension9).ProvideValue((IServiceProvider)xamlServiceProvider9);
		grid8.BackgroundColor = (Color)obj9;
		VisualDiagnostics.RegisterSourceInfo(obj9, new Uri("Views/CompositionMeterDetailView.xaml", UriKind.RelativeOrAbsolute), 72, 73);
		grid8.SetValue(Grid.RowSpacingProperty, 0.0);
		grid8.SetValue(Grid.ColumnSpacingProperty, 0.0);
		grid19.Children.Add(grid8);
		VisualDiagnostics.RegisterSourceInfo(grid8, new Uri("Views/CompositionMeterDetailView.xaml", UriKind.RelativeOrAbsolute), 72, 18);
		grid9.SetValue(Grid.RowProperty, 18);
		grid9.SetValue(Grid.ColumnProperty, 0);
		grid9.SetValue(Grid.ColumnSpanProperty, 2);
		staticResourceExtension10.Key = "LineColor";
		XamlServiceProvider xamlServiceProvider10 = new XamlServiceProvider();
		Type typeFromHandle19 = typeof(IProvideValueTarget);
		object[] array10 = new object[0 + 5];
		array10[0] = grid9;
		array10[1] = grid19;
		array10[2] = stackLayout;
		array10[3] = scrollView;
		array10[4] = compositionMeterDetailView;
		object service10;
		xamlServiceProvider10.Add(typeFromHandle19, service10 = new SimpleValueTargetProvider(array10, VisualElement.BackgroundColorProperty, nameScope));
		xamlServiceProvider10.Add(typeof(IReferenceProvider), service10);
		Type typeFromHandle20 = typeof(IXamlTypeResolver);
		XmlNamespaceResolver xmlNamespaceResolver10 = new XmlNamespaceResolver();
		xmlNamespaceResolver10.Add("", "http://xamarin.com/schemas/2014/forms");
		xmlNamespaceResolver10.Add("x", "http://schemas.microsoft.com/winfx/2009/xaml");
		xmlNamespaceResolver10.Add("effect", "clr-namespace:NHL.Views.Effect");
		xmlNamespaceResolver10.Add("calx", "clr-namespace:Caliburn.Micro.Xamarin.Forms;assembly=Caliburn.Micro.Platform.Xamarin.Forms");
		xamlServiceProvider10.Add(typeFromHandle20, new XamlTypeResolver(xmlNamespaceResolver10, typeof(CompositionMeterDetailView).GetTypeInfo().Assembly));
		xamlServiceProvider10.Add(typeof(IXmlLineInfoProvider), new XmlLineInfoProvider(new XmlLineInfo(73, 73)));
		object obj10 = ((IMarkupExtension)staticResourceExtension10).ProvideValue((IServiceProvider)xamlServiceProvider10);
		grid9.BackgroundColor = (Color)obj10;
		VisualDiagnostics.RegisterSourceInfo(obj10, new Uri("Views/CompositionMeterDetailView.xaml", UriKind.RelativeOrAbsolute), 73, 73);
		grid9.SetValue(Grid.RowSpacingProperty, 0.0);
		grid9.SetValue(Grid.ColumnSpacingProperty, 0.0);
		grid19.Children.Add(grid9);
		VisualDiagnostics.RegisterSourceInfo(grid9, new Uri("Views/CompositionMeterDetailView.xaml", UriKind.RelativeOrAbsolute), 73, 18);
		grid10.SetValue(Grid.RowProperty, 1);
		grid10.SetValue(Grid.ColumnProperty, 0);
		grid10.SetValue(Grid.ColumnSpanProperty, 2);
		grid10.SetValue(VisualElement.BackgroundColorProperty, Color.White);
		grid10.SetValue(Grid.RowSpacingProperty, 0.0);
		grid10.SetValue(Grid.ColumnSpacingProperty, 0.0);
		grid19.Children.Add(grid10);
		VisualDiagnostics.RegisterSourceInfo(grid10, new Uri("Views/CompositionMeterDetailView.xaml", UriKind.RelativeOrAbsolute), 76, 18);
		grid11.SetValue(Grid.RowProperty, 3);
		grid11.SetValue(Grid.ColumnProperty, 0);
		grid11.SetValue(Grid.ColumnSpanProperty, 2);
		grid11.SetValue(VisualElement.BackgroundColorProperty, Color.White);
		grid11.SetValue(Grid.RowSpacingProperty, 0.0);
		grid11.SetValue(Grid.ColumnSpacingProperty, 0.0);
		grid19.Children.Add(grid11);
		VisualDiagnostics.RegisterSourceInfo(grid11, new Uri("Views/CompositionMeterDetailView.xaml", UriKind.RelativeOrAbsolute), 77, 18);
		grid12.SetValue(Grid.RowProperty, 5);
		grid12.SetValue(Grid.ColumnProperty, 0);
		grid12.SetValue(Grid.ColumnSpanProperty, 2);
		grid12.SetValue(VisualElement.BackgroundColorProperty, Color.White);
		grid12.SetValue(Grid.RowSpacingProperty, 0.0);
		grid12.SetValue(Grid.ColumnSpacingProperty, 0.0);
		grid19.Children.Add(grid12);
		VisualDiagnostics.RegisterSourceInfo(grid12, new Uri("Views/CompositionMeterDetailView.xaml", UriKind.RelativeOrAbsolute), 78, 18);
		grid13.SetValue(Grid.RowProperty, 7);
		grid13.SetValue(Grid.ColumnProperty, 0);
		grid13.SetValue(Grid.ColumnSpanProperty, 2);
		grid13.SetValue(VisualElement.BackgroundColorProperty, Color.White);
		grid13.SetValue(Grid.RowSpacingProperty, 0.0);
		grid13.SetValue(Grid.ColumnSpacingProperty, 0.0);
		grid19.Children.Add(grid13);
		VisualDiagnostics.RegisterSourceInfo(grid13, new Uri("Views/CompositionMeterDetailView.xaml", UriKind.RelativeOrAbsolute), 79, 18);
		grid14.SetValue(Grid.RowProperty, 9);
		grid14.SetValue(Grid.ColumnProperty, 0);
		grid14.SetValue(Grid.ColumnSpanProperty, 2);
		grid14.SetValue(VisualElement.BackgroundColorProperty, Color.White);
		grid14.SetValue(Grid.RowSpacingProperty, 0.0);
		grid14.SetValue(Grid.ColumnSpacingProperty, 0.0);
		grid19.Children.Add(grid14);
		VisualDiagnostics.RegisterSourceInfo(grid14, new Uri("Views/CompositionMeterDetailView.xaml", UriKind.RelativeOrAbsolute), 80, 18);
		grid15.SetValue(Grid.RowProperty, 11);
		grid15.SetValue(Grid.ColumnProperty, 0);
		grid15.SetValue(Grid.ColumnSpanProperty, 2);
		grid15.SetValue(VisualElement.BackgroundColorProperty, Color.White);
		grid15.SetValue(Grid.RowSpacingProperty, 0.0);
		grid15.SetValue(Grid.ColumnSpacingProperty, 0.0);
		grid19.Children.Add(grid15);
		VisualDiagnostics.RegisterSourceInfo(grid15, new Uri("Views/CompositionMeterDetailView.xaml", UriKind.RelativeOrAbsolute), 81, 18);
		grid16.SetValue(Grid.RowProperty, 13);
		grid16.SetValue(Grid.ColumnProperty, 0);
		grid16.SetValue(Grid.ColumnSpanProperty, 2);
		grid16.SetValue(VisualElement.BackgroundColorProperty, Color.White);
		grid16.SetValue(Grid.RowSpacingProperty, 0.0);
		grid16.SetValue(Grid.ColumnSpacingProperty, 0.0);
		grid19.Children.Add(grid16);
		VisualDiagnostics.RegisterSourceInfo(grid16, new Uri("Views/CompositionMeterDetailView.xaml", UriKind.RelativeOrAbsolute), 82, 18);
		grid17.SetValue(Grid.RowProperty, 15);
		grid17.SetValue(Grid.ColumnProperty, 0);
		grid17.SetValue(Grid.ColumnSpanProperty, 2);
		grid17.SetValue(VisualElement.BackgroundColorProperty, Color.White);
		grid17.SetValue(Grid.RowSpacingProperty, 0.0);
		grid17.SetValue(Grid.ColumnSpacingProperty, 0.0);
		grid19.Children.Add(grid17);
		VisualDiagnostics.RegisterSourceInfo(grid17, new Uri("Views/CompositionMeterDetailView.xaml", UriKind.RelativeOrAbsolute), 83, 18);
		grid18.SetValue(Grid.RowProperty, 17);
		grid18.SetValue(Grid.ColumnProperty, 0);
		grid18.SetValue(Grid.ColumnSpanProperty, 2);
		grid18.SetValue(VisualElement.BackgroundColorProperty, Color.White);
		grid18.SetValue(Grid.RowSpacingProperty, 0.0);
		grid18.SetValue(Grid.ColumnSpacingProperty, 0.0);
		grid19.Children.Add(grid18);
		VisualDiagnostics.RegisterSourceInfo(grid18, new Uri("Views/CompositionMeterDetailView.xaml", UriKind.RelativeOrAbsolute), 84, 18);
		label.SetValue(Grid.RowProperty, 1);
		label.SetValue(Grid.ColumnProperty, 0);
		label.SetValue(Xamarin.Forms.View.MarginProperty, new Thickness(10.0, 5.0, 0.0, 5.0));
		bindingExtension.Path = "TextWeight";
		BindingBase binding = ((IMarkupExtension<BindingBase>)bindingExtension).ProvideValue((IServiceProvider)null);
		label.SetBinding(Label.TextProperty, binding);
		BindableProperty fontSizeProperty = Label.FontSizeProperty;
		FontSizeConverter fontSizeConverter = new FontSizeConverter();
		XamlServiceProvider xamlServiceProvider11 = new XamlServiceProvider();
		Type typeFromHandle21 = typeof(IProvideValueTarget);
		object[] array11 = new object[0 + 5];
		array11[0] = label;
		array11[1] = grid19;
		array11[2] = stackLayout;
		array11[3] = scrollView;
		array11[4] = compositionMeterDetailView;
		object service11;
		xamlServiceProvider11.Add(typeFromHandle21, service11 = new SimpleValueTargetProvider(array11, Label.FontSizeProperty, nameScope));
		xamlServiceProvider11.Add(typeof(IReferenceProvider), service11);
		Type typeFromHandle22 = typeof(IXamlTypeResolver);
		XmlNamespaceResolver xmlNamespaceResolver11 = new XmlNamespaceResolver();
		xmlNamespaceResolver11.Add("", "http://xamarin.com/schemas/2014/forms");
		xmlNamespaceResolver11.Add("x", "http://schemas.microsoft.com/winfx/2009/xaml");
		xmlNamespaceResolver11.Add("effect", "clr-namespace:NHL.Views.Effect");
		xmlNamespaceResolver11.Add("calx", "clr-namespace:Caliburn.Micro.Xamarin.Forms;assembly=Caliburn.Micro.Platform.Xamarin.Forms");
		xamlServiceProvider11.Add(typeFromHandle22, new XamlTypeResolver(xmlNamespaceResolver11, typeof(CompositionMeterDetailView).GetTypeInfo().Assembly));
		xamlServiceProvider11.Add(typeof(IXmlLineInfoProvider), new XmlLineInfoProvider(new XmlLineInfo(87, 99)));
		label.SetValue(fontSizeProperty, ((IExtendedTypeConverter)fontSizeConverter).ConvertFromInvariantString("Large", (IServiceProvider)xamlServiceProvider11));
		label.SetValue(Xamarin.Forms.View.HorizontalOptionsProperty, LayoutOptions.Start);
		label.Effects.Add(fixedFontSizeLabelEffect);
		VisualDiagnostics.RegisterSourceInfo(fixedFontSizeLabelEffect, new Uri("Views/CompositionMeterDetailView.xaml", UriKind.RelativeOrAbsolute), 89, 26);
		grid19.Children.Add(label);
		VisualDiagnostics.RegisterSourceInfo(label, new Uri("Views/CompositionMeterDetailView.xaml", UriKind.RelativeOrAbsolute), 87, 18);
		label2.SetValue(Grid.RowProperty, 3);
		label2.SetValue(Grid.ColumnProperty, 0);
		label2.SetValue(Xamarin.Forms.View.MarginProperty, new Thickness(10.0, 5.0, 0.0, 5.0));
		bindingExtension2.Path = "TextBmi";
		BindingBase binding2 = ((IMarkupExtension<BindingBase>)bindingExtension2).ProvideValue((IServiceProvider)null);
		label2.SetBinding(Label.TextProperty, binding2);
		BindableProperty fontSizeProperty2 = Label.FontSizeProperty;
		FontSizeConverter fontSizeConverter2 = new FontSizeConverter();
		XamlServiceProvider xamlServiceProvider12 = new XamlServiceProvider();
		Type typeFromHandle23 = typeof(IProvideValueTarget);
		object[] array12 = new object[0 + 5];
		array12[0] = label2;
		array12[1] = grid19;
		array12[2] = stackLayout;
		array12[3] = scrollView;
		array12[4] = compositionMeterDetailView;
		object service12;
		xamlServiceProvider12.Add(typeFromHandle23, service12 = new SimpleValueTargetProvider(array12, Label.FontSizeProperty, nameScope));
		xamlServiceProvider12.Add(typeof(IReferenceProvider), service12);
		Type typeFromHandle24 = typeof(IXamlTypeResolver);
		XmlNamespaceResolver xmlNamespaceResolver12 = new XmlNamespaceResolver();
		xmlNamespaceResolver12.Add("", "http://xamarin.com/schemas/2014/forms");
		xmlNamespaceResolver12.Add("x", "http://schemas.microsoft.com/winfx/2009/xaml");
		xmlNamespaceResolver12.Add("effect", "clr-namespace:NHL.Views.Effect");
		xmlNamespaceResolver12.Add("calx", "clr-namespace:Caliburn.Micro.Xamarin.Forms;assembly=Caliburn.Micro.Platform.Xamarin.Forms");
		xamlServiceProvider12.Add(typeFromHandle24, new XamlTypeResolver(xmlNamespaceResolver12, typeof(CompositionMeterDetailView).GetTypeInfo().Assembly));
		xamlServiceProvider12.Add(typeof(IXmlLineInfoProvider), new XmlLineInfoProvider(new XmlLineInfo(92, 96)));
		label2.SetValue(fontSizeProperty2, ((IExtendedTypeConverter)fontSizeConverter2).ConvertFromInvariantString("Large", (IServiceProvider)xamlServiceProvider12));
		label2.SetValue(Xamarin.Forms.View.HorizontalOptionsProperty, LayoutOptions.Start);
		label2.Effects.Add(fixedFontSizeLabelEffect2);
		VisualDiagnostics.RegisterSourceInfo(fixedFontSizeLabelEffect2, new Uri("Views/CompositionMeterDetailView.xaml", UriKind.RelativeOrAbsolute), 94, 26);
		grid19.Children.Add(label2);
		VisualDiagnostics.RegisterSourceInfo(label2, new Uri("Views/CompositionMeterDetailView.xaml", UriKind.RelativeOrAbsolute), 92, 18);
		label3.SetValue(Grid.RowProperty, 5);
		label3.SetValue(Grid.ColumnProperty, 0);
		label3.SetValue(Xamarin.Forms.View.MarginProperty, new Thickness(10.0, 5.0, 0.0, 5.0));
		bindingExtension3.Path = "TextFatPercentage";
		BindingBase binding3 = ((IMarkupExtension<BindingBase>)bindingExtension3).ProvideValue((IServiceProvider)null);
		label3.SetBinding(Label.TextProperty, binding3);
		BindableProperty fontSizeProperty3 = Label.FontSizeProperty;
		FontSizeConverter fontSizeConverter3 = new FontSizeConverter();
		XamlServiceProvider xamlServiceProvider13 = new XamlServiceProvider();
		Type typeFromHandle25 = typeof(IProvideValueTarget);
		object[] array13 = new object[0 + 5];
		array13[0] = label3;
		array13[1] = grid19;
		array13[2] = stackLayout;
		array13[3] = scrollView;
		array13[4] = compositionMeterDetailView;
		object service13;
		xamlServiceProvider13.Add(typeFromHandle25, service13 = new SimpleValueTargetProvider(array13, Label.FontSizeProperty, nameScope));
		xamlServiceProvider13.Add(typeof(IReferenceProvider), service13);
		Type typeFromHandle26 = typeof(IXamlTypeResolver);
		XmlNamespaceResolver xmlNamespaceResolver13 = new XmlNamespaceResolver();
		xmlNamespaceResolver13.Add("", "http://xamarin.com/schemas/2014/forms");
		xmlNamespaceResolver13.Add("x", "http://schemas.microsoft.com/winfx/2009/xaml");
		xmlNamespaceResolver13.Add("effect", "clr-namespace:NHL.Views.Effect");
		xmlNamespaceResolver13.Add("calx", "clr-namespace:Caliburn.Micro.Xamarin.Forms;assembly=Caliburn.Micro.Platform.Xamarin.Forms");
		xamlServiceProvider13.Add(typeFromHandle26, new XamlTypeResolver(xmlNamespaceResolver13, typeof(CompositionMeterDetailView).GetTypeInfo().Assembly));
		xamlServiceProvider13.Add(typeof(IXmlLineInfoProvider), new XmlLineInfoProvider(new XmlLineInfo(97, 106)));
		label3.SetValue(fontSizeProperty3, ((IExtendedTypeConverter)fontSizeConverter3).ConvertFromInvariantString("Large", (IServiceProvider)xamlServiceProvider13));
		label3.SetValue(Xamarin.Forms.View.HorizontalOptionsProperty, LayoutOptions.Start);
		label3.Effects.Add(fixedFontSizeLabelEffect3);
		VisualDiagnostics.RegisterSourceInfo(fixedFontSizeLabelEffect3, new Uri("Views/CompositionMeterDetailView.xaml", UriKind.RelativeOrAbsolute), 99, 26);
		grid19.Children.Add(label3);
		VisualDiagnostics.RegisterSourceInfo(label3, new Uri("Views/CompositionMeterDetailView.xaml", UriKind.RelativeOrAbsolute), 97, 18);
		label4.SetValue(Grid.RowProperty, 7);
		label4.SetValue(Grid.ColumnProperty, 0);
		label4.SetValue(Xamarin.Forms.View.MarginProperty, new Thickness(10.0, 5.0, 0.0, 5.0));
		bindingExtension4.Path = "TextFatMass";
		BindingBase binding4 = ((IMarkupExtension<BindingBase>)bindingExtension4).ProvideValue((IServiceProvider)null);
		label4.SetBinding(Label.TextProperty, binding4);
		BindableProperty fontSizeProperty4 = Label.FontSizeProperty;
		FontSizeConverter fontSizeConverter4 = new FontSizeConverter();
		XamlServiceProvider xamlServiceProvider14 = new XamlServiceProvider();
		Type typeFromHandle27 = typeof(IProvideValueTarget);
		object[] array14 = new object[0 + 5];
		array14[0] = label4;
		array14[1] = grid19;
		array14[2] = stackLayout;
		array14[3] = scrollView;
		array14[4] = compositionMeterDetailView;
		object service14;
		xamlServiceProvider14.Add(typeFromHandle27, service14 = new SimpleValueTargetProvider(array14, Label.FontSizeProperty, nameScope));
		xamlServiceProvider14.Add(typeof(IReferenceProvider), service14);
		Type typeFromHandle28 = typeof(IXamlTypeResolver);
		XmlNamespaceResolver xmlNamespaceResolver14 = new XmlNamespaceResolver();
		xmlNamespaceResolver14.Add("", "http://xamarin.com/schemas/2014/forms");
		xmlNamespaceResolver14.Add("x", "http://schemas.microsoft.com/winfx/2009/xaml");
		xmlNamespaceResolver14.Add("effect", "clr-namespace:NHL.Views.Effect");
		xmlNamespaceResolver14.Add("calx", "clr-namespace:Caliburn.Micro.Xamarin.Forms;assembly=Caliburn.Micro.Platform.Xamarin.Forms");
		xamlServiceProvider14.Add(typeFromHandle28, new XamlTypeResolver(xmlNamespaceResolver14, typeof(CompositionMeterDetailView).GetTypeInfo().Assembly));
		xamlServiceProvider14.Add(typeof(IXmlLineInfoProvider), new XmlLineInfoProvider(new XmlLineInfo(102, 100)));
		label4.SetValue(fontSizeProperty4, ((IExtendedTypeConverter)fontSizeConverter4).ConvertFromInvariantString("Large", (IServiceProvider)xamlServiceProvider14));
		label4.SetValue(Xamarin.Forms.View.HorizontalOptionsProperty, LayoutOptions.Start);
		label4.Effects.Add(fixedFontSizeLabelEffect4);
		VisualDiagnostics.RegisterSourceInfo(fixedFontSizeLabelEffect4, new Uri("Views/CompositionMeterDetailView.xaml", UriKind.RelativeOrAbsolute), 104, 26);
		grid19.Children.Add(label4);
		VisualDiagnostics.RegisterSourceInfo(label4, new Uri("Views/CompositionMeterDetailView.xaml", UriKind.RelativeOrAbsolute), 102, 18);
		label5.SetValue(Grid.RowProperty, 9);
		label5.SetValue(Grid.ColumnProperty, 0);
		label5.SetValue(Xamarin.Forms.View.MarginProperty, new Thickness(10.0, 5.0, 0.0, 5.0));
		bindingExtension5.Path = "TextMusclePercentage";
		BindingBase binding5 = ((IMarkupExtension<BindingBase>)bindingExtension5).ProvideValue((IServiceProvider)null);
		label5.SetBinding(Label.TextProperty, binding5);
		BindableProperty fontSizeProperty5 = Label.FontSizeProperty;
		FontSizeConverter fontSizeConverter5 = new FontSizeConverter();
		XamlServiceProvider xamlServiceProvider15 = new XamlServiceProvider();
		Type typeFromHandle29 = typeof(IProvideValueTarget);
		object[] array15 = new object[0 + 5];
		array15[0] = label5;
		array15[1] = grid19;
		array15[2] = stackLayout;
		array15[3] = scrollView;
		array15[4] = compositionMeterDetailView;
		object service15;
		xamlServiceProvider15.Add(typeFromHandle29, service15 = new SimpleValueTargetProvider(array15, Label.FontSizeProperty, nameScope));
		xamlServiceProvider15.Add(typeof(IReferenceProvider), service15);
		Type typeFromHandle30 = typeof(IXamlTypeResolver);
		XmlNamespaceResolver xmlNamespaceResolver15 = new XmlNamespaceResolver();
		xmlNamespaceResolver15.Add("", "http://xamarin.com/schemas/2014/forms");
		xmlNamespaceResolver15.Add("x", "http://schemas.microsoft.com/winfx/2009/xaml");
		xmlNamespaceResolver15.Add("effect", "clr-namespace:NHL.Views.Effect");
		xmlNamespaceResolver15.Add("calx", "clr-namespace:Caliburn.Micro.Xamarin.Forms;assembly=Caliburn.Micro.Platform.Xamarin.Forms");
		xamlServiceProvider15.Add(typeFromHandle30, new XamlTypeResolver(xmlNamespaceResolver15, typeof(CompositionMeterDetailView).GetTypeInfo().Assembly));
		xamlServiceProvider15.Add(typeof(IXmlLineInfoProvider), new XmlLineInfoProvider(new XmlLineInfo(107, 109)));
		label5.SetValue(fontSizeProperty5, ((IExtendedTypeConverter)fontSizeConverter5).ConvertFromInvariantString("Large", (IServiceProvider)xamlServiceProvider15));
		label5.SetValue(Xamarin.Forms.View.HorizontalOptionsProperty, LayoutOptions.Start);
		label5.Effects.Add(fixedFontSizeLabelEffect5);
		VisualDiagnostics.RegisterSourceInfo(fixedFontSizeLabelEffect5, new Uri("Views/CompositionMeterDetailView.xaml", UriKind.RelativeOrAbsolute), 109, 26);
		grid19.Children.Add(label5);
		VisualDiagnostics.RegisterSourceInfo(label5, new Uri("Views/CompositionMeterDetailView.xaml", UriKind.RelativeOrAbsolute), 107, 18);
		label6.SetValue(Grid.RowProperty, 11);
		label6.SetValue(Grid.ColumnProperty, 0);
		label6.SetValue(Xamarin.Forms.View.MarginProperty, new Thickness(10.0, 5.0, 0.0, 5.0));
		bindingExtension6.Path = "TextMuscleMass";
		BindingBase binding6 = ((IMarkupExtension<BindingBase>)bindingExtension6).ProvideValue((IServiceProvider)null);
		label6.SetBinding(Label.TextProperty, binding6);
		BindableProperty fontSizeProperty6 = Label.FontSizeProperty;
		FontSizeConverter fontSizeConverter6 = new FontSizeConverter();
		XamlServiceProvider xamlServiceProvider16 = new XamlServiceProvider();
		Type typeFromHandle31 = typeof(IProvideValueTarget);
		object[] array16 = new object[0 + 5];
		array16[0] = label6;
		array16[1] = grid19;
		array16[2] = stackLayout;
		array16[3] = scrollView;
		array16[4] = compositionMeterDetailView;
		object service16;
		xamlServiceProvider16.Add(typeFromHandle31, service16 = new SimpleValueTargetProvider(array16, Label.FontSizeProperty, nameScope));
		xamlServiceProvider16.Add(typeof(IReferenceProvider), service16);
		Type typeFromHandle32 = typeof(IXamlTypeResolver);
		XmlNamespaceResolver xmlNamespaceResolver16 = new XmlNamespaceResolver();
		xmlNamespaceResolver16.Add("", "http://xamarin.com/schemas/2014/forms");
		xmlNamespaceResolver16.Add("x", "http://schemas.microsoft.com/winfx/2009/xaml");
		xmlNamespaceResolver16.Add("effect", "clr-namespace:NHL.Views.Effect");
		xmlNamespaceResolver16.Add("calx", "clr-namespace:Caliburn.Micro.Xamarin.Forms;assembly=Caliburn.Micro.Platform.Xamarin.Forms");
		xamlServiceProvider16.Add(typeFromHandle32, new XamlTypeResolver(xmlNamespaceResolver16, typeof(CompositionMeterDetailView).GetTypeInfo().Assembly));
		xamlServiceProvider16.Add(typeof(IXmlLineInfoProvider), new XmlLineInfoProvider(new XmlLineInfo(112, 104)));
		label6.SetValue(fontSizeProperty6, ((IExtendedTypeConverter)fontSizeConverter6).ConvertFromInvariantString("Large", (IServiceProvider)xamlServiceProvider16));
		label6.SetValue(Xamarin.Forms.View.HorizontalOptionsProperty, LayoutOptions.Start);
		label6.Effects.Add(fixedFontSizeLabelEffect6);
		VisualDiagnostics.RegisterSourceInfo(fixedFontSizeLabelEffect6, new Uri("Views/CompositionMeterDetailView.xaml", UriKind.RelativeOrAbsolute), 114, 26);
		grid19.Children.Add(label6);
		VisualDiagnostics.RegisterSourceInfo(label6, new Uri("Views/CompositionMeterDetailView.xaml", UriKind.RelativeOrAbsolute), 112, 18);
		label7.SetValue(Grid.RowProperty, 13);
		label7.SetValue(Grid.ColumnProperty, 0);
		label7.SetValue(Xamarin.Forms.View.MarginProperty, new Thickness(10.0, 5.0, 0.0, 5.0));
		bindingExtension7.Path = "TextWaterPercentage";
		BindingBase binding7 = ((IMarkupExtension<BindingBase>)bindingExtension7).ProvideValue((IServiceProvider)null);
		label7.SetBinding(Label.TextProperty, binding7);
		BindableProperty fontSizeProperty7 = Label.FontSizeProperty;
		FontSizeConverter fontSizeConverter7 = new FontSizeConverter();
		XamlServiceProvider xamlServiceProvider17 = new XamlServiceProvider();
		Type typeFromHandle33 = typeof(IProvideValueTarget);
		object[] array17 = new object[0 + 5];
		array17[0] = label7;
		array17[1] = grid19;
		array17[2] = stackLayout;
		array17[3] = scrollView;
		array17[4] = compositionMeterDetailView;
		object service17;
		xamlServiceProvider17.Add(typeFromHandle33, service17 = new SimpleValueTargetProvider(array17, Label.FontSizeProperty, nameScope));
		xamlServiceProvider17.Add(typeof(IReferenceProvider), service17);
		Type typeFromHandle34 = typeof(IXamlTypeResolver);
		XmlNamespaceResolver xmlNamespaceResolver17 = new XmlNamespaceResolver();
		xmlNamespaceResolver17.Add("", "http://xamarin.com/schemas/2014/forms");
		xmlNamespaceResolver17.Add("x", "http://schemas.microsoft.com/winfx/2009/xaml");
		xmlNamespaceResolver17.Add("effect", "clr-namespace:NHL.Views.Effect");
		xmlNamespaceResolver17.Add("calx", "clr-namespace:Caliburn.Micro.Xamarin.Forms;assembly=Caliburn.Micro.Platform.Xamarin.Forms");
		xamlServiceProvider17.Add(typeFromHandle34, new XamlTypeResolver(xmlNamespaceResolver17, typeof(CompositionMeterDetailView).GetTypeInfo().Assembly));
		xamlServiceProvider17.Add(typeof(IXmlLineInfoProvider), new XmlLineInfoProvider(new XmlLineInfo(117, 109)));
		label7.SetValue(fontSizeProperty7, ((IExtendedTypeConverter)fontSizeConverter7).ConvertFromInvariantString("Large", (IServiceProvider)xamlServiceProvider17));
		label7.SetValue(Xamarin.Forms.View.HorizontalOptionsProperty, LayoutOptions.Start);
		label7.Effects.Add(fixedFontSizeLabelEffect7);
		VisualDiagnostics.RegisterSourceInfo(fixedFontSizeLabelEffect7, new Uri("Views/CompositionMeterDetailView.xaml", UriKind.RelativeOrAbsolute), 119, 26);
		grid19.Children.Add(label7);
		VisualDiagnostics.RegisterSourceInfo(label7, new Uri("Views/CompositionMeterDetailView.xaml", UriKind.RelativeOrAbsolute), 117, 18);
		label8.SetValue(Grid.RowProperty, 15);
		label8.SetValue(Grid.ColumnProperty, 0);
		label8.SetValue(Xamarin.Forms.View.MarginProperty, new Thickness(10.0, 5.0, 0.0, 5.0));
		bindingExtension8.Path = "TextWaterMass";
		BindingBase binding8 = ((IMarkupExtension<BindingBase>)bindingExtension8).ProvideValue((IServiceProvider)null);
		label8.SetBinding(Label.TextProperty, binding8);
		BindableProperty fontSizeProperty8 = Label.FontSizeProperty;
		FontSizeConverter fontSizeConverter8 = new FontSizeConverter();
		XamlServiceProvider xamlServiceProvider18 = new XamlServiceProvider();
		Type typeFromHandle35 = typeof(IProvideValueTarget);
		object[] array18 = new object[0 + 5];
		array18[0] = label8;
		array18[1] = grid19;
		array18[2] = stackLayout;
		array18[3] = scrollView;
		array18[4] = compositionMeterDetailView;
		object service18;
		xamlServiceProvider18.Add(typeFromHandle35, service18 = new SimpleValueTargetProvider(array18, Label.FontSizeProperty, nameScope));
		xamlServiceProvider18.Add(typeof(IReferenceProvider), service18);
		Type typeFromHandle36 = typeof(IXamlTypeResolver);
		XmlNamespaceResolver xmlNamespaceResolver18 = new XmlNamespaceResolver();
		xmlNamespaceResolver18.Add("", "http://xamarin.com/schemas/2014/forms");
		xmlNamespaceResolver18.Add("x", "http://schemas.microsoft.com/winfx/2009/xaml");
		xmlNamespaceResolver18.Add("effect", "clr-namespace:NHL.Views.Effect");
		xmlNamespaceResolver18.Add("calx", "clr-namespace:Caliburn.Micro.Xamarin.Forms;assembly=Caliburn.Micro.Platform.Xamarin.Forms");
		xamlServiceProvider18.Add(typeFromHandle36, new XamlTypeResolver(xmlNamespaceResolver18, typeof(CompositionMeterDetailView).GetTypeInfo().Assembly));
		xamlServiceProvider18.Add(typeof(IXmlLineInfoProvider), new XmlLineInfoProvider(new XmlLineInfo(122, 103)));
		label8.SetValue(fontSizeProperty8, ((IExtendedTypeConverter)fontSizeConverter8).ConvertFromInvariantString("Large", (IServiceProvider)xamlServiceProvider18));
		label8.SetValue(Xamarin.Forms.View.HorizontalOptionsProperty, LayoutOptions.Start);
		label8.Effects.Add(fixedFontSizeLabelEffect8);
		VisualDiagnostics.RegisterSourceInfo(fixedFontSizeLabelEffect8, new Uri("Views/CompositionMeterDetailView.xaml", UriKind.RelativeOrAbsolute), 124, 26);
		grid19.Children.Add(label8);
		VisualDiagnostics.RegisterSourceInfo(label8, new Uri("Views/CompositionMeterDetailView.xaml", UriKind.RelativeOrAbsolute), 122, 18);
		label9.SetValue(Grid.RowProperty, 17);
		label9.SetValue(Grid.ColumnProperty, 0);
		label9.SetValue(Xamarin.Forms.View.MarginProperty, new Thickness(10.0, 5.0, 0.0, 5.0));
		bindingExtension9.Path = "TextBasalMetabolism";
		BindingBase binding9 = ((IMarkupExtension<BindingBase>)bindingExtension9).ProvideValue((IServiceProvider)null);
		label9.SetBinding(Label.TextProperty, binding9);
		BindableProperty fontSizeProperty9 = Label.FontSizeProperty;
		FontSizeConverter fontSizeConverter9 = new FontSizeConverter();
		XamlServiceProvider xamlServiceProvider19 = new XamlServiceProvider();
		Type typeFromHandle37 = typeof(IProvideValueTarget);
		object[] array19 = new object[0 + 5];
		array19[0] = label9;
		array19[1] = grid19;
		array19[2] = stackLayout;
		array19[3] = scrollView;
		array19[4] = compositionMeterDetailView;
		object service19;
		xamlServiceProvider19.Add(typeFromHandle37, service19 = new SimpleValueTargetProvider(array19, Label.FontSizeProperty, nameScope));
		xamlServiceProvider19.Add(typeof(IReferenceProvider), service19);
		Type typeFromHandle38 = typeof(IXamlTypeResolver);
		XmlNamespaceResolver xmlNamespaceResolver19 = new XmlNamespaceResolver();
		xmlNamespaceResolver19.Add("", "http://xamarin.com/schemas/2014/forms");
		xmlNamespaceResolver19.Add("x", "http://schemas.microsoft.com/winfx/2009/xaml");
		xmlNamespaceResolver19.Add("effect", "clr-namespace:NHL.Views.Effect");
		xmlNamespaceResolver19.Add("calx", "clr-namespace:Caliburn.Micro.Xamarin.Forms;assembly=Caliburn.Micro.Platform.Xamarin.Forms");
		xamlServiceProvider19.Add(typeFromHandle38, new XamlTypeResolver(xmlNamespaceResolver19, typeof(CompositionMeterDetailView).GetTypeInfo().Assembly));
		xamlServiceProvider19.Add(typeof(IXmlLineInfoProvider), new XmlLineInfoProvider(new XmlLineInfo(127, 109)));
		label9.SetValue(fontSizeProperty9, ((IExtendedTypeConverter)fontSizeConverter9).ConvertFromInvariantString("Large", (IServiceProvider)xamlServiceProvider19));
		label9.SetValue(Xamarin.Forms.View.HorizontalOptionsProperty, LayoutOptions.Start);
		label9.Effects.Add(fixedFontSizeLabelEffect9);
		VisualDiagnostics.RegisterSourceInfo(fixedFontSizeLabelEffect9, new Uri("Views/CompositionMeterDetailView.xaml", UriKind.RelativeOrAbsolute), 129, 26);
		grid19.Children.Add(label9);
		VisualDiagnostics.RegisterSourceInfo(label9, new Uri("Views/CompositionMeterDetailView.xaml", UriKind.RelativeOrAbsolute), 127, 18);
		label10.SetValue(Grid.RowProperty, 1);
		label10.SetValue(Grid.ColumnProperty, 1);
		label10.SetValue(Xamarin.Forms.View.MarginProperty, new Thickness(10.0, 5.0, 0.0, 5.0));
		bindingExtension10.Path = "Weight";
		BindingBase binding10 = ((IMarkupExtension<BindingBase>)bindingExtension10).ProvideValue((IServiceProvider)null);
		label10.SetBinding(Label.TextProperty, binding10);
		BindableProperty fontSizeProperty10 = Label.FontSizeProperty;
		FontSizeConverter fontSizeConverter10 = new FontSizeConverter();
		XamlServiceProvider xamlServiceProvider20 = new XamlServiceProvider();
		Type typeFromHandle39 = typeof(IProvideValueTarget);
		object[] array20 = new object[0 + 5];
		array20[0] = label10;
		array20[1] = grid19;
		array20[2] = stackLayout;
		array20[3] = scrollView;
		array20[4] = compositionMeterDetailView;
		object service20;
		xamlServiceProvider20.Add(typeFromHandle39, service20 = new SimpleValueTargetProvider(array20, Label.FontSizeProperty, nameScope));
		xamlServiceProvider20.Add(typeof(IReferenceProvider), service20);
		Type typeFromHandle40 = typeof(IXamlTypeResolver);
		XmlNamespaceResolver xmlNamespaceResolver20 = new XmlNamespaceResolver();
		xmlNamespaceResolver20.Add("", "http://xamarin.com/schemas/2014/forms");
		xmlNamespaceResolver20.Add("x", "http://schemas.microsoft.com/winfx/2009/xaml");
		xmlNamespaceResolver20.Add("effect", "clr-namespace:NHL.Views.Effect");
		xmlNamespaceResolver20.Add("calx", "clr-namespace:Caliburn.Micro.Xamarin.Forms;assembly=Caliburn.Micro.Platform.Xamarin.Forms");
		xamlServiceProvider20.Add(typeFromHandle40, new XamlTypeResolver(xmlNamespaceResolver20, typeof(CompositionMeterDetailView).GetTypeInfo().Assembly));
		xamlServiceProvider20.Add(typeof(IXmlLineInfoProvider), new XmlLineInfoProvider(new XmlLineInfo(135, 95)));
		label10.SetValue(fontSizeProperty10, ((IExtendedTypeConverter)fontSizeConverter10).ConvertFromInvariantString("Large", (IServiceProvider)xamlServiceProvider20));
		label10.SetValue(Xamarin.Forms.View.HorizontalOptionsProperty, LayoutOptions.Start);
		label10.Effects.Add(fixedFontSizeLabelEffect10);
		VisualDiagnostics.RegisterSourceInfo(fixedFontSizeLabelEffect10, new Uri("Views/CompositionMeterDetailView.xaml", UriKind.RelativeOrAbsolute), 137, 26);
		grid19.Children.Add(label10);
		VisualDiagnostics.RegisterSourceInfo(label10, new Uri("Views/CompositionMeterDetailView.xaml", UriKind.RelativeOrAbsolute), 135, 18);
		label11.SetValue(Grid.RowProperty, 3);
		label11.SetValue(Grid.ColumnProperty, 1);
		label11.SetValue(Xamarin.Forms.View.MarginProperty, new Thickness(10.0, 5.0, 0.0, 5.0));
		bindingExtension11.Path = "Bmi";
		BindingBase binding11 = ((IMarkupExtension<BindingBase>)bindingExtension11).ProvideValue((IServiceProvider)null);
		label11.SetBinding(Label.TextProperty, binding11);
		BindableProperty fontSizeProperty11 = Label.FontSizeProperty;
		FontSizeConverter fontSizeConverter11 = new FontSizeConverter();
		XamlServiceProvider xamlServiceProvider21 = new XamlServiceProvider();
		Type typeFromHandle41 = typeof(IProvideValueTarget);
		object[] array21 = new object[0 + 5];
		array21[0] = label11;
		array21[1] = grid19;
		array21[2] = stackLayout;
		array21[3] = scrollView;
		array21[4] = compositionMeterDetailView;
		object service21;
		xamlServiceProvider21.Add(typeFromHandle41, service21 = new SimpleValueTargetProvider(array21, Label.FontSizeProperty, nameScope));
		xamlServiceProvider21.Add(typeof(IReferenceProvider), service21);
		Type typeFromHandle42 = typeof(IXamlTypeResolver);
		XmlNamespaceResolver xmlNamespaceResolver21 = new XmlNamespaceResolver();
		xmlNamespaceResolver21.Add("", "http://xamarin.com/schemas/2014/forms");
		xmlNamespaceResolver21.Add("x", "http://schemas.microsoft.com/winfx/2009/xaml");
		xmlNamespaceResolver21.Add("effect", "clr-namespace:NHL.Views.Effect");
		xmlNamespaceResolver21.Add("calx", "clr-namespace:Caliburn.Micro.Xamarin.Forms;assembly=Caliburn.Micro.Platform.Xamarin.Forms");
		xamlServiceProvider21.Add(typeFromHandle42, new XamlTypeResolver(xmlNamespaceResolver21, typeof(CompositionMeterDetailView).GetTypeInfo().Assembly));
		xamlServiceProvider21.Add(typeof(IXmlLineInfoProvider), new XmlLineInfoProvider(new XmlLineInfo(140, 92)));
		label11.SetValue(fontSizeProperty11, ((IExtendedTypeConverter)fontSizeConverter11).ConvertFromInvariantString("Large", (IServiceProvider)xamlServiceProvider21));
		label11.SetValue(Xamarin.Forms.View.HorizontalOptionsProperty, LayoutOptions.Start);
		label11.Effects.Add(fixedFontSizeLabelEffect11);
		VisualDiagnostics.RegisterSourceInfo(fixedFontSizeLabelEffect11, new Uri("Views/CompositionMeterDetailView.xaml", UriKind.RelativeOrAbsolute), 142, 26);
		grid19.Children.Add(label11);
		VisualDiagnostics.RegisterSourceInfo(label11, new Uri("Views/CompositionMeterDetailView.xaml", UriKind.RelativeOrAbsolute), 140, 18);
		label12.SetValue(Grid.RowProperty, 5);
		label12.SetValue(Grid.ColumnProperty, 1);
		label12.SetValue(Xamarin.Forms.View.MarginProperty, new Thickness(10.0, 5.0, 0.0, 5.0));
		bindingExtension12.Path = "FatPercentage";
		BindingBase binding12 = ((IMarkupExtension<BindingBase>)bindingExtension12).ProvideValue((IServiceProvider)null);
		label12.SetBinding(Label.TextProperty, binding12);
		BindableProperty fontSizeProperty12 = Label.FontSizeProperty;
		FontSizeConverter fontSizeConverter12 = new FontSizeConverter();
		XamlServiceProvider xamlServiceProvider22 = new XamlServiceProvider();
		Type typeFromHandle43 = typeof(IProvideValueTarget);
		object[] array22 = new object[0 + 5];
		array22[0] = label12;
		array22[1] = grid19;
		array22[2] = stackLayout;
		array22[3] = scrollView;
		array22[4] = compositionMeterDetailView;
		object service22;
		xamlServiceProvider22.Add(typeFromHandle43, service22 = new SimpleValueTargetProvider(array22, Label.FontSizeProperty, nameScope));
		xamlServiceProvider22.Add(typeof(IReferenceProvider), service22);
		Type typeFromHandle44 = typeof(IXamlTypeResolver);
		XmlNamespaceResolver xmlNamespaceResolver22 = new XmlNamespaceResolver();
		xmlNamespaceResolver22.Add("", "http://xamarin.com/schemas/2014/forms");
		xmlNamespaceResolver22.Add("x", "http://schemas.microsoft.com/winfx/2009/xaml");
		xmlNamespaceResolver22.Add("effect", "clr-namespace:NHL.Views.Effect");
		xmlNamespaceResolver22.Add("calx", "clr-namespace:Caliburn.Micro.Xamarin.Forms;assembly=Caliburn.Micro.Platform.Xamarin.Forms");
		xamlServiceProvider22.Add(typeFromHandle44, new XamlTypeResolver(xmlNamespaceResolver22, typeof(CompositionMeterDetailView).GetTypeInfo().Assembly));
		xamlServiceProvider22.Add(typeof(IXmlLineInfoProvider), new XmlLineInfoProvider(new XmlLineInfo(145, 102)));
		label12.SetValue(fontSizeProperty12, ((IExtendedTypeConverter)fontSizeConverter12).ConvertFromInvariantString("Large", (IServiceProvider)xamlServiceProvider22));
		label12.SetValue(Xamarin.Forms.View.HorizontalOptionsProperty, LayoutOptions.Start);
		label12.Effects.Add(fixedFontSizeLabelEffect12);
		VisualDiagnostics.RegisterSourceInfo(fixedFontSizeLabelEffect12, new Uri("Views/CompositionMeterDetailView.xaml", UriKind.RelativeOrAbsolute), 147, 26);
		grid19.Children.Add(label12);
		VisualDiagnostics.RegisterSourceInfo(label12, new Uri("Views/CompositionMeterDetailView.xaml", UriKind.RelativeOrAbsolute), 145, 18);
		label13.SetValue(Grid.RowProperty, 7);
		label13.SetValue(Grid.ColumnProperty, 1);
		label13.SetValue(Xamarin.Forms.View.MarginProperty, new Thickness(10.0, 5.0, 0.0, 5.0));
		bindingExtension13.Path = "FatMass";
		BindingBase binding13 = ((IMarkupExtension<BindingBase>)bindingExtension13).ProvideValue((IServiceProvider)null);
		label13.SetBinding(Label.TextProperty, binding13);
		BindableProperty fontSizeProperty13 = Label.FontSizeProperty;
		FontSizeConverter fontSizeConverter13 = new FontSizeConverter();
		XamlServiceProvider xamlServiceProvider23 = new XamlServiceProvider();
		Type typeFromHandle45 = typeof(IProvideValueTarget);
		object[] array23 = new object[0 + 5];
		array23[0] = label13;
		array23[1] = grid19;
		array23[2] = stackLayout;
		array23[3] = scrollView;
		array23[4] = compositionMeterDetailView;
		object service23;
		xamlServiceProvider23.Add(typeFromHandle45, service23 = new SimpleValueTargetProvider(array23, Label.FontSizeProperty, nameScope));
		xamlServiceProvider23.Add(typeof(IReferenceProvider), service23);
		Type typeFromHandle46 = typeof(IXamlTypeResolver);
		XmlNamespaceResolver xmlNamespaceResolver23 = new XmlNamespaceResolver();
		xmlNamespaceResolver23.Add("", "http://xamarin.com/schemas/2014/forms");
		xmlNamespaceResolver23.Add("x", "http://schemas.microsoft.com/winfx/2009/xaml");
		xmlNamespaceResolver23.Add("effect", "clr-namespace:NHL.Views.Effect");
		xmlNamespaceResolver23.Add("calx", "clr-namespace:Caliburn.Micro.Xamarin.Forms;assembly=Caliburn.Micro.Platform.Xamarin.Forms");
		xamlServiceProvider23.Add(typeFromHandle46, new XamlTypeResolver(xmlNamespaceResolver23, typeof(CompositionMeterDetailView).GetTypeInfo().Assembly));
		xamlServiceProvider23.Add(typeof(IXmlLineInfoProvider), new XmlLineInfoProvider(new XmlLineInfo(150, 96)));
		label13.SetValue(fontSizeProperty13, ((IExtendedTypeConverter)fontSizeConverter13).ConvertFromInvariantString("Large", (IServiceProvider)xamlServiceProvider23));
		label13.SetValue(Xamarin.Forms.View.HorizontalOptionsProperty, LayoutOptions.Start);
		label13.Effects.Add(fixedFontSizeLabelEffect13);
		VisualDiagnostics.RegisterSourceInfo(fixedFontSizeLabelEffect13, new Uri("Views/CompositionMeterDetailView.xaml", UriKind.RelativeOrAbsolute), 152, 26);
		grid19.Children.Add(label13);
		VisualDiagnostics.RegisterSourceInfo(label13, new Uri("Views/CompositionMeterDetailView.xaml", UriKind.RelativeOrAbsolute), 150, 18);
		label14.SetValue(Grid.RowProperty, 9);
		label14.SetValue(Grid.ColumnProperty, 1);
		label14.SetValue(Xamarin.Forms.View.MarginProperty, new Thickness(10.0, 5.0, 0.0, 5.0));
		bindingExtension14.Path = "MusclePercentage";
		BindingBase binding14 = ((IMarkupExtension<BindingBase>)bindingExtension14).ProvideValue((IServiceProvider)null);
		label14.SetBinding(Label.TextProperty, binding14);
		BindableProperty fontSizeProperty14 = Label.FontSizeProperty;
		FontSizeConverter fontSizeConverter14 = new FontSizeConverter();
		XamlServiceProvider xamlServiceProvider24 = new XamlServiceProvider();
		Type typeFromHandle47 = typeof(IProvideValueTarget);
		object[] array24 = new object[0 + 5];
		array24[0] = label14;
		array24[1] = grid19;
		array24[2] = stackLayout;
		array24[3] = scrollView;
		array24[4] = compositionMeterDetailView;
		object service24;
		xamlServiceProvider24.Add(typeFromHandle47, service24 = new SimpleValueTargetProvider(array24, Label.FontSizeProperty, nameScope));
		xamlServiceProvider24.Add(typeof(IReferenceProvider), service24);
		Type typeFromHandle48 = typeof(IXamlTypeResolver);
		XmlNamespaceResolver xmlNamespaceResolver24 = new XmlNamespaceResolver();
		xmlNamespaceResolver24.Add("", "http://xamarin.com/schemas/2014/forms");
		xmlNamespaceResolver24.Add("x", "http://schemas.microsoft.com/winfx/2009/xaml");
		xmlNamespaceResolver24.Add("effect", "clr-namespace:NHL.Views.Effect");
		xmlNamespaceResolver24.Add("calx", "clr-namespace:Caliburn.Micro.Xamarin.Forms;assembly=Caliburn.Micro.Platform.Xamarin.Forms");
		xamlServiceProvider24.Add(typeFromHandle48, new XamlTypeResolver(xmlNamespaceResolver24, typeof(CompositionMeterDetailView).GetTypeInfo().Assembly));
		xamlServiceProvider24.Add(typeof(IXmlLineInfoProvider), new XmlLineInfoProvider(new XmlLineInfo(155, 105)));
		label14.SetValue(fontSizeProperty14, ((IExtendedTypeConverter)fontSizeConverter14).ConvertFromInvariantString("Large", (IServiceProvider)xamlServiceProvider24));
		label14.SetValue(Xamarin.Forms.View.HorizontalOptionsProperty, LayoutOptions.Start);
		label14.Effects.Add(fixedFontSizeLabelEffect14);
		VisualDiagnostics.RegisterSourceInfo(fixedFontSizeLabelEffect14, new Uri("Views/CompositionMeterDetailView.xaml", UriKind.RelativeOrAbsolute), 157, 26);
		grid19.Children.Add(label14);
		VisualDiagnostics.RegisterSourceInfo(label14, new Uri("Views/CompositionMeterDetailView.xaml", UriKind.RelativeOrAbsolute), 155, 18);
		label15.SetValue(Grid.RowProperty, 11);
		label15.SetValue(Grid.ColumnProperty, 1);
		label15.SetValue(Xamarin.Forms.View.MarginProperty, new Thickness(10.0, 5.0, 0.0, 5.0));
		bindingExtension15.Path = "MuscleMass";
		BindingBase binding15 = ((IMarkupExtension<BindingBase>)bindingExtension15).ProvideValue((IServiceProvider)null);
		label15.SetBinding(Label.TextProperty, binding15);
		BindableProperty fontSizeProperty15 = Label.FontSizeProperty;
		FontSizeConverter fontSizeConverter15 = new FontSizeConverter();
		XamlServiceProvider xamlServiceProvider25 = new XamlServiceProvider();
		Type typeFromHandle49 = typeof(IProvideValueTarget);
		object[] array25 = new object[0 + 5];
		array25[0] = label15;
		array25[1] = grid19;
		array25[2] = stackLayout;
		array25[3] = scrollView;
		array25[4] = compositionMeterDetailView;
		object service25;
		xamlServiceProvider25.Add(typeFromHandle49, service25 = new SimpleValueTargetProvider(array25, Label.FontSizeProperty, nameScope));
		xamlServiceProvider25.Add(typeof(IReferenceProvider), service25);
		Type typeFromHandle50 = typeof(IXamlTypeResolver);
		XmlNamespaceResolver xmlNamespaceResolver25 = new XmlNamespaceResolver();
		xmlNamespaceResolver25.Add("", "http://xamarin.com/schemas/2014/forms");
		xmlNamespaceResolver25.Add("x", "http://schemas.microsoft.com/winfx/2009/xaml");
		xmlNamespaceResolver25.Add("effect", "clr-namespace:NHL.Views.Effect");
		xmlNamespaceResolver25.Add("calx", "clr-namespace:Caliburn.Micro.Xamarin.Forms;assembly=Caliburn.Micro.Platform.Xamarin.Forms");
		xamlServiceProvider25.Add(typeFromHandle50, new XamlTypeResolver(xmlNamespaceResolver25, typeof(CompositionMeterDetailView).GetTypeInfo().Assembly));
		xamlServiceProvider25.Add(typeof(IXmlLineInfoProvider), new XmlLineInfoProvider(new XmlLineInfo(160, 100)));
		label15.SetValue(fontSizeProperty15, ((IExtendedTypeConverter)fontSizeConverter15).ConvertFromInvariantString("Large", (IServiceProvider)xamlServiceProvider25));
		label15.SetValue(Xamarin.Forms.View.HorizontalOptionsProperty, LayoutOptions.Start);
		label15.Effects.Add(fixedFontSizeLabelEffect15);
		VisualDiagnostics.RegisterSourceInfo(fixedFontSizeLabelEffect15, new Uri("Views/CompositionMeterDetailView.xaml", UriKind.RelativeOrAbsolute), 162, 26);
		grid19.Children.Add(label15);
		VisualDiagnostics.RegisterSourceInfo(label15, new Uri("Views/CompositionMeterDetailView.xaml", UriKind.RelativeOrAbsolute), 160, 18);
		label16.SetValue(Grid.RowProperty, 13);
		label16.SetValue(Grid.ColumnProperty, 1);
		label16.SetValue(Xamarin.Forms.View.MarginProperty, new Thickness(10.0, 5.0, 0.0, 5.0));
		bindingExtension16.Path = "WaterPercentage";
		BindingBase binding16 = ((IMarkupExtension<BindingBase>)bindingExtension16).ProvideValue((IServiceProvider)null);
		label16.SetBinding(Label.TextProperty, binding16);
		BindableProperty fontSizeProperty16 = Label.FontSizeProperty;
		FontSizeConverter fontSizeConverter16 = new FontSizeConverter();
		XamlServiceProvider xamlServiceProvider26 = new XamlServiceProvider();
		Type typeFromHandle51 = typeof(IProvideValueTarget);
		object[] array26 = new object[0 + 5];
		array26[0] = label16;
		array26[1] = grid19;
		array26[2] = stackLayout;
		array26[3] = scrollView;
		array26[4] = compositionMeterDetailView;
		object service26;
		xamlServiceProvider26.Add(typeFromHandle51, service26 = new SimpleValueTargetProvider(array26, Label.FontSizeProperty, nameScope));
		xamlServiceProvider26.Add(typeof(IReferenceProvider), service26);
		Type typeFromHandle52 = typeof(IXamlTypeResolver);
		XmlNamespaceResolver xmlNamespaceResolver26 = new XmlNamespaceResolver();
		xmlNamespaceResolver26.Add("", "http://xamarin.com/schemas/2014/forms");
		xmlNamespaceResolver26.Add("x", "http://schemas.microsoft.com/winfx/2009/xaml");
		xmlNamespaceResolver26.Add("effect", "clr-namespace:NHL.Views.Effect");
		xmlNamespaceResolver26.Add("calx", "clr-namespace:Caliburn.Micro.Xamarin.Forms;assembly=Caliburn.Micro.Platform.Xamarin.Forms");
		xamlServiceProvider26.Add(typeFromHandle52, new XamlTypeResolver(xmlNamespaceResolver26, typeof(CompositionMeterDetailView).GetTypeInfo().Assembly));
		xamlServiceProvider26.Add(typeof(IXmlLineInfoProvider), new XmlLineInfoProvider(new XmlLineInfo(165, 105)));
		label16.SetValue(fontSizeProperty16, ((IExtendedTypeConverter)fontSizeConverter16).ConvertFromInvariantString("Large", (IServiceProvider)xamlServiceProvider26));
		label16.SetValue(Xamarin.Forms.View.HorizontalOptionsProperty, LayoutOptions.Start);
		label16.Effects.Add(fixedFontSizeLabelEffect16);
		VisualDiagnostics.RegisterSourceInfo(fixedFontSizeLabelEffect16, new Uri("Views/CompositionMeterDetailView.xaml", UriKind.RelativeOrAbsolute), 167, 26);
		grid19.Children.Add(label16);
		VisualDiagnostics.RegisterSourceInfo(label16, new Uri("Views/CompositionMeterDetailView.xaml", UriKind.RelativeOrAbsolute), 165, 18);
		label17.SetValue(Grid.RowProperty, 15);
		label17.SetValue(Grid.ColumnProperty, 1);
		label17.SetValue(Xamarin.Forms.View.MarginProperty, new Thickness(10.0, 5.0, 0.0, 5.0));
		bindingExtension17.Path = "WaterMass";
		BindingBase binding17 = ((IMarkupExtension<BindingBase>)bindingExtension17).ProvideValue((IServiceProvider)null);
		label17.SetBinding(Label.TextProperty, binding17);
		BindableProperty fontSizeProperty17 = Label.FontSizeProperty;
		FontSizeConverter fontSizeConverter17 = new FontSizeConverter();
		XamlServiceProvider xamlServiceProvider27 = new XamlServiceProvider();
		Type typeFromHandle53 = typeof(IProvideValueTarget);
		object[] array27 = new object[0 + 5];
		array27[0] = label17;
		array27[1] = grid19;
		array27[2] = stackLayout;
		array27[3] = scrollView;
		array27[4] = compositionMeterDetailView;
		object service27;
		xamlServiceProvider27.Add(typeFromHandle53, service27 = new SimpleValueTargetProvider(array27, Label.FontSizeProperty, nameScope));
		xamlServiceProvider27.Add(typeof(IReferenceProvider), service27);
		Type typeFromHandle54 = typeof(IXamlTypeResolver);
		XmlNamespaceResolver xmlNamespaceResolver27 = new XmlNamespaceResolver();
		xmlNamespaceResolver27.Add("", "http://xamarin.com/schemas/2014/forms");
		xmlNamespaceResolver27.Add("x", "http://schemas.microsoft.com/winfx/2009/xaml");
		xmlNamespaceResolver27.Add("effect", "clr-namespace:NHL.Views.Effect");
		xmlNamespaceResolver27.Add("calx", "clr-namespace:Caliburn.Micro.Xamarin.Forms;assembly=Caliburn.Micro.Platform.Xamarin.Forms");
		xamlServiceProvider27.Add(typeFromHandle54, new XamlTypeResolver(xmlNamespaceResolver27, typeof(CompositionMeterDetailView).GetTypeInfo().Assembly));
		xamlServiceProvider27.Add(typeof(IXmlLineInfoProvider), new XmlLineInfoProvider(new XmlLineInfo(170, 99)));
		label17.SetValue(fontSizeProperty17, ((IExtendedTypeConverter)fontSizeConverter17).ConvertFromInvariantString("Large", (IServiceProvider)xamlServiceProvider27));
		label17.SetValue(Xamarin.Forms.View.HorizontalOptionsProperty, LayoutOptions.Start);
		label17.Effects.Add(fixedFontSizeLabelEffect17);
		VisualDiagnostics.RegisterSourceInfo(fixedFontSizeLabelEffect17, new Uri("Views/CompositionMeterDetailView.xaml", UriKind.RelativeOrAbsolute), 172, 26);
		grid19.Children.Add(label17);
		VisualDiagnostics.RegisterSourceInfo(label17, new Uri("Views/CompositionMeterDetailView.xaml", UriKind.RelativeOrAbsolute), 170, 18);
		label18.SetValue(Grid.RowProperty, 17);
		label18.SetValue(Grid.ColumnProperty, 1);
		label18.SetValue(Xamarin.Forms.View.MarginProperty, new Thickness(10.0, 5.0, 0.0, 5.0));
		bindingExtension18.Path = "BasalMetabolism";
		BindingBase binding18 = ((IMarkupExtension<BindingBase>)bindingExtension18).ProvideValue((IServiceProvider)null);
		label18.SetBinding(Label.TextProperty, binding18);
		BindableProperty fontSizeProperty18 = Label.FontSizeProperty;
		FontSizeConverter fontSizeConverter18 = new FontSizeConverter();
		XamlServiceProvider xamlServiceProvider28 = new XamlServiceProvider();
		Type typeFromHandle55 = typeof(IProvideValueTarget);
		object[] array28 = new object[0 + 5];
		array28[0] = label18;
		array28[1] = grid19;
		array28[2] = stackLayout;
		array28[3] = scrollView;
		array28[4] = compositionMeterDetailView;
		object service28;
		xamlServiceProvider28.Add(typeFromHandle55, service28 = new SimpleValueTargetProvider(array28, Label.FontSizeProperty, nameScope));
		xamlServiceProvider28.Add(typeof(IReferenceProvider), service28);
		Type typeFromHandle56 = typeof(IXamlTypeResolver);
		XmlNamespaceResolver xmlNamespaceResolver28 = new XmlNamespaceResolver();
		xmlNamespaceResolver28.Add("", "http://xamarin.com/schemas/2014/forms");
		xmlNamespaceResolver28.Add("x", "http://schemas.microsoft.com/winfx/2009/xaml");
		xmlNamespaceResolver28.Add("effect", "clr-namespace:NHL.Views.Effect");
		xmlNamespaceResolver28.Add("calx", "clr-namespace:Caliburn.Micro.Xamarin.Forms;assembly=Caliburn.Micro.Platform.Xamarin.Forms");
		xamlServiceProvider28.Add(typeFromHandle56, new XamlTypeResolver(xmlNamespaceResolver28, typeof(CompositionMeterDetailView).GetTypeInfo().Assembly));
		xamlServiceProvider28.Add(typeof(IXmlLineInfoProvider), new XmlLineInfoProvider(new XmlLineInfo(175, 105)));
		label18.SetValue(fontSizeProperty18, ((IExtendedTypeConverter)fontSizeConverter18).ConvertFromInvariantString("Large", (IServiceProvider)xamlServiceProvider28));
		label18.SetValue(Xamarin.Forms.View.HorizontalOptionsProperty, LayoutOptions.Start);
		label18.Effects.Add(fixedFontSizeLabelEffect18);
		VisualDiagnostics.RegisterSourceInfo(fixedFontSizeLabelEffect18, new Uri("Views/CompositionMeterDetailView.xaml", UriKind.RelativeOrAbsolute), 177, 26);
		grid19.Children.Add(label18);
		VisualDiagnostics.RegisterSourceInfo(label18, new Uri("Views/CompositionMeterDetailView.xaml", UriKind.RelativeOrAbsolute), 175, 18);
		stackLayout.Children.Add(grid19);
		VisualDiagnostics.RegisterSourceInfo(grid19, new Uri("Views/CompositionMeterDetailView.xaml", UriKind.RelativeOrAbsolute), 37, 14);
		button.SetValue(Xamarin.Forms.View.MarginProperty, new Thickness(10.0, 10.0, 10.0, 5.0));
		button.SetValue(Button.TextProperty, "測定結果を削除");
		button.SetValue(Message.AttachProperty, "Delete");
		button.SetValue(Xamarin.Forms.View.HorizontalOptionsProperty, LayoutOptions.FillAndExpand);
		button.SetValue(Button.TextColorProperty, Color.White);
		staticResourceExtension11.Key = "WarnButtonColor";
		XamlServiceProvider xamlServiceProvider29 = new XamlServiceProvider();
		Type typeFromHandle57 = typeof(IProvideValueTarget);
		object[] array29 = new object[0 + 4];
		array29[0] = button;
		array29[1] = stackLayout;
		array29[2] = scrollView;
		array29[3] = compositionMeterDetailView;
		object service29;
		xamlServiceProvider29.Add(typeFromHandle57, service29 = new SimpleValueTargetProvider(array29, VisualElement.BackgroundColorProperty, nameScope));
		xamlServiceProvider29.Add(typeof(IReferenceProvider), service29);
		Type typeFromHandle58 = typeof(IXamlTypeResolver);
		XmlNamespaceResolver xmlNamespaceResolver29 = new XmlNamespaceResolver();
		xmlNamespaceResolver29.Add("", "http://xamarin.com/schemas/2014/forms");
		xmlNamespaceResolver29.Add("x", "http://schemas.microsoft.com/winfx/2009/xaml");
		xmlNamespaceResolver29.Add("effect", "clr-namespace:NHL.Views.Effect");
		xmlNamespaceResolver29.Add("calx", "clr-namespace:Caliburn.Micro.Xamarin.Forms;assembly=Caliburn.Micro.Platform.Xamarin.Forms");
		xamlServiceProvider29.Add(typeFromHandle58, new XamlTypeResolver(xmlNamespaceResolver29, typeof(CompositionMeterDetailView).GetTypeInfo().Assembly));
		xamlServiceProvider29.Add(typeof(IXmlLineInfoProvider), new XmlLineInfoProvider(new XmlLineInfo(182, 138)));
		object obj11 = ((IMarkupExtension)staticResourceExtension11).ProvideValue((IServiceProvider)xamlServiceProvider29);
		button.BackgroundColor = (Color)obj11;
		VisualDiagnostics.RegisterSourceInfo(obj11, new Uri("Views/CompositionMeterDetailView.xaml", UriKind.RelativeOrAbsolute), 182, 138);
		button.Effects.Add(fixedFontSizeButtonEffect);
		VisualDiagnostics.RegisterSourceInfo(fixedFontSizeButtonEffect, new Uri("Views/CompositionMeterDetailView.xaml", UriKind.RelativeOrAbsolute), 184, 22);
		stackLayout.Children.Add(button);
		VisualDiagnostics.RegisterSourceInfo(button, new Uri("Views/CompositionMeterDetailView.xaml", UriKind.RelativeOrAbsolute), 182, 14);
		scrollView.Content = stackLayout;
		VisualDiagnostics.RegisterSourceInfo(stackLayout, new Uri("Views/CompositionMeterDetailView.xaml", UriKind.RelativeOrAbsolute), 36, 10);
		compositionMeterDetailView.SetValue(ContentPage.ContentProperty, scrollView);
		VisualDiagnostics.RegisterSourceInfo(scrollView, new Uri("Views/CompositionMeterDetailView.xaml", UriKind.RelativeOrAbsolute), 35, 6);
		VisualDiagnostics.RegisterSourceInfo(compositionMeterDetailView, new Uri("Views/CompositionMeterDetailView.xaml", UriKind.RelativeOrAbsolute), 2, 2);
	}

	private void __InitComponentRuntime()
	{
		this.LoadFromXaml(typeof(CompositionMeterDetailView));
	}
}
