using System;
using System.CodeDom.Compiler;
using System.Reflection;
using Caliburn.Micro.Xamarin.Forms;
using NHL.Views.Converters;
using NHL.Views.Effect;
using NHL.Views.Renderer;
using Xamarin.Forms;
using Xamarin.Forms.Internals;
using Xamarin.Forms.Xaml;
using Xamarin.Forms.Xaml.Diagnostics;
using Xamarin.Forms.Xaml.Internals;

namespace NHL.Views;

[XamlCompilation(XamlCompilationOptions.Compile)]
[XamlFilePath("Views/GlucoseTargetRegistView.xaml")]
public class GlucoseTargetRegistView : ContentPage
{
	public GlucoseTargetRegistView()
	{
		InitializeComponent();
	}

	[GeneratedCode("Xamarin.Forms.Build.Tasks.XamlG", "2.0.0.0")]
	private void InitializeComponent()
	{
		if (ResourceLoader.CanProvideContentFor(new ResourceLoader.ResourceLoadingQuery
		{
			AssemblyName = typeof(GlucoseTargetRegistView).GetTypeInfo().Assembly.GetName(),
			ResourcePath = "Views/GlucoseTargetRegistView.xaml",
			Instance = this
		}))
		{
			__InitComponentRuntime();
			return;
		}
		if (XamlLoader.XamlFileProvider != null && XamlLoader.XamlFileProvider(GetType()) != null)
		{
			__InitComponentRuntime();
			return;
		}
		StaticResourceExtension staticResourceExtension = new StaticResourceExtension();
		GlucoseTargetThresholdToBisibleConverter value = new GlucoseTargetThresholdToBisibleConverter();
		Color color = Color.FromHex("#EFEFF4");
		Color color2 = Color.FromHex("#5B9BD5");
		Color color3 = Color.FromHex("#CFCFCF");
		Color color4 = Color.FromHex("#B4B4B4");
		ResourceDictionary resourceDictionary = new ResourceDictionary();
		RowDefinition rowDefinition = new RowDefinition();
		RowDefinition rowDefinition2 = new RowDefinition();
		RowDefinition rowDefinition3 = new RowDefinition();
		RowDefinition rowDefinition4 = new RowDefinition();
		RowDefinition rowDefinition5 = new RowDefinition();
		RowDefinition rowDefinition6 = new RowDefinition();
		ColumnDefinition columnDefinition = new ColumnDefinition();
		ColumnDefinition columnDefinition2 = new ColumnDefinition();
		ColumnDefinition columnDefinition3 = new ColumnDefinition();
		ColumnDefinition columnDefinition4 = new ColumnDefinition();
		FixedFontSizeLabelEffect fixedFontSizeLabelEffect = new FixedFontSizeLabelEffect();
		Label label = new Label();
		RowDefinition rowDefinition7 = new RowDefinition();
		RowDefinition rowDefinition8 = new RowDefinition();
		RowDefinition rowDefinition9 = new RowDefinition();
		StaticResourceExtension staticResourceExtension2 = new StaticResourceExtension();
		Grid grid = new Grid();
		Grid grid2 = new Grid();
		StaticResourceExtension staticResourceExtension3 = new StaticResourceExtension();
		StaticResourceExtension staticResourceExtension4 = new StaticResourceExtension();
		BindingExtension bindingExtension = new BindingExtension();
		FixedFontSizeLabelEffect fixedFontSizeLabelEffect2 = new FixedFontSizeLabelEffect();
		Label label2 = new Label();
		BindingExtension bindingExtension2 = new BindingExtension();
		BindingExtension bindingExtension3 = new BindingExtension();
		BindingExtension bindingExtension4 = new BindingExtension();
		FixedFontSizeTextBoxEffect fixedFontSizeTextBoxEffect = new FixedFontSizeTextBoxEffect();
		PickerView pickerView = new PickerView();
		FixedFontSizeLabelEffect fixedFontSizeLabelEffect3 = new FixedFontSizeLabelEffect();
		Label label3 = new Label();
		Grid grid3 = new Grid();
		ColumnDefinition columnDefinition5 = new ColumnDefinition();
		ColumnDefinition columnDefinition6 = new ColumnDefinition();
		ColumnDefinition columnDefinition7 = new ColumnDefinition();
		ColumnDefinition columnDefinition8 = new ColumnDefinition();
		RowDefinition rowDefinition10 = new RowDefinition();
		RowDefinition rowDefinition11 = new RowDefinition();
		RowDefinition rowDefinition12 = new RowDefinition();
		FixedFontSizeLabelEffect fixedFontSizeLabelEffect4 = new FixedFontSizeLabelEffect();
		Label label4 = new Label();
		FixedFontSizeLabelEffect fixedFontSizeLabelEffect5 = new FixedFontSizeLabelEffect();
		Label label5 = new Label();
		ColumnDefinition columnDefinition9 = new ColumnDefinition();
		ColumnDefinition columnDefinition10 = new ColumnDefinition();
		ColumnDefinition columnDefinition11 = new ColumnDefinition();
		FixedFontSizeLabelEffect fixedFontSizeLabelEffect6 = new FixedFontSizeLabelEffect();
		Label label6 = new Label();
		Grid grid4 = new Grid();
		ColumnDefinition columnDefinition12 = new ColumnDefinition();
		ColumnDefinition columnDefinition13 = new ColumnDefinition();
		ColumnDefinition columnDefinition14 = new ColumnDefinition();
		RowDefinition rowDefinition13 = new RowDefinition();
		RowDefinition rowDefinition14 = new RowDefinition();
		RowDefinition rowDefinition15 = new RowDefinition();
		RowDefinition rowDefinition16 = new RowDefinition();
		RowDefinition rowDefinition17 = new RowDefinition();
		StaticResourceExtension staticResourceExtension5 = new StaticResourceExtension();
		Grid grid5 = new Grid();
		Grid grid6 = new Grid();
		RowDefinition rowDefinition18 = new RowDefinition();
		RowDefinition rowDefinition19 = new RowDefinition();
		RowDefinition rowDefinition20 = new RowDefinition();
		RowDefinition rowDefinition21 = new RowDefinition();
		RowDefinition rowDefinition22 = new RowDefinition();
		StaticResourceExtension staticResourceExtension6 = new StaticResourceExtension();
		Grid grid7 = new Grid();
		Grid grid8 = new Grid();
		RowDefinition rowDefinition23 = new RowDefinition();
		RowDefinition rowDefinition24 = new RowDefinition();
		RowDefinition rowDefinition25 = new RowDefinition();
		RowDefinition rowDefinition26 = new RowDefinition();
		RowDefinition rowDefinition27 = new RowDefinition();
		StaticResourceExtension staticResourceExtension7 = new StaticResourceExtension();
		Grid grid9 = new Grid();
		StaticResourceExtension staticResourceExtension8 = new StaticResourceExtension();
		Grid grid10 = new Grid();
		Grid grid11 = new Grid();
		Grid grid12 = new Grid();
		StaticResourceExtension staticResourceExtension9 = new StaticResourceExtension();
		StaticResourceExtension staticResourceExtension10 = new StaticResourceExtension();
		BindingExtension bindingExtension5 = new BindingExtension();
		FixedFontSizeLabelEffect fixedFontSizeLabelEffect7 = new FixedFontSizeLabelEffect();
		Label label7 = new Label();
		BindingExtension bindingExtension6 = new BindingExtension();
		BindingExtension bindingExtension7 = new BindingExtension();
		BindingExtension bindingExtension8 = new BindingExtension();
		FixedFontSizeTextBoxEffect fixedFontSizeTextBoxEffect2 = new FixedFontSizeTextBoxEffect();
		PickerView pickerView2 = new PickerView();
		FixedFontSizeLabelEffect fixedFontSizeLabelEffect8 = new FixedFontSizeLabelEffect();
		Label label8 = new Label();
		StaticResourceExtension staticResourceExtension11 = new StaticResourceExtension();
		StaticResourceExtension staticResourceExtension12 = new StaticResourceExtension();
		BindingExtension bindingExtension9 = new BindingExtension();
		FixedFontSizeLabelEffect fixedFontSizeLabelEffect9 = new FixedFontSizeLabelEffect();
		Label label9 = new Label();
		BindingExtension bindingExtension10 = new BindingExtension();
		BindingExtension bindingExtension11 = new BindingExtension();
		BindingExtension bindingExtension12 = new BindingExtension();
		FixedFontSizeTextBoxEffect fixedFontSizeTextBoxEffect3 = new FixedFontSizeTextBoxEffect();
		PickerView pickerView3 = new PickerView();
		FixedFontSizeLabelEffect fixedFontSizeLabelEffect10 = new FixedFontSizeLabelEffect();
		Label label10 = new Label();
		Grid grid13 = new Grid();
		ColumnDefinition columnDefinition15 = new ColumnDefinition();
		ColumnDefinition columnDefinition16 = new ColumnDefinition();
		ColumnDefinition columnDefinition17 = new ColumnDefinition();
		ColumnDefinition columnDefinition18 = new ColumnDefinition();
		FixedFontSizeLabelEffect fixedFontSizeLabelEffect11 = new FixedFontSizeLabelEffect();
		Label label11 = new Label();
		RowDefinition rowDefinition28 = new RowDefinition();
		RowDefinition rowDefinition29 = new RowDefinition();
		RowDefinition rowDefinition30 = new RowDefinition();
		StaticResourceExtension staticResourceExtension13 = new StaticResourceExtension();
		Grid grid14 = new Grid();
		Grid grid15 = new Grid();
		StaticResourceExtension staticResourceExtension14 = new StaticResourceExtension();
		StaticResourceExtension staticResourceExtension15 = new StaticResourceExtension();
		BindingExtension bindingExtension13 = new BindingExtension();
		FixedFontSizeLabelEffect fixedFontSizeLabelEffect12 = new FixedFontSizeLabelEffect();
		Label label12 = new Label();
		BindingExtension bindingExtension14 = new BindingExtension();
		BindingExtension bindingExtension15 = new BindingExtension();
		BindingExtension bindingExtension16 = new BindingExtension();
		FixedFontSizeTextBoxEffect fixedFontSizeTextBoxEffect4 = new FixedFontSizeTextBoxEffect();
		PickerView pickerView4 = new PickerView();
		FixedFontSizeLabelEffect fixedFontSizeLabelEffect13 = new FixedFontSizeLabelEffect();
		Label label13 = new Label();
		Grid grid16 = new Grid();
		StaticResourceExtension staticResourceExtension16 = new StaticResourceExtension();
		FixedFontSizeButtonEffect fixedFontSizeButtonEffect = new FixedFontSizeButtonEffect();
		Button button = new Button();
		StaticResourceExtension staticResourceExtension17 = new StaticResourceExtension();
		FixedFontSizeButtonEffect fixedFontSizeButtonEffect2 = new FixedFontSizeButtonEffect();
		Button button2 = new Button();
		Grid grid17 = new Grid();
		GlucoseTargetRegistView glucoseTargetRegistView;
		NameScope nameScope = (NameScope)(NameScope.GetNameScope(glucoseTargetRegistView = this) ?? new NameScope());
		NameScope.SetNameScope(glucoseTargetRegistView, nameScope);
		glucoseTargetRegistView.Resources = resourceDictionary;
		VisualDiagnostics.RegisterSourceInfo(resourceDictionary, new Uri("Views/GlucoseTargetRegistView.xaml", UriKind.RelativeOrAbsolute), 15, 10);
		resourceDictionary.Add("GlucoseTargetThresholdToBisibleConverter", value);
		resourceDictionary.Add("PageBackgroundColor", color);
		resourceDictionary.Add("ButtonColor", color2);
		resourceDictionary.Add("LineColor", color3);
		resourceDictionary.Add("LabelColor", color4);
		glucoseTargetRegistView.SetValue(NavigationPage.HasBackButtonProperty, true);
		glucoseTargetRegistView.SetValue(NavigationPage.BackButtonTitleProperty, "戻る");
		glucoseTargetRegistView.SetValue(Page.TitleProperty, "目標値設定（血糖値）");
		staticResourceExtension.Key = "PageBackgroundColor";
		XamlServiceProvider xamlServiceProvider = new XamlServiceProvider();
		Type typeFromHandle = typeof(IProvideValueTarget);
		object[] array = new object[0 + 1];
		array[0] = glucoseTargetRegistView;
		object service;
		xamlServiceProvider.Add(typeFromHandle, service = new SimpleValueTargetProvider(array, VisualElement.BackgroundColorProperty, nameScope));
		xamlServiceProvider.Add(typeof(IReferenceProvider), service);
		Type typeFromHandle2 = typeof(IXamlTypeResolver);
		XmlNamespaceResolver xmlNamespaceResolver = new XmlNamespaceResolver();
		xmlNamespaceResolver.Add("", "http://xamarin.com/schemas/2014/forms");
		xmlNamespaceResolver.Add("x", "http://schemas.microsoft.com/winfx/2009/xaml");
		xmlNamespaceResolver.Add("calx", "clr-namespace:Caliburn.Micro.Xamarin.Forms;assembly=Caliburn.Micro.Platform.Xamarin.Forms");
		xmlNamespaceResolver.Add("converter", "clr-namespace:NHL.Views.Converters");
		xmlNamespaceResolver.Add("renderer", "clr-namespace:NHL.Views.Renderer");
		xmlNamespaceResolver.Add("effect", "clr-namespace:NHL.Views.Effect");
		xamlServiceProvider.Add(typeFromHandle2, new XamlTypeResolver(xmlNamespaceResolver, typeof(GlucoseTargetRegistView).GetTypeInfo().Assembly));
		xamlServiceProvider.Add(typeof(IXmlLineInfoProvider), new XmlLineInfoProvider(new XmlLineInfo(12, 14)));
		object obj = ((IMarkupExtension)staticResourceExtension).ProvideValue((IServiceProvider)xamlServiceProvider);
		glucoseTargetRegistView.BackgroundColor = (Color)obj;
		VisualDiagnostics.RegisterSourceInfo(obj, new Uri("Views/GlucoseTargetRegistView.xaml", UriKind.RelativeOrAbsolute), 12, 14);
		glucoseTargetRegistView.Resources = resourceDictionary;
		VisualDiagnostics.RegisterSourceInfo(resourceDictionary, new Uri("Views/GlucoseTargetRegistView.xaml", UriKind.RelativeOrAbsolute), 15, 10);
		grid17.SetValue(Grid.RowSpacingProperty, 0.0);
		grid17.SetValue(Xamarin.Forms.View.HorizontalOptionsProperty, LayoutOptions.Fill);
		grid17.SetValue(Xamarin.Forms.View.VerticalOptionsProperty, LayoutOptions.FillAndExpand);
		rowDefinition.SetValue(RowDefinition.HeightProperty, new GridLengthTypeConverter().ConvertFromInvariantString("Auto"));
		((DefinitionCollection<RowDefinition>)grid17.GetValue(Grid.RowDefinitionsProperty)).Add(rowDefinition);
		rowDefinition2.SetValue(RowDefinition.HeightProperty, new GridLengthTypeConverter().ConvertFromInvariantString("Auto"));
		((DefinitionCollection<RowDefinition>)grid17.GetValue(Grid.RowDefinitionsProperty)).Add(rowDefinition2);
		rowDefinition3.SetValue(RowDefinition.HeightProperty, new GridLengthTypeConverter().ConvertFromInvariantString("Auto"));
		((DefinitionCollection<RowDefinition>)grid17.GetValue(Grid.RowDefinitionsProperty)).Add(rowDefinition3);
		rowDefinition4.SetValue(RowDefinition.HeightProperty, new GridLengthTypeConverter().ConvertFromInvariantString("Auto"));
		((DefinitionCollection<RowDefinition>)grid17.GetValue(Grid.RowDefinitionsProperty)).Add(rowDefinition4);
		rowDefinition5.SetValue(RowDefinition.HeightProperty, new GridLengthTypeConverter().ConvertFromInvariantString("Auto"));
		((DefinitionCollection<RowDefinition>)grid17.GetValue(Grid.RowDefinitionsProperty)).Add(rowDefinition5);
		rowDefinition6.SetValue(RowDefinition.HeightProperty, new GridLengthTypeConverter().ConvertFromInvariantString("*"));
		((DefinitionCollection<RowDefinition>)grid17.GetValue(Grid.RowDefinitionsProperty)).Add(rowDefinition6);
		grid3.SetValue(Grid.RowProperty, 0);
		columnDefinition.SetValue(ColumnDefinition.WidthProperty, new GridLengthTypeConverter().ConvertFromInvariantString("Auto"));
		((DefinitionCollection<ColumnDefinition>)grid3.GetValue(Grid.ColumnDefinitionsProperty)).Add(columnDefinition);
		columnDefinition2.SetValue(ColumnDefinition.WidthProperty, new GridLengthTypeConverter().ConvertFromInvariantString("*"));
		((DefinitionCollection<ColumnDefinition>)grid3.GetValue(Grid.ColumnDefinitionsProperty)).Add(columnDefinition2);
		columnDefinition3.SetValue(ColumnDefinition.WidthProperty, new GridLengthTypeConverter().ConvertFromInvariantString("Auto"));
		((DefinitionCollection<ColumnDefinition>)grid3.GetValue(Grid.ColumnDefinitionsProperty)).Add(columnDefinition3);
		columnDefinition4.SetValue(ColumnDefinition.WidthProperty, new GridLengthTypeConverter().ConvertFromInvariantString("Auto"));
		((DefinitionCollection<ColumnDefinition>)grid3.GetValue(Grid.ColumnDefinitionsProperty)).Add(columnDefinition4);
		label.SetValue(Xamarin.Forms.View.MarginProperty, new Thickness(10.0, 5.0, 0.0, 5.0));
		label.SetValue(Label.TextProperty, "高い");
		BindableProperty fontSizeProperty = Label.FontSizeProperty;
		FontSizeConverter fontSizeConverter = new FontSizeConverter();
		XamlServiceProvider xamlServiceProvider2 = new XamlServiceProvider();
		Type typeFromHandle3 = typeof(IProvideValueTarget);
		object[] array2 = new object[0 + 4];
		array2[0] = label;
		array2[1] = grid3;
		array2[2] = grid17;
		array2[3] = glucoseTargetRegistView;
		object service2;
		xamlServiceProvider2.Add(typeFromHandle3, service2 = new SimpleValueTargetProvider(array2, Label.FontSizeProperty, nameScope));
		xamlServiceProvider2.Add(typeof(IReferenceProvider), service2);
		Type typeFromHandle4 = typeof(IXamlTypeResolver);
		XmlNamespaceResolver xmlNamespaceResolver2 = new XmlNamespaceResolver();
		xmlNamespaceResolver2.Add("", "http://xamarin.com/schemas/2014/forms");
		xmlNamespaceResolver2.Add("x", "http://schemas.microsoft.com/winfx/2009/xaml");
		xmlNamespaceResolver2.Add("calx", "clr-namespace:Caliburn.Micro.Xamarin.Forms;assembly=Caliburn.Micro.Platform.Xamarin.Forms");
		xmlNamespaceResolver2.Add("converter", "clr-namespace:NHL.Views.Converters");
		xmlNamespaceResolver2.Add("renderer", "clr-namespace:NHL.Views.Renderer");
		xmlNamespaceResolver2.Add("effect", "clr-namespace:NHL.Views.Effect");
		xamlServiceProvider2.Add(typeFromHandle4, new XamlTypeResolver(xmlNamespaceResolver2, typeof(GlucoseTargetRegistView).GetTypeInfo().Assembly));
		xamlServiceProvider2.Add(typeof(IXmlLineInfoProvider), new XmlLineInfoProvider(new XmlLineInfo(67, 48)));
		label.SetValue(fontSizeProperty, ((IExtendedTypeConverter)fontSizeConverter).ConvertFromInvariantString("Large", (IServiceProvider)xamlServiceProvider2));
		label.SetValue(Xamarin.Forms.View.HorizontalOptionsProperty, LayoutOptions.Start);
		label.SetValue(Label.VerticalTextAlignmentProperty, new TextAlignmentConverter().ConvertFromInvariantString("Center"));
		label.SetValue(Label.TextColorProperty, Color.Red);
		label.Effects.Add(fixedFontSizeLabelEffect);
		VisualDiagnostics.RegisterSourceInfo(fixedFontSizeLabelEffect, new Uri("Views/GlucoseTargetRegistView.xaml", UriKind.RelativeOrAbsolute), 69, 22);
		grid3.Children.Add(label);
		VisualDiagnostics.RegisterSourceInfo(label, new Uri("Views/GlucoseTargetRegistView.xaml", UriKind.RelativeOrAbsolute), 67, 14);
		grid2.SetValue(Grid.ColumnProperty, 1);
		rowDefinition7.SetValue(RowDefinition.HeightProperty, new GridLengthTypeConverter().ConvertFromInvariantString("*"));
		((DefinitionCollection<RowDefinition>)grid2.GetValue(Grid.RowDefinitionsProperty)).Add(rowDefinition7);
		rowDefinition8.SetValue(RowDefinition.HeightProperty, new GridLengthTypeConverter().ConvertFromInvariantString("1"));
		((DefinitionCollection<RowDefinition>)grid2.GetValue(Grid.RowDefinitionsProperty)).Add(rowDefinition8);
		rowDefinition9.SetValue(RowDefinition.HeightProperty, new GridLengthTypeConverter().ConvertFromInvariantString("*"));
		((DefinitionCollection<RowDefinition>)grid2.GetValue(Grid.RowDefinitionsProperty)).Add(rowDefinition9);
		grid.SetValue(Grid.RowProperty, 1);
		staticResourceExtension2.Key = "LineColor";
		XamlServiceProvider xamlServiceProvider3 = new XamlServiceProvider();
		Type typeFromHandle5 = typeof(IProvideValueTarget);
		object[] array3 = new object[0 + 5];
		array3[0] = grid;
		array3[1] = grid2;
		array3[2] = grid3;
		array3[3] = grid17;
		array3[4] = glucoseTargetRegistView;
		object service3;
		xamlServiceProvider3.Add(typeFromHandle5, service3 = new SimpleValueTargetProvider(array3, VisualElement.BackgroundColorProperty, nameScope));
		xamlServiceProvider3.Add(typeof(IReferenceProvider), service3);
		Type typeFromHandle6 = typeof(IXamlTypeResolver);
		XmlNamespaceResolver xmlNamespaceResolver3 = new XmlNamespaceResolver();
		xmlNamespaceResolver3.Add("", "http://xamarin.com/schemas/2014/forms");
		xmlNamespaceResolver3.Add("x", "http://schemas.microsoft.com/winfx/2009/xaml");
		xmlNamespaceResolver3.Add("calx", "clr-namespace:Caliburn.Micro.Xamarin.Forms;assembly=Caliburn.Micro.Platform.Xamarin.Forms");
		xmlNamespaceResolver3.Add("converter", "clr-namespace:NHL.Views.Converters");
		xmlNamespaceResolver3.Add("renderer", "clr-namespace:NHL.Views.Renderer");
		xmlNamespaceResolver3.Add("effect", "clr-namespace:NHL.Views.Effect");
		xamlServiceProvider3.Add(typeFromHandle6, new XamlTypeResolver(xmlNamespaceResolver3, typeof(GlucoseTargetRegistView).GetTypeInfo().Assembly));
		xamlServiceProvider3.Add(typeof(IXmlLineInfoProvider), new XmlLineInfoProvider(new XmlLineInfo(80, 36)));
		object obj2 = ((IMarkupExtension)staticResourceExtension2).ProvideValue((IServiceProvider)xamlServiceProvider3);
		grid.BackgroundColor = (Color)obj2;
		VisualDiagnostics.RegisterSourceInfo(obj2, new Uri("Views/GlucoseTargetRegistView.xaml", UriKind.RelativeOrAbsolute), 80, 36);
		grid.SetValue(Grid.RowSpacingProperty, 0.0);
		grid.SetValue(Grid.ColumnSpacingProperty, 0.0);
		grid2.Children.Add(grid);
		VisualDiagnostics.RegisterSourceInfo(grid, new Uri("Views/GlucoseTargetRegistView.xaml", UriKind.RelativeOrAbsolute), 80, 18);
		grid3.Children.Add(grid2);
		VisualDiagnostics.RegisterSourceInfo(grid2, new Uri("Views/GlucoseTargetRegistView.xaml", UriKind.RelativeOrAbsolute), 74, 14);
		label2.SetValue(Grid.ColumnProperty, 2);
		label2.SetValue(Label.TextProperty, "必須");
		label2.SetValue(Xamarin.Forms.View.MarginProperty, new Thickness(5.0, 5.0, 5.0, 5.0));
		BindableProperty fontSizeProperty2 = Label.FontSizeProperty;
		FontSizeConverter fontSizeConverter2 = new FontSizeConverter();
		XamlServiceProvider xamlServiceProvider4 = new XamlServiceProvider();
		Type typeFromHandle7 = typeof(IProvideValueTarget);
		object[] array4 = new object[0 + 4];
		array4[0] = label2;
		array4[1] = grid3;
		array4[2] = grid17;
		array4[3] = glucoseTargetRegistView;
		object service4;
		xamlServiceProvider4.Add(typeFromHandle7, service4 = new SimpleValueTargetProvider(array4, Label.FontSizeProperty, nameScope));
		xamlServiceProvider4.Add(typeof(IReferenceProvider), service4);
		Type typeFromHandle8 = typeof(IXamlTypeResolver);
		XmlNamespaceResolver xmlNamespaceResolver4 = new XmlNamespaceResolver();
		xmlNamespaceResolver4.Add("", "http://xamarin.com/schemas/2014/forms");
		xmlNamespaceResolver4.Add("x", "http://schemas.microsoft.com/winfx/2009/xaml");
		xmlNamespaceResolver4.Add("calx", "clr-namespace:Caliburn.Micro.Xamarin.Forms;assembly=Caliburn.Micro.Platform.Xamarin.Forms");
		xmlNamespaceResolver4.Add("converter", "clr-namespace:NHL.Views.Converters");
		xmlNamespaceResolver4.Add("renderer", "clr-namespace:NHL.Views.Renderer");
		xmlNamespaceResolver4.Add("effect", "clr-namespace:NHL.Views.Effect");
		xamlServiceProvider4.Add(typeFromHandle8, new XamlTypeResolver(xmlNamespaceResolver4, typeof(GlucoseTargetRegistView).GetTypeInfo().Assembly));
		xamlServiceProvider4.Add(typeof(IXmlLineInfoProvider), new XmlLineInfoProvider(new XmlLineInfo(84, 63)));
		label2.SetValue(fontSizeProperty2, ((IExtendedTypeConverter)fontSizeConverter2).ConvertFromInvariantString("Large", (IServiceProvider)xamlServiceProvider4));
		staticResourceExtension3.Key = "LabelColor";
		XamlServiceProvider xamlServiceProvider5 = new XamlServiceProvider();
		Type typeFromHandle9 = typeof(IProvideValueTarget);
		object[] array5 = new object[0 + 4];
		array5[0] = label2;
		array5[1] = grid3;
		array5[2] = grid17;
		array5[3] = glucoseTargetRegistView;
		object service5;
		xamlServiceProvider5.Add(typeFromHandle9, service5 = new SimpleValueTargetProvider(array5, Label.TextColorProperty, nameScope));
		xamlServiceProvider5.Add(typeof(IReferenceProvider), service5);
		Type typeFromHandle10 = typeof(IXamlTypeResolver);
		XmlNamespaceResolver xmlNamespaceResolver5 = new XmlNamespaceResolver();
		xmlNamespaceResolver5.Add("", "http://xamarin.com/schemas/2014/forms");
		xmlNamespaceResolver5.Add("x", "http://schemas.microsoft.com/winfx/2009/xaml");
		xmlNamespaceResolver5.Add("calx", "clr-namespace:Caliburn.Micro.Xamarin.Forms;assembly=Caliburn.Micro.Platform.Xamarin.Forms");
		xmlNamespaceResolver5.Add("converter", "clr-namespace:NHL.Views.Converters");
		xmlNamespaceResolver5.Add("renderer", "clr-namespace:NHL.Views.Renderer");
		xmlNamespaceResolver5.Add("effect", "clr-namespace:NHL.Views.Effect");
		xamlServiceProvider5.Add(typeFromHandle10, new XamlTypeResolver(xmlNamespaceResolver5, typeof(GlucoseTargetRegistView).GetTypeInfo().Assembly));
		xamlServiceProvider5.Add(typeof(IXmlLineInfoProvider), new XmlLineInfoProvider(new XmlLineInfo(84, 80)));
		object obj3 = ((IMarkupExtension)staticResourceExtension3).ProvideValue((IServiceProvider)xamlServiceProvider5);
		label2.TextColor = (Color)obj3;
		VisualDiagnostics.RegisterSourceInfo(obj3, new Uri("Views/GlucoseTargetRegistView.xaml", UriKind.RelativeOrAbsolute), 84, 80);
		label2.SetValue(Label.VerticalTextAlignmentProperty, new TextAlignmentConverter().ConvertFromInvariantString("Center"));
		staticResourceExtension4.Key = "GlucoseTargetThresholdToBisibleConverter";
		XamlServiceProvider xamlServiceProvider6 = new XamlServiceProvider();
		Type typeFromHandle11 = typeof(IProvideValueTarget);
		object[] array6 = new object[0 + 5];
		array6[0] = bindingExtension;
		array6[1] = label2;
		array6[2] = grid3;
		array6[3] = grid17;
		array6[4] = glucoseTargetRegistView;
		object service6;
		xamlServiceProvider6.Add(typeFromHandle11, service6 = new SimpleValueTargetProvider(array6, typeof(BindingExtension).GetRuntimeProperty("Converter"), nameScope));
		xamlServiceProvider6.Add(typeof(IReferenceProvider), service6);
		Type typeFromHandle12 = typeof(IXamlTypeResolver);
		XmlNamespaceResolver xmlNamespaceResolver6 = new XmlNamespaceResolver();
		xmlNamespaceResolver6.Add("", "http://xamarin.com/schemas/2014/forms");
		xmlNamespaceResolver6.Add("x", "http://schemas.microsoft.com/winfx/2009/xaml");
		xmlNamespaceResolver6.Add("calx", "clr-namespace:Caliburn.Micro.Xamarin.Forms;assembly=Caliburn.Micro.Platform.Xamarin.Forms");
		xmlNamespaceResolver6.Add("converter", "clr-namespace:NHL.Views.Converters");
		xmlNamespaceResolver6.Add("renderer", "clr-namespace:NHL.Views.Renderer");
		xmlNamespaceResolver6.Add("effect", "clr-namespace:NHL.Views.Effect");
		xamlServiceProvider6.Add(typeFromHandle12, new XamlTypeResolver(xmlNamespaceResolver6, typeof(GlucoseTargetRegistView).GetTypeInfo().Assembly));
		xamlServiceProvider6.Add(typeof(IXmlLineInfoProvider), new XmlLineInfoProvider(new XmlLineInfo(84, 151)));
		object target = (bindingExtension.Converter = (IValueConverter)((IMarkupExtension)staticResourceExtension4).ProvideValue((IServiceProvider)xamlServiceProvider6));
		VisualDiagnostics.RegisterSourceInfo(target, new Uri("Views/GlucoseTargetRegistView.xaml", UriKind.RelativeOrAbsolute), 84, 151);
		bindingExtension.Path = "GlucoseHighValue";
		BindingBase binding = ((IMarkupExtension<BindingBase>)bindingExtension).ProvideValue((IServiceProvider)null);
		label2.SetBinding(VisualElement.IsVisibleProperty, binding);
		label2.Effects.Add(fixedFontSizeLabelEffect2);
		VisualDiagnostics.RegisterSourceInfo(fixedFontSizeLabelEffect2, new Uri("Views/GlucoseTargetRegistView.xaml", UriKind.RelativeOrAbsolute), 86, 22);
		grid3.Children.Add(label2);
		VisualDiagnostics.RegisterSourceInfo(label2, new Uri("Views/GlucoseTargetRegistView.xaml", UriKind.RelativeOrAbsolute), 84, 14);
		pickerView.SetValue(Grid.ColumnProperty, 2);
		pickerView.SetValue(Xamarin.Forms.View.MarginProperty, new Thickness(0.0, 5.0, 0.0, 5.0));
		bindingExtension2.Mode = BindingMode.TwoWay;
		bindingExtension2.Path = "GlucoseHighValue";
		BindingBase binding2 = ((IMarkupExtension<BindingBase>)bindingExtension2).ProvideValue((IServiceProvider)null);
		pickerView.SetBinding(Picker.SelectedItemProperty, binding2);
		bindingExtension3.Path = "ThresholdList";
		BindingBase binding3 = ((IMarkupExtension<BindingBase>)bindingExtension3).ProvideValue((IServiceProvider)null);
		pickerView.SetBinding(Picker.ItemsSourceProperty, binding3);
		bindingExtension4.Path = "Name";
		BindingBase target2 = (pickerView.ItemDisplayBinding = ((IMarkupExtension<BindingBase>)bindingExtension4).ProvideValue((IServiceProvider)null));
		VisualDiagnostics.RegisterSourceInfo(target2, new Uri("Views/GlucoseTargetRegistView.xaml", UriKind.RelativeOrAbsolute), 89, 160);
		pickerView.SetValue(VisualElement.BackgroundColorProperty, Color.Transparent);
		pickerView.Effects.Add(fixedFontSizeTextBoxEffect);
		VisualDiagnostics.RegisterSourceInfo(fixedFontSizeTextBoxEffect, new Uri("Views/GlucoseTargetRegistView.xaml", UriKind.RelativeOrAbsolute), 91, 22);
		grid3.Children.Add(pickerView);
		VisualDiagnostics.RegisterSourceInfo(pickerView, new Uri("Views/GlucoseTargetRegistView.xaml", UriKind.RelativeOrAbsolute), 89, 14);
		label3.SetValue(Grid.ColumnProperty, 3);
		label3.SetValue(Label.TextProperty, "以上");
		label3.SetValue(Xamarin.Forms.View.MarginProperty, new Thickness(0.0, 5.0, 10.0, 5.0));
		BindableProperty fontSizeProperty3 = Label.FontSizeProperty;
		FontSizeConverter fontSizeConverter3 = new FontSizeConverter();
		XamlServiceProvider xamlServiceProvider7 = new XamlServiceProvider();
		Type typeFromHandle13 = typeof(IProvideValueTarget);
		object[] array7 = new object[0 + 4];
		array7[0] = label3;
		array7[1] = grid3;
		array7[2] = grid17;
		array7[3] = glucoseTargetRegistView;
		object service7;
		xamlServiceProvider7.Add(typeFromHandle13, service7 = new SimpleValueTargetProvider(array7, Label.FontSizeProperty, nameScope));
		xamlServiceProvider7.Add(typeof(IReferenceProvider), service7);
		Type typeFromHandle14 = typeof(IXamlTypeResolver);
		XmlNamespaceResolver xmlNamespaceResolver7 = new XmlNamespaceResolver();
		xmlNamespaceResolver7.Add("", "http://xamarin.com/schemas/2014/forms");
		xmlNamespaceResolver7.Add("x", "http://schemas.microsoft.com/winfx/2009/xaml");
		xmlNamespaceResolver7.Add("calx", "clr-namespace:Caliburn.Micro.Xamarin.Forms;assembly=Caliburn.Micro.Platform.Xamarin.Forms");
		xmlNamespaceResolver7.Add("converter", "clr-namespace:NHL.Views.Converters");
		xmlNamespaceResolver7.Add("renderer", "clr-namespace:NHL.Views.Renderer");
		xmlNamespaceResolver7.Add("effect", "clr-namespace:NHL.Views.Effect");
		xamlServiceProvider7.Add(typeFromHandle14, new XamlTypeResolver(xmlNamespaceResolver7, typeof(GlucoseTargetRegistView).GetTypeInfo().Assembly));
		xamlServiceProvider7.Add(typeof(IXmlLineInfoProvider), new XmlLineInfoProvider(new XmlLineInfo(94, 65)));
		label3.SetValue(fontSizeProperty3, ((IExtendedTypeConverter)fontSizeConverter3).ConvertFromInvariantString("Large", (IServiceProvider)xamlServiceProvider7));
		label3.SetValue(Label.VerticalTextAlignmentProperty, new TextAlignmentConverter().ConvertFromInvariantString("Center"));
		label3.Effects.Add(fixedFontSizeLabelEffect3);
		VisualDiagnostics.RegisterSourceInfo(fixedFontSizeLabelEffect3, new Uri("Views/GlucoseTargetRegistView.xaml", UriKind.RelativeOrAbsolute), 96, 22);
		grid3.Children.Add(label3);
		VisualDiagnostics.RegisterSourceInfo(label3, new Uri("Views/GlucoseTargetRegistView.xaml", UriKind.RelativeOrAbsolute), 94, 14);
		grid17.Children.Add(grid3);
		VisualDiagnostics.RegisterSourceInfo(grid3, new Uri("Views/GlucoseTargetRegistView.xaml", UriKind.RelativeOrAbsolute), 59, 10);
		grid13.SetValue(Grid.RowProperty, 1);
		columnDefinition5.SetValue(ColumnDefinition.WidthProperty, new GridLengthTypeConverter().ConvertFromInvariantString("Auto"));
		((DefinitionCollection<ColumnDefinition>)grid13.GetValue(Grid.ColumnDefinitionsProperty)).Add(columnDefinition5);
		columnDefinition6.SetValue(ColumnDefinition.WidthProperty, new GridLengthTypeConverter().ConvertFromInvariantString("*"));
		((DefinitionCollection<ColumnDefinition>)grid13.GetValue(Grid.ColumnDefinitionsProperty)).Add(columnDefinition6);
		columnDefinition7.SetValue(ColumnDefinition.WidthProperty, new GridLengthTypeConverter().ConvertFromInvariantString("Auto"));
		((DefinitionCollection<ColumnDefinition>)grid13.GetValue(Grid.ColumnDefinitionsProperty)).Add(columnDefinition7);
		columnDefinition8.SetValue(ColumnDefinition.WidthProperty, new GridLengthTypeConverter().ConvertFromInvariantString("Auto"));
		((DefinitionCollection<ColumnDefinition>)grid13.GetValue(Grid.ColumnDefinitionsProperty)).Add(columnDefinition8);
		rowDefinition10.SetValue(RowDefinition.HeightProperty, new GridLengthTypeConverter().ConvertFromInvariantString("Auto"));
		((DefinitionCollection<RowDefinition>)grid13.GetValue(Grid.RowDefinitionsProperty)).Add(rowDefinition10);
		rowDefinition11.SetValue(RowDefinition.HeightProperty, new GridLengthTypeConverter().ConvertFromInvariantString("*"));
		((DefinitionCollection<RowDefinition>)grid13.GetValue(Grid.RowDefinitionsProperty)).Add(rowDefinition11);
		rowDefinition12.SetValue(RowDefinition.HeightProperty, new GridLengthTypeConverter().ConvertFromInvariantString("Auto"));
		((DefinitionCollection<RowDefinition>)grid13.GetValue(Grid.RowDefinitionsProperty)).Add(rowDefinition12);
		label4.SetValue(Xamarin.Forms.View.MarginProperty, new Thickness(30.0, 5.0, 0.0, 5.0));
		label4.SetValue(Label.TextProperty, "やや高い");
		BindableProperty fontSizeProperty4 = Label.FontSizeProperty;
		FontSizeConverter fontSizeConverter4 = new FontSizeConverter();
		XamlServiceProvider xamlServiceProvider8 = new XamlServiceProvider();
		Type typeFromHandle15 = typeof(IProvideValueTarget);
		object[] array8 = new object[0 + 4];
		array8[0] = label4;
		array8[1] = grid13;
		array8[2] = grid17;
		array8[3] = glucoseTargetRegistView;
		object service8;
		xamlServiceProvider8.Add(typeFromHandle15, service8 = new SimpleValueTargetProvider(array8, Label.FontSizeProperty, nameScope));
		xamlServiceProvider8.Add(typeof(IReferenceProvider), service8);
		Type typeFromHandle16 = typeof(IXamlTypeResolver);
		XmlNamespaceResolver xmlNamespaceResolver8 = new XmlNamespaceResolver();
		xmlNamespaceResolver8.Add("", "http://xamarin.com/schemas/2014/forms");
		xmlNamespaceResolver8.Add("x", "http://schemas.microsoft.com/winfx/2009/xaml");
		xmlNamespaceResolver8.Add("calx", "clr-namespace:Caliburn.Micro.Xamarin.Forms;assembly=Caliburn.Micro.Platform.Xamarin.Forms");
		xmlNamespaceResolver8.Add("converter", "clr-namespace:NHL.Views.Converters");
		xmlNamespaceResolver8.Add("renderer", "clr-namespace:NHL.Views.Renderer");
		xmlNamespaceResolver8.Add("effect", "clr-namespace:NHL.Views.Effect");
		xamlServiceProvider8.Add(typeFromHandle16, new XamlTypeResolver(xmlNamespaceResolver8, typeof(GlucoseTargetRegistView).GetTypeInfo().Assembly));
		xamlServiceProvider8.Add(typeof(IXmlLineInfoProvider), new XmlLineInfoProvider(new XmlLineInfo(116, 50)));
		label4.SetValue(fontSizeProperty4, ((IExtendedTypeConverter)fontSizeConverter4).ConvertFromInvariantString("Medium", (IServiceProvider)xamlServiceProvider8));
		label4.SetValue(Xamarin.Forms.View.HorizontalOptionsProperty, LayoutOptions.Center);
		label4.SetValue(Xamarin.Forms.View.VerticalOptionsProperty, LayoutOptions.Center);
		label4.SetValue(Label.TextColorProperty, Color.Orange);
		fixedFontSizeLabelEffect4.FixedSize = 11;
		label4.Effects.Add(fixedFontSizeLabelEffect4);
		VisualDiagnostics.RegisterSourceInfo(fixedFontSizeLabelEffect4, new Uri("Views/GlucoseTargetRegistView.xaml", UriKind.RelativeOrAbsolute), 118, 22);
		grid13.Children.Add(label4);
		VisualDiagnostics.RegisterSourceInfo(label4, new Uri("Views/GlucoseTargetRegistView.xaml", UriKind.RelativeOrAbsolute), 116, 14);
		label5.SetValue(Grid.RowProperty, 2);
		label5.SetValue(Xamarin.Forms.View.MarginProperty, new Thickness(30.0, 5.0, 0.0, 5.0));
		label5.SetValue(Label.TextProperty, "やや低い");
		BindableProperty fontSizeProperty5 = Label.FontSizeProperty;
		FontSizeConverter fontSizeConverter5 = new FontSizeConverter();
		XamlServiceProvider xamlServiceProvider9 = new XamlServiceProvider();
		Type typeFromHandle17 = typeof(IProvideValueTarget);
		object[] array9 = new object[0 + 4];
		array9[0] = label5;
		array9[1] = grid13;
		array9[2] = grid17;
		array9[3] = glucoseTargetRegistView;
		object service9;
		xamlServiceProvider9.Add(typeFromHandle17, service9 = new SimpleValueTargetProvider(array9, Label.FontSizeProperty, nameScope));
		xamlServiceProvider9.Add(typeof(IReferenceProvider), service9);
		Type typeFromHandle18 = typeof(IXamlTypeResolver);
		XmlNamespaceResolver xmlNamespaceResolver9 = new XmlNamespaceResolver();
		xmlNamespaceResolver9.Add("", "http://xamarin.com/schemas/2014/forms");
		xmlNamespaceResolver9.Add("x", "http://schemas.microsoft.com/winfx/2009/xaml");
		xmlNamespaceResolver9.Add("calx", "clr-namespace:Caliburn.Micro.Xamarin.Forms;assembly=Caliburn.Micro.Platform.Xamarin.Forms");
		xmlNamespaceResolver9.Add("converter", "clr-namespace:NHL.Views.Converters");
		xmlNamespaceResolver9.Add("renderer", "clr-namespace:NHL.Views.Renderer");
		xmlNamespaceResolver9.Add("effect", "clr-namespace:NHL.Views.Effect");
		xamlServiceProvider9.Add(typeFromHandle18, new XamlTypeResolver(xmlNamespaceResolver9, typeof(GlucoseTargetRegistView).GetTypeInfo().Assembly));
		xamlServiceProvider9.Add(typeof(IXmlLineInfoProvider), new XmlLineInfoProvider(new XmlLineInfo(122, 63)));
		label5.SetValue(fontSizeProperty5, ((IExtendedTypeConverter)fontSizeConverter5).ConvertFromInvariantString("Medium", (IServiceProvider)xamlServiceProvider9));
		label5.SetValue(Xamarin.Forms.View.HorizontalOptionsProperty, LayoutOptions.Start);
		label5.SetValue(Xamarin.Forms.View.VerticalOptionsProperty, LayoutOptions.Center);
		label5.SetValue(Label.TextColorProperty, Color.SkyBlue);
		fixedFontSizeLabelEffect5.FixedSize = 11;
		label5.Effects.Add(fixedFontSizeLabelEffect5);
		VisualDiagnostics.RegisterSourceInfo(fixedFontSizeLabelEffect5, new Uri("Views/GlucoseTargetRegistView.xaml", UriKind.RelativeOrAbsolute), 124, 22);
		grid13.Children.Add(label5);
		VisualDiagnostics.RegisterSourceInfo(label5, new Uri("Views/GlucoseTargetRegistView.xaml", UriKind.RelativeOrAbsolute), 122, 14);
		grid4.SetValue(Grid.RowProperty, 1);
		columnDefinition9.SetValue(ColumnDefinition.WidthProperty, new GridLengthTypeConverter().ConvertFromInvariantString("Auto"));
		((DefinitionCollection<ColumnDefinition>)grid4.GetValue(Grid.ColumnDefinitionsProperty)).Add(columnDefinition9);
		columnDefinition10.SetValue(ColumnDefinition.WidthProperty, new GridLengthTypeConverter().ConvertFromInvariantString("*"));
		((DefinitionCollection<ColumnDefinition>)grid4.GetValue(Grid.ColumnDefinitionsProperty)).Add(columnDefinition10);
		columnDefinition11.SetValue(ColumnDefinition.WidthProperty, new GridLengthTypeConverter().ConvertFromInvariantString("Auto"));
		((DefinitionCollection<ColumnDefinition>)grid4.GetValue(Grid.ColumnDefinitionsProperty)).Add(columnDefinition11);
		label6.SetValue(Xamarin.Forms.View.MarginProperty, new Thickness(10.0, 5.0, 0.0, 5.0));
		label6.SetValue(Label.TextProperty, "目標値");
		BindableProperty fontSizeProperty6 = Label.FontSizeProperty;
		FontSizeConverter fontSizeConverter6 = new FontSizeConverter();
		XamlServiceProvider xamlServiceProvider10 = new XamlServiceProvider();
		Type typeFromHandle19 = typeof(IProvideValueTarget);
		object[] array10 = new object[0 + 5];
		array10[0] = label6;
		array10[1] = grid4;
		array10[2] = grid13;
		array10[3] = grid17;
		array10[4] = glucoseTargetRegistView;
		object service10;
		xamlServiceProvider10.Add(typeFromHandle19, service10 = new SimpleValueTargetProvider(array10, Label.FontSizeProperty, nameScope));
		xamlServiceProvider10.Add(typeof(IReferenceProvider), service10);
		Type typeFromHandle20 = typeof(IXamlTypeResolver);
		XmlNamespaceResolver xmlNamespaceResolver10 = new XmlNamespaceResolver();
		xmlNamespaceResolver10.Add("", "http://xamarin.com/schemas/2014/forms");
		xmlNamespaceResolver10.Add("x", "http://schemas.microsoft.com/winfx/2009/xaml");
		xmlNamespaceResolver10.Add("calx", "clr-namespace:Caliburn.Micro.Xamarin.Forms;assembly=Caliburn.Micro.Platform.Xamarin.Forms");
		xmlNamespaceResolver10.Add("converter", "clr-namespace:NHL.Views.Converters");
		xmlNamespaceResolver10.Add("renderer", "clr-namespace:NHL.Views.Renderer");
		xmlNamespaceResolver10.Add("effect", "clr-namespace:NHL.Views.Effect");
		xamlServiceProvider10.Add(typeFromHandle20, new XamlTypeResolver(xmlNamespaceResolver10, typeof(GlucoseTargetRegistView).GetTypeInfo().Assembly));
		xamlServiceProvider10.Add(typeof(IXmlLineInfoProvider), new XmlLineInfoProvider(new XmlLineInfo(135, 53)));
		label6.SetValue(fontSizeProperty6, ((IExtendedTypeConverter)fontSizeConverter6).ConvertFromInvariantString("Large", (IServiceProvider)xamlServiceProvider10));
		label6.SetValue(Xamarin.Forms.View.HorizontalOptionsProperty, LayoutOptions.Start);
		label6.Effects.Add(fixedFontSizeLabelEffect6);
		VisualDiagnostics.RegisterSourceInfo(fixedFontSizeLabelEffect6, new Uri("Views/GlucoseTargetRegistView.xaml", UriKind.RelativeOrAbsolute), 137, 26);
		grid4.Children.Add(label6);
		VisualDiagnostics.RegisterSourceInfo(label6, new Uri("Views/GlucoseTargetRegistView.xaml", UriKind.RelativeOrAbsolute), 135, 18);
		grid13.Children.Add(grid4);
		VisualDiagnostics.RegisterSourceInfo(grid4, new Uri("Views/GlucoseTargetRegistView.xaml", UriKind.RelativeOrAbsolute), 129, 14);
		grid12.SetValue(Grid.RowSpanProperty, 3);
		grid12.SetValue(Grid.ColumnProperty, 1);
		columnDefinition12.SetValue(ColumnDefinition.WidthProperty, new GridLengthTypeConverter().ConvertFromInvariantString("*"));
		((DefinitionCollection<ColumnDefinition>)grid12.GetValue(Grid.ColumnDefinitionsProperty)).Add(columnDefinition12);
		columnDefinition13.SetValue(ColumnDefinition.WidthProperty, new GridLengthTypeConverter().ConvertFromInvariantString("1"));
		((DefinitionCollection<ColumnDefinition>)grid12.GetValue(Grid.ColumnDefinitionsProperty)).Add(columnDefinition13);
		columnDefinition14.SetValue(ColumnDefinition.WidthProperty, new GridLengthTypeConverter().ConvertFromInvariantString("*"));
		((DefinitionCollection<ColumnDefinition>)grid12.GetValue(Grid.ColumnDefinitionsProperty)).Add(columnDefinition14);
		rowDefinition13.SetValue(RowDefinition.HeightProperty, new GridLengthTypeConverter().ConvertFromInvariantString("1*"));
		((DefinitionCollection<RowDefinition>)grid12.GetValue(Grid.RowDefinitionsProperty)).Add(rowDefinition13);
		rowDefinition14.SetValue(RowDefinition.HeightProperty, new GridLengthTypeConverter().ConvertFromInvariantString("1*"));
		((DefinitionCollection<RowDefinition>)grid12.GetValue(Grid.RowDefinitionsProperty)).Add(rowDefinition14);
		grid6.SetValue(Grid.RowSpanProperty, 2);
		grid6.SetValue(Grid.ColumnSpanProperty, 2);
		rowDefinition15.SetValue(RowDefinition.HeightProperty, new GridLengthTypeConverter().ConvertFromInvariantString("*"));
		((DefinitionCollection<RowDefinition>)grid6.GetValue(Grid.RowDefinitionsProperty)).Add(rowDefinition15);
		rowDefinition16.SetValue(RowDefinition.HeightProperty, new GridLengthTypeConverter().ConvertFromInvariantString("1"));
		((DefinitionCollection<RowDefinition>)grid6.GetValue(Grid.RowDefinitionsProperty)).Add(rowDefinition16);
		rowDefinition17.SetValue(RowDefinition.HeightProperty, new GridLengthTypeConverter().ConvertFromInvariantString("*"));
		((DefinitionCollection<RowDefinition>)grid6.GetValue(Grid.RowDefinitionsProperty)).Add(rowDefinition17);
		grid5.SetValue(Grid.RowProperty, 1);
		staticResourceExtension5.Key = "LineColor";
		XamlServiceProvider xamlServiceProvider11 = new XamlServiceProvider();
		Type typeFromHandle21 = typeof(IProvideValueTarget);
		object[] array11 = new object[0 + 6];
		array11[0] = grid5;
		array11[1] = grid6;
		array11[2] = grid12;
		array11[3] = grid13;
		array11[4] = grid17;
		array11[5] = glucoseTargetRegistView;
		object service11;
		xamlServiceProvider11.Add(typeFromHandle21, service11 = new SimpleValueTargetProvider(array11, VisualElement.BackgroundColorProperty, nameScope));
		xamlServiceProvider11.Add(typeof(IReferenceProvider), service11);
		Type typeFromHandle22 = typeof(IXamlTypeResolver);
		XmlNamespaceResolver xmlNamespaceResolver11 = new XmlNamespaceResolver();
		xmlNamespaceResolver11.Add("", "http://xamarin.com/schemas/2014/forms");
		xmlNamespaceResolver11.Add("x", "http://schemas.microsoft.com/winfx/2009/xaml");
		xmlNamespaceResolver11.Add("calx", "clr-namespace:Caliburn.Micro.Xamarin.Forms;assembly=Caliburn.Micro.Platform.Xamarin.Forms");
		xmlNamespaceResolver11.Add("converter", "clr-namespace:NHL.Views.Converters");
		xmlNamespaceResolver11.Add("renderer", "clr-namespace:NHL.Views.Renderer");
		xmlNamespaceResolver11.Add("effect", "clr-namespace:NHL.Views.Effect");
		xamlServiceProvider11.Add(typeFromHandle22, new XamlTypeResolver(xmlNamespaceResolver11, typeof(GlucoseTargetRegistView).GetTypeInfo().Assembly));
		xamlServiceProvider11.Add(typeof(IXmlLineInfoProvider), new XmlLineInfoProvider(new XmlLineInfo(159, 40)));
		object obj4 = ((IMarkupExtension)staticResourceExtension5).ProvideValue((IServiceProvider)xamlServiceProvider11);
		grid5.BackgroundColor = (Color)obj4;
		VisualDiagnostics.RegisterSourceInfo(obj4, new Uri("Views/GlucoseTargetRegistView.xaml", UriKind.RelativeOrAbsolute), 159, 40);
		grid5.SetValue(Grid.RowSpacingProperty, 0.0);
		grid5.SetValue(Grid.ColumnSpacingProperty, 0.0);
		grid6.Children.Add(grid5);
		VisualDiagnostics.RegisterSourceInfo(grid5, new Uri("Views/GlucoseTargetRegistView.xaml", UriKind.RelativeOrAbsolute), 159, 22);
		grid12.Children.Add(grid6);
		VisualDiagnostics.RegisterSourceInfo(grid6, new Uri("Views/GlucoseTargetRegistView.xaml", UriKind.RelativeOrAbsolute), 153, 18);
		grid8.SetValue(Grid.ColumnProperty, 1);
		grid8.SetValue(Grid.RowSpanProperty, 2);
		rowDefinition18.SetValue(RowDefinition.HeightProperty, new GridLengthTypeConverter().ConvertFromInvariantString("1*"));
		((DefinitionCollection<RowDefinition>)grid8.GetValue(Grid.RowDefinitionsProperty)).Add(rowDefinition18);
		rowDefinition19.SetValue(RowDefinition.HeightProperty, new GridLengthTypeConverter().ConvertFromInvariantString("1"));
		((DefinitionCollection<RowDefinition>)grid8.GetValue(Grid.RowDefinitionsProperty)).Add(rowDefinition19);
		rowDefinition20.SetValue(RowDefinition.HeightProperty, new GridLengthTypeConverter().ConvertFromInvariantString("2*"));
		((DefinitionCollection<RowDefinition>)grid8.GetValue(Grid.RowDefinitionsProperty)).Add(rowDefinition20);
		rowDefinition21.SetValue(RowDefinition.HeightProperty, new GridLengthTypeConverter().ConvertFromInvariantString("1"));
		((DefinitionCollection<RowDefinition>)grid8.GetValue(Grid.RowDefinitionsProperty)).Add(rowDefinition21);
		rowDefinition22.SetValue(RowDefinition.HeightProperty, new GridLengthTypeConverter().ConvertFromInvariantString("1*"));
		((DefinitionCollection<RowDefinition>)grid8.GetValue(Grid.RowDefinitionsProperty)).Add(rowDefinition22);
		grid7.SetValue(Grid.RowProperty, 1);
		grid7.SetValue(Grid.RowSpanProperty, 3);
		staticResourceExtension6.Key = "LineColor";
		XamlServiceProvider xamlServiceProvider12 = new XamlServiceProvider();
		Type typeFromHandle23 = typeof(IProvideValueTarget);
		object[] array12 = new object[0 + 6];
		array12[0] = grid7;
		array12[1] = grid8;
		array12[2] = grid12;
		array12[3] = grid13;
		array12[4] = grid17;
		array12[5] = glucoseTargetRegistView;
		object service12;
		xamlServiceProvider12.Add(typeFromHandle23, service12 = new SimpleValueTargetProvider(array12, VisualElement.BackgroundColorProperty, nameScope));
		xamlServiceProvider12.Add(typeof(IReferenceProvider), service12);
		Type typeFromHandle24 = typeof(IXamlTypeResolver);
		XmlNamespaceResolver xmlNamespaceResolver12 = new XmlNamespaceResolver();
		xmlNamespaceResolver12.Add("", "http://xamarin.com/schemas/2014/forms");
		xmlNamespaceResolver12.Add("x", "http://schemas.microsoft.com/winfx/2009/xaml");
		xmlNamespaceResolver12.Add("calx", "clr-namespace:Caliburn.Micro.Xamarin.Forms;assembly=Caliburn.Micro.Platform.Xamarin.Forms");
		xmlNamespaceResolver12.Add("converter", "clr-namespace:NHL.Views.Converters");
		xmlNamespaceResolver12.Add("renderer", "clr-namespace:NHL.Views.Renderer");
		xmlNamespaceResolver12.Add("effect", "clr-namespace:NHL.Views.Effect");
		xamlServiceProvider12.Add(typeFromHandle24, new XamlTypeResolver(xmlNamespaceResolver12, typeof(GlucoseTargetRegistView).GetTypeInfo().Assembly));
		xamlServiceProvider12.Add(typeof(IXmlLineInfoProvider), new XmlLineInfoProvider(new XmlLineInfo(169, 57)));
		object obj5 = ((IMarkupExtension)staticResourceExtension6).ProvideValue((IServiceProvider)xamlServiceProvider12);
		grid7.BackgroundColor = (Color)obj5;
		VisualDiagnostics.RegisterSourceInfo(obj5, new Uri("Views/GlucoseTargetRegistView.xaml", UriKind.RelativeOrAbsolute), 169, 57);
		grid7.SetValue(Grid.RowSpacingProperty, 0.0);
		grid7.SetValue(Grid.ColumnSpacingProperty, 0.0);
		grid8.Children.Add(grid7);
		VisualDiagnostics.RegisterSourceInfo(grid7, new Uri("Views/GlucoseTargetRegistView.xaml", UriKind.RelativeOrAbsolute), 169, 22);
		grid12.Children.Add(grid8);
		VisualDiagnostics.RegisterSourceInfo(grid8, new Uri("Views/GlucoseTargetRegistView.xaml", UriKind.RelativeOrAbsolute), 161, 18);
		grid11.SetValue(Grid.ColumnProperty, 1);
		grid11.SetValue(Grid.ColumnSpanProperty, 2);
		grid11.SetValue(Grid.RowSpanProperty, 2);
		rowDefinition23.SetValue(RowDefinition.HeightProperty, new GridLengthTypeConverter().ConvertFromInvariantString("1*"));
		((DefinitionCollection<RowDefinition>)grid11.GetValue(Grid.RowDefinitionsProperty)).Add(rowDefinition23);
		rowDefinition24.SetValue(RowDefinition.HeightProperty, new GridLengthTypeConverter().ConvertFromInvariantString("1"));
		((DefinitionCollection<RowDefinition>)grid11.GetValue(Grid.RowDefinitionsProperty)).Add(rowDefinition24);
		rowDefinition25.SetValue(RowDefinition.HeightProperty, new GridLengthTypeConverter().ConvertFromInvariantString("2*"));
		((DefinitionCollection<RowDefinition>)grid11.GetValue(Grid.RowDefinitionsProperty)).Add(rowDefinition25);
		rowDefinition26.SetValue(RowDefinition.HeightProperty, new GridLengthTypeConverter().ConvertFromInvariantString("1"));
		((DefinitionCollection<RowDefinition>)grid11.GetValue(Grid.RowDefinitionsProperty)).Add(rowDefinition26);
		rowDefinition27.SetValue(RowDefinition.HeightProperty, new GridLengthTypeConverter().ConvertFromInvariantString("1*"));
		((DefinitionCollection<RowDefinition>)grid11.GetValue(Grid.RowDefinitionsProperty)).Add(rowDefinition27);
		grid9.SetValue(Grid.RowProperty, 1);
		staticResourceExtension7.Key = "LineColor";
		XamlServiceProvider xamlServiceProvider13 = new XamlServiceProvider();
		Type typeFromHandle25 = typeof(IProvideValueTarget);
		object[] array13 = new object[0 + 6];
		array13[0] = grid9;
		array13[1] = grid11;
		array13[2] = grid12;
		array13[3] = grid13;
		array13[4] = grid17;
		array13[5] = glucoseTargetRegistView;
		object service13;
		xamlServiceProvider13.Add(typeFromHandle25, service13 = new SimpleValueTargetProvider(array13, VisualElement.BackgroundColorProperty, nameScope));
		xamlServiceProvider13.Add(typeof(IReferenceProvider), service13);
		Type typeFromHandle26 = typeof(IXamlTypeResolver);
		XmlNamespaceResolver xmlNamespaceResolver13 = new XmlNamespaceResolver();
		xmlNamespaceResolver13.Add("", "http://xamarin.com/schemas/2014/forms");
		xmlNamespaceResolver13.Add("x", "http://schemas.microsoft.com/winfx/2009/xaml");
		xmlNamespaceResolver13.Add("calx", "clr-namespace:Caliburn.Micro.Xamarin.Forms;assembly=Caliburn.Micro.Platform.Xamarin.Forms");
		xmlNamespaceResolver13.Add("converter", "clr-namespace:NHL.Views.Converters");
		xmlNamespaceResolver13.Add("renderer", "clr-namespace:NHL.Views.Renderer");
		xmlNamespaceResolver13.Add("effect", "clr-namespace:NHL.Views.Effect");
		xamlServiceProvider13.Add(typeFromHandle26, new XamlTypeResolver(xmlNamespaceResolver13, typeof(GlucoseTargetRegistView).GetTypeInfo().Assembly));
		xamlServiceProvider13.Add(typeof(IXmlLineInfoProvider), new XmlLineInfoProvider(new XmlLineInfo(179, 40)));
		object obj6 = ((IMarkupExtension)staticResourceExtension7).ProvideValue((IServiceProvider)xamlServiceProvider13);
		grid9.BackgroundColor = (Color)obj6;
		VisualDiagnostics.RegisterSourceInfo(obj6, new Uri("Views/GlucoseTargetRegistView.xaml", UriKind.RelativeOrAbsolute), 179, 40);
		grid9.SetValue(Grid.RowSpacingProperty, 0.0);
		grid9.SetValue(Grid.ColumnSpacingProperty, 0.0);
		grid11.Children.Add(grid9);
		VisualDiagnostics.RegisterSourceInfo(grid9, new Uri("Views/GlucoseTargetRegistView.xaml", UriKind.RelativeOrAbsolute), 179, 22);
		grid10.SetValue(Grid.RowProperty, 3);
		staticResourceExtension8.Key = "LineColor";
		XamlServiceProvider xamlServiceProvider14 = new XamlServiceProvider();
		Type typeFromHandle27 = typeof(IProvideValueTarget);
		object[] array14 = new object[0 + 6];
		array14[0] = grid10;
		array14[1] = grid11;
		array14[2] = grid12;
		array14[3] = grid13;
		array14[4] = grid17;
		array14[5] = glucoseTargetRegistView;
		object service14;
		xamlServiceProvider14.Add(typeFromHandle27, service14 = new SimpleValueTargetProvider(array14, VisualElement.BackgroundColorProperty, nameScope));
		xamlServiceProvider14.Add(typeof(IReferenceProvider), service14);
		Type typeFromHandle28 = typeof(IXamlTypeResolver);
		XmlNamespaceResolver xmlNamespaceResolver14 = new XmlNamespaceResolver();
		xmlNamespaceResolver14.Add("", "http://xamarin.com/schemas/2014/forms");
		xmlNamespaceResolver14.Add("x", "http://schemas.microsoft.com/winfx/2009/xaml");
		xmlNamespaceResolver14.Add("calx", "clr-namespace:Caliburn.Micro.Xamarin.Forms;assembly=Caliburn.Micro.Platform.Xamarin.Forms");
		xmlNamespaceResolver14.Add("converter", "clr-namespace:NHL.Views.Converters");
		xmlNamespaceResolver14.Add("renderer", "clr-namespace:NHL.Views.Renderer");
		xmlNamespaceResolver14.Add("effect", "clr-namespace:NHL.Views.Effect");
		xamlServiceProvider14.Add(typeFromHandle28, new XamlTypeResolver(xmlNamespaceResolver14, typeof(GlucoseTargetRegistView).GetTypeInfo().Assembly));
		xamlServiceProvider14.Add(typeof(IXmlLineInfoProvider), new XmlLineInfoProvider(new XmlLineInfo(180, 40)));
		object obj7 = ((IMarkupExtension)staticResourceExtension8).ProvideValue((IServiceProvider)xamlServiceProvider14);
		grid10.BackgroundColor = (Color)obj7;
		VisualDiagnostics.RegisterSourceInfo(obj7, new Uri("Views/GlucoseTargetRegistView.xaml", UriKind.RelativeOrAbsolute), 180, 40);
		grid10.SetValue(Grid.RowSpacingProperty, 0.0);
		grid10.SetValue(Grid.ColumnSpacingProperty, 0.0);
		grid11.Children.Add(grid10);
		VisualDiagnostics.RegisterSourceInfo(grid10, new Uri("Views/GlucoseTargetRegistView.xaml", UriKind.RelativeOrAbsolute), 180, 22);
		grid12.Children.Add(grid11);
		VisualDiagnostics.RegisterSourceInfo(grid11, new Uri("Views/GlucoseTargetRegistView.xaml", UriKind.RelativeOrAbsolute), 171, 18);
		grid13.Children.Add(grid12);
		VisualDiagnostics.RegisterSourceInfo(grid12, new Uri("Views/GlucoseTargetRegistView.xaml", UriKind.RelativeOrAbsolute), 143, 14);
		label7.SetValue(Grid.RowProperty, 0);
		label7.SetValue(Grid.ColumnProperty, 2);
		label7.SetValue(Label.TextProperty, "必須");
		label7.SetValue(Xamarin.Forms.View.MarginProperty, new Thickness(5.0, 5.0, 5.0, 5.0));
		BindableProperty fontSizeProperty7 = Label.FontSizeProperty;
		FontSizeConverter fontSizeConverter7 = new FontSizeConverter();
		XamlServiceProvider xamlServiceProvider15 = new XamlServiceProvider();
		Type typeFromHandle29 = typeof(IProvideValueTarget);
		object[] array15 = new object[0 + 4];
		array15[0] = label7;
		array15[1] = grid13;
		array15[2] = grid17;
		array15[3] = glucoseTargetRegistView;
		object service15;
		xamlServiceProvider15.Add(typeFromHandle29, service15 = new SimpleValueTargetProvider(array15, Label.FontSizeProperty, nameScope));
		xamlServiceProvider15.Add(typeof(IReferenceProvider), service15);
		Type typeFromHandle30 = typeof(IXamlTypeResolver);
		XmlNamespaceResolver xmlNamespaceResolver15 = new XmlNamespaceResolver();
		xmlNamespaceResolver15.Add("", "http://xamarin.com/schemas/2014/forms");
		xmlNamespaceResolver15.Add("x", "http://schemas.microsoft.com/winfx/2009/xaml");
		xmlNamespaceResolver15.Add("calx", "clr-namespace:Caliburn.Micro.Xamarin.Forms;assembly=Caliburn.Micro.Platform.Xamarin.Forms");
		xmlNamespaceResolver15.Add("converter", "clr-namespace:NHL.Views.Converters");
		xmlNamespaceResolver15.Add("renderer", "clr-namespace:NHL.Views.Renderer");
		xmlNamespaceResolver15.Add("effect", "clr-namespace:NHL.Views.Effect");
		xamlServiceProvider15.Add(typeFromHandle30, new XamlTypeResolver(xmlNamespaceResolver15, typeof(GlucoseTargetRegistView).GetTypeInfo().Assembly));
		xamlServiceProvider15.Add(typeof(IXmlLineInfoProvider), new XmlLineInfoProvider(new XmlLineInfo(186, 76)));
		label7.SetValue(fontSizeProperty7, ((IExtendedTypeConverter)fontSizeConverter7).ConvertFromInvariantString("Large", (IServiceProvider)xamlServiceProvider15));
		staticResourceExtension9.Key = "LabelColor";
		XamlServiceProvider xamlServiceProvider16 = new XamlServiceProvider();
		Type typeFromHandle31 = typeof(IProvideValueTarget);
		object[] array16 = new object[0 + 4];
		array16[0] = label7;
		array16[1] = grid13;
		array16[2] = grid17;
		array16[3] = glucoseTargetRegistView;
		object service16;
		xamlServiceProvider16.Add(typeFromHandle31, service16 = new SimpleValueTargetProvider(array16, Label.TextColorProperty, nameScope));
		xamlServiceProvider16.Add(typeof(IReferenceProvider), service16);
		Type typeFromHandle32 = typeof(IXamlTypeResolver);
		XmlNamespaceResolver xmlNamespaceResolver16 = new XmlNamespaceResolver();
		xmlNamespaceResolver16.Add("", "http://xamarin.com/schemas/2014/forms");
		xmlNamespaceResolver16.Add("x", "http://schemas.microsoft.com/winfx/2009/xaml");
		xmlNamespaceResolver16.Add("calx", "clr-namespace:Caliburn.Micro.Xamarin.Forms;assembly=Caliburn.Micro.Platform.Xamarin.Forms");
		xmlNamespaceResolver16.Add("converter", "clr-namespace:NHL.Views.Converters");
		xmlNamespaceResolver16.Add("renderer", "clr-namespace:NHL.Views.Renderer");
		xmlNamespaceResolver16.Add("effect", "clr-namespace:NHL.Views.Effect");
		xamlServiceProvider16.Add(typeFromHandle32, new XamlTypeResolver(xmlNamespaceResolver16, typeof(GlucoseTargetRegistView).GetTypeInfo().Assembly));
		xamlServiceProvider16.Add(typeof(IXmlLineInfoProvider), new XmlLineInfoProvider(new XmlLineInfo(186, 93)));
		object obj8 = ((IMarkupExtension)staticResourceExtension9).ProvideValue((IServiceProvider)xamlServiceProvider16);
		label7.TextColor = (Color)obj8;
		VisualDiagnostics.RegisterSourceInfo(obj8, new Uri("Views/GlucoseTargetRegistView.xaml", UriKind.RelativeOrAbsolute), 186, 93);
		label7.SetValue(Label.VerticalTextAlignmentProperty, new TextAlignmentConverter().ConvertFromInvariantString("Center"));
		staticResourceExtension10.Key = "GlucoseTargetThresholdToBisibleConverter";
		XamlServiceProvider xamlServiceProvider17 = new XamlServiceProvider();
		Type typeFromHandle33 = typeof(IProvideValueTarget);
		object[] array17 = new object[0 + 5];
		array17[0] = bindingExtension5;
		array17[1] = label7;
		array17[2] = grid13;
		array17[3] = grid17;
		array17[4] = glucoseTargetRegistView;
		object service17;
		xamlServiceProvider17.Add(typeFromHandle33, service17 = new SimpleValueTargetProvider(array17, typeof(BindingExtension).GetRuntimeProperty("Converter"), nameScope));
		xamlServiceProvider17.Add(typeof(IReferenceProvider), service17);
		Type typeFromHandle34 = typeof(IXamlTypeResolver);
		XmlNamespaceResolver xmlNamespaceResolver17 = new XmlNamespaceResolver();
		xmlNamespaceResolver17.Add("", "http://xamarin.com/schemas/2014/forms");
		xmlNamespaceResolver17.Add("x", "http://schemas.microsoft.com/winfx/2009/xaml");
		xmlNamespaceResolver17.Add("calx", "clr-namespace:Caliburn.Micro.Xamarin.Forms;assembly=Caliburn.Micro.Platform.Xamarin.Forms");
		xmlNamespaceResolver17.Add("converter", "clr-namespace:NHL.Views.Converters");
		xmlNamespaceResolver17.Add("renderer", "clr-namespace:NHL.Views.Renderer");
		xmlNamespaceResolver17.Add("effect", "clr-namespace:NHL.Views.Effect");
		xamlServiceProvider17.Add(typeFromHandle34, new XamlTypeResolver(xmlNamespaceResolver17, typeof(GlucoseTargetRegistView).GetTypeInfo().Assembly));
		xamlServiceProvider17.Add(typeof(IXmlLineInfoProvider), new XmlLineInfoProvider(new XmlLineInfo(186, 164)));
		object target3 = (bindingExtension5.Converter = (IValueConverter)((IMarkupExtension)staticResourceExtension10).ProvideValue((IServiceProvider)xamlServiceProvider17));
		VisualDiagnostics.RegisterSourceInfo(target3, new Uri("Views/GlucoseTargetRegistView.xaml", UriKind.RelativeOrAbsolute), 186, 164);
		bindingExtension5.Path = "GlucoseLittleHighValue";
		BindingBase binding4 = ((IMarkupExtension<BindingBase>)bindingExtension5).ProvideValue((IServiceProvider)null);
		label7.SetBinding(VisualElement.IsVisibleProperty, binding4);
		label7.Effects.Add(fixedFontSizeLabelEffect7);
		VisualDiagnostics.RegisterSourceInfo(fixedFontSizeLabelEffect7, new Uri("Views/GlucoseTargetRegistView.xaml", UriKind.RelativeOrAbsolute), 188, 22);
		grid13.Children.Add(label7);
		VisualDiagnostics.RegisterSourceInfo(label7, new Uri("Views/GlucoseTargetRegistView.xaml", UriKind.RelativeOrAbsolute), 186, 14);
		pickerView2.SetValue(Grid.RowProperty, 0);
		pickerView2.SetValue(Grid.ColumnProperty, 2);
		pickerView2.SetValue(Xamarin.Forms.View.MarginProperty, new Thickness(0.0, 5.0, 0.0, 5.0));
		bindingExtension6.Mode = BindingMode.TwoWay;
		bindingExtension6.Path = "GlucoseLittleHighValue";
		BindingBase binding5 = ((IMarkupExtension<BindingBase>)bindingExtension6).ProvideValue((IServiceProvider)null);
		pickerView2.SetBinding(Picker.SelectedItemProperty, binding5);
		bindingExtension7.Path = "ThresholdList";
		BindingBase binding6 = ((IMarkupExtension<BindingBase>)bindingExtension7).ProvideValue((IServiceProvider)null);
		pickerView2.SetBinding(Picker.ItemsSourceProperty, binding6);
		bindingExtension8.Path = "Name";
		BindingBase target4 = (pickerView2.ItemDisplayBinding = ((IMarkupExtension<BindingBase>)bindingExtension8).ProvideValue((IServiceProvider)null));
		VisualDiagnostics.RegisterSourceInfo(target4, new Uri("Views/GlucoseTargetRegistView.xaml", UriKind.RelativeOrAbsolute), 191, 180);
		pickerView2.SetValue(VisualElement.BackgroundColorProperty, Color.Transparent);
		pickerView2.Effects.Add(fixedFontSizeTextBoxEffect2);
		VisualDiagnostics.RegisterSourceInfo(fixedFontSizeTextBoxEffect2, new Uri("Views/GlucoseTargetRegistView.xaml", UriKind.RelativeOrAbsolute), 193, 22);
		grid13.Children.Add(pickerView2);
		VisualDiagnostics.RegisterSourceInfo(pickerView2, new Uri("Views/GlucoseTargetRegistView.xaml", UriKind.RelativeOrAbsolute), 191, 14);
		label8.SetValue(Grid.RowProperty, 0);
		label8.SetValue(Grid.ColumnProperty, 3);
		label8.SetValue(Label.TextProperty, "以下");
		label8.SetValue(Xamarin.Forms.View.MarginProperty, new Thickness(0.0, 5.0, 10.0, 5.0));
		BindableProperty fontSizeProperty8 = Label.FontSizeProperty;
		FontSizeConverter fontSizeConverter8 = new FontSizeConverter();
		XamlServiceProvider xamlServiceProvider18 = new XamlServiceProvider();
		Type typeFromHandle35 = typeof(IProvideValueTarget);
		object[] array18 = new object[0 + 4];
		array18[0] = label8;
		array18[1] = grid13;
		array18[2] = grid17;
		array18[3] = glucoseTargetRegistView;
		object service18;
		xamlServiceProvider18.Add(typeFromHandle35, service18 = new SimpleValueTargetProvider(array18, Label.FontSizeProperty, nameScope));
		xamlServiceProvider18.Add(typeof(IReferenceProvider), service18);
		Type typeFromHandle36 = typeof(IXamlTypeResolver);
		XmlNamespaceResolver xmlNamespaceResolver18 = new XmlNamespaceResolver();
		xmlNamespaceResolver18.Add("", "http://xamarin.com/schemas/2014/forms");
		xmlNamespaceResolver18.Add("x", "http://schemas.microsoft.com/winfx/2009/xaml");
		xmlNamespaceResolver18.Add("calx", "clr-namespace:Caliburn.Micro.Xamarin.Forms;assembly=Caliburn.Micro.Platform.Xamarin.Forms");
		xmlNamespaceResolver18.Add("converter", "clr-namespace:NHL.Views.Converters");
		xmlNamespaceResolver18.Add("renderer", "clr-namespace:NHL.Views.Renderer");
		xmlNamespaceResolver18.Add("effect", "clr-namespace:NHL.Views.Effect");
		xamlServiceProvider18.Add(typeFromHandle36, new XamlTypeResolver(xmlNamespaceResolver18, typeof(GlucoseTargetRegistView).GetTypeInfo().Assembly));
		xamlServiceProvider18.Add(typeof(IXmlLineInfoProvider), new XmlLineInfoProvider(new XmlLineInfo(196, 78)));
		label8.SetValue(fontSizeProperty8, ((IExtendedTypeConverter)fontSizeConverter8).ConvertFromInvariantString("Large", (IServiceProvider)xamlServiceProvider18));
		label8.SetValue(Label.VerticalTextAlignmentProperty, new TextAlignmentConverter().ConvertFromInvariantString("Center"));
		label8.Effects.Add(fixedFontSizeLabelEffect8);
		VisualDiagnostics.RegisterSourceInfo(fixedFontSizeLabelEffect8, new Uri("Views/GlucoseTargetRegistView.xaml", UriKind.RelativeOrAbsolute), 198, 22);
		grid13.Children.Add(label8);
		VisualDiagnostics.RegisterSourceInfo(label8, new Uri("Views/GlucoseTargetRegistView.xaml", UriKind.RelativeOrAbsolute), 196, 14);
		label9.SetValue(Grid.RowProperty, 2);
		label9.SetValue(Grid.ColumnProperty, 2);
		label9.SetValue(Label.TextProperty, "必須");
		label9.SetValue(Xamarin.Forms.View.MarginProperty, new Thickness(5.0, 5.0, 5.0, 5.0));
		BindableProperty fontSizeProperty9 = Label.FontSizeProperty;
		FontSizeConverter fontSizeConverter9 = new FontSizeConverter();
		XamlServiceProvider xamlServiceProvider19 = new XamlServiceProvider();
		Type typeFromHandle37 = typeof(IProvideValueTarget);
		object[] array19 = new object[0 + 4];
		array19[0] = label9;
		array19[1] = grid13;
		array19[2] = grid17;
		array19[3] = glucoseTargetRegistView;
		object service19;
		xamlServiceProvider19.Add(typeFromHandle37, service19 = new SimpleValueTargetProvider(array19, Label.FontSizeProperty, nameScope));
		xamlServiceProvider19.Add(typeof(IReferenceProvider), service19);
		Type typeFromHandle38 = typeof(IXamlTypeResolver);
		XmlNamespaceResolver xmlNamespaceResolver19 = new XmlNamespaceResolver();
		xmlNamespaceResolver19.Add("", "http://xamarin.com/schemas/2014/forms");
		xmlNamespaceResolver19.Add("x", "http://schemas.microsoft.com/winfx/2009/xaml");
		xmlNamespaceResolver19.Add("calx", "clr-namespace:Caliburn.Micro.Xamarin.Forms;assembly=Caliburn.Micro.Platform.Xamarin.Forms");
		xmlNamespaceResolver19.Add("converter", "clr-namespace:NHL.Views.Converters");
		xmlNamespaceResolver19.Add("renderer", "clr-namespace:NHL.Views.Renderer");
		xmlNamespaceResolver19.Add("effect", "clr-namespace:NHL.Views.Effect");
		xamlServiceProvider19.Add(typeFromHandle38, new XamlTypeResolver(xmlNamespaceResolver19, typeof(GlucoseTargetRegistView).GetTypeInfo().Assembly));
		xamlServiceProvider19.Add(typeof(IXmlLineInfoProvider), new XmlLineInfoProvider(new XmlLineInfo(202, 76)));
		label9.SetValue(fontSizeProperty9, ((IExtendedTypeConverter)fontSizeConverter9).ConvertFromInvariantString("Large", (IServiceProvider)xamlServiceProvider19));
		staticResourceExtension11.Key = "LabelColor";
		XamlServiceProvider xamlServiceProvider20 = new XamlServiceProvider();
		Type typeFromHandle39 = typeof(IProvideValueTarget);
		object[] array20 = new object[0 + 4];
		array20[0] = label9;
		array20[1] = grid13;
		array20[2] = grid17;
		array20[3] = glucoseTargetRegistView;
		object service20;
		xamlServiceProvider20.Add(typeFromHandle39, service20 = new SimpleValueTargetProvider(array20, Label.TextColorProperty, nameScope));
		xamlServiceProvider20.Add(typeof(IReferenceProvider), service20);
		Type typeFromHandle40 = typeof(IXamlTypeResolver);
		XmlNamespaceResolver xmlNamespaceResolver20 = new XmlNamespaceResolver();
		xmlNamespaceResolver20.Add("", "http://xamarin.com/schemas/2014/forms");
		xmlNamespaceResolver20.Add("x", "http://schemas.microsoft.com/winfx/2009/xaml");
		xmlNamespaceResolver20.Add("calx", "clr-namespace:Caliburn.Micro.Xamarin.Forms;assembly=Caliburn.Micro.Platform.Xamarin.Forms");
		xmlNamespaceResolver20.Add("converter", "clr-namespace:NHL.Views.Converters");
		xmlNamespaceResolver20.Add("renderer", "clr-namespace:NHL.Views.Renderer");
		xmlNamespaceResolver20.Add("effect", "clr-namespace:NHL.Views.Effect");
		xamlServiceProvider20.Add(typeFromHandle40, new XamlTypeResolver(xmlNamespaceResolver20, typeof(GlucoseTargetRegistView).GetTypeInfo().Assembly));
		xamlServiceProvider20.Add(typeof(IXmlLineInfoProvider), new XmlLineInfoProvider(new XmlLineInfo(202, 93)));
		object obj9 = ((IMarkupExtension)staticResourceExtension11).ProvideValue((IServiceProvider)xamlServiceProvider20);
		label9.TextColor = (Color)obj9;
		VisualDiagnostics.RegisterSourceInfo(obj9, new Uri("Views/GlucoseTargetRegistView.xaml", UriKind.RelativeOrAbsolute), 202, 93);
		label9.SetValue(Label.VerticalTextAlignmentProperty, new TextAlignmentConverter().ConvertFromInvariantString("Center"));
		staticResourceExtension12.Key = "GlucoseTargetThresholdToBisibleConverter";
		XamlServiceProvider xamlServiceProvider21 = new XamlServiceProvider();
		Type typeFromHandle41 = typeof(IProvideValueTarget);
		object[] array21 = new object[0 + 5];
		array21[0] = bindingExtension9;
		array21[1] = label9;
		array21[2] = grid13;
		array21[3] = grid17;
		array21[4] = glucoseTargetRegistView;
		object service21;
		xamlServiceProvider21.Add(typeFromHandle41, service21 = new SimpleValueTargetProvider(array21, typeof(BindingExtension).GetRuntimeProperty("Converter"), nameScope));
		xamlServiceProvider21.Add(typeof(IReferenceProvider), service21);
		Type typeFromHandle42 = typeof(IXamlTypeResolver);
		XmlNamespaceResolver xmlNamespaceResolver21 = new XmlNamespaceResolver();
		xmlNamespaceResolver21.Add("", "http://xamarin.com/schemas/2014/forms");
		xmlNamespaceResolver21.Add("x", "http://schemas.microsoft.com/winfx/2009/xaml");
		xmlNamespaceResolver21.Add("calx", "clr-namespace:Caliburn.Micro.Xamarin.Forms;assembly=Caliburn.Micro.Platform.Xamarin.Forms");
		xmlNamespaceResolver21.Add("converter", "clr-namespace:NHL.Views.Converters");
		xmlNamespaceResolver21.Add("renderer", "clr-namespace:NHL.Views.Renderer");
		xmlNamespaceResolver21.Add("effect", "clr-namespace:NHL.Views.Effect");
		xamlServiceProvider21.Add(typeFromHandle42, new XamlTypeResolver(xmlNamespaceResolver21, typeof(GlucoseTargetRegistView).GetTypeInfo().Assembly));
		xamlServiceProvider21.Add(typeof(IXmlLineInfoProvider), new XmlLineInfoProvider(new XmlLineInfo(202, 164)));
		object target5 = (bindingExtension9.Converter = (IValueConverter)((IMarkupExtension)staticResourceExtension12).ProvideValue((IServiceProvider)xamlServiceProvider21));
		VisualDiagnostics.RegisterSourceInfo(target5, new Uri("Views/GlucoseTargetRegistView.xaml", UriKind.RelativeOrAbsolute), 202, 164);
		bindingExtension9.Path = "GlucoseLittleLowValue";
		BindingBase binding7 = ((IMarkupExtension<BindingBase>)bindingExtension9).ProvideValue((IServiceProvider)null);
		label9.SetBinding(VisualElement.IsVisibleProperty, binding7);
		label9.Effects.Add(fixedFontSizeLabelEffect9);
		VisualDiagnostics.RegisterSourceInfo(fixedFontSizeLabelEffect9, new Uri("Views/GlucoseTargetRegistView.xaml", UriKind.RelativeOrAbsolute), 204, 22);
		grid13.Children.Add(label9);
		VisualDiagnostics.RegisterSourceInfo(label9, new Uri("Views/GlucoseTargetRegistView.xaml", UriKind.RelativeOrAbsolute), 202, 14);
		pickerView3.SetValue(Grid.RowProperty, 2);
		pickerView3.SetValue(Grid.ColumnProperty, 2);
		pickerView3.SetValue(Xamarin.Forms.View.MarginProperty, new Thickness(0.0, 5.0, 0.0, 5.0));
		bindingExtension10.Mode = BindingMode.TwoWay;
		bindingExtension10.Path = "GlucoseLittleLowValue";
		BindingBase binding8 = ((IMarkupExtension<BindingBase>)bindingExtension10).ProvideValue((IServiceProvider)null);
		pickerView3.SetBinding(Picker.SelectedItemProperty, binding8);
		bindingExtension11.Path = "ThresholdList";
		BindingBase binding9 = ((IMarkupExtension<BindingBase>)bindingExtension11).ProvideValue((IServiceProvider)null);
		pickerView3.SetBinding(Picker.ItemsSourceProperty, binding9);
		bindingExtension12.Path = "Name";
		BindingBase target6 = (pickerView3.ItemDisplayBinding = ((IMarkupExtension<BindingBase>)bindingExtension12).ProvideValue((IServiceProvider)null));
		VisualDiagnostics.RegisterSourceInfo(target6, new Uri("Views/GlucoseTargetRegistView.xaml", UriKind.RelativeOrAbsolute), 207, 178);
		pickerView3.SetValue(VisualElement.BackgroundColorProperty, Color.Transparent);
		pickerView3.Effects.Add(fixedFontSizeTextBoxEffect3);
		VisualDiagnostics.RegisterSourceInfo(fixedFontSizeTextBoxEffect3, new Uri("Views/GlucoseTargetRegistView.xaml", UriKind.RelativeOrAbsolute), 209, 22);
		grid13.Children.Add(pickerView3);
		VisualDiagnostics.RegisterSourceInfo(pickerView3, new Uri("Views/GlucoseTargetRegistView.xaml", UriKind.RelativeOrAbsolute), 207, 14);
		label10.SetValue(Grid.RowProperty, 2);
		label10.SetValue(Grid.ColumnProperty, 3);
		label10.SetValue(Label.TextProperty, "以上");
		label10.SetValue(Xamarin.Forms.View.MarginProperty, new Thickness(0.0, 5.0, 10.0, 5.0));
		BindableProperty fontSizeProperty10 = Label.FontSizeProperty;
		FontSizeConverter fontSizeConverter10 = new FontSizeConverter();
		XamlServiceProvider xamlServiceProvider22 = new XamlServiceProvider();
		Type typeFromHandle43 = typeof(IProvideValueTarget);
		object[] array22 = new object[0 + 4];
		array22[0] = label10;
		array22[1] = grid13;
		array22[2] = grid17;
		array22[3] = glucoseTargetRegistView;
		object service22;
		xamlServiceProvider22.Add(typeFromHandle43, service22 = new SimpleValueTargetProvider(array22, Label.FontSizeProperty, nameScope));
		xamlServiceProvider22.Add(typeof(IReferenceProvider), service22);
		Type typeFromHandle44 = typeof(IXamlTypeResolver);
		XmlNamespaceResolver xmlNamespaceResolver22 = new XmlNamespaceResolver();
		xmlNamespaceResolver22.Add("", "http://xamarin.com/schemas/2014/forms");
		xmlNamespaceResolver22.Add("x", "http://schemas.microsoft.com/winfx/2009/xaml");
		xmlNamespaceResolver22.Add("calx", "clr-namespace:Caliburn.Micro.Xamarin.Forms;assembly=Caliburn.Micro.Platform.Xamarin.Forms");
		xmlNamespaceResolver22.Add("converter", "clr-namespace:NHL.Views.Converters");
		xmlNamespaceResolver22.Add("renderer", "clr-namespace:NHL.Views.Renderer");
		xmlNamespaceResolver22.Add("effect", "clr-namespace:NHL.Views.Effect");
		xamlServiceProvider22.Add(typeFromHandle44, new XamlTypeResolver(xmlNamespaceResolver22, typeof(GlucoseTargetRegistView).GetTypeInfo().Assembly));
		xamlServiceProvider22.Add(typeof(IXmlLineInfoProvider), new XmlLineInfoProvider(new XmlLineInfo(212, 79)));
		label10.SetValue(fontSizeProperty10, ((IExtendedTypeConverter)fontSizeConverter10).ConvertFromInvariantString("Large", (IServiceProvider)xamlServiceProvider22));
		label10.SetValue(Label.VerticalTextAlignmentProperty, new TextAlignmentConverter().ConvertFromInvariantString("Center"));
		label10.Effects.Add(fixedFontSizeLabelEffect10);
		VisualDiagnostics.RegisterSourceInfo(fixedFontSizeLabelEffect10, new Uri("Views/GlucoseTargetRegistView.xaml", UriKind.RelativeOrAbsolute), 214, 22);
		grid13.Children.Add(label10);
		VisualDiagnostics.RegisterSourceInfo(label10, new Uri("Views/GlucoseTargetRegistView.xaml", UriKind.RelativeOrAbsolute), 212, 14);
		grid17.Children.Add(grid13);
		VisualDiagnostics.RegisterSourceInfo(grid13, new Uri("Views/GlucoseTargetRegistView.xaml", UriKind.RelativeOrAbsolute), 102, 10);
		grid16.SetValue(Grid.RowProperty, 2);
		columnDefinition15.SetValue(ColumnDefinition.WidthProperty, new GridLengthTypeConverter().ConvertFromInvariantString("Auto"));
		((DefinitionCollection<ColumnDefinition>)grid16.GetValue(Grid.ColumnDefinitionsProperty)).Add(columnDefinition15);
		columnDefinition16.SetValue(ColumnDefinition.WidthProperty, new GridLengthTypeConverter().ConvertFromInvariantString("*"));
		((DefinitionCollection<ColumnDefinition>)grid16.GetValue(Grid.ColumnDefinitionsProperty)).Add(columnDefinition16);
		columnDefinition17.SetValue(ColumnDefinition.WidthProperty, new GridLengthTypeConverter().ConvertFromInvariantString("Auto"));
		((DefinitionCollection<ColumnDefinition>)grid16.GetValue(Grid.ColumnDefinitionsProperty)).Add(columnDefinition17);
		columnDefinition18.SetValue(ColumnDefinition.WidthProperty, new GridLengthTypeConverter().ConvertFromInvariantString("Auto"));
		((DefinitionCollection<ColumnDefinition>)grid16.GetValue(Grid.ColumnDefinitionsProperty)).Add(columnDefinition18);
		label11.SetValue(Xamarin.Forms.View.MarginProperty, new Thickness(10.0, 5.0, 0.0, 5.0));
		label11.SetValue(Label.TextProperty, "低い");
		BindableProperty fontSizeProperty11 = Label.FontSizeProperty;
		FontSizeConverter fontSizeConverter11 = new FontSizeConverter();
		XamlServiceProvider xamlServiceProvider23 = new XamlServiceProvider();
		Type typeFromHandle45 = typeof(IProvideValueTarget);
		object[] array23 = new object[0 + 4];
		array23[0] = label11;
		array23[1] = grid16;
		array23[2] = grid17;
		array23[3] = glucoseTargetRegistView;
		object service23;
		xamlServiceProvider23.Add(typeFromHandle45, service23 = new SimpleValueTargetProvider(array23, Label.FontSizeProperty, nameScope));
		xamlServiceProvider23.Add(typeof(IReferenceProvider), service23);
		Type typeFromHandle46 = typeof(IXamlTypeResolver);
		XmlNamespaceResolver xmlNamespaceResolver23 = new XmlNamespaceResolver();
		xmlNamespaceResolver23.Add("", "http://xamarin.com/schemas/2014/forms");
		xmlNamespaceResolver23.Add("x", "http://schemas.microsoft.com/winfx/2009/xaml");
		xmlNamespaceResolver23.Add("calx", "clr-namespace:Caliburn.Micro.Xamarin.Forms;assembly=Caliburn.Micro.Platform.Xamarin.Forms");
		xmlNamespaceResolver23.Add("converter", "clr-namespace:NHL.Views.Converters");
		xmlNamespaceResolver23.Add("renderer", "clr-namespace:NHL.Views.Renderer");
		xmlNamespaceResolver23.Add("effect", "clr-namespace:NHL.Views.Effect");
		xamlServiceProvider23.Add(typeFromHandle46, new XamlTypeResolver(xmlNamespaceResolver23, typeof(GlucoseTargetRegistView).GetTypeInfo().Assembly));
		xamlServiceProvider23.Add(typeof(IXmlLineInfoProvider), new XmlLineInfoProvider(new XmlLineInfo(228, 48)));
		label11.SetValue(fontSizeProperty11, ((IExtendedTypeConverter)fontSizeConverter11).ConvertFromInvariantString("Large", (IServiceProvider)xamlServiceProvider23));
		label11.SetValue(Xamarin.Forms.View.HorizontalOptionsProperty, LayoutOptions.Start);
		label11.SetValue(Label.VerticalTextAlignmentProperty, new TextAlignmentConverter().ConvertFromInvariantString("Center"));
		label11.SetValue(Label.TextColorProperty, Color.Blue);
		label11.Effects.Add(fixedFontSizeLabelEffect11);
		VisualDiagnostics.RegisterSourceInfo(fixedFontSizeLabelEffect11, new Uri("Views/GlucoseTargetRegistView.xaml", UriKind.RelativeOrAbsolute), 230, 22);
		grid16.Children.Add(label11);
		VisualDiagnostics.RegisterSourceInfo(label11, new Uri("Views/GlucoseTargetRegistView.xaml", UriKind.RelativeOrAbsolute), 228, 14);
		grid15.SetValue(Grid.ColumnProperty, 1);
		rowDefinition28.SetValue(RowDefinition.HeightProperty, new GridLengthTypeConverter().ConvertFromInvariantString("*"));
		((DefinitionCollection<RowDefinition>)grid15.GetValue(Grid.RowDefinitionsProperty)).Add(rowDefinition28);
		rowDefinition29.SetValue(RowDefinition.HeightProperty, new GridLengthTypeConverter().ConvertFromInvariantString("1"));
		((DefinitionCollection<RowDefinition>)grid15.GetValue(Grid.RowDefinitionsProperty)).Add(rowDefinition29);
		rowDefinition30.SetValue(RowDefinition.HeightProperty, new GridLengthTypeConverter().ConvertFromInvariantString("*"));
		((DefinitionCollection<RowDefinition>)grid15.GetValue(Grid.RowDefinitionsProperty)).Add(rowDefinition30);
		grid14.SetValue(Grid.RowProperty, 1);
		staticResourceExtension13.Key = "LineColor";
		XamlServiceProvider xamlServiceProvider24 = new XamlServiceProvider();
		Type typeFromHandle47 = typeof(IProvideValueTarget);
		object[] array24 = new object[0 + 5];
		array24[0] = grid14;
		array24[1] = grid15;
		array24[2] = grid16;
		array24[3] = grid17;
		array24[4] = glucoseTargetRegistView;
		object service24;
		xamlServiceProvider24.Add(typeFromHandle47, service24 = new SimpleValueTargetProvider(array24, VisualElement.BackgroundColorProperty, nameScope));
		xamlServiceProvider24.Add(typeof(IReferenceProvider), service24);
		Type typeFromHandle48 = typeof(IXamlTypeResolver);
		XmlNamespaceResolver xmlNamespaceResolver24 = new XmlNamespaceResolver();
		xmlNamespaceResolver24.Add("", "http://xamarin.com/schemas/2014/forms");
		xmlNamespaceResolver24.Add("x", "http://schemas.microsoft.com/winfx/2009/xaml");
		xmlNamespaceResolver24.Add("calx", "clr-namespace:Caliburn.Micro.Xamarin.Forms;assembly=Caliburn.Micro.Platform.Xamarin.Forms");
		xmlNamespaceResolver24.Add("converter", "clr-namespace:NHL.Views.Converters");
		xmlNamespaceResolver24.Add("renderer", "clr-namespace:NHL.Views.Renderer");
		xmlNamespaceResolver24.Add("effect", "clr-namespace:NHL.Views.Effect");
		xamlServiceProvider24.Add(typeFromHandle48, new XamlTypeResolver(xmlNamespaceResolver24, typeof(GlucoseTargetRegistView).GetTypeInfo().Assembly));
		xamlServiceProvider24.Add(typeof(IXmlLineInfoProvider), new XmlLineInfoProvider(new XmlLineInfo(241, 36)));
		object obj10 = ((IMarkupExtension)staticResourceExtension13).ProvideValue((IServiceProvider)xamlServiceProvider24);
		grid14.BackgroundColor = (Color)obj10;
		VisualDiagnostics.RegisterSourceInfo(obj10, new Uri("Views/GlucoseTargetRegistView.xaml", UriKind.RelativeOrAbsolute), 241, 36);
		grid14.SetValue(Grid.RowSpacingProperty, 0.0);
		grid14.SetValue(Grid.ColumnSpacingProperty, 0.0);
		grid15.Children.Add(grid14);
		VisualDiagnostics.RegisterSourceInfo(grid14, new Uri("Views/GlucoseTargetRegistView.xaml", UriKind.RelativeOrAbsolute), 241, 18);
		grid16.Children.Add(grid15);
		VisualDiagnostics.RegisterSourceInfo(grid15, new Uri("Views/GlucoseTargetRegistView.xaml", UriKind.RelativeOrAbsolute), 235, 14);
		label12.SetValue(Grid.ColumnProperty, 2);
		label12.SetValue(Label.TextProperty, "必須");
		label12.SetValue(Xamarin.Forms.View.MarginProperty, new Thickness(5.0, 5.0, 5.0, 5.0));
		BindableProperty fontSizeProperty12 = Label.FontSizeProperty;
		FontSizeConverter fontSizeConverter12 = new FontSizeConverter();
		XamlServiceProvider xamlServiceProvider25 = new XamlServiceProvider();
		Type typeFromHandle49 = typeof(IProvideValueTarget);
		object[] array25 = new object[0 + 4];
		array25[0] = label12;
		array25[1] = grid16;
		array25[2] = grid17;
		array25[3] = glucoseTargetRegistView;
		object service25;
		xamlServiceProvider25.Add(typeFromHandle49, service25 = new SimpleValueTargetProvider(array25, Label.FontSizeProperty, nameScope));
		xamlServiceProvider25.Add(typeof(IReferenceProvider), service25);
		Type typeFromHandle50 = typeof(IXamlTypeResolver);
		XmlNamespaceResolver xmlNamespaceResolver25 = new XmlNamespaceResolver();
		xmlNamespaceResolver25.Add("", "http://xamarin.com/schemas/2014/forms");
		xmlNamespaceResolver25.Add("x", "http://schemas.microsoft.com/winfx/2009/xaml");
		xmlNamespaceResolver25.Add("calx", "clr-namespace:Caliburn.Micro.Xamarin.Forms;assembly=Caliburn.Micro.Platform.Xamarin.Forms");
		xmlNamespaceResolver25.Add("converter", "clr-namespace:NHL.Views.Converters");
		xmlNamespaceResolver25.Add("renderer", "clr-namespace:NHL.Views.Renderer");
		xmlNamespaceResolver25.Add("effect", "clr-namespace:NHL.Views.Effect");
		xamlServiceProvider25.Add(typeFromHandle50, new XamlTypeResolver(xmlNamespaceResolver25, typeof(GlucoseTargetRegistView).GetTypeInfo().Assembly));
		xamlServiceProvider25.Add(typeof(IXmlLineInfoProvider), new XmlLineInfoProvider(new XmlLineInfo(245, 63)));
		label12.SetValue(fontSizeProperty12, ((IExtendedTypeConverter)fontSizeConverter12).ConvertFromInvariantString("Large", (IServiceProvider)xamlServiceProvider25));
		staticResourceExtension14.Key = "LabelColor";
		XamlServiceProvider xamlServiceProvider26 = new XamlServiceProvider();
		Type typeFromHandle51 = typeof(IProvideValueTarget);
		object[] array26 = new object[0 + 4];
		array26[0] = label12;
		array26[1] = grid16;
		array26[2] = grid17;
		array26[3] = glucoseTargetRegistView;
		object service26;
		xamlServiceProvider26.Add(typeFromHandle51, service26 = new SimpleValueTargetProvider(array26, Label.TextColorProperty, nameScope));
		xamlServiceProvider26.Add(typeof(IReferenceProvider), service26);
		Type typeFromHandle52 = typeof(IXamlTypeResolver);
		XmlNamespaceResolver xmlNamespaceResolver26 = new XmlNamespaceResolver();
		xmlNamespaceResolver26.Add("", "http://xamarin.com/schemas/2014/forms");
		xmlNamespaceResolver26.Add("x", "http://schemas.microsoft.com/winfx/2009/xaml");
		xmlNamespaceResolver26.Add("calx", "clr-namespace:Caliburn.Micro.Xamarin.Forms;assembly=Caliburn.Micro.Platform.Xamarin.Forms");
		xmlNamespaceResolver26.Add("converter", "clr-namespace:NHL.Views.Converters");
		xmlNamespaceResolver26.Add("renderer", "clr-namespace:NHL.Views.Renderer");
		xmlNamespaceResolver26.Add("effect", "clr-namespace:NHL.Views.Effect");
		xamlServiceProvider26.Add(typeFromHandle52, new XamlTypeResolver(xmlNamespaceResolver26, typeof(GlucoseTargetRegistView).GetTypeInfo().Assembly));
		xamlServiceProvider26.Add(typeof(IXmlLineInfoProvider), new XmlLineInfoProvider(new XmlLineInfo(245, 80)));
		object obj11 = ((IMarkupExtension)staticResourceExtension14).ProvideValue((IServiceProvider)xamlServiceProvider26);
		label12.TextColor = (Color)obj11;
		VisualDiagnostics.RegisterSourceInfo(obj11, new Uri("Views/GlucoseTargetRegistView.xaml", UriKind.RelativeOrAbsolute), 245, 80);
		label12.SetValue(Label.VerticalTextAlignmentProperty, new TextAlignmentConverter().ConvertFromInvariantString("Center"));
		staticResourceExtension15.Key = "GlucoseTargetThresholdToBisibleConverter";
		XamlServiceProvider xamlServiceProvider27 = new XamlServiceProvider();
		Type typeFromHandle53 = typeof(IProvideValueTarget);
		object[] array27 = new object[0 + 5];
		array27[0] = bindingExtension13;
		array27[1] = label12;
		array27[2] = grid16;
		array27[3] = grid17;
		array27[4] = glucoseTargetRegistView;
		object service27;
		xamlServiceProvider27.Add(typeFromHandle53, service27 = new SimpleValueTargetProvider(array27, typeof(BindingExtension).GetRuntimeProperty("Converter"), nameScope));
		xamlServiceProvider27.Add(typeof(IReferenceProvider), service27);
		Type typeFromHandle54 = typeof(IXamlTypeResolver);
		XmlNamespaceResolver xmlNamespaceResolver27 = new XmlNamespaceResolver();
		xmlNamespaceResolver27.Add("", "http://xamarin.com/schemas/2014/forms");
		xmlNamespaceResolver27.Add("x", "http://schemas.microsoft.com/winfx/2009/xaml");
		xmlNamespaceResolver27.Add("calx", "clr-namespace:Caliburn.Micro.Xamarin.Forms;assembly=Caliburn.Micro.Platform.Xamarin.Forms");
		xmlNamespaceResolver27.Add("converter", "clr-namespace:NHL.Views.Converters");
		xmlNamespaceResolver27.Add("renderer", "clr-namespace:NHL.Views.Renderer");
		xmlNamespaceResolver27.Add("effect", "clr-namespace:NHL.Views.Effect");
		xamlServiceProvider27.Add(typeFromHandle54, new XamlTypeResolver(xmlNamespaceResolver27, typeof(GlucoseTargetRegistView).GetTypeInfo().Assembly));
		xamlServiceProvider27.Add(typeof(IXmlLineInfoProvider), new XmlLineInfoProvider(new XmlLineInfo(245, 151)));
		object target7 = (bindingExtension13.Converter = (IValueConverter)((IMarkupExtension)staticResourceExtension15).ProvideValue((IServiceProvider)xamlServiceProvider27));
		VisualDiagnostics.RegisterSourceInfo(target7, new Uri("Views/GlucoseTargetRegistView.xaml", UriKind.RelativeOrAbsolute), 245, 151);
		bindingExtension13.Path = "GlucoseLowValue";
		BindingBase binding10 = ((IMarkupExtension<BindingBase>)bindingExtension13).ProvideValue((IServiceProvider)null);
		label12.SetBinding(VisualElement.IsVisibleProperty, binding10);
		label12.Effects.Add(fixedFontSizeLabelEffect12);
		VisualDiagnostics.RegisterSourceInfo(fixedFontSizeLabelEffect12, new Uri("Views/GlucoseTargetRegistView.xaml", UriKind.RelativeOrAbsolute), 247, 22);
		grid16.Children.Add(label12);
		VisualDiagnostics.RegisterSourceInfo(label12, new Uri("Views/GlucoseTargetRegistView.xaml", UriKind.RelativeOrAbsolute), 245, 14);
		pickerView4.SetValue(Grid.ColumnProperty, 2);
		pickerView4.SetValue(Xamarin.Forms.View.MarginProperty, new Thickness(0.0, 5.0, 0.0, 5.0));
		bindingExtension14.Mode = BindingMode.TwoWay;
		bindingExtension14.Path = "GlucoseLowValue";
		BindingBase binding11 = ((IMarkupExtension<BindingBase>)bindingExtension14).ProvideValue((IServiceProvider)null);
		pickerView4.SetBinding(Picker.SelectedItemProperty, binding11);
		bindingExtension15.Path = "ThresholdList";
		BindingBase binding12 = ((IMarkupExtension<BindingBase>)bindingExtension15).ProvideValue((IServiceProvider)null);
		pickerView4.SetBinding(Picker.ItemsSourceProperty, binding12);
		bindingExtension16.Path = "Name";
		BindingBase target8 = (pickerView4.ItemDisplayBinding = ((IMarkupExtension<BindingBase>)bindingExtension16).ProvideValue((IServiceProvider)null));
		VisualDiagnostics.RegisterSourceInfo(target8, new Uri("Views/GlucoseTargetRegistView.xaml", UriKind.RelativeOrAbsolute), 250, 159);
		pickerView4.SetValue(VisualElement.BackgroundColorProperty, Color.Transparent);
		pickerView4.Effects.Add(fixedFontSizeTextBoxEffect4);
		VisualDiagnostics.RegisterSourceInfo(fixedFontSizeTextBoxEffect4, new Uri("Views/GlucoseTargetRegistView.xaml", UriKind.RelativeOrAbsolute), 252, 22);
		grid16.Children.Add(pickerView4);
		VisualDiagnostics.RegisterSourceInfo(pickerView4, new Uri("Views/GlucoseTargetRegistView.xaml", UriKind.RelativeOrAbsolute), 250, 14);
		label13.SetValue(Grid.ColumnProperty, 3);
		label13.SetValue(Label.TextProperty, "以下");
		label13.SetValue(Xamarin.Forms.View.MarginProperty, new Thickness(0.0, 5.0, 10.0, 5.0));
		BindableProperty fontSizeProperty13 = Label.FontSizeProperty;
		FontSizeConverter fontSizeConverter13 = new FontSizeConverter();
		XamlServiceProvider xamlServiceProvider28 = new XamlServiceProvider();
		Type typeFromHandle55 = typeof(IProvideValueTarget);
		object[] array28 = new object[0 + 4];
		array28[0] = label13;
		array28[1] = grid16;
		array28[2] = grid17;
		array28[3] = glucoseTargetRegistView;
		object service28;
		xamlServiceProvider28.Add(typeFromHandle55, service28 = new SimpleValueTargetProvider(array28, Label.FontSizeProperty, nameScope));
		xamlServiceProvider28.Add(typeof(IReferenceProvider), service28);
		Type typeFromHandle56 = typeof(IXamlTypeResolver);
		XmlNamespaceResolver xmlNamespaceResolver28 = new XmlNamespaceResolver();
		xmlNamespaceResolver28.Add("", "http://xamarin.com/schemas/2014/forms");
		xmlNamespaceResolver28.Add("x", "http://schemas.microsoft.com/winfx/2009/xaml");
		xmlNamespaceResolver28.Add("calx", "clr-namespace:Caliburn.Micro.Xamarin.Forms;assembly=Caliburn.Micro.Platform.Xamarin.Forms");
		xmlNamespaceResolver28.Add("converter", "clr-namespace:NHL.Views.Converters");
		xmlNamespaceResolver28.Add("renderer", "clr-namespace:NHL.Views.Renderer");
		xmlNamespaceResolver28.Add("effect", "clr-namespace:NHL.Views.Effect");
		xamlServiceProvider28.Add(typeFromHandle56, new XamlTypeResolver(xmlNamespaceResolver28, typeof(GlucoseTargetRegistView).GetTypeInfo().Assembly));
		xamlServiceProvider28.Add(typeof(IXmlLineInfoProvider), new XmlLineInfoProvider(new XmlLineInfo(255, 65)));
		label13.SetValue(fontSizeProperty13, ((IExtendedTypeConverter)fontSizeConverter13).ConvertFromInvariantString("Large", (IServiceProvider)xamlServiceProvider28));
		label13.SetValue(Label.VerticalTextAlignmentProperty, new TextAlignmentConverter().ConvertFromInvariantString("Center"));
		label13.Effects.Add(fixedFontSizeLabelEffect13);
		VisualDiagnostics.RegisterSourceInfo(fixedFontSizeLabelEffect13, new Uri("Views/GlucoseTargetRegistView.xaml", UriKind.RelativeOrAbsolute), 257, 22);
		grid16.Children.Add(label13);
		VisualDiagnostics.RegisterSourceInfo(label13, new Uri("Views/GlucoseTargetRegistView.xaml", UriKind.RelativeOrAbsolute), 255, 14);
		grid17.Children.Add(grid16);
		VisualDiagnostics.RegisterSourceInfo(grid16, new Uri("Views/GlucoseTargetRegistView.xaml", UriKind.RelativeOrAbsolute), 220, 10);
		button.SetValue(Grid.RowProperty, 3);
		button.SetValue(Xamarin.Forms.View.MarginProperty, new Thickness(10.0, 10.0, 10.0, 5.0));
		button.SetValue(Button.TextProperty, "次へ");
		button.SetValue(Message.AttachProperty, "NextButton");
		button.SetValue(Xamarin.Forms.View.HorizontalOptionsProperty, LayoutOptions.FillAndExpand);
		button.SetValue(Button.TextColorProperty, Color.White);
		staticResourceExtension16.Key = "ButtonColor";
		XamlServiceProvider xamlServiceProvider29 = new XamlServiceProvider();
		Type typeFromHandle57 = typeof(IProvideValueTarget);
		object[] array29 = new object[0 + 3];
		array29[0] = button;
		array29[1] = grid17;
		array29[2] = glucoseTargetRegistView;
		object service29;
		xamlServiceProvider29.Add(typeFromHandle57, service29 = new SimpleValueTargetProvider(array29, VisualElement.BackgroundColorProperty, nameScope));
		xamlServiceProvider29.Add(typeof(IReferenceProvider), service29);
		Type typeFromHandle58 = typeof(IXamlTypeResolver);
		XmlNamespaceResolver xmlNamespaceResolver29 = new XmlNamespaceResolver();
		xmlNamespaceResolver29.Add("", "http://xamarin.com/schemas/2014/forms");
		xmlNamespaceResolver29.Add("x", "http://schemas.microsoft.com/winfx/2009/xaml");
		xmlNamespaceResolver29.Add("calx", "clr-namespace:Caliburn.Micro.Xamarin.Forms;assembly=Caliburn.Micro.Platform.Xamarin.Forms");
		xmlNamespaceResolver29.Add("converter", "clr-namespace:NHL.Views.Converters");
		xmlNamespaceResolver29.Add("renderer", "clr-namespace:NHL.Views.Renderer");
		xmlNamespaceResolver29.Add("effect", "clr-namespace:NHL.Views.Effect");
		xamlServiceProvider29.Add(typeFromHandle58, new XamlTypeResolver(xmlNamespaceResolver29, typeof(GlucoseTargetRegistView).GetTypeInfo().Assembly));
		xamlServiceProvider29.Add(typeof(IXmlLineInfoProvider), new XmlLineInfoProvider(new XmlLineInfo(263, 145)));
		object obj12 = ((IMarkupExtension)staticResourceExtension16).ProvideValue((IServiceProvider)xamlServiceProvider29);
		button.BackgroundColor = (Color)obj12;
		VisualDiagnostics.RegisterSourceInfo(obj12, new Uri("Views/GlucoseTargetRegistView.xaml", UriKind.RelativeOrAbsolute), 263, 145);
		button.Effects.Add(fixedFontSizeButtonEffect);
		VisualDiagnostics.RegisterSourceInfo(fixedFontSizeButtonEffect, new Uri("Views/GlucoseTargetRegistView.xaml", UriKind.RelativeOrAbsolute), 265, 18);
		grid17.Children.Add(button);
		VisualDiagnostics.RegisterSourceInfo(button, new Uri("Views/GlucoseTargetRegistView.xaml", UriKind.RelativeOrAbsolute), 263, 10);
		button2.SetValue(Grid.RowProperty, 4);
		button2.SetValue(Xamarin.Forms.View.MarginProperty, new Thickness(10.0, 10.0, 10.0, 5.0));
		button2.SetValue(Button.TextProperty, "今はしない");
		button2.SetValue(Message.AttachProperty, "LaterButton");
		button2.SetValue(Xamarin.Forms.View.HorizontalOptionsProperty, LayoutOptions.FillAndExpand);
		staticResourceExtension17.Key = "ButtonColor";
		XamlServiceProvider xamlServiceProvider30 = new XamlServiceProvider();
		Type typeFromHandle59 = typeof(IProvideValueTarget);
		object[] array30 = new object[0 + 3];
		array30[0] = button2;
		array30[1] = grid17;
		array30[2] = glucoseTargetRegistView;
		object service30;
		xamlServiceProvider30.Add(typeFromHandle59, service30 = new SimpleValueTargetProvider(array30, Button.TextColorProperty, nameScope));
		xamlServiceProvider30.Add(typeof(IReferenceProvider), service30);
		Type typeFromHandle60 = typeof(IXamlTypeResolver);
		XmlNamespaceResolver xmlNamespaceResolver30 = new XmlNamespaceResolver();
		xmlNamespaceResolver30.Add("", "http://xamarin.com/schemas/2014/forms");
		xmlNamespaceResolver30.Add("x", "http://schemas.microsoft.com/winfx/2009/xaml");
		xmlNamespaceResolver30.Add("calx", "clr-namespace:Caliburn.Micro.Xamarin.Forms;assembly=Caliburn.Micro.Platform.Xamarin.Forms");
		xmlNamespaceResolver30.Add("converter", "clr-namespace:NHL.Views.Converters");
		xmlNamespaceResolver30.Add("renderer", "clr-namespace:NHL.Views.Renderer");
		xmlNamespaceResolver30.Add("effect", "clr-namespace:NHL.Views.Effect");
		xamlServiceProvider30.Add(typeFromHandle60, new XamlTypeResolver(xmlNamespaceResolver30, typeof(GlucoseTargetRegistView).GetTypeInfo().Assembly));
		xamlServiceProvider30.Add(typeof(IXmlLineInfoProvider), new XmlLineInfoProvider(new XmlLineInfo(268, 131)));
		object obj13 = ((IMarkupExtension)staticResourceExtension17).ProvideValue((IServiceProvider)xamlServiceProvider30);
		button2.TextColor = (Color)obj13;
		VisualDiagnostics.RegisterSourceInfo(obj13, new Uri("Views/GlucoseTargetRegistView.xaml", UriKind.RelativeOrAbsolute), 268, 131);
		button2.SetValue(VisualElement.BackgroundColorProperty, Color.Transparent);
		button2.Effects.Add(fixedFontSizeButtonEffect2);
		VisualDiagnostics.RegisterSourceInfo(fixedFontSizeButtonEffect2, new Uri("Views/GlucoseTargetRegistView.xaml", UriKind.RelativeOrAbsolute), 270, 18);
		grid17.Children.Add(button2);
		VisualDiagnostics.RegisterSourceInfo(button2, new Uri("Views/GlucoseTargetRegistView.xaml", UriKind.RelativeOrAbsolute), 268, 10);
		glucoseTargetRegistView.SetValue(ContentPage.ContentProperty, grid17);
		VisualDiagnostics.RegisterSourceInfo(grid17, new Uri("Views/GlucoseTargetRegistView.xaml", UriKind.RelativeOrAbsolute), 48, 6);
		VisualDiagnostics.RegisterSourceInfo(glucoseTargetRegistView, new Uri("Views/GlucoseTargetRegistView.xaml", UriKind.RelativeOrAbsolute), 2, 2);
	}

	private void __InitComponentRuntime()
	{
		this.LoadFromXaml(typeof(GlucoseTargetRegistView));
	}
}
