using System;
using System.CodeDom.Compiler;
using System.Reflection;
using System.Runtime.CompilerServices;
using Caliburn.Micro.Xamarin.Forms;
using NHL.Views.Effect;
using Xamarin.Forms;
using Xamarin.Forms.Internals;
using Xamarin.Forms.Xaml;
using Xamarin.Forms.Xaml.Diagnostics;
using Xamarin.Forms.Xaml.Internals;

namespace NHL.Views;

[XamlCompilation(XamlCompilationOptions.Compile)]
[XamlFilePath("Views/LogView.xaml")]
public class LogView : ContentPage
{
	[CompilerGenerated]
	private sealed class _003CInitializeComponent_003E_anonXamlCDataTemplate_5
	{
		internal object[] parentValues;

		internal LogView root;

		internal object LoadDataTemplate()
		{
			ColumnDefinition columnDefinition = new ColumnDefinition();
			ColumnDefinition columnDefinition2 = new ColumnDefinition();
			ColumnDefinition columnDefinition3 = new ColumnDefinition();
			ColumnDefinition columnDefinition4 = new ColumnDefinition();
			RowDefinition rowDefinition = new RowDefinition();
			RowDefinition rowDefinition2 = new RowDefinition();
			RowDefinition rowDefinition3 = new RowDefinition();
			BoxView boxView = new BoxView();
			BoxView boxView2 = new BoxView();
			BindingExtension bindingExtension = new BindingExtension();
			FixedFontSizeLabelEffect fixedFontSizeLabelEffect = new FixedFontSizeLabelEffect();
			Label label = new Label();
			BindingExtension bindingExtension2 = new BindingExtension();
			FixedFontSizeLabelEffect fixedFontSizeLabelEffect2 = new FixedFontSizeLabelEffect();
			Label label2 = new Label();
			FixedFontSizeButtonEffect fixedFontSizeButtonEffect = new FixedFontSizeButtonEffect();
			Button button = new Button();
			FixedFontSizeButtonEffect fixedFontSizeButtonEffect2 = new FixedFontSizeButtonEffect();
			Button button2 = new Button();
			Grid grid = new Grid();
			ViewCell viewCell = new ViewCell();
			NameScope nameScope = new NameScope();
			NameScope.SetNameScope(viewCell, nameScope);
			grid.SetValue(VisualElement.BackgroundColorProperty, Color.White);
			columnDefinition.SetValue(ColumnDefinition.WidthProperty, new GridLengthTypeConverter().ConvertFromInvariantString("*"));
			((DefinitionCollection<ColumnDefinition>)grid.GetValue(Grid.ColumnDefinitionsProperty)).Add(columnDefinition);
			columnDefinition2.SetValue(ColumnDefinition.WidthProperty, new GridLengthTypeConverter().ConvertFromInvariantString("*"));
			((DefinitionCollection<ColumnDefinition>)grid.GetValue(Grid.ColumnDefinitionsProperty)).Add(columnDefinition2);
			columnDefinition3.SetValue(ColumnDefinition.WidthProperty, new GridLengthTypeConverter().ConvertFromInvariantString("80"));
			((DefinitionCollection<ColumnDefinition>)grid.GetValue(Grid.ColumnDefinitionsProperty)).Add(columnDefinition3);
			columnDefinition4.SetValue(ColumnDefinition.WidthProperty, new GridLengthTypeConverter().ConvertFromInvariantString("80"));
			((DefinitionCollection<ColumnDefinition>)grid.GetValue(Grid.ColumnDefinitionsProperty)).Add(columnDefinition4);
			rowDefinition.SetValue(RowDefinition.HeightProperty, new GridLengthTypeConverter().ConvertFromInvariantString("1"));
			((DefinitionCollection<RowDefinition>)grid.GetValue(Grid.RowDefinitionsProperty)).Add(rowDefinition);
			rowDefinition2.SetValue(RowDefinition.HeightProperty, new GridLengthTypeConverter().ConvertFromInvariantString("*"));
			((DefinitionCollection<RowDefinition>)grid.GetValue(Grid.RowDefinitionsProperty)).Add(rowDefinition2);
			rowDefinition3.SetValue(RowDefinition.HeightProperty, new GridLengthTypeConverter().ConvertFromInvariantString("1"));
			((DefinitionCollection<RowDefinition>)grid.GetValue(Grid.RowDefinitionsProperty)).Add(rowDefinition3);
			boxView.SetValue(Grid.RowProperty, 0);
			boxView.SetValue(Grid.ColumnProperty, 0);
			boxView.SetValue(Grid.ColumnSpanProperty, 4);
			boxView.SetValue(VisualElement.BackgroundColorProperty, Color.Black);
			boxView.SetValue(VisualElement.HeightRequestProperty, 1.0);
			boxView.SetValue(Xamarin.Forms.View.VerticalOptionsProperty, LayoutOptions.End);
			boxView.SetValue(Xamarin.Forms.View.HorizontalOptionsProperty, LayoutOptions.FillAndExpand);
			grid.Children.Add(boxView);
			VisualDiagnostics.RegisterSourceInfo(boxView, new Uri("Views/LogView.xaml", UriKind.RelativeOrAbsolute), 50, 34);
			boxView2.SetValue(Grid.RowProperty, 2);
			boxView2.SetValue(Grid.ColumnProperty, 0);
			boxView2.SetValue(Grid.ColumnSpanProperty, 4);
			boxView2.SetValue(VisualElement.BackgroundColorProperty, Color.Black);
			boxView2.SetValue(VisualElement.HeightRequestProperty, 1.0);
			boxView2.SetValue(Xamarin.Forms.View.VerticalOptionsProperty, LayoutOptions.End);
			boxView2.SetValue(Xamarin.Forms.View.HorizontalOptionsProperty, LayoutOptions.FillAndExpand);
			grid.Children.Add(boxView2);
			VisualDiagnostics.RegisterSourceInfo(boxView2, new Uri("Views/LogView.xaml", UriKind.RelativeOrAbsolute), 51, 34);
			label.SetValue(Grid.RowProperty, 1);
			label.SetValue(Label.VerticalTextAlignmentProperty, new TextAlignmentConverter().ConvertFromInvariantString("Center"));
			label.SetValue(Label.HorizontalTextAlignmentProperty, new TextAlignmentConverter().ConvertFromInvariantString("Start"));
			bindingExtension.Mode = BindingMode.OneWay;
			bindingExtension.Path = "Name";
			BindingBase binding = ((IMarkupExtension<BindingBase>)bindingExtension).ProvideValue((IServiceProvider)null);
			label.SetBinding(Label.TextProperty, binding);
			BindableProperty fontSizeProperty = Label.FontSizeProperty;
			FontSizeConverter fontSizeConverter = new FontSizeConverter();
			XamlServiceProvider xamlServiceProvider = new XamlServiceProvider();
			Type typeFromHandle = typeof(IProvideValueTarget);
			int length;
			object[] array = new object[(length = parentValues.Length) + 3];
			Array.Copy(parentValues, 0, array, 3, length);
			array[0] = label;
			array[1] = grid;
			array[2] = viewCell;
			object service;
			xamlServiceProvider.Add(typeFromHandle, service = new SimpleValueTargetProvider(array, Label.FontSizeProperty, nameScope));
			xamlServiceProvider.Add(typeof(IReferenceProvider), service);
			Type typeFromHandle2 = typeof(IXamlTypeResolver);
			XmlNamespaceResolver xmlNamespaceResolver = new XmlNamespaceResolver();
			xmlNamespaceResolver.Add("", "http://xamarin.com/schemas/2014/forms");
			xmlNamespaceResolver.Add("x", "http://schemas.microsoft.com/winfx/2009/xaml");
			xmlNamespaceResolver.Add("calx", "clr-namespace:Caliburn.Micro.Xamarin.Forms;assembly=Caliburn.Micro.Platform.Xamarin.Forms");
			xmlNamespaceResolver.Add("effect", "clr-namespace:NHL.Views.Effect");
			xamlServiceProvider.Add(typeFromHandle2, new XamlTypeResolver(xmlNamespaceResolver, typeof(_003CInitializeComponent_003E_anonXamlCDataTemplate_5).GetTypeInfo().Assembly));
			xamlServiceProvider.Add(typeof(IXmlLineInfoProvider), new XmlLineInfoProvider(new XmlLineInfo(53, 151)));
			label.SetValue(fontSizeProperty, ((IExtendedTypeConverter)fontSizeConverter).ConvertFromInvariantString("Small", (IServiceProvider)xamlServiceProvider));
			label.Effects.Add(fixedFontSizeLabelEffect);
			VisualDiagnostics.RegisterSourceInfo(fixedFontSizeLabelEffect, new Uri("Views/LogView.xaml", UriKind.RelativeOrAbsolute), 55, 42);
			grid.Children.Add(label);
			VisualDiagnostics.RegisterSourceInfo(label, new Uri("Views/LogView.xaml", UriKind.RelativeOrAbsolute), 53, 34);
			label2.SetValue(Grid.RowProperty, 1);
			label2.SetValue(Grid.ColumnProperty, 1);
			label2.SetValue(Label.VerticalTextAlignmentProperty, new TextAlignmentConverter().ConvertFromInvariantString("Center"));
			label2.SetValue(Label.HorizontalTextAlignmentProperty, new TextAlignmentConverter().ConvertFromInvariantString("Start"));
			bindingExtension2.Mode = BindingMode.OneWay;
			bindingExtension2.Path = "SizeString";
			BindingBase binding2 = ((IMarkupExtension<BindingBase>)bindingExtension2).ProvideValue((IServiceProvider)null);
			label2.SetBinding(Label.TextProperty, binding2);
			BindableProperty fontSizeProperty2 = Label.FontSizeProperty;
			FontSizeConverter fontSizeConverter2 = new FontSizeConverter();
			XamlServiceProvider xamlServiceProvider2 = new XamlServiceProvider();
			Type typeFromHandle3 = typeof(IProvideValueTarget);
			int length2;
			object[] array2 = new object[(length2 = parentValues.Length) + 3];
			Array.Copy(parentValues, 0, array2, 3, length2);
			array2[0] = label2;
			array2[1] = grid;
			array2[2] = viewCell;
			object service2;
			xamlServiceProvider2.Add(typeFromHandle3, service2 = new SimpleValueTargetProvider(array2, Label.FontSizeProperty, nameScope));
			xamlServiceProvider2.Add(typeof(IReferenceProvider), service2);
			Type typeFromHandle4 = typeof(IXamlTypeResolver);
			XmlNamespaceResolver xmlNamespaceResolver2 = new XmlNamespaceResolver();
			xmlNamespaceResolver2.Add("", "http://xamarin.com/schemas/2014/forms");
			xmlNamespaceResolver2.Add("x", "http://schemas.microsoft.com/winfx/2009/xaml");
			xmlNamespaceResolver2.Add("calx", "clr-namespace:Caliburn.Micro.Xamarin.Forms;assembly=Caliburn.Micro.Platform.Xamarin.Forms");
			xmlNamespaceResolver2.Add("effect", "clr-namespace:NHL.Views.Effect");
			xamlServiceProvider2.Add(typeFromHandle4, new XamlTypeResolver(xmlNamespaceResolver2, typeof(_003CInitializeComponent_003E_anonXamlCDataTemplate_5).GetTypeInfo().Assembly));
			xamlServiceProvider2.Add(typeof(IXmlLineInfoProvider), new XmlLineInfoProvider(new XmlLineInfo(58, 173)));
			label2.SetValue(fontSizeProperty2, ((IExtendedTypeConverter)fontSizeConverter2).ConvertFromInvariantString("Small", (IServiceProvider)xamlServiceProvider2));
			label2.Effects.Add(fixedFontSizeLabelEffect2);
			VisualDiagnostics.RegisterSourceInfo(fixedFontSizeLabelEffect2, new Uri("Views/LogView.xaml", UriKind.RelativeOrAbsolute), 60, 42);
			grid.Children.Add(label2);
			VisualDiagnostics.RegisterSourceInfo(label2, new Uri("Views/LogView.xaml", UriKind.RelativeOrAbsolute), 58, 34);
			button.SetValue(Grid.RowProperty, 1);
			button.SetValue(Grid.ColumnProperty, 2);
			button.SetValue(Button.TextProperty, "表示");
			button.SetValue(VisualElement.BackgroundColorProperty, Color.Silver);
			button.SetValue(Button.TextColorProperty, Color.Black);
			BindableProperty fontSizeProperty3 = Button.FontSizeProperty;
			FontSizeConverter fontSizeConverter3 = new FontSizeConverter();
			XamlServiceProvider xamlServiceProvider3 = new XamlServiceProvider();
			Type typeFromHandle5 = typeof(IProvideValueTarget);
			int length3;
			object[] array3 = new object[(length3 = parentValues.Length) + 3];
			Array.Copy(parentValues, 0, array3, 3, length3);
			array3[0] = button;
			array3[1] = grid;
			array3[2] = viewCell;
			object service3;
			xamlServiceProvider3.Add(typeFromHandle5, service3 = new SimpleValueTargetProvider(array3, Button.FontSizeProperty, nameScope));
			xamlServiceProvider3.Add(typeof(IReferenceProvider), service3);
			Type typeFromHandle6 = typeof(IXamlTypeResolver);
			XmlNamespaceResolver xmlNamespaceResolver3 = new XmlNamespaceResolver();
			xmlNamespaceResolver3.Add("", "http://xamarin.com/schemas/2014/forms");
			xmlNamespaceResolver3.Add("x", "http://schemas.microsoft.com/winfx/2009/xaml");
			xmlNamespaceResolver3.Add("calx", "clr-namespace:Caliburn.Micro.Xamarin.Forms;assembly=Caliburn.Micro.Platform.Xamarin.Forms");
			xmlNamespaceResolver3.Add("effect", "clr-namespace:NHL.Views.Effect");
			xamlServiceProvider3.Add(typeFromHandle6, new XamlTypeResolver(xmlNamespaceResolver3, typeof(_003CInitializeComponent_003E_anonXamlCDataTemplate_5).GetTypeInfo().Assembly));
			xamlServiceProvider3.Add(typeof(IXmlLineInfoProvider), new XmlLineInfoProvider(new XmlLineInfo(63, 123)));
			button.SetValue(fontSizeProperty3, ((IExtendedTypeConverter)fontSizeConverter3).ConvertFromInvariantString("10", (IServiceProvider)xamlServiceProvider3));
			button.SetValue(Message.AttachProperty, "ViewLog($dataContext)");
			button.Effects.Add(fixedFontSizeButtonEffect);
			VisualDiagnostics.RegisterSourceInfo(fixedFontSizeButtonEffect, new Uri("Views/LogView.xaml", UriKind.RelativeOrAbsolute), 65, 42);
			grid.Children.Add(button);
			VisualDiagnostics.RegisterSourceInfo(button, new Uri("Views/LogView.xaml", UriKind.RelativeOrAbsolute), 63, 34);
			button2.SetValue(Grid.RowProperty, 1);
			button2.SetValue(Grid.ColumnProperty, 3);
			button2.SetValue(Button.TextProperty, "送信");
			button2.SetValue(VisualElement.BackgroundColorProperty, Color.Silver);
			button2.SetValue(Button.TextColorProperty, Color.Black);
			BindableProperty fontSizeProperty4 = Button.FontSizeProperty;
			FontSizeConverter fontSizeConverter4 = new FontSizeConverter();
			XamlServiceProvider xamlServiceProvider4 = new XamlServiceProvider();
			Type typeFromHandle7 = typeof(IProvideValueTarget);
			int length4;
			object[] array4 = new object[(length4 = parentValues.Length) + 3];
			Array.Copy(parentValues, 0, array4, 3, length4);
			array4[0] = button2;
			array4[1] = grid;
			array4[2] = viewCell;
			object service4;
			xamlServiceProvider4.Add(typeFromHandle7, service4 = new SimpleValueTargetProvider(array4, Button.FontSizeProperty, nameScope));
			xamlServiceProvider4.Add(typeof(IReferenceProvider), service4);
			Type typeFromHandle8 = typeof(IXamlTypeResolver);
			XmlNamespaceResolver xmlNamespaceResolver4 = new XmlNamespaceResolver();
			xmlNamespaceResolver4.Add("", "http://xamarin.com/schemas/2014/forms");
			xmlNamespaceResolver4.Add("x", "http://schemas.microsoft.com/winfx/2009/xaml");
			xmlNamespaceResolver4.Add("calx", "clr-namespace:Caliburn.Micro.Xamarin.Forms;assembly=Caliburn.Micro.Platform.Xamarin.Forms");
			xmlNamespaceResolver4.Add("effect", "clr-namespace:NHL.Views.Effect");
			xamlServiceProvider4.Add(typeFromHandle8, new XamlTypeResolver(xmlNamespaceResolver4, typeof(_003CInitializeComponent_003E_anonXamlCDataTemplate_5).GetTypeInfo().Assembly));
			xamlServiceProvider4.Add(typeof(IXmlLineInfoProvider), new XmlLineInfoProvider(new XmlLineInfo(68, 123)));
			button2.SetValue(fontSizeProperty4, ((IExtendedTypeConverter)fontSizeConverter4).ConvertFromInvariantString("10", (IServiceProvider)xamlServiceProvider4));
			button2.SetValue(Message.AttachProperty, "SendLog($dataContext)");
			button2.Effects.Add(fixedFontSizeButtonEffect2);
			VisualDiagnostics.RegisterSourceInfo(fixedFontSizeButtonEffect2, new Uri("Views/LogView.xaml", UriKind.RelativeOrAbsolute), 70, 42);
			grid.Children.Add(button2);
			VisualDiagnostics.RegisterSourceInfo(button2, new Uri("Views/LogView.xaml", UriKind.RelativeOrAbsolute), 68, 34);
			viewCell.View = grid;
			VisualDiagnostics.RegisterSourceInfo(grid, new Uri("Views/LogView.xaml", UriKind.RelativeOrAbsolute), 37, 30);
			return viewCell;
		}
	}

	[CompilerGenerated]
	private sealed class _003CInitializeComponent_003E_anonXamlCDataTemplate_6
	{
		internal object[] parentValues;

		internal LogView root;

		internal object LoadDataTemplate()
		{
			BindingExtension bindingExtension = new BindingExtension();
			FixedFontSizeLabelEffect fixedFontSizeLabelEffect = new FixedFontSizeLabelEffect();
			Label label = new Label();
			Grid grid = new Grid();
			ViewCell viewCell = new ViewCell();
			NameScope nameScope = new NameScope();
			NameScope.SetNameScope(viewCell, nameScope);
			grid.SetValue(VisualElement.BackgroundColorProperty, Color.White);
			label.SetValue(Label.VerticalTextAlignmentProperty, new TextAlignmentConverter().ConvertFromInvariantString("Center"));
			label.SetValue(Label.HorizontalTextAlignmentProperty, new TextAlignmentConverter().ConvertFromInvariantString("Start"));
			bindingExtension.Mode = BindingMode.OneWay;
			bindingExtension.Path = ".";
			BindingBase binding = ((IMarkupExtension<BindingBase>)bindingExtension).ProvideValue((IServiceProvider)null);
			label.SetBinding(Label.TextProperty, binding);
			BindableProperty fontSizeProperty = Label.FontSizeProperty;
			FontSizeConverter fontSizeConverter = new FontSizeConverter();
			XamlServiceProvider xamlServiceProvider = new XamlServiceProvider();
			Type typeFromHandle = typeof(IProvideValueTarget);
			int length;
			object[] array = new object[(length = parentValues.Length) + 3];
			Array.Copy(parentValues, 0, array, 3, length);
			array[0] = label;
			array[1] = grid;
			array[2] = viewCell;
			object service;
			xamlServiceProvider.Add(typeFromHandle, service = new SimpleValueTargetProvider(array, Label.FontSizeProperty, nameScope));
			xamlServiceProvider.Add(typeof(IReferenceProvider), service);
			Type typeFromHandle2 = typeof(IXamlTypeResolver);
			XmlNamespaceResolver xmlNamespaceResolver = new XmlNamespaceResolver();
			xmlNamespaceResolver.Add("", "http://xamarin.com/schemas/2014/forms");
			xmlNamespaceResolver.Add("x", "http://schemas.microsoft.com/winfx/2009/xaml");
			xmlNamespaceResolver.Add("calx", "clr-namespace:Caliburn.Micro.Xamarin.Forms;assembly=Caliburn.Micro.Platform.Xamarin.Forms");
			xmlNamespaceResolver.Add("effect", "clr-namespace:NHL.Views.Effect");
			xamlServiceProvider.Add(typeFromHandle2, new XamlTypeResolver(xmlNamespaceResolver, typeof(_003CInitializeComponent_003E_anonXamlCDataTemplate_6).GetTypeInfo().Assembly));
			xamlServiceProvider.Add(typeof(IXmlLineInfoProvider), new XmlLineInfoProvider(new XmlLineInfo(92, 135)));
			label.SetValue(fontSizeProperty, ((IExtendedTypeConverter)fontSizeConverter).ConvertFromInvariantString("Small", (IServiceProvider)xamlServiceProvider));
			label.Effects.Add(fixedFontSizeLabelEffect);
			VisualDiagnostics.RegisterSourceInfo(fixedFontSizeLabelEffect, new Uri("Views/LogView.xaml", UriKind.RelativeOrAbsolute), 94, 42);
			grid.Children.Add(label);
			VisualDiagnostics.RegisterSourceInfo(label, new Uri("Views/LogView.xaml", UriKind.RelativeOrAbsolute), 92, 34);
			viewCell.View = grid;
			VisualDiagnostics.RegisterSourceInfo(grid, new Uri("Views/LogView.xaml", UriKind.RelativeOrAbsolute), 91, 30);
			return viewCell;
		}
	}

	public LogView()
	{
		InitializeComponent();
	}

	[GeneratedCode("Xamarin.Forms.Build.Tasks.XamlG", "2.0.0.0")]
	private void InitializeComponent()
	{
		if (ResourceLoader.CanProvideContentFor(new ResourceLoader.ResourceLoadingQuery
		{
			AssemblyName = typeof(LogView).GetTypeInfo().Assembly.GetName(),
			ResourcePath = "Views/LogView.xaml",
			Instance = this
		}))
		{
			__InitComponentRuntime();
			return;
		}
		if (XamlLoader.XamlFileProvider != null && XamlLoader.XamlFileProvider(GetType()) != null)
		{
			__InitComponentRuntime();
			return;
		}
		Color color = Color.FromHex("#5B9BD5");
		ResourceDictionary resourceDictionary = new ResourceDictionary();
		RowDefinition rowDefinition = new RowDefinition();
		RowDefinition rowDefinition2 = new RowDefinition();
		BindingExtension bindingExtension = new BindingExtension();
		BindingExtension bindingExtension2 = new BindingExtension();
		FixedFontSizeLabelEffect fixedFontSizeLabelEffect = new FixedFontSizeLabelEffect();
		Label label = new Label();
		Grid grid = new Grid();
		DataTemplate dataTemplate = new DataTemplate();
		ListView listView = new ListView();
		BindingExtension bindingExtension3 = new BindingExtension();
		FixedFontSizeLabelEffect fixedFontSizeLabelEffect2 = new FixedFontSizeLabelEffect();
		Label label2 = new Label();
		Grid grid2 = new Grid();
		DataTemplate dataTemplate2 = new DataTemplate();
		ListView listView2 = new ListView();
		Grid grid3 = new Grid();
		LogView logView;
		NameScope nameScope = (NameScope)(NameScope.GetNameScope(logView = this) ?? new NameScope());
		NameScope.SetNameScope(logView, nameScope);
		logView.Resources = resourceDictionary;
		VisualDiagnostics.RegisterSourceInfo(resourceDictionary, new Uri("Views/LogView.xaml", UriKind.RelativeOrAbsolute), 9, 10);
		resourceDictionary.Add("ButtonColor", color);
		logView.SetValue(Page.TitleProperty, "ログ");
		logView.Resources = resourceDictionary;
		VisualDiagnostics.RegisterSourceInfo(resourceDictionary, new Uri("Views/LogView.xaml", UriKind.RelativeOrAbsolute), 9, 10);
		rowDefinition.SetValue(RowDefinition.HeightProperty, new GridLengthTypeConverter().ConvertFromInvariantString("Auto"));
		((DefinitionCollection<RowDefinition>)grid3.GetValue(Grid.RowDefinitionsProperty)).Add(rowDefinition);
		rowDefinition2.SetValue(RowDefinition.HeightProperty, new GridLengthTypeConverter().ConvertFromInvariantString("*"));
		((DefinitionCollection<RowDefinition>)grid3.GetValue(Grid.RowDefinitionsProperty)).Add(rowDefinition2);
		bindingExtension.Path = "LogFileList";
		BindingBase binding = ((IMarkupExtension<BindingBase>)bindingExtension).ProvideValue((IServiceProvider)null);
		listView.SetBinding(ItemsView<Cell>.ItemsSourceProperty, binding);
		bindingExtension2.Path = "SelectedItem";
		BindingBase binding2 = ((IMarkupExtension<BindingBase>)bindingExtension2).ProvideValue((IServiceProvider)null);
		listView.SetBinding(ListView.SelectedItemProperty, binding2);
		listView.SetValue(ListView.SeparatorVisibilityProperty, SeparatorVisibility.None);
		listView.SetValue(ListView.RowHeightProperty, 40);
		listView.SetValue(VisualElement.HeightRequestProperty, 80.0);
		label.SetValue(Xamarin.Forms.View.HorizontalOptionsProperty, LayoutOptions.FillAndExpand);
		label.SetValue(Xamarin.Forms.View.VerticalOptionsProperty, LayoutOptions.FillAndExpand);
		label.SetValue(Label.VerticalTextAlignmentProperty, new TextAlignmentConverter().ConvertFromInvariantString("Center"));
		label.SetValue(Label.HorizontalTextAlignmentProperty, new TextAlignmentConverter().ConvertFromInvariantString("Center"));
		label.SetValue(Label.TextProperty, "ログ一覧");
		BindableProperty fontSizeProperty = Label.FontSizeProperty;
		FontSizeConverter fontSizeConverter = new FontSizeConverter();
		XamlServiceProvider xamlServiceProvider = new XamlServiceProvider();
		Type typeFromHandle = typeof(IProvideValueTarget);
		object[] array = new object[0 + 5];
		array[0] = label;
		array[1] = grid;
		array[2] = listView;
		array[3] = grid3;
		array[4] = logView;
		object service;
		xamlServiceProvider.Add(typeFromHandle, service = new SimpleValueTargetProvider(array, Label.FontSizeProperty, nameScope));
		xamlServiceProvider.Add(typeof(IReferenceProvider), service);
		Type typeFromHandle2 = typeof(IXamlTypeResolver);
		XmlNamespaceResolver xmlNamespaceResolver = new XmlNamespaceResolver();
		xmlNamespaceResolver.Add("", "http://xamarin.com/schemas/2014/forms");
		xmlNamespaceResolver.Add("x", "http://schemas.microsoft.com/winfx/2009/xaml");
		xmlNamespaceResolver.Add("calx", "clr-namespace:Caliburn.Micro.Xamarin.Forms;assembly=Caliburn.Micro.Platform.Xamarin.Forms");
		xmlNamespaceResolver.Add("effect", "clr-namespace:NHL.Views.Effect");
		xamlServiceProvider.Add(typeFromHandle2, new XamlTypeResolver(xmlNamespaceResolver, typeof(LogView).GetTypeInfo().Assembly));
		xamlServiceProvider.Add(typeof(IXmlLineInfoProvider), new XmlLineInfoProvider(new XmlLineInfo(27, 174)));
		label.SetValue(fontSizeProperty, ((IExtendedTypeConverter)fontSizeConverter).ConvertFromInvariantString("Small", (IServiceProvider)xamlServiceProvider));
		label.SetValue(VisualElement.BackgroundColorProperty, Color.Navy);
		label.SetValue(Label.TextColorProperty, Color.White);
		label.Effects.Add(fixedFontSizeLabelEffect);
		VisualDiagnostics.RegisterSourceInfo(fixedFontSizeLabelEffect, new Uri("Views/LogView.xaml", UriKind.RelativeOrAbsolute), 29, 34);
		grid.Children.Add(label);
		VisualDiagnostics.RegisterSourceInfo(label, new Uri("Views/LogView.xaml", UriKind.RelativeOrAbsolute), 27, 26);
		listView.SetValue(ListView.HeaderProperty, grid);
		VisualDiagnostics.RegisterSourceInfo(grid, new Uri("Views/LogView.xaml", UriKind.RelativeOrAbsolute), 26, 22);
		object[] array2 = new object[0 + 4];
		array2[0] = dataTemplate;
		array2[1] = listView;
		array2[2] = grid3;
		array2[3] = logView;
		object[] parentValues = array2;
		LogView root = logView;
		((IDataTemplate)dataTemplate).LoadTemplate = delegate
		{
			ColumnDefinition columnDefinition = new ColumnDefinition();
			ColumnDefinition columnDefinition2 = new ColumnDefinition();
			ColumnDefinition columnDefinition3 = new ColumnDefinition();
			ColumnDefinition columnDefinition4 = new ColumnDefinition();
			RowDefinition rowDefinition3 = new RowDefinition();
			RowDefinition rowDefinition4 = new RowDefinition();
			RowDefinition rowDefinition5 = new RowDefinition();
			BoxView boxView = new BoxView();
			BoxView boxView2 = new BoxView();
			BindingExtension bindingExtension4 = new BindingExtension();
			FixedFontSizeLabelEffect fixedFontSizeLabelEffect3 = new FixedFontSizeLabelEffect();
			Label label3 = new Label();
			BindingExtension bindingExtension5 = new BindingExtension();
			FixedFontSizeLabelEffect fixedFontSizeLabelEffect4 = new FixedFontSizeLabelEffect();
			Label label4 = new Label();
			FixedFontSizeButtonEffect fixedFontSizeButtonEffect = new FixedFontSizeButtonEffect();
			Button button = new Button();
			FixedFontSizeButtonEffect fixedFontSizeButtonEffect2 = new FixedFontSizeButtonEffect();
			Button button2 = new Button();
			Grid grid4 = new Grid();
			ViewCell viewCell = new ViewCell();
			NameScope nameScope2 = new NameScope();
			NameScope.SetNameScope(viewCell, nameScope2);
			grid4.SetValue(VisualElement.BackgroundColorProperty, Color.White);
			columnDefinition.SetValue(ColumnDefinition.WidthProperty, new GridLengthTypeConverter().ConvertFromInvariantString("*"));
			((DefinitionCollection<ColumnDefinition>)grid4.GetValue(Grid.ColumnDefinitionsProperty)).Add(columnDefinition);
			columnDefinition2.SetValue(ColumnDefinition.WidthProperty, new GridLengthTypeConverter().ConvertFromInvariantString("*"));
			((DefinitionCollection<ColumnDefinition>)grid4.GetValue(Grid.ColumnDefinitionsProperty)).Add(columnDefinition2);
			columnDefinition3.SetValue(ColumnDefinition.WidthProperty, new GridLengthTypeConverter().ConvertFromInvariantString("80"));
			((DefinitionCollection<ColumnDefinition>)grid4.GetValue(Grid.ColumnDefinitionsProperty)).Add(columnDefinition3);
			columnDefinition4.SetValue(ColumnDefinition.WidthProperty, new GridLengthTypeConverter().ConvertFromInvariantString("80"));
			((DefinitionCollection<ColumnDefinition>)grid4.GetValue(Grid.ColumnDefinitionsProperty)).Add(columnDefinition4);
			rowDefinition3.SetValue(RowDefinition.HeightProperty, new GridLengthTypeConverter().ConvertFromInvariantString("1"));
			((DefinitionCollection<RowDefinition>)grid4.GetValue(Grid.RowDefinitionsProperty)).Add(rowDefinition3);
			rowDefinition4.SetValue(RowDefinition.HeightProperty, new GridLengthTypeConverter().ConvertFromInvariantString("*"));
			((DefinitionCollection<RowDefinition>)grid4.GetValue(Grid.RowDefinitionsProperty)).Add(rowDefinition4);
			rowDefinition5.SetValue(RowDefinition.HeightProperty, new GridLengthTypeConverter().ConvertFromInvariantString("1"));
			((DefinitionCollection<RowDefinition>)grid4.GetValue(Grid.RowDefinitionsProperty)).Add(rowDefinition5);
			boxView.SetValue(Grid.RowProperty, 0);
			boxView.SetValue(Grid.ColumnProperty, 0);
			boxView.SetValue(Grid.ColumnSpanProperty, 4);
			boxView.SetValue(VisualElement.BackgroundColorProperty, Color.Black);
			boxView.SetValue(VisualElement.HeightRequestProperty, 1.0);
			boxView.SetValue(Xamarin.Forms.View.VerticalOptionsProperty, LayoutOptions.End);
			boxView.SetValue(Xamarin.Forms.View.HorizontalOptionsProperty, LayoutOptions.FillAndExpand);
			grid4.Children.Add(boxView);
			VisualDiagnostics.RegisterSourceInfo(boxView, new Uri("Views/LogView.xaml", UriKind.RelativeOrAbsolute), 50, 34);
			boxView2.SetValue(Grid.RowProperty, 2);
			boxView2.SetValue(Grid.ColumnProperty, 0);
			boxView2.SetValue(Grid.ColumnSpanProperty, 4);
			boxView2.SetValue(VisualElement.BackgroundColorProperty, Color.Black);
			boxView2.SetValue(VisualElement.HeightRequestProperty, 1.0);
			boxView2.SetValue(Xamarin.Forms.View.VerticalOptionsProperty, LayoutOptions.End);
			boxView2.SetValue(Xamarin.Forms.View.HorizontalOptionsProperty, LayoutOptions.FillAndExpand);
			grid4.Children.Add(boxView2);
			VisualDiagnostics.RegisterSourceInfo(boxView2, new Uri("Views/LogView.xaml", UriKind.RelativeOrAbsolute), 51, 34);
			label3.SetValue(Grid.RowProperty, 1);
			label3.SetValue(Label.VerticalTextAlignmentProperty, new TextAlignmentConverter().ConvertFromInvariantString("Center"));
			label3.SetValue(Label.HorizontalTextAlignmentProperty, new TextAlignmentConverter().ConvertFromInvariantString("Start"));
			bindingExtension4.Mode = BindingMode.OneWay;
			bindingExtension4.Path = "Name";
			BindingBase binding4 = ((IMarkupExtension<BindingBase>)bindingExtension4).ProvideValue((IServiceProvider)null);
			label3.SetBinding(Label.TextProperty, binding4);
			BindableProperty fontSizeProperty3 = Label.FontSizeProperty;
			FontSizeConverter fontSizeConverter3 = new FontSizeConverter();
			XamlServiceProvider xamlServiceProvider3 = new XamlServiceProvider();
			Type typeFromHandle5 = typeof(IProvideValueTarget);
			int length;
			object[] array5 = new object[(length = parentValues.Length) + 3];
			Array.Copy(parentValues, 0, array5, 3, length);
			array5[0] = label3;
			array5[1] = grid4;
			array5[2] = viewCell;
			object service3;
			xamlServiceProvider3.Add(typeFromHandle5, service3 = new SimpleValueTargetProvider(array5, Label.FontSizeProperty, nameScope2));
			xamlServiceProvider3.Add(typeof(IReferenceProvider), service3);
			Type typeFromHandle6 = typeof(IXamlTypeResolver);
			XmlNamespaceResolver xmlNamespaceResolver3 = new XmlNamespaceResolver();
			xmlNamespaceResolver3.Add("", "http://xamarin.com/schemas/2014/forms");
			xmlNamespaceResolver3.Add("x", "http://schemas.microsoft.com/winfx/2009/xaml");
			xmlNamespaceResolver3.Add("calx", "clr-namespace:Caliburn.Micro.Xamarin.Forms;assembly=Caliburn.Micro.Platform.Xamarin.Forms");
			xmlNamespaceResolver3.Add("effect", "clr-namespace:NHL.Views.Effect");
			xamlServiceProvider3.Add(typeFromHandle6, new XamlTypeResolver(xmlNamespaceResolver3, typeof(_003CInitializeComponent_003E_anonXamlCDataTemplate_5).GetTypeInfo().Assembly));
			xamlServiceProvider3.Add(typeof(IXmlLineInfoProvider), new XmlLineInfoProvider(new XmlLineInfo(53, 151)));
			label3.SetValue(fontSizeProperty3, ((IExtendedTypeConverter)fontSizeConverter3).ConvertFromInvariantString("Small", (IServiceProvider)xamlServiceProvider3));
			label3.Effects.Add(fixedFontSizeLabelEffect3);
			VisualDiagnostics.RegisterSourceInfo(fixedFontSizeLabelEffect3, new Uri("Views/LogView.xaml", UriKind.RelativeOrAbsolute), 55, 42);
			grid4.Children.Add(label3);
			VisualDiagnostics.RegisterSourceInfo(label3, new Uri("Views/LogView.xaml", UriKind.RelativeOrAbsolute), 53, 34);
			label4.SetValue(Grid.RowProperty, 1);
			label4.SetValue(Grid.ColumnProperty, 1);
			label4.SetValue(Label.VerticalTextAlignmentProperty, new TextAlignmentConverter().ConvertFromInvariantString("Center"));
			label4.SetValue(Label.HorizontalTextAlignmentProperty, new TextAlignmentConverter().ConvertFromInvariantString("Start"));
			bindingExtension5.Mode = BindingMode.OneWay;
			bindingExtension5.Path = "SizeString";
			BindingBase binding5 = ((IMarkupExtension<BindingBase>)bindingExtension5).ProvideValue((IServiceProvider)null);
			label4.SetBinding(Label.TextProperty, binding5);
			BindableProperty fontSizeProperty4 = Label.FontSizeProperty;
			FontSizeConverter fontSizeConverter4 = new FontSizeConverter();
			XamlServiceProvider xamlServiceProvider4 = new XamlServiceProvider();
			Type typeFromHandle7 = typeof(IProvideValueTarget);
			int length2;
			object[] array6 = new object[(length2 = parentValues.Length) + 3];
			Array.Copy(parentValues, 0, array6, 3, length2);
			array6[0] = label4;
			array6[1] = grid4;
			array6[2] = viewCell;
			object service4;
			xamlServiceProvider4.Add(typeFromHandle7, service4 = new SimpleValueTargetProvider(array6, Label.FontSizeProperty, nameScope2));
			xamlServiceProvider4.Add(typeof(IReferenceProvider), service4);
			Type typeFromHandle8 = typeof(IXamlTypeResolver);
			XmlNamespaceResolver xmlNamespaceResolver4 = new XmlNamespaceResolver();
			xmlNamespaceResolver4.Add("", "http://xamarin.com/schemas/2014/forms");
			xmlNamespaceResolver4.Add("x", "http://schemas.microsoft.com/winfx/2009/xaml");
			xmlNamespaceResolver4.Add("calx", "clr-namespace:Caliburn.Micro.Xamarin.Forms;assembly=Caliburn.Micro.Platform.Xamarin.Forms");
			xmlNamespaceResolver4.Add("effect", "clr-namespace:NHL.Views.Effect");
			xamlServiceProvider4.Add(typeFromHandle8, new XamlTypeResolver(xmlNamespaceResolver4, typeof(_003CInitializeComponent_003E_anonXamlCDataTemplate_5).GetTypeInfo().Assembly));
			xamlServiceProvider4.Add(typeof(IXmlLineInfoProvider), new XmlLineInfoProvider(new XmlLineInfo(58, 173)));
			label4.SetValue(fontSizeProperty4, ((IExtendedTypeConverter)fontSizeConverter4).ConvertFromInvariantString("Small", (IServiceProvider)xamlServiceProvider4));
			label4.Effects.Add(fixedFontSizeLabelEffect4);
			VisualDiagnostics.RegisterSourceInfo(fixedFontSizeLabelEffect4, new Uri("Views/LogView.xaml", UriKind.RelativeOrAbsolute), 60, 42);
			grid4.Children.Add(label4);
			VisualDiagnostics.RegisterSourceInfo(label4, new Uri("Views/LogView.xaml", UriKind.RelativeOrAbsolute), 58, 34);
			button.SetValue(Grid.RowProperty, 1);
			button.SetValue(Grid.ColumnProperty, 2);
			button.SetValue(Button.TextProperty, "表示");
			button.SetValue(VisualElement.BackgroundColorProperty, Color.Silver);
			button.SetValue(Button.TextColorProperty, Color.Black);
			BindableProperty fontSizeProperty5 = Button.FontSizeProperty;
			FontSizeConverter fontSizeConverter5 = new FontSizeConverter();
			XamlServiceProvider xamlServiceProvider5 = new XamlServiceProvider();
			Type typeFromHandle9 = typeof(IProvideValueTarget);
			int length3;
			object[] array7 = new object[(length3 = parentValues.Length) + 3];
			Array.Copy(parentValues, 0, array7, 3, length3);
			array7[0] = button;
			array7[1] = grid4;
			array7[2] = viewCell;
			object service5;
			xamlServiceProvider5.Add(typeFromHandle9, service5 = new SimpleValueTargetProvider(array7, Button.FontSizeProperty, nameScope2));
			xamlServiceProvider5.Add(typeof(IReferenceProvider), service5);
			Type typeFromHandle10 = typeof(IXamlTypeResolver);
			XmlNamespaceResolver xmlNamespaceResolver5 = new XmlNamespaceResolver();
			xmlNamespaceResolver5.Add("", "http://xamarin.com/schemas/2014/forms");
			xmlNamespaceResolver5.Add("x", "http://schemas.microsoft.com/winfx/2009/xaml");
			xmlNamespaceResolver5.Add("calx", "clr-namespace:Caliburn.Micro.Xamarin.Forms;assembly=Caliburn.Micro.Platform.Xamarin.Forms");
			xmlNamespaceResolver5.Add("effect", "clr-namespace:NHL.Views.Effect");
			xamlServiceProvider5.Add(typeFromHandle10, new XamlTypeResolver(xmlNamespaceResolver5, typeof(_003CInitializeComponent_003E_anonXamlCDataTemplate_5).GetTypeInfo().Assembly));
			xamlServiceProvider5.Add(typeof(IXmlLineInfoProvider), new XmlLineInfoProvider(new XmlLineInfo(63, 123)));
			button.SetValue(fontSizeProperty5, ((IExtendedTypeConverter)fontSizeConverter5).ConvertFromInvariantString("10", (IServiceProvider)xamlServiceProvider5));
			button.SetValue(Message.AttachProperty, "ViewLog($dataContext)");
			button.Effects.Add(fixedFontSizeButtonEffect);
			VisualDiagnostics.RegisterSourceInfo(fixedFontSizeButtonEffect, new Uri("Views/LogView.xaml", UriKind.RelativeOrAbsolute), 65, 42);
			grid4.Children.Add(button);
			VisualDiagnostics.RegisterSourceInfo(button, new Uri("Views/LogView.xaml", UriKind.RelativeOrAbsolute), 63, 34);
			button2.SetValue(Grid.RowProperty, 1);
			button2.SetValue(Grid.ColumnProperty, 3);
			button2.SetValue(Button.TextProperty, "送信");
			button2.SetValue(VisualElement.BackgroundColorProperty, Color.Silver);
			button2.SetValue(Button.TextColorProperty, Color.Black);
			BindableProperty fontSizeProperty6 = Button.FontSizeProperty;
			FontSizeConverter fontSizeConverter6 = new FontSizeConverter();
			XamlServiceProvider xamlServiceProvider6 = new XamlServiceProvider();
			Type typeFromHandle11 = typeof(IProvideValueTarget);
			int length4;
			object[] array8 = new object[(length4 = parentValues.Length) + 3];
			Array.Copy(parentValues, 0, array8, 3, length4);
			array8[0] = button2;
			array8[1] = grid4;
			array8[2] = viewCell;
			object service6;
			xamlServiceProvider6.Add(typeFromHandle11, service6 = new SimpleValueTargetProvider(array8, Button.FontSizeProperty, nameScope2));
			xamlServiceProvider6.Add(typeof(IReferenceProvider), service6);
			Type typeFromHandle12 = typeof(IXamlTypeResolver);
			XmlNamespaceResolver xmlNamespaceResolver6 = new XmlNamespaceResolver();
			xmlNamespaceResolver6.Add("", "http://xamarin.com/schemas/2014/forms");
			xmlNamespaceResolver6.Add("x", "http://schemas.microsoft.com/winfx/2009/xaml");
			xmlNamespaceResolver6.Add("calx", "clr-namespace:Caliburn.Micro.Xamarin.Forms;assembly=Caliburn.Micro.Platform.Xamarin.Forms");
			xmlNamespaceResolver6.Add("effect", "clr-namespace:NHL.Views.Effect");
			xamlServiceProvider6.Add(typeFromHandle12, new XamlTypeResolver(xmlNamespaceResolver6, typeof(_003CInitializeComponent_003E_anonXamlCDataTemplate_5).GetTypeInfo().Assembly));
			xamlServiceProvider6.Add(typeof(IXmlLineInfoProvider), new XmlLineInfoProvider(new XmlLineInfo(68, 123)));
			button2.SetValue(fontSizeProperty6, ((IExtendedTypeConverter)fontSizeConverter6).ConvertFromInvariantString("10", (IServiceProvider)xamlServiceProvider6));
			button2.SetValue(Message.AttachProperty, "SendLog($dataContext)");
			button2.Effects.Add(fixedFontSizeButtonEffect2);
			VisualDiagnostics.RegisterSourceInfo(fixedFontSizeButtonEffect2, new Uri("Views/LogView.xaml", UriKind.RelativeOrAbsolute), 70, 42);
			grid4.Children.Add(button2);
			VisualDiagnostics.RegisterSourceInfo(button2, new Uri("Views/LogView.xaml", UriKind.RelativeOrAbsolute), 68, 34);
			viewCell.View = grid4;
			VisualDiagnostics.RegisterSourceInfo(grid4, new Uri("Views/LogView.xaml", UriKind.RelativeOrAbsolute), 37, 30);
			return viewCell;
		};
		listView.SetValue(ItemsView<Cell>.ItemTemplateProperty, dataTemplate);
		VisualDiagnostics.RegisterSourceInfo(dataTemplate, new Uri("Views/LogView.xaml", UriKind.RelativeOrAbsolute), 35, 22);
		grid3.Children.Add(listView);
		VisualDiagnostics.RegisterSourceInfo(listView, new Uri("Views/LogView.xaml", UriKind.RelativeOrAbsolute), 24, 14);
		listView2.SetValue(Grid.RowProperty, 1);
		bindingExtension3.Mode = BindingMode.OneWay;
		bindingExtension3.Path = "LogTextList";
		BindingBase binding3 = ((IMarkupExtension<BindingBase>)bindingExtension3).ProvideValue((IServiceProvider)null);
		listView2.SetBinding(ItemsView<Cell>.ItemsSourceProperty, binding3);
		listView2.SetValue(ListView.SeparatorVisibilityProperty, SeparatorVisibility.None);
		listView2.SetValue(ListView.HasUnevenRowsProperty, true);
		label2.SetValue(Xamarin.Forms.View.HorizontalOptionsProperty, LayoutOptions.FillAndExpand);
		label2.SetValue(Xamarin.Forms.View.VerticalOptionsProperty, LayoutOptions.FillAndExpand);
		label2.SetValue(Label.VerticalTextAlignmentProperty, new TextAlignmentConverter().ConvertFromInvariantString("Center"));
		label2.SetValue(Label.HorizontalTextAlignmentProperty, new TextAlignmentConverter().ConvertFromInvariantString("Center"));
		label2.SetValue(Label.TextProperty, "ログ内容");
		BindableProperty fontSizeProperty2 = Label.FontSizeProperty;
		FontSizeConverter fontSizeConverter2 = new FontSizeConverter();
		XamlServiceProvider xamlServiceProvider2 = new XamlServiceProvider();
		Type typeFromHandle3 = typeof(IProvideValueTarget);
		object[] array3 = new object[0 + 5];
		array3[0] = label2;
		array3[1] = grid2;
		array3[2] = listView2;
		array3[3] = grid3;
		array3[4] = logView;
		object service2;
		xamlServiceProvider2.Add(typeFromHandle3, service2 = new SimpleValueTargetProvider(array3, Label.FontSizeProperty, nameScope));
		xamlServiceProvider2.Add(typeof(IReferenceProvider), service2);
		Type typeFromHandle4 = typeof(IXamlTypeResolver);
		XmlNamespaceResolver xmlNamespaceResolver2 = new XmlNamespaceResolver();
		xmlNamespaceResolver2.Add("", "http://xamarin.com/schemas/2014/forms");
		xmlNamespaceResolver2.Add("x", "http://schemas.microsoft.com/winfx/2009/xaml");
		xmlNamespaceResolver2.Add("calx", "clr-namespace:Caliburn.Micro.Xamarin.Forms;assembly=Caliburn.Micro.Platform.Xamarin.Forms");
		xmlNamespaceResolver2.Add("effect", "clr-namespace:NHL.Views.Effect");
		xamlServiceProvider2.Add(typeFromHandle4, new XamlTypeResolver(xmlNamespaceResolver2, typeof(LogView).GetTypeInfo().Assembly));
		xamlServiceProvider2.Add(typeof(IXmlLineInfoProvider), new XmlLineInfoProvider(new XmlLineInfo(81, 174)));
		label2.SetValue(fontSizeProperty2, ((IExtendedTypeConverter)fontSizeConverter2).ConvertFromInvariantString("Small", (IServiceProvider)xamlServiceProvider2));
		label2.SetValue(VisualElement.BackgroundColorProperty, Color.Navy);
		label2.SetValue(Label.TextColorProperty, Color.White);
		label2.Effects.Add(fixedFontSizeLabelEffect2);
		VisualDiagnostics.RegisterSourceInfo(fixedFontSizeLabelEffect2, new Uri("Views/LogView.xaml", UriKind.RelativeOrAbsolute), 83, 34);
		grid2.Children.Add(label2);
		VisualDiagnostics.RegisterSourceInfo(label2, new Uri("Views/LogView.xaml", UriKind.RelativeOrAbsolute), 81, 26);
		listView2.SetValue(ListView.HeaderProperty, grid2);
		VisualDiagnostics.RegisterSourceInfo(grid2, new Uri("Views/LogView.xaml", UriKind.RelativeOrAbsolute), 80, 22);
		object[] array4 = new object[0 + 4];
		array4[0] = dataTemplate2;
		array4[1] = listView2;
		array4[2] = grid3;
		array4[3] = logView;
		object[] parentValues2 = array4;
		LogView root2 = logView;
		((IDataTemplate)dataTemplate2).LoadTemplate = delegate
		{
			BindingExtension bindingExtension4 = new BindingExtension();
			FixedFontSizeLabelEffect fixedFontSizeLabelEffect3 = new FixedFontSizeLabelEffect();
			Label label3 = new Label();
			Grid grid4 = new Grid();
			ViewCell viewCell = new ViewCell();
			NameScope nameScope2 = new NameScope();
			NameScope.SetNameScope(viewCell, nameScope2);
			grid4.SetValue(VisualElement.BackgroundColorProperty, Color.White);
			label3.SetValue(Label.VerticalTextAlignmentProperty, new TextAlignmentConverter().ConvertFromInvariantString("Center"));
			label3.SetValue(Label.HorizontalTextAlignmentProperty, new TextAlignmentConverter().ConvertFromInvariantString("Start"));
			bindingExtension4.Mode = BindingMode.OneWay;
			bindingExtension4.Path = ".";
			BindingBase binding4 = ((IMarkupExtension<BindingBase>)bindingExtension4).ProvideValue((IServiceProvider)null);
			label3.SetBinding(Label.TextProperty, binding4);
			BindableProperty fontSizeProperty3 = Label.FontSizeProperty;
			FontSizeConverter fontSizeConverter3 = new FontSizeConverter();
			XamlServiceProvider xamlServiceProvider3 = new XamlServiceProvider();
			Type typeFromHandle5 = typeof(IProvideValueTarget);
			int length;
			object[] array5 = new object[(length = parentValues2.Length) + 3];
			Array.Copy(parentValues2, 0, array5, 3, length);
			array5[0] = label3;
			array5[1] = grid4;
			array5[2] = viewCell;
			object service3;
			xamlServiceProvider3.Add(typeFromHandle5, service3 = new SimpleValueTargetProvider(array5, Label.FontSizeProperty, nameScope2));
			xamlServiceProvider3.Add(typeof(IReferenceProvider), service3);
			Type typeFromHandle6 = typeof(IXamlTypeResolver);
			XmlNamespaceResolver xmlNamespaceResolver3 = new XmlNamespaceResolver();
			xmlNamespaceResolver3.Add("", "http://xamarin.com/schemas/2014/forms");
			xmlNamespaceResolver3.Add("x", "http://schemas.microsoft.com/winfx/2009/xaml");
			xmlNamespaceResolver3.Add("calx", "clr-namespace:Caliburn.Micro.Xamarin.Forms;assembly=Caliburn.Micro.Platform.Xamarin.Forms");
			xmlNamespaceResolver3.Add("effect", "clr-namespace:NHL.Views.Effect");
			xamlServiceProvider3.Add(typeFromHandle6, new XamlTypeResolver(xmlNamespaceResolver3, typeof(_003CInitializeComponent_003E_anonXamlCDataTemplate_6).GetTypeInfo().Assembly));
			xamlServiceProvider3.Add(typeof(IXmlLineInfoProvider), new XmlLineInfoProvider(new XmlLineInfo(92, 135)));
			label3.SetValue(fontSizeProperty3, ((IExtendedTypeConverter)fontSizeConverter3).ConvertFromInvariantString("Small", (IServiceProvider)xamlServiceProvider3));
			label3.Effects.Add(fixedFontSizeLabelEffect3);
			VisualDiagnostics.RegisterSourceInfo(fixedFontSizeLabelEffect3, new Uri("Views/LogView.xaml", UriKind.RelativeOrAbsolute), 94, 42);
			grid4.Children.Add(label3);
			VisualDiagnostics.RegisterSourceInfo(label3, new Uri("Views/LogView.xaml", UriKind.RelativeOrAbsolute), 92, 34);
			viewCell.View = grid4;
			VisualDiagnostics.RegisterSourceInfo(grid4, new Uri("Views/LogView.xaml", UriKind.RelativeOrAbsolute), 91, 30);
			return viewCell;
		};
		listView2.SetValue(ItemsView<Cell>.ItemTemplateProperty, dataTemplate2);
		VisualDiagnostics.RegisterSourceInfo(dataTemplate2, new Uri("Views/LogView.xaml", UriKind.RelativeOrAbsolute), 89, 22);
		grid3.Children.Add(listView2);
		VisualDiagnostics.RegisterSourceInfo(listView2, new Uri("Views/LogView.xaml", UriKind.RelativeOrAbsolute), 78, 14);
		logView.SetValue(ContentPage.ContentProperty, grid3);
		VisualDiagnostics.RegisterSourceInfo(grid3, new Uri("Views/LogView.xaml", UriKind.RelativeOrAbsolute), 19, 10);
		VisualDiagnostics.RegisterSourceInfo(logView, new Uri("Views/LogView.xaml", UriKind.RelativeOrAbsolute), 2, 2);
	}

	private void __InitComponentRuntime()
	{
		this.LoadFromXaml(typeof(LogView));
	}
}
