using System;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Reflection;
using Caliburn.Micro.Xamarin.Forms;
using NHL.Views.Effect;
using Xamarin.Forms;
using Xamarin.Forms.Internals;
using Xamarin.Forms.Xaml;
using Xamarin.Forms.Xaml.Diagnostics;
using Xamarin.Forms.Xaml.Internals;

namespace NHL.Views;

[XamlCompilation(XamlCompilationOptions.Compile)]
[XamlFilePath("Views/MeterView.xaml")]
public class MeterView : ContentPage
{
	public MeterView()
	{
		InitializeComponent();
	}

	[GeneratedCode("Xamarin.Forms.Build.Tasks.XamlG", "2.0.0.0")]
	private void InitializeComponent()
	{
		if (ResourceLoader.CanProvideContentFor(new ResourceLoader.ResourceLoadingQuery
		{
			AssemblyName = typeof(MeterView).GetTypeInfo().Assembly.GetName(),
			ResourcePath = "Views/MeterView.xaml",
			Instance = this
		}))
		{
			__InitComponentRuntime();
			return;
		}
		if (XamlLoader.XamlFileProvider != null && XamlLoader.XamlFileProvider(GetType()) != null)
		{
			__InitComponentRuntime();
			return;
		}
		StaticResourceExtension staticResourceExtension = new StaticResourceExtension();
		Color color = Color.FromHex("#EFEFF4");
		Color color2 = Color.FromHex("#CFCFCF");
		ResourceDictionary resourceDictionary = new ResourceDictionary();
		OnPlatform<Thickness> onPlatform = new OnPlatform<Thickness>();
		RowDefinition rowDefinition = new RowDefinition();
		RowDefinition rowDefinition2 = new RowDefinition();
		RowDefinition rowDefinition3 = new RowDefinition();
		RowDefinition rowDefinition4 = new RowDefinition();
		RowDefinition rowDefinition5 = new RowDefinition();
		RowDefinition rowDefinition6 = new RowDefinition();
		RowDefinition rowDefinition7 = new RowDefinition();
		RowDefinition rowDefinition8 = new RowDefinition();
		RowDefinition rowDefinition9 = new RowDefinition();
		RowDefinition rowDefinition10 = new RowDefinition();
		RowDefinition rowDefinition11 = new RowDefinition();
		Grid grid = new Grid();
		Grid grid2 = new Grid();
		Grid grid3 = new Grid();
		Grid grid4 = new Grid();
		Grid grid5 = new Grid();
		FixedFontSizeLabelEffect fixedFontSizeLabelEffect = new FixedFontSizeLabelEffect();
		Label label = new Label();
		BindingExtension bindingExtension = new BindingExtension();
		FixedFontSizeLabelEffect fixedFontSizeLabelEffect2 = new FixedFontSizeLabelEffect();
		Label label2 = new Label();
		FixedFontSizeLabelEffect fixedFontSizeLabelEffect3 = new FixedFontSizeLabelEffect();
		Label label3 = new Label();
		StaticResourceExtension staticResourceExtension2 = new StaticResourceExtension();
		BoxView boxView = new BoxView();
		FixedFontSizeButtonEffect fixedFontSizeButtonEffect = new FixedFontSizeButtonEffect();
		Button button = new Button();
		FixedFontSizeLabelEffect fixedFontSizeLabelEffect4 = new FixedFontSizeLabelEffect();
		Label label4 = new Label();
		BindingExtension bindingExtension2 = new BindingExtension();
		FixedFontSizeLabelEffect fixedFontSizeLabelEffect5 = new FixedFontSizeLabelEffect();
		Label label5 = new Label();
		FixedFontSizeLabelEffect fixedFontSizeLabelEffect6 = new FixedFontSizeLabelEffect();
		Label label6 = new Label();
		StaticResourceExtension staticResourceExtension3 = new StaticResourceExtension();
		BoxView boxView2 = new BoxView();
		FixedFontSizeButtonEffect fixedFontSizeButtonEffect2 = new FixedFontSizeButtonEffect();
		Button button2 = new Button();
		FixedFontSizeLabelEffect fixedFontSizeLabelEffect7 = new FixedFontSizeLabelEffect();
		Label label7 = new Label();
		BindingExtension bindingExtension3 = new BindingExtension();
		FixedFontSizeLabelEffect fixedFontSizeLabelEffect8 = new FixedFontSizeLabelEffect();
		Label label8 = new Label();
		FixedFontSizeLabelEffect fixedFontSizeLabelEffect9 = new FixedFontSizeLabelEffect();
		Label label9 = new Label();
		StaticResourceExtension staticResourceExtension4 = new StaticResourceExtension();
		BoxView boxView3 = new BoxView();
		FixedFontSizeButtonEffect fixedFontSizeButtonEffect3 = new FixedFontSizeButtonEffect();
		Button button3 = new Button();
		FixedFontSizeLabelEffect fixedFontSizeLabelEffect10 = new FixedFontSizeLabelEffect();
		Label label10 = new Label();
		BindingExtension bindingExtension4 = new BindingExtension();
		FixedFontSizeLabelEffect fixedFontSizeLabelEffect11 = new FixedFontSizeLabelEffect();
		Label label11 = new Label();
		BindingExtension bindingExtension5 = new BindingExtension();
		FixedFontSizeLabelEffect fixedFontSizeLabelEffect12 = new FixedFontSizeLabelEffect();
		Label label12 = new Label();
		BindingExtension bindingExtension6 = new BindingExtension();
		Setter setter = new Setter();
		DataTrigger dataTrigger = new DataTrigger(typeof(Grid));
		Grid grid6 = new Grid();
		BindingExtension bindingExtension7 = new BindingExtension();
		FixedFontSizeLabelEffect fixedFontSizeLabelEffect13 = new FixedFontSizeLabelEffect();
		BindingExtension bindingExtension8 = new BindingExtension();
		Setter setter2 = new Setter();
		DataTrigger dataTrigger2 = new DataTrigger(typeof(Label));
		Label label13 = new Label();
		FixedFontSizeLabelEffect fixedFontSizeLabelEffect14 = new FixedFontSizeLabelEffect();
		Label label14 = new Label();
		FixedFontSizeButtonEffect fixedFontSizeButtonEffect4 = new FixedFontSizeButtonEffect();
		Button button4 = new Button();
		FixedFontSizeLabelEffect fixedFontSizeLabelEffect15 = new FixedFontSizeLabelEffect();
		Span span = new Span();
		string newLine = Environment.NewLine;
		Span span2 = new Span();
		Span span3 = new Span();
		FormattedString formattedString = new FormattedString();
		Label label15 = new Label();
		Grid grid7 = new Grid();
		ScrollView scrollView = new ScrollView();
		MeterView meterView;
		NameScope nameScope = (NameScope)(NameScope.GetNameScope(meterView = this) ?? new NameScope());
		NameScope.SetNameScope(meterView, nameScope);
		meterView.Resources = resourceDictionary;
		VisualDiagnostics.RegisterSourceInfo(resourceDictionary, new Uri("Views/MeterView.xaml", UriKind.RelativeOrAbsolute), 13, 10);
		resourceDictionary.Add("PageBackgroundColor", color);
		resourceDictionary.Add("LineColor", color2);
		meterView.SetValue(Page.TitleProperty, "測定器");
		staticResourceExtension.Key = "PageBackgroundColor";
		XamlServiceProvider xamlServiceProvider = new XamlServiceProvider();
		Type typeFromHandle = typeof(IProvideValueTarget);
		object[] array = new object[0 + 1];
		array[0] = meterView;
		object service;
		xamlServiceProvider.Add(typeFromHandle, service = new SimpleValueTargetProvider(array, VisualElement.BackgroundColorProperty, nameScope));
		xamlServiceProvider.Add(typeof(IReferenceProvider), service);
		Type typeFromHandle2 = typeof(IXamlTypeResolver);
		XmlNamespaceResolver xmlNamespaceResolver = new XmlNamespaceResolver();
		xmlNamespaceResolver.Add("", "http://xamarin.com/schemas/2014/forms");
		xmlNamespaceResolver.Add("x", "http://schemas.microsoft.com/winfx/2009/xaml");
		xmlNamespaceResolver.Add("calx", "clr-namespace:Caliburn.Micro.Xamarin.Forms;assembly=Caliburn.Micro.Platform.Xamarin.Forms");
		xmlNamespaceResolver.Add("effect", "clr-namespace:NHL.Views.Effect");
		xmlNamespaceResolver.Add("system", "clr-namespace:System;assembly=System.Runtime.Extensions");
		xamlServiceProvider.Add(typeFromHandle2, new XamlTypeResolver(xmlNamespaceResolver, typeof(MeterView).GetTypeInfo().Assembly));
		xamlServiceProvider.Add(typeof(IXmlLineInfoProvider), new XmlLineInfoProvider(new XmlLineInfo(10, 14)));
		object obj = ((IMarkupExtension)staticResourceExtension).ProvideValue((IServiceProvider)xamlServiceProvider);
		meterView.BackgroundColor = (Color)obj;
		VisualDiagnostics.RegisterSourceInfo(obj, new Uri("Views/MeterView.xaml", UriKind.RelativeOrAbsolute), 10, 14);
		meterView.Resources = resourceDictionary;
		VisualDiagnostics.RegisterSourceInfo(resourceDictionary, new Uri("Views/MeterView.xaml", UriKind.RelativeOrAbsolute), 13, 10);
		onPlatform.iOS = new Thickness(0.0, 20.0, 0.0, 20.0);
		onPlatform.Android = new Thickness(0.0, 10.0, 0.0, 20.0);
		meterView.SetValue(Page.PaddingProperty, (Thickness)onPlatform);
		VisualDiagnostics.RegisterSourceInfo(onPlatform, new Uri("Views/MeterView.xaml", UriKind.RelativeOrAbsolute), 33, 10);
		scrollView.SetValue(Xamarin.Forms.View.VerticalOptionsProperty, LayoutOptions.FillAndExpand);
		scrollView.SetValue(Xamarin.Forms.View.HorizontalOptionsProperty, LayoutOptions.FillAndExpand);
		grid7.SetValue(Grid.RowSpacingProperty, 0.0);
		grid7.SetValue(Grid.ColumnSpacingProperty, 0.0);
		rowDefinition.SetValue(RowDefinition.HeightProperty, new GridLengthTypeConverter().ConvertFromInvariantString("Auto"));
		((DefinitionCollection<RowDefinition>)grid7.GetValue(Grid.RowDefinitionsProperty)).Add(rowDefinition);
		rowDefinition2.SetValue(RowDefinition.HeightProperty, new GridLengthTypeConverter().ConvertFromInvariantString("Auto"));
		((DefinitionCollection<RowDefinition>)grid7.GetValue(Grid.RowDefinitionsProperty)).Add(rowDefinition2);
		rowDefinition3.SetValue(RowDefinition.HeightProperty, new GridLengthTypeConverter().ConvertFromInvariantString("Auto"));
		((DefinitionCollection<RowDefinition>)grid7.GetValue(Grid.RowDefinitionsProperty)).Add(rowDefinition3);
		rowDefinition4.SetValue(RowDefinition.HeightProperty, new GridLengthTypeConverter().ConvertFromInvariantString("Auto"));
		((DefinitionCollection<RowDefinition>)grid7.GetValue(Grid.RowDefinitionsProperty)).Add(rowDefinition4);
		rowDefinition5.SetValue(RowDefinition.HeightProperty, new GridLengthTypeConverter().ConvertFromInvariantString("Auto"));
		((DefinitionCollection<RowDefinition>)grid7.GetValue(Grid.RowDefinitionsProperty)).Add(rowDefinition5);
		rowDefinition6.SetValue(RowDefinition.HeightProperty, new GridLengthTypeConverter().ConvertFromInvariantString("Auto"));
		((DefinitionCollection<RowDefinition>)grid7.GetValue(Grid.RowDefinitionsProperty)).Add(rowDefinition6);
		rowDefinition7.SetValue(RowDefinition.HeightProperty, new GridLengthTypeConverter().ConvertFromInvariantString("Auto"));
		((DefinitionCollection<RowDefinition>)grid7.GetValue(Grid.RowDefinitionsProperty)).Add(rowDefinition7);
		rowDefinition8.SetValue(RowDefinition.HeightProperty, new GridLengthTypeConverter().ConvertFromInvariantString("Auto"));
		((DefinitionCollection<RowDefinition>)grid7.GetValue(Grid.RowDefinitionsProperty)).Add(rowDefinition8);
		rowDefinition9.SetValue(RowDefinition.HeightProperty, new GridLengthTypeConverter().ConvertFromInvariantString("Auto"));
		((DefinitionCollection<RowDefinition>)grid7.GetValue(Grid.RowDefinitionsProperty)).Add(rowDefinition9);
		rowDefinition10.SetValue(RowDefinition.HeightProperty, new GridLengthTypeConverter().ConvertFromInvariantString("Auto"));
		((DefinitionCollection<RowDefinition>)grid7.GetValue(Grid.RowDefinitionsProperty)).Add(rowDefinition10);
		rowDefinition11.SetValue(RowDefinition.HeightProperty, new GridLengthTypeConverter().ConvertFromInvariantString("*"));
		((DefinitionCollection<RowDefinition>)grid7.GetValue(Grid.RowDefinitionsProperty)).Add(rowDefinition11);
		grid.SetValue(Grid.RowProperty, 1);
		grid.SetValue(VisualElement.BackgroundColorProperty, Color.White);
		grid7.Children.Add(grid);
		VisualDiagnostics.RegisterSourceInfo(grid, new Uri("Views/MeterView.xaml", UriKind.RelativeOrAbsolute), 56, 14);
		grid2.SetValue(Grid.RowProperty, 3);
		grid2.SetValue(VisualElement.BackgroundColorProperty, Color.White);
		grid7.Children.Add(grid2);
		VisualDiagnostics.RegisterSourceInfo(grid2, new Uri("Views/MeterView.xaml", UriKind.RelativeOrAbsolute), 57, 14);
		grid3.SetValue(Grid.RowProperty, 5);
		grid3.SetValue(VisualElement.BackgroundColorProperty, Color.White);
		grid7.Children.Add(grid3);
		VisualDiagnostics.RegisterSourceInfo(grid3, new Uri("Views/MeterView.xaml", UriKind.RelativeOrAbsolute), 58, 14);
		grid4.SetValue(Grid.RowProperty, 7);
		grid4.SetValue(VisualElement.BackgroundColorProperty, Color.White);
		grid7.Children.Add(grid4);
		VisualDiagnostics.RegisterSourceInfo(grid4, new Uri("Views/MeterView.xaml", UriKind.RelativeOrAbsolute), 59, 14);
		grid5.SetValue(Grid.RowProperty, 8);
		grid5.SetValue(VisualElement.BackgroundColorProperty, Color.White);
		grid7.Children.Add(grid5);
		VisualDiagnostics.RegisterSourceInfo(grid5, new Uri("Views/MeterView.xaml", UriKind.RelativeOrAbsolute), 60, 14);
		label.SetValue(Grid.RowProperty, 0);
		label.SetValue(Label.TextProperty, "血糖（ニプロケアファストLink）");
		BindableProperty fontSizeProperty = Label.FontSizeProperty;
		FontSizeConverter fontSizeConverter = new FontSizeConverter();
		XamlServiceProvider xamlServiceProvider2 = new XamlServiceProvider();
		Type typeFromHandle3 = typeof(IProvideValueTarget);
		object[] array2 = new object[0 + 4];
		array2[0] = label;
		array2[1] = grid7;
		array2[2] = scrollView;
		array2[3] = meterView;
		object service2;
		xamlServiceProvider2.Add(typeFromHandle3, service2 = new SimpleValueTargetProvider(array2, Label.FontSizeProperty, nameScope));
		xamlServiceProvider2.Add(typeof(IReferenceProvider), service2);
		Type typeFromHandle4 = typeof(IXamlTypeResolver);
		XmlNamespaceResolver xmlNamespaceResolver2 = new XmlNamespaceResolver();
		xmlNamespaceResolver2.Add("", "http://xamarin.com/schemas/2014/forms");
		xmlNamespaceResolver2.Add("x", "http://schemas.microsoft.com/winfx/2009/xaml");
		xmlNamespaceResolver2.Add("calx", "clr-namespace:Caliburn.Micro.Xamarin.Forms;assembly=Caliburn.Micro.Platform.Xamarin.Forms");
		xmlNamespaceResolver2.Add("effect", "clr-namespace:NHL.Views.Effect");
		xmlNamespaceResolver2.Add("system", "clr-namespace:System;assembly=System.Runtime.Extensions");
		xamlServiceProvider2.Add(typeFromHandle4, new XamlTypeResolver(xmlNamespaceResolver2, typeof(MeterView).GetTypeInfo().Assembly));
		xamlServiceProvider2.Add(typeof(IXmlLineInfoProvider), new XmlLineInfoProvider(new XmlLineInfo(63, 58)));
		label.SetValue(fontSizeProperty, ((IExtendedTypeConverter)fontSizeConverter).ConvertFromInvariantString("Medium", (IServiceProvider)xamlServiceProvider2));
		label.SetValue(Label.FontAttributesProperty, new FontAttributesConverter().ConvertFromInvariantString("Bold"));
		label.SetValue(Xamarin.Forms.View.MarginProperty, new Thickness(10.0, 0.0, 0.0, 0.0));
		label.Effects.Add(fixedFontSizeLabelEffect);
		VisualDiagnostics.RegisterSourceInfo(fixedFontSizeLabelEffect, new Uri("Views/MeterView.xaml", UriKind.RelativeOrAbsolute), 65, 22);
		grid7.Children.Add(label);
		VisualDiagnostics.RegisterSourceInfo(label, new Uri("Views/MeterView.xaml", UriKind.RelativeOrAbsolute), 63, 14);
		label2.SetValue(Grid.RowProperty, 1);
		bindingExtension.Path = "BloodGlucoseMeter.Name";
		BindingBase binding = ((IMarkupExtension<BindingBase>)bindingExtension).ProvideValue((IServiceProvider)null);
		label2.SetBinding(Label.TextProperty, binding);
		label2.SetValue(Xamarin.Forms.View.MarginProperty, new Thickness(10.0, 0.0, 0.0, 1.0));
		label2.SetValue(Label.VerticalTextAlignmentProperty, new TextAlignmentConverter().ConvertFromInvariantString("Center"));
		label2.SetValue(Xamarin.Forms.View.VerticalOptionsProperty, LayoutOptions.Center);
		label2.Effects.Add(fixedFontSizeLabelEffect2);
		VisualDiagnostics.RegisterSourceInfo(fixedFontSizeLabelEffect2, new Uri("Views/MeterView.xaml", UriKind.RelativeOrAbsolute), 70, 22);
		grid7.Children.Add(label2);
		VisualDiagnostics.RegisterSourceInfo(label2, new Uri("Views/MeterView.xaml", UriKind.RelativeOrAbsolute), 68, 14);
		label3.SetValue(Grid.RowProperty, 1);
		label3.SetValue(Label.TextProperty, "＞");
		label3.SetValue(VisualElement.WidthRequestProperty, 20.0);
		label3.SetValue(Xamarin.Forms.View.HorizontalOptionsProperty, LayoutOptions.End);
		label3.SetValue(Label.VerticalTextAlignmentProperty, new TextAlignmentConverter().ConvertFromInvariantString("Center"));
		label3.Effects.Add(fixedFontSizeLabelEffect3);
		VisualDiagnostics.RegisterSourceInfo(fixedFontSizeLabelEffect3, new Uri("Views/MeterView.xaml", UriKind.RelativeOrAbsolute), 75, 22);
		grid7.Children.Add(label3);
		VisualDiagnostics.RegisterSourceInfo(label3, new Uri("Views/MeterView.xaml", UriKind.RelativeOrAbsolute), 73, 14);
		boxView.SetValue(Grid.RowProperty, 1);
		staticResourceExtension2.Key = "LineColor";
		XamlServiceProvider xamlServiceProvider3 = new XamlServiceProvider();
		Type typeFromHandle5 = typeof(IProvideValueTarget);
		object[] array3 = new object[0 + 4];
		array3[0] = boxView;
		array3[1] = grid7;
		array3[2] = scrollView;
		array3[3] = meterView;
		object service3;
		xamlServiceProvider3.Add(typeFromHandle5, service3 = new SimpleValueTargetProvider(array3, VisualElement.BackgroundColorProperty, nameScope));
		xamlServiceProvider3.Add(typeof(IReferenceProvider), service3);
		Type typeFromHandle6 = typeof(IXamlTypeResolver);
		XmlNamespaceResolver xmlNamespaceResolver3 = new XmlNamespaceResolver();
		xmlNamespaceResolver3.Add("", "http://xamarin.com/schemas/2014/forms");
		xmlNamespaceResolver3.Add("x", "http://schemas.microsoft.com/winfx/2009/xaml");
		xmlNamespaceResolver3.Add("calx", "clr-namespace:Caliburn.Micro.Xamarin.Forms;assembly=Caliburn.Micro.Platform.Xamarin.Forms");
		xmlNamespaceResolver3.Add("effect", "clr-namespace:NHL.Views.Effect");
		xmlNamespaceResolver3.Add("system", "clr-namespace:System;assembly=System.Runtime.Extensions");
		xamlServiceProvider3.Add(typeFromHandle6, new XamlTypeResolver(xmlNamespaceResolver3, typeof(MeterView).GetTypeInfo().Assembly));
		xamlServiceProvider3.Add(typeof(IXmlLineInfoProvider), new XmlLineInfoProvider(new XmlLineInfo(78, 35)));
		object obj2 = ((IMarkupExtension)staticResourceExtension2).ProvideValue((IServiceProvider)xamlServiceProvider3);
		boxView.BackgroundColor = (Color)obj2;
		VisualDiagnostics.RegisterSourceInfo(obj2, new Uri("Views/MeterView.xaml", UriKind.RelativeOrAbsolute), 78, 35);
		boxView.SetValue(VisualElement.HeightRequestProperty, 1.0);
		boxView.SetValue(Xamarin.Forms.View.VerticalOptionsProperty, LayoutOptions.End);
		grid7.Children.Add(boxView);
		VisualDiagnostics.RegisterSourceInfo(boxView, new Uri("Views/MeterView.xaml", UriKind.RelativeOrAbsolute), 78, 14);
		button.SetValue(Grid.RowProperty, 1);
		button.SetValue(VisualElement.BackgroundColorProperty, Color.Transparent);
		button.SetValue(Button.BorderColorProperty, Color.Transparent);
		button.SetValue(Message.AttachProperty, "ScanGL");
		button.SetValue(Xamarin.Forms.View.HorizontalOptionsProperty, LayoutOptions.FillAndExpand);
		button.Effects.Add(fixedFontSizeButtonEffect);
		VisualDiagnostics.RegisterSourceInfo(fixedFontSizeButtonEffect, new Uri("Views/MeterView.xaml", UriKind.RelativeOrAbsolute), 81, 22);
		grid7.Children.Add(button);
		VisualDiagnostics.RegisterSourceInfo(button, new Uri("Views/MeterView.xaml", UriKind.RelativeOrAbsolute), 79, 14);
		label4.SetValue(Grid.RowProperty, 2);
		label4.SetValue(Label.TextProperty, "体温計（NSM-1BLE, NT-100B）");
		BindableProperty fontSizeProperty2 = Label.FontSizeProperty;
		FontSizeConverter fontSizeConverter2 = new FontSizeConverter();
		XamlServiceProvider xamlServiceProvider4 = new XamlServiceProvider();
		Type typeFromHandle7 = typeof(IProvideValueTarget);
		object[] array4 = new object[0 + 4];
		array4[0] = label4;
		array4[1] = grid7;
		array4[2] = scrollView;
		array4[3] = meterView;
		object service4;
		xamlServiceProvider4.Add(typeFromHandle7, service4 = new SimpleValueTargetProvider(array4, Label.FontSizeProperty, nameScope));
		xamlServiceProvider4.Add(typeof(IReferenceProvider), service4);
		Type typeFromHandle8 = typeof(IXamlTypeResolver);
		XmlNamespaceResolver xmlNamespaceResolver4 = new XmlNamespaceResolver();
		xmlNamespaceResolver4.Add("", "http://xamarin.com/schemas/2014/forms");
		xmlNamespaceResolver4.Add("x", "http://schemas.microsoft.com/winfx/2009/xaml");
		xmlNamespaceResolver4.Add("calx", "clr-namespace:Caliburn.Micro.Xamarin.Forms;assembly=Caliburn.Micro.Platform.Xamarin.Forms");
		xmlNamespaceResolver4.Add("effect", "clr-namespace:NHL.Views.Effect");
		xmlNamespaceResolver4.Add("system", "clr-namespace:System;assembly=System.Runtime.Extensions");
		xamlServiceProvider4.Add(typeFromHandle8, new XamlTypeResolver(xmlNamespaceResolver4, typeof(MeterView).GetTypeInfo().Assembly));
		xamlServiceProvider4.Add(typeof(IXmlLineInfoProvider), new XmlLineInfoProvider(new XmlLineInfo(86, 63)));
		label4.SetValue(fontSizeProperty2, ((IExtendedTypeConverter)fontSizeConverter2).ConvertFromInvariantString("Medium", (IServiceProvider)xamlServiceProvider4));
		label4.SetValue(Label.FontAttributesProperty, new FontAttributesConverter().ConvertFromInvariantString("Bold"));
		label4.SetValue(Xamarin.Forms.View.MarginProperty, new Thickness(10.0, 0.0, 0.0, 0.0));
		label4.Effects.Add(fixedFontSizeLabelEffect4);
		VisualDiagnostics.RegisterSourceInfo(fixedFontSizeLabelEffect4, new Uri("Views/MeterView.xaml", UriKind.RelativeOrAbsolute), 88, 22);
		grid7.Children.Add(label4);
		VisualDiagnostics.RegisterSourceInfo(label4, new Uri("Views/MeterView.xaml", UriKind.RelativeOrAbsolute), 86, 14);
		label5.SetValue(Grid.RowProperty, 3);
		bindingExtension2.Path = "Thermometer.Name";
		BindingBase binding2 = ((IMarkupExtension<BindingBase>)bindingExtension2).ProvideValue((IServiceProvider)null);
		label5.SetBinding(Label.TextProperty, binding2);
		label5.SetValue(Xamarin.Forms.View.MarginProperty, new Thickness(10.0, 0.0, 0.0, 1.0));
		label5.SetValue(Label.VerticalTextAlignmentProperty, new TextAlignmentConverter().ConvertFromInvariantString("Center"));
		label5.SetValue(Xamarin.Forms.View.VerticalOptionsProperty, LayoutOptions.Center);
		label5.Effects.Add(fixedFontSizeLabelEffect5);
		VisualDiagnostics.RegisterSourceInfo(fixedFontSizeLabelEffect5, new Uri("Views/MeterView.xaml", UriKind.RelativeOrAbsolute), 93, 22);
		grid7.Children.Add(label5);
		VisualDiagnostics.RegisterSourceInfo(label5, new Uri("Views/MeterView.xaml", UriKind.RelativeOrAbsolute), 91, 14);
		label6.SetValue(Grid.RowProperty, 3);
		label6.SetValue(Label.TextProperty, "＞");
		label6.SetValue(VisualElement.WidthRequestProperty, 20.0);
		label6.SetValue(Xamarin.Forms.View.HorizontalOptionsProperty, LayoutOptions.End);
		label6.SetValue(Label.VerticalTextAlignmentProperty, new TextAlignmentConverter().ConvertFromInvariantString("Center"));
		label6.Effects.Add(fixedFontSizeLabelEffect6);
		VisualDiagnostics.RegisterSourceInfo(fixedFontSizeLabelEffect6, new Uri("Views/MeterView.xaml", UriKind.RelativeOrAbsolute), 98, 22);
		grid7.Children.Add(label6);
		VisualDiagnostics.RegisterSourceInfo(label6, new Uri("Views/MeterView.xaml", UriKind.RelativeOrAbsolute), 96, 14);
		boxView2.SetValue(Grid.RowProperty, 3);
		staticResourceExtension3.Key = "LineColor";
		XamlServiceProvider xamlServiceProvider5 = new XamlServiceProvider();
		Type typeFromHandle9 = typeof(IProvideValueTarget);
		object[] array5 = new object[0 + 4];
		array5[0] = boxView2;
		array5[1] = grid7;
		array5[2] = scrollView;
		array5[3] = meterView;
		object service5;
		xamlServiceProvider5.Add(typeFromHandle9, service5 = new SimpleValueTargetProvider(array5, VisualElement.BackgroundColorProperty, nameScope));
		xamlServiceProvider5.Add(typeof(IReferenceProvider), service5);
		Type typeFromHandle10 = typeof(IXamlTypeResolver);
		XmlNamespaceResolver xmlNamespaceResolver5 = new XmlNamespaceResolver();
		xmlNamespaceResolver5.Add("", "http://xamarin.com/schemas/2014/forms");
		xmlNamespaceResolver5.Add("x", "http://schemas.microsoft.com/winfx/2009/xaml");
		xmlNamespaceResolver5.Add("calx", "clr-namespace:Caliburn.Micro.Xamarin.Forms;assembly=Caliburn.Micro.Platform.Xamarin.Forms");
		xmlNamespaceResolver5.Add("effect", "clr-namespace:NHL.Views.Effect");
		xmlNamespaceResolver5.Add("system", "clr-namespace:System;assembly=System.Runtime.Extensions");
		xamlServiceProvider5.Add(typeFromHandle10, new XamlTypeResolver(xmlNamespaceResolver5, typeof(MeterView).GetTypeInfo().Assembly));
		xamlServiceProvider5.Add(typeof(IXmlLineInfoProvider), new XmlLineInfoProvider(new XmlLineInfo(101, 35)));
		object obj3 = ((IMarkupExtension)staticResourceExtension3).ProvideValue((IServiceProvider)xamlServiceProvider5);
		boxView2.BackgroundColor = (Color)obj3;
		VisualDiagnostics.RegisterSourceInfo(obj3, new Uri("Views/MeterView.xaml", UriKind.RelativeOrAbsolute), 101, 35);
		boxView2.SetValue(VisualElement.HeightRequestProperty, 1.0);
		boxView2.SetValue(Xamarin.Forms.View.VerticalOptionsProperty, LayoutOptions.End);
		grid7.Children.Add(boxView2);
		VisualDiagnostics.RegisterSourceInfo(boxView2, new Uri("Views/MeterView.xaml", UriKind.RelativeOrAbsolute), 101, 14);
		button2.SetValue(Grid.RowProperty, 3);
		button2.SetValue(VisualElement.BackgroundColorProperty, Color.Transparent);
		button2.SetValue(Button.BorderColorProperty, Color.Transparent);
		button2.SetValue(Message.AttachProperty, "ScanHT");
		button2.SetValue(Xamarin.Forms.View.HorizontalOptionsProperty, LayoutOptions.FillAndExpand);
		button2.Effects.Add(fixedFontSizeButtonEffect2);
		VisualDiagnostics.RegisterSourceInfo(fixedFontSizeButtonEffect2, new Uri("Views/MeterView.xaml", UriKind.RelativeOrAbsolute), 104, 22);
		grid7.Children.Add(button2);
		VisualDiagnostics.RegisterSourceInfo(button2, new Uri("Views/MeterView.xaml", UriKind.RelativeOrAbsolute), 102, 14);
		label7.SetValue(Grid.RowProperty, 4);
		label7.SetValue(Label.TextProperty, "血圧/脈拍計（NBP-1BLE）");
		BindableProperty fontSizeProperty3 = Label.FontSizeProperty;
		FontSizeConverter fontSizeConverter3 = new FontSizeConverter();
		XamlServiceProvider xamlServiceProvider6 = new XamlServiceProvider();
		Type typeFromHandle11 = typeof(IProvideValueTarget);
		object[] array6 = new object[0 + 4];
		array6[0] = label7;
		array6[1] = grid7;
		array6[2] = scrollView;
		array6[3] = meterView;
		object service6;
		xamlServiceProvider6.Add(typeFromHandle11, service6 = new SimpleValueTargetProvider(array6, Label.FontSizeProperty, nameScope));
		xamlServiceProvider6.Add(typeof(IReferenceProvider), service6);
		Type typeFromHandle12 = typeof(IXamlTypeResolver);
		XmlNamespaceResolver xmlNamespaceResolver6 = new XmlNamespaceResolver();
		xmlNamespaceResolver6.Add("", "http://xamarin.com/schemas/2014/forms");
		xmlNamespaceResolver6.Add("x", "http://schemas.microsoft.com/winfx/2009/xaml");
		xmlNamespaceResolver6.Add("calx", "clr-namespace:Caliburn.Micro.Xamarin.Forms;assembly=Caliburn.Micro.Platform.Xamarin.Forms");
		xmlNamespaceResolver6.Add("effect", "clr-namespace:NHL.Views.Effect");
		xmlNamespaceResolver6.Add("system", "clr-namespace:System;assembly=System.Runtime.Extensions");
		xamlServiceProvider6.Add(typeFromHandle12, new XamlTypeResolver(xmlNamespaceResolver6, typeof(MeterView).GetTypeInfo().Assembly));
		xamlServiceProvider6.Add(typeof(IXmlLineInfoProvider), new XmlLineInfoProvider(new XmlLineInfo(109, 57)));
		label7.SetValue(fontSizeProperty3, ((IExtendedTypeConverter)fontSizeConverter3).ConvertFromInvariantString("Medium", (IServiceProvider)xamlServiceProvider6));
		label7.SetValue(Label.FontAttributesProperty, new FontAttributesConverter().ConvertFromInvariantString("Bold"));
		label7.SetValue(Xamarin.Forms.View.MarginProperty, new Thickness(10.0, 0.0, 0.0, 0.0));
		label7.Effects.Add(fixedFontSizeLabelEffect7);
		VisualDiagnostics.RegisterSourceInfo(fixedFontSizeLabelEffect7, new Uri("Views/MeterView.xaml", UriKind.RelativeOrAbsolute), 111, 22);
		grid7.Children.Add(label7);
		VisualDiagnostics.RegisterSourceInfo(label7, new Uri("Views/MeterView.xaml", UriKind.RelativeOrAbsolute), 109, 14);
		label8.SetValue(Grid.RowProperty, 5);
		bindingExtension3.Path = "Sphygmomanometer.Name";
		BindingBase binding3 = ((IMarkupExtension<BindingBase>)bindingExtension3).ProvideValue((IServiceProvider)null);
		label8.SetBinding(Label.TextProperty, binding3);
		label8.SetValue(Xamarin.Forms.View.MarginProperty, new Thickness(10.0, 0.0, 0.0, 1.0));
		label8.SetValue(Label.VerticalTextAlignmentProperty, new TextAlignmentConverter().ConvertFromInvariantString("Center"));
		label8.SetValue(Xamarin.Forms.View.VerticalOptionsProperty, LayoutOptions.Center);
		label8.Effects.Add(fixedFontSizeLabelEffect8);
		VisualDiagnostics.RegisterSourceInfo(fixedFontSizeLabelEffect8, new Uri("Views/MeterView.xaml", UriKind.RelativeOrAbsolute), 116, 22);
		grid7.Children.Add(label8);
		VisualDiagnostics.RegisterSourceInfo(label8, new Uri("Views/MeterView.xaml", UriKind.RelativeOrAbsolute), 114, 14);
		label9.SetValue(Grid.RowProperty, 5);
		label9.SetValue(Label.TextProperty, "＞");
		label9.SetValue(VisualElement.WidthRequestProperty, 20.0);
		label9.SetValue(Xamarin.Forms.View.HorizontalOptionsProperty, LayoutOptions.End);
		label9.SetValue(Label.VerticalTextAlignmentProperty, new TextAlignmentConverter().ConvertFromInvariantString("Center"));
		label9.Effects.Add(fixedFontSizeLabelEffect9);
		VisualDiagnostics.RegisterSourceInfo(fixedFontSizeLabelEffect9, new Uri("Views/MeterView.xaml", UriKind.RelativeOrAbsolute), 121, 22);
		grid7.Children.Add(label9);
		VisualDiagnostics.RegisterSourceInfo(label9, new Uri("Views/MeterView.xaml", UriKind.RelativeOrAbsolute), 119, 14);
		boxView3.SetValue(Grid.RowProperty, 5);
		staticResourceExtension4.Key = "LineColor";
		XamlServiceProvider xamlServiceProvider7 = new XamlServiceProvider();
		Type typeFromHandle13 = typeof(IProvideValueTarget);
		object[] array7 = new object[0 + 4];
		array7[0] = boxView3;
		array7[1] = grid7;
		array7[2] = scrollView;
		array7[3] = meterView;
		object service7;
		xamlServiceProvider7.Add(typeFromHandle13, service7 = new SimpleValueTargetProvider(array7, VisualElement.BackgroundColorProperty, nameScope));
		xamlServiceProvider7.Add(typeof(IReferenceProvider), service7);
		Type typeFromHandle14 = typeof(IXamlTypeResolver);
		XmlNamespaceResolver xmlNamespaceResolver7 = new XmlNamespaceResolver();
		xmlNamespaceResolver7.Add("", "http://xamarin.com/schemas/2014/forms");
		xmlNamespaceResolver7.Add("x", "http://schemas.microsoft.com/winfx/2009/xaml");
		xmlNamespaceResolver7.Add("calx", "clr-namespace:Caliburn.Micro.Xamarin.Forms;assembly=Caliburn.Micro.Platform.Xamarin.Forms");
		xmlNamespaceResolver7.Add("effect", "clr-namespace:NHL.Views.Effect");
		xmlNamespaceResolver7.Add("system", "clr-namespace:System;assembly=System.Runtime.Extensions");
		xamlServiceProvider7.Add(typeFromHandle14, new XamlTypeResolver(xmlNamespaceResolver7, typeof(MeterView).GetTypeInfo().Assembly));
		xamlServiceProvider7.Add(typeof(IXmlLineInfoProvider), new XmlLineInfoProvider(new XmlLineInfo(124, 35)));
		object obj4 = ((IMarkupExtension)staticResourceExtension4).ProvideValue((IServiceProvider)xamlServiceProvider7);
		boxView3.BackgroundColor = (Color)obj4;
		VisualDiagnostics.RegisterSourceInfo(obj4, new Uri("Views/MeterView.xaml", UriKind.RelativeOrAbsolute), 124, 35);
		boxView3.SetValue(VisualElement.HeightRequestProperty, 1.0);
		boxView3.SetValue(Xamarin.Forms.View.VerticalOptionsProperty, LayoutOptions.End);
		grid7.Children.Add(boxView3);
		VisualDiagnostics.RegisterSourceInfo(boxView3, new Uri("Views/MeterView.xaml", UriKind.RelativeOrAbsolute), 124, 14);
		button3.SetValue(Grid.RowProperty, 5);
		button3.SetValue(VisualElement.BackgroundColorProperty, Color.Transparent);
		button3.SetValue(Button.BorderColorProperty, Color.Transparent);
		button3.SetValue(Message.AttachProperty, "ScanBP");
		button3.SetValue(Xamarin.Forms.View.HorizontalOptionsProperty, LayoutOptions.FillAndExpand);
		button3.Effects.Add(fixedFontSizeButtonEffect3);
		VisualDiagnostics.RegisterSourceInfo(fixedFontSizeButtonEffect3, new Uri("Views/MeterView.xaml", UriKind.RelativeOrAbsolute), 127, 22);
		grid7.Children.Add(button3);
		VisualDiagnostics.RegisterSourceInfo(button3, new Uri("Views/MeterView.xaml", UriKind.RelativeOrAbsolute), 125, 14);
		label10.SetValue(Grid.RowProperty, 6);
		label10.SetValue(Label.TextProperty, "体組成計（NBCM）");
		BindableProperty fontSizeProperty4 = Label.FontSizeProperty;
		FontSizeConverter fontSizeConverter4 = new FontSizeConverter();
		XamlServiceProvider xamlServiceProvider8 = new XamlServiceProvider();
		Type typeFromHandle15 = typeof(IProvideValueTarget);
		object[] array8 = new object[0 + 4];
		array8[0] = label10;
		array8[1] = grid7;
		array8[2] = scrollView;
		array8[3] = meterView;
		object service8;
		xamlServiceProvider8.Add(typeFromHandle15, service8 = new SimpleValueTargetProvider(array8, Label.FontSizeProperty, nameScope));
		xamlServiceProvider8.Add(typeof(IReferenceProvider), service8);
		Type typeFromHandle16 = typeof(IXamlTypeResolver);
		XmlNamespaceResolver xmlNamespaceResolver8 = new XmlNamespaceResolver();
		xmlNamespaceResolver8.Add("", "http://xamarin.com/schemas/2014/forms");
		xmlNamespaceResolver8.Add("x", "http://schemas.microsoft.com/winfx/2009/xaml");
		xmlNamespaceResolver8.Add("calx", "clr-namespace:Caliburn.Micro.Xamarin.Forms;assembly=Caliburn.Micro.Platform.Xamarin.Forms");
		xmlNamespaceResolver8.Add("effect", "clr-namespace:NHL.Views.Effect");
		xmlNamespaceResolver8.Add("system", "clr-namespace:System;assembly=System.Runtime.Extensions");
		xamlServiceProvider8.Add(typeFromHandle16, new XamlTypeResolver(xmlNamespaceResolver8, typeof(MeterView).GetTypeInfo().Assembly));
		xamlServiceProvider8.Add(typeof(IXmlLineInfoProvider), new XmlLineInfoProvider(new XmlLineInfo(132, 51)));
		label10.SetValue(fontSizeProperty4, ((IExtendedTypeConverter)fontSizeConverter4).ConvertFromInvariantString("Medium", (IServiceProvider)xamlServiceProvider8));
		label10.SetValue(Label.FontAttributesProperty, new FontAttributesConverter().ConvertFromInvariantString("Bold"));
		label10.SetValue(Xamarin.Forms.View.MarginProperty, new Thickness(10.0, 0.0, 0.0, 0.0));
		label10.Effects.Add(fixedFontSizeLabelEffect10);
		VisualDiagnostics.RegisterSourceInfo(fixedFontSizeLabelEffect10, new Uri("Views/MeterView.xaml", UriKind.RelativeOrAbsolute), 134, 22);
		grid7.Children.Add(label10);
		VisualDiagnostics.RegisterSourceInfo(label10, new Uri("Views/MeterView.xaml", UriKind.RelativeOrAbsolute), 132, 14);
		label11.SetValue(Grid.RowProperty, 7);
		bindingExtension4.Path = "BodyCompositionMeter.Name";
		BindingBase binding4 = ((IMarkupExtension<BindingBase>)bindingExtension4).ProvideValue((IServiceProvider)null);
		label11.SetBinding(Label.TextProperty, binding4);
		label11.SetValue(Xamarin.Forms.View.MarginProperty, new Thickness(10.0, 0.0, 0.0, 1.0));
		label11.SetValue(Label.VerticalTextAlignmentProperty, new TextAlignmentConverter().ConvertFromInvariantString("Center"));
		label11.SetValue(Xamarin.Forms.View.VerticalOptionsProperty, LayoutOptions.Center);
		label11.Effects.Add(fixedFontSizeLabelEffect11);
		VisualDiagnostics.RegisterSourceInfo(fixedFontSizeLabelEffect11, new Uri("Views/MeterView.xaml", UriKind.RelativeOrAbsolute), 139, 22);
		grid7.Children.Add(label11);
		VisualDiagnostics.RegisterSourceInfo(label11, new Uri("Views/MeterView.xaml", UriKind.RelativeOrAbsolute), 137, 14);
		label12.SetValue(Grid.RowProperty, 8);
		bindingExtension5.Path = "BodyCompositionMeterUserInfo";
		BindingBase binding5 = ((IMarkupExtension<BindingBase>)bindingExtension5).ProvideValue((IServiceProvider)null);
		label12.SetBinding(Label.TextProperty, binding5);
		label12.SetValue(Xamarin.Forms.View.MarginProperty, new Thickness(10.0, 0.0, 0.0, 1.0));
		label12.SetValue(Label.VerticalTextAlignmentProperty, new TextAlignmentConverter().ConvertFromInvariantString("Center"));
		label12.SetValue(Xamarin.Forms.View.VerticalOptionsProperty, LayoutOptions.Center);
		label12.Effects.Add(fixedFontSizeLabelEffect12);
		VisualDiagnostics.RegisterSourceInfo(fixedFontSizeLabelEffect12, new Uri("Views/MeterView.xaml", UriKind.RelativeOrAbsolute), 144, 22);
		grid7.Children.Add(label12);
		VisualDiagnostics.RegisterSourceInfo(label12, new Uri("Views/MeterView.xaml", UriKind.RelativeOrAbsolute), 142, 14);
		grid6.SetValue(Grid.RowProperty, 7);
		grid6.SetValue(Grid.RowSpanProperty, 2);
		grid6.SetValue(VisualElement.IsVisibleProperty, new VisibilityConverter().ConvertFromInvariantString("False"));
		grid6.SetValue(VisualElement.BackgroundColorProperty, Color.White);
		bindingExtension6.Path = "BodyCompositionMeterUserInfo";
		BindingBase target = (dataTrigger.Binding = ((IMarkupExtension<BindingBase>)bindingExtension6).ProvideValue((IServiceProvider)null));
		VisualDiagnostics.RegisterSourceInfo(target, new Uri("Views/MeterView.xaml", UriKind.RelativeOrAbsolute), 150, 52);
		dataTrigger.Value = "";
		setter.Property = VisualElement.IsVisibleProperty;
		setter.Value = "True";
		setter.Value = new VisibilityConverter().ConvertFromInvariantString("True");
		dataTrigger.Setters.Add(setter);
		VisualDiagnostics.RegisterSourceInfo(setter, new Uri("Views/MeterView.xaml", UriKind.RelativeOrAbsolute), 151, 26);
		((ICollection<TriggerBase>)grid6.GetValue(VisualElement.TriggersProperty)).Add((TriggerBase)dataTrigger);
		VisualDiagnostics.RegisterSourceInfo(dataTrigger, new Uri("Views/MeterView.xaml", UriKind.RelativeOrAbsolute), 150, 22);
		grid7.Children.Add(grid6);
		VisualDiagnostics.RegisterSourceInfo(grid6, new Uri("Views/MeterView.xaml", UriKind.RelativeOrAbsolute), 148, 14);
		label13.SetValue(Grid.RowProperty, 7);
		label13.SetValue(Grid.RowSpanProperty, 2);
		label13.SetValue(VisualElement.IsVisibleProperty, new VisibilityConverter().ConvertFromInvariantString("False"));
		bindingExtension7.Path = "BodyCompositionMeter.Name";
		BindingBase binding6 = ((IMarkupExtension<BindingBase>)bindingExtension7).ProvideValue((IServiceProvider)null);
		label13.SetBinding(Label.TextProperty, binding6);
		label13.SetValue(Xamarin.Forms.View.MarginProperty, new Thickness(10.0, 0.0, 0.0, 1.0));
		label13.SetValue(Label.VerticalTextAlignmentProperty, new TextAlignmentConverter().ConvertFromInvariantString("Center"));
		label13.SetValue(Xamarin.Forms.View.VerticalOptionsProperty, LayoutOptions.Fill);
		label13.Effects.Add(fixedFontSizeLabelEffect13);
		VisualDiagnostics.RegisterSourceInfo(fixedFontSizeLabelEffect13, new Uri("Views/MeterView.xaml", UriKind.RelativeOrAbsolute), 157, 22);
		bindingExtension8.Path = "BodyCompositionMeterUserInfo";
		BindingBase target2 = (dataTrigger2.Binding = ((IMarkupExtension<BindingBase>)bindingExtension8).ProvideValue((IServiceProvider)null));
		VisualDiagnostics.RegisterSourceInfo(target2, new Uri("Views/MeterView.xaml", UriKind.RelativeOrAbsolute), 160, 53);
		dataTrigger2.Value = "";
		setter2.Property = VisualElement.IsVisibleProperty;
		setter2.Value = "True";
		setter2.Value = new VisibilityConverter().ConvertFromInvariantString("True");
		dataTrigger2.Setters.Add(setter2);
		VisualDiagnostics.RegisterSourceInfo(setter2, new Uri("Views/MeterView.xaml", UriKind.RelativeOrAbsolute), 161, 26);
		((ICollection<TriggerBase>)label13.GetValue(VisualElement.TriggersProperty)).Add((TriggerBase)dataTrigger2);
		VisualDiagnostics.RegisterSourceInfo(dataTrigger2, new Uri("Views/MeterView.xaml", UriKind.RelativeOrAbsolute), 160, 22);
		grid7.Children.Add(label13);
		VisualDiagnostics.RegisterSourceInfo(label13, new Uri("Views/MeterView.xaml", UriKind.RelativeOrAbsolute), 155, 14);
		label14.SetValue(Grid.RowProperty, 7);
		label14.SetValue(Grid.RowSpanProperty, 2);
		label14.SetValue(Label.TextProperty, "＞");
		label14.SetValue(VisualElement.WidthRequestProperty, 20.0);
		label14.SetValue(Xamarin.Forms.View.HorizontalOptionsProperty, LayoutOptions.End);
		label14.SetValue(Label.VerticalTextAlignmentProperty, new TextAlignmentConverter().ConvertFromInvariantString("Center"));
		label14.Effects.Add(fixedFontSizeLabelEffect14);
		VisualDiagnostics.RegisterSourceInfo(fixedFontSizeLabelEffect14, new Uri("Views/MeterView.xaml", UriKind.RelativeOrAbsolute), 167, 22);
		grid7.Children.Add(label14);
		VisualDiagnostics.RegisterSourceInfo(label14, new Uri("Views/MeterView.xaml", UriKind.RelativeOrAbsolute), 165, 14);
		button4.SetValue(Grid.RowProperty, 7);
		button4.SetValue(Grid.RowSpanProperty, 2);
		button4.SetValue(VisualElement.BackgroundColorProperty, Color.Transparent);
		button4.SetValue(Button.BorderColorProperty, Color.Transparent);
		button4.SetValue(Message.AttachProperty, "ScanBC");
		button4.SetValue(Xamarin.Forms.View.HorizontalOptionsProperty, LayoutOptions.FillAndExpand);
		button4.Effects.Add(fixedFontSizeButtonEffect4);
		VisualDiagnostics.RegisterSourceInfo(fixedFontSizeButtonEffect4, new Uri("Views/MeterView.xaml", UriKind.RelativeOrAbsolute), 172, 22);
		grid7.Children.Add(button4);
		VisualDiagnostics.RegisterSourceInfo(button4, new Uri("Views/MeterView.xaml", UriKind.RelativeOrAbsolute), 170, 14);
		label15.SetValue(Grid.RowProperty, 9);
		label15.SetValue(Xamarin.Forms.View.MarginProperty, new Thickness(10.0, 10.0, 10.0, 0.0));
		label15.Effects.Add(fixedFontSizeLabelEffect15);
		VisualDiagnostics.RegisterSourceInfo(fixedFontSizeLabelEffect15, new Uri("Views/MeterView.xaml", UriKind.RelativeOrAbsolute), 178, 22);
		span.SetValue(Span.TextProperty, "血糖、体温計、血圧計は測定を行うと各画面で自動的に受信します。");
		formattedString.Spans.Add(span);
		VisualDiagnostics.RegisterSourceInfo(span, new Uri("Views/MeterView.xaml", UriKind.RelativeOrAbsolute), 182, 26);
		span2.SetValue(Span.TextProperty, newLine);
		VisualDiagnostics.RegisterSourceInfo(newLine, new Uri("Views/MeterView.xaml", UriKind.RelativeOrAbsolute), 183, 31);
		formattedString.Spans.Add(span2);
		VisualDiagnostics.RegisterSourceInfo(span2, new Uri("Views/MeterView.xaml", UriKind.RelativeOrAbsolute), 183, 26);
		span3.SetValue(Span.TextProperty, "体組成計は、ホーム画面から専用ボタンで受信を行って下さい。");
		formattedString.Spans.Add(span3);
		VisualDiagnostics.RegisterSourceInfo(span3, new Uri("Views/MeterView.xaml", UriKind.RelativeOrAbsolute), 184, 26);
		label15.SetValue(Label.FormattedTextProperty, formattedString);
		VisualDiagnostics.RegisterSourceInfo(formattedString, new Uri("Views/MeterView.xaml", UriKind.RelativeOrAbsolute), 181, 22);
		grid7.Children.Add(label15);
		VisualDiagnostics.RegisterSourceInfo(label15, new Uri("Views/MeterView.xaml", UriKind.RelativeOrAbsolute), 176, 14);
		scrollView.Content = grid7;
		VisualDiagnostics.RegisterSourceInfo(grid7, new Uri("Views/MeterView.xaml", UriKind.RelativeOrAbsolute), 40, 10);
		meterView.SetValue(ContentPage.ContentProperty, scrollView);
		VisualDiagnostics.RegisterSourceInfo(scrollView, new Uri("Views/MeterView.xaml", UriKind.RelativeOrAbsolute), 38, 6);
		VisualDiagnostics.RegisterSourceInfo(meterView, new Uri("Views/MeterView.xaml", UriKind.RelativeOrAbsolute), 3, 2);
	}

	private void __InitComponentRuntime()
	{
		this.LoadFromXaml(typeof(MeterView));
	}
}
