using System;
using System.CodeDom.Compiler;
using System.Reflection;
using System.Runtime.CompilerServices;
using NHL.Views.Effect;
using Xamarin.Forms;
using Xamarin.Forms.Internals;
using Xamarin.Forms.Xaml;
using Xamarin.Forms.Xaml.Diagnostics;
using Xamarin.Forms.Xaml.Internals;

namespace NHL.Views;

[XamlCompilation(XamlCompilationOptions.Compile)]
[XamlFilePath("Views/NoticeListView.xaml")]
public class NoticeListView : ContentPage
{
	[CompilerGenerated]
	private sealed class _003CInitializeComponent_003E_anonXamlCDataTemplate_1
	{
		internal object[] parentValues;

		internal NoticeListView root;

		internal object LoadDataTemplate()
		{
			ColumnDefinition columnDefinition = new ColumnDefinition();
			ColumnDefinition columnDefinition2 = new ColumnDefinition();
			RowDefinition rowDefinition = new RowDefinition();
			RowDefinition rowDefinition2 = new RowDefinition();
			RowDefinition rowDefinition3 = new RowDefinition();
			RowDefinition rowDefinition4 = new RowDefinition();
			FixedFontSizeLabelEffect fixedFontSizeLabelEffect = new FixedFontSizeLabelEffect();
			BindingExtension bindingExtension = new BindingExtension();
			Span span = new Span();
			BindingExtension bindingExtension2 = new BindingExtension();
			Span span2 = new Span();
			FormattedString formattedString = new FormattedString();
			Label label = new Label();
			BindingExtension bindingExtension3 = new BindingExtension();
			FixedFontSizeLabelEffect fixedFontSizeLabelEffect2 = new FixedFontSizeLabelEffect();
			Label label2 = new Label();
			FixedFontSizeLabelEffect fixedFontSizeLabelEffect3 = new FixedFontSizeLabelEffect();
			Label label3 = new Label();
			StaticResourceExtension staticResourceExtension = new StaticResourceExtension();
			BoxView boxView = new BoxView();
			StaticResourceExtension staticResourceExtension2 = new StaticResourceExtension();
			Label label4 = new Label();
			Grid grid = new Grid();
			StackLayout stackLayout = new StackLayout();
			ViewCell viewCell = new ViewCell();
			NameScope nameScope = new NameScope();
			NameScope.SetNameScope(viewCell, nameScope);
			stackLayout.SetValue(View.HorizontalOptionsProperty, LayoutOptions.Start);
			grid.SetValue(Grid.RowSpacingProperty, 0.0);
			grid.SetValue(Grid.ColumnSpacingProperty, 0.0);
			grid.SetValue(VisualElement.BackgroundColorProperty, Color.White);
			grid.SetValue(View.HorizontalOptionsProperty, LayoutOptions.Fill);
			grid.SetValue(View.VerticalOptionsProperty, LayoutOptions.Center);
			columnDefinition.SetValue(ColumnDefinition.WidthProperty, new GridLengthTypeConverter().ConvertFromInvariantString("*"));
			((DefinitionCollection<ColumnDefinition>)grid.GetValue(Grid.ColumnDefinitionsProperty)).Add(columnDefinition);
			columnDefinition2.SetValue(ColumnDefinition.WidthProperty, new GridLengthTypeConverter().ConvertFromInvariantString("30"));
			((DefinitionCollection<ColumnDefinition>)grid.GetValue(Grid.ColumnDefinitionsProperty)).Add(columnDefinition2);
			rowDefinition.SetValue(RowDefinition.HeightProperty, new GridLengthTypeConverter().ConvertFromInvariantString("30"));
			((DefinitionCollection<RowDefinition>)grid.GetValue(Grid.RowDefinitionsProperty)).Add(rowDefinition);
			rowDefinition2.SetValue(RowDefinition.HeightProperty, new GridLengthTypeConverter().ConvertFromInvariantString("35"));
			((DefinitionCollection<RowDefinition>)grid.GetValue(Grid.RowDefinitionsProperty)).Add(rowDefinition2);
			rowDefinition3.SetValue(RowDefinition.HeightProperty, new GridLengthTypeConverter().ConvertFromInvariantString("Auto"));
			((DefinitionCollection<RowDefinition>)grid.GetValue(Grid.RowDefinitionsProperty)).Add(rowDefinition3);
			rowDefinition4.SetValue(RowDefinition.HeightProperty, new GridLengthTypeConverter().ConvertFromInvariantString("*"));
			((DefinitionCollection<RowDefinition>)grid.GetValue(Grid.RowDefinitionsProperty)).Add(rowDefinition4);
			label.SetValue(Grid.RowProperty, 0);
			label.SetValue(Grid.ColumnProperty, 0);
			label.SetValue(View.MarginProperty, new Thickness(10.0, 5.0, 0.0, 0.0));
			label.Effects.Add(fixedFontSizeLabelEffect);
			VisualDiagnostics.RegisterSourceInfo(fixedFontSizeLabelEffect, new Uri("Views/NoticeListView.xaml", UriKind.RelativeOrAbsolute), 70, 46);
			bindingExtension.StringFormat = "{0:yyyy/MM/dd(ddd)}";
			bindingExtension.Path = "Notice.ExpiryDateFrom";
			BindingBase binding = ((IMarkupExtension<BindingBase>)bindingExtension).ProvideValue((IServiceProvider)null);
			span.SetBinding(Span.TextProperty, binding);
			span.SetValue(Span.FontAttributesProperty, new FontAttributesConverter().ConvertFromInvariantString("Bold"));
			formattedString.Spans.Add(span);
			VisualDiagnostics.RegisterSourceInfo(span, new Uri("Views/NoticeListView.xaml", UriKind.RelativeOrAbsolute), 75, 50);
			bindingExtension2.StringFormat = " {0}";
			bindingExtension2.Path = "Hospital.FacilitiesName";
			BindingBase binding2 = ((IMarkupExtension<BindingBase>)bindingExtension2).ProvideValue((IServiceProvider)null);
			span2.SetBinding(Span.TextProperty, binding2);
			span2.SetValue(Span.FontAttributesProperty, new FontAttributesConverter().ConvertFromInvariantString("Bold"));
			formattedString.Spans.Add(span2);
			VisualDiagnostics.RegisterSourceInfo(span2, new Uri("Views/NoticeListView.xaml", UriKind.RelativeOrAbsolute), 77, 50);
			label.SetValue(Label.FormattedTextProperty, formattedString);
			VisualDiagnostics.RegisterSourceInfo(formattedString, new Uri("Views/NoticeListView.xaml", UriKind.RelativeOrAbsolute), 73, 46);
			grid.Children.Add(label);
			VisualDiagnostics.RegisterSourceInfo(label, new Uri("Views/NoticeListView.xaml", UriKind.RelativeOrAbsolute), 68, 38);
			label2.SetValue(Grid.RowProperty, 1);
			label2.SetValue(Grid.ColumnProperty, 0);
			bindingExtension3.Path = "Notice.Title";
			BindingBase binding3 = ((IMarkupExtension<BindingBase>)bindingExtension3).ProvideValue((IServiceProvider)null);
			label2.SetBinding(Label.TextProperty, binding3);
			label2.SetValue(View.MarginProperty, new Thickness(15.0, 5.0, 0.0, 0.0));
			label2.SetValue(Label.LineBreakModeProperty, LineBreakMode.TailTruncation);
			label2.Effects.Add(fixedFontSizeLabelEffect2);
			VisualDiagnostics.RegisterSourceInfo(fixedFontSizeLabelEffect2, new Uri("Views/NoticeListView.xaml", UriKind.RelativeOrAbsolute), 85, 46);
			grid.Children.Add(label2);
			VisualDiagnostics.RegisterSourceInfo(label2, new Uri("Views/NoticeListView.xaml", UriKind.RelativeOrAbsolute), 83, 38);
			label3.SetValue(Grid.RowProperty, 0);
			label3.SetValue(Grid.ColumnProperty, 1);
			label3.SetValue(Grid.RowSpanProperty, 3);
			label3.SetValue(Label.TextProperty, "＞");
			label3.SetValue(View.HorizontalOptionsProperty, LayoutOptions.End);
			label3.SetValue(Label.VerticalTextAlignmentProperty, new TextAlignmentConverter().ConvertFromInvariantString("Center"));
			label3.SetValue(View.MarginProperty, new Thickness(0.0, 0.0, 10.0, 0.0));
			label3.Effects.Add(fixedFontSizeLabelEffect3);
			VisualDiagnostics.RegisterSourceInfo(fixedFontSizeLabelEffect3, new Uri("Views/NoticeListView.xaml", UriKind.RelativeOrAbsolute), 92, 46);
			grid.Children.Add(label3);
			VisualDiagnostics.RegisterSourceInfo(label3, new Uri("Views/NoticeListView.xaml", UriKind.RelativeOrAbsolute), 90, 38);
			boxView.SetValue(Grid.RowProperty, 2);
			boxView.SetValue(Grid.ColumnProperty, 0);
			boxView.SetValue(Grid.ColumnSpanProperty, 2);
			staticResourceExtension.Key = "LineColor";
			XamlServiceProvider xamlServiceProvider = new XamlServiceProvider();
			Type typeFromHandle = typeof(IProvideValueTarget);
			int length;
			object[] array = new object[(length = parentValues.Length) + 4];
			Array.Copy(parentValues, 0, array, 4, length);
			array[0] = boxView;
			array[1] = grid;
			array[2] = stackLayout;
			array[3] = viewCell;
			object service;
			xamlServiceProvider.Add(typeFromHandle, service = new SimpleValueTargetProvider(array, VisualElement.BackgroundColorProperty, nameScope));
			xamlServiceProvider.Add(typeof(IReferenceProvider), service);
			Type typeFromHandle2 = typeof(IXamlTypeResolver);
			XmlNamespaceResolver xmlNamespaceResolver = new XmlNamespaceResolver();
			xmlNamespaceResolver.Add("", "http://xamarin.com/schemas/2014/forms");
			xmlNamespaceResolver.Add("x", "http://schemas.microsoft.com/winfx/2009/xaml");
			xmlNamespaceResolver.Add("effect", "clr-namespace:NHL.Views.Effect");
			xamlServiceProvider.Add(typeFromHandle2, new XamlTypeResolver(xmlNamespaceResolver, typeof(_003CInitializeComponent_003E_anonXamlCDataTemplate_1).GetTypeInfo().Assembly));
			xamlServiceProvider.Add(typeof(IXmlLineInfoProvider), new XmlLineInfoProvider(new XmlLineInfo(95, 95)));
			object obj = ((IMarkupExtension)staticResourceExtension).ProvideValue((IServiceProvider)xamlServiceProvider);
			boxView.BackgroundColor = (Color)obj;
			VisualDiagnostics.RegisterSourceInfo(obj, new Uri("Views/NoticeListView.xaml", UriKind.RelativeOrAbsolute), 95, 95);
			boxView.SetValue(VisualElement.HeightRequestProperty, 1.0);
			grid.Children.Add(boxView);
			VisualDiagnostics.RegisterSourceInfo(boxView, new Uri("Views/NoticeListView.xaml", UriKind.RelativeOrAbsolute), 95, 38);
			label4.SetValue(Grid.RowProperty, 3);
			label4.SetValue(Grid.ColumnProperty, 0);
			label4.SetValue(Grid.ColumnSpanProperty, 2);
			staticResourceExtension2.Key = "PageBackgroundColor";
			XamlServiceProvider xamlServiceProvider2 = new XamlServiceProvider();
			Type typeFromHandle3 = typeof(IProvideValueTarget);
			int length2;
			object[] array2 = new object[(length2 = parentValues.Length) + 4];
			Array.Copy(parentValues, 0, array2, 4, length2);
			array2[0] = label4;
			array2[1] = grid;
			array2[2] = stackLayout;
			array2[3] = viewCell;
			object service2;
			xamlServiceProvider2.Add(typeFromHandle3, service2 = new SimpleValueTargetProvider(array2, VisualElement.BackgroundColorProperty, nameScope));
			xamlServiceProvider2.Add(typeof(IReferenceProvider), service2);
			Type typeFromHandle4 = typeof(IXamlTypeResolver);
			XmlNamespaceResolver xmlNamespaceResolver2 = new XmlNamespaceResolver();
			xmlNamespaceResolver2.Add("", "http://xamarin.com/schemas/2014/forms");
			xmlNamespaceResolver2.Add("x", "http://schemas.microsoft.com/winfx/2009/xaml");
			xmlNamespaceResolver2.Add("effect", "clr-namespace:NHL.Views.Effect");
			xamlServiceProvider2.Add(typeFromHandle4, new XamlTypeResolver(xmlNamespaceResolver2, typeof(_003CInitializeComponent_003E_anonXamlCDataTemplate_1).GetTypeInfo().Assembly));
			xamlServiceProvider2.Add(typeof(IXmlLineInfoProvider), new XmlLineInfoProvider(new XmlLineInfo(96, 93)));
			object obj2 = ((IMarkupExtension)staticResourceExtension2).ProvideValue((IServiceProvider)xamlServiceProvider2);
			label4.BackgroundColor = (Color)obj2;
			VisualDiagnostics.RegisterSourceInfo(obj2, new Uri("Views/NoticeListView.xaml", UriKind.RelativeOrAbsolute), 96, 93);
			grid.Children.Add(label4);
			VisualDiagnostics.RegisterSourceInfo(label4, new Uri("Views/NoticeListView.xaml", UriKind.RelativeOrAbsolute), 96, 38);
			stackLayout.Children.Add(grid);
			VisualDiagnostics.RegisterSourceInfo(grid, new Uri("Views/NoticeListView.xaml", UriKind.RelativeOrAbsolute), 56, 34);
			viewCell.View = stackLayout;
			VisualDiagnostics.RegisterSourceInfo(stackLayout, new Uri("Views/NoticeListView.xaml", UriKind.RelativeOrAbsolute), 55, 30);
			return viewCell;
		}
	}

	public NoticeListView()
	{
		InitializeComponent();
	}

	[GeneratedCode("Xamarin.Forms.Build.Tasks.XamlG", "2.0.0.0")]
	private void InitializeComponent()
	{
		if (ResourceLoader.CanProvideContentFor(new ResourceLoader.ResourceLoadingQuery
		{
			AssemblyName = typeof(NoticeListView).GetTypeInfo().Assembly.GetName(),
			ResourcePath = "Views/NoticeListView.xaml",
			Instance = this
		}))
		{
			__InitComponentRuntime();
			return;
		}
		if (XamlLoader.XamlFileProvider != null && XamlLoader.XamlFileProvider(GetType()) != null)
		{
			__InitComponentRuntime();
			return;
		}
		StaticResourceExtension staticResourceExtension = new StaticResourceExtension();
		Color color = Color.FromHex("#EFEFF4");
		Color color2 = Color.FromHex("#CFCFCF");
		ResourceDictionary resourceDictionary = new ResourceDictionary();
		OnPlatform<Thickness> onPlatform = new OnPlatform<Thickness>();
		RowDefinition rowDefinition = new RowDefinition();
		RowDefinition rowDefinition2 = new RowDefinition();
		BindingExtension bindingExtension = new BindingExtension();
		FixedFontSizeLabelEffect fixedFontSizeLabelEffect = new FixedFontSizeLabelEffect();
		Span span = new Span();
		FormattedString formattedString = new FormattedString();
		Label label = new Label();
		BindingExtension bindingExtension2 = new BindingExtension();
		BindingExtension bindingExtension3 = new BindingExtension();
		DataTemplate dataTemplate = new DataTemplate();
		ListView listView = new ListView();
		Grid grid = new Grid();
		NoticeListView noticeListView;
		NameScope nameScope = (NameScope)(NameScope.GetNameScope(noticeListView = this) ?? new NameScope());
		NameScope.SetNameScope(noticeListView, nameScope);
		noticeListView.Resources = resourceDictionary;
		VisualDiagnostics.RegisterSourceInfo(resourceDictionary, new Uri("Views/NoticeListView.xaml", UriKind.RelativeOrAbsolute), 13, 10);
		resourceDictionary.Add("PageBackgroundColor", color);
		resourceDictionary.Add("LineColor", color2);
		noticeListView.SetValue(NavigationPage.HasBackButtonProperty, true);
		noticeListView.SetValue(NavigationPage.BackButtonTitleProperty, "戻る");
		noticeListView.SetValue(Page.TitleProperty, "お知らせ");
		staticResourceExtension.Key = "PageBackgroundColor";
		XamlServiceProvider xamlServiceProvider = new XamlServiceProvider();
		Type typeFromHandle = typeof(IProvideValueTarget);
		object[] array = new object[0 + 1];
		array[0] = noticeListView;
		object service;
		xamlServiceProvider.Add(typeFromHandle, service = new SimpleValueTargetProvider(array, VisualElement.BackgroundColorProperty, nameScope));
		xamlServiceProvider.Add(typeof(IReferenceProvider), service);
		Type typeFromHandle2 = typeof(IXamlTypeResolver);
		XmlNamespaceResolver xmlNamespaceResolver = new XmlNamespaceResolver();
		xmlNamespaceResolver.Add("", "http://xamarin.com/schemas/2014/forms");
		xmlNamespaceResolver.Add("x", "http://schemas.microsoft.com/winfx/2009/xaml");
		xmlNamespaceResolver.Add("effect", "clr-namespace:NHL.Views.Effect");
		xamlServiceProvider.Add(typeFromHandle2, new XamlTypeResolver(xmlNamespaceResolver, typeof(NoticeListView).GetTypeInfo().Assembly));
		xamlServiceProvider.Add(typeof(IXmlLineInfoProvider), new XmlLineInfoProvider(new XmlLineInfo(10, 14)));
		object obj = ((IMarkupExtension)staticResourceExtension).ProvideValue((IServiceProvider)xamlServiceProvider);
		noticeListView.BackgroundColor = (Color)obj;
		VisualDiagnostics.RegisterSourceInfo(obj, new Uri("Views/NoticeListView.xaml", UriKind.RelativeOrAbsolute), 10, 14);
		noticeListView.Resources = resourceDictionary;
		VisualDiagnostics.RegisterSourceInfo(resourceDictionary, new Uri("Views/NoticeListView.xaml", UriKind.RelativeOrAbsolute), 13, 10);
		onPlatform.iOS = new Thickness(0.0, 20.0, 0.0, 10.0);
		onPlatform.Android = new Thickness(0.0, 10.0, 0.0, 10.0);
		noticeListView.SetValue(Page.PaddingProperty, (Thickness)onPlatform);
		VisualDiagnostics.RegisterSourceInfo(onPlatform, new Uri("Views/NoticeListView.xaml", UriKind.RelativeOrAbsolute), 30, 10);
		rowDefinition.SetValue(RowDefinition.HeightProperty, new GridLengthTypeConverter().ConvertFromInvariantString("Auto"));
		((DefinitionCollection<RowDefinition>)grid.GetValue(Grid.RowDefinitionsProperty)).Add(rowDefinition);
		rowDefinition2.SetValue(RowDefinition.HeightProperty, new GridLengthTypeConverter().ConvertFromInvariantString("*"));
		((DefinitionCollection<RowDefinition>)grid.GetValue(Grid.RowDefinitionsProperty)).Add(rowDefinition2);
		label.SetValue(Grid.RowProperty, 0);
		label.SetValue(View.MarginProperty, new Thickness(10.0, 10.0, 10.0, 0.0));
		bindingExtension.Path = "IsNoticeNothing";
		BindingBase binding = ((IMarkupExtension<BindingBase>)bindingExtension).ProvideValue((IServiceProvider)null);
		label.SetBinding(VisualElement.IsVisibleProperty, binding);
		label.Effects.Add(fixedFontSizeLabelEffect);
		VisualDiagnostics.RegisterSourceInfo(fixedFontSizeLabelEffect, new Uri("Views/NoticeListView.xaml", UriKind.RelativeOrAbsolute), 43, 22);
		span.SetValue(Span.TextProperty, "現在、お知らせ情報はありません。");
		formattedString.Spans.Add(span);
		VisualDiagnostics.RegisterSourceInfo(span, new Uri("Views/NoticeListView.xaml", UriKind.RelativeOrAbsolute), 47, 26);
		label.SetValue(Label.FormattedTextProperty, formattedString);
		VisualDiagnostics.RegisterSourceInfo(formattedString, new Uri("Views/NoticeListView.xaml", UriKind.RelativeOrAbsolute), 46, 22);
		grid.Children.Add(label);
		VisualDiagnostics.RegisterSourceInfo(label, new Uri("Views/NoticeListView.xaml", UriKind.RelativeOrAbsolute), 41, 14);
		listView.SetValue(Grid.RowProperty, 1);
		listView.SetValue(ListView.RowHeightProperty, 70);
		bindingExtension2.Path = "NoticeList";
		BindingBase binding2 = ((IMarkupExtension<BindingBase>)bindingExtension2).ProvideValue((IServiceProvider)null);
		listView.SetBinding(ItemsView<Cell>.ItemsSourceProperty, binding2);
		bindingExtension3.Mode = BindingMode.TwoWay;
		bindingExtension3.Path = "SelectedNotice";
		BindingBase binding3 = ((IMarkupExtension<BindingBase>)bindingExtension3).ProvideValue((IServiceProvider)null);
		listView.SetBinding(ListView.SelectedItemProperty, binding3);
		listView.SetValue(ListView.SelectionModeProperty, ListViewSelectionMode.Single);
		object[] array2 = new object[0 + 4];
		array2[0] = dataTemplate;
		array2[1] = listView;
		array2[2] = grid;
		array2[3] = noticeListView;
		object[] parentValues = array2;
		NoticeListView root = noticeListView;
		((IDataTemplate)dataTemplate).LoadTemplate = delegate
		{
			ColumnDefinition columnDefinition = new ColumnDefinition();
			ColumnDefinition columnDefinition2 = new ColumnDefinition();
			RowDefinition rowDefinition3 = new RowDefinition();
			RowDefinition rowDefinition4 = new RowDefinition();
			RowDefinition rowDefinition5 = new RowDefinition();
			RowDefinition rowDefinition6 = new RowDefinition();
			FixedFontSizeLabelEffect fixedFontSizeLabelEffect2 = new FixedFontSizeLabelEffect();
			BindingExtension bindingExtension4 = new BindingExtension();
			Span span2 = new Span();
			BindingExtension bindingExtension5 = new BindingExtension();
			Span span3 = new Span();
			FormattedString formattedString2 = new FormattedString();
			Label label2 = new Label();
			BindingExtension bindingExtension6 = new BindingExtension();
			FixedFontSizeLabelEffect fixedFontSizeLabelEffect3 = new FixedFontSizeLabelEffect();
			Label label3 = new Label();
			FixedFontSizeLabelEffect fixedFontSizeLabelEffect4 = new FixedFontSizeLabelEffect();
			Label label4 = new Label();
			StaticResourceExtension staticResourceExtension2 = new StaticResourceExtension();
			BoxView boxView = new BoxView();
			StaticResourceExtension staticResourceExtension3 = new StaticResourceExtension();
			Label label5 = new Label();
			Grid grid2 = new Grid();
			StackLayout stackLayout = new StackLayout();
			ViewCell viewCell = new ViewCell();
			NameScope nameScope2 = new NameScope();
			NameScope.SetNameScope(viewCell, nameScope2);
			stackLayout.SetValue(View.HorizontalOptionsProperty, LayoutOptions.Start);
			grid2.SetValue(Grid.RowSpacingProperty, 0.0);
			grid2.SetValue(Grid.ColumnSpacingProperty, 0.0);
			grid2.SetValue(VisualElement.BackgroundColorProperty, Color.White);
			grid2.SetValue(View.HorizontalOptionsProperty, LayoutOptions.Fill);
			grid2.SetValue(View.VerticalOptionsProperty, LayoutOptions.Center);
			columnDefinition.SetValue(ColumnDefinition.WidthProperty, new GridLengthTypeConverter().ConvertFromInvariantString("*"));
			((DefinitionCollection<ColumnDefinition>)grid2.GetValue(Grid.ColumnDefinitionsProperty)).Add(columnDefinition);
			columnDefinition2.SetValue(ColumnDefinition.WidthProperty, new GridLengthTypeConverter().ConvertFromInvariantString("30"));
			((DefinitionCollection<ColumnDefinition>)grid2.GetValue(Grid.ColumnDefinitionsProperty)).Add(columnDefinition2);
			rowDefinition3.SetValue(RowDefinition.HeightProperty, new GridLengthTypeConverter().ConvertFromInvariantString("30"));
			((DefinitionCollection<RowDefinition>)grid2.GetValue(Grid.RowDefinitionsProperty)).Add(rowDefinition3);
			rowDefinition4.SetValue(RowDefinition.HeightProperty, new GridLengthTypeConverter().ConvertFromInvariantString("35"));
			((DefinitionCollection<RowDefinition>)grid2.GetValue(Grid.RowDefinitionsProperty)).Add(rowDefinition4);
			rowDefinition5.SetValue(RowDefinition.HeightProperty, new GridLengthTypeConverter().ConvertFromInvariantString("Auto"));
			((DefinitionCollection<RowDefinition>)grid2.GetValue(Grid.RowDefinitionsProperty)).Add(rowDefinition5);
			rowDefinition6.SetValue(RowDefinition.HeightProperty, new GridLengthTypeConverter().ConvertFromInvariantString("*"));
			((DefinitionCollection<RowDefinition>)grid2.GetValue(Grid.RowDefinitionsProperty)).Add(rowDefinition6);
			label2.SetValue(Grid.RowProperty, 0);
			label2.SetValue(Grid.ColumnProperty, 0);
			label2.SetValue(View.MarginProperty, new Thickness(10.0, 5.0, 0.0, 0.0));
			label2.Effects.Add(fixedFontSizeLabelEffect2);
			VisualDiagnostics.RegisterSourceInfo(fixedFontSizeLabelEffect2, new Uri("Views/NoticeListView.xaml", UriKind.RelativeOrAbsolute), 70, 46);
			bindingExtension4.StringFormat = "{0:yyyy/MM/dd(ddd)}";
			bindingExtension4.Path = "Notice.ExpiryDateFrom";
			BindingBase binding4 = ((IMarkupExtension<BindingBase>)bindingExtension4).ProvideValue((IServiceProvider)null);
			span2.SetBinding(Span.TextProperty, binding4);
			span2.SetValue(Span.FontAttributesProperty, new FontAttributesConverter().ConvertFromInvariantString("Bold"));
			formattedString2.Spans.Add(span2);
			VisualDiagnostics.RegisterSourceInfo(span2, new Uri("Views/NoticeListView.xaml", UriKind.RelativeOrAbsolute), 75, 50);
			bindingExtension5.StringFormat = " {0}";
			bindingExtension5.Path = "Hospital.FacilitiesName";
			BindingBase binding5 = ((IMarkupExtension<BindingBase>)bindingExtension5).ProvideValue((IServiceProvider)null);
			span3.SetBinding(Span.TextProperty, binding5);
			span3.SetValue(Span.FontAttributesProperty, new FontAttributesConverter().ConvertFromInvariantString("Bold"));
			formattedString2.Spans.Add(span3);
			VisualDiagnostics.RegisterSourceInfo(span3, new Uri("Views/NoticeListView.xaml", UriKind.RelativeOrAbsolute), 77, 50);
			label2.SetValue(Label.FormattedTextProperty, formattedString2);
			VisualDiagnostics.RegisterSourceInfo(formattedString2, new Uri("Views/NoticeListView.xaml", UriKind.RelativeOrAbsolute), 73, 46);
			grid2.Children.Add(label2);
			VisualDiagnostics.RegisterSourceInfo(label2, new Uri("Views/NoticeListView.xaml", UriKind.RelativeOrAbsolute), 68, 38);
			label3.SetValue(Grid.RowProperty, 1);
			label3.SetValue(Grid.ColumnProperty, 0);
			bindingExtension6.Path = "Notice.Title";
			BindingBase binding6 = ((IMarkupExtension<BindingBase>)bindingExtension6).ProvideValue((IServiceProvider)null);
			label3.SetBinding(Label.TextProperty, binding6);
			label3.SetValue(View.MarginProperty, new Thickness(15.0, 5.0, 0.0, 0.0));
			label3.SetValue(Label.LineBreakModeProperty, LineBreakMode.TailTruncation);
			label3.Effects.Add(fixedFontSizeLabelEffect3);
			VisualDiagnostics.RegisterSourceInfo(fixedFontSizeLabelEffect3, new Uri("Views/NoticeListView.xaml", UriKind.RelativeOrAbsolute), 85, 46);
			grid2.Children.Add(label3);
			VisualDiagnostics.RegisterSourceInfo(label3, new Uri("Views/NoticeListView.xaml", UriKind.RelativeOrAbsolute), 83, 38);
			label4.SetValue(Grid.RowProperty, 0);
			label4.SetValue(Grid.ColumnProperty, 1);
			label4.SetValue(Grid.RowSpanProperty, 3);
			label4.SetValue(Label.TextProperty, "＞");
			label4.SetValue(View.HorizontalOptionsProperty, LayoutOptions.End);
			label4.SetValue(Label.VerticalTextAlignmentProperty, new TextAlignmentConverter().ConvertFromInvariantString("Center"));
			label4.SetValue(View.MarginProperty, new Thickness(0.0, 0.0, 10.0, 0.0));
			label4.Effects.Add(fixedFontSizeLabelEffect4);
			VisualDiagnostics.RegisterSourceInfo(fixedFontSizeLabelEffect4, new Uri("Views/NoticeListView.xaml", UriKind.RelativeOrAbsolute), 92, 46);
			grid2.Children.Add(label4);
			VisualDiagnostics.RegisterSourceInfo(label4, new Uri("Views/NoticeListView.xaml", UriKind.RelativeOrAbsolute), 90, 38);
			boxView.SetValue(Grid.RowProperty, 2);
			boxView.SetValue(Grid.ColumnProperty, 0);
			boxView.SetValue(Grid.ColumnSpanProperty, 2);
			staticResourceExtension2.Key = "LineColor";
			XamlServiceProvider xamlServiceProvider2 = new XamlServiceProvider();
			Type typeFromHandle3 = typeof(IProvideValueTarget);
			int length;
			object[] array3 = new object[(length = parentValues.Length) + 4];
			Array.Copy(parentValues, 0, array3, 4, length);
			array3[0] = boxView;
			array3[1] = grid2;
			array3[2] = stackLayout;
			array3[3] = viewCell;
			object service2;
			xamlServiceProvider2.Add(typeFromHandle3, service2 = new SimpleValueTargetProvider(array3, VisualElement.BackgroundColorProperty, nameScope2));
			xamlServiceProvider2.Add(typeof(IReferenceProvider), service2);
			Type typeFromHandle4 = typeof(IXamlTypeResolver);
			XmlNamespaceResolver xmlNamespaceResolver2 = new XmlNamespaceResolver();
			xmlNamespaceResolver2.Add("", "http://xamarin.com/schemas/2014/forms");
			xmlNamespaceResolver2.Add("x", "http://schemas.microsoft.com/winfx/2009/xaml");
			xmlNamespaceResolver2.Add("effect", "clr-namespace:NHL.Views.Effect");
			xamlServiceProvider2.Add(typeFromHandle4, new XamlTypeResolver(xmlNamespaceResolver2, typeof(_003CInitializeComponent_003E_anonXamlCDataTemplate_1).GetTypeInfo().Assembly));
			xamlServiceProvider2.Add(typeof(IXmlLineInfoProvider), new XmlLineInfoProvider(new XmlLineInfo(95, 95)));
			object obj2 = ((IMarkupExtension)staticResourceExtension2).ProvideValue((IServiceProvider)xamlServiceProvider2);
			boxView.BackgroundColor = (Color)obj2;
			VisualDiagnostics.RegisterSourceInfo(obj2, new Uri("Views/NoticeListView.xaml", UriKind.RelativeOrAbsolute), 95, 95);
			boxView.SetValue(VisualElement.HeightRequestProperty, 1.0);
			grid2.Children.Add(boxView);
			VisualDiagnostics.RegisterSourceInfo(boxView, new Uri("Views/NoticeListView.xaml", UriKind.RelativeOrAbsolute), 95, 38);
			label5.SetValue(Grid.RowProperty, 3);
			label5.SetValue(Grid.ColumnProperty, 0);
			label5.SetValue(Grid.ColumnSpanProperty, 2);
			staticResourceExtension3.Key = "PageBackgroundColor";
			XamlServiceProvider xamlServiceProvider3 = new XamlServiceProvider();
			Type typeFromHandle5 = typeof(IProvideValueTarget);
			int length2;
			object[] array4 = new object[(length2 = parentValues.Length) + 4];
			Array.Copy(parentValues, 0, array4, 4, length2);
			array4[0] = label5;
			array4[1] = grid2;
			array4[2] = stackLayout;
			array4[3] = viewCell;
			object service3;
			xamlServiceProvider3.Add(typeFromHandle5, service3 = new SimpleValueTargetProvider(array4, VisualElement.BackgroundColorProperty, nameScope2));
			xamlServiceProvider3.Add(typeof(IReferenceProvider), service3);
			Type typeFromHandle6 = typeof(IXamlTypeResolver);
			XmlNamespaceResolver xmlNamespaceResolver3 = new XmlNamespaceResolver();
			xmlNamespaceResolver3.Add("", "http://xamarin.com/schemas/2014/forms");
			xmlNamespaceResolver3.Add("x", "http://schemas.microsoft.com/winfx/2009/xaml");
			xmlNamespaceResolver3.Add("effect", "clr-namespace:NHL.Views.Effect");
			xamlServiceProvider3.Add(typeFromHandle6, new XamlTypeResolver(xmlNamespaceResolver3, typeof(_003CInitializeComponent_003E_anonXamlCDataTemplate_1).GetTypeInfo().Assembly));
			xamlServiceProvider3.Add(typeof(IXmlLineInfoProvider), new XmlLineInfoProvider(new XmlLineInfo(96, 93)));
			object obj3 = ((IMarkupExtension)staticResourceExtension3).ProvideValue((IServiceProvider)xamlServiceProvider3);
			label5.BackgroundColor = (Color)obj3;
			VisualDiagnostics.RegisterSourceInfo(obj3, new Uri("Views/NoticeListView.xaml", UriKind.RelativeOrAbsolute), 96, 93);
			grid2.Children.Add(label5);
			VisualDiagnostics.RegisterSourceInfo(label5, new Uri("Views/NoticeListView.xaml", UriKind.RelativeOrAbsolute), 96, 38);
			stackLayout.Children.Add(grid2);
			VisualDiagnostics.RegisterSourceInfo(grid2, new Uri("Views/NoticeListView.xaml", UriKind.RelativeOrAbsolute), 56, 34);
			viewCell.View = stackLayout;
			VisualDiagnostics.RegisterSourceInfo(stackLayout, new Uri("Views/NoticeListView.xaml", UriKind.RelativeOrAbsolute), 55, 30);
			return viewCell;
		};
		listView.SetValue(ItemsView<Cell>.ItemTemplateProperty, dataTemplate);
		VisualDiagnostics.RegisterSourceInfo(dataTemplate, new Uri("Views/NoticeListView.xaml", UriKind.RelativeOrAbsolute), 53, 22);
		grid.Children.Add(listView);
		VisualDiagnostics.RegisterSourceInfo(listView, new Uri("Views/NoticeListView.xaml", UriKind.RelativeOrAbsolute), 51, 14);
		noticeListView.SetValue(ContentPage.ContentProperty, grid);
		VisualDiagnostics.RegisterSourceInfo(grid, new Uri("Views/NoticeListView.xaml", UriKind.RelativeOrAbsolute), 36, 10);
		VisualDiagnostics.RegisterSourceInfo(noticeListView, new Uri("Views/NoticeListView.xaml", UriKind.RelativeOrAbsolute), 3, 2);
	}

	private void __InitComponentRuntime()
	{
		this.LoadFromXaml(typeof(NoticeListView));
	}
}
