using System;
using System.CodeDom.Compiler;
using System.Reflection;
using Caliburn.Micro.Xamarin.Forms;
using NHL.Views.Effect;
using NHL.Views.Renderer;
using Xamarin.Forms;
using Xamarin.Forms.Internals;
using Xamarin.Forms.Xaml;
using Xamarin.Forms.Xaml.Diagnostics;
using Xamarin.Forms.Xaml.Internals;

namespace NHL.Views;

[XamlCompilation(XamlCompilationOptions.Compile)]
[XamlFilePath("Views/RecordEditView.xaml")]
public class RecordEditView : ContentPage
{
	[GeneratedCode("Xamarin.Forms.Build.Tasks.XamlG", "2.0.0.0")]
	private DatePickerView MeasurementAtPicker;

	public RecordEditView()
	{
		InitializeComponent();
	}

	[GeneratedCode("Xamarin.Forms.Build.Tasks.XamlG", "2.0.0.0")]
	private void InitializeComponent()
	{
		if (ResourceLoader.CanProvideContentFor(new ResourceLoader.ResourceLoadingQuery
		{
			AssemblyName = typeof(RecordEditView).GetTypeInfo().Assembly.GetName(),
			ResourcePath = "Views/RecordEditView.xaml",
			Instance = this
		}))
		{
			__InitComponentRuntime();
			return;
		}
		if (XamlLoader.XamlFileProvider != null && XamlLoader.XamlFileProvider(GetType()) != null)
		{
			__InitComponentRuntime();
			return;
		}
		RowDefinition rowDefinition = new RowDefinition();
		RowDefinition rowDefinition2 = new RowDefinition();
		RowDefinition rowDefinition3 = new RowDefinition();
		RowDefinition rowDefinition4 = new RowDefinition();
		RowDefinition rowDefinition5 = new RowDefinition();
		RowDefinition rowDefinition6 = new RowDefinition();
		ColumnDefinition columnDefinition = new ColumnDefinition();
		ColumnDefinition columnDefinition2 = new ColumnDefinition();
		FixedFontSizeLabelEffect fixedFontSizeLabelEffect = new FixedFontSizeLabelEffect();
		Label label = new Label();
		Grid grid = new Grid();
		BindingExtension bindingExtension = new BindingExtension();
		BindingExtension bindingExtension2 = new BindingExtension();
		FixedFontSizeTextBoxEffect fixedFontSizeTextBoxEffect = new FixedFontSizeTextBoxEffect();
		DatePickerView datePickerView = new DatePickerView();
		Grid grid2 = new Grid();
		FixedFontSizeLabelEffect fixedFontSizeLabelEffect2 = new FixedFontSizeLabelEffect();
		Label label2 = new Label();
		Grid grid3 = new Grid();
		FixedFontSizeLabelEffect fixedFontSizeLabelEffect3 = new FixedFontSizeLabelEffect();
		Label label3 = new Label();
		Grid grid4 = new Grid();
		FixedFontSizeLabelEffect fixedFontSizeLabelEffect4 = new FixedFontSizeLabelEffect();
		Label label4 = new Label();
		Grid grid5 = new Grid();
		BindingExtension bindingExtension3 = new BindingExtension();
		FixedFontSizeTextBoxEffect fixedFontSizeTextBoxEffect2 = new FixedFontSizeTextBoxEffect();
		Entry entry = new Entry();
		Grid grid6 = new Grid();
		FixedFontSizeLabelEffect fixedFontSizeLabelEffect5 = new FixedFontSizeLabelEffect();
		Label label5 = new Label();
		BindingExtension bindingExtension4 = new BindingExtension();
		FixedFontSizeLabelEffect fixedFontSizeLabelEffect6 = new FixedFontSizeLabelEffect();
		Label label6 = new Label();
		FixedFontSizeButtonEffect fixedFontSizeButtonEffect = new FixedFontSizeButtonEffect();
		Button button = new Button();
		BindingExtension bindingExtension5 = new BindingExtension();
		FixedFontSizeLabelEffect fixedFontSizeLabelEffect7 = new FixedFontSizeLabelEffect();
		Label label7 = new Label();
		BindingExtension bindingExtension6 = new BindingExtension();
		FixedFontSizeButtonEffect fixedFontSizeButtonEffect2 = new FixedFontSizeButtonEffect();
		Button button2 = new Button();
		Grid grid7 = new Grid();
		Grid grid8 = new Grid();
		RecordEditView recordEditView;
		NameScope nameScope = (NameScope)(NameScope.GetNameScope(recordEditView = this) ?? new NameScope());
		NameScope.SetNameScope(recordEditView, nameScope);
		((INameScope)nameScope).RegisterName("MeasurementAtPicker", (object)datePickerView);
		if (datePickerView.StyleId == null)
		{
			datePickerView.StyleId = "MeasurementAtPicker";
		}
		MeasurementAtPicker = datePickerView;
		recordEditView.SetValue(NavigationPage.HasBackButtonProperty, true);
		recordEditView.SetValue(NavigationPage.BackButtonTitleProperty, "戻る");
		recordEditView.SetValue(Page.TitleProperty, "記録の編集");
		rowDefinition.SetValue(RowDefinition.HeightProperty, new GridLengthTypeConverter().ConvertFromInvariantString("Auto"));
		((DefinitionCollection<RowDefinition>)grid7.GetValue(Grid.RowDefinitionsProperty)).Add(rowDefinition);
		rowDefinition2.SetValue(RowDefinition.HeightProperty, new GridLengthTypeConverter().ConvertFromInvariantString("Auto"));
		((DefinitionCollection<RowDefinition>)grid7.GetValue(Grid.RowDefinitionsProperty)).Add(rowDefinition2);
		rowDefinition3.SetValue(RowDefinition.HeightProperty, new GridLengthTypeConverter().ConvertFromInvariantString("Auto"));
		((DefinitionCollection<RowDefinition>)grid7.GetValue(Grid.RowDefinitionsProperty)).Add(rowDefinition3);
		rowDefinition4.SetValue(RowDefinition.HeightProperty, new GridLengthTypeConverter().ConvertFromInvariantString("Auto"));
		((DefinitionCollection<RowDefinition>)grid7.GetValue(Grid.RowDefinitionsProperty)).Add(rowDefinition4);
		rowDefinition5.SetValue(RowDefinition.HeightProperty, new GridLengthTypeConverter().ConvertFromInvariantString("Auto"));
		((DefinitionCollection<RowDefinition>)grid7.GetValue(Grid.RowDefinitionsProperty)).Add(rowDefinition5);
		rowDefinition6.SetValue(RowDefinition.HeightProperty, new GridLengthTypeConverter().ConvertFromInvariantString("*"));
		((DefinitionCollection<RowDefinition>)grid7.GetValue(Grid.RowDefinitionsProperty)).Add(rowDefinition6);
		columnDefinition.SetValue(ColumnDefinition.WidthProperty, new GridLengthTypeConverter().ConvertFromInvariantString("*"));
		((DefinitionCollection<ColumnDefinition>)grid7.GetValue(Grid.ColumnDefinitionsProperty)).Add(columnDefinition);
		columnDefinition2.SetValue(ColumnDefinition.WidthProperty, new GridLengthTypeConverter().ConvertFromInvariantString("*"));
		((DefinitionCollection<ColumnDefinition>)grid7.GetValue(Grid.ColumnDefinitionsProperty)).Add(columnDefinition2);
		grid.SetValue(Grid.RowProperty, 0);
		grid.SetValue(Grid.ColumnProperty, 0);
		grid.SetValue(VisualElement.BackgroundColorProperty, Color.Transparent);
		grid.SetValue(Xamarin.Forms.View.MarginProperty, new Thickness(10.0, 5.0, 0.0, 5.0));
		label.SetValue(Label.TextColorProperty, Color.Gray);
		BindableProperty fontSizeProperty = Label.FontSizeProperty;
		FontSizeConverter fontSizeConverter = new FontSizeConverter();
		XamlServiceProvider xamlServiceProvider = new XamlServiceProvider();
		Type typeFromHandle = typeof(IProvideValueTarget);
		object[] array = new object[0 + 5];
		array[0] = label;
		array[1] = grid;
		array[2] = grid7;
		array[3] = grid8;
		array[4] = recordEditView;
		object service;
		xamlServiceProvider.Add(typeFromHandle, service = new SimpleValueTargetProvider(array, Label.FontSizeProperty, nameScope));
		xamlServiceProvider.Add(typeof(IReferenceProvider), service);
		Type typeFromHandle2 = typeof(IXamlTypeResolver);
		XmlNamespaceResolver xmlNamespaceResolver = new XmlNamespaceResolver();
		xmlNamespaceResolver.Add("", "http://xamarin.com/schemas/2014/forms");
		xmlNamespaceResolver.Add("x", "http://schemas.microsoft.com/winfx/2009/xaml");
		xmlNamespaceResolver.Add("calx", "clr-namespace:Caliburn.Micro.Xamarin.Forms;assembly=Caliburn.Micro.Platform.Xamarin.Forms");
		xmlNamespaceResolver.Add("effect", "clr-namespace:NHL.Views.Effect");
		xmlNamespaceResolver.Add("renderer", "clr-namespace:NHL.Views.Renderer");
		xmlNamespaceResolver.Add("system", "clr-namespace:System;assembly=System.Runtime.Extensions");
		xamlServiceProvider.Add(typeFromHandle2, new XamlTypeResolver(xmlNamespaceResolver, typeof(RecordEditView).GetTypeInfo().Assembly));
		xamlServiceProvider.Add(typeof(IXmlLineInfoProvider), new XmlLineInfoProvider(new XmlLineInfo(30, 41)));
		label.SetValue(fontSizeProperty, ((IExtendedTypeConverter)fontSizeConverter).ConvertFromInvariantString("Large", (IServiceProvider)xamlServiceProvider));
		label.SetValue(Label.HorizontalTextAlignmentProperty, new TextAlignmentConverter().ConvertFromInvariantString("Start"));
		label.SetValue(Label.VerticalTextAlignmentProperty, new TextAlignmentConverter().ConvertFromInvariantString("Center"));
		label.SetValue(VisualElement.BackgroundColorProperty, Color.Transparent);
		label.SetValue(Label.TextProperty, "測定日");
		label.Effects.Add(fixedFontSizeLabelEffect);
		VisualDiagnostics.RegisterSourceInfo(fixedFontSizeLabelEffect, new Uri("Views/RecordEditView.xaml", UriKind.RelativeOrAbsolute), 32, 26);
		grid.Children.Add(label);
		VisualDiagnostics.RegisterSourceInfo(label, new Uri("Views/RecordEditView.xaml", UriKind.RelativeOrAbsolute), 30, 18);
		grid7.Children.Add(grid);
		VisualDiagnostics.RegisterSourceInfo(grid, new Uri("Views/RecordEditView.xaml", UriKind.RelativeOrAbsolute), 29, 14);
		grid2.SetValue(Grid.RowProperty, 0);
		grid2.SetValue(Grid.ColumnProperty, 1);
		grid2.SetValue(VisualElement.BackgroundColorProperty, Color.Transparent);
		grid2.SetValue(Xamarin.Forms.View.MarginProperty, new Thickness(0.0, 5.0, 10.0, 5.0));
		datePickerView.SetValue(DatePicker.FormatProperty, "yyyy/MM/dd");
		bindingExtension.Mode = BindingMode.TwoWay;
		bindingExtension.Path = "MeasurementAt";
		BindingBase binding = ((IMarkupExtension<BindingBase>)bindingExtension).ProvideValue((IServiceProvider)null);
		datePickerView.SetBinding(DatePickerView.NullableDateProperty, binding);
		bindingExtension2.Mode = BindingMode.OneWay;
		bindingExtension2.Path = "IsEnableMeasurementAt";
		BindingBase binding2 = ((IMarkupExtension<BindingBase>)bindingExtension2).ProvideValue((IServiceProvider)null);
		datePickerView.SetBinding(VisualElement.IsEnabledProperty, binding2);
		datePickerView.Effects.Add(fixedFontSizeTextBoxEffect);
		VisualDiagnostics.RegisterSourceInfo(fixedFontSizeTextBoxEffect, new Uri("Views/RecordEditView.xaml", UriKind.RelativeOrAbsolute), 39, 26);
		grid2.Children.Add(datePickerView);
		VisualDiagnostics.RegisterSourceInfo(datePickerView, new Uri("Views/RecordEditView.xaml", UriKind.RelativeOrAbsolute), 37, 18);
		grid7.Children.Add(grid2);
		VisualDiagnostics.RegisterSourceInfo(grid2, new Uri("Views/RecordEditView.xaml", UriKind.RelativeOrAbsolute), 36, 14);
		grid3.SetValue(Grid.RowProperty, 1);
		grid3.SetValue(Grid.ColumnProperty, 0);
		grid3.SetValue(VisualElement.BackgroundColorProperty, Color.Transparent);
		grid3.SetValue(Xamarin.Forms.View.MarginProperty, new Thickness(10.0, 5.0, 0.0, 5.0));
		label2.SetValue(Label.TextColorProperty, Color.Gray);
		BindableProperty fontSizeProperty2 = Label.FontSizeProperty;
		FontSizeConverter fontSizeConverter2 = new FontSizeConverter();
		XamlServiceProvider xamlServiceProvider2 = new XamlServiceProvider();
		Type typeFromHandle3 = typeof(IProvideValueTarget);
		object[] array2 = new object[0 + 5];
		array2[0] = label2;
		array2[1] = grid3;
		array2[2] = grid7;
		array2[3] = grid8;
		array2[4] = recordEditView;
		object service2;
		xamlServiceProvider2.Add(typeFromHandle3, service2 = new SimpleValueTargetProvider(array2, Label.FontSizeProperty, nameScope));
		xamlServiceProvider2.Add(typeof(IReferenceProvider), service2);
		Type typeFromHandle4 = typeof(IXamlTypeResolver);
		XmlNamespaceResolver xmlNamespaceResolver2 = new XmlNamespaceResolver();
		xmlNamespaceResolver2.Add("", "http://xamarin.com/schemas/2014/forms");
		xmlNamespaceResolver2.Add("x", "http://schemas.microsoft.com/winfx/2009/xaml");
		xmlNamespaceResolver2.Add("calx", "clr-namespace:Caliburn.Micro.Xamarin.Forms;assembly=Caliburn.Micro.Platform.Xamarin.Forms");
		xmlNamespaceResolver2.Add("effect", "clr-namespace:NHL.Views.Effect");
		xmlNamespaceResolver2.Add("renderer", "clr-namespace:NHL.Views.Renderer");
		xmlNamespaceResolver2.Add("system", "clr-namespace:System;assembly=System.Runtime.Extensions");
		xamlServiceProvider2.Add(typeFromHandle4, new XamlTypeResolver(xmlNamespaceResolver2, typeof(RecordEditView).GetTypeInfo().Assembly));
		xamlServiceProvider2.Add(typeof(IXmlLineInfoProvider), new XmlLineInfoProvider(new XmlLineInfo(45, 41)));
		label2.SetValue(fontSizeProperty2, ((IExtendedTypeConverter)fontSizeConverter2).ConvertFromInvariantString("Large", (IServiceProvider)xamlServiceProvider2));
		label2.SetValue(Label.HorizontalTextAlignmentProperty, new TextAlignmentConverter().ConvertFromInvariantString("Start"));
		label2.SetValue(Label.VerticalTextAlignmentProperty, new TextAlignmentConverter().ConvertFromInvariantString("Center"));
		label2.SetValue(VisualElement.BackgroundColorProperty, Color.Transparent);
		label2.SetValue(Label.TextProperty, "測定区分");
		label2.Effects.Add(fixedFontSizeLabelEffect2);
		VisualDiagnostics.RegisterSourceInfo(fixedFontSizeLabelEffect2, new Uri("Views/RecordEditView.xaml", UriKind.RelativeOrAbsolute), 47, 26);
		grid3.Children.Add(label2);
		VisualDiagnostics.RegisterSourceInfo(label2, new Uri("Views/RecordEditView.xaml", UriKind.RelativeOrAbsolute), 45, 18);
		grid7.Children.Add(grid3);
		VisualDiagnostics.RegisterSourceInfo(grid3, new Uri("Views/RecordEditView.xaml", UriKind.RelativeOrAbsolute), 44, 14);
		grid4.SetValue(Grid.RowProperty, 1);
		grid4.SetValue(Grid.ColumnProperty, 1);
		grid4.SetValue(VisualElement.BackgroundColorProperty, Color.Transparent);
		grid4.SetValue(Xamarin.Forms.View.MarginProperty, new Thickness(0.0, 5.0, 10.0, 5.0));
		label3.SetValue(Label.TextColorProperty, Color.Black);
		BindableProperty fontSizeProperty3 = Label.FontSizeProperty;
		FontSizeConverter fontSizeConverter3 = new FontSizeConverter();
		XamlServiceProvider xamlServiceProvider3 = new XamlServiceProvider();
		Type typeFromHandle5 = typeof(IProvideValueTarget);
		object[] array3 = new object[0 + 5];
		array3[0] = label3;
		array3[1] = grid4;
		array3[2] = grid7;
		array3[3] = grid8;
		array3[4] = recordEditView;
		object service3;
		xamlServiceProvider3.Add(typeFromHandle5, service3 = new SimpleValueTargetProvider(array3, Label.FontSizeProperty, nameScope));
		xamlServiceProvider3.Add(typeof(IReferenceProvider), service3);
		Type typeFromHandle6 = typeof(IXamlTypeResolver);
		XmlNamespaceResolver xmlNamespaceResolver3 = new XmlNamespaceResolver();
		xmlNamespaceResolver3.Add("", "http://xamarin.com/schemas/2014/forms");
		xmlNamespaceResolver3.Add("x", "http://schemas.microsoft.com/winfx/2009/xaml");
		xmlNamespaceResolver3.Add("calx", "clr-namespace:Caliburn.Micro.Xamarin.Forms;assembly=Caliburn.Micro.Platform.Xamarin.Forms");
		xmlNamespaceResolver3.Add("effect", "clr-namespace:NHL.Views.Effect");
		xmlNamespaceResolver3.Add("renderer", "clr-namespace:NHL.Views.Renderer");
		xmlNamespaceResolver3.Add("system", "clr-namespace:System;assembly=System.Runtime.Extensions");
		xamlServiceProvider3.Add(typeFromHandle6, new XamlTypeResolver(xmlNamespaceResolver3, typeof(RecordEditView).GetTypeInfo().Assembly));
		xamlServiceProvider3.Add(typeof(IXmlLineInfoProvider), new XmlLineInfoProvider(new XmlLineInfo(53, 42)));
		label3.SetValue(fontSizeProperty3, ((IExtendedTypeConverter)fontSizeConverter3).ConvertFromInvariantString("Large", (IServiceProvider)xamlServiceProvider3));
		label3.SetValue(Label.HorizontalTextAlignmentProperty, new TextAlignmentConverter().ConvertFromInvariantString("Start"));
		label3.SetValue(VisualElement.BackgroundColorProperty, Color.Transparent);
		label3.SetValue(Label.TextProperty, "歩数");
		label3.Effects.Add(fixedFontSizeLabelEffect3);
		VisualDiagnostics.RegisterSourceInfo(fixedFontSizeLabelEffect3, new Uri("Views/RecordEditView.xaml", UriKind.RelativeOrAbsolute), 55, 26);
		grid4.Children.Add(label3);
		VisualDiagnostics.RegisterSourceInfo(label3, new Uri("Views/RecordEditView.xaml", UriKind.RelativeOrAbsolute), 53, 18);
		grid7.Children.Add(grid4);
		VisualDiagnostics.RegisterSourceInfo(grid4, new Uri("Views/RecordEditView.xaml", UriKind.RelativeOrAbsolute), 52, 14);
		grid5.SetValue(Grid.RowProperty, 2);
		grid5.SetValue(Grid.ColumnProperty, 0);
		grid5.SetValue(VisualElement.BackgroundColorProperty, Color.Transparent);
		grid5.SetValue(Xamarin.Forms.View.MarginProperty, new Thickness(10.0, 5.0, 0.0, 5.0));
		label4.SetValue(Label.TextColorProperty, Color.Gray);
		BindableProperty fontSizeProperty4 = Label.FontSizeProperty;
		FontSizeConverter fontSizeConverter4 = new FontSizeConverter();
		XamlServiceProvider xamlServiceProvider4 = new XamlServiceProvider();
		Type typeFromHandle7 = typeof(IProvideValueTarget);
		object[] array4 = new object[0 + 5];
		array4[0] = label4;
		array4[1] = grid5;
		array4[2] = grid7;
		array4[3] = grid8;
		array4[4] = recordEditView;
		object service4;
		xamlServiceProvider4.Add(typeFromHandle7, service4 = new SimpleValueTargetProvider(array4, Label.FontSizeProperty, nameScope));
		xamlServiceProvider4.Add(typeof(IReferenceProvider), service4);
		Type typeFromHandle8 = typeof(IXamlTypeResolver);
		XmlNamespaceResolver xmlNamespaceResolver4 = new XmlNamespaceResolver();
		xmlNamespaceResolver4.Add("", "http://xamarin.com/schemas/2014/forms");
		xmlNamespaceResolver4.Add("x", "http://schemas.microsoft.com/winfx/2009/xaml");
		xmlNamespaceResolver4.Add("calx", "clr-namespace:Caliburn.Micro.Xamarin.Forms;assembly=Caliburn.Micro.Platform.Xamarin.Forms");
		xmlNamespaceResolver4.Add("effect", "clr-namespace:NHL.Views.Effect");
		xmlNamespaceResolver4.Add("renderer", "clr-namespace:NHL.Views.Renderer");
		xmlNamespaceResolver4.Add("system", "clr-namespace:System;assembly=System.Runtime.Extensions");
		xamlServiceProvider4.Add(typeFromHandle8, new XamlTypeResolver(xmlNamespaceResolver4, typeof(RecordEditView).GetTypeInfo().Assembly));
		xamlServiceProvider4.Add(typeof(IXmlLineInfoProvider), new XmlLineInfoProvider(new XmlLineInfo(61, 41)));
		label4.SetValue(fontSizeProperty4, ((IExtendedTypeConverter)fontSizeConverter4).ConvertFromInvariantString("Large", (IServiceProvider)xamlServiceProvider4));
		label4.SetValue(Label.HorizontalTextAlignmentProperty, new TextAlignmentConverter().ConvertFromInvariantString("Start"));
		label4.SetValue(Label.VerticalTextAlignmentProperty, new TextAlignmentConverter().ConvertFromInvariantString("Center"));
		label4.SetValue(VisualElement.BackgroundColorProperty, Color.Transparent);
		label4.SetValue(Label.TextProperty, "測定値");
		label4.Effects.Add(fixedFontSizeLabelEffect4);
		VisualDiagnostics.RegisterSourceInfo(fixedFontSizeLabelEffect4, new Uri("Views/RecordEditView.xaml", UriKind.RelativeOrAbsolute), 63, 26);
		grid5.Children.Add(label4);
		VisualDiagnostics.RegisterSourceInfo(label4, new Uri("Views/RecordEditView.xaml", UriKind.RelativeOrAbsolute), 61, 18);
		grid7.Children.Add(grid5);
		VisualDiagnostics.RegisterSourceInfo(grid5, new Uri("Views/RecordEditView.xaml", UriKind.RelativeOrAbsolute), 60, 14);
		grid6.SetValue(Grid.RowProperty, 2);
		grid6.SetValue(Grid.ColumnProperty, 1);
		grid6.SetValue(VisualElement.BackgroundColorProperty, Color.Transparent);
		grid6.SetValue(Xamarin.Forms.View.MarginProperty, new Thickness(0.0, 5.0, 10.0, 5.0));
		BindableProperty fontSizeProperty5 = Entry.FontSizeProperty;
		FontSizeConverter fontSizeConverter5 = new FontSizeConverter();
		XamlServiceProvider xamlServiceProvider5 = new XamlServiceProvider();
		Type typeFromHandle9 = typeof(IProvideValueTarget);
		object[] array5 = new object[0 + 5];
		array5[0] = entry;
		array5[1] = grid6;
		array5[2] = grid7;
		array5[3] = grid8;
		array5[4] = recordEditView;
		object service5;
		xamlServiceProvider5.Add(typeFromHandle9, service5 = new SimpleValueTargetProvider(array5, Entry.FontSizeProperty, nameScope));
		xamlServiceProvider5.Add(typeof(IReferenceProvider), service5);
		Type typeFromHandle10 = typeof(IXamlTypeResolver);
		XmlNamespaceResolver xmlNamespaceResolver5 = new XmlNamespaceResolver();
		xmlNamespaceResolver5.Add("", "http://xamarin.com/schemas/2014/forms");
		xmlNamespaceResolver5.Add("x", "http://schemas.microsoft.com/winfx/2009/xaml");
		xmlNamespaceResolver5.Add("calx", "clr-namespace:Caliburn.Micro.Xamarin.Forms;assembly=Caliburn.Micro.Platform.Xamarin.Forms");
		xmlNamespaceResolver5.Add("effect", "clr-namespace:NHL.Views.Effect");
		xmlNamespaceResolver5.Add("renderer", "clr-namespace:NHL.Views.Renderer");
		xmlNamespaceResolver5.Add("system", "clr-namespace:System;assembly=System.Runtime.Extensions");
		xamlServiceProvider5.Add(typeFromHandle10, new XamlTypeResolver(xmlNamespaceResolver5, typeof(RecordEditView).GetTypeInfo().Assembly));
		xamlServiceProvider5.Add(typeof(IXmlLineInfoProvider), new XmlLineInfoProvider(new XmlLineInfo(68, 24)));
		entry.SetValue(fontSizeProperty5, ((IExtendedTypeConverter)fontSizeConverter5).ConvertFromInvariantString("Large", (IServiceProvider)xamlServiceProvider5));
		entry.SetValue(InputView.KeyboardProperty, new KeyboardTypeConverter().ConvertFromInvariantString("Numeric"));
		bindingExtension3.Mode = BindingMode.TwoWay;
		bindingExtension3.Path = "MeasurementValue";
		BindingBase binding3 = ((IMarkupExtension<BindingBase>)bindingExtension3).ProvideValue((IServiceProvider)null);
		entry.SetBinding(Entry.TextProperty, binding3);
		entry.Effects.Add(fixedFontSizeTextBoxEffect2);
		VisualDiagnostics.RegisterSourceInfo(fixedFontSizeTextBoxEffect2, new Uri("Views/RecordEditView.xaml", UriKind.RelativeOrAbsolute), 70, 26);
		grid6.Children.Add(entry);
		VisualDiagnostics.RegisterSourceInfo(entry, new Uri("Views/RecordEditView.xaml", UriKind.RelativeOrAbsolute), 68, 18);
		grid7.Children.Add(grid6);
		VisualDiagnostics.RegisterSourceInfo(grid6, new Uri("Views/RecordEditView.xaml", UriKind.RelativeOrAbsolute), 67, 14);
		label5.SetValue(Grid.RowProperty, 3);
		label5.SetValue(Grid.ColumnProperty, 0);
		label5.SetValue(Grid.ColumnSpanProperty, 2);
		label5.SetValue(Xamarin.Forms.View.MarginProperty, new Thickness(10.0, 10.0, 10.0, 10.0));
		label5.SetValue(VisualElement.BackgroundColorProperty, new Color(0.35686275362968445, 0.6078431606292725, 0.8352941274642944, 1.0));
		label5.SetValue(Label.HorizontalTextAlignmentProperty, new TextAlignmentConverter().ConvertFromInvariantString("Center"));
		label5.SetValue(Label.VerticalTextAlignmentProperty, new TextAlignmentConverter().ConvertFromInvariantString("Center"));
		BindableProperty fontSizeProperty6 = Label.FontSizeProperty;
		FontSizeConverter fontSizeConverter6 = new FontSizeConverter();
		XamlServiceProvider xamlServiceProvider6 = new XamlServiceProvider();
		Type typeFromHandle11 = typeof(IProvideValueTarget);
		object[] array6 = new object[0 + 4];
		array6[0] = label5;
		array6[1] = grid7;
		array6[2] = grid8;
		array6[3] = recordEditView;
		object service6;
		xamlServiceProvider6.Add(typeFromHandle11, service6 = new SimpleValueTargetProvider(array6, Label.FontSizeProperty, nameScope));
		xamlServiceProvider6.Add(typeof(IReferenceProvider), service6);
		Type typeFromHandle12 = typeof(IXamlTypeResolver);
		XmlNamespaceResolver xmlNamespaceResolver6 = new XmlNamespaceResolver();
		xmlNamespaceResolver6.Add("", "http://xamarin.com/schemas/2014/forms");
		xmlNamespaceResolver6.Add("x", "http://schemas.microsoft.com/winfx/2009/xaml");
		xmlNamespaceResolver6.Add("calx", "clr-namespace:Caliburn.Micro.Xamarin.Forms;assembly=Caliburn.Micro.Platform.Xamarin.Forms");
		xmlNamespaceResolver6.Add("effect", "clr-namespace:NHL.Views.Effect");
		xmlNamespaceResolver6.Add("renderer", "clr-namespace:NHL.Views.Renderer");
		xmlNamespaceResolver6.Add("system", "clr-namespace:System;assembly=System.Runtime.Extensions");
		xamlServiceProvider6.Add(typeFromHandle12, new XamlTypeResolver(xmlNamespaceResolver6, typeof(RecordEditView).GetTypeInfo().Assembly));
		xamlServiceProvider6.Add(typeof(IXmlLineInfoProvider), new XmlLineInfoProvider(new XmlLineInfo(76, 180)));
		label5.SetValue(fontSizeProperty6, ((IExtendedTypeConverter)fontSizeConverter6).ConvertFromInvariantString("Medium", (IServiceProvider)xamlServiceProvider6));
		label5.SetValue(Label.FontAttributesProperty, new FontAttributesConverter().ConvertFromInvariantString("Bold"));
		label5.SetValue(Label.TextColorProperty, Color.White);
		label5.SetValue(Label.TextProperty, "登録");
		label5.Effects.Add(fixedFontSizeLabelEffect5);
		VisualDiagnostics.RegisterSourceInfo(fixedFontSizeLabelEffect5, new Uri("Views/RecordEditView.xaml", UriKind.RelativeOrAbsolute), 79, 22);
		grid7.Children.Add(label5);
		VisualDiagnostics.RegisterSourceInfo(label5, new Uri("Views/RecordEditView.xaml", UriKind.RelativeOrAbsolute), 76, 14);
		label6.SetValue(Grid.RowProperty, 3);
		label6.SetValue(Grid.ColumnProperty, 0);
		label6.SetValue(Grid.ColumnSpanProperty, 2);
		label6.SetValue(Xamarin.Forms.View.MarginProperty, new Thickness(10.0, 10.0, 10.0, 10.0));
		label6.SetValue(VisualElement.BackgroundColorProperty, new Color(0.35686275362968445, 0.6078431606292725, 0.8352941274642944, 1.0));
		label6.SetValue(Label.HorizontalTextAlignmentProperty, new TextAlignmentConverter().ConvertFromInvariantString("Center"));
		label6.SetValue(Label.VerticalTextAlignmentProperty, new TextAlignmentConverter().ConvertFromInvariantString("Center"));
		BindableProperty fontSizeProperty7 = Label.FontSizeProperty;
		FontSizeConverter fontSizeConverter7 = new FontSizeConverter();
		XamlServiceProvider xamlServiceProvider7 = new XamlServiceProvider();
		Type typeFromHandle13 = typeof(IProvideValueTarget);
		object[] array7 = new object[0 + 4];
		array7[0] = label6;
		array7[1] = grid7;
		array7[2] = grid8;
		array7[3] = recordEditView;
		object service7;
		xamlServiceProvider7.Add(typeFromHandle13, service7 = new SimpleValueTargetProvider(array7, Label.FontSizeProperty, nameScope));
		xamlServiceProvider7.Add(typeof(IReferenceProvider), service7);
		Type typeFromHandle14 = typeof(IXamlTypeResolver);
		XmlNamespaceResolver xmlNamespaceResolver7 = new XmlNamespaceResolver();
		xmlNamespaceResolver7.Add("", "http://xamarin.com/schemas/2014/forms");
		xmlNamespaceResolver7.Add("x", "http://schemas.microsoft.com/winfx/2009/xaml");
		xmlNamespaceResolver7.Add("calx", "clr-namespace:Caliburn.Micro.Xamarin.Forms;assembly=Caliburn.Micro.Platform.Xamarin.Forms");
		xmlNamespaceResolver7.Add("effect", "clr-namespace:NHL.Views.Effect");
		xmlNamespaceResolver7.Add("renderer", "clr-namespace:NHL.Views.Renderer");
		xmlNamespaceResolver7.Add("system", "clr-namespace:System;assembly=System.Runtime.Extensions");
		xamlServiceProvider7.Add(typeFromHandle14, new XamlTypeResolver(xmlNamespaceResolver7, typeof(RecordEditView).GetTypeInfo().Assembly));
		xamlServiceProvider7.Add(typeof(IXmlLineInfoProvider), new XmlLineInfoProvider(new XmlLineInfo(82, 180)));
		label6.SetValue(fontSizeProperty7, ((IExtendedTypeConverter)fontSizeConverter7).ConvertFromInvariantString("Medium", (IServiceProvider)xamlServiceProvider7));
		label6.SetValue(Label.FontAttributesProperty, new FontAttributesConverter().ConvertFromInvariantString("Bold"));
		label6.SetValue(Label.TextColorProperty, Color.White);
		label6.SetValue(Label.TextProperty, "更新");
		bindingExtension4.Path = "IsEdited";
		BindingBase binding4 = ((IMarkupExtension<BindingBase>)bindingExtension4).ProvideValue((IServiceProvider)null);
		label6.SetBinding(VisualElement.IsVisibleProperty, binding4);
		label6.Effects.Add(fixedFontSizeLabelEffect6);
		VisualDiagnostics.RegisterSourceInfo(fixedFontSizeLabelEffect6, new Uri("Views/RecordEditView.xaml", UriKind.RelativeOrAbsolute), 85, 22);
		grid7.Children.Add(label6);
		VisualDiagnostics.RegisterSourceInfo(label6, new Uri("Views/RecordEditView.xaml", UriKind.RelativeOrAbsolute), 82, 14);
		button.SetValue(Grid.RowProperty, 3);
		button.SetValue(Grid.ColumnProperty, 0);
		button.SetValue(Grid.ColumnSpanProperty, 2);
		button.SetValue(Xamarin.Forms.View.MarginProperty, new Thickness(10.0, 10.0, 10.0, 10.0));
		button.SetValue(VisualElement.BackgroundColorProperty, Color.Transparent);
		button.SetValue(Xamarin.Forms.View.HorizontalOptionsProperty, LayoutOptions.FillAndExpand);
		button.SetValue(Button.BorderWidthProperty, 1.0);
		button.SetValue(Button.BorderColorProperty, Color.Black);
		button.SetValue(Message.AttachProperty, "OnRegisterTapped");
		button.Effects.Add(fixedFontSizeButtonEffect);
		VisualDiagnostics.RegisterSourceInfo(fixedFontSizeButtonEffect, new Uri("Views/RecordEditView.xaml", UriKind.RelativeOrAbsolute), 91, 22);
		grid7.Children.Add(button);
		VisualDiagnostics.RegisterSourceInfo(button, new Uri("Views/RecordEditView.xaml", UriKind.RelativeOrAbsolute), 88, 14);
		label7.SetValue(Grid.RowProperty, 4);
		label7.SetValue(Grid.ColumnProperty, 0);
		label7.SetValue(Grid.ColumnSpanProperty, 2);
		label7.SetValue(Xamarin.Forms.View.MarginProperty, new Thickness(10.0, 10.0, 10.0, 10.0));
		label7.SetValue(VisualElement.BackgroundColorProperty, new Color(0.95686274766922, 0.26274511218070984, 0.21176470816135406, 1.0));
		label7.SetValue(Label.HorizontalTextAlignmentProperty, new TextAlignmentConverter().ConvertFromInvariantString("Center"));
		label7.SetValue(Label.VerticalTextAlignmentProperty, new TextAlignmentConverter().ConvertFromInvariantString("Center"));
		BindableProperty fontSizeProperty8 = Label.FontSizeProperty;
		FontSizeConverter fontSizeConverter8 = new FontSizeConverter();
		XamlServiceProvider xamlServiceProvider8 = new XamlServiceProvider();
		Type typeFromHandle15 = typeof(IProvideValueTarget);
		object[] array8 = new object[0 + 4];
		array8[0] = label7;
		array8[1] = grid7;
		array8[2] = grid8;
		array8[3] = recordEditView;
		object service8;
		xamlServiceProvider8.Add(typeFromHandle15, service8 = new SimpleValueTargetProvider(array8, Label.FontSizeProperty, nameScope));
		xamlServiceProvider8.Add(typeof(IReferenceProvider), service8);
		Type typeFromHandle16 = typeof(IXamlTypeResolver);
		XmlNamespaceResolver xmlNamespaceResolver8 = new XmlNamespaceResolver();
		xmlNamespaceResolver8.Add("", "http://xamarin.com/schemas/2014/forms");
		xmlNamespaceResolver8.Add("x", "http://schemas.microsoft.com/winfx/2009/xaml");
		xmlNamespaceResolver8.Add("calx", "clr-namespace:Caliburn.Micro.Xamarin.Forms;assembly=Caliburn.Micro.Platform.Xamarin.Forms");
		xmlNamespaceResolver8.Add("effect", "clr-namespace:NHL.Views.Effect");
		xmlNamespaceResolver8.Add("renderer", "clr-namespace:NHL.Views.Renderer");
		xmlNamespaceResolver8.Add("system", "clr-namespace:System;assembly=System.Runtime.Extensions");
		xamlServiceProvider8.Add(typeFromHandle16, new XamlTypeResolver(xmlNamespaceResolver8, typeof(RecordEditView).GetTypeInfo().Assembly));
		xamlServiceProvider8.Add(typeof(IXmlLineInfoProvider), new XmlLineInfoProvider(new XmlLineInfo(96, 180)));
		label7.SetValue(fontSizeProperty8, ((IExtendedTypeConverter)fontSizeConverter8).ConvertFromInvariantString("Medium", (IServiceProvider)xamlServiceProvider8));
		label7.SetValue(Label.FontAttributesProperty, new FontAttributesConverter().ConvertFromInvariantString("Bold"));
		label7.SetValue(Label.TextColorProperty, Color.White);
		label7.SetValue(Label.TextProperty, "削除");
		bindingExtension5.Path = "IsEdited";
		BindingBase binding5 = ((IMarkupExtension<BindingBase>)bindingExtension5).ProvideValue((IServiceProvider)null);
		label7.SetBinding(VisualElement.IsVisibleProperty, binding5);
		label7.Effects.Add(fixedFontSizeLabelEffect7);
		VisualDiagnostics.RegisterSourceInfo(fixedFontSizeLabelEffect7, new Uri("Views/RecordEditView.xaml", UriKind.RelativeOrAbsolute), 99, 22);
		grid7.Children.Add(label7);
		VisualDiagnostics.RegisterSourceInfo(label7, new Uri("Views/RecordEditView.xaml", UriKind.RelativeOrAbsolute), 96, 14);
		button2.SetValue(Grid.RowProperty, 4);
		button2.SetValue(Grid.ColumnProperty, 0);
		button2.SetValue(Grid.ColumnSpanProperty, 2);
		button2.SetValue(Xamarin.Forms.View.MarginProperty, new Thickness(10.0, 10.0, 10.0, 10.0));
		button2.SetValue(VisualElement.BackgroundColorProperty, Color.Transparent);
		button2.SetValue(Xamarin.Forms.View.HorizontalOptionsProperty, LayoutOptions.FillAndExpand);
		button2.SetValue(Button.BorderWidthProperty, 1.0);
		button2.SetValue(Button.BorderColorProperty, Color.Black);
		button2.SetValue(Message.AttachProperty, "OnDeleteTapped");
		bindingExtension6.Path = "IsEdited";
		BindingBase binding6 = ((IMarkupExtension<BindingBase>)bindingExtension6).ProvideValue((IServiceProvider)null);
		button2.SetBinding(VisualElement.IsVisibleProperty, binding6);
		button2.Effects.Add(fixedFontSizeButtonEffect2);
		VisualDiagnostics.RegisterSourceInfo(fixedFontSizeButtonEffect2, new Uri("Views/RecordEditView.xaml", UriKind.RelativeOrAbsolute), 105, 22);
		grid7.Children.Add(button2);
		VisualDiagnostics.RegisterSourceInfo(button2, new Uri("Views/RecordEditView.xaml", UriKind.RelativeOrAbsolute), 102, 14);
		grid8.Children.Add(grid7);
		VisualDiagnostics.RegisterSourceInfo(grid7, new Uri("Views/RecordEditView.xaml", UriKind.RelativeOrAbsolute), 13, 10);
		recordEditView.SetValue(ContentPage.ContentProperty, grid8);
		VisualDiagnostics.RegisterSourceInfo(grid8, new Uri("Views/RecordEditView.xaml", UriKind.RelativeOrAbsolute), 12, 6);
		VisualDiagnostics.RegisterSourceInfo(recordEditView, new Uri("Views/RecordEditView.xaml", UriKind.RelativeOrAbsolute), 2, 2);
	}

	private void __InitComponentRuntime()
	{
		this.LoadFromXaml(typeof(RecordEditView));
		MeasurementAtPicker = this.FindByName<DatePickerView>("MeasurementAtPicker");
	}
}
