using System;
using System.CodeDom.Compiler;
using System.Reflection;
using Caliburn.Micro.Xamarin.Forms;
using NHL.Views.Effect;
using NHL.Views.Renderer;
using Xamarin.Forms;
using Xamarin.Forms.Internals;
using Xamarin.Forms.Xaml;
using Xamarin.Forms.Xaml.Diagnostics;
using Xamarin.Forms.Xaml.Internals;

namespace NHL.Views;

[XamlCompilation(XamlCompilationOptions.Compile)]
[XamlFilePath("Views/SettingView.xaml")]
public class SettingView : ContentPage
{
	public SettingView()
	{
		InitializeComponent();
	}

	[GeneratedCode("Xamarin.Forms.Build.Tasks.XamlG", "2.0.0.0")]
	private void InitializeComponent()
	{
		if (ResourceLoader.CanProvideContentFor(new ResourceLoader.ResourceLoadingQuery
		{
			AssemblyName = typeof(SettingView).GetTypeInfo().Assembly.GetName(),
			ResourcePath = "Views/SettingView.xaml",
			Instance = this
		}))
		{
			__InitComponentRuntime();
			return;
		}
		if (XamlLoader.XamlFileProvider != null && XamlLoader.XamlFileProvider(GetType()) != null)
		{
			__InitComponentRuntime();
			return;
		}
		Color color = Color.FromHex("#CFCFCF");
		ResourceDictionary resourceDictionary = new ResourceDictionary();
		OnPlatform<Thickness> onPlatform = new OnPlatform<Thickness>();
		RowDefinition rowDefinition = new RowDefinition();
		RowDefinition rowDefinition2 = new RowDefinition();
		RowDefinition rowDefinition3 = new RowDefinition();
		RowDefinition rowDefinition4 = new RowDefinition();
		RowDefinition rowDefinition5 = new RowDefinition();
		RowDefinition rowDefinition6 = new RowDefinition();
		RowDefinition rowDefinition7 = new RowDefinition();
		RowDefinition rowDefinition8 = new RowDefinition();
		RowDefinition rowDefinition9 = new RowDefinition();
		RowDefinition rowDefinition10 = new RowDefinition();
		RowDefinition rowDefinition11 = new RowDefinition();
		RowDefinition rowDefinition12 = new RowDefinition();
		RowDefinition rowDefinition13 = new RowDefinition();
		RowDefinition rowDefinition14 = new RowDefinition();
		RowDefinition rowDefinition15 = new RowDefinition();
		RowDefinition rowDefinition16 = new RowDefinition();
		RowDefinition rowDefinition17 = new RowDefinition();
		RowDefinition rowDefinition18 = new RowDefinition();
		RowDefinition rowDefinition19 = new RowDefinition();
		RowDefinition item = new RowDefinition();
		FixedFontSizeLabelEffect fixedFontSizeLabelEffect = new FixedFontSizeLabelEffect();
		Label label = new Label();
		StaticResourceExtension staticResourceExtension = new StaticResourceExtension();
		Grid grid = new Grid();
		StaticResourceExtension staticResourceExtension2 = new StaticResourceExtension();
		Grid grid2 = new Grid();
		StaticResourceExtension staticResourceExtension3 = new StaticResourceExtension();
		Grid grid3 = new Grid();
		StaticResourceExtension staticResourceExtension4 = new StaticResourceExtension();
		Grid grid4 = new Grid();
		FixedFontSizeButtonEffect fixedFontSizeButtonEffect = new FixedFontSizeButtonEffect();
		ExtendedButton extendedButton = new ExtendedButton();
		FixedFontSizeButtonEffect fixedFontSizeButtonEffect2 = new FixedFontSizeButtonEffect();
		ExtendedButton extendedButton2 = new ExtendedButton();
		FixedFontSizeButtonEffect fixedFontSizeButtonEffect3 = new FixedFontSizeButtonEffect();
		ExtendedButton extendedButton3 = new ExtendedButton();
		FixedFontSizeButtonEffect fixedFontSizeButtonEffect4 = new FixedFontSizeButtonEffect();
		ExtendedButton extendedButton4 = new ExtendedButton();
		FixedFontSizeButtonEffect fixedFontSizeButtonEffect5 = new FixedFontSizeButtonEffect();
		ExtendedButton extendedButton5 = new ExtendedButton();
		FixedFontSizeButtonEffect fixedFontSizeButtonEffect6 = new FixedFontSizeButtonEffect();
		ExtendedButton extendedButton6 = new ExtendedButton();
		FixedFontSizeButtonEffect fixedFontSizeButtonEffect7 = new FixedFontSizeButtonEffect();
		ExtendedButton extendedButton7 = new ExtendedButton();
		FixedFontSizeButtonEffect fixedFontSizeButtonEffect8 = new FixedFontSizeButtonEffect();
		ExtendedButton extendedButton8 = new ExtendedButton();
		FixedFontSizeButtonEffect fixedFontSizeButtonEffect9 = new FixedFontSizeButtonEffect();
		ExtendedButton extendedButton9 = new ExtendedButton();
		FixedFontSizeButtonEffect fixedFontSizeButtonEffect10 = new FixedFontSizeButtonEffect();
		ExtendedButton extendedButton10 = new ExtendedButton();
		FixedFontSizeButtonEffect fixedFontSizeButtonEffect11 = new FixedFontSizeButtonEffect();
		ExtendedButton extendedButton11 = new ExtendedButton();
		FixedFontSizeButtonEffect fixedFontSizeButtonEffect12 = new FixedFontSizeButtonEffect();
		ExtendedButton extendedButton12 = new ExtendedButton();
		FixedFontSizeButtonEffect fixedFontSizeButtonEffect13 = new FixedFontSizeButtonEffect();
		ExtendedButton extendedButton13 = new ExtendedButton();
		Grid grid5 = new Grid();
		ScrollView scrollView = new ScrollView();
		SettingView settingView;
		NameScope nameScope = (NameScope)(NameScope.GetNameScope(settingView = this) ?? new NameScope());
		NameScope.SetNameScope(settingView, nameScope);
		settingView.Resources = resourceDictionary;
		VisualDiagnostics.RegisterSourceInfo(resourceDictionary, new Uri("Views/SettingView.xaml", UriKind.RelativeOrAbsolute), 12, 10);
		resourceDictionary.Add("LineColor", color);
		settingView.SetValue(Page.IconProperty, new FileImageSourceConverter().ConvertFromInvariantString("hamburgermenu.png"));
		settingView.SetValue(Page.TitleProperty, "設定");
		settingView.Resources = resourceDictionary;
		VisualDiagnostics.RegisterSourceInfo(resourceDictionary, new Uri("Views/SettingView.xaml", UriKind.RelativeOrAbsolute), 12, 10);
		onPlatform.iOS = new Thickness(20.0, 20.0, 20.0, 20.0);
		onPlatform.Android = new Thickness(20.0, 10.0, 20.0, 20.0);
		settingView.SetValue(Page.PaddingProperty, (Thickness)onPlatform);
		VisualDiagnostics.RegisterSourceInfo(onPlatform, new Uri("Views/SettingView.xaml", UriKind.RelativeOrAbsolute), 23, 10);
		scrollView.SetValue(ScrollView.OrientationProperty, ScrollOrientation.Vertical);
		rowDefinition.SetValue(RowDefinition.HeightProperty, new GridLengthTypeConverter().ConvertFromInvariantString("60"));
		((DefinitionCollection<RowDefinition>)grid5.GetValue(Grid.RowDefinitionsProperty)).Add(rowDefinition);
		rowDefinition2.SetValue(RowDefinition.HeightProperty, new GridLengthTypeConverter().ConvertFromInvariantString("1"));
		((DefinitionCollection<RowDefinition>)grid5.GetValue(Grid.RowDefinitionsProperty)).Add(rowDefinition2);
		rowDefinition3.SetValue(RowDefinition.HeightProperty, new GridLengthTypeConverter().ConvertFromInvariantString("Auto"));
		((DefinitionCollection<RowDefinition>)grid5.GetValue(Grid.RowDefinitionsProperty)).Add(rowDefinition3);
		rowDefinition4.SetValue(RowDefinition.HeightProperty, new GridLengthTypeConverter().ConvertFromInvariantString("1"));
		((DefinitionCollection<RowDefinition>)grid5.GetValue(Grid.RowDefinitionsProperty)).Add(rowDefinition4);
		rowDefinition5.SetValue(RowDefinition.HeightProperty, new GridLengthTypeConverter().ConvertFromInvariantString("Auto"));
		((DefinitionCollection<RowDefinition>)grid5.GetValue(Grid.RowDefinitionsProperty)).Add(rowDefinition5);
		rowDefinition6.SetValue(RowDefinition.HeightProperty, new GridLengthTypeConverter().ConvertFromInvariantString("Auto"));
		((DefinitionCollection<RowDefinition>)grid5.GetValue(Grid.RowDefinitionsProperty)).Add(rowDefinition6);
		rowDefinition7.SetValue(RowDefinition.HeightProperty, new GridLengthTypeConverter().ConvertFromInvariantString("Auto"));
		((DefinitionCollection<RowDefinition>)grid5.GetValue(Grid.RowDefinitionsProperty)).Add(rowDefinition7);
		rowDefinition8.SetValue(RowDefinition.HeightProperty, new GridLengthTypeConverter().ConvertFromInvariantString("Auto"));
		((DefinitionCollection<RowDefinition>)grid5.GetValue(Grid.RowDefinitionsProperty)).Add(rowDefinition8);
		rowDefinition9.SetValue(RowDefinition.HeightProperty, new GridLengthTypeConverter().ConvertFromInvariantString("1"));
		((DefinitionCollection<RowDefinition>)grid5.GetValue(Grid.RowDefinitionsProperty)).Add(rowDefinition9);
		rowDefinition10.SetValue(RowDefinition.HeightProperty, new GridLengthTypeConverter().ConvertFromInvariantString("Auto"));
		((DefinitionCollection<RowDefinition>)grid5.GetValue(Grid.RowDefinitionsProperty)).Add(rowDefinition10);
		rowDefinition11.SetValue(RowDefinition.HeightProperty, new GridLengthTypeConverter().ConvertFromInvariantString("Auto"));
		((DefinitionCollection<RowDefinition>)grid5.GetValue(Grid.RowDefinitionsProperty)).Add(rowDefinition11);
		rowDefinition12.SetValue(RowDefinition.HeightProperty, new GridLengthTypeConverter().ConvertFromInvariantString("Auto"));
		((DefinitionCollection<RowDefinition>)grid5.GetValue(Grid.RowDefinitionsProperty)).Add(rowDefinition12);
		rowDefinition13.SetValue(RowDefinition.HeightProperty, new GridLengthTypeConverter().ConvertFromInvariantString("Auto"));
		((DefinitionCollection<RowDefinition>)grid5.GetValue(Grid.RowDefinitionsProperty)).Add(rowDefinition13);
		rowDefinition14.SetValue(RowDefinition.HeightProperty, new GridLengthTypeConverter().ConvertFromInvariantString("1"));
		((DefinitionCollection<RowDefinition>)grid5.GetValue(Grid.RowDefinitionsProperty)).Add(rowDefinition14);
		rowDefinition15.SetValue(RowDefinition.HeightProperty, new GridLengthTypeConverter().ConvertFromInvariantString("Auto"));
		((DefinitionCollection<RowDefinition>)grid5.GetValue(Grid.RowDefinitionsProperty)).Add(rowDefinition15);
		rowDefinition16.SetValue(RowDefinition.HeightProperty, new GridLengthTypeConverter().ConvertFromInvariantString("Auto"));
		((DefinitionCollection<RowDefinition>)grid5.GetValue(Grid.RowDefinitionsProperty)).Add(rowDefinition16);
		rowDefinition17.SetValue(RowDefinition.HeightProperty, new GridLengthTypeConverter().ConvertFromInvariantString("Auto"));
		((DefinitionCollection<RowDefinition>)grid5.GetValue(Grid.RowDefinitionsProperty)).Add(rowDefinition17);
		rowDefinition18.SetValue(RowDefinition.HeightProperty, new GridLengthTypeConverter().ConvertFromInvariantString("1"));
		((DefinitionCollection<RowDefinition>)grid5.GetValue(Grid.RowDefinitionsProperty)).Add(rowDefinition18);
		rowDefinition19.SetValue(RowDefinition.HeightProperty, new GridLengthTypeConverter().ConvertFromInvariantString("Auto"));
		((DefinitionCollection<RowDefinition>)grid5.GetValue(Grid.RowDefinitionsProperty)).Add(rowDefinition19);
		((DefinitionCollection<RowDefinition>)grid5.GetValue(Grid.RowDefinitionsProperty)).Add(item);
		label.SetValue(Grid.RowProperty, 0);
		label.SetValue(Label.TextProperty, "設定");
		BindableProperty fontSizeProperty = Label.FontSizeProperty;
		FontSizeConverter fontSizeConverter = new FontSizeConverter();
		XamlServiceProvider xamlServiceProvider = new XamlServiceProvider();
		Type typeFromHandle = typeof(IProvideValueTarget);
		object[] array = new object[0 + 4];
		array[0] = label;
		array[1] = grid5;
		array[2] = scrollView;
		array[3] = settingView;
		object service;
		xamlServiceProvider.Add(typeFromHandle, service = new SimpleValueTargetProvider(array, Label.FontSizeProperty, nameScope));
		xamlServiceProvider.Add(typeof(IReferenceProvider), service);
		Type typeFromHandle2 = typeof(IXamlTypeResolver);
		XmlNamespaceResolver xmlNamespaceResolver = new XmlNamespaceResolver();
		xmlNamespaceResolver.Add("", "http://xamarin.com/schemas/2014/forms");
		xmlNamespaceResolver.Add("x", "http://schemas.microsoft.com/winfx/2009/xaml");
		xmlNamespaceResolver.Add("calx", "clr-namespace:Caliburn.Micro.Xamarin.Forms;assembly=Caliburn.Micro.Platform.Xamarin.Forms");
		xmlNamespaceResolver.Add("renderer", "clr-namespace:NHL.Views.Renderer");
		xmlNamespaceResolver.Add("effect", "clr-namespace:NHL.Views.Effect");
		xamlServiceProvider.Add(typeFromHandle2, new XamlTypeResolver(xmlNamespaceResolver, typeof(SettingView).GetTypeInfo().Assembly));
		xamlServiceProvider.Add(typeof(IXmlLineInfoProvider), new XmlLineInfoProvider(new XmlLineInfo(54, 43)));
		label.SetValue(fontSizeProperty, ((IExtendedTypeConverter)fontSizeConverter).ConvertFromInvariantString("Large", (IServiceProvider)xamlServiceProvider));
		label.Effects.Add(fixedFontSizeLabelEffect);
		VisualDiagnostics.RegisterSourceInfo(fixedFontSizeLabelEffect, new Uri("Views/SettingView.xaml", UriKind.RelativeOrAbsolute), 56, 22);
		grid5.Children.Add(label);
		VisualDiagnostics.RegisterSourceInfo(label, new Uri("Views/SettingView.xaml", UriKind.RelativeOrAbsolute), 54, 14);
		grid.SetValue(Grid.RowProperty, 3);
		staticResourceExtension.Key = "LineColor";
		XamlServiceProvider xamlServiceProvider2 = new XamlServiceProvider();
		Type typeFromHandle3 = typeof(IProvideValueTarget);
		object[] array2 = new object[0 + 4];
		array2[0] = grid;
		array2[1] = grid5;
		array2[2] = scrollView;
		array2[3] = settingView;
		object service2;
		xamlServiceProvider2.Add(typeFromHandle3, service2 = new SimpleValueTargetProvider(array2, VisualElement.BackgroundColorProperty, nameScope));
		xamlServiceProvider2.Add(typeof(IReferenceProvider), service2);
		Type typeFromHandle4 = typeof(IXamlTypeResolver);
		XmlNamespaceResolver xmlNamespaceResolver2 = new XmlNamespaceResolver();
		xmlNamespaceResolver2.Add("", "http://xamarin.com/schemas/2014/forms");
		xmlNamespaceResolver2.Add("x", "http://schemas.microsoft.com/winfx/2009/xaml");
		xmlNamespaceResolver2.Add("calx", "clr-namespace:Caliburn.Micro.Xamarin.Forms;assembly=Caliburn.Micro.Platform.Xamarin.Forms");
		xmlNamespaceResolver2.Add("renderer", "clr-namespace:NHL.Views.Renderer");
		xmlNamespaceResolver2.Add("effect", "clr-namespace:NHL.Views.Effect");
		xamlServiceProvider2.Add(typeFromHandle4, new XamlTypeResolver(xmlNamespaceResolver2, typeof(SettingView).GetTypeInfo().Assembly));
		xamlServiceProvider2.Add(typeof(IXmlLineInfoProvider), new XmlLineInfoProvider(new XmlLineInfo(61, 32)));
		object obj = ((IMarkupExtension)staticResourceExtension).ProvideValue((IServiceProvider)xamlServiceProvider2);
		grid.BackgroundColor = (Color)obj;
		VisualDiagnostics.RegisterSourceInfo(obj, new Uri("Views/SettingView.xaml", UriKind.RelativeOrAbsolute), 61, 32);
		grid.SetValue(Grid.RowSpacingProperty, 1.0);
		grid.SetValue(Grid.ColumnSpacingProperty, 1.0);
		grid5.Children.Add(grid);
		VisualDiagnostics.RegisterSourceInfo(grid, new Uri("Views/SettingView.xaml", UriKind.RelativeOrAbsolute), 61, 14);
		grid2.SetValue(Grid.RowProperty, 8);
		staticResourceExtension2.Key = "LineColor";
		XamlServiceProvider xamlServiceProvider3 = new XamlServiceProvider();
		Type typeFromHandle5 = typeof(IProvideValueTarget);
		object[] array3 = new object[0 + 4];
		array3[0] = grid2;
		array3[1] = grid5;
		array3[2] = scrollView;
		array3[3] = settingView;
		object service3;
		xamlServiceProvider3.Add(typeFromHandle5, service3 = new SimpleValueTargetProvider(array3, VisualElement.BackgroundColorProperty, nameScope));
		xamlServiceProvider3.Add(typeof(IReferenceProvider), service3);
		Type typeFromHandle6 = typeof(IXamlTypeResolver);
		XmlNamespaceResolver xmlNamespaceResolver3 = new XmlNamespaceResolver();
		xmlNamespaceResolver3.Add("", "http://xamarin.com/schemas/2014/forms");
		xmlNamespaceResolver3.Add("x", "http://schemas.microsoft.com/winfx/2009/xaml");
		xmlNamespaceResolver3.Add("calx", "clr-namespace:Caliburn.Micro.Xamarin.Forms;assembly=Caliburn.Micro.Platform.Xamarin.Forms");
		xmlNamespaceResolver3.Add("renderer", "clr-namespace:NHL.Views.Renderer");
		xmlNamespaceResolver3.Add("effect", "clr-namespace:NHL.Views.Effect");
		xamlServiceProvider3.Add(typeFromHandle6, new XamlTypeResolver(xmlNamespaceResolver3, typeof(SettingView).GetTypeInfo().Assembly));
		xamlServiceProvider3.Add(typeof(IXmlLineInfoProvider), new XmlLineInfoProvider(new XmlLineInfo(62, 32)));
		object obj2 = ((IMarkupExtension)staticResourceExtension2).ProvideValue((IServiceProvider)xamlServiceProvider3);
		grid2.BackgroundColor = (Color)obj2;
		VisualDiagnostics.RegisterSourceInfo(obj2, new Uri("Views/SettingView.xaml", UriKind.RelativeOrAbsolute), 62, 32);
		grid2.SetValue(Grid.RowSpacingProperty, 1.0);
		grid2.SetValue(Grid.ColumnSpacingProperty, 1.0);
		grid5.Children.Add(grid2);
		VisualDiagnostics.RegisterSourceInfo(grid2, new Uri("Views/SettingView.xaml", UriKind.RelativeOrAbsolute), 62, 14);
		grid3.SetValue(Grid.RowProperty, 13);
		staticResourceExtension3.Key = "LineColor";
		XamlServiceProvider xamlServiceProvider4 = new XamlServiceProvider();
		Type typeFromHandle7 = typeof(IProvideValueTarget);
		object[] array4 = new object[0 + 4];
		array4[0] = grid3;
		array4[1] = grid5;
		array4[2] = scrollView;
		array4[3] = settingView;
		object service4;
		xamlServiceProvider4.Add(typeFromHandle7, service4 = new SimpleValueTargetProvider(array4, VisualElement.BackgroundColorProperty, nameScope));
		xamlServiceProvider4.Add(typeof(IReferenceProvider), service4);
		Type typeFromHandle8 = typeof(IXamlTypeResolver);
		XmlNamespaceResolver xmlNamespaceResolver4 = new XmlNamespaceResolver();
		xmlNamespaceResolver4.Add("", "http://xamarin.com/schemas/2014/forms");
		xmlNamespaceResolver4.Add("x", "http://schemas.microsoft.com/winfx/2009/xaml");
		xmlNamespaceResolver4.Add("calx", "clr-namespace:Caliburn.Micro.Xamarin.Forms;assembly=Caliburn.Micro.Platform.Xamarin.Forms");
		xmlNamespaceResolver4.Add("renderer", "clr-namespace:NHL.Views.Renderer");
		xmlNamespaceResolver4.Add("effect", "clr-namespace:NHL.Views.Effect");
		xamlServiceProvider4.Add(typeFromHandle8, new XamlTypeResolver(xmlNamespaceResolver4, typeof(SettingView).GetTypeInfo().Assembly));
		xamlServiceProvider4.Add(typeof(IXmlLineInfoProvider), new XmlLineInfoProvider(new XmlLineInfo(63, 33)));
		object obj3 = ((IMarkupExtension)staticResourceExtension3).ProvideValue((IServiceProvider)xamlServiceProvider4);
		grid3.BackgroundColor = (Color)obj3;
		VisualDiagnostics.RegisterSourceInfo(obj3, new Uri("Views/SettingView.xaml", UriKind.RelativeOrAbsolute), 63, 33);
		grid3.SetValue(Grid.RowSpacingProperty, 1.0);
		grid3.SetValue(Grid.ColumnSpacingProperty, 1.0);
		grid5.Children.Add(grid3);
		VisualDiagnostics.RegisterSourceInfo(grid3, new Uri("Views/SettingView.xaml", UriKind.RelativeOrAbsolute), 63, 14);
		grid4.SetValue(Grid.RowProperty, 17);
		staticResourceExtension4.Key = "LineColor";
		XamlServiceProvider xamlServiceProvider5 = new XamlServiceProvider();
		Type typeFromHandle9 = typeof(IProvideValueTarget);
		object[] array5 = new object[0 + 4];
		array5[0] = grid4;
		array5[1] = grid5;
		array5[2] = scrollView;
		array5[3] = settingView;
		object service5;
		xamlServiceProvider5.Add(typeFromHandle9, service5 = new SimpleValueTargetProvider(array5, VisualElement.BackgroundColorProperty, nameScope));
		xamlServiceProvider5.Add(typeof(IReferenceProvider), service5);
		Type typeFromHandle10 = typeof(IXamlTypeResolver);
		XmlNamespaceResolver xmlNamespaceResolver5 = new XmlNamespaceResolver();
		xmlNamespaceResolver5.Add("", "http://xamarin.com/schemas/2014/forms");
		xmlNamespaceResolver5.Add("x", "http://schemas.microsoft.com/winfx/2009/xaml");
		xmlNamespaceResolver5.Add("calx", "clr-namespace:Caliburn.Micro.Xamarin.Forms;assembly=Caliburn.Micro.Platform.Xamarin.Forms");
		xmlNamespaceResolver5.Add("renderer", "clr-namespace:NHL.Views.Renderer");
		xmlNamespaceResolver5.Add("effect", "clr-namespace:NHL.Views.Effect");
		xamlServiceProvider5.Add(typeFromHandle10, new XamlTypeResolver(xmlNamespaceResolver5, typeof(SettingView).GetTypeInfo().Assembly));
		xamlServiceProvider5.Add(typeof(IXmlLineInfoProvider), new XmlLineInfoProvider(new XmlLineInfo(64, 33)));
		object obj4 = ((IMarkupExtension)staticResourceExtension4).ProvideValue((IServiceProvider)xamlServiceProvider5);
		grid4.BackgroundColor = (Color)obj4;
		VisualDiagnostics.RegisterSourceInfo(obj4, new Uri("Views/SettingView.xaml", UriKind.RelativeOrAbsolute), 64, 33);
		grid4.SetValue(Grid.RowSpacingProperty, 1.0);
		grid4.SetValue(Grid.ColumnSpacingProperty, 1.0);
		grid5.Children.Add(grid4);
		VisualDiagnostics.RegisterSourceInfo(grid4, new Uri("Views/SettingView.xaml", UriKind.RelativeOrAbsolute), 64, 14);
		extendedButton.SetValue(Grid.RowProperty, 2);
		extendedButton.SetValue(Button.TextProperty, "お知らせ");
		extendedButton.SetValue(Message.AttachProperty, "NoticeList");
		BindableProperty fontSizeProperty2 = Button.FontSizeProperty;
		FontSizeConverter fontSizeConverter2 = new FontSizeConverter();
		XamlServiceProvider xamlServiceProvider6 = new XamlServiceProvider();
		Type typeFromHandle11 = typeof(IProvideValueTarget);
		object[] array6 = new object[0 + 4];
		array6[0] = extendedButton;
		array6[1] = grid5;
		array6[2] = scrollView;
		array6[3] = settingView;
		object service6;
		xamlServiceProvider6.Add(typeFromHandle11, service6 = new SimpleValueTargetProvider(array6, Button.FontSizeProperty, nameScope));
		xamlServiceProvider6.Add(typeof(IReferenceProvider), service6);
		Type typeFromHandle12 = typeof(IXamlTypeResolver);
		XmlNamespaceResolver xmlNamespaceResolver6 = new XmlNamespaceResolver();
		xmlNamespaceResolver6.Add("", "http://xamarin.com/schemas/2014/forms");
		xmlNamespaceResolver6.Add("x", "http://schemas.microsoft.com/winfx/2009/xaml");
		xmlNamespaceResolver6.Add("calx", "clr-namespace:Caliburn.Micro.Xamarin.Forms;assembly=Caliburn.Micro.Platform.Xamarin.Forms");
		xmlNamespaceResolver6.Add("renderer", "clr-namespace:NHL.Views.Renderer");
		xmlNamespaceResolver6.Add("effect", "clr-namespace:NHL.Views.Effect");
		xamlServiceProvider6.Add(typeFromHandle12, new XamlTypeResolver(xmlNamespaceResolver6, typeof(SettingView).GetTypeInfo().Assembly));
		xamlServiceProvider6.Add(typeof(IXmlLineInfoProvider), new XmlLineInfoProvider(new XmlLineInfo(67, 96)));
		extendedButton.SetValue(fontSizeProperty2, ((IExtendedTypeConverter)fontSizeConverter2).ConvertFromInvariantString("Medium", (IServiceProvider)xamlServiceProvider6));
		extendedButton.SetValue(Xamarin.Forms.View.HorizontalOptionsProperty, LayoutOptions.StartAndExpand);
		extendedButton.SetValue(VisualElement.BackgroundColorProperty, Color.Transparent);
		extendedButton.SetValue(ExtendedButton.HorizontalTextAlignmentProperty, new TextAlignmentConverter().ConvertFromInvariantString("Start"));
		extendedButton.Effects.Add(fixedFontSizeButtonEffect);
		VisualDiagnostics.RegisterSourceInfo(fixedFontSizeButtonEffect, new Uri("Views/SettingView.xaml", UriKind.RelativeOrAbsolute), 69, 22);
		grid5.Children.Add(extendedButton);
		VisualDiagnostics.RegisterSourceInfo(extendedButton, new Uri("Views/SettingView.xaml", UriKind.RelativeOrAbsolute), 67, 14);
		extendedButton2.SetValue(Grid.RowProperty, 4);
		extendedButton2.SetValue(Button.TextProperty, "ユーザー情報");
		extendedButton2.SetValue(Message.AttachProperty, "UserInfo");
		BindableProperty fontSizeProperty3 = Button.FontSizeProperty;
		FontSizeConverter fontSizeConverter3 = new FontSizeConverter();
		XamlServiceProvider xamlServiceProvider7 = new XamlServiceProvider();
		Type typeFromHandle13 = typeof(IProvideValueTarget);
		object[] array7 = new object[0 + 4];
		array7[0] = extendedButton2;
		array7[1] = grid5;
		array7[2] = scrollView;
		array7[3] = settingView;
		object service7;
		xamlServiceProvider7.Add(typeFromHandle13, service7 = new SimpleValueTargetProvider(array7, Button.FontSizeProperty, nameScope));
		xamlServiceProvider7.Add(typeof(IReferenceProvider), service7);
		Type typeFromHandle14 = typeof(IXamlTypeResolver);
		XmlNamespaceResolver xmlNamespaceResolver7 = new XmlNamespaceResolver();
		xmlNamespaceResolver7.Add("", "http://xamarin.com/schemas/2014/forms");
		xmlNamespaceResolver7.Add("x", "http://schemas.microsoft.com/winfx/2009/xaml");
		xmlNamespaceResolver7.Add("calx", "clr-namespace:Caliburn.Micro.Xamarin.Forms;assembly=Caliburn.Micro.Platform.Xamarin.Forms");
		xmlNamespaceResolver7.Add("renderer", "clr-namespace:NHL.Views.Renderer");
		xmlNamespaceResolver7.Add("effect", "clr-namespace:NHL.Views.Effect");
		xamlServiceProvider7.Add(typeFromHandle14, new XamlTypeResolver(xmlNamespaceResolver7, typeof(SettingView).GetTypeInfo().Assembly));
		xamlServiceProvider7.Add(typeof(IXmlLineInfoProvider), new XmlLineInfoProvider(new XmlLineInfo(72, 96)));
		extendedButton2.SetValue(fontSizeProperty3, ((IExtendedTypeConverter)fontSizeConverter3).ConvertFromInvariantString("Medium", (IServiceProvider)xamlServiceProvider7));
		extendedButton2.SetValue(Xamarin.Forms.View.HorizontalOptionsProperty, LayoutOptions.StartAndExpand);
		extendedButton2.SetValue(VisualElement.BackgroundColorProperty, Color.Transparent);
		extendedButton2.SetValue(ExtendedButton.HorizontalTextAlignmentProperty, new TextAlignmentConverter().ConvertFromInvariantString("Start"));
		extendedButton2.Effects.Add(fixedFontSizeButtonEffect2);
		VisualDiagnostics.RegisterSourceInfo(fixedFontSizeButtonEffect2, new Uri("Views/SettingView.xaml", UriKind.RelativeOrAbsolute), 74, 22);
		grid5.Children.Add(extendedButton2);
		VisualDiagnostics.RegisterSourceInfo(extendedButton2, new Uri("Views/SettingView.xaml", UriKind.RelativeOrAbsolute), 72, 14);
		extendedButton3.SetValue(Grid.RowProperty, 5);
		extendedButton3.SetValue(Button.TextProperty, "タイムゾーン設定（血糖）");
		extendedButton3.SetValue(Message.AttachProperty, "Timezone");
		BindableProperty fontSizeProperty4 = Button.FontSizeProperty;
		FontSizeConverter fontSizeConverter4 = new FontSizeConverter();
		XamlServiceProvider xamlServiceProvider8 = new XamlServiceProvider();
		Type typeFromHandle15 = typeof(IProvideValueTarget);
		object[] array8 = new object[0 + 4];
		array8[0] = extendedButton3;
		array8[1] = grid5;
		array8[2] = scrollView;
		array8[3] = settingView;
		object service8;
		xamlServiceProvider8.Add(typeFromHandle15, service8 = new SimpleValueTargetProvider(array8, Button.FontSizeProperty, nameScope));
		xamlServiceProvider8.Add(typeof(IReferenceProvider), service8);
		Type typeFromHandle16 = typeof(IXamlTypeResolver);
		XmlNamespaceResolver xmlNamespaceResolver8 = new XmlNamespaceResolver();
		xmlNamespaceResolver8.Add("", "http://xamarin.com/schemas/2014/forms");
		xmlNamespaceResolver8.Add("x", "http://schemas.microsoft.com/winfx/2009/xaml");
		xmlNamespaceResolver8.Add("calx", "clr-namespace:Caliburn.Micro.Xamarin.Forms;assembly=Caliburn.Micro.Platform.Xamarin.Forms");
		xmlNamespaceResolver8.Add("renderer", "clr-namespace:NHL.Views.Renderer");
		xmlNamespaceResolver8.Add("effect", "clr-namespace:NHL.Views.Effect");
		xamlServiceProvider8.Add(typeFromHandle16, new XamlTypeResolver(xmlNamespaceResolver8, typeof(SettingView).GetTypeInfo().Assembly));
		xamlServiceProvider8.Add(typeof(IXmlLineInfoProvider), new XmlLineInfoProvider(new XmlLineInfo(77, 102)));
		extendedButton3.SetValue(fontSizeProperty4, ((IExtendedTypeConverter)fontSizeConverter4).ConvertFromInvariantString("Medium", (IServiceProvider)xamlServiceProvider8));
		extendedButton3.SetValue(Xamarin.Forms.View.HorizontalOptionsProperty, LayoutOptions.StartAndExpand);
		extendedButton3.SetValue(VisualElement.BackgroundColorProperty, Color.Transparent);
		extendedButton3.SetValue(ExtendedButton.HorizontalTextAlignmentProperty, new TextAlignmentConverter().ConvertFromInvariantString("Start"));
		extendedButton3.Effects.Add(fixedFontSizeButtonEffect3);
		VisualDiagnostics.RegisterSourceInfo(fixedFontSizeButtonEffect3, new Uri("Views/SettingView.xaml", UriKind.RelativeOrAbsolute), 79, 22);
		grid5.Children.Add(extendedButton3);
		VisualDiagnostics.RegisterSourceInfo(extendedButton3, new Uri("Views/SettingView.xaml", UriKind.RelativeOrAbsolute), 77, 14);
		extendedButton4.SetValue(Grid.RowProperty, 6);
		extendedButton4.SetValue(Button.TextProperty, "タイムゾーン設定（その他）");
		extendedButton4.SetValue(Message.AttachProperty, "TimezoneOther");
		BindableProperty fontSizeProperty5 = Button.FontSizeProperty;
		FontSizeConverter fontSizeConverter5 = new FontSizeConverter();
		XamlServiceProvider xamlServiceProvider9 = new XamlServiceProvider();
		Type typeFromHandle17 = typeof(IProvideValueTarget);
		object[] array9 = new object[0 + 4];
		array9[0] = extendedButton4;
		array9[1] = grid5;
		array9[2] = scrollView;
		array9[3] = settingView;
		object service9;
		xamlServiceProvider9.Add(typeFromHandle17, service9 = new SimpleValueTargetProvider(array9, Button.FontSizeProperty, nameScope));
		xamlServiceProvider9.Add(typeof(IReferenceProvider), service9);
		Type typeFromHandle18 = typeof(IXamlTypeResolver);
		XmlNamespaceResolver xmlNamespaceResolver9 = new XmlNamespaceResolver();
		xmlNamespaceResolver9.Add("", "http://xamarin.com/schemas/2014/forms");
		xmlNamespaceResolver9.Add("x", "http://schemas.microsoft.com/winfx/2009/xaml");
		xmlNamespaceResolver9.Add("calx", "clr-namespace:Caliburn.Micro.Xamarin.Forms;assembly=Caliburn.Micro.Platform.Xamarin.Forms");
		xmlNamespaceResolver9.Add("renderer", "clr-namespace:NHL.Views.Renderer");
		xmlNamespaceResolver9.Add("effect", "clr-namespace:NHL.Views.Effect");
		xamlServiceProvider9.Add(typeFromHandle18, new XamlTypeResolver(xmlNamespaceResolver9, typeof(SettingView).GetTypeInfo().Assembly));
		xamlServiceProvider9.Add(typeof(IXmlLineInfoProvider), new XmlLineInfoProvider(new XmlLineInfo(82, 108)));
		extendedButton4.SetValue(fontSizeProperty5, ((IExtendedTypeConverter)fontSizeConverter5).ConvertFromInvariantString("Medium", (IServiceProvider)xamlServiceProvider9));
		extendedButton4.SetValue(Xamarin.Forms.View.HorizontalOptionsProperty, LayoutOptions.StartAndExpand);
		extendedButton4.SetValue(VisualElement.BackgroundColorProperty, Color.Transparent);
		extendedButton4.SetValue(ExtendedButton.HorizontalTextAlignmentProperty, new TextAlignmentConverter().ConvertFromInvariantString("Start"));
		extendedButton4.Effects.Add(fixedFontSizeButtonEffect4);
		VisualDiagnostics.RegisterSourceInfo(fixedFontSizeButtonEffect4, new Uri("Views/SettingView.xaml", UriKind.RelativeOrAbsolute), 84, 22);
		grid5.Children.Add(extendedButton4);
		VisualDiagnostics.RegisterSourceInfo(extendedButton4, new Uri("Views/SettingView.xaml", UriKind.RelativeOrAbsolute), 82, 14);
		extendedButton5.SetValue(Grid.RowProperty, 7);
		extendedButton5.SetValue(Button.TextProperty, "目標値設定（血糖値）");
		extendedButton5.SetValue(Message.AttachProperty, "GlucoseTarget");
		BindableProperty fontSizeProperty6 = Button.FontSizeProperty;
		FontSizeConverter fontSizeConverter6 = new FontSizeConverter();
		XamlServiceProvider xamlServiceProvider10 = new XamlServiceProvider();
		Type typeFromHandle19 = typeof(IProvideValueTarget);
		object[] array10 = new object[0 + 4];
		array10[0] = extendedButton5;
		array10[1] = grid5;
		array10[2] = scrollView;
		array10[3] = settingView;
		object service10;
		xamlServiceProvider10.Add(typeFromHandle19, service10 = new SimpleValueTargetProvider(array10, Button.FontSizeProperty, nameScope));
		xamlServiceProvider10.Add(typeof(IReferenceProvider), service10);
		Type typeFromHandle20 = typeof(IXamlTypeResolver);
		XmlNamespaceResolver xmlNamespaceResolver10 = new XmlNamespaceResolver();
		xmlNamespaceResolver10.Add("", "http://xamarin.com/schemas/2014/forms");
		xmlNamespaceResolver10.Add("x", "http://schemas.microsoft.com/winfx/2009/xaml");
		xmlNamespaceResolver10.Add("calx", "clr-namespace:Caliburn.Micro.Xamarin.Forms;assembly=Caliburn.Micro.Platform.Xamarin.Forms");
		xmlNamespaceResolver10.Add("renderer", "clr-namespace:NHL.Views.Renderer");
		xmlNamespaceResolver10.Add("effect", "clr-namespace:NHL.Views.Effect");
		xamlServiceProvider10.Add(typeFromHandle20, new XamlTypeResolver(xmlNamespaceResolver10, typeof(SettingView).GetTypeInfo().Assembly));
		xamlServiceProvider10.Add(typeof(IXmlLineInfoProvider), new XmlLineInfoProvider(new XmlLineInfo(87, 105)));
		extendedButton5.SetValue(fontSizeProperty6, ((IExtendedTypeConverter)fontSizeConverter6).ConvertFromInvariantString("Medium", (IServiceProvider)xamlServiceProvider10));
		extendedButton5.SetValue(Xamarin.Forms.View.HorizontalOptionsProperty, LayoutOptions.StartAndExpand);
		extendedButton5.SetValue(VisualElement.BackgroundColorProperty, Color.Transparent);
		extendedButton5.SetValue(ExtendedButton.HorizontalTextAlignmentProperty, new TextAlignmentConverter().ConvertFromInvariantString("Start"));
		extendedButton5.Effects.Add(fixedFontSizeButtonEffect5);
		VisualDiagnostics.RegisterSourceInfo(fixedFontSizeButtonEffect5, new Uri("Views/SettingView.xaml", UriKind.RelativeOrAbsolute), 89, 22);
		grid5.Children.Add(extendedButton5);
		VisualDiagnostics.RegisterSourceInfo(extendedButton5, new Uri("Views/SettingView.xaml", UriKind.RelativeOrAbsolute), 87, 14);
		extendedButton6.SetValue(Grid.RowProperty, 9);
		extendedButton6.SetValue(Button.TextProperty, "測定器");
		extendedButton6.SetValue(Message.AttachProperty, "Meter");
		BindableProperty fontSizeProperty7 = Button.FontSizeProperty;
		FontSizeConverter fontSizeConverter7 = new FontSizeConverter();
		XamlServiceProvider xamlServiceProvider11 = new XamlServiceProvider();
		Type typeFromHandle21 = typeof(IProvideValueTarget);
		object[] array11 = new object[0 + 4];
		array11[0] = extendedButton6;
		array11[1] = grid5;
		array11[2] = scrollView;
		array11[3] = settingView;
		object service11;
		xamlServiceProvider11.Add(typeFromHandle21, service11 = new SimpleValueTargetProvider(array11, Button.FontSizeProperty, nameScope));
		xamlServiceProvider11.Add(typeof(IReferenceProvider), service11);
		Type typeFromHandle22 = typeof(IXamlTypeResolver);
		XmlNamespaceResolver xmlNamespaceResolver11 = new XmlNamespaceResolver();
		xmlNamespaceResolver11.Add("", "http://xamarin.com/schemas/2014/forms");
		xmlNamespaceResolver11.Add("x", "http://schemas.microsoft.com/winfx/2009/xaml");
		xmlNamespaceResolver11.Add("calx", "clr-namespace:Caliburn.Micro.Xamarin.Forms;assembly=Caliburn.Micro.Platform.Xamarin.Forms");
		xmlNamespaceResolver11.Add("renderer", "clr-namespace:NHL.Views.Renderer");
		xmlNamespaceResolver11.Add("effect", "clr-namespace:NHL.Views.Effect");
		xamlServiceProvider11.Add(typeFromHandle22, new XamlTypeResolver(xmlNamespaceResolver11, typeof(SettingView).GetTypeInfo().Assembly));
		xamlServiceProvider11.Add(typeof(IXmlLineInfoProvider), new XmlLineInfoProvider(new XmlLineInfo(92, 90)));
		extendedButton6.SetValue(fontSizeProperty7, ((IExtendedTypeConverter)fontSizeConverter7).ConvertFromInvariantString("Medium", (IServiceProvider)xamlServiceProvider11));
		extendedButton6.SetValue(Xamarin.Forms.View.HorizontalOptionsProperty, LayoutOptions.StartAndExpand);
		extendedButton6.SetValue(VisualElement.BackgroundColorProperty, Color.Transparent);
		extendedButton6.SetValue(ExtendedButton.HorizontalTextAlignmentProperty, new TextAlignmentConverter().ConvertFromInvariantString("Start"));
		extendedButton6.Effects.Add(fixedFontSizeButtonEffect6);
		VisualDiagnostics.RegisterSourceInfo(fixedFontSizeButtonEffect6, new Uri("Views/SettingView.xaml", UriKind.RelativeOrAbsolute), 94, 22);
		grid5.Children.Add(extendedButton6);
		VisualDiagnostics.RegisterSourceInfo(extendedButton6, new Uri("Views/SettingView.xaml", UriKind.RelativeOrAbsolute), 92, 14);
		extendedButton7.SetValue(Grid.RowProperty, 10);
		extendedButton7.SetValue(Button.TextProperty, "データ共有（施設）");
		extendedButton7.SetValue(Message.AttachProperty, "Hospital");
		BindableProperty fontSizeProperty8 = Button.FontSizeProperty;
		FontSizeConverter fontSizeConverter8 = new FontSizeConverter();
		XamlServiceProvider xamlServiceProvider12 = new XamlServiceProvider();
		Type typeFromHandle23 = typeof(IProvideValueTarget);
		object[] array12 = new object[0 + 4];
		array12[0] = extendedButton7;
		array12[1] = grid5;
		array12[2] = scrollView;
		array12[3] = settingView;
		object service12;
		xamlServiceProvider12.Add(typeFromHandle23, service12 = new SimpleValueTargetProvider(array12, Button.FontSizeProperty, nameScope));
		xamlServiceProvider12.Add(typeof(IReferenceProvider), service12);
		Type typeFromHandle24 = typeof(IXamlTypeResolver);
		XmlNamespaceResolver xmlNamespaceResolver12 = new XmlNamespaceResolver();
		xmlNamespaceResolver12.Add("", "http://xamarin.com/schemas/2014/forms");
		xmlNamespaceResolver12.Add("x", "http://schemas.microsoft.com/winfx/2009/xaml");
		xmlNamespaceResolver12.Add("calx", "clr-namespace:Caliburn.Micro.Xamarin.Forms;assembly=Caliburn.Micro.Platform.Xamarin.Forms");
		xmlNamespaceResolver12.Add("renderer", "clr-namespace:NHL.Views.Renderer");
		xmlNamespaceResolver12.Add("effect", "clr-namespace:NHL.Views.Effect");
		xamlServiceProvider12.Add(typeFromHandle24, new XamlTypeResolver(xmlNamespaceResolver12, typeof(SettingView).GetTypeInfo().Assembly));
		xamlServiceProvider12.Add(typeof(IXmlLineInfoProvider), new XmlLineInfoProvider(new XmlLineInfo(97, 100)));
		extendedButton7.SetValue(fontSizeProperty8, ((IExtendedTypeConverter)fontSizeConverter8).ConvertFromInvariantString("Medium", (IServiceProvider)xamlServiceProvider12));
		extendedButton7.SetValue(Xamarin.Forms.View.HorizontalOptionsProperty, LayoutOptions.StartAndExpand);
		extendedButton7.SetValue(VisualElement.BackgroundColorProperty, Color.Transparent);
		extendedButton7.SetValue(ExtendedButton.HorizontalTextAlignmentProperty, new TextAlignmentConverter().ConvertFromInvariantString("Start"));
		extendedButton7.Effects.Add(fixedFontSizeButtonEffect7);
		VisualDiagnostics.RegisterSourceInfo(fixedFontSizeButtonEffect7, new Uri("Views/SettingView.xaml", UriKind.RelativeOrAbsolute), 99, 22);
		grid5.Children.Add(extendedButton7);
		VisualDiagnostics.RegisterSourceInfo(extendedButton7, new Uri("Views/SettingView.xaml", UriKind.RelativeOrAbsolute), 97, 14);
		extendedButton8.SetValue(Grid.RowProperty, 11);
		extendedButton8.SetValue(Button.TextProperty, "WEB機能（本人用）");
		extendedButton8.SetValue(Message.AttachProperty, "SharerInfo");
		BindableProperty fontSizeProperty9 = Button.FontSizeProperty;
		FontSizeConverter fontSizeConverter9 = new FontSizeConverter();
		XamlServiceProvider xamlServiceProvider13 = new XamlServiceProvider();
		Type typeFromHandle25 = typeof(IProvideValueTarget);
		object[] array13 = new object[0 + 4];
		array13[0] = extendedButton8;
		array13[1] = grid5;
		array13[2] = scrollView;
		array13[3] = settingView;
		object service13;
		xamlServiceProvider13.Add(typeFromHandle25, service13 = new SimpleValueTargetProvider(array13, Button.FontSizeProperty, nameScope));
		xamlServiceProvider13.Add(typeof(IReferenceProvider), service13);
		Type typeFromHandle26 = typeof(IXamlTypeResolver);
		XmlNamespaceResolver xmlNamespaceResolver13 = new XmlNamespaceResolver();
		xmlNamespaceResolver13.Add("", "http://xamarin.com/schemas/2014/forms");
		xmlNamespaceResolver13.Add("x", "http://schemas.microsoft.com/winfx/2009/xaml");
		xmlNamespaceResolver13.Add("calx", "clr-namespace:Caliburn.Micro.Xamarin.Forms;assembly=Caliburn.Micro.Platform.Xamarin.Forms");
		xmlNamespaceResolver13.Add("renderer", "clr-namespace:NHL.Views.Renderer");
		xmlNamespaceResolver13.Add("effect", "clr-namespace:NHL.Views.Effect");
		xamlServiceProvider13.Add(typeFromHandle26, new XamlTypeResolver(xmlNamespaceResolver13, typeof(SettingView).GetTypeInfo().Assembly));
		xamlServiceProvider13.Add(typeof(IXmlLineInfoProvider), new XmlLineInfoProvider(new XmlLineInfo(102, 103)));
		extendedButton8.SetValue(fontSizeProperty9, ((IExtendedTypeConverter)fontSizeConverter9).ConvertFromInvariantString("Medium", (IServiceProvider)xamlServiceProvider13));
		extendedButton8.SetValue(Xamarin.Forms.View.HorizontalOptionsProperty, LayoutOptions.StartAndExpand);
		extendedButton8.SetValue(VisualElement.BackgroundColorProperty, Color.Transparent);
		extendedButton8.SetValue(ExtendedButton.HorizontalTextAlignmentProperty, new TextAlignmentConverter().ConvertFromInvariantString("Start"));
		extendedButton8.Effects.Add(fixedFontSizeButtonEffect8);
		VisualDiagnostics.RegisterSourceInfo(fixedFontSizeButtonEffect8, new Uri("Views/SettingView.xaml", UriKind.RelativeOrAbsolute), 104, 22);
		grid5.Children.Add(extendedButton8);
		VisualDiagnostics.RegisterSourceInfo(extendedButton8, new Uri("Views/SettingView.xaml", UriKind.RelativeOrAbsolute), 102, 14);
		extendedButton9.SetValue(Grid.RowProperty, 12);
		extendedButton9.SetValue(Button.TextProperty, "バックアップコード");
		extendedButton9.SetValue(Message.AttachProperty, "BackupCode");
		BindableProperty fontSizeProperty10 = Button.FontSizeProperty;
		FontSizeConverter fontSizeConverter10 = new FontSizeConverter();
		XamlServiceProvider xamlServiceProvider14 = new XamlServiceProvider();
		Type typeFromHandle27 = typeof(IProvideValueTarget);
		object[] array14 = new object[0 + 4];
		array14[0] = extendedButton9;
		array14[1] = grid5;
		array14[2] = scrollView;
		array14[3] = settingView;
		object service14;
		xamlServiceProvider14.Add(typeFromHandle27, service14 = new SimpleValueTargetProvider(array14, Button.FontSizeProperty, nameScope));
		xamlServiceProvider14.Add(typeof(IReferenceProvider), service14);
		Type typeFromHandle28 = typeof(IXamlTypeResolver);
		XmlNamespaceResolver xmlNamespaceResolver14 = new XmlNamespaceResolver();
		xmlNamespaceResolver14.Add("", "http://xamarin.com/schemas/2014/forms");
		xmlNamespaceResolver14.Add("x", "http://schemas.microsoft.com/winfx/2009/xaml");
		xmlNamespaceResolver14.Add("calx", "clr-namespace:Caliburn.Micro.Xamarin.Forms;assembly=Caliburn.Micro.Platform.Xamarin.Forms");
		xmlNamespaceResolver14.Add("renderer", "clr-namespace:NHL.Views.Renderer");
		xmlNamespaceResolver14.Add("effect", "clr-namespace:NHL.Views.Effect");
		xamlServiceProvider14.Add(typeFromHandle28, new XamlTypeResolver(xmlNamespaceResolver14, typeof(SettingView).GetTypeInfo().Assembly));
		xamlServiceProvider14.Add(typeof(IXmlLineInfoProvider), new XmlLineInfoProvider(new XmlLineInfo(107, 102)));
		extendedButton9.SetValue(fontSizeProperty10, ((IExtendedTypeConverter)fontSizeConverter10).ConvertFromInvariantString("Medium", (IServiceProvider)xamlServiceProvider14));
		extendedButton9.SetValue(Xamarin.Forms.View.HorizontalOptionsProperty, LayoutOptions.StartAndExpand);
		extendedButton9.SetValue(VisualElement.BackgroundColorProperty, Color.Transparent);
		extendedButton9.SetValue(ExtendedButton.HorizontalTextAlignmentProperty, new TextAlignmentConverter().ConvertFromInvariantString("Start"));
		extendedButton9.Effects.Add(fixedFontSizeButtonEffect9);
		VisualDiagnostics.RegisterSourceInfo(fixedFontSizeButtonEffect9, new Uri("Views/SettingView.xaml", UriKind.RelativeOrAbsolute), 109, 22);
		grid5.Children.Add(extendedButton9);
		VisualDiagnostics.RegisterSourceInfo(extendedButton9, new Uri("Views/SettingView.xaml", UriKind.RelativeOrAbsolute), 107, 14);
		extendedButton10.SetValue(Grid.RowProperty, 14);
		extendedButton10.SetValue(Button.TextProperty, "情報");
		extendedButton10.SetValue(Message.AttachProperty, "Information");
		BindableProperty fontSizeProperty11 = Button.FontSizeProperty;
		FontSizeConverter fontSizeConverter11 = new FontSizeConverter();
		XamlServiceProvider xamlServiceProvider15 = new XamlServiceProvider();
		Type typeFromHandle29 = typeof(IProvideValueTarget);
		object[] array15 = new object[0 + 4];
		array15[0] = extendedButton10;
		array15[1] = grid5;
		array15[2] = scrollView;
		array15[3] = settingView;
		object service15;
		xamlServiceProvider15.Add(typeFromHandle29, service15 = new SimpleValueTargetProvider(array15, Button.FontSizeProperty, nameScope));
		xamlServiceProvider15.Add(typeof(IReferenceProvider), service15);
		Type typeFromHandle30 = typeof(IXamlTypeResolver);
		XmlNamespaceResolver xmlNamespaceResolver15 = new XmlNamespaceResolver();
		xmlNamespaceResolver15.Add("", "http://xamarin.com/schemas/2014/forms");
		xmlNamespaceResolver15.Add("x", "http://schemas.microsoft.com/winfx/2009/xaml");
		xmlNamespaceResolver15.Add("calx", "clr-namespace:Caliburn.Micro.Xamarin.Forms;assembly=Caliburn.Micro.Platform.Xamarin.Forms");
		xmlNamespaceResolver15.Add("renderer", "clr-namespace:NHL.Views.Renderer");
		xmlNamespaceResolver15.Add("effect", "clr-namespace:NHL.Views.Effect");
		xamlServiceProvider15.Add(typeFromHandle30, new XamlTypeResolver(xmlNamespaceResolver15, typeof(SettingView).GetTypeInfo().Assembly));
		xamlServiceProvider15.Add(typeof(IXmlLineInfoProvider), new XmlLineInfoProvider(new XmlLineInfo(112, 96)));
		extendedButton10.SetValue(fontSizeProperty11, ((IExtendedTypeConverter)fontSizeConverter11).ConvertFromInvariantString("Medium", (IServiceProvider)xamlServiceProvider15));
		extendedButton10.SetValue(Xamarin.Forms.View.HorizontalOptionsProperty, LayoutOptions.StartAndExpand);
		extendedButton10.SetValue(VisualElement.BackgroundColorProperty, Color.Transparent);
		extendedButton10.SetValue(ExtendedButton.HorizontalTextAlignmentProperty, new TextAlignmentConverter().ConvertFromInvariantString("Start"));
		extendedButton10.Effects.Add(fixedFontSizeButtonEffect10);
		VisualDiagnostics.RegisterSourceInfo(fixedFontSizeButtonEffect10, new Uri("Views/SettingView.xaml", UriKind.RelativeOrAbsolute), 114, 22);
		grid5.Children.Add(extendedButton10);
		VisualDiagnostics.RegisterSourceInfo(extendedButton10, new Uri("Views/SettingView.xaml", UriKind.RelativeOrAbsolute), 112, 14);
		extendedButton11.SetValue(Grid.RowProperty, 15);
		extendedButton11.SetValue(Button.TextProperty, "データ同期");
		extendedButton11.SetValue(Message.AttachProperty, "ManualDataSync");
		BindableProperty fontSizeProperty12 = Button.FontSizeProperty;
		FontSizeConverter fontSizeConverter12 = new FontSizeConverter();
		XamlServiceProvider xamlServiceProvider16 = new XamlServiceProvider();
		Type typeFromHandle31 = typeof(IProvideValueTarget);
		object[] array16 = new object[0 + 4];
		array16[0] = extendedButton11;
		array16[1] = grid5;
		array16[2] = scrollView;
		array16[3] = settingView;
		object service16;
		xamlServiceProvider16.Add(typeFromHandle31, service16 = new SimpleValueTargetProvider(array16, Button.FontSizeProperty, nameScope));
		xamlServiceProvider16.Add(typeof(IReferenceProvider), service16);
		Type typeFromHandle32 = typeof(IXamlTypeResolver);
		XmlNamespaceResolver xmlNamespaceResolver16 = new XmlNamespaceResolver();
		xmlNamespaceResolver16.Add("", "http://xamarin.com/schemas/2014/forms");
		xmlNamespaceResolver16.Add("x", "http://schemas.microsoft.com/winfx/2009/xaml");
		xmlNamespaceResolver16.Add("calx", "clr-namespace:Caliburn.Micro.Xamarin.Forms;assembly=Caliburn.Micro.Platform.Xamarin.Forms");
		xmlNamespaceResolver16.Add("renderer", "clr-namespace:NHL.Views.Renderer");
		xmlNamespaceResolver16.Add("effect", "clr-namespace:NHL.Views.Effect");
		xamlServiceProvider16.Add(typeFromHandle32, new XamlTypeResolver(xmlNamespaceResolver16, typeof(SettingView).GetTypeInfo().Assembly));
		xamlServiceProvider16.Add(typeof(IXmlLineInfoProvider), new XmlLineInfoProvider(new XmlLineInfo(117, 102)));
		extendedButton11.SetValue(fontSizeProperty12, ((IExtendedTypeConverter)fontSizeConverter12).ConvertFromInvariantString("Medium", (IServiceProvider)xamlServiceProvider16));
		extendedButton11.SetValue(Xamarin.Forms.View.HorizontalOptionsProperty, LayoutOptions.StartAndExpand);
		extendedButton11.SetValue(VisualElement.BackgroundColorProperty, Color.Transparent);
		extendedButton11.SetValue(ExtendedButton.HorizontalTextAlignmentProperty, new TextAlignmentConverter().ConvertFromInvariantString("Start"));
		extendedButton11.Effects.Add(fixedFontSizeButtonEffect11);
		VisualDiagnostics.RegisterSourceInfo(fixedFontSizeButtonEffect11, new Uri("Views/SettingView.xaml", UriKind.RelativeOrAbsolute), 119, 22);
		grid5.Children.Add(extendedButton11);
		VisualDiagnostics.RegisterSourceInfo(extendedButton11, new Uri("Views/SettingView.xaml", UriKind.RelativeOrAbsolute), 117, 14);
		extendedButton12.SetValue(Grid.RowProperty, 16);
		extendedButton12.SetValue(Button.TextProperty, "利用規約");
		extendedButton12.SetValue(Message.AttachProperty, "TermsOfService");
		BindableProperty fontSizeProperty13 = Button.FontSizeProperty;
		FontSizeConverter fontSizeConverter13 = new FontSizeConverter();
		XamlServiceProvider xamlServiceProvider17 = new XamlServiceProvider();
		Type typeFromHandle33 = typeof(IProvideValueTarget);
		object[] array17 = new object[0 + 4];
		array17[0] = extendedButton12;
		array17[1] = grid5;
		array17[2] = scrollView;
		array17[3] = settingView;
		object service17;
		xamlServiceProvider17.Add(typeFromHandle33, service17 = new SimpleValueTargetProvider(array17, Button.FontSizeProperty, nameScope));
		xamlServiceProvider17.Add(typeof(IReferenceProvider), service17);
		Type typeFromHandle34 = typeof(IXamlTypeResolver);
		XmlNamespaceResolver xmlNamespaceResolver17 = new XmlNamespaceResolver();
		xmlNamespaceResolver17.Add("", "http://xamarin.com/schemas/2014/forms");
		xmlNamespaceResolver17.Add("x", "http://schemas.microsoft.com/winfx/2009/xaml");
		xmlNamespaceResolver17.Add("calx", "clr-namespace:Caliburn.Micro.Xamarin.Forms;assembly=Caliburn.Micro.Platform.Xamarin.Forms");
		xmlNamespaceResolver17.Add("renderer", "clr-namespace:NHL.Views.Renderer");
		xmlNamespaceResolver17.Add("effect", "clr-namespace:NHL.Views.Effect");
		xamlServiceProvider17.Add(typeFromHandle34, new XamlTypeResolver(xmlNamespaceResolver17, typeof(SettingView).GetTypeInfo().Assembly));
		xamlServiceProvider17.Add(typeof(IXmlLineInfoProvider), new XmlLineInfoProvider(new XmlLineInfo(123, 101)));
		extendedButton12.SetValue(fontSizeProperty13, ((IExtendedTypeConverter)fontSizeConverter13).ConvertFromInvariantString("Medium", (IServiceProvider)xamlServiceProvider17));
		extendedButton12.SetValue(Xamarin.Forms.View.HorizontalOptionsProperty, LayoutOptions.StartAndExpand);
		extendedButton12.SetValue(VisualElement.BackgroundColorProperty, Color.Transparent);
		extendedButton12.SetValue(ExtendedButton.HorizontalTextAlignmentProperty, new TextAlignmentConverter().ConvertFromInvariantString("Start"));
		extendedButton12.Effects.Add(fixedFontSizeButtonEffect12);
		VisualDiagnostics.RegisterSourceInfo(fixedFontSizeButtonEffect12, new Uri("Views/SettingView.xaml", UriKind.RelativeOrAbsolute), 125, 22);
		grid5.Children.Add(extendedButton12);
		VisualDiagnostics.RegisterSourceInfo(extendedButton12, new Uri("Views/SettingView.xaml", UriKind.RelativeOrAbsolute), 123, 14);
		extendedButton13.SetValue(Grid.RowProperty, 18);
		extendedButton13.SetValue(Button.TextProperty, "お問い合わせ");
		extendedButton13.SetValue(Message.AttachProperty, "ContactUs");
		BindableProperty fontSizeProperty14 = Button.FontSizeProperty;
		FontSizeConverter fontSizeConverter14 = new FontSizeConverter();
		XamlServiceProvider xamlServiceProvider18 = new XamlServiceProvider();
		Type typeFromHandle35 = typeof(IProvideValueTarget);
		object[] array18 = new object[0 + 4];
		array18[0] = extendedButton13;
		array18[1] = grid5;
		array18[2] = scrollView;
		array18[3] = settingView;
		object service18;
		xamlServiceProvider18.Add(typeFromHandle35, service18 = new SimpleValueTargetProvider(array18, Button.FontSizeProperty, nameScope));
		xamlServiceProvider18.Add(typeof(IReferenceProvider), service18);
		Type typeFromHandle36 = typeof(IXamlTypeResolver);
		XmlNamespaceResolver xmlNamespaceResolver18 = new XmlNamespaceResolver();
		xmlNamespaceResolver18.Add("", "http://xamarin.com/schemas/2014/forms");
		xmlNamespaceResolver18.Add("x", "http://schemas.microsoft.com/winfx/2009/xaml");
		xmlNamespaceResolver18.Add("calx", "clr-namespace:Caliburn.Micro.Xamarin.Forms;assembly=Caliburn.Micro.Platform.Xamarin.Forms");
		xmlNamespaceResolver18.Add("renderer", "clr-namespace:NHL.Views.Renderer");
		xmlNamespaceResolver18.Add("effect", "clr-namespace:NHL.Views.Effect");
		xamlServiceProvider18.Add(typeFromHandle36, new XamlTypeResolver(xmlNamespaceResolver18, typeof(SettingView).GetTypeInfo().Assembly));
		xamlServiceProvider18.Add(typeof(IXmlLineInfoProvider), new XmlLineInfoProvider(new XmlLineInfo(128, 98)));
		extendedButton13.SetValue(fontSizeProperty14, ((IExtendedTypeConverter)fontSizeConverter14).ConvertFromInvariantString("Medium", (IServiceProvider)xamlServiceProvider18));
		extendedButton13.SetValue(Xamarin.Forms.View.HorizontalOptionsProperty, LayoutOptions.StartAndExpand);
		extendedButton13.SetValue(VisualElement.BackgroundColorProperty, Color.Transparent);
		extendedButton13.SetValue(ExtendedButton.HorizontalTextAlignmentProperty, new TextAlignmentConverter().ConvertFromInvariantString("Start"));
		extendedButton13.Effects.Add(fixedFontSizeButtonEffect13);
		VisualDiagnostics.RegisterSourceInfo(fixedFontSizeButtonEffect13, new Uri("Views/SettingView.xaml", UriKind.RelativeOrAbsolute), 130, 22);
		grid5.Children.Add(extendedButton13);
		VisualDiagnostics.RegisterSourceInfo(extendedButton13, new Uri("Views/SettingView.xaml", UriKind.RelativeOrAbsolute), 128, 14);
		scrollView.Content = grid5;
		VisualDiagnostics.RegisterSourceInfo(grid5, new Uri("Views/SettingView.xaml", UriKind.RelativeOrAbsolute), 29, 10);
		settingView.SetValue(ContentPage.ContentProperty, scrollView);
		VisualDiagnostics.RegisterSourceInfo(scrollView, new Uri("Views/SettingView.xaml", UriKind.RelativeOrAbsolute), 28, 6);
		VisualDiagnostics.RegisterSourceInfo(settingView, new Uri("Views/SettingView.xaml", UriKind.RelativeOrAbsolute), 2, 2);
	}

	private void __InitComponentRuntime()
	{
		this.LoadFromXaml(typeof(SettingView));
	}
}
