using System;
using System.CodeDom.Compiler;
using System.Reflection;
using Caliburn.Micro.Xamarin.Forms;
using NHL.Views.Effect;
using Xamarin.Forms;
using Xamarin.Forms.Internals;
using Xamarin.Forms.Xaml;
using Xamarin.Forms.Xaml.Diagnostics;
using Xamarin.Forms.Xaml.Internals;

namespace NHL.Views;

[XamlCompilation(XamlCompilationOptions.Compile)]
[XamlFilePath("Views/SetupView.xaml")]
public class SetupView : ContentPage
{
	public SetupView()
	{
		InitializeComponent();
	}

	[GeneratedCode("Xamarin.Forms.Build.Tasks.XamlG", "2.0.0.0")]
	private void InitializeComponent()
	{
		if (ResourceLoader.CanProvideContentFor(new ResourceLoader.ResourceLoadingQuery
		{
			AssemblyName = typeof(SetupView).GetTypeInfo().Assembly.GetName(),
			ResourcePath = "Views/SetupView.xaml",
			Instance = this
		}))
		{
			__InitComponentRuntime();
			return;
		}
		if (XamlLoader.XamlFileProvider != null && XamlLoader.XamlFileProvider(GetType()) != null)
		{
			__InitComponentRuntime();
			return;
		}
		StaticResourceExtension staticResourceExtension = new StaticResourceExtension();
		Color color = Color.FromHex("#EFEFF4");
		Color color2 = Color.FromHex("#CFCFCF");
		ResourceDictionary resourceDictionary = new ResourceDictionary();
		ColumnDefinition columnDefinition = new ColumnDefinition();
		ColumnDefinition columnDefinition2 = new ColumnDefinition();
		RowDefinition rowDefinition = new RowDefinition();
		RowDefinition rowDefinition2 = new RowDefinition();
		RowDefinition rowDefinition3 = new RowDefinition();
		RowDefinition rowDefinition4 = new RowDefinition();
		RowDefinition rowDefinition5 = new RowDefinition();
		RowDefinition item = new RowDefinition();
		StaticResourceExtension staticResourceExtension2 = new StaticResourceExtension();
		Grid grid = new Grid();
		StaticResourceExtension staticResourceExtension3 = new StaticResourceExtension();
		Grid grid2 = new Grid();
		Grid grid3 = new Grid();
		Grid grid4 = new Grid();
		FixedFontSizeLabelEffect fixedFontSizeLabelEffect = new FixedFontSizeLabelEffect();
		Label label = new Label();
		FixedFontSizeLabelEffect fixedFontSizeLabelEffect2 = new FixedFontSizeLabelEffect();
		Label label2 = new Label();
		FixedFontSizeButtonEffect fixedFontSizeButtonEffect = new FixedFontSizeButtonEffect();
		Button button = new Button();
		FixedFontSizeLabelEffect fixedFontSizeLabelEffect3 = new FixedFontSizeLabelEffect();
		Label label3 = new Label();
		FixedFontSizeLabelEffect fixedFontSizeLabelEffect4 = new FixedFontSizeLabelEffect();
		Label label4 = new Label();
		FixedFontSizeButtonEffect fixedFontSizeButtonEffect2 = new FixedFontSizeButtonEffect();
		Button button2 = new Button();
		Grid grid5 = new Grid();
		StackLayout stackLayout = new StackLayout();
		SetupView setupView;
		NameScope nameScope = (NameScope)(NameScope.GetNameScope(setupView = this) ?? new NameScope());
		NameScope.SetNameScope(setupView, nameScope);
		setupView.Resources = resourceDictionary;
		VisualDiagnostics.RegisterSourceInfo(resourceDictionary, new Uri("Views/SetupView.xaml", UriKind.RelativeOrAbsolute), 12, 10);
		resourceDictionary.Add("PageBackgroundColor", color);
		resourceDictionary.Add("LineColor", color2);
		setupView.SetValue(NavigationPage.BackButtonTitleProperty, "戻る");
		setupView.SetValue(Page.TitleProperty, "セットアップ");
		staticResourceExtension.Key = "PageBackgroundColor";
		XamlServiceProvider xamlServiceProvider = new XamlServiceProvider();
		Type typeFromHandle = typeof(IProvideValueTarget);
		object[] array = new object[0 + 1];
		array[0] = setupView;
		object service;
		xamlServiceProvider.Add(typeFromHandle, service = new SimpleValueTargetProvider(array, VisualElement.BackgroundColorProperty, nameScope));
		xamlServiceProvider.Add(typeof(IReferenceProvider), service);
		Type typeFromHandle2 = typeof(IXamlTypeResolver);
		XmlNamespaceResolver xmlNamespaceResolver = new XmlNamespaceResolver();
		xmlNamespaceResolver.Add("", "http://xamarin.com/schemas/2014/forms");
		xmlNamespaceResolver.Add("x", "http://schemas.microsoft.com/winfx/2009/xaml");
		xmlNamespaceResolver.Add("calx", "clr-namespace:Caliburn.Micro.Xamarin.Forms;assembly=Caliburn.Micro.Platform.Xamarin.Forms");
		xmlNamespaceResolver.Add("effect", "clr-namespace:NHL.Views.Effect");
		xamlServiceProvider.Add(typeFromHandle2, new XamlTypeResolver(xmlNamespaceResolver, typeof(SetupView).GetTypeInfo().Assembly));
		xamlServiceProvider.Add(typeof(IXmlLineInfoProvider), new XmlLineInfoProvider(new XmlLineInfo(9, 14)));
		object obj = ((IMarkupExtension)staticResourceExtension).ProvideValue((IServiceProvider)xamlServiceProvider);
		setupView.BackgroundColor = (Color)obj;
		VisualDiagnostics.RegisterSourceInfo(obj, new Uri("Views/SetupView.xaml", UriKind.RelativeOrAbsolute), 9, 14);
		setupView.Resources = resourceDictionary;
		VisualDiagnostics.RegisterSourceInfo(resourceDictionary, new Uri("Views/SetupView.xaml", UriKind.RelativeOrAbsolute), 12, 10);
		stackLayout.SetValue(Xamarin.Forms.View.HorizontalOptionsProperty, LayoutOptions.FillAndExpand);
		stackLayout.SetValue(StackLayout.SpacingProperty, 0.0);
		grid5.SetValue(Grid.RowSpacingProperty, 0.0);
		columnDefinition.SetValue(ColumnDefinition.WidthProperty, new GridLengthTypeConverter().ConvertFromInvariantString("*"));
		((DefinitionCollection<ColumnDefinition>)grid5.GetValue(Grid.ColumnDefinitionsProperty)).Add(columnDefinition);
		columnDefinition2.SetValue(ColumnDefinition.WidthProperty, new GridLengthTypeConverter().ConvertFromInvariantString("Auto"));
		((DefinitionCollection<ColumnDefinition>)grid5.GetValue(Grid.ColumnDefinitionsProperty)).Add(columnDefinition2);
		rowDefinition.SetValue(RowDefinition.HeightProperty, new GridLengthTypeConverter().ConvertFromInvariantString("1"));
		((DefinitionCollection<RowDefinition>)grid5.GetValue(Grid.RowDefinitionsProperty)).Add(rowDefinition);
		rowDefinition2.SetValue(RowDefinition.HeightProperty, new GridLengthTypeConverter().ConvertFromInvariantString("Auto"));
		((DefinitionCollection<RowDefinition>)grid5.GetValue(Grid.RowDefinitionsProperty)).Add(rowDefinition2);
		rowDefinition3.SetValue(RowDefinition.HeightProperty, new GridLengthTypeConverter().ConvertFromInvariantString("1"));
		((DefinitionCollection<RowDefinition>)grid5.GetValue(Grid.RowDefinitionsProperty)).Add(rowDefinition3);
		rowDefinition4.SetValue(RowDefinition.HeightProperty, new GridLengthTypeConverter().ConvertFromInvariantString("Auto"));
		((DefinitionCollection<RowDefinition>)grid5.GetValue(Grid.RowDefinitionsProperty)).Add(rowDefinition4);
		rowDefinition5.SetValue(RowDefinition.HeightProperty, new GridLengthTypeConverter().ConvertFromInvariantString("1"));
		((DefinitionCollection<RowDefinition>)grid5.GetValue(Grid.RowDefinitionsProperty)).Add(rowDefinition5);
		((DefinitionCollection<RowDefinition>)grid5.GetValue(Grid.RowDefinitionsProperty)).Add(item);
		grid.SetValue(Grid.RowProperty, 2);
		grid.SetValue(Grid.ColumnSpanProperty, 2);
		staticResourceExtension2.Key = "LineColor";
		XamlServiceProvider xamlServiceProvider2 = new XamlServiceProvider();
		Type typeFromHandle3 = typeof(IProvideValueTarget);
		object[] array2 = new object[0 + 4];
		array2[0] = grid;
		array2[1] = grid5;
		array2[2] = stackLayout;
		array2[3] = setupView;
		object service2;
		xamlServiceProvider2.Add(typeFromHandle3, service2 = new SimpleValueTargetProvider(array2, VisualElement.BackgroundColorProperty, nameScope));
		xamlServiceProvider2.Add(typeof(IReferenceProvider), service2);
		Type typeFromHandle4 = typeof(IXamlTypeResolver);
		XmlNamespaceResolver xmlNamespaceResolver2 = new XmlNamespaceResolver();
		xmlNamespaceResolver2.Add("", "http://xamarin.com/schemas/2014/forms");
		xmlNamespaceResolver2.Add("x", "http://schemas.microsoft.com/winfx/2009/xaml");
		xmlNamespaceResolver2.Add("calx", "clr-namespace:Caliburn.Micro.Xamarin.Forms;assembly=Caliburn.Micro.Platform.Xamarin.Forms");
		xmlNamespaceResolver2.Add("effect", "clr-namespace:NHL.Views.Effect");
		xamlServiceProvider2.Add(typeFromHandle4, new XamlTypeResolver(xmlNamespaceResolver2, typeof(SetupView).GetTypeInfo().Assembly));
		xamlServiceProvider2.Add(typeof(IXmlLineInfoProvider), new XmlLineInfoProvider(new XmlLineInfo(47, 56)));
		object obj2 = ((IMarkupExtension)staticResourceExtension2).ProvideValue((IServiceProvider)xamlServiceProvider2);
		grid.BackgroundColor = (Color)obj2;
		VisualDiagnostics.RegisterSourceInfo(obj2, new Uri("Views/SetupView.xaml", UriKind.RelativeOrAbsolute), 47, 56);
		grid.SetValue(Grid.RowSpacingProperty, 1.0);
		grid.SetValue(Grid.ColumnSpacingProperty, 1.0);
		grid5.Children.Add(grid);
		VisualDiagnostics.RegisterSourceInfo(grid, new Uri("Views/SetupView.xaml", UriKind.RelativeOrAbsolute), 47, 18);
		grid2.SetValue(Grid.RowProperty, 4);
		grid2.SetValue(Grid.ColumnSpanProperty, 2);
		staticResourceExtension3.Key = "LineColor";
		XamlServiceProvider xamlServiceProvider3 = new XamlServiceProvider();
		Type typeFromHandle5 = typeof(IProvideValueTarget);
		object[] array3 = new object[0 + 4];
		array3[0] = grid2;
		array3[1] = grid5;
		array3[2] = stackLayout;
		array3[3] = setupView;
		object service3;
		xamlServiceProvider3.Add(typeFromHandle5, service3 = new SimpleValueTargetProvider(array3, VisualElement.BackgroundColorProperty, nameScope));
		xamlServiceProvider3.Add(typeof(IReferenceProvider), service3);
		Type typeFromHandle6 = typeof(IXamlTypeResolver);
		XmlNamespaceResolver xmlNamespaceResolver3 = new XmlNamespaceResolver();
		xmlNamespaceResolver3.Add("", "http://xamarin.com/schemas/2014/forms");
		xmlNamespaceResolver3.Add("x", "http://schemas.microsoft.com/winfx/2009/xaml");
		xmlNamespaceResolver3.Add("calx", "clr-namespace:Caliburn.Micro.Xamarin.Forms;assembly=Caliburn.Micro.Platform.Xamarin.Forms");
		xmlNamespaceResolver3.Add("effect", "clr-namespace:NHL.Views.Effect");
		xamlServiceProvider3.Add(typeFromHandle6, new XamlTypeResolver(xmlNamespaceResolver3, typeof(SetupView).GetTypeInfo().Assembly));
		xamlServiceProvider3.Add(typeof(IXmlLineInfoProvider), new XmlLineInfoProvider(new XmlLineInfo(48, 56)));
		object obj3 = ((IMarkupExtension)staticResourceExtension3).ProvideValue((IServiceProvider)xamlServiceProvider3);
		grid2.BackgroundColor = (Color)obj3;
		VisualDiagnostics.RegisterSourceInfo(obj3, new Uri("Views/SetupView.xaml", UriKind.RelativeOrAbsolute), 48, 56);
		grid2.SetValue(Grid.RowSpacingProperty, 1.0);
		grid2.SetValue(Grid.ColumnSpacingProperty, 1.0);
		grid5.Children.Add(grid2);
		VisualDiagnostics.RegisterSourceInfo(grid2, new Uri("Views/SetupView.xaml", UriKind.RelativeOrAbsolute), 48, 18);
		grid3.SetValue(Grid.RowProperty, 1);
		grid3.SetValue(Grid.ColumnProperty, 0);
		grid3.SetValue(Grid.ColumnSpanProperty, 2);
		grid3.SetValue(VisualElement.BackgroundColorProperty, Color.White);
		grid5.Children.Add(grid3);
		VisualDiagnostics.RegisterSourceInfo(grid3, new Uri("Views/SetupView.xaml", UriKind.RelativeOrAbsolute), 50, 18);
		grid4.SetValue(Grid.RowProperty, 3);
		grid4.SetValue(Grid.ColumnProperty, 0);
		grid4.SetValue(Grid.ColumnSpanProperty, 2);
		grid4.SetValue(VisualElement.BackgroundColorProperty, Color.White);
		grid5.Children.Add(grid4);
		VisualDiagnostics.RegisterSourceInfo(grid4, new Uri("Views/SetupView.xaml", UriKind.RelativeOrAbsolute), 51, 18);
		label.SetValue(Grid.RowProperty, 1);
		label.SetValue(Grid.ColumnProperty, 0);
		label.SetValue(Xamarin.Forms.View.MarginProperty, new Thickness(10.0, 0.0, 0.0, 0.0));
		label.SetValue(Label.TextProperty, "新規に利用を開始");
		BindableProperty fontSizeProperty = Label.FontSizeProperty;
		FontSizeConverter fontSizeConverter = new FontSizeConverter();
		XamlServiceProvider xamlServiceProvider4 = new XamlServiceProvider();
		Type typeFromHandle7 = typeof(IProvideValueTarget);
		object[] array4 = new object[0 + 4];
		array4[0] = label;
		array4[1] = grid5;
		array4[2] = stackLayout;
		array4[3] = setupView;
		object service4;
		xamlServiceProvider4.Add(typeFromHandle7, service4 = new SimpleValueTargetProvider(array4, Label.FontSizeProperty, nameScope));
		xamlServiceProvider4.Add(typeof(IReferenceProvider), service4);
		Type typeFromHandle8 = typeof(IXamlTypeResolver);
		XmlNamespaceResolver xmlNamespaceResolver4 = new XmlNamespaceResolver();
		xmlNamespaceResolver4.Add("", "http://xamarin.com/schemas/2014/forms");
		xmlNamespaceResolver4.Add("x", "http://schemas.microsoft.com/winfx/2009/xaml");
		xmlNamespaceResolver4.Add("calx", "clr-namespace:Caliburn.Micro.Xamarin.Forms;assembly=Caliburn.Micro.Platform.Xamarin.Forms");
		xmlNamespaceResolver4.Add("effect", "clr-namespace:NHL.Views.Effect");
		xamlServiceProvider4.Add(typeFromHandle8, new XamlTypeResolver(xmlNamespaceResolver4, typeof(SetupView).GetTypeInfo().Assembly));
		xamlServiceProvider4.Add(typeof(IXmlLineInfoProvider), new XmlLineInfoProvider(new XmlLineInfo(53, 88)));
		label.SetValue(fontSizeProperty, ((IExtendedTypeConverter)fontSizeConverter).ConvertFromInvariantString("Large", (IServiceProvider)xamlServiceProvider4));
		label.SetValue(Label.VerticalTextAlignmentProperty, new TextAlignmentConverter().ConvertFromInvariantString("Center"));
		label.SetValue(Xamarin.Forms.View.VerticalOptionsProperty, LayoutOptions.CenterAndExpand);
		label.SetValue(VisualElement.BackgroundColorProperty, Color.White);
		label.Effects.Add(fixedFontSizeLabelEffect);
		VisualDiagnostics.RegisterSourceInfo(fixedFontSizeLabelEffect, new Uri("Views/SetupView.xaml", UriKind.RelativeOrAbsolute), 55, 26);
		grid5.Children.Add(label);
		VisualDiagnostics.RegisterSourceInfo(label, new Uri("Views/SetupView.xaml", UriKind.RelativeOrAbsolute), 53, 18);
		label2.SetValue(Grid.RowProperty, 1);
		label2.SetValue(Grid.ColumnProperty, 1);
		label2.SetValue(Label.TextProperty, "＞");
		BindableProperty fontSizeProperty2 = Label.FontSizeProperty;
		FontSizeConverter fontSizeConverter2 = new FontSizeConverter();
		XamlServiceProvider xamlServiceProvider5 = new XamlServiceProvider();
		Type typeFromHandle9 = typeof(IProvideValueTarget);
		object[] array5 = new object[0 + 4];
		array5[0] = label2;
		array5[1] = grid5;
		array5[2] = stackLayout;
		array5[3] = setupView;
		object service5;
		xamlServiceProvider5.Add(typeFromHandle9, service5 = new SimpleValueTargetProvider(array5, Label.FontSizeProperty, nameScope));
		xamlServiceProvider5.Add(typeof(IReferenceProvider), service5);
		Type typeFromHandle10 = typeof(IXamlTypeResolver);
		XmlNamespaceResolver xmlNamespaceResolver5 = new XmlNamespaceResolver();
		xmlNamespaceResolver5.Add("", "http://xamarin.com/schemas/2014/forms");
		xmlNamespaceResolver5.Add("x", "http://schemas.microsoft.com/winfx/2009/xaml");
		xmlNamespaceResolver5.Add("calx", "clr-namespace:Caliburn.Micro.Xamarin.Forms;assembly=Caliburn.Micro.Platform.Xamarin.Forms");
		xmlNamespaceResolver5.Add("effect", "clr-namespace:NHL.Views.Effect");
		xamlServiceProvider5.Add(typeFromHandle10, new XamlTypeResolver(xmlNamespaceResolver5, typeof(SetupView).GetTypeInfo().Assembly));
		xamlServiceProvider5.Add(typeof(IXmlLineInfoProvider), new XmlLineInfoProvider(new XmlLineInfo(58, 62)));
		label2.SetValue(fontSizeProperty2, ((IExtendedTypeConverter)fontSizeConverter2).ConvertFromInvariantString("Large", (IServiceProvider)xamlServiceProvider5));
		label2.SetValue(Label.VerticalTextAlignmentProperty, new TextAlignmentConverter().ConvertFromInvariantString("Center"));
		label2.SetValue(Xamarin.Forms.View.VerticalOptionsProperty, LayoutOptions.CenterAndExpand);
		label2.Effects.Add(fixedFontSizeLabelEffect2);
		VisualDiagnostics.RegisterSourceInfo(fixedFontSizeLabelEffect2, new Uri("Views/SetupView.xaml", UriKind.RelativeOrAbsolute), 60, 26);
		grid5.Children.Add(label2);
		VisualDiagnostics.RegisterSourceInfo(label2, new Uri("Views/SetupView.xaml", UriKind.RelativeOrAbsolute), 58, 18);
		button.SetValue(Grid.RowProperty, 1);
		button.SetValue(Grid.ColumnProperty, 0);
		button.SetValue(Grid.ColumnSpanProperty, 2);
		button.SetValue(VisualElement.BackgroundColorProperty, Color.Transparent);
		button.SetValue(Button.BorderColorProperty, Color.Transparent);
		button.SetValue(Button.BorderWidthProperty, 0.0);
		button.SetValue(Message.AttachProperty, "StartNew");
		button.Effects.Add(fixedFontSizeButtonEffect);
		VisualDiagnostics.RegisterSourceInfo(fixedFontSizeButtonEffect, new Uri("Views/SetupView.xaml", UriKind.RelativeOrAbsolute), 65, 26);
		grid5.Children.Add(button);
		VisualDiagnostics.RegisterSourceInfo(button, new Uri("Views/SetupView.xaml", UriKind.RelativeOrAbsolute), 63, 18);
		label3.SetValue(Grid.RowProperty, 3);
		label3.SetValue(Grid.ColumnProperty, 0);
		label3.SetValue(Xamarin.Forms.View.MarginProperty, new Thickness(10.0, 0.0, 0.0, 0.0));
		label3.SetValue(Label.TextProperty, "バックアップコードから復元");
		BindableProperty fontSizeProperty3 = Label.FontSizeProperty;
		FontSizeConverter fontSizeConverter3 = new FontSizeConverter();
		XamlServiceProvider xamlServiceProvider6 = new XamlServiceProvider();
		Type typeFromHandle11 = typeof(IProvideValueTarget);
		object[] array6 = new object[0 + 4];
		array6[0] = label3;
		array6[1] = grid5;
		array6[2] = stackLayout;
		array6[3] = setupView;
		object service6;
		xamlServiceProvider6.Add(typeFromHandle11, service6 = new SimpleValueTargetProvider(array6, Label.FontSizeProperty, nameScope));
		xamlServiceProvider6.Add(typeof(IReferenceProvider), service6);
		Type typeFromHandle12 = typeof(IXamlTypeResolver);
		XmlNamespaceResolver xmlNamespaceResolver6 = new XmlNamespaceResolver();
		xmlNamespaceResolver6.Add("", "http://xamarin.com/schemas/2014/forms");
		xmlNamespaceResolver6.Add("x", "http://schemas.microsoft.com/winfx/2009/xaml");
		xmlNamespaceResolver6.Add("calx", "clr-namespace:Caliburn.Micro.Xamarin.Forms;assembly=Caliburn.Micro.Platform.Xamarin.Forms");
		xmlNamespaceResolver6.Add("effect", "clr-namespace:NHL.Views.Effect");
		xamlServiceProvider6.Add(typeFromHandle12, new XamlTypeResolver(xmlNamespaceResolver6, typeof(SetupView).GetTypeInfo().Assembly));
		xamlServiceProvider6.Add(typeof(IXmlLineInfoProvider), new XmlLineInfoProvider(new XmlLineInfo(69, 93)));
		label3.SetValue(fontSizeProperty3, ((IExtendedTypeConverter)fontSizeConverter3).ConvertFromInvariantString("Large", (IServiceProvider)xamlServiceProvider6));
		label3.SetValue(Label.VerticalTextAlignmentProperty, new TextAlignmentConverter().ConvertFromInvariantString("Center"));
		label3.SetValue(Xamarin.Forms.View.VerticalOptionsProperty, LayoutOptions.CenterAndExpand);
		label3.SetValue(VisualElement.BackgroundColorProperty, Color.White);
		label3.Effects.Add(fixedFontSizeLabelEffect3);
		VisualDiagnostics.RegisterSourceInfo(fixedFontSizeLabelEffect3, new Uri("Views/SetupView.xaml", UriKind.RelativeOrAbsolute), 71, 26);
		grid5.Children.Add(label3);
		VisualDiagnostics.RegisterSourceInfo(label3, new Uri("Views/SetupView.xaml", UriKind.RelativeOrAbsolute), 69, 18);
		label4.SetValue(Grid.RowProperty, 3);
		label4.SetValue(Grid.ColumnProperty, 1);
		label4.SetValue(Label.TextProperty, "＞");
		BindableProperty fontSizeProperty4 = Label.FontSizeProperty;
		FontSizeConverter fontSizeConverter4 = new FontSizeConverter();
		XamlServiceProvider xamlServiceProvider7 = new XamlServiceProvider();
		Type typeFromHandle13 = typeof(IProvideValueTarget);
		object[] array7 = new object[0 + 4];
		array7[0] = label4;
		array7[1] = grid5;
		array7[2] = stackLayout;
		array7[3] = setupView;
		object service7;
		xamlServiceProvider7.Add(typeFromHandle13, service7 = new SimpleValueTargetProvider(array7, Label.FontSizeProperty, nameScope));
		xamlServiceProvider7.Add(typeof(IReferenceProvider), service7);
		Type typeFromHandle14 = typeof(IXamlTypeResolver);
		XmlNamespaceResolver xmlNamespaceResolver7 = new XmlNamespaceResolver();
		xmlNamespaceResolver7.Add("", "http://xamarin.com/schemas/2014/forms");
		xmlNamespaceResolver7.Add("x", "http://schemas.microsoft.com/winfx/2009/xaml");
		xmlNamespaceResolver7.Add("calx", "clr-namespace:Caliburn.Micro.Xamarin.Forms;assembly=Caliburn.Micro.Platform.Xamarin.Forms");
		xmlNamespaceResolver7.Add("effect", "clr-namespace:NHL.Views.Effect");
		xamlServiceProvider7.Add(typeFromHandle14, new XamlTypeResolver(xmlNamespaceResolver7, typeof(SetupView).GetTypeInfo().Assembly));
		xamlServiceProvider7.Add(typeof(IXmlLineInfoProvider), new XmlLineInfoProvider(new XmlLineInfo(74, 62)));
		label4.SetValue(fontSizeProperty4, ((IExtendedTypeConverter)fontSizeConverter4).ConvertFromInvariantString("Large", (IServiceProvider)xamlServiceProvider7));
		label4.SetValue(Label.VerticalTextAlignmentProperty, new TextAlignmentConverter().ConvertFromInvariantString("Center"));
		label4.SetValue(Xamarin.Forms.View.VerticalOptionsProperty, LayoutOptions.CenterAndExpand);
		label4.Effects.Add(fixedFontSizeLabelEffect4);
		VisualDiagnostics.RegisterSourceInfo(fixedFontSizeLabelEffect4, new Uri("Views/SetupView.xaml", UriKind.RelativeOrAbsolute), 76, 26);
		grid5.Children.Add(label4);
		VisualDiagnostics.RegisterSourceInfo(label4, new Uri("Views/SetupView.xaml", UriKind.RelativeOrAbsolute), 74, 18);
		button2.SetValue(Grid.RowProperty, 3);
		button2.SetValue(Grid.ColumnProperty, 0);
		button2.SetValue(Grid.ColumnSpanProperty, 2);
		button2.SetValue(VisualElement.BackgroundColorProperty, Color.Transparent);
		button2.SetValue(Button.BorderColorProperty, Color.Transparent);
		button2.SetValue(Button.BorderWidthProperty, 0.0);
		button2.SetValue(Message.AttachProperty, "Restore");
		button2.Effects.Add(fixedFontSizeButtonEffect2);
		VisualDiagnostics.RegisterSourceInfo(fixedFontSizeButtonEffect2, new Uri("Views/SetupView.xaml", UriKind.RelativeOrAbsolute), 81, 26);
		grid5.Children.Add(button2);
		VisualDiagnostics.RegisterSourceInfo(button2, new Uri("Views/SetupView.xaml", UriKind.RelativeOrAbsolute), 79, 18);
		stackLayout.Children.Add(grid5);
		VisualDiagnostics.RegisterSourceInfo(grid5, new Uri("Views/SetupView.xaml", UriKind.RelativeOrAbsolute), 33, 14);
		setupView.SetValue(ContentPage.ContentProperty, stackLayout);
		VisualDiagnostics.RegisterSourceInfo(stackLayout, new Uri("Views/SetupView.xaml", UriKind.RelativeOrAbsolute), 32, 10);
		VisualDiagnostics.RegisterSourceInfo(setupView, new Uri("Views/SetupView.xaml", UriKind.RelativeOrAbsolute), 2, 2);
	}

	private void __InitComponentRuntime()
	{
		this.LoadFromXaml(typeof(SetupView));
	}
}
