using System;
using System.CodeDom.Compiler;
using System.Reflection;
using Caliburn.Micro.Xamarin.Forms;
using NHL.Views.Converters;
using NHL.Views.Effect;
using Xamarin.Forms;
using Xamarin.Forms.Internals;
using Xamarin.Forms.Xaml;
using Xamarin.Forms.Xaml.Diagnostics;
using Xamarin.Forms.Xaml.Internals;

namespace NHL.Views;

[XamlCompilation(XamlCompilationOptions.Compile)]
[XamlFilePath("Views/SharerRegisterView.xaml")]
public class SharerRegisterView : ContentPage
{
	public SharerRegisterView()
	{
		InitializeComponent();
	}

	[GeneratedCode("Xamarin.Forms.Build.Tasks.XamlG", "2.0.0.0")]
	private void InitializeComponent()
	{
		if (ResourceLoader.CanProvideContentFor(new ResourceLoader.ResourceLoadingQuery
		{
			AssemblyName = typeof(SharerRegisterView).GetTypeInfo().Assembly.GetName(),
			ResourcePath = "Views/SharerRegisterView.xaml",
			Instance = this
		}))
		{
			__InitComponentRuntime();
			return;
		}
		if (XamlLoader.XamlFileProvider != null && XamlLoader.XamlFileProvider(GetType()) != null)
		{
			__InitComponentRuntime();
			return;
		}
		StaticResourceExtension staticResourceExtension = new StaticResourceExtension();
		BooleanSwitchConverter value = new BooleanSwitchConverter();
		Color color = Color.FromHex("#EFEFF4");
		Color color2 = Color.FromHex("#5B9BD5");
		Color color3 = Color.FromHex("#CFCFCF");
		Color color4 = Color.FromHex("#B4B4B4");
		ResourceDictionary resourceDictionary = new ResourceDictionary();
		ColumnDefinition columnDefinition = new ColumnDefinition();
		ColumnDefinition columnDefinition2 = new ColumnDefinition();
		RowDefinition rowDefinition = new RowDefinition();
		RowDefinition rowDefinition2 = new RowDefinition();
		RowDefinition rowDefinition3 = new RowDefinition();
		RowDefinition rowDefinition4 = new RowDefinition();
		RowDefinition rowDefinition5 = new RowDefinition();
		RowDefinition rowDefinition6 = new RowDefinition();
		RowDefinition rowDefinition7 = new RowDefinition();
		RowDefinition rowDefinition8 = new RowDefinition();
		RowDefinition rowDefinition9 = new RowDefinition();
		RowDefinition rowDefinition10 = new RowDefinition();
		RowDefinition rowDefinition11 = new RowDefinition();
		StaticResourceExtension staticResourceExtension2 = new StaticResourceExtension();
		Grid grid = new Grid();
		StaticResourceExtension staticResourceExtension3 = new StaticResourceExtension();
		Grid grid2 = new Grid();
		StaticResourceExtension staticResourceExtension4 = new StaticResourceExtension();
		Grid grid3 = new Grid();
		StaticResourceExtension staticResourceExtension5 = new StaticResourceExtension();
		Grid grid4 = new Grid();
		Grid grid5 = new Grid();
		Grid grid6 = new Grid();
		Grid grid7 = new Grid();
		Grid grid8 = new Grid();
		Grid grid9 = new Grid();
		Grid grid10 = new Grid();
		FixedFontSizeLabelEffect fixedFontSizeLabelEffect = new FixedFontSizeLabelEffect();
		Label label = new Label();
		BindingExtension bindingExtension = new BindingExtension();
		BindingExtension bindingExtension2 = new BindingExtension();
		FixedFontSizeTextBoxEffect fixedFontSizeTextBoxEffect = new FixedFontSizeTextBoxEffect();
		Entry entry = new Entry();
		FixedFontSizeLabelEffect fixedFontSizeLabelEffect2 = new FixedFontSizeLabelEffect();
		Label label2 = new Label();
		BindingExtension bindingExtension3 = new BindingExtension();
		BindingExtension bindingExtension4 = new BindingExtension();
		FixedFontSizeTextBoxEffect fixedFontSizeTextBoxEffect2 = new FixedFontSizeTextBoxEffect();
		Entry entry2 = new Entry();
		FixedFontSizeLabelEffect fixedFontSizeLabelEffect3 = new FixedFontSizeLabelEffect();
		Label label3 = new Label();
		BindingExtension bindingExtension5 = new BindingExtension();
		BindingExtension bindingExtension6 = new BindingExtension();
		FixedFontSizeTextBoxEffect fixedFontSizeTextBoxEffect3 = new FixedFontSizeTextBoxEffect();
		Entry entry3 = new Entry();
		FixedFontSizeLabelEffect fixedFontSizeLabelEffect4 = new FixedFontSizeLabelEffect();
		Span span = new Span();
		Span span2 = new Span();
		FormattedString formattedString = new FormattedString();
		Label label4 = new Label();
		BindingExtension bindingExtension7 = new BindingExtension();
		BindingExtension bindingExtension8 = new BindingExtension();
		FixedFontSizeTextBoxEffect fixedFontSizeTextBoxEffect4 = new FixedFontSizeTextBoxEffect();
		Entry entry4 = new Entry();
		FixedFontSizeLabelEffect fixedFontSizeLabelEffect5 = new FixedFontSizeLabelEffect();
		Span span3 = new Span();
		string newLine = Environment.NewLine;
		Span span4 = new Span();
		Span span5 = new Span();
		FormattedString formattedString2 = new FormattedString();
		Label label5 = new Label();
		StaticResourceExtension staticResourceExtension6 = new StaticResourceExtension();
		StaticResourceExtension staticResourceExtension7 = new StaticResourceExtension();
		BindingExtension bindingExtension9 = new BindingExtension();
		BindingExtension bindingExtension10 = new BindingExtension();
		FixedFontSizeButtonEffect fixedFontSizeButtonEffect = new FixedFontSizeButtonEffect();
		Button button = new Button();
		StaticResourceExtension staticResourceExtension8 = new StaticResourceExtension();
		BindingExtension bindingExtension11 = new BindingExtension();
		BindingExtension bindingExtension12 = new BindingExtension();
		FixedFontSizeButtonEffect fixedFontSizeButtonEffect2 = new FixedFontSizeButtonEffect();
		Button button2 = new Button();
		Grid grid11 = new Grid();
		StackLayout stackLayout = new StackLayout();
		ScrollView scrollView = new ScrollView();
		SharerRegisterView sharerRegisterView;
		NameScope nameScope = (NameScope)(NameScope.GetNameScope(sharerRegisterView = this) ?? new NameScope());
		NameScope.SetNameScope(sharerRegisterView, nameScope);
		sharerRegisterView.Resources = resourceDictionary;
		VisualDiagnostics.RegisterSourceInfo(resourceDictionary, new Uri("Views/SharerRegisterView.xaml", UriKind.RelativeOrAbsolute), 17, 10);
		resourceDictionary.Add("BooleanSwitchConverter", value);
		resourceDictionary.Add("PageBackgroundColor", color);
		resourceDictionary.Add("ButtonColor", color2);
		resourceDictionary.Add("LineColor", color3);
		resourceDictionary.Add("LabelColor", color4);
		sharerRegisterView.SetValue(NavigationPage.HasBackButtonProperty, true);
		sharerRegisterView.SetValue(NavigationPage.BackButtonTitleProperty, "戻る");
		sharerRegisterView.SetValue(Page.TitleProperty, "アカウント登録");
		staticResourceExtension.Key = "PageBackgroundColor";
		XamlServiceProvider xamlServiceProvider = new XamlServiceProvider();
		Type typeFromHandle = typeof(IProvideValueTarget);
		object[] array = new object[0 + 1];
		array[0] = sharerRegisterView;
		object service;
		xamlServiceProvider.Add(typeFromHandle, service = new SimpleValueTargetProvider(array, VisualElement.BackgroundColorProperty, nameScope));
		xamlServiceProvider.Add(typeof(IReferenceProvider), service);
		Type typeFromHandle2 = typeof(IXamlTypeResolver);
		XmlNamespaceResolver xmlNamespaceResolver = new XmlNamespaceResolver();
		xmlNamespaceResolver.Add("", "http://xamarin.com/schemas/2014/forms");
		xmlNamespaceResolver.Add("x", "http://schemas.microsoft.com/winfx/2009/xaml");
		xmlNamespaceResolver.Add("calx", "clr-namespace:Caliburn.Micro.Xamarin.Forms;assembly=Caliburn.Micro.Platform.Xamarin.Forms");
		xmlNamespaceResolver.Add("renderer", "clr-namespace:NHL.Views.Renderer");
		xmlNamespaceResolver.Add("converter", "clr-namespace:NHL.Views.Converters");
		xmlNamespaceResolver.Add("effect", "clr-namespace:NHL.Views.Effect");
		xmlNamespaceResolver.Add("system", "clr-namespace:System;assembly=System.Runtime.Extensions");
		xamlServiceProvider.Add(typeFromHandle2, new XamlTypeResolver(xmlNamespaceResolver, typeof(SharerRegisterView).GetTypeInfo().Assembly));
		xamlServiceProvider.Add(typeof(IXmlLineInfoProvider), new XmlLineInfoProvider(new XmlLineInfo(14, 14)));
		object obj = ((IMarkupExtension)staticResourceExtension).ProvideValue((IServiceProvider)xamlServiceProvider);
		sharerRegisterView.BackgroundColor = (Color)obj;
		VisualDiagnostics.RegisterSourceInfo(obj, new Uri("Views/SharerRegisterView.xaml", UriKind.RelativeOrAbsolute), 14, 14);
		sharerRegisterView.Resources = resourceDictionary;
		VisualDiagnostics.RegisterSourceInfo(resourceDictionary, new Uri("Views/SharerRegisterView.xaml", UriKind.RelativeOrAbsolute), 17, 10);
		scrollView.SetValue(Xamarin.Forms.View.VerticalOptionsProperty, LayoutOptions.FillAndExpand);
		scrollView.SetValue(Xamarin.Forms.View.HorizontalOptionsProperty, LayoutOptions.FillAndExpand);
		stackLayout.SetValue(StackLayout.OrientationProperty, StackOrientation.Vertical);
		grid11.SetValue(Grid.RowSpacingProperty, 0.0);
		columnDefinition.SetValue(ColumnDefinition.WidthProperty, new GridLengthTypeConverter().ConvertFromInvariantString("Auto"));
		((DefinitionCollection<ColumnDefinition>)grid11.GetValue(Grid.ColumnDefinitionsProperty)).Add(columnDefinition);
		columnDefinition2.SetValue(ColumnDefinition.WidthProperty, new GridLengthTypeConverter().ConvertFromInvariantString("*"));
		((DefinitionCollection<ColumnDefinition>)grid11.GetValue(Grid.ColumnDefinitionsProperty)).Add(columnDefinition2);
		rowDefinition.SetValue(RowDefinition.HeightProperty, new GridLengthTypeConverter().ConvertFromInvariantString("1"));
		((DefinitionCollection<RowDefinition>)grid11.GetValue(Grid.RowDefinitionsProperty)).Add(rowDefinition);
		rowDefinition2.SetValue(RowDefinition.HeightProperty, new GridLengthTypeConverter().ConvertFromInvariantString("Auto"));
		((DefinitionCollection<RowDefinition>)grid11.GetValue(Grid.RowDefinitionsProperty)).Add(rowDefinition2);
		rowDefinition3.SetValue(RowDefinition.HeightProperty, new GridLengthTypeConverter().ConvertFromInvariantString("1"));
		((DefinitionCollection<RowDefinition>)grid11.GetValue(Grid.RowDefinitionsProperty)).Add(rowDefinition3);
		rowDefinition4.SetValue(RowDefinition.HeightProperty, new GridLengthTypeConverter().ConvertFromInvariantString("Auto"));
		((DefinitionCollection<RowDefinition>)grid11.GetValue(Grid.RowDefinitionsProperty)).Add(rowDefinition4);
		rowDefinition5.SetValue(RowDefinition.HeightProperty, new GridLengthTypeConverter().ConvertFromInvariantString("1"));
		((DefinitionCollection<RowDefinition>)grid11.GetValue(Grid.RowDefinitionsProperty)).Add(rowDefinition5);
		rowDefinition6.SetValue(RowDefinition.HeightProperty, new GridLengthTypeConverter().ConvertFromInvariantString("Auto"));
		((DefinitionCollection<RowDefinition>)grid11.GetValue(Grid.RowDefinitionsProperty)).Add(rowDefinition6);
		rowDefinition7.SetValue(RowDefinition.HeightProperty, new GridLengthTypeConverter().ConvertFromInvariantString("1"));
		((DefinitionCollection<RowDefinition>)grid11.GetValue(Grid.RowDefinitionsProperty)).Add(rowDefinition7);
		rowDefinition8.SetValue(RowDefinition.HeightProperty, new GridLengthTypeConverter().ConvertFromInvariantString("Auto"));
		((DefinitionCollection<RowDefinition>)grid11.GetValue(Grid.RowDefinitionsProperty)).Add(rowDefinition8);
		rowDefinition9.SetValue(RowDefinition.HeightProperty, new GridLengthTypeConverter().ConvertFromInvariantString("1"));
		((DefinitionCollection<RowDefinition>)grid11.GetValue(Grid.RowDefinitionsProperty)).Add(rowDefinition9);
		rowDefinition10.SetValue(RowDefinition.HeightProperty, new GridLengthTypeConverter().ConvertFromInvariantString("Auto"));
		((DefinitionCollection<RowDefinition>)grid11.GetValue(Grid.RowDefinitionsProperty)).Add(rowDefinition10);
		rowDefinition11.SetValue(RowDefinition.HeightProperty, new GridLengthTypeConverter().ConvertFromInvariantString("Auto"));
		((DefinitionCollection<RowDefinition>)grid11.GetValue(Grid.RowDefinitionsProperty)).Add(rowDefinition11);
		grid.SetValue(Grid.RowProperty, 2);
		grid.SetValue(Grid.ColumnProperty, 0);
		grid.SetValue(Grid.ColumnSpanProperty, 2);
		staticResourceExtension2.Key = "LineColor";
		XamlServiceProvider xamlServiceProvider2 = new XamlServiceProvider();
		Type typeFromHandle3 = typeof(IProvideValueTarget);
		object[] array2 = new object[0 + 5];
		array2[0] = grid;
		array2[1] = grid11;
		array2[2] = stackLayout;
		array2[3] = scrollView;
		array2[4] = sharerRegisterView;
		object service2;
		xamlServiceProvider2.Add(typeFromHandle3, service2 = new SimpleValueTargetProvider(array2, VisualElement.BackgroundColorProperty, nameScope));
		xamlServiceProvider2.Add(typeof(IReferenceProvider), service2);
		Type typeFromHandle4 = typeof(IXamlTypeResolver);
		XmlNamespaceResolver xmlNamespaceResolver2 = new XmlNamespaceResolver();
		xmlNamespaceResolver2.Add("", "http://xamarin.com/schemas/2014/forms");
		xmlNamespaceResolver2.Add("x", "http://schemas.microsoft.com/winfx/2009/xaml");
		xmlNamespaceResolver2.Add("calx", "clr-namespace:Caliburn.Micro.Xamarin.Forms;assembly=Caliburn.Micro.Platform.Xamarin.Forms");
		xmlNamespaceResolver2.Add("renderer", "clr-namespace:NHL.Views.Renderer");
		xmlNamespaceResolver2.Add("converter", "clr-namespace:NHL.Views.Converters");
		xmlNamespaceResolver2.Add("effect", "clr-namespace:NHL.Views.Effect");
		xmlNamespaceResolver2.Add("system", "clr-namespace:System;assembly=System.Runtime.Extensions");
		xamlServiceProvider2.Add(typeFromHandle4, new XamlTypeResolver(xmlNamespaceResolver2, typeof(SharerRegisterView).GetTypeInfo().Assembly));
		xamlServiceProvider2.Add(typeof(IXmlLineInfoProvider), new XmlLineInfoProvider(new XmlLineInfo(72, 72)));
		object obj2 = ((IMarkupExtension)staticResourceExtension2).ProvideValue((IServiceProvider)xamlServiceProvider2);
		grid.BackgroundColor = (Color)obj2;
		VisualDiagnostics.RegisterSourceInfo(obj2, new Uri("Views/SharerRegisterView.xaml", UriKind.RelativeOrAbsolute), 72, 72);
		grid.SetValue(Grid.RowSpacingProperty, 0.0);
		grid.SetValue(Grid.ColumnSpacingProperty, 0.0);
		grid11.Children.Add(grid);
		VisualDiagnostics.RegisterSourceInfo(grid, new Uri("Views/SharerRegisterView.xaml", UriKind.RelativeOrAbsolute), 72, 18);
		grid2.SetValue(Grid.RowProperty, 4);
		grid2.SetValue(Grid.ColumnProperty, 0);
		grid2.SetValue(Grid.ColumnSpanProperty, 2);
		staticResourceExtension3.Key = "LineColor";
		XamlServiceProvider xamlServiceProvider3 = new XamlServiceProvider();
		Type typeFromHandle5 = typeof(IProvideValueTarget);
		object[] array3 = new object[0 + 5];
		array3[0] = grid2;
		array3[1] = grid11;
		array3[2] = stackLayout;
		array3[3] = scrollView;
		array3[4] = sharerRegisterView;
		object service3;
		xamlServiceProvider3.Add(typeFromHandle5, service3 = new SimpleValueTargetProvider(array3, VisualElement.BackgroundColorProperty, nameScope));
		xamlServiceProvider3.Add(typeof(IReferenceProvider), service3);
		Type typeFromHandle6 = typeof(IXamlTypeResolver);
		XmlNamespaceResolver xmlNamespaceResolver3 = new XmlNamespaceResolver();
		xmlNamespaceResolver3.Add("", "http://xamarin.com/schemas/2014/forms");
		xmlNamespaceResolver3.Add("x", "http://schemas.microsoft.com/winfx/2009/xaml");
		xmlNamespaceResolver3.Add("calx", "clr-namespace:Caliburn.Micro.Xamarin.Forms;assembly=Caliburn.Micro.Platform.Xamarin.Forms");
		xmlNamespaceResolver3.Add("renderer", "clr-namespace:NHL.Views.Renderer");
		xmlNamespaceResolver3.Add("converter", "clr-namespace:NHL.Views.Converters");
		xmlNamespaceResolver3.Add("effect", "clr-namespace:NHL.Views.Effect");
		xmlNamespaceResolver3.Add("system", "clr-namespace:System;assembly=System.Runtime.Extensions");
		xamlServiceProvider3.Add(typeFromHandle6, new XamlTypeResolver(xmlNamespaceResolver3, typeof(SharerRegisterView).GetTypeInfo().Assembly));
		xamlServiceProvider3.Add(typeof(IXmlLineInfoProvider), new XmlLineInfoProvider(new XmlLineInfo(73, 72)));
		object obj3 = ((IMarkupExtension)staticResourceExtension3).ProvideValue((IServiceProvider)xamlServiceProvider3);
		grid2.BackgroundColor = (Color)obj3;
		VisualDiagnostics.RegisterSourceInfo(obj3, new Uri("Views/SharerRegisterView.xaml", UriKind.RelativeOrAbsolute), 73, 72);
		grid2.SetValue(Grid.RowSpacingProperty, 0.0);
		grid2.SetValue(Grid.ColumnSpacingProperty, 0.0);
		grid11.Children.Add(grid2);
		VisualDiagnostics.RegisterSourceInfo(grid2, new Uri("Views/SharerRegisterView.xaml", UriKind.RelativeOrAbsolute), 73, 18);
		grid3.SetValue(Grid.RowProperty, 6);
		grid3.SetValue(Grid.ColumnProperty, 0);
		grid3.SetValue(Grid.ColumnSpanProperty, 2);
		staticResourceExtension4.Key = "LineColor";
		XamlServiceProvider xamlServiceProvider4 = new XamlServiceProvider();
		Type typeFromHandle7 = typeof(IProvideValueTarget);
		object[] array4 = new object[0 + 5];
		array4[0] = grid3;
		array4[1] = grid11;
		array4[2] = stackLayout;
		array4[3] = scrollView;
		array4[4] = sharerRegisterView;
		object service4;
		xamlServiceProvider4.Add(typeFromHandle7, service4 = new SimpleValueTargetProvider(array4, VisualElement.BackgroundColorProperty, nameScope));
		xamlServiceProvider4.Add(typeof(IReferenceProvider), service4);
		Type typeFromHandle8 = typeof(IXamlTypeResolver);
		XmlNamespaceResolver xmlNamespaceResolver4 = new XmlNamespaceResolver();
		xmlNamespaceResolver4.Add("", "http://xamarin.com/schemas/2014/forms");
		xmlNamespaceResolver4.Add("x", "http://schemas.microsoft.com/winfx/2009/xaml");
		xmlNamespaceResolver4.Add("calx", "clr-namespace:Caliburn.Micro.Xamarin.Forms;assembly=Caliburn.Micro.Platform.Xamarin.Forms");
		xmlNamespaceResolver4.Add("renderer", "clr-namespace:NHL.Views.Renderer");
		xmlNamespaceResolver4.Add("converter", "clr-namespace:NHL.Views.Converters");
		xmlNamespaceResolver4.Add("effect", "clr-namespace:NHL.Views.Effect");
		xmlNamespaceResolver4.Add("system", "clr-namespace:System;assembly=System.Runtime.Extensions");
		xamlServiceProvider4.Add(typeFromHandle8, new XamlTypeResolver(xmlNamespaceResolver4, typeof(SharerRegisterView).GetTypeInfo().Assembly));
		xamlServiceProvider4.Add(typeof(IXmlLineInfoProvider), new XmlLineInfoProvider(new XmlLineInfo(74, 72)));
		object obj4 = ((IMarkupExtension)staticResourceExtension4).ProvideValue((IServiceProvider)xamlServiceProvider4);
		grid3.BackgroundColor = (Color)obj4;
		VisualDiagnostics.RegisterSourceInfo(obj4, new Uri("Views/SharerRegisterView.xaml", UriKind.RelativeOrAbsolute), 74, 72);
		grid3.SetValue(Grid.RowSpacingProperty, 0.0);
		grid3.SetValue(Grid.ColumnSpacingProperty, 0.0);
		grid11.Children.Add(grid3);
		VisualDiagnostics.RegisterSourceInfo(grid3, new Uri("Views/SharerRegisterView.xaml", UriKind.RelativeOrAbsolute), 74, 18);
		grid4.SetValue(Grid.RowProperty, 8);
		grid4.SetValue(Grid.ColumnProperty, 0);
		grid4.SetValue(Grid.ColumnSpanProperty, 2);
		staticResourceExtension5.Key = "LineColor";
		XamlServiceProvider xamlServiceProvider5 = new XamlServiceProvider();
		Type typeFromHandle9 = typeof(IProvideValueTarget);
		object[] array5 = new object[0 + 5];
		array5[0] = grid4;
		array5[1] = grid11;
		array5[2] = stackLayout;
		array5[3] = scrollView;
		array5[4] = sharerRegisterView;
		object service5;
		xamlServiceProvider5.Add(typeFromHandle9, service5 = new SimpleValueTargetProvider(array5, VisualElement.BackgroundColorProperty, nameScope));
		xamlServiceProvider5.Add(typeof(IReferenceProvider), service5);
		Type typeFromHandle10 = typeof(IXamlTypeResolver);
		XmlNamespaceResolver xmlNamespaceResolver5 = new XmlNamespaceResolver();
		xmlNamespaceResolver5.Add("", "http://xamarin.com/schemas/2014/forms");
		xmlNamespaceResolver5.Add("x", "http://schemas.microsoft.com/winfx/2009/xaml");
		xmlNamespaceResolver5.Add("calx", "clr-namespace:Caliburn.Micro.Xamarin.Forms;assembly=Caliburn.Micro.Platform.Xamarin.Forms");
		xmlNamespaceResolver5.Add("renderer", "clr-namespace:NHL.Views.Renderer");
		xmlNamespaceResolver5.Add("converter", "clr-namespace:NHL.Views.Converters");
		xmlNamespaceResolver5.Add("effect", "clr-namespace:NHL.Views.Effect");
		xmlNamespaceResolver5.Add("system", "clr-namespace:System;assembly=System.Runtime.Extensions");
		xamlServiceProvider5.Add(typeFromHandle10, new XamlTypeResolver(xmlNamespaceResolver5, typeof(SharerRegisterView).GetTypeInfo().Assembly));
		xamlServiceProvider5.Add(typeof(IXmlLineInfoProvider), new XmlLineInfoProvider(new XmlLineInfo(75, 72)));
		object obj5 = ((IMarkupExtension)staticResourceExtension5).ProvideValue((IServiceProvider)xamlServiceProvider5);
		grid4.BackgroundColor = (Color)obj5;
		VisualDiagnostics.RegisterSourceInfo(obj5, new Uri("Views/SharerRegisterView.xaml", UriKind.RelativeOrAbsolute), 75, 72);
		grid4.SetValue(Grid.RowSpacingProperty, 0.0);
		grid4.SetValue(Grid.ColumnSpacingProperty, 0.0);
		grid11.Children.Add(grid4);
		VisualDiagnostics.RegisterSourceInfo(grid4, new Uri("Views/SharerRegisterView.xaml", UriKind.RelativeOrAbsolute), 75, 18);
		grid5.SetValue(Grid.RowProperty, 1);
		grid5.SetValue(Grid.ColumnProperty, 0);
		grid5.SetValue(Grid.ColumnSpanProperty, 2);
		grid5.SetValue(VisualElement.BackgroundColorProperty, Color.White);
		grid5.SetValue(Grid.RowSpacingProperty, 0.0);
		grid5.SetValue(Grid.ColumnSpacingProperty, 0.0);
		grid11.Children.Add(grid5);
		VisualDiagnostics.RegisterSourceInfo(grid5, new Uri("Views/SharerRegisterView.xaml", UriKind.RelativeOrAbsolute), 78, 18);
		grid6.SetValue(Grid.RowProperty, 3);
		grid6.SetValue(Grid.ColumnProperty, 0);
		grid6.SetValue(Grid.ColumnSpanProperty, 2);
		grid6.SetValue(VisualElement.BackgroundColorProperty, Color.White);
		grid6.SetValue(Grid.RowSpacingProperty, 0.0);
		grid6.SetValue(Grid.ColumnSpacingProperty, 0.0);
		grid11.Children.Add(grid6);
		VisualDiagnostics.RegisterSourceInfo(grid6, new Uri("Views/SharerRegisterView.xaml", UriKind.RelativeOrAbsolute), 79, 18);
		grid7.SetValue(Grid.RowProperty, 5);
		grid7.SetValue(Grid.ColumnProperty, 0);
		grid7.SetValue(Grid.ColumnSpanProperty, 2);
		grid7.SetValue(VisualElement.BackgroundColorProperty, Color.White);
		grid7.SetValue(Grid.RowSpacingProperty, 0.0);
		grid7.SetValue(Grid.ColumnSpacingProperty, 0.0);
		grid11.Children.Add(grid7);
		VisualDiagnostics.RegisterSourceInfo(grid7, new Uri("Views/SharerRegisterView.xaml", UriKind.RelativeOrAbsolute), 80, 18);
		grid8.SetValue(Grid.RowProperty, 7);
		grid8.SetValue(Grid.ColumnProperty, 0);
		grid8.SetValue(Grid.ColumnSpanProperty, 2);
		grid8.SetValue(VisualElement.BackgroundColorProperty, Color.White);
		grid8.SetValue(Grid.RowSpacingProperty, 0.0);
		grid8.SetValue(Grid.ColumnSpacingProperty, 0.0);
		grid11.Children.Add(grid8);
		VisualDiagnostics.RegisterSourceInfo(grid8, new Uri("Views/SharerRegisterView.xaml", UriKind.RelativeOrAbsolute), 81, 18);
		grid9.SetValue(Grid.RowProperty, 9);
		grid9.SetValue(Grid.ColumnProperty, 0);
		grid9.SetValue(Grid.ColumnSpanProperty, 2);
		grid9.SetValue(VisualElement.BackgroundColorProperty, Color.White);
		grid9.SetValue(Grid.RowSpacingProperty, 0.0);
		grid9.SetValue(Grid.ColumnSpacingProperty, 0.0);
		grid11.Children.Add(grid9);
		VisualDiagnostics.RegisterSourceInfo(grid9, new Uri("Views/SharerRegisterView.xaml", UriKind.RelativeOrAbsolute), 82, 18);
		grid10.SetValue(Grid.RowProperty, 10);
		grid10.SetValue(Grid.ColumnProperty, 0);
		grid10.SetValue(Grid.ColumnSpanProperty, 2);
		grid10.SetValue(VisualElement.BackgroundColorProperty, Color.White);
		grid10.SetValue(Grid.RowSpacingProperty, 0.0);
		grid10.SetValue(Grid.ColumnSpacingProperty, 0.0);
		grid11.Children.Add(grid10);
		VisualDiagnostics.RegisterSourceInfo(grid10, new Uri("Views/SharerRegisterView.xaml", UriKind.RelativeOrAbsolute), 83, 18);
		label.SetValue(Grid.RowProperty, 1);
		label.SetValue(Grid.ColumnProperty, 0);
		label.SetValue(Xamarin.Forms.View.MarginProperty, new Thickness(10.0, 5.0, 0.0, 5.0));
		label.SetValue(Label.TextProperty, "ユーザーID");
		BindableProperty fontSizeProperty = Label.FontSizeProperty;
		FontSizeConverter fontSizeConverter = new FontSizeConverter();
		XamlServiceProvider xamlServiceProvider6 = new XamlServiceProvider();
		Type typeFromHandle11 = typeof(IProvideValueTarget);
		object[] array6 = new object[0 + 5];
		array6[0] = label;
		array6[1] = grid11;
		array6[2] = stackLayout;
		array6[3] = scrollView;
		array6[4] = sharerRegisterView;
		object service6;
		xamlServiceProvider6.Add(typeFromHandle11, service6 = new SimpleValueTargetProvider(array6, Label.FontSizeProperty, nameScope));
		xamlServiceProvider6.Add(typeof(IReferenceProvider), service6);
		Type typeFromHandle12 = typeof(IXamlTypeResolver);
		XmlNamespaceResolver xmlNamespaceResolver6 = new XmlNamespaceResolver();
		xmlNamespaceResolver6.Add("", "http://xamarin.com/schemas/2014/forms");
		xmlNamespaceResolver6.Add("x", "http://schemas.microsoft.com/winfx/2009/xaml");
		xmlNamespaceResolver6.Add("calx", "clr-namespace:Caliburn.Micro.Xamarin.Forms;assembly=Caliburn.Micro.Platform.Xamarin.Forms");
		xmlNamespaceResolver6.Add("renderer", "clr-namespace:NHL.Views.Renderer");
		xmlNamespaceResolver6.Add("converter", "clr-namespace:NHL.Views.Converters");
		xmlNamespaceResolver6.Add("effect", "clr-namespace:NHL.Views.Effect");
		xmlNamespaceResolver6.Add("system", "clr-namespace:System;assembly=System.Runtime.Extensions");
		xamlServiceProvider6.Add(typeFromHandle12, new XamlTypeResolver(xmlNamespaceResolver6, typeof(SharerRegisterView).GetTypeInfo().Assembly));
		xamlServiceProvider6.Add(typeof(IXmlLineInfoProvider), new XmlLineInfoProvider(new XmlLineInfo(86, 85)));
		label.SetValue(fontSizeProperty, ((IExtendedTypeConverter)fontSizeConverter).ConvertFromInvariantString("Medium", (IServiceProvider)xamlServiceProvider6));
		label.SetValue(Xamarin.Forms.View.HorizontalOptionsProperty, LayoutOptions.Start);
		label.Effects.Add(fixedFontSizeLabelEffect);
		VisualDiagnostics.RegisterSourceInfo(fixedFontSizeLabelEffect, new Uri("Views/SharerRegisterView.xaml", UriKind.RelativeOrAbsolute), 88, 26);
		grid11.Children.Add(label);
		VisualDiagnostics.RegisterSourceInfo(label, new Uri("Views/SharerRegisterView.xaml", UriKind.RelativeOrAbsolute), 86, 18);
		entry.SetValue(Grid.RowProperty, 1);
		entry.SetValue(Grid.ColumnProperty, 1);
		entry.SetValue(Xamarin.Forms.View.MarginProperty, new Thickness(0.0, 5.0, 10.0, 5.0));
		BindableProperty fontSizeProperty2 = Entry.FontSizeProperty;
		FontSizeConverter fontSizeConverter2 = new FontSizeConverter();
		XamlServiceProvider xamlServiceProvider7 = new XamlServiceProvider();
		Type typeFromHandle13 = typeof(IProvideValueTarget);
		object[] array7 = new object[0 + 5];
		array7[0] = entry;
		array7[1] = grid11;
		array7[2] = stackLayout;
		array7[3] = scrollView;
		array7[4] = sharerRegisterView;
		object service7;
		xamlServiceProvider7.Add(typeFromHandle13, service7 = new SimpleValueTargetProvider(array7, Entry.FontSizeProperty, nameScope));
		xamlServiceProvider7.Add(typeof(IReferenceProvider), service7);
		Type typeFromHandle14 = typeof(IXamlTypeResolver);
		XmlNamespaceResolver xmlNamespaceResolver7 = new XmlNamespaceResolver();
		xmlNamespaceResolver7.Add("", "http://xamarin.com/schemas/2014/forms");
		xmlNamespaceResolver7.Add("x", "http://schemas.microsoft.com/winfx/2009/xaml");
		xmlNamespaceResolver7.Add("calx", "clr-namespace:Caliburn.Micro.Xamarin.Forms;assembly=Caliburn.Micro.Platform.Xamarin.Forms");
		xmlNamespaceResolver7.Add("renderer", "clr-namespace:NHL.Views.Renderer");
		xmlNamespaceResolver7.Add("converter", "clr-namespace:NHL.Views.Converters");
		xmlNamespaceResolver7.Add("effect", "clr-namespace:NHL.Views.Effect");
		xmlNamespaceResolver7.Add("system", "clr-namespace:System;assembly=System.Runtime.Extensions");
		xamlServiceProvider7.Add(typeFromHandle14, new XamlTypeResolver(xmlNamespaceResolver7, typeof(SharerRegisterView).GetTypeInfo().Assembly));
		xamlServiceProvider7.Add(typeof(IXmlLineInfoProvider), new XmlLineInfoProvider(new XmlLineInfo(94, 21)));
		entry.SetValue(fontSizeProperty2, ((IExtendedTypeConverter)fontSizeConverter2).ConvertFromInvariantString("Large", (IServiceProvider)xamlServiceProvider7));
		entry.SetValue(Entry.PlaceholderProperty, "必須");
		entry.SetValue(InputView.KeyboardProperty, new KeyboardTypeConverter().ConvertFromInvariantString("Email"));
		bindingExtension.Mode = BindingMode.TwoWay;
		bindingExtension.Path = "SharerLoginId";
		BindingBase binding = ((IMarkupExtension<BindingBase>)bindingExtension).ProvideValue((IServiceProvider)null);
		entry.SetBinding(Entry.TextProperty, binding);
		bindingExtension2.Path = "IsNetworkEnabled";
		BindingBase binding2 = ((IMarkupExtension<BindingBase>)bindingExtension2).ProvideValue((IServiceProvider)null);
		entry.SetBinding(VisualElement.IsEnabledProperty, binding2);
		entry.Effects.Add(fixedFontSizeTextBoxEffect);
		VisualDiagnostics.RegisterSourceInfo(fixedFontSizeTextBoxEffect, new Uri("Views/SharerRegisterView.xaml", UriKind.RelativeOrAbsolute), 100, 26);
		grid11.Children.Add(entry);
		VisualDiagnostics.RegisterSourceInfo(entry, new Uri("Views/SharerRegisterView.xaml", UriKind.RelativeOrAbsolute), 91, 18);
		label2.SetValue(Grid.RowProperty, 3);
		label2.SetValue(Grid.ColumnProperty, 0);
		label2.SetValue(Xamarin.Forms.View.MarginProperty, new Thickness(10.0, 5.0, 0.0, 5.0));
		label2.SetValue(Label.TextProperty, "パスワード");
		BindableProperty fontSizeProperty3 = Label.FontSizeProperty;
		FontSizeConverter fontSizeConverter3 = new FontSizeConverter();
		XamlServiceProvider xamlServiceProvider8 = new XamlServiceProvider();
		Type typeFromHandle15 = typeof(IProvideValueTarget);
		object[] array8 = new object[0 + 5];
		array8[0] = label2;
		array8[1] = grid11;
		array8[2] = stackLayout;
		array8[3] = scrollView;
		array8[4] = sharerRegisterView;
		object service8;
		xamlServiceProvider8.Add(typeFromHandle15, service8 = new SimpleValueTargetProvider(array8, Label.FontSizeProperty, nameScope));
		xamlServiceProvider8.Add(typeof(IReferenceProvider), service8);
		Type typeFromHandle16 = typeof(IXamlTypeResolver);
		XmlNamespaceResolver xmlNamespaceResolver8 = new XmlNamespaceResolver();
		xmlNamespaceResolver8.Add("", "http://xamarin.com/schemas/2014/forms");
		xmlNamespaceResolver8.Add("x", "http://schemas.microsoft.com/winfx/2009/xaml");
		xmlNamespaceResolver8.Add("calx", "clr-namespace:Caliburn.Micro.Xamarin.Forms;assembly=Caliburn.Micro.Platform.Xamarin.Forms");
		xmlNamespaceResolver8.Add("renderer", "clr-namespace:NHL.Views.Renderer");
		xmlNamespaceResolver8.Add("converter", "clr-namespace:NHL.Views.Converters");
		xmlNamespaceResolver8.Add("effect", "clr-namespace:NHL.Views.Effect");
		xmlNamespaceResolver8.Add("system", "clr-namespace:System;assembly=System.Runtime.Extensions");
		xamlServiceProvider8.Add(typeFromHandle16, new XamlTypeResolver(xmlNamespaceResolver8, typeof(SharerRegisterView).GetTypeInfo().Assembly));
		xamlServiceProvider8.Add(typeof(IXmlLineInfoProvider), new XmlLineInfoProvider(new XmlLineInfo(105, 84)));
		label2.SetValue(fontSizeProperty3, ((IExtendedTypeConverter)fontSizeConverter3).ConvertFromInvariantString("Medium", (IServiceProvider)xamlServiceProvider8));
		label2.SetValue(Xamarin.Forms.View.HorizontalOptionsProperty, LayoutOptions.Start);
		label2.Effects.Add(fixedFontSizeLabelEffect2);
		VisualDiagnostics.RegisterSourceInfo(fixedFontSizeLabelEffect2, new Uri("Views/SharerRegisterView.xaml", UriKind.RelativeOrAbsolute), 107, 26);
		grid11.Children.Add(label2);
		VisualDiagnostics.RegisterSourceInfo(label2, new Uri("Views/SharerRegisterView.xaml", UriKind.RelativeOrAbsolute), 105, 18);
		entry2.SetValue(Grid.RowProperty, 3);
		entry2.SetValue(Grid.ColumnProperty, 1);
		entry2.SetValue(Xamarin.Forms.View.MarginProperty, new Thickness(0.0, 5.0, 10.0, 5.0));
		BindableProperty fontSizeProperty4 = Entry.FontSizeProperty;
		FontSizeConverter fontSizeConverter4 = new FontSizeConverter();
		XamlServiceProvider xamlServiceProvider9 = new XamlServiceProvider();
		Type typeFromHandle17 = typeof(IProvideValueTarget);
		object[] array9 = new object[0 + 5];
		array9[0] = entry2;
		array9[1] = grid11;
		array9[2] = stackLayout;
		array9[3] = scrollView;
		array9[4] = sharerRegisterView;
		object service9;
		xamlServiceProvider9.Add(typeFromHandle17, service9 = new SimpleValueTargetProvider(array9, Entry.FontSizeProperty, nameScope));
		xamlServiceProvider9.Add(typeof(IReferenceProvider), service9);
		Type typeFromHandle18 = typeof(IXamlTypeResolver);
		XmlNamespaceResolver xmlNamespaceResolver9 = new XmlNamespaceResolver();
		xmlNamespaceResolver9.Add("", "http://xamarin.com/schemas/2014/forms");
		xmlNamespaceResolver9.Add("x", "http://schemas.microsoft.com/winfx/2009/xaml");
		xmlNamespaceResolver9.Add("calx", "clr-namespace:Caliburn.Micro.Xamarin.Forms;assembly=Caliburn.Micro.Platform.Xamarin.Forms");
		xmlNamespaceResolver9.Add("renderer", "clr-namespace:NHL.Views.Renderer");
		xmlNamespaceResolver9.Add("converter", "clr-namespace:NHL.Views.Converters");
		xmlNamespaceResolver9.Add("effect", "clr-namespace:NHL.Views.Effect");
		xmlNamespaceResolver9.Add("system", "clr-namespace:System;assembly=System.Runtime.Extensions");
		xamlServiceProvider9.Add(typeFromHandle18, new XamlTypeResolver(xmlNamespaceResolver9, typeof(SharerRegisterView).GetTypeInfo().Assembly));
		xamlServiceProvider9.Add(typeof(IXmlLineInfoProvider), new XmlLineInfoProvider(new XmlLineInfo(113, 21)));
		entry2.SetValue(fontSizeProperty4, ((IExtendedTypeConverter)fontSizeConverter4).ConvertFromInvariantString("Large", (IServiceProvider)xamlServiceProvider9));
		entry2.SetValue(Entry.PlaceholderProperty, "必須");
		entry2.SetValue(Entry.IsPasswordProperty, true);
		bindingExtension3.Mode = BindingMode.TwoWay;
		bindingExtension3.Path = "SharerPassword";
		BindingBase binding3 = ((IMarkupExtension<BindingBase>)bindingExtension3).ProvideValue((IServiceProvider)null);
		entry2.SetBinding(Entry.TextProperty, binding3);
		bindingExtension4.Path = "IsNetworkEnabled";
		BindingBase binding4 = ((IMarkupExtension<BindingBase>)bindingExtension4).ProvideValue((IServiceProvider)null);
		entry2.SetBinding(VisualElement.IsEnabledProperty, binding4);
		entry2.Effects.Add(fixedFontSizeTextBoxEffect2);
		VisualDiagnostics.RegisterSourceInfo(fixedFontSizeTextBoxEffect2, new Uri("Views/SharerRegisterView.xaml", UriKind.RelativeOrAbsolute), 119, 26);
		grid11.Children.Add(entry2);
		VisualDiagnostics.RegisterSourceInfo(entry2, new Uri("Views/SharerRegisterView.xaml", UriKind.RelativeOrAbsolute), 110, 18);
		label3.SetValue(Grid.RowProperty, 5);
		label3.SetValue(Grid.ColumnProperty, 0);
		label3.SetValue(Xamarin.Forms.View.MarginProperty, new Thickness(10.0, 5.0, 0.0, 5.0));
		label3.SetValue(Label.TextProperty, "パスワード確認");
		BindableProperty fontSizeProperty5 = Label.FontSizeProperty;
		FontSizeConverter fontSizeConverter5 = new FontSizeConverter();
		XamlServiceProvider xamlServiceProvider10 = new XamlServiceProvider();
		Type typeFromHandle19 = typeof(IProvideValueTarget);
		object[] array10 = new object[0 + 5];
		array10[0] = label3;
		array10[1] = grid11;
		array10[2] = stackLayout;
		array10[3] = scrollView;
		array10[4] = sharerRegisterView;
		object service10;
		xamlServiceProvider10.Add(typeFromHandle19, service10 = new SimpleValueTargetProvider(array10, Label.FontSizeProperty, nameScope));
		xamlServiceProvider10.Add(typeof(IReferenceProvider), service10);
		Type typeFromHandle20 = typeof(IXamlTypeResolver);
		XmlNamespaceResolver xmlNamespaceResolver10 = new XmlNamespaceResolver();
		xmlNamespaceResolver10.Add("", "http://xamarin.com/schemas/2014/forms");
		xmlNamespaceResolver10.Add("x", "http://schemas.microsoft.com/winfx/2009/xaml");
		xmlNamespaceResolver10.Add("calx", "clr-namespace:Caliburn.Micro.Xamarin.Forms;assembly=Caliburn.Micro.Platform.Xamarin.Forms");
		xmlNamespaceResolver10.Add("renderer", "clr-namespace:NHL.Views.Renderer");
		xmlNamespaceResolver10.Add("converter", "clr-namespace:NHL.Views.Converters");
		xmlNamespaceResolver10.Add("effect", "clr-namespace:NHL.Views.Effect");
		xmlNamespaceResolver10.Add("system", "clr-namespace:System;assembly=System.Runtime.Extensions");
		xamlServiceProvider10.Add(typeFromHandle20, new XamlTypeResolver(xmlNamespaceResolver10, typeof(SharerRegisterView).GetTypeInfo().Assembly));
		xamlServiceProvider10.Add(typeof(IXmlLineInfoProvider), new XmlLineInfoProvider(new XmlLineInfo(124, 86)));
		label3.SetValue(fontSizeProperty5, ((IExtendedTypeConverter)fontSizeConverter5).ConvertFromInvariantString("Medium", (IServiceProvider)xamlServiceProvider10));
		label3.SetValue(Xamarin.Forms.View.HorizontalOptionsProperty, LayoutOptions.Start);
		label3.Effects.Add(fixedFontSizeLabelEffect3);
		VisualDiagnostics.RegisterSourceInfo(fixedFontSizeLabelEffect3, new Uri("Views/SharerRegisterView.xaml", UriKind.RelativeOrAbsolute), 126, 26);
		grid11.Children.Add(label3);
		VisualDiagnostics.RegisterSourceInfo(label3, new Uri("Views/SharerRegisterView.xaml", UriKind.RelativeOrAbsolute), 124, 18);
		entry3.SetValue(Grid.RowProperty, 5);
		entry3.SetValue(Grid.ColumnProperty, 1);
		entry3.SetValue(Xamarin.Forms.View.MarginProperty, new Thickness(0.0, 5.0, 10.0, 5.0));
		BindableProperty fontSizeProperty6 = Entry.FontSizeProperty;
		FontSizeConverter fontSizeConverter6 = new FontSizeConverter();
		XamlServiceProvider xamlServiceProvider11 = new XamlServiceProvider();
		Type typeFromHandle21 = typeof(IProvideValueTarget);
		object[] array11 = new object[0 + 5];
		array11[0] = entry3;
		array11[1] = grid11;
		array11[2] = stackLayout;
		array11[3] = scrollView;
		array11[4] = sharerRegisterView;
		object service11;
		xamlServiceProvider11.Add(typeFromHandle21, service11 = new SimpleValueTargetProvider(array11, Entry.FontSizeProperty, nameScope));
		xamlServiceProvider11.Add(typeof(IReferenceProvider), service11);
		Type typeFromHandle22 = typeof(IXamlTypeResolver);
		XmlNamespaceResolver xmlNamespaceResolver11 = new XmlNamespaceResolver();
		xmlNamespaceResolver11.Add("", "http://xamarin.com/schemas/2014/forms");
		xmlNamespaceResolver11.Add("x", "http://schemas.microsoft.com/winfx/2009/xaml");
		xmlNamespaceResolver11.Add("calx", "clr-namespace:Caliburn.Micro.Xamarin.Forms;assembly=Caliburn.Micro.Platform.Xamarin.Forms");
		xmlNamespaceResolver11.Add("renderer", "clr-namespace:NHL.Views.Renderer");
		xmlNamespaceResolver11.Add("converter", "clr-namespace:NHL.Views.Converters");
		xmlNamespaceResolver11.Add("effect", "clr-namespace:NHL.Views.Effect");
		xmlNamespaceResolver11.Add("system", "clr-namespace:System;assembly=System.Runtime.Extensions");
		xamlServiceProvider11.Add(typeFromHandle22, new XamlTypeResolver(xmlNamespaceResolver11, typeof(SharerRegisterView).GetTypeInfo().Assembly));
		xamlServiceProvider11.Add(typeof(IXmlLineInfoProvider), new XmlLineInfoProvider(new XmlLineInfo(132, 21)));
		entry3.SetValue(fontSizeProperty6, ((IExtendedTypeConverter)fontSizeConverter6).ConvertFromInvariantString("Large", (IServiceProvider)xamlServiceProvider11));
		entry3.SetValue(Entry.PlaceholderProperty, "必須");
		entry3.SetValue(Entry.IsPasswordProperty, true);
		bindingExtension5.Mode = BindingMode.TwoWay;
		bindingExtension5.Path = "CheckSharerPassword";
		BindingBase binding5 = ((IMarkupExtension<BindingBase>)bindingExtension5).ProvideValue((IServiceProvider)null);
		entry3.SetBinding(Entry.TextProperty, binding5);
		bindingExtension6.Path = "IsNetworkEnabled";
		BindingBase binding6 = ((IMarkupExtension<BindingBase>)bindingExtension6).ProvideValue((IServiceProvider)null);
		entry3.SetBinding(VisualElement.IsEnabledProperty, binding6);
		entry3.Effects.Add(fixedFontSizeTextBoxEffect3);
		VisualDiagnostics.RegisterSourceInfo(fixedFontSizeTextBoxEffect3, new Uri("Views/SharerRegisterView.xaml", UriKind.RelativeOrAbsolute), 138, 26);
		grid11.Children.Add(entry3);
		VisualDiagnostics.RegisterSourceInfo(entry3, new Uri("Views/SharerRegisterView.xaml", UriKind.RelativeOrAbsolute), 129, 18);
		label4.SetValue(Grid.RowProperty, 7);
		label4.SetValue(Grid.ColumnProperty, 0);
		label4.SetValue(Xamarin.Forms.View.MarginProperty, new Thickness(10.0, 5.0, 0.0, 5.0));
		label4.SetValue(Label.TextProperty, "メールアドレス");
		label4.SetValue(Xamarin.Forms.View.HorizontalOptionsProperty, LayoutOptions.Start);
		label4.Effects.Add(fixedFontSizeLabelEffect4);
		VisualDiagnostics.RegisterSourceInfo(fixedFontSizeLabelEffect4, new Uri("Views/SharerRegisterView.xaml", UriKind.RelativeOrAbsolute), 145, 26);
		span.SetValue(Span.TextProperty, "メールアドレス");
		formattedString.Spans.Add(span);
		VisualDiagnostics.RegisterSourceInfo(span, new Uri("Views/SharerRegisterView.xaml", UriKind.RelativeOrAbsolute), 149, 30);
		span2.SetValue(Span.TextProperty, "*任意");
		BindableProperty fontSizeProperty7 = Span.FontSizeProperty;
		FontSizeConverter fontSizeConverter7 = new FontSizeConverter();
		XamlServiceProvider xamlServiceProvider12 = new XamlServiceProvider();
		Type typeFromHandle23 = typeof(IProvideValueTarget);
		object[] array12 = new object[0 + 7];
		array12[0] = span2;
		array12[1] = formattedString;
		array12[2] = label4;
		array12[3] = grid11;
		array12[4] = stackLayout;
		array12[5] = scrollView;
		array12[6] = sharerRegisterView;
		object service12;
		xamlServiceProvider12.Add(typeFromHandle23, service12 = new SimpleValueTargetProvider(array12, Span.FontSizeProperty, nameScope));
		xamlServiceProvider12.Add(typeof(IReferenceProvider), service12);
		Type typeFromHandle24 = typeof(IXamlTypeResolver);
		XmlNamespaceResolver xmlNamespaceResolver12 = new XmlNamespaceResolver();
		xmlNamespaceResolver12.Add("", "http://xamarin.com/schemas/2014/forms");
		xmlNamespaceResolver12.Add("x", "http://schemas.microsoft.com/winfx/2009/xaml");
		xmlNamespaceResolver12.Add("calx", "clr-namespace:Caliburn.Micro.Xamarin.Forms;assembly=Caliburn.Micro.Platform.Xamarin.Forms");
		xmlNamespaceResolver12.Add("renderer", "clr-namespace:NHL.Views.Renderer");
		xmlNamespaceResolver12.Add("converter", "clr-namespace:NHL.Views.Converters");
		xmlNamespaceResolver12.Add("effect", "clr-namespace:NHL.Views.Effect");
		xmlNamespaceResolver12.Add("system", "clr-namespace:System;assembly=System.Runtime.Extensions");
		xamlServiceProvider12.Add(typeFromHandle24, new XamlTypeResolver(xmlNamespaceResolver12, typeof(SharerRegisterView).GetTypeInfo().Assembly));
		xamlServiceProvider12.Add(typeof(IXmlLineInfoProvider), new XmlLineInfoProvider(new XmlLineInfo(150, 46)));
		span2.SetValue(fontSizeProperty7, ((IExtendedTypeConverter)fontSizeConverter7).ConvertFromInvariantString("Small", (IServiceProvider)xamlServiceProvider12));
		span2.SetValue(Span.TextColorProperty, Color.Red);
		formattedString.Spans.Add(span2);
		VisualDiagnostics.RegisterSourceInfo(span2, new Uri("Views/SharerRegisterView.xaml", UriKind.RelativeOrAbsolute), 150, 30);
		label4.SetValue(Label.FormattedTextProperty, formattedString);
		VisualDiagnostics.RegisterSourceInfo(formattedString, new Uri("Views/SharerRegisterView.xaml", UriKind.RelativeOrAbsolute), 148, 26);
		grid11.Children.Add(label4);
		VisualDiagnostics.RegisterSourceInfo(label4, new Uri("Views/SharerRegisterView.xaml", UriKind.RelativeOrAbsolute), 143, 18);
		entry4.SetValue(Grid.RowProperty, 7);
		entry4.SetValue(Grid.ColumnProperty, 1);
		entry4.SetValue(Xamarin.Forms.View.MarginProperty, new Thickness(0.0, 5.0, 10.0, 5.0));
		BindableProperty fontSizeProperty8 = Entry.FontSizeProperty;
		FontSizeConverter fontSizeConverter8 = new FontSizeConverter();
		XamlServiceProvider xamlServiceProvider13 = new XamlServiceProvider();
		Type typeFromHandle25 = typeof(IProvideValueTarget);
		object[] array13 = new object[0 + 5];
		array13[0] = entry4;
		array13[1] = grid11;
		array13[2] = stackLayout;
		array13[3] = scrollView;
		array13[4] = sharerRegisterView;
		object service13;
		xamlServiceProvider13.Add(typeFromHandle25, service13 = new SimpleValueTargetProvider(array13, Entry.FontSizeProperty, nameScope));
		xamlServiceProvider13.Add(typeof(IReferenceProvider), service13);
		Type typeFromHandle26 = typeof(IXamlTypeResolver);
		XmlNamespaceResolver xmlNamespaceResolver13 = new XmlNamespaceResolver();
		xmlNamespaceResolver13.Add("", "http://xamarin.com/schemas/2014/forms");
		xmlNamespaceResolver13.Add("x", "http://schemas.microsoft.com/winfx/2009/xaml");
		xmlNamespaceResolver13.Add("calx", "clr-namespace:Caliburn.Micro.Xamarin.Forms;assembly=Caliburn.Micro.Platform.Xamarin.Forms");
		xmlNamespaceResolver13.Add("renderer", "clr-namespace:NHL.Views.Renderer");
		xmlNamespaceResolver13.Add("converter", "clr-namespace:NHL.Views.Converters");
		xmlNamespaceResolver13.Add("effect", "clr-namespace:NHL.Views.Effect");
		xmlNamespaceResolver13.Add("system", "clr-namespace:System;assembly=System.Runtime.Extensions");
		xamlServiceProvider13.Add(typeFromHandle26, new XamlTypeResolver(xmlNamespaceResolver13, typeof(SharerRegisterView).GetTypeInfo().Assembly));
		xamlServiceProvider13.Add(typeof(IXmlLineInfoProvider), new XmlLineInfoProvider(new XmlLineInfo(158, 21)));
		entry4.SetValue(fontSizeProperty8, ((IExtendedTypeConverter)fontSizeConverter8).ConvertFromInvariantString("Large", (IServiceProvider)xamlServiceProvider13));
		entry4.SetValue(InputView.KeyboardProperty, new KeyboardTypeConverter().ConvertFromInvariantString("Email"));
		bindingExtension7.Mode = BindingMode.TwoWay;
		bindingExtension7.Path = "Email";
		BindingBase binding7 = ((IMarkupExtension<BindingBase>)bindingExtension7).ProvideValue((IServiceProvider)null);
		entry4.SetBinding(Entry.TextProperty, binding7);
		bindingExtension8.Path = "IsNetworkEnabled";
		BindingBase binding8 = ((IMarkupExtension<BindingBase>)bindingExtension8).ProvideValue((IServiceProvider)null);
		entry4.SetBinding(VisualElement.IsEnabledProperty, binding8);
		entry4.Effects.Add(fixedFontSizeTextBoxEffect4);
		VisualDiagnostics.RegisterSourceInfo(fixedFontSizeTextBoxEffect4, new Uri("Views/SharerRegisterView.xaml", UriKind.RelativeOrAbsolute), 163, 26);
		grid11.Children.Add(entry4);
		VisualDiagnostics.RegisterSourceInfo(entry4, new Uri("Views/SharerRegisterView.xaml", UriKind.RelativeOrAbsolute), 155, 18);
		label5.SetValue(Grid.RowProperty, 9);
		label5.SetValue(Grid.ColumnProperty, 0);
		label5.SetValue(Grid.ColumnSpanProperty, 2);
		label5.SetValue(Xamarin.Forms.View.MarginProperty, new Thickness(10.0, 5.0, 10.0, 5.0));
		BindableProperty fontSizeProperty9 = Label.FontSizeProperty;
		FontSizeConverter fontSizeConverter9 = new FontSizeConverter();
		XamlServiceProvider xamlServiceProvider14 = new XamlServiceProvider();
		Type typeFromHandle27 = typeof(IProvideValueTarget);
		object[] array14 = new object[0 + 5];
		array14[0] = label5;
		array14[1] = grid11;
		array14[2] = stackLayout;
		array14[3] = scrollView;
		array14[4] = sharerRegisterView;
		object service14;
		xamlServiceProvider14.Add(typeFromHandle27, service14 = new SimpleValueTargetProvider(array14, Label.FontSizeProperty, nameScope));
		xamlServiceProvider14.Add(typeof(IReferenceProvider), service14);
		Type typeFromHandle28 = typeof(IXamlTypeResolver);
		XmlNamespaceResolver xmlNamespaceResolver14 = new XmlNamespaceResolver();
		xmlNamespaceResolver14.Add("", "http://xamarin.com/schemas/2014/forms");
		xmlNamespaceResolver14.Add("x", "http://schemas.microsoft.com/winfx/2009/xaml");
		xmlNamespaceResolver14.Add("calx", "clr-namespace:Caliburn.Micro.Xamarin.Forms;assembly=Caliburn.Micro.Platform.Xamarin.Forms");
		xmlNamespaceResolver14.Add("renderer", "clr-namespace:NHL.Views.Renderer");
		xmlNamespaceResolver14.Add("converter", "clr-namespace:NHL.Views.Converters");
		xmlNamespaceResolver14.Add("effect", "clr-namespace:NHL.Views.Effect");
		xmlNamespaceResolver14.Add("system", "clr-namespace:System;assembly=System.Runtime.Extensions");
		xamlServiceProvider14.Add(typeFromHandle28, new XamlTypeResolver(xmlNamespaceResolver14, typeof(SharerRegisterView).GetTypeInfo().Assembly));
		xamlServiceProvider14.Add(typeof(IXmlLineInfoProvider), new XmlLineInfoProvider(new XmlLineInfo(167, 92)));
		label5.SetValue(fontSizeProperty9, ((IExtendedTypeConverter)fontSizeConverter9).ConvertFromInvariantString("Small", (IServiceProvider)xamlServiceProvider14));
		label5.SetValue(Xamarin.Forms.View.HorizontalOptionsProperty, LayoutOptions.Start);
		label5.Effects.Add(fixedFontSizeLabelEffect5);
		VisualDiagnostics.RegisterSourceInfo(fixedFontSizeLabelEffect5, new Uri("Views/SharerRegisterView.xaml", UriKind.RelativeOrAbsolute), 169, 26);
		span3.SetValue(Span.TextProperty, "※パスワードは忘れずに保管ください。");
		formattedString2.Spans.Add(span3);
		VisualDiagnostics.RegisterSourceInfo(span3, new Uri("Views/SharerRegisterView.xaml", UriKind.RelativeOrAbsolute), 173, 30);
		span4.SetValue(Span.TextProperty, newLine);
		VisualDiagnostics.RegisterSourceInfo(newLine, new Uri("Views/SharerRegisterView.xaml", UriKind.RelativeOrAbsolute), 174, 35);
		formattedString2.Spans.Add(span4);
		VisualDiagnostics.RegisterSourceInfo(span4, new Uri("Views/SharerRegisterView.xaml", UriKind.RelativeOrAbsolute), 174, 30);
		span5.SetValue(Span.TextProperty, "※上記メールアドレス宛の登録完了メールからもログインいただけます。");
		formattedString2.Spans.Add(span5);
		VisualDiagnostics.RegisterSourceInfo(span5, new Uri("Views/SharerRegisterView.xaml", UriKind.RelativeOrAbsolute), 175, 30);
		label5.SetValue(Label.FormattedTextProperty, formattedString2);
		VisualDiagnostics.RegisterSourceInfo(formattedString2, new Uri("Views/SharerRegisterView.xaml", UriKind.RelativeOrAbsolute), 172, 26);
		grid11.Children.Add(label5);
		VisualDiagnostics.RegisterSourceInfo(label5, new Uri("Views/SharerRegisterView.xaml", UriKind.RelativeOrAbsolute), 167, 18);
		button.SetValue(Grid.RowProperty, 10);
		button.SetValue(Grid.ColumnProperty, 0);
		button.SetValue(Grid.ColumnSpanProperty, 2);
		button.SetValue(Xamarin.Forms.View.MarginProperty, new Thickness(10.0, 10.0, 10.0, 5.0));
		button.SetValue(Button.TextProperty, "登録");
		button.SetValue(Message.AttachProperty, "Register");
		button.SetValue(Xamarin.Forms.View.HorizontalOptionsProperty, LayoutOptions.FillAndExpand);
		button.SetValue(Button.TextColorProperty, Color.White);
		staticResourceExtension6.Key = "ButtonColor";
		XamlServiceProvider xamlServiceProvider15 = new XamlServiceProvider();
		Type typeFromHandle29 = typeof(IProvideValueTarget);
		object[] array15 = new object[0 + 5];
		array15[0] = button;
		array15[1] = grid11;
		array15[2] = stackLayout;
		array15[3] = scrollView;
		array15[4] = sharerRegisterView;
		object service15;
		xamlServiceProvider15.Add(typeFromHandle29, service15 = new SimpleValueTargetProvider(array15, VisualElement.BackgroundColorProperty, nameScope));
		xamlServiceProvider15.Add(typeof(IReferenceProvider), service15);
		Type typeFromHandle30 = typeof(IXamlTypeResolver);
		XmlNamespaceResolver xmlNamespaceResolver15 = new XmlNamespaceResolver();
		xmlNamespaceResolver15.Add("", "http://xamarin.com/schemas/2014/forms");
		xmlNamespaceResolver15.Add("x", "http://schemas.microsoft.com/winfx/2009/xaml");
		xmlNamespaceResolver15.Add("calx", "clr-namespace:Caliburn.Micro.Xamarin.Forms;assembly=Caliburn.Micro.Platform.Xamarin.Forms");
		xmlNamespaceResolver15.Add("renderer", "clr-namespace:NHL.Views.Renderer");
		xmlNamespaceResolver15.Add("converter", "clr-namespace:NHL.Views.Converters");
		xmlNamespaceResolver15.Add("effect", "clr-namespace:NHL.Views.Effect");
		xmlNamespaceResolver15.Add("system", "clr-namespace:System;assembly=System.Runtime.Extensions");
		xamlServiceProvider15.Add(typeFromHandle30, new XamlTypeResolver(xmlNamespaceResolver15, typeof(SharerRegisterView).GetTypeInfo().Assembly));
		xamlServiceProvider15.Add(typeof(IXmlLineInfoProvider), new XmlLineInfoProvider(new XmlLineInfo(188, 25)));
		object obj6 = ((IMarkupExtension)staticResourceExtension6).ProvideValue((IServiceProvider)xamlServiceProvider15);
		button.BackgroundColor = (Color)obj6;
		VisualDiagnostics.RegisterSourceInfo(obj6, new Uri("Views/SharerRegisterView.xaml", UriKind.RelativeOrAbsolute), 188, 25);
		staticResourceExtension7.Key = "BooleanSwitchConverter";
		XamlServiceProvider xamlServiceProvider16 = new XamlServiceProvider();
		Type typeFromHandle31 = typeof(IProvideValueTarget);
		object[] array16 = new object[0 + 6];
		array16[0] = bindingExtension9;
		array16[1] = button;
		array16[2] = grid11;
		array16[3] = stackLayout;
		array16[4] = scrollView;
		array16[5] = sharerRegisterView;
		object service16;
		xamlServiceProvider16.Add(typeFromHandle31, service16 = new SimpleValueTargetProvider(array16, typeof(BindingExtension).GetRuntimeProperty("Converter"), nameScope));
		xamlServiceProvider16.Add(typeof(IReferenceProvider), service16);
		Type typeFromHandle32 = typeof(IXamlTypeResolver);
		XmlNamespaceResolver xmlNamespaceResolver16 = new XmlNamespaceResolver();
		xmlNamespaceResolver16.Add("", "http://xamarin.com/schemas/2014/forms");
		xmlNamespaceResolver16.Add("x", "http://schemas.microsoft.com/winfx/2009/xaml");
		xmlNamespaceResolver16.Add("calx", "clr-namespace:Caliburn.Micro.Xamarin.Forms;assembly=Caliburn.Micro.Platform.Xamarin.Forms");
		xmlNamespaceResolver16.Add("renderer", "clr-namespace:NHL.Views.Renderer");
		xmlNamespaceResolver16.Add("converter", "clr-namespace:NHL.Views.Converters");
		xmlNamespaceResolver16.Add("effect", "clr-namespace:NHL.Views.Effect");
		xmlNamespaceResolver16.Add("system", "clr-namespace:System;assembly=System.Runtime.Extensions");
		xamlServiceProvider16.Add(typeFromHandle32, new XamlTypeResolver(xmlNamespaceResolver16, typeof(SharerRegisterView).GetTypeInfo().Assembly));
		xamlServiceProvider16.Add(typeof(IXmlLineInfoProvider), new XmlLineInfoProvider(new XmlLineInfo(189, 25)));
		object target = (bindingExtension9.Converter = (IValueConverter)((IMarkupExtension)staticResourceExtension7).ProvideValue((IServiceProvider)xamlServiceProvider16));
		VisualDiagnostics.RegisterSourceInfo(target, new Uri("Views/SharerRegisterView.xaml", UriKind.RelativeOrAbsolute), 189, 25);
		bindingExtension9.Path = "IsSharerRegistered";
		BindingBase binding9 = ((IMarkupExtension<BindingBase>)bindingExtension9).ProvideValue((IServiceProvider)null);
		button.SetBinding(VisualElement.IsVisibleProperty, binding9);
		bindingExtension10.Path = "IsNetworkEnabled";
		BindingBase binding10 = ((IMarkupExtension<BindingBase>)bindingExtension10).ProvideValue((IServiceProvider)null);
		button.SetBinding(VisualElement.IsEnabledProperty, binding10);
		button.Effects.Add(fixedFontSizeButtonEffect);
		VisualDiagnostics.RegisterSourceInfo(fixedFontSizeButtonEffect, new Uri("Views/SharerRegisterView.xaml", UriKind.RelativeOrAbsolute), 192, 26);
		grid11.Children.Add(button);
		VisualDiagnostics.RegisterSourceInfo(button, new Uri("Views/SharerRegisterView.xaml", UriKind.RelativeOrAbsolute), 182, 18);
		button2.SetValue(Grid.RowProperty, 10);
		button2.SetValue(Grid.ColumnProperty, 0);
		button2.SetValue(Grid.ColumnSpanProperty, 2);
		button2.SetValue(Xamarin.Forms.View.MarginProperty, new Thickness(10.0, 10.0, 10.0, 5.0));
		button2.SetValue(Button.TextProperty, "保存");
		button2.SetValue(Message.AttachProperty, "Update");
		button2.SetValue(Xamarin.Forms.View.HorizontalOptionsProperty, LayoutOptions.FillAndExpand);
		button2.SetValue(Button.TextColorProperty, Color.White);
		staticResourceExtension8.Key = "ButtonColor";
		XamlServiceProvider xamlServiceProvider17 = new XamlServiceProvider();
		Type typeFromHandle33 = typeof(IProvideValueTarget);
		object[] array17 = new object[0 + 5];
		array17[0] = button2;
		array17[1] = grid11;
		array17[2] = stackLayout;
		array17[3] = scrollView;
		array17[4] = sharerRegisterView;
		object service17;
		xamlServiceProvider17.Add(typeFromHandle33, service17 = new SimpleValueTargetProvider(array17, VisualElement.BackgroundColorProperty, nameScope));
		xamlServiceProvider17.Add(typeof(IReferenceProvider), service17);
		Type typeFromHandle34 = typeof(IXamlTypeResolver);
		XmlNamespaceResolver xmlNamespaceResolver17 = new XmlNamespaceResolver();
		xmlNamespaceResolver17.Add("", "http://xamarin.com/schemas/2014/forms");
		xmlNamespaceResolver17.Add("x", "http://schemas.microsoft.com/winfx/2009/xaml");
		xmlNamespaceResolver17.Add("calx", "clr-namespace:Caliburn.Micro.Xamarin.Forms;assembly=Caliburn.Micro.Platform.Xamarin.Forms");
		xmlNamespaceResolver17.Add("renderer", "clr-namespace:NHL.Views.Renderer");
		xmlNamespaceResolver17.Add("converter", "clr-namespace:NHL.Views.Converters");
		xmlNamespaceResolver17.Add("effect", "clr-namespace:NHL.Views.Effect");
		xmlNamespaceResolver17.Add("system", "clr-namespace:System;assembly=System.Runtime.Extensions");
		xamlServiceProvider17.Add(typeFromHandle34, new XamlTypeResolver(xmlNamespaceResolver17, typeof(SharerRegisterView).GetTypeInfo().Assembly));
		xamlServiceProvider17.Add(typeof(IXmlLineInfoProvider), new XmlLineInfoProvider(new XmlLineInfo(201, 25)));
		object obj7 = ((IMarkupExtension)staticResourceExtension8).ProvideValue((IServiceProvider)xamlServiceProvider17);
		button2.BackgroundColor = (Color)obj7;
		VisualDiagnostics.RegisterSourceInfo(obj7, new Uri("Views/SharerRegisterView.xaml", UriKind.RelativeOrAbsolute), 201, 25);
		bindingExtension11.Path = "IsSharerRegistered";
		BindingBase binding11 = ((IMarkupExtension<BindingBase>)bindingExtension11).ProvideValue((IServiceProvider)null);
		button2.SetBinding(VisualElement.IsVisibleProperty, binding11);
		bindingExtension12.Path = "IsNetworkEnabled";
		BindingBase binding12 = ((IMarkupExtension<BindingBase>)bindingExtension12).ProvideValue((IServiceProvider)null);
		button2.SetBinding(VisualElement.IsEnabledProperty, binding12);
		button2.Effects.Add(fixedFontSizeButtonEffect2);
		VisualDiagnostics.RegisterSourceInfo(fixedFontSizeButtonEffect2, new Uri("Views/SharerRegisterView.xaml", UriKind.RelativeOrAbsolute), 205, 26);
		grid11.Children.Add(button2);
		VisualDiagnostics.RegisterSourceInfo(button2, new Uri("Views/SharerRegisterView.xaml", UriKind.RelativeOrAbsolute), 195, 18);
		stackLayout.Children.Add(grid11);
		VisualDiagnostics.RegisterSourceInfo(grid11, new Uri("Views/SharerRegisterView.xaml", UriKind.RelativeOrAbsolute), 52, 14);
		scrollView.Content = stackLayout;
		VisualDiagnostics.RegisterSourceInfo(stackLayout, new Uri("Views/SharerRegisterView.xaml", UriKind.RelativeOrAbsolute), 51, 10);
		sharerRegisterView.SetValue(ContentPage.ContentProperty, scrollView);
		VisualDiagnostics.RegisterSourceInfo(scrollView, new Uri("Views/SharerRegisterView.xaml", UriKind.RelativeOrAbsolute), 50, 6);
		VisualDiagnostics.RegisterSourceInfo(sharerRegisterView, new Uri("Views/SharerRegisterView.xaml", UriKind.RelativeOrAbsolute), 3, 2);
	}

	private void __InitComponentRuntime()
	{
		this.LoadFromXaml(typeof(SharerRegisterView));
	}
}
