using System;
using System.CodeDom.Compiler;
using System.Reflection;
using Caliburn.Micro.Xamarin.Forms;
using NHL.Views.Converters;
using NHL.Views.Effect;
using Xamarin.Forms;
using Xamarin.Forms.Internals;
using Xamarin.Forms.Xaml;
using Xamarin.Forms.Xaml.Diagnostics;
using Xamarin.Forms.Xaml.Internals;

namespace NHL.Views;

[XamlCompilation(XamlCompilationOptions.Compile)]
[XamlFilePath("Views/SharerInformationView.xaml")]
public class SharerInformationView : ContentPage
{
	public SharerInformationView()
	{
		InitializeComponent();
	}

	[GeneratedCode("Xamarin.Forms.Build.Tasks.XamlG", "2.0.0.0")]
	private void InitializeComponent()
	{
		if (ResourceLoader.CanProvideContentFor(new ResourceLoader.ResourceLoadingQuery
		{
			AssemblyName = typeof(SharerInformationView).GetTypeInfo().Assembly.GetName(),
			ResourcePath = "Views/SharerInformationView.xaml",
			Instance = this
		}))
		{
			__InitComponentRuntime();
			return;
		}
		if (XamlLoader.XamlFileProvider != null && XamlLoader.XamlFileProvider(GetType()) != null)
		{
			__InitComponentRuntime();
			return;
		}
		StaticResourceExtension staticResourceExtension = new StaticResourceExtension();
		BooleanSwitchConverter value = new BooleanSwitchConverter();
		Color color = Color.FromHex("#EFEFF4");
		Color color2 = Color.FromHex("#CFCFCF");
		Color color3 = Color.FromHex("#5B9BD5");
		ResourceDictionary resourceDictionary = new ResourceDictionary();
		OnPlatform<Thickness> onPlatform = new OnPlatform<Thickness>();
		RowDefinition rowDefinition = new RowDefinition();
		RowDefinition rowDefinition2 = new RowDefinition();
		RowDefinition rowDefinition3 = new RowDefinition();
		RowDefinition rowDefinition4 = new RowDefinition();
		RowDefinition item = new RowDefinition();
		FixedFontSizeLabelEffect fixedFontSizeLabelEffect = new FixedFontSizeLabelEffect();
		Label label = new Label();
		ColumnDefinition item2 = new ColumnDefinition();
		ColumnDefinition columnDefinition = new ColumnDefinition();
		RowDefinition rowDefinition5 = new RowDefinition();
		RowDefinition rowDefinition6 = new RowDefinition();
		StaticResourceExtension staticResourceExtension2 = new StaticResourceExtension();
		BindingExtension bindingExtension = new BindingExtension();
		FixedFontSizeLabelEffect fixedFontSizeLabelEffect2 = new FixedFontSizeLabelEffect();
		Span span = new Span();
		FormattedString formattedString = new FormattedString();
		Label label2 = new Label();
		BindingExtension bindingExtension2 = new BindingExtension();
		FixedFontSizeLabelEffect fixedFontSizeLabelEffect3 = new FixedFontSizeLabelEffect();
		Span span2 = new Span();
		BindingExtension bindingExtension3 = new BindingExtension();
		Span span3 = new Span();
		string newLine = Environment.NewLine;
		Span span4 = new Span();
		Span span5 = new Span();
		BindingExtension bindingExtension4 = new BindingExtension();
		Span span6 = new Span();
		FormattedString formattedString2 = new FormattedString();
		Label label3 = new Label();
		StaticResourceExtension staticResourceExtension3 = new StaticResourceExtension();
		BindingExtension bindingExtension5 = new BindingExtension();
		BindingExtension bindingExtension6 = new BindingExtension();
		FixedFontSizeButtonEffect fixedFontSizeButtonEffect = new FixedFontSizeButtonEffect();
		Button button = new Button();
		BindingExtension bindingExtension7 = new BindingExtension();
		BindingExtension bindingExtension8 = new BindingExtension();
		FixedFontSizeButtonEffect fixedFontSizeButtonEffect2 = new FixedFontSizeButtonEffect();
		Button button2 = new Button();
		FixedFontSizeLabelEffect fixedFontSizeLabelEffect4 = new FixedFontSizeLabelEffect();
		Label label4 = new Label();
		StaticResourceExtension staticResourceExtension4 = new StaticResourceExtension();
		BoxView boxView = new BoxView();
		Grid grid = new Grid();
		BindingExtension bindingExtension9 = new BindingExtension();
		FixedFontSizeLabelEffect fixedFontSizeLabelEffect5 = new FixedFontSizeLabelEffect();
		Label label5 = new Label();
		FixedFontSizeButtonEffect fixedFontSizeButtonEffect3 = new FixedFontSizeButtonEffect();
		Button button3 = new Button();
		StaticResourceExtension staticResourceExtension5 = new StaticResourceExtension();
		FixedFontSizeButtonEffect fixedFontSizeButtonEffect4 = new FixedFontSizeButtonEffect();
		Button button4 = new Button();
		FixedFontSizeLabelEffect fixedFontSizeLabelEffect6 = new FixedFontSizeLabelEffect();
		Span span7 = new Span();
		string newLine2 = Environment.NewLine;
		Span span8 = new Span();
		Span span9 = new Span();
		string newLine3 = Environment.NewLine;
		Span span10 = new Span();
		string newLine4 = Environment.NewLine;
		Span span11 = new Span();
		Span span12 = new Span();
		FormattedString formattedString3 = new FormattedString();
		Label label6 = new Label();
		Grid grid2 = new Grid();
		ScrollView scrollView = new ScrollView();
		SharerInformationView sharerInformationView;
		NameScope nameScope = (NameScope)(NameScope.GetNameScope(sharerInformationView = this) ?? new NameScope());
		NameScope.SetNameScope(sharerInformationView, nameScope);
		sharerInformationView.Resources = resourceDictionary;
		VisualDiagnostics.RegisterSourceInfo(resourceDictionary, new Uri("Views/SharerInformationView.xaml", UriKind.RelativeOrAbsolute), 16, 10);
		resourceDictionary.Add("BooleanSwitchConverter", value);
		resourceDictionary.Add("PageBackgroundColor", color);
		resourceDictionary.Add("LineColor", color2);
		resourceDictionary.Add("ButtonColor", color3);
		sharerInformationView.SetValue(NavigationPage.HasBackButtonProperty, true);
		sharerInformationView.SetValue(NavigationPage.BackButtonTitleProperty, "戻る");
		sharerInformationView.SetValue(Page.TitleProperty, "WEB機能（本人用）");
		staticResourceExtension.Key = "PageBackgroundColor";
		XamlServiceProvider xamlServiceProvider = new XamlServiceProvider();
		Type typeFromHandle = typeof(IProvideValueTarget);
		object[] array = new object[0 + 1];
		array[0] = sharerInformationView;
		object service;
		xamlServiceProvider.Add(typeFromHandle, service = new SimpleValueTargetProvider(array, VisualElement.BackgroundColorProperty, nameScope));
		xamlServiceProvider.Add(typeof(IReferenceProvider), service);
		Type typeFromHandle2 = typeof(IXamlTypeResolver);
		XmlNamespaceResolver xmlNamespaceResolver = new XmlNamespaceResolver();
		xmlNamespaceResolver.Add("", "http://xamarin.com/schemas/2014/forms");
		xmlNamespaceResolver.Add("x", "http://schemas.microsoft.com/winfx/2009/xaml");
		xmlNamespaceResolver.Add("calx", "clr-namespace:Caliburn.Micro.Xamarin.Forms;assembly=Caliburn.Micro.Platform.Xamarin.Forms");
		xmlNamespaceResolver.Add("converter", "clr-namespace:NHL.Views.Converters");
		xmlNamespaceResolver.Add("effect", "clr-namespace:NHL.Views.Effect");
		xmlNamespaceResolver.Add("system", "clr-namespace:System;assembly=System.Runtime.Extensions");
		xamlServiceProvider.Add(typeFromHandle2, new XamlTypeResolver(xmlNamespaceResolver, typeof(SharerInformationView).GetTypeInfo().Assembly));
		xamlServiceProvider.Add(typeof(IXmlLineInfoProvider), new XmlLineInfoProvider(new XmlLineInfo(13, 14)));
		object obj = ((IMarkupExtension)staticResourceExtension).ProvideValue((IServiceProvider)xamlServiceProvider);
		sharerInformationView.BackgroundColor = (Color)obj;
		VisualDiagnostics.RegisterSourceInfo(obj, new Uri("Views/SharerInformationView.xaml", UriKind.RelativeOrAbsolute), 13, 14);
		sharerInformationView.Resources = resourceDictionary;
		VisualDiagnostics.RegisterSourceInfo(resourceDictionary, new Uri("Views/SharerInformationView.xaml", UriKind.RelativeOrAbsolute), 16, 10);
		onPlatform.iOS = new Thickness(0.0, 20.0, 0.0, 20.0);
		onPlatform.Android = new Thickness(0.0, 10.0, 0.0, 20.0);
		sharerInformationView.SetValue(Page.PaddingProperty, (Thickness)onPlatform);
		VisualDiagnostics.RegisterSourceInfo(onPlatform, new Uri("Views/SharerInformationView.xaml", UriKind.RelativeOrAbsolute), 40, 10);
		grid2.SetValue(Grid.RowSpacingProperty, 0.0);
		grid2.SetValue(Grid.ColumnSpacingProperty, 0.0);
		rowDefinition.SetValue(RowDefinition.HeightProperty, new GridLengthTypeConverter().ConvertFromInvariantString("Auto"));
		((DefinitionCollection<RowDefinition>)grid2.GetValue(Grid.RowDefinitionsProperty)).Add(rowDefinition);
		rowDefinition2.SetValue(RowDefinition.HeightProperty, new GridLengthTypeConverter().ConvertFromInvariantString("Auto"));
		((DefinitionCollection<RowDefinition>)grid2.GetValue(Grid.RowDefinitionsProperty)).Add(rowDefinition2);
		rowDefinition3.SetValue(RowDefinition.HeightProperty, new GridLengthTypeConverter().ConvertFromInvariantString("Auto"));
		((DefinitionCollection<RowDefinition>)grid2.GetValue(Grid.RowDefinitionsProperty)).Add(rowDefinition3);
		rowDefinition4.SetValue(RowDefinition.HeightProperty, new GridLengthTypeConverter().ConvertFromInvariantString("Auto"));
		((DefinitionCollection<RowDefinition>)grid2.GetValue(Grid.RowDefinitionsProperty)).Add(rowDefinition4);
		((DefinitionCollection<RowDefinition>)grid2.GetValue(Grid.RowDefinitionsProperty)).Add(item);
		label.SetValue(Grid.RowProperty, 0);
		label.SetValue(Label.TextProperty, "アカウント情報");
		label.SetValue(Xamarin.Forms.View.MarginProperty, new Thickness(10.0, 0.0, 0.0, 0.0));
		label.Effects.Add(fixedFontSizeLabelEffect);
		VisualDiagnostics.RegisterSourceInfo(fixedFontSizeLabelEffect, new Uri("Views/SharerInformationView.xaml", UriKind.RelativeOrAbsolute), 56, 18);
		grid2.Children.Add(label);
		VisualDiagnostics.RegisterSourceInfo(label, new Uri("Views/SharerInformationView.xaml", UriKind.RelativeOrAbsolute), 54, 10);
		grid.SetValue(Grid.RowProperty, 1);
		grid.SetValue(Grid.RowSpacingProperty, 0.0);
		grid.SetValue(Grid.ColumnSpacingProperty, 0.0);
		grid.SetValue(VisualElement.BackgroundColorProperty, Color.White);
		grid.SetValue(Xamarin.Forms.View.HorizontalOptionsProperty, LayoutOptions.Fill);
		grid.SetValue(Xamarin.Forms.View.VerticalOptionsProperty, LayoutOptions.Center);
		((DefinitionCollection<ColumnDefinition>)grid.GetValue(Grid.ColumnDefinitionsProperty)).Add(item2);
		columnDefinition.SetValue(ColumnDefinition.WidthProperty, new GridLengthTypeConverter().ConvertFromInvariantString("30"));
		((DefinitionCollection<ColumnDefinition>)grid.GetValue(Grid.ColumnDefinitionsProperty)).Add(columnDefinition);
		rowDefinition5.SetValue(RowDefinition.HeightProperty, new GridLengthTypeConverter().ConvertFromInvariantString("Auto"));
		((DefinitionCollection<RowDefinition>)grid.GetValue(Grid.RowDefinitionsProperty)).Add(rowDefinition5);
		rowDefinition6.SetValue(RowDefinition.HeightProperty, new GridLengthTypeConverter().ConvertFromInvariantString("1"));
		((DefinitionCollection<RowDefinition>)grid.GetValue(Grid.RowDefinitionsProperty)).Add(rowDefinition6);
		label2.SetValue(Grid.RowProperty, 0);
		label2.SetValue(Grid.ColumnProperty, 0);
		label2.SetValue(Xamarin.Forms.View.MarginProperty, new Thickness(10.0, 0.0, 0.0, 1.0));
		label2.SetValue(Label.VerticalTextAlignmentProperty, new TextAlignmentConverter().ConvertFromInvariantString("Center"));
		label2.SetValue(Xamarin.Forms.View.VerticalOptionsProperty, LayoutOptions.Center);
		staticResourceExtension2.Key = "BooleanSwitchConverter";
		XamlServiceProvider xamlServiceProvider2 = new XamlServiceProvider();
		Type typeFromHandle3 = typeof(IProvideValueTarget);
		object[] array2 = new object[0 + 6];
		array2[0] = bindingExtension;
		array2[1] = label2;
		array2[2] = grid;
		array2[3] = grid2;
		array2[4] = scrollView;
		array2[5] = sharerInformationView;
		object service2;
		xamlServiceProvider2.Add(typeFromHandle3, service2 = new SimpleValueTargetProvider(array2, typeof(BindingExtension).GetRuntimeProperty("Converter"), nameScope));
		xamlServiceProvider2.Add(typeof(IReferenceProvider), service2);
		Type typeFromHandle4 = typeof(IXamlTypeResolver);
		XmlNamespaceResolver xmlNamespaceResolver2 = new XmlNamespaceResolver();
		xmlNamespaceResolver2.Add("", "http://xamarin.com/schemas/2014/forms");
		xmlNamespaceResolver2.Add("x", "http://schemas.microsoft.com/winfx/2009/xaml");
		xmlNamespaceResolver2.Add("calx", "clr-namespace:Caliburn.Micro.Xamarin.Forms;assembly=Caliburn.Micro.Platform.Xamarin.Forms");
		xmlNamespaceResolver2.Add("converter", "clr-namespace:NHL.Views.Converters");
		xmlNamespaceResolver2.Add("effect", "clr-namespace:NHL.Views.Effect");
		xmlNamespaceResolver2.Add("system", "clr-namespace:System;assembly=System.Runtime.Extensions");
		xamlServiceProvider2.Add(typeFromHandle4, new XamlTypeResolver(xmlNamespaceResolver2, typeof(SharerInformationView).GetTypeInfo().Assembly));
		xamlServiceProvider2.Add(typeof(IXmlLineInfoProvider), new XmlLineInfoProvider(new XmlLineInfo(75, 20)));
		object target = (bindingExtension.Converter = (IValueConverter)((IMarkupExtension)staticResourceExtension2).ProvideValue((IServiceProvider)xamlServiceProvider2));
		VisualDiagnostics.RegisterSourceInfo(target, new Uri("Views/SharerInformationView.xaml", UriKind.RelativeOrAbsolute), 75, 20);
		bindingExtension.Path = "IsSharerRegistered";
		BindingBase binding = ((IMarkupExtension<BindingBase>)bindingExtension).ProvideValue((IServiceProvider)null);
		label2.SetBinding(VisualElement.IsVisibleProperty, binding);
		label2.Effects.Add(fixedFontSizeLabelEffect2);
		VisualDiagnostics.RegisterSourceInfo(fixedFontSizeLabelEffect2, new Uri("Views/SharerInformationView.xaml", UriKind.RelativeOrAbsolute), 77, 22);
		span.SetValue(Span.TextProperty, "未登録");
		formattedString.Spans.Add(span);
		VisualDiagnostics.RegisterSourceInfo(span, new Uri("Views/SharerInformationView.xaml", UriKind.RelativeOrAbsolute), 81, 26);
		label2.SetValue(Label.FormattedTextProperty, formattedString);
		VisualDiagnostics.RegisterSourceInfo(formattedString, new Uri("Views/SharerInformationView.xaml", UriKind.RelativeOrAbsolute), 80, 22);
		grid.Children.Add(label2);
		VisualDiagnostics.RegisterSourceInfo(label2, new Uri("Views/SharerInformationView.xaml", UriKind.RelativeOrAbsolute), 71, 14);
		label3.SetValue(Grid.RowProperty, 0);
		label3.SetValue(Grid.ColumnProperty, 0);
		label3.SetValue(Xamarin.Forms.View.MarginProperty, new Thickness(10.0, 0.0, 0.0, 1.0));
		label3.SetValue(Label.VerticalTextAlignmentProperty, new TextAlignmentConverter().ConvertFromInvariantString("Center"));
		label3.SetValue(Xamarin.Forms.View.VerticalOptionsProperty, LayoutOptions.Center);
		bindingExtension2.Path = "IsSharerRegistered";
		BindingBase binding2 = ((IMarkupExtension<BindingBase>)bindingExtension2).ProvideValue((IServiceProvider)null);
		label3.SetBinding(VisualElement.IsVisibleProperty, binding2);
		label3.Effects.Add(fixedFontSizeLabelEffect3);
		VisualDiagnostics.RegisterSourceInfo(fixedFontSizeLabelEffect3, new Uri("Views/SharerInformationView.xaml", UriKind.RelativeOrAbsolute), 91, 22);
		span2.SetValue(Span.TextProperty, "共有コード：");
		formattedString2.Spans.Add(span2);
		VisualDiagnostics.RegisterSourceInfo(span2, new Uri("Views/SharerInformationView.xaml", UriKind.RelativeOrAbsolute), 95, 26);
		bindingExtension3.Path = "SharerHospitalCode";
		BindingBase binding3 = ((IMarkupExtension<BindingBase>)bindingExtension3).ProvideValue((IServiceProvider)null);
		span3.SetBinding(Span.TextProperty, binding3);
		formattedString2.Spans.Add(span3);
		VisualDiagnostics.RegisterSourceInfo(span3, new Uri("Views/SharerInformationView.xaml", UriKind.RelativeOrAbsolute), 96, 26);
		span4.SetValue(Span.TextProperty, newLine);
		VisualDiagnostics.RegisterSourceInfo(newLine, new Uri("Views/SharerInformationView.xaml", UriKind.RelativeOrAbsolute), 97, 31);
		formattedString2.Spans.Add(span4);
		VisualDiagnostics.RegisterSourceInfo(span4, new Uri("Views/SharerInformationView.xaml", UriKind.RelativeOrAbsolute), 97, 26);
		span5.SetValue(Span.TextProperty, "ユーザーID：");
		formattedString2.Spans.Add(span5);
		VisualDiagnostics.RegisterSourceInfo(span5, new Uri("Views/SharerInformationView.xaml", UriKind.RelativeOrAbsolute), 98, 26);
		bindingExtension4.Path = "SharerLoginId";
		BindingBase binding4 = ((IMarkupExtension<BindingBase>)bindingExtension4).ProvideValue((IServiceProvider)null);
		span6.SetBinding(Span.TextProperty, binding4);
		formattedString2.Spans.Add(span6);
		VisualDiagnostics.RegisterSourceInfo(span6, new Uri("Views/SharerInformationView.xaml", UriKind.RelativeOrAbsolute), 99, 26);
		label3.SetValue(Label.FormattedTextProperty, formattedString2);
		VisualDiagnostics.RegisterSourceInfo(formattedString2, new Uri("Views/SharerInformationView.xaml", UriKind.RelativeOrAbsolute), 94, 22);
		grid.Children.Add(label3);
		VisualDiagnostics.RegisterSourceInfo(label3, new Uri("Views/SharerInformationView.xaml", UriKind.RelativeOrAbsolute), 85, 14);
		button.SetValue(Grid.RowProperty, 0);
		button.SetValue(Grid.ColumnProperty, 0);
		button.SetValue(Grid.ColumnSpanProperty, 2);
		button.SetValue(Message.AttachProperty, "Introduction");
		button.SetValue(VisualElement.BackgroundColorProperty, Color.Transparent);
		staticResourceExtension3.Key = "BooleanSwitchConverter";
		XamlServiceProvider xamlServiceProvider3 = new XamlServiceProvider();
		Type typeFromHandle5 = typeof(IProvideValueTarget);
		object[] array3 = new object[0 + 6];
		array3[0] = bindingExtension5;
		array3[1] = button;
		array3[2] = grid;
		array3[3] = grid2;
		array3[4] = scrollView;
		array3[5] = sharerInformationView;
		object service3;
		xamlServiceProvider3.Add(typeFromHandle5, service3 = new SimpleValueTargetProvider(array3, typeof(BindingExtension).GetRuntimeProperty("Converter"), nameScope));
		xamlServiceProvider3.Add(typeof(IReferenceProvider), service3);
		Type typeFromHandle6 = typeof(IXamlTypeResolver);
		XmlNamespaceResolver xmlNamespaceResolver3 = new XmlNamespaceResolver();
		xmlNamespaceResolver3.Add("", "http://xamarin.com/schemas/2014/forms");
		xmlNamespaceResolver3.Add("x", "http://schemas.microsoft.com/winfx/2009/xaml");
		xmlNamespaceResolver3.Add("calx", "clr-namespace:Caliburn.Micro.Xamarin.Forms;assembly=Caliburn.Micro.Platform.Xamarin.Forms");
		xmlNamespaceResolver3.Add("converter", "clr-namespace:NHL.Views.Converters");
		xmlNamespaceResolver3.Add("effect", "clr-namespace:NHL.Views.Effect");
		xmlNamespaceResolver3.Add("system", "clr-namespace:System;assembly=System.Runtime.Extensions");
		xamlServiceProvider3.Add(typeFromHandle6, new XamlTypeResolver(xmlNamespaceResolver3, typeof(SharerInformationView).GetTypeInfo().Assembly));
		xamlServiceProvider3.Add(typeof(IXmlLineInfoProvider), new XmlLineInfoProvider(new XmlLineInfo(105, 135)));
		object target2 = (bindingExtension5.Converter = (IValueConverter)((IMarkupExtension)staticResourceExtension3).ProvideValue((IServiceProvider)xamlServiceProvider3));
		VisualDiagnostics.RegisterSourceInfo(target2, new Uri("Views/SharerInformationView.xaml", UriKind.RelativeOrAbsolute), 105, 135);
		bindingExtension5.Path = "IsSharerRegistered";
		BindingBase binding5 = ((IMarkupExtension<BindingBase>)bindingExtension5).ProvideValue((IServiceProvider)null);
		button.SetBinding(VisualElement.IsVisibleProperty, binding5);
		bindingExtension6.Path = "IsNetworkEnabled";
		BindingBase binding6 = ((IMarkupExtension<BindingBase>)bindingExtension6).ProvideValue((IServiceProvider)null);
		button.SetBinding(VisualElement.IsEnabledProperty, binding6);
		button.Effects.Add(fixedFontSizeButtonEffect);
		VisualDiagnostics.RegisterSourceInfo(fixedFontSizeButtonEffect, new Uri("Views/SharerInformationView.xaml", UriKind.RelativeOrAbsolute), 107, 22);
		grid.Children.Add(button);
		VisualDiagnostics.RegisterSourceInfo(button, new Uri("Views/SharerInformationView.xaml", UriKind.RelativeOrAbsolute), 105, 14);
		button2.SetValue(Grid.RowProperty, 0);
		button2.SetValue(Grid.ColumnProperty, 0);
		button2.SetValue(Grid.ColumnSpanProperty, 2);
		button2.SetValue(Message.AttachProperty, "Update");
		button2.SetValue(VisualElement.BackgroundColorProperty, Color.Transparent);
		bindingExtension7.Path = "IsSharerRegistered";
		BindingBase binding7 = ((IMarkupExtension<BindingBase>)bindingExtension7).ProvideValue((IServiceProvider)null);
		button2.SetBinding(VisualElement.IsVisibleProperty, binding7);
		bindingExtension8.Path = "IsNetworkEnabled";
		BindingBase binding8 = ((IMarkupExtension<BindingBase>)bindingExtension8).ProvideValue((IServiceProvider)null);
		button2.SetBinding(VisualElement.IsEnabledProperty, binding8);
		button2.Effects.Add(fixedFontSizeButtonEffect2);
		VisualDiagnostics.RegisterSourceInfo(fixedFontSizeButtonEffect2, new Uri("Views/SharerInformationView.xaml", UriKind.RelativeOrAbsolute), 112, 22);
		grid.Children.Add(button2);
		VisualDiagnostics.RegisterSourceInfo(button2, new Uri("Views/SharerInformationView.xaml", UriKind.RelativeOrAbsolute), 110, 14);
		label4.SetValue(Grid.RowProperty, 0);
		label4.SetValue(Grid.ColumnProperty, 1);
		label4.SetValue(Label.TextProperty, "＞");
		label4.SetValue(Xamarin.Forms.View.HorizontalOptionsProperty, LayoutOptions.End);
		label4.SetValue(Label.VerticalTextAlignmentProperty, new TextAlignmentConverter().ConvertFromInvariantString("Center"));
		label4.Effects.Add(fixedFontSizeLabelEffect4);
		VisualDiagnostics.RegisterSourceInfo(fixedFontSizeLabelEffect4, new Uri("Views/SharerInformationView.xaml", UriKind.RelativeOrAbsolute), 118, 22);
		grid.Children.Add(label4);
		VisualDiagnostics.RegisterSourceInfo(label4, new Uri("Views/SharerInformationView.xaml", UriKind.RelativeOrAbsolute), 116, 14);
		boxView.SetValue(Grid.RowProperty, 1);
		boxView.SetValue(Grid.ColumnProperty, 0);
		boxView.SetValue(Grid.ColumnSpanProperty, 2);
		staticResourceExtension4.Key = "LineColor";
		XamlServiceProvider xamlServiceProvider4 = new XamlServiceProvider();
		Type typeFromHandle7 = typeof(IProvideValueTarget);
		object[] array4 = new object[0 + 5];
		array4[0] = boxView;
		array4[1] = grid;
		array4[2] = grid2;
		array4[3] = scrollView;
		array4[4] = sharerInformationView;
		object service4;
		xamlServiceProvider4.Add(typeFromHandle7, service4 = new SimpleValueTargetProvider(array4, VisualElement.BackgroundColorProperty, nameScope));
		xamlServiceProvider4.Add(typeof(IReferenceProvider), service4);
		Type typeFromHandle8 = typeof(IXamlTypeResolver);
		XmlNamespaceResolver xmlNamespaceResolver4 = new XmlNamespaceResolver();
		xmlNamespaceResolver4.Add("", "http://xamarin.com/schemas/2014/forms");
		xmlNamespaceResolver4.Add("x", "http://schemas.microsoft.com/winfx/2009/xaml");
		xmlNamespaceResolver4.Add("calx", "clr-namespace:Caliburn.Micro.Xamarin.Forms;assembly=Caliburn.Micro.Platform.Xamarin.Forms");
		xmlNamespaceResolver4.Add("converter", "clr-namespace:NHL.Views.Converters");
		xmlNamespaceResolver4.Add("effect", "clr-namespace:NHL.Views.Effect");
		xmlNamespaceResolver4.Add("system", "clr-namespace:System;assembly=System.Runtime.Extensions");
		xamlServiceProvider4.Add(typeFromHandle8, new XamlTypeResolver(xmlNamespaceResolver4, typeof(SharerInformationView).GetTypeInfo().Assembly));
		xamlServiceProvider4.Add(typeof(IXmlLineInfoProvider), new XmlLineInfoProvider(new XmlLineInfo(122, 71)));
		object obj2 = ((IMarkupExtension)staticResourceExtension4).ProvideValue((IServiceProvider)xamlServiceProvider4);
		boxView.BackgroundColor = (Color)obj2;
		VisualDiagnostics.RegisterSourceInfo(obj2, new Uri("Views/SharerInformationView.xaml", UriKind.RelativeOrAbsolute), 122, 71);
		grid.Children.Add(boxView);
		VisualDiagnostics.RegisterSourceInfo(boxView, new Uri("Views/SharerInformationView.xaml", UriKind.RelativeOrAbsolute), 122, 14);
		grid2.Children.Add(grid);
		VisualDiagnostics.RegisterSourceInfo(grid, new Uri("Views/SharerInformationView.xaml", UriKind.RelativeOrAbsolute), 60, 10);
		label5.SetValue(Grid.RowProperty, 2);
		label5.SetValue(Xamarin.Forms.View.MarginProperty, new Thickness(10.0));
		bindingExtension9.Path = "IgWebSharerLoginUrl";
		BindingBase binding9 = ((IMarkupExtension<BindingBase>)bindingExtension9).ProvideValue((IServiceProvider)null);
		label5.SetBinding(Label.TextProperty, binding9);
		BindableProperty fontSizeProperty = Label.FontSizeProperty;
		FontSizeConverter fontSizeConverter = new FontSizeConverter();
		XamlServiceProvider xamlServiceProvider5 = new XamlServiceProvider();
		Type typeFromHandle9 = typeof(IProvideValueTarget);
		object[] array5 = new object[0 + 4];
		array5[0] = label5;
		array5[1] = grid2;
		array5[2] = scrollView;
		array5[3] = sharerInformationView;
		object service5;
		xamlServiceProvider5.Add(typeFromHandle9, service5 = new SimpleValueTargetProvider(array5, Label.FontSizeProperty, nameScope));
		xamlServiceProvider5.Add(typeof(IReferenceProvider), service5);
		Type typeFromHandle10 = typeof(IXamlTypeResolver);
		XmlNamespaceResolver xmlNamespaceResolver5 = new XmlNamespaceResolver();
		xmlNamespaceResolver5.Add("", "http://xamarin.com/schemas/2014/forms");
		xmlNamespaceResolver5.Add("x", "http://schemas.microsoft.com/winfx/2009/xaml");
		xmlNamespaceResolver5.Add("calx", "clr-namespace:Caliburn.Micro.Xamarin.Forms;assembly=Caliburn.Micro.Platform.Xamarin.Forms");
		xmlNamespaceResolver5.Add("converter", "clr-namespace:NHL.Views.Converters");
		xmlNamespaceResolver5.Add("effect", "clr-namespace:NHL.Views.Effect");
		xmlNamespaceResolver5.Add("system", "clr-namespace:System;assembly=System.Runtime.Extensions");
		xamlServiceProvider5.Add(typeFromHandle10, new XamlTypeResolver(xmlNamespaceResolver5, typeof(SharerInformationView).GetTypeInfo().Assembly));
		xamlServiceProvider5.Add(typeof(IXmlLineInfoProvider), new XmlLineInfoProvider(new XmlLineInfo(126, 78)));
		label5.SetValue(fontSizeProperty, ((IExtendedTypeConverter)fontSizeConverter).ConvertFromInvariantString("Medium", (IServiceProvider)xamlServiceProvider5));
		label5.SetValue(Label.TextColorProperty, Color.Blue);
		label5.SetValue(Xamarin.Forms.View.HorizontalOptionsProperty, LayoutOptions.StartAndExpand);
		label5.SetValue(Label.VerticalTextAlignmentProperty, new TextAlignmentConverter().ConvertFromInvariantString("Center"));
		label5.SetValue(Xamarin.Forms.View.VerticalOptionsProperty, LayoutOptions.CenterAndExpand);
		label5.Effects.Add(fixedFontSizeLabelEffect5);
		VisualDiagnostics.RegisterSourceInfo(fixedFontSizeLabelEffect5, new Uri("Views/SharerInformationView.xaml", UriKind.RelativeOrAbsolute), 128, 18);
		grid2.Children.Add(label5);
		VisualDiagnostics.RegisterSourceInfo(label5, new Uri("Views/SharerInformationView.xaml", UriKind.RelativeOrAbsolute), 126, 10);
		button3.SetValue(Grid.RowProperty, 2);
		button3.SetValue(Message.AttachProperty, "OpenIgWebSharerLoginUrl");
		button3.SetValue(VisualElement.BackgroundColorProperty, Color.Transparent);
		button3.Effects.Add(fixedFontSizeButtonEffect3);
		VisualDiagnostics.RegisterSourceInfo(fixedFontSizeButtonEffect3, new Uri("Views/SharerInformationView.xaml", UriKind.RelativeOrAbsolute), 133, 18);
		grid2.Children.Add(button3);
		VisualDiagnostics.RegisterSourceInfo(button3, new Uri("Views/SharerInformationView.xaml", UriKind.RelativeOrAbsolute), 131, 10);
		button4.SetValue(Grid.RowProperty, 3);
		button4.SetValue(Xamarin.Forms.View.MarginProperty, new Thickness(10.0));
		button4.SetValue(Button.TextProperty, "リンクをコピー");
		button4.SetValue(Message.AttachProperty, "CopyButton");
		button4.SetValue(Xamarin.Forms.View.HorizontalOptionsProperty, LayoutOptions.FillAndExpand);
		button4.SetValue(Button.TextColorProperty, Color.White);
		staticResourceExtension5.Key = "ButtonColor";
		XamlServiceProvider xamlServiceProvider6 = new XamlServiceProvider();
		Type typeFromHandle11 = typeof(IProvideValueTarget);
		object[] array6 = new object[0 + 4];
		array6[0] = button4;
		array6[1] = grid2;
		array6[2] = scrollView;
		array6[3] = sharerInformationView;
		object service6;
		xamlServiceProvider6.Add(typeFromHandle11, service6 = new SimpleValueTargetProvider(array6, VisualElement.BackgroundColorProperty, nameScope));
		xamlServiceProvider6.Add(typeof(IReferenceProvider), service6);
		Type typeFromHandle12 = typeof(IXamlTypeResolver);
		XmlNamespaceResolver xmlNamespaceResolver6 = new XmlNamespaceResolver();
		xmlNamespaceResolver6.Add("", "http://xamarin.com/schemas/2014/forms");
		xmlNamespaceResolver6.Add("x", "http://schemas.microsoft.com/winfx/2009/xaml");
		xmlNamespaceResolver6.Add("calx", "clr-namespace:Caliburn.Micro.Xamarin.Forms;assembly=Caliburn.Micro.Platform.Xamarin.Forms");
		xmlNamespaceResolver6.Add("converter", "clr-namespace:NHL.Views.Converters");
		xmlNamespaceResolver6.Add("effect", "clr-namespace:NHL.Views.Effect");
		xmlNamespaceResolver6.Add("system", "clr-namespace:System;assembly=System.Runtime.Extensions");
		xamlServiceProvider6.Add(typeFromHandle12, new XamlTypeResolver(xmlNamespaceResolver6, typeof(SharerInformationView).GetTypeInfo().Assembly));
		xamlServiceProvider6.Add(typeof(IXmlLineInfoProvider), new XmlLineInfoProvider(new XmlLineInfo(137, 142)));
		object obj3 = ((IMarkupExtension)staticResourceExtension5).ProvideValue((IServiceProvider)xamlServiceProvider6);
		button4.BackgroundColor = (Color)obj3;
		VisualDiagnostics.RegisterSourceInfo(obj3, new Uri("Views/SharerInformationView.xaml", UriKind.RelativeOrAbsolute), 137, 142);
		button4.Effects.Add(fixedFontSizeButtonEffect4);
		VisualDiagnostics.RegisterSourceInfo(fixedFontSizeButtonEffect4, new Uri("Views/SharerInformationView.xaml", UriKind.RelativeOrAbsolute), 139, 18);
		grid2.Children.Add(button4);
		VisualDiagnostics.RegisterSourceInfo(button4, new Uri("Views/SharerInformationView.xaml", UriKind.RelativeOrAbsolute), 137, 10);
		label6.SetValue(Grid.RowProperty, 4);
		label6.SetValue(Xamarin.Forms.View.MarginProperty, new Thickness(10.0, 10.0, 10.0, 0.0));
		label6.Effects.Add(fixedFontSizeLabelEffect6);
		VisualDiagnostics.RegisterSourceInfo(fixedFontSizeLabelEffect6, new Uri("Views/SharerInformationView.xaml", UriKind.RelativeOrAbsolute), 146, 22);
		span7.SetValue(Span.TextProperty, "上記にアクセスしてWEB機能をご利用いただけます。");
		BindableProperty fontSizeProperty2 = Span.FontSizeProperty;
		FontSizeConverter fontSizeConverter2 = new FontSizeConverter();
		XamlServiceProvider xamlServiceProvider7 = new XamlServiceProvider();
		Type typeFromHandle13 = typeof(IProvideValueTarget);
		object[] array7 = new object[0 + 6];
		array7[0] = span7;
		array7[1] = formattedString3;
		array7[2] = label6;
		array7[3] = grid2;
		array7[4] = scrollView;
		array7[5] = sharerInformationView;
		object service7;
		xamlServiceProvider7.Add(typeFromHandle13, service7 = new SimpleValueTargetProvider(array7, Span.FontSizeProperty, nameScope));
		xamlServiceProvider7.Add(typeof(IReferenceProvider), service7);
		Type typeFromHandle14 = typeof(IXamlTypeResolver);
		XmlNamespaceResolver xmlNamespaceResolver7 = new XmlNamespaceResolver();
		xmlNamespaceResolver7.Add("", "http://xamarin.com/schemas/2014/forms");
		xmlNamespaceResolver7.Add("x", "http://schemas.microsoft.com/winfx/2009/xaml");
		xmlNamespaceResolver7.Add("calx", "clr-namespace:Caliburn.Micro.Xamarin.Forms;assembly=Caliburn.Micro.Platform.Xamarin.Forms");
		xmlNamespaceResolver7.Add("converter", "clr-namespace:NHL.Views.Converters");
		xmlNamespaceResolver7.Add("effect", "clr-namespace:NHL.Views.Effect");
		xmlNamespaceResolver7.Add("system", "clr-namespace:System;assembly=System.Runtime.Extensions");
		xamlServiceProvider7.Add(typeFromHandle14, new XamlTypeResolver(xmlNamespaceResolver7, typeof(SharerInformationView).GetTypeInfo().Assembly));
		xamlServiceProvider7.Add(typeof(IXmlLineInfoProvider), new XmlLineInfoProvider(new XmlLineInfo(150, 64)));
		span7.SetValue(fontSizeProperty2, ((IExtendedTypeConverter)fontSizeConverter2).ConvertFromInvariantString("Medium", (IServiceProvider)xamlServiceProvider7));
		formattedString3.Spans.Add(span7);
		VisualDiagnostics.RegisterSourceInfo(span7, new Uri("Views/SharerInformationView.xaml", UriKind.RelativeOrAbsolute), 150, 26);
		span8.SetValue(Span.TextProperty, newLine2);
		VisualDiagnostics.RegisterSourceInfo(newLine2, new Uri("Views/SharerInformationView.xaml", UriKind.RelativeOrAbsolute), 151, 31);
		formattedString3.Spans.Add(span8);
		VisualDiagnostics.RegisterSourceInfo(span8, new Uri("Views/SharerInformationView.xaml", UriKind.RelativeOrAbsolute), 151, 26);
		span9.SetValue(Span.TextProperty, "WEBページ内で家族や友人のアカウントを発行すればデータの共有が可能です。");
		BindableProperty fontSizeProperty3 = Span.FontSizeProperty;
		FontSizeConverter fontSizeConverter3 = new FontSizeConverter();
		XamlServiceProvider xamlServiceProvider8 = new XamlServiceProvider();
		Type typeFromHandle15 = typeof(IProvideValueTarget);
		object[] array8 = new object[0 + 6];
		array8[0] = span9;
		array8[1] = formattedString3;
		array8[2] = label6;
		array8[3] = grid2;
		array8[4] = scrollView;
		array8[5] = sharerInformationView;
		object service8;
		xamlServiceProvider8.Add(typeFromHandle15, service8 = new SimpleValueTargetProvider(array8, Span.FontSizeProperty, nameScope));
		xamlServiceProvider8.Add(typeof(IReferenceProvider), service8);
		Type typeFromHandle16 = typeof(IXamlTypeResolver);
		XmlNamespaceResolver xmlNamespaceResolver8 = new XmlNamespaceResolver();
		xmlNamespaceResolver8.Add("", "http://xamarin.com/schemas/2014/forms");
		xmlNamespaceResolver8.Add("x", "http://schemas.microsoft.com/winfx/2009/xaml");
		xmlNamespaceResolver8.Add("calx", "clr-namespace:Caliburn.Micro.Xamarin.Forms;assembly=Caliburn.Micro.Platform.Xamarin.Forms");
		xmlNamespaceResolver8.Add("converter", "clr-namespace:NHL.Views.Converters");
		xmlNamespaceResolver8.Add("effect", "clr-namespace:NHL.Views.Effect");
		xmlNamespaceResolver8.Add("system", "clr-namespace:System;assembly=System.Runtime.Extensions");
		xamlServiceProvider8.Add(typeFromHandle16, new XamlTypeResolver(xmlNamespaceResolver8, typeof(SharerInformationView).GetTypeInfo().Assembly));
		xamlServiceProvider8.Add(typeof(IXmlLineInfoProvider), new XmlLineInfoProvider(new XmlLineInfo(152, 76)));
		span9.SetValue(fontSizeProperty3, ((IExtendedTypeConverter)fontSizeConverter3).ConvertFromInvariantString("Medium", (IServiceProvider)xamlServiceProvider8));
		formattedString3.Spans.Add(span9);
		VisualDiagnostics.RegisterSourceInfo(span9, new Uri("Views/SharerInformationView.xaml", UriKind.RelativeOrAbsolute), 152, 26);
		span10.SetValue(Span.TextProperty, newLine3);
		VisualDiagnostics.RegisterSourceInfo(newLine3, new Uri("Views/SharerInformationView.xaml", UriKind.RelativeOrAbsolute), 153, 31);
		formattedString3.Spans.Add(span10);
		VisualDiagnostics.RegisterSourceInfo(span10, new Uri("Views/SharerInformationView.xaml", UriKind.RelativeOrAbsolute), 153, 26);
		span11.SetValue(Span.TextProperty, newLine4);
		VisualDiagnostics.RegisterSourceInfo(newLine4, new Uri("Views/SharerInformationView.xaml", UriKind.RelativeOrAbsolute), 154, 31);
		BindableProperty fontSizeProperty4 = Span.FontSizeProperty;
		FontSizeConverter fontSizeConverter4 = new FontSizeConverter();
		XamlServiceProvider xamlServiceProvider9 = new XamlServiceProvider();
		Type typeFromHandle17 = typeof(IProvideValueTarget);
		object[] array9 = new object[0 + 6];
		array9[0] = span11;
		array9[1] = formattedString3;
		array9[2] = label6;
		array9[3] = grid2;
		array9[4] = scrollView;
		array9[5] = sharerInformationView;
		object service9;
		xamlServiceProvider9.Add(typeFromHandle17, service9 = new SimpleValueTargetProvider(array9, Span.FontSizeProperty, nameScope));
		xamlServiceProvider9.Add(typeof(IReferenceProvider), service9);
		Type typeFromHandle18 = typeof(IXamlTypeResolver);
		XmlNamespaceResolver xmlNamespaceResolver9 = new XmlNamespaceResolver();
		xmlNamespaceResolver9.Add("", "http://xamarin.com/schemas/2014/forms");
		xmlNamespaceResolver9.Add("x", "http://schemas.microsoft.com/winfx/2009/xaml");
		xmlNamespaceResolver9.Add("calx", "clr-namespace:Caliburn.Micro.Xamarin.Forms;assembly=Caliburn.Micro.Platform.Xamarin.Forms");
		xmlNamespaceResolver9.Add("converter", "clr-namespace:NHL.Views.Converters");
		xmlNamespaceResolver9.Add("effect", "clr-namespace:NHL.Views.Effect");
		xmlNamespaceResolver9.Add("system", "clr-namespace:System;assembly=System.Runtime.Extensions");
		xamlServiceProvider9.Add(typeFromHandle18, new XamlTypeResolver(xmlNamespaceResolver9, typeof(SharerInformationView).GetTypeInfo().Assembly));
		xamlServiceProvider9.Add(typeof(IXmlLineInfoProvider), new XmlLineInfoProvider(new XmlLineInfo(154, 76)));
		span11.SetValue(fontSizeProperty4, ((IExtendedTypeConverter)fontSizeConverter4).ConvertFromInvariantString("Small", (IServiceProvider)xamlServiceProvider9));
		formattedString3.Spans.Add(span11);
		VisualDiagnostics.RegisterSourceInfo(span11, new Uri("Views/SharerInformationView.xaml", UriKind.RelativeOrAbsolute), 154, 26);
		span12.SetValue(Span.TextProperty, "※PCでの利用が推奨です。");
		BindableProperty fontSizeProperty5 = Span.FontSizeProperty;
		FontSizeConverter fontSizeConverter5 = new FontSizeConverter();
		XamlServiceProvider xamlServiceProvider10 = new XamlServiceProvider();
		Type typeFromHandle19 = typeof(IProvideValueTarget);
		object[] array10 = new object[0 + 6];
		array10[0] = span12;
		array10[1] = formattedString3;
		array10[2] = label6;
		array10[3] = grid2;
		array10[4] = scrollView;
		array10[5] = sharerInformationView;
		object service10;
		xamlServiceProvider10.Add(typeFromHandle19, service10 = new SimpleValueTargetProvider(array10, Span.FontSizeProperty, nameScope));
		xamlServiceProvider10.Add(typeof(IReferenceProvider), service10);
		Type typeFromHandle20 = typeof(IXamlTypeResolver);
		XmlNamespaceResolver xmlNamespaceResolver10 = new XmlNamespaceResolver();
		xmlNamespaceResolver10.Add("", "http://xamarin.com/schemas/2014/forms");
		xmlNamespaceResolver10.Add("x", "http://schemas.microsoft.com/winfx/2009/xaml");
		xmlNamespaceResolver10.Add("calx", "clr-namespace:Caliburn.Micro.Xamarin.Forms;assembly=Caliburn.Micro.Platform.Xamarin.Forms");
		xmlNamespaceResolver10.Add("converter", "clr-namespace:NHL.Views.Converters");
		xmlNamespaceResolver10.Add("effect", "clr-namespace:NHL.Views.Effect");
		xmlNamespaceResolver10.Add("system", "clr-namespace:System;assembly=System.Runtime.Extensions");
		xamlServiceProvider10.Add(typeFromHandle20, new XamlTypeResolver(xmlNamespaceResolver10, typeof(SharerInformationView).GetTypeInfo().Assembly));
		xamlServiceProvider10.Add(typeof(IXmlLineInfoProvider), new XmlLineInfoProvider(new XmlLineInfo(155, 52)));
		span12.SetValue(fontSizeProperty5, ((IExtendedTypeConverter)fontSizeConverter5).ConvertFromInvariantString("Small", (IServiceProvider)xamlServiceProvider10));
		formattedString3.Spans.Add(span12);
		VisualDiagnostics.RegisterSourceInfo(span12, new Uri("Views/SharerInformationView.xaml", UriKind.RelativeOrAbsolute), 155, 26);
		label6.SetValue(Label.FormattedTextProperty, formattedString3);
		VisualDiagnostics.RegisterSourceInfo(formattedString3, new Uri("Views/SharerInformationView.xaml", UriKind.RelativeOrAbsolute), 149, 22);
		grid2.Children.Add(label6);
		VisualDiagnostics.RegisterSourceInfo(label6, new Uri("Views/SharerInformationView.xaml", UriKind.RelativeOrAbsolute), 144, 14);
		scrollView.Content = grid2;
		VisualDiagnostics.RegisterSourceInfo(grid2, new Uri("Views/SharerInformationView.xaml", UriKind.RelativeOrAbsolute), 45, 10);
		sharerInformationView.SetValue(ContentPage.ContentProperty, scrollView);
		VisualDiagnostics.RegisterSourceInfo(scrollView, new Uri("Views/SharerInformationView.xaml", UriKind.RelativeOrAbsolute), 44, 6);
		VisualDiagnostics.RegisterSourceInfo(sharerInformationView, new Uri("Views/SharerInformationView.xaml", UriKind.RelativeOrAbsolute), 3, 2);
	}

	private void __InitComponentRuntime()
	{
		this.LoadFromXaml(typeof(SharerInformationView));
	}
}
