using System;
using System.CodeDom.Compiler;
using System.Reflection;
using C1.Xamarin.Forms.Chart;
using Caliburn.Micro;
using Caliburn.Micro.Xamarin.Forms;
using NHL.Models;
using NHL.Views.Effect;
using Xamarin.Forms;
using Xamarin.Forms.Internals;
using Xamarin.Forms.Xaml;
using Xamarin.Forms.Xaml.Diagnostics;
using Xamarin.Forms.Xaml.Internals;

namespace NHL.Views;

[XamlCompilation(XamlCompilationOptions.Compile)]
[XamlFilePath("Views/StepChartView.xaml")]
public class StepChartView : ContentPage
{
	[GeneratedCode("Xamarin.Forms.Build.Tasks.XamlG", "2.0.0.0")]
	private Label Dates;

	[GeneratedCode("Xamarin.Forms.Build.Tasks.XamlG", "2.0.0.0")]
	private FlexChart chart;

	[GeneratedCode("Xamarin.Forms.Build.Tasks.XamlG", "2.0.0.0")]
	private ChartSeries stepLine;

	public StepChartView()
	{
		InitializeComponent();
	}

	public void ChartView(BindableCollection<DisplayStepChartDataModel> data, double max, int majorUnit)
	{
		chart.ItemsSource = data;
		chart.AxisX.MajorUnit = majorUnit;
		chart.AxisY.Max = max;
	}

	public BindableCollection<ChartSettingModel> ChartVisible(BindableCollection<ChartSettingModel> chartSettings)
	{
		chartSettings = new BindableCollection<ChartSettingModel>();
		string[] array = new string[1] { "歩数" };
		foreach (string setting in array)
		{
			ChartSettingModel item = new ChartSettingModel
			{
				Setting = setting,
				Active = true
			};
			chartSettings.Add(item);
		}
		return chartSettings;
	}

	[GeneratedCode("Xamarin.Forms.Build.Tasks.XamlG", "2.0.0.0")]
	private void InitializeComponent()
	{
		if (ResourceLoader.CanProvideContentFor(new ResourceLoader.ResourceLoadingQuery
		{
			AssemblyName = typeof(StepChartView).GetTypeInfo().Assembly.GetName(),
			ResourcePath = "Views/StepChartView.xaml",
			Instance = this
		}))
		{
			__InitComponentRuntime();
			return;
		}
		if (XamlLoader.XamlFileProvider != null && XamlLoader.XamlFileProvider(GetType()) != null)
		{
			__InitComponentRuntime();
			return;
		}
		RowDefinition rowDefinition = new RowDefinition();
		RowDefinition rowDefinition2 = new RowDefinition();
		RowDefinition rowDefinition3 = new RowDefinition();
		RowDefinition rowDefinition4 = new RowDefinition();
		RowDefinition rowDefinition5 = new RowDefinition();
		RowDefinition rowDefinition6 = new RowDefinition();
		RowDefinition rowDefinition7 = new RowDefinition();
		RowDefinition rowDefinition8 = new RowDefinition();
		RowDefinition rowDefinition9 = new RowDefinition();
		RowDefinition rowDefinition10 = new RowDefinition();
		ColumnDefinition item = new ColumnDefinition();
		ColumnDefinition item2 = new ColumnDefinition();
		ColumnDefinition item3 = new ColumnDefinition();
		ColumnDefinition item4 = new ColumnDefinition();
		ColumnDefinition item5 = new ColumnDefinition();
		ColumnDefinition item6 = new ColumnDefinition();
		FixedFontSizeButtonEffect fixedFontSizeButtonEffect = new FixedFontSizeButtonEffect();
		Button button = new Button();
		FixedFontSizeButtonEffect fixedFontSizeButtonEffect2 = new FixedFontSizeButtonEffect();
		Button button2 = new Button();
		FixedFontSizeButtonEffect fixedFontSizeButtonEffect3 = new FixedFontSizeButtonEffect();
		Button button3 = new Button();
		BindingExtension bindingExtension = new BindingExtension();
		Label label = new Label();
		Grid grid = new Grid();
		BindingExtension bindingExtension2 = new BindingExtension();
		FixedFontSizeButtonEffect fixedFontSizeButtonEffect4 = new FixedFontSizeButtonEffect();
		Button button4 = new Button();
		Span span = new Span();
		BindingExtension bindingExtension3 = new BindingExtension();
		Span span2 = new Span();
		Span span3 = new Span();
		FormattedString formattedString = new FormattedString();
		Label label2 = new Label();
		Grid grid2 = new Grid();
		BindingExtension bindingExtension4 = new BindingExtension();
		ChartStyle chartStyle = new ChartStyle();
		ChartAxis chartAxis = new ChartAxis();
		ChartStyle chartStyle2 = new ChartStyle();
		ChartAxis chartAxis2 = new ChartAxis();
		ChartOptions chartOptions = new ChartOptions();
		ChartStyle chartStyle3 = new ChartStyle();
		ChartSeries chartSeries = new ChartSeries();
		FlexChart flexChart = new FlexChart();
		Label label3 = new Label();
		Grid grid3 = new Grid();
		Grid grid4 = new Grid();
		Label label4 = new Label();
		Grid grid5 = new Grid();
		BindingExtension bindingExtension5 = new BindingExtension();
		Label label5 = new Label();
		Grid grid6 = new Grid();
		Label label6 = new Label();
		Grid grid7 = new Grid();
		FixedFontSizeButtonEffect fixedFontSizeButtonEffect5 = new FixedFontSizeButtonEffect();
		Button button5 = new Button();
		Grid grid8 = new Grid();
		ScrollView scrollView = new ScrollView();
		Grid grid9 = new Grid();
		StepChartView stepChartView;
		NameScope nameScope = (NameScope)(NameScope.GetNameScope(stepChartView = this) ?? new NameScope());
		NameScope.SetNameScope(stepChartView, nameScope);
		((INameScope)nameScope).RegisterName("Dates", (object)label);
		if (label.StyleId == null)
		{
			label.StyleId = "Dates";
		}
		((INameScope)nameScope).RegisterName("chart", (object)flexChart);
		if (flexChart.StyleId == null)
		{
			flexChart.StyleId = "chart";
		}
		((INameScope)nameScope).RegisterName("stepLine", (object)chartSeries);
		Dates = label;
		chart = flexChart;
		stepLine = chartSeries;
		stepChartView.SetValue(NavigationPage.HasBackButtonProperty, true);
		stepChartView.SetValue(NavigationPage.BackButtonTitleProperty, "戻る");
		stepChartView.SetValue(Page.BackgroundImageProperty, "bg.png");
		stepChartView.SetValue(Page.TitleProperty, "詳細情報");
		rowDefinition.SetValue(RowDefinition.HeightProperty, new GridLengthTypeConverter().ConvertFromInvariantString("Auto"));
		((DefinitionCollection<RowDefinition>)grid8.GetValue(Grid.RowDefinitionsProperty)).Add(rowDefinition);
		rowDefinition2.SetValue(RowDefinition.HeightProperty, new GridLengthTypeConverter().ConvertFromInvariantString("Auto"));
		((DefinitionCollection<RowDefinition>)grid8.GetValue(Grid.RowDefinitionsProperty)).Add(rowDefinition2);
		rowDefinition3.SetValue(RowDefinition.HeightProperty, new GridLengthTypeConverter().ConvertFromInvariantString("50"));
		((DefinitionCollection<RowDefinition>)grid8.GetValue(Grid.RowDefinitionsProperty)).Add(rowDefinition3);
		rowDefinition4.SetValue(RowDefinition.HeightProperty, new GridLengthTypeConverter().ConvertFromInvariantString("300"));
		((DefinitionCollection<RowDefinition>)grid8.GetValue(Grid.RowDefinitionsProperty)).Add(rowDefinition4);
		rowDefinition5.SetValue(RowDefinition.HeightProperty, new GridLengthTypeConverter().ConvertFromInvariantString("Auto"));
		((DefinitionCollection<RowDefinition>)grid8.GetValue(Grid.RowDefinitionsProperty)).Add(rowDefinition5);
		rowDefinition6.SetValue(RowDefinition.HeightProperty, new GridLengthTypeConverter().ConvertFromInvariantString("Auto"));
		((DefinitionCollection<RowDefinition>)grid8.GetValue(Grid.RowDefinitionsProperty)).Add(rowDefinition6);
		rowDefinition7.SetValue(RowDefinition.HeightProperty, new GridLengthTypeConverter().ConvertFromInvariantString("Auto"));
		((DefinitionCollection<RowDefinition>)grid8.GetValue(Grid.RowDefinitionsProperty)).Add(rowDefinition7);
		rowDefinition8.SetValue(RowDefinition.HeightProperty, new GridLengthTypeConverter().ConvertFromInvariantString("Auto"));
		((DefinitionCollection<RowDefinition>)grid8.GetValue(Grid.RowDefinitionsProperty)).Add(rowDefinition8);
		rowDefinition9.SetValue(RowDefinition.HeightProperty, new GridLengthTypeConverter().ConvertFromInvariantString("Auto"));
		((DefinitionCollection<RowDefinition>)grid8.GetValue(Grid.RowDefinitionsProperty)).Add(rowDefinition9);
		rowDefinition10.SetValue(RowDefinition.HeightProperty, new GridLengthTypeConverter().ConvertFromInvariantString("Auto"));
		((DefinitionCollection<RowDefinition>)grid8.GetValue(Grid.RowDefinitionsProperty)).Add(rowDefinition10);
		((DefinitionCollection<ColumnDefinition>)grid8.GetValue(Grid.ColumnDefinitionsProperty)).Add(item);
		((DefinitionCollection<ColumnDefinition>)grid8.GetValue(Grid.ColumnDefinitionsProperty)).Add(item2);
		((DefinitionCollection<ColumnDefinition>)grid8.GetValue(Grid.ColumnDefinitionsProperty)).Add(item3);
		((DefinitionCollection<ColumnDefinition>)grid8.GetValue(Grid.ColumnDefinitionsProperty)).Add(item4);
		((DefinitionCollection<ColumnDefinition>)grid8.GetValue(Grid.ColumnDefinitionsProperty)).Add(item5);
		((DefinitionCollection<ColumnDefinition>)grid8.GetValue(Grid.ColumnDefinitionsProperty)).Add(item6);
		button.SetValue(Message.AttachProperty, "WeekButtonTapped");
		button.SetValue(Grid.RowProperty, 0);
		button.SetValue(Grid.ColumnSpanProperty, 3);
		button.SetValue(Button.TextProperty, "週");
		button.SetValue(Button.FontAttributesProperty, new FontAttributesConverter().ConvertFromInvariantString("Bold"));
		button.SetValue(Button.TextColorProperty, Color.Blue);
		button.SetValue(VisualElement.BackgroundColorProperty, Color.Transparent);
		BindableProperty fontSizeProperty = Button.FontSizeProperty;
		FontSizeConverter fontSizeConverter = new FontSizeConverter();
		XamlServiceProvider xamlServiceProvider = new XamlServiceProvider();
		Type typeFromHandle = typeof(IProvideValueTarget);
		object[] array = new object[0 + 5];
		array[0] = button;
		array[1] = grid8;
		array[2] = scrollView;
		array[3] = grid9;
		array[4] = stepChartView;
		object service;
		xamlServiceProvider.Add(typeFromHandle, service = new SimpleValueTargetProvider(array, Button.FontSizeProperty, nameScope));
		xamlServiceProvider.Add(typeof(IReferenceProvider), service);
		Type typeFromHandle2 = typeof(IXamlTypeResolver);
		XmlNamespaceResolver xmlNamespaceResolver = new XmlNamespaceResolver();
		xmlNamespaceResolver.Add("", "http://xamarin.com/schemas/2014/forms");
		xmlNamespaceResolver.Add("x", "http://schemas.microsoft.com/winfx/2009/xaml");
		xmlNamespaceResolver.Add("calx", "clr-namespace:Caliburn.Micro.Xamarin.Forms;assembly=Caliburn.Micro.Platform.Xamarin.Forms");
		xmlNamespaceResolver.Add("effect", "clr-namespace:NHL.Views.Effect");
		xmlNamespaceResolver.Add("c1", "clr-namespace:C1.Xamarin.Forms.Chart;assembly=C1.Xamarin.Forms.Chart");
		xamlServiceProvider.Add(typeFromHandle2, new XamlTypeResolver(xmlNamespaceResolver, typeof(StepChartView).GetTypeInfo().Assembly));
		xamlServiceProvider.Add(typeof(IXmlLineInfoProvider), new XmlLineInfoProvider(new XmlLineInfo(39, 175)));
		button.SetValue(fontSizeProperty, ((IExtendedTypeConverter)fontSizeConverter).ConvertFromInvariantString("Large", (IServiceProvider)xamlServiceProvider));
		button.SetValue(Xamarin.Forms.View.VerticalOptionsProperty, LayoutOptions.CenterAndExpand);
		button.SetValue(Xamarin.Forms.View.HorizontalOptionsProperty, LayoutOptions.Center);
		fixedFontSizeButtonEffect.FixedSize = 8;
		button.Effects.Add(fixedFontSizeButtonEffect);
		VisualDiagnostics.RegisterSourceInfo(fixedFontSizeButtonEffect, new Uri("Views/StepChartView.xaml", UriKind.RelativeOrAbsolute), 42, 26);
		grid8.Children.Add(button);
		VisualDiagnostics.RegisterSourceInfo(button, new Uri("Views/StepChartView.xaml", UriKind.RelativeOrAbsolute), 39, 18);
		button2.SetValue(Message.AttachProperty, "MonthButtonTapped");
		button2.SetValue(Grid.RowProperty, 0);
		button2.SetValue(Grid.ColumnProperty, 3);
		button2.SetValue(Grid.ColumnSpanProperty, 3);
		button2.SetValue(Button.TextProperty, "月");
		button2.SetValue(Button.FontAttributesProperty, new FontAttributesConverter().ConvertFromInvariantString("Bold"));
		button2.SetValue(Button.TextColorProperty, Color.Blue);
		button2.SetValue(VisualElement.BackgroundColorProperty, Color.Transparent);
		BindableProperty fontSizeProperty2 = Button.FontSizeProperty;
		FontSizeConverter fontSizeConverter2 = new FontSizeConverter();
		XamlServiceProvider xamlServiceProvider2 = new XamlServiceProvider();
		Type typeFromHandle3 = typeof(IProvideValueTarget);
		object[] array2 = new object[0 + 5];
		array2[0] = button2;
		array2[1] = grid8;
		array2[2] = scrollView;
		array2[3] = grid9;
		array2[4] = stepChartView;
		object service2;
		xamlServiceProvider2.Add(typeFromHandle3, service2 = new SimpleValueTargetProvider(array2, Button.FontSizeProperty, nameScope));
		xamlServiceProvider2.Add(typeof(IReferenceProvider), service2);
		Type typeFromHandle4 = typeof(IXamlTypeResolver);
		XmlNamespaceResolver xmlNamespaceResolver2 = new XmlNamespaceResolver();
		xmlNamespaceResolver2.Add("", "http://xamarin.com/schemas/2014/forms");
		xmlNamespaceResolver2.Add("x", "http://schemas.microsoft.com/winfx/2009/xaml");
		xmlNamespaceResolver2.Add("calx", "clr-namespace:Caliburn.Micro.Xamarin.Forms;assembly=Caliburn.Micro.Platform.Xamarin.Forms");
		xmlNamespaceResolver2.Add("effect", "clr-namespace:NHL.Views.Effect");
		xmlNamespaceResolver2.Add("c1", "clr-namespace:C1.Xamarin.Forms.Chart;assembly=C1.Xamarin.Forms.Chart");
		xamlServiceProvider2.Add(typeFromHandle4, new XamlTypeResolver(xmlNamespaceResolver2, typeof(StepChartView).GetTypeInfo().Assembly));
		xamlServiceProvider2.Add(typeof(IXmlLineInfoProvider), new XmlLineInfoProvider(new XmlLineInfo(47, 192)));
		button2.SetValue(fontSizeProperty2, ((IExtendedTypeConverter)fontSizeConverter2).ConvertFromInvariantString("Large", (IServiceProvider)xamlServiceProvider2));
		button2.SetValue(Xamarin.Forms.View.VerticalOptionsProperty, LayoutOptions.CenterAndExpand);
		button2.SetValue(Xamarin.Forms.View.HorizontalOptionsProperty, LayoutOptions.Center);
		fixedFontSizeButtonEffect2.FixedSize = 8;
		button2.Effects.Add(fixedFontSizeButtonEffect2);
		VisualDiagnostics.RegisterSourceInfo(fixedFontSizeButtonEffect2, new Uri("Views/StepChartView.xaml", UriKind.RelativeOrAbsolute), 50, 26);
		grid8.Children.Add(button2);
		VisualDiagnostics.RegisterSourceInfo(button2, new Uri("Views/StepChartView.xaml", UriKind.RelativeOrAbsolute), 47, 18);
		button3.SetValue(Message.AttachProperty, "SelectPrevTermTapped");
		button3.SetValue(Grid.RowProperty, 1);
		button3.SetValue(Button.TextProperty, "＜");
		button3.SetValue(Button.FontAttributesProperty, new FontAttributesConverter().ConvertFromInvariantString("Bold"));
		button3.SetValue(Button.TextColorProperty, Color.Blue);
		button3.SetValue(VisualElement.BackgroundColorProperty, Color.Transparent);
		BindableProperty fontSizeProperty3 = Button.FontSizeProperty;
		FontSizeConverter fontSizeConverter3 = new FontSizeConverter();
		XamlServiceProvider xamlServiceProvider3 = new XamlServiceProvider();
		Type typeFromHandle5 = typeof(IProvideValueTarget);
		object[] array3 = new object[0 + 5];
		array3[0] = button3;
		array3[1] = grid8;
		array3[2] = scrollView;
		array3[3] = grid9;
		array3[4] = stepChartView;
		object service3;
		xamlServiceProvider3.Add(typeFromHandle5, service3 = new SimpleValueTargetProvider(array3, Button.FontSizeProperty, nameScope));
		xamlServiceProvider3.Add(typeof(IReferenceProvider), service3);
		Type typeFromHandle6 = typeof(IXamlTypeResolver);
		XmlNamespaceResolver xmlNamespaceResolver3 = new XmlNamespaceResolver();
		xmlNamespaceResolver3.Add("", "http://xamarin.com/schemas/2014/forms");
		xmlNamespaceResolver3.Add("x", "http://schemas.microsoft.com/winfx/2009/xaml");
		xmlNamespaceResolver3.Add("calx", "clr-namespace:Caliburn.Micro.Xamarin.Forms;assembly=Caliburn.Micro.Platform.Xamarin.Forms");
		xmlNamespaceResolver3.Add("effect", "clr-namespace:NHL.Views.Effect");
		xmlNamespaceResolver3.Add("c1", "clr-namespace:C1.Xamarin.Forms.Chart;assembly=C1.Xamarin.Forms.Chart");
		xamlServiceProvider3.Add(typeFromHandle6, new XamlTypeResolver(xmlNamespaceResolver3, typeof(StepChartView).GetTypeInfo().Assembly));
		xamlServiceProvider3.Add(typeof(IXmlLineInfoProvider), new XmlLineInfoProvider(new XmlLineInfo(57, 159)));
		button3.SetValue(fontSizeProperty3, ((IExtendedTypeConverter)fontSizeConverter3).ConvertFromInvariantString("Large", (IServiceProvider)xamlServiceProvider3));
		button3.SetValue(Xamarin.Forms.View.VerticalOptionsProperty, LayoutOptions.CenterAndExpand);
		button3.SetValue(Xamarin.Forms.View.HorizontalOptionsProperty, LayoutOptions.Center);
		fixedFontSizeButtonEffect3.FixedSize = 8;
		button3.Effects.Add(fixedFontSizeButtonEffect3);
		VisualDiagnostics.RegisterSourceInfo(fixedFontSizeButtonEffect3, new Uri("Views/StepChartView.xaml", UriKind.RelativeOrAbsolute), 60, 26);
		grid8.Children.Add(button3);
		VisualDiagnostics.RegisterSourceInfo(button3, new Uri("Views/StepChartView.xaml", UriKind.RelativeOrAbsolute), 57, 18);
		grid.SetValue(Grid.RowProperty, 1);
		grid.SetValue(Grid.ColumnProperty, 1);
		grid.SetValue(Grid.ColumnSpanProperty, 4);
		bindingExtension.Path = "DisplaySelectedDates";
		BindingBase binding = ((IMarkupExtension<BindingBase>)bindingExtension).ProvideValue((IServiceProvider)null);
		label.SetBinding(Label.TextProperty, binding);
		label.SetValue(Label.FontAttributesProperty, new FontAttributesConverter().ConvertFromInvariantString("Bold"));
		label.SetValue(Label.TextColorProperty, Color.Blue);
		BindableProperty fontSizeProperty4 = Label.FontSizeProperty;
		FontSizeConverter fontSizeConverter4 = new FontSizeConverter();
		XamlServiceProvider xamlServiceProvider4 = new XamlServiceProvider();
		Type typeFromHandle7 = typeof(IProvideValueTarget);
		object[] array4 = new object[0 + 6];
		array4[0] = label;
		array4[1] = grid;
		array4[2] = grid8;
		array4[3] = scrollView;
		array4[4] = grid9;
		array4[5] = stepChartView;
		object service4;
		xamlServiceProvider4.Add(typeFromHandle7, service4 = new SimpleValueTargetProvider(array4, Label.FontSizeProperty, nameScope));
		xamlServiceProvider4.Add(typeof(IReferenceProvider), service4);
		Type typeFromHandle8 = typeof(IXamlTypeResolver);
		XmlNamespaceResolver xmlNamespaceResolver4 = new XmlNamespaceResolver();
		xmlNamespaceResolver4.Add("", "http://xamarin.com/schemas/2014/forms");
		xmlNamespaceResolver4.Add("x", "http://schemas.microsoft.com/winfx/2009/xaml");
		xmlNamespaceResolver4.Add("calx", "clr-namespace:Caliburn.Micro.Xamarin.Forms;assembly=Caliburn.Micro.Platform.Xamarin.Forms");
		xmlNamespaceResolver4.Add("effect", "clr-namespace:NHL.Views.Effect");
		xmlNamespaceResolver4.Add("c1", "clr-namespace:C1.Xamarin.Forms.Chart;assembly=C1.Xamarin.Forms.Chart");
		xamlServiceProvider4.Add(typeFromHandle8, new XamlTypeResolver(xmlNamespaceResolver4, typeof(StepChartView).GetTypeInfo().Assembly));
		xamlServiceProvider4.Add(typeof(IXmlLineInfoProvider), new XmlLineInfoProvider(new XmlLineInfo(66, 120)));
		label.SetValue(fontSizeProperty4, ((IExtendedTypeConverter)fontSizeConverter4).ConvertFromInvariantString("Large", (IServiceProvider)xamlServiceProvider4));
		label.SetValue(Xamarin.Forms.View.VerticalOptionsProperty, LayoutOptions.CenterAndExpand);
		label.SetValue(Xamarin.Forms.View.HorizontalOptionsProperty, LayoutOptions.CenterAndExpand);
		grid.Children.Add(label);
		VisualDiagnostics.RegisterSourceInfo(label, new Uri("Views/StepChartView.xaml", UriKind.RelativeOrAbsolute), 66, 22);
		grid8.Children.Add(grid);
		VisualDiagnostics.RegisterSourceInfo(grid, new Uri("Views/StepChartView.xaml", UriKind.RelativeOrAbsolute), 65, 18);
		button4.SetValue(Message.AttachProperty, "SelectNextTermTapped");
		button4.SetValue(Grid.RowProperty, 1);
		button4.SetValue(Grid.ColumnProperty, 5);
		button4.SetValue(Button.TextProperty, "＞");
		button4.SetValue(Button.FontAttributesProperty, new FontAttributesConverter().ConvertFromInvariantString("Bold"));
		button4.SetValue(Button.TextColorProperty, Color.Blue);
		button4.SetValue(VisualElement.BackgroundColorProperty, Color.Transparent);
		BindableProperty fontSizeProperty5 = Button.FontSizeProperty;
		FontSizeConverter fontSizeConverter5 = new FontSizeConverter();
		XamlServiceProvider xamlServiceProvider5 = new XamlServiceProvider();
		Type typeFromHandle9 = typeof(IProvideValueTarget);
		object[] array5 = new object[0 + 5];
		array5[0] = button4;
		array5[1] = grid8;
		array5[2] = scrollView;
		array5[3] = grid9;
		array5[4] = stepChartView;
		object service5;
		xamlServiceProvider5.Add(typeFromHandle9, service5 = new SimpleValueTargetProvider(array5, Button.FontSizeProperty, nameScope));
		xamlServiceProvider5.Add(typeof(IReferenceProvider), service5);
		Type typeFromHandle10 = typeof(IXamlTypeResolver);
		XmlNamespaceResolver xmlNamespaceResolver5 = new XmlNamespaceResolver();
		xmlNamespaceResolver5.Add("", "http://xamarin.com/schemas/2014/forms");
		xmlNamespaceResolver5.Add("x", "http://schemas.microsoft.com/winfx/2009/xaml");
		xmlNamespaceResolver5.Add("calx", "clr-namespace:Caliburn.Micro.Xamarin.Forms;assembly=Caliburn.Micro.Platform.Xamarin.Forms");
		xmlNamespaceResolver5.Add("effect", "clr-namespace:NHL.Views.Effect");
		xmlNamespaceResolver5.Add("c1", "clr-namespace:C1.Xamarin.Forms.Chart;assembly=C1.Xamarin.Forms.Chart");
		xamlServiceProvider5.Add(typeFromHandle10, new XamlTypeResolver(xmlNamespaceResolver5, typeof(StepChartView).GetTypeInfo().Assembly));
		xamlServiceProvider5.Add(typeof(IXmlLineInfoProvider), new XmlLineInfoProvider(new XmlLineInfo(71, 175)));
		button4.SetValue(fontSizeProperty5, ((IExtendedTypeConverter)fontSizeConverter5).ConvertFromInvariantString("Large", (IServiceProvider)xamlServiceProvider5));
		button4.SetValue(Xamarin.Forms.View.VerticalOptionsProperty, LayoutOptions.CenterAndExpand);
		button4.SetValue(Xamarin.Forms.View.HorizontalOptionsProperty, LayoutOptions.Center);
		bindingExtension2.Path = "IsVisibleSelectNext";
		BindingBase binding2 = ((IMarkupExtension<BindingBase>)bindingExtension2).ProvideValue((IServiceProvider)null);
		button4.SetBinding(VisualElement.IsVisibleProperty, binding2);
		fixedFontSizeButtonEffect4.FixedSize = 8;
		button4.Effects.Add(fixedFontSizeButtonEffect4);
		VisualDiagnostics.RegisterSourceInfo(fixedFontSizeButtonEffect4, new Uri("Views/StepChartView.xaml", UriKind.RelativeOrAbsolute), 74, 26);
		grid8.Children.Add(button4);
		VisualDiagnostics.RegisterSourceInfo(button4, new Uri("Views/StepChartView.xaml", UriKind.RelativeOrAbsolute), 71, 18);
		grid2.SetValue(Grid.RowProperty, 2);
		grid2.SetValue(Grid.ColumnProperty, 0);
		grid2.SetValue(Grid.ColumnSpanProperty, 6);
		grid2.SetValue(Grid.ColumnSpacingProperty, 0.0);
		label2.SetValue(Label.TextColorProperty, Color.Blue);
		label2.SetValue(Xamarin.Forms.View.VerticalOptionsProperty, LayoutOptions.EndAndExpand);
		label2.SetValue(Xamarin.Forms.View.HorizontalOptionsProperty, LayoutOptions.CenterAndExpand);
		label2.SetValue(Label.FontAttributesProperty, new FontAttributesConverter().ConvertFromInvariantString("Bold"));
		span.SetValue(Span.TextProperty, "合計");
		BindableProperty fontSizeProperty6 = Span.FontSizeProperty;
		FontSizeConverter fontSizeConverter6 = new FontSizeConverter();
		XamlServiceProvider xamlServiceProvider6 = new XamlServiceProvider();
		Type typeFromHandle11 = typeof(IProvideValueTarget);
		object[] array6 = new object[0 + 8];
		array6[0] = span;
		array6[1] = formattedString;
		array6[2] = label2;
		array6[3] = grid2;
		array6[4] = grid8;
		array6[5] = scrollView;
		array6[6] = grid9;
		array6[7] = stepChartView;
		object service6;
		xamlServiceProvider6.Add(typeFromHandle11, service6 = new SimpleValueTargetProvider(array6, Span.FontSizeProperty, nameScope));
		xamlServiceProvider6.Add(typeof(IReferenceProvider), service6);
		Type typeFromHandle12 = typeof(IXamlTypeResolver);
		XmlNamespaceResolver xmlNamespaceResolver6 = new XmlNamespaceResolver();
		xmlNamespaceResolver6.Add("", "http://xamarin.com/schemas/2014/forms");
		xmlNamespaceResolver6.Add("x", "http://schemas.microsoft.com/winfx/2009/xaml");
		xmlNamespaceResolver6.Add("calx", "clr-namespace:Caliburn.Micro.Xamarin.Forms;assembly=Caliburn.Micro.Platform.Xamarin.Forms");
		xmlNamespaceResolver6.Add("effect", "clr-namespace:NHL.Views.Effect");
		xmlNamespaceResolver6.Add("c1", "clr-namespace:C1.Xamarin.Forms.Chart;assembly=C1.Xamarin.Forms.Chart");
		xamlServiceProvider6.Add(typeFromHandle12, new XamlTypeResolver(xmlNamespaceResolver6, typeof(StepChartView).GetTypeInfo().Assembly));
		xamlServiceProvider6.Add(typeof(IXmlLineInfoProvider), new XmlLineInfoProvider(new XmlLineInfo(85, 49)));
		span.SetValue(fontSizeProperty6, ((IExtendedTypeConverter)fontSizeConverter6).ConvertFromInvariantString("Large", (IServiceProvider)xamlServiceProvider6));
		formattedString.Spans.Add(span);
		VisualDiagnostics.RegisterSourceInfo(span, new Uri("Views/StepChartView.xaml", UriKind.RelativeOrAbsolute), 85, 34);
		bindingExtension3.Path = "StepTotal";
		BindingBase binding3 = ((IMarkupExtension<BindingBase>)bindingExtension3).ProvideValue((IServiceProvider)null);
		span2.SetBinding(Span.TextProperty, binding3);
		BindableProperty fontSizeProperty7 = Span.FontSizeProperty;
		FontSizeConverter fontSizeConverter7 = new FontSizeConverter();
		XamlServiceProvider xamlServiceProvider7 = new XamlServiceProvider();
		Type typeFromHandle13 = typeof(IProvideValueTarget);
		object[] array7 = new object[0 + 8];
		array7[0] = span2;
		array7[1] = formattedString;
		array7[2] = label2;
		array7[3] = grid2;
		array7[4] = grid8;
		array7[5] = scrollView;
		array7[6] = grid9;
		array7[7] = stepChartView;
		object service7;
		xamlServiceProvider7.Add(typeFromHandle13, service7 = new SimpleValueTargetProvider(array7, Span.FontSizeProperty, nameScope));
		xamlServiceProvider7.Add(typeof(IReferenceProvider), service7);
		Type typeFromHandle14 = typeof(IXamlTypeResolver);
		XmlNamespaceResolver xmlNamespaceResolver7 = new XmlNamespaceResolver();
		xmlNamespaceResolver7.Add("", "http://xamarin.com/schemas/2014/forms");
		xmlNamespaceResolver7.Add("x", "http://schemas.microsoft.com/winfx/2009/xaml");
		xmlNamespaceResolver7.Add("calx", "clr-namespace:Caliburn.Micro.Xamarin.Forms;assembly=Caliburn.Micro.Platform.Xamarin.Forms");
		xmlNamespaceResolver7.Add("effect", "clr-namespace:NHL.Views.Effect");
		xmlNamespaceResolver7.Add("c1", "clr-namespace:C1.Xamarin.Forms.Chart;assembly=C1.Xamarin.Forms.Chart");
		xamlServiceProvider7.Add(typeFromHandle14, new XamlTypeResolver(xmlNamespaceResolver7, typeof(StepChartView).GetTypeInfo().Assembly));
		xamlServiceProvider7.Add(typeof(IXmlLineInfoProvider), new XmlLineInfoProvider(new XmlLineInfo(86, 66)));
		span2.SetValue(fontSizeProperty7, ((IExtendedTypeConverter)fontSizeConverter7).ConvertFromInvariantString("Medium", (IServiceProvider)xamlServiceProvider7));
		formattedString.Spans.Add(span2);
		VisualDiagnostics.RegisterSourceInfo(span2, new Uri("Views/StepChartView.xaml", UriKind.RelativeOrAbsolute), 86, 34);
		span3.SetValue(Span.TextProperty, "歩");
		BindableProperty fontSizeProperty8 = Span.FontSizeProperty;
		FontSizeConverter fontSizeConverter8 = new FontSizeConverter();
		XamlServiceProvider xamlServiceProvider8 = new XamlServiceProvider();
		Type typeFromHandle15 = typeof(IProvideValueTarget);
		object[] array8 = new object[0 + 8];
		array8[0] = span3;
		array8[1] = formattedString;
		array8[2] = label2;
		array8[3] = grid2;
		array8[4] = grid8;
		array8[5] = scrollView;
		array8[6] = grid9;
		array8[7] = stepChartView;
		object service8;
		xamlServiceProvider8.Add(typeFromHandle15, service8 = new SimpleValueTargetProvider(array8, Span.FontSizeProperty, nameScope));
		xamlServiceProvider8.Add(typeof(IReferenceProvider), service8);
		Type typeFromHandle16 = typeof(IXamlTypeResolver);
		XmlNamespaceResolver xmlNamespaceResolver8 = new XmlNamespaceResolver();
		xmlNamespaceResolver8.Add("", "http://xamarin.com/schemas/2014/forms");
		xmlNamespaceResolver8.Add("x", "http://schemas.microsoft.com/winfx/2009/xaml");
		xmlNamespaceResolver8.Add("calx", "clr-namespace:Caliburn.Micro.Xamarin.Forms;assembly=Caliburn.Micro.Platform.Xamarin.Forms");
		xmlNamespaceResolver8.Add("effect", "clr-namespace:NHL.Views.Effect");
		xmlNamespaceResolver8.Add("c1", "clr-namespace:C1.Xamarin.Forms.Chart;assembly=C1.Xamarin.Forms.Chart");
		xamlServiceProvider8.Add(typeFromHandle16, new XamlTypeResolver(xmlNamespaceResolver8, typeof(StepChartView).GetTypeInfo().Assembly));
		xamlServiceProvider8.Add(typeof(IXmlLineInfoProvider), new XmlLineInfoProvider(new XmlLineInfo(87, 48)));
		span3.SetValue(fontSizeProperty8, ((IExtendedTypeConverter)fontSizeConverter8).ConvertFromInvariantString("Large", (IServiceProvider)xamlServiceProvider8));
		formattedString.Spans.Add(span3);
		VisualDiagnostics.RegisterSourceInfo(span3, new Uri("Views/StepChartView.xaml", UriKind.RelativeOrAbsolute), 87, 34);
		label2.SetValue(Label.FormattedTextProperty, formattedString);
		VisualDiagnostics.RegisterSourceInfo(formattedString, new Uri("Views/StepChartView.xaml", UriKind.RelativeOrAbsolute), 84, 30);
		grid2.Children.Add(label2);
		VisualDiagnostics.RegisterSourceInfo(label2, new Uri("Views/StepChartView.xaml", UriKind.RelativeOrAbsolute), 81, 22);
		grid8.Children.Add(grid2);
		VisualDiagnostics.RegisterSourceInfo(grid2, new Uri("Views/StepChartView.xaml", UriKind.RelativeOrAbsolute), 80, 18);
		flexChart.SetValue(Grid.RowProperty, 3);
		flexChart.SetValue(Grid.ColumnProperty, 0);
		flexChart.SetValue(Grid.ColumnSpanProperty, 6);
		flexChart.SetValue(ChartBase.LegendPositionProperty, ChartPositionType.Bottom);
		flexChart.SetValue(VisualElement.BackgroundColorProperty, Color.White);
		flexChart.SetValue(Xamarin.Forms.View.MarginProperty, new Thickness(3.0, 3.0, 3.0, 3.0));
		BindingBase binding4 = ((IMarkupExtension<BindingBase>)bindingExtension4).ProvideValue((IServiceProvider)null);
		flexChart.SetBinding(ChartBase.BindingProperty, binding4);
		flexChart.SetValue(FlexChart.BindingXProperty, "Date");
		flexChart.SetValue(Xamarin.Forms.View.HorizontalOptionsProperty, LayoutOptions.FillAndExpand);
		flexChart.SetValue(Xamarin.Forms.View.VerticalOptionsProperty, LayoutOptions.FillAndExpand);
		chartAxis.SetValue(ChartAxis.MinProperty, 0.0);
		chartAxis.SetValue(ChartAxis.AxisLineProperty, true);
		chartAxis.SetValue(ChartAxis.MajorTickMarksProperty, ChartTickMarkType.Outside);
		chartAxis.SetValue(ChartAxis.MajorUnitProperty, 2000.0);
		chartAxis.SetValue(ChartAxis.MajorGridProperty, true);
		chartAxis.SetValue(ChartAxis.TitleProperty, "測定値");
		chartAxis.SetValue(ChartAxis.FormatProperty, "#,0");
		chartStyle.SetValue(ChartStyle.FontSizeProperty, 13.0);
		chartAxis.SetValue(ChartAxis.StyleProperty, chartStyle);
		VisualDiagnostics.RegisterSourceInfo(chartStyle, new Uri("Views/StepChartView.xaml", UriKind.RelativeOrAbsolute), 107, 34);
		flexChart.AxisY = chartAxis;
		VisualDiagnostics.RegisterSourceInfo(chartAxis, new Uri("Views/StepChartView.xaml", UriKind.RelativeOrAbsolute), 105, 26);
		chartAxis2.SetValue(ChartAxis.AxisLineProperty, true);
		chartAxis2.SetValue(ChartAxis.TitleProperty, "測定日");
		chartAxis2.SetValue(ChartAxis.MajorGridProperty, true);
		chartStyle2.SetValue(ChartStyle.FontSizeProperty, 13.0);
		chartAxis2.SetValue(ChartAxis.StyleProperty, chartStyle2);
		VisualDiagnostics.RegisterSourceInfo(chartStyle2, new Uri("Views/StepChartView.xaml", UriKind.RelativeOrAbsolute), 114, 34);
		flexChart.AxisX = chartAxis2;
		VisualDiagnostics.RegisterSourceInfo(chartAxis2, new Uri("Views/StepChartView.xaml", UriKind.RelativeOrAbsolute), 112, 26);
		chartOptions.SetValue(ChartOptions.InterpolateNullsProperty, true);
		flexChart.SetValue(FlexChart.OptionsProperty, chartOptions);
		VisualDiagnostics.RegisterSourceInfo(chartOptions, new Uri("Views/StepChartView.xaml", UriKind.RelativeOrAbsolute), 119, 26);
		chartSeries.SetValue(ChartSeries.SeriesNameProperty, "歩数");
		chartSeries.SetValue(ChartSeries.BindingProperty, "Step");
		chartSeries.SetValue(ChartSeries.ChartTypeProperty, new ChartType?(ChartType.Column));
		chartStyle3.SetValue(ChartStyle.StrokeProperty, new Color(0.08235294371843338, 0.3960784375667572, 0.7529411911964417, 1.0));
		chartStyle3.SetValue(ChartStyle.FillProperty, new Color(0.08235294371843338, 0.3960784375667572, 0.7529411911964417, 1.0));
		chartSeries.SetValue(ChartSeries.StyleProperty, chartStyle3);
		VisualDiagnostics.RegisterSourceInfo(chartStyle3, new Uri("Views/StepChartView.xaml", UriKind.RelativeOrAbsolute), 125, 34);
		flexChart.Series.Add(chartSeries);
		VisualDiagnostics.RegisterSourceInfo(chartSeries, new Uri("Views/StepChartView.xaml", UriKind.RelativeOrAbsolute), 123, 26);
		grid8.Children.Add(flexChart);
		VisualDiagnostics.RegisterSourceInfo(flexChart, new Uri("Views/StepChartView.xaml", UriKind.RelativeOrAbsolute), 94, 18);
		grid3.SetValue(Grid.RowProperty, 4);
		grid3.SetValue(Grid.ColumnProperty, 0);
		grid3.SetValue(Grid.ColumnSpanProperty, 6);
		grid3.SetValue(Grid.RowSpacingProperty, 0.0);
		grid3.SetValue(VisualElement.BackgroundColorProperty, Color.Transparent);
		grid3.SetValue(Xamarin.Forms.View.MarginProperty, new Thickness(3.0, 3.0, 3.0, 3.0));
		label3.SetValue(Label.TextProperty, " 平均値");
		label3.SetValue(Label.TextColorProperty, Color.Blue);
		label3.SetValue(Xamarin.Forms.View.VerticalOptionsProperty, LayoutOptions.End);
		label3.SetValue(Xamarin.Forms.View.HorizontalOptionsProperty, LayoutOptions.CenterAndExpand);
		BindableProperty fontSizeProperty9 = Label.FontSizeProperty;
		FontSizeConverter fontSizeConverter9 = new FontSizeConverter();
		XamlServiceProvider xamlServiceProvider9 = new XamlServiceProvider();
		Type typeFromHandle17 = typeof(IProvideValueTarget);
		object[] array9 = new object[0 + 6];
		array9[0] = label3;
		array9[1] = grid3;
		array9[2] = grid8;
		array9[3] = scrollView;
		array9[4] = grid9;
		array9[5] = stepChartView;
		object service9;
		xamlServiceProvider9.Add(typeFromHandle17, service9 = new SimpleValueTargetProvider(array9, Label.FontSizeProperty, nameScope));
		xamlServiceProvider9.Add(typeof(IReferenceProvider), service9);
		Type typeFromHandle18 = typeof(IXamlTypeResolver);
		XmlNamespaceResolver xmlNamespaceResolver9 = new XmlNamespaceResolver();
		xmlNamespaceResolver9.Add("", "http://xamarin.com/schemas/2014/forms");
		xmlNamespaceResolver9.Add("x", "http://schemas.microsoft.com/winfx/2009/xaml");
		xmlNamespaceResolver9.Add("calx", "clr-namespace:Caliburn.Micro.Xamarin.Forms;assembly=Caliburn.Micro.Platform.Xamarin.Forms");
		xmlNamespaceResolver9.Add("effect", "clr-namespace:NHL.Views.Effect");
		xmlNamespaceResolver9.Add("c1", "clr-namespace:C1.Xamarin.Forms.Chart;assembly=C1.Xamarin.Forms.Chart");
		xamlServiceProvider9.Add(typeFromHandle18, new XamlTypeResolver(xmlNamespaceResolver9, typeof(StepChartView).GetTypeInfo().Assembly));
		xamlServiceProvider9.Add(typeof(IXmlLineInfoProvider), new XmlLineInfoProvider(new XmlLineInfo(141, 115)));
		label3.SetValue(fontSizeProperty9, ((IExtendedTypeConverter)fontSizeConverter9).ConvertFromInvariantString("Large", (IServiceProvider)xamlServiceProvider9));
		label3.SetValue(Label.FontAttributesProperty, new FontAttributesConverter().ConvertFromInvariantString("Bold"));
		label3.SetValue(VisualElement.BackgroundColorProperty, Color.Transparent);
		grid3.Children.Add(label3);
		VisualDiagnostics.RegisterSourceInfo(label3, new Uri("Views/StepChartView.xaml", UriKind.RelativeOrAbsolute), 141, 22);
		grid8.Children.Add(grid3);
		VisualDiagnostics.RegisterSourceInfo(grid3, new Uri("Views/StepChartView.xaml", UriKind.RelativeOrAbsolute), 140, 18);
		grid4.SetValue(Grid.RowProperty, 5);
		grid4.SetValue(Grid.ColumnProperty, 0);
		grid4.SetValue(Grid.ColumnSpanProperty, 6);
		grid4.SetValue(VisualElement.BackgroundColorProperty, Color.White);
		grid4.SetValue(Xamarin.Forms.View.MarginProperty, new Thickness(3.0, 3.0, 3.0, 3.0));
		grid8.Children.Add(grid4);
		VisualDiagnostics.RegisterSourceInfo(grid4, new Uri("Views/StepChartView.xaml", UriKind.RelativeOrAbsolute), 143, 18);
		grid5.SetValue(Grid.RowProperty, 5);
		grid5.SetValue(Grid.ColumnProperty, 0);
		grid5.SetValue(Grid.ColumnSpanProperty, 3);
		grid5.SetValue(VisualElement.BackgroundColorProperty, Color.Transparent);
		grid5.SetValue(Xamarin.Forms.View.MarginProperty, new Thickness(15.0, 0.0, 0.0, 0.0));
		label4.SetValue(Label.TextProperty, "歩数");
		label4.SetValue(Label.TextColorProperty, Color.Blue);
		label4.SetValue(Xamarin.Forms.View.VerticalOptionsProperty, LayoutOptions.Center);
		label4.SetValue(Xamarin.Forms.View.HorizontalOptionsProperty, LayoutOptions.StartAndExpand);
		BindableProperty fontSizeProperty10 = Label.FontSizeProperty;
		FontSizeConverter fontSizeConverter10 = new FontSizeConverter();
		XamlServiceProvider xamlServiceProvider10 = new XamlServiceProvider();
		Type typeFromHandle19 = typeof(IProvideValueTarget);
		object[] array10 = new object[0 + 6];
		array10[0] = label4;
		array10[1] = grid5;
		array10[2] = grid8;
		array10[3] = scrollView;
		array10[4] = grid9;
		array10[5] = stepChartView;
		object service10;
		xamlServiceProvider10.Add(typeFromHandle19, service10 = new SimpleValueTargetProvider(array10, Label.FontSizeProperty, nameScope));
		xamlServiceProvider10.Add(typeof(IReferenceProvider), service10);
		Type typeFromHandle20 = typeof(IXamlTypeResolver);
		XmlNamespaceResolver xmlNamespaceResolver10 = new XmlNamespaceResolver();
		xmlNamespaceResolver10.Add("", "http://xamarin.com/schemas/2014/forms");
		xmlNamespaceResolver10.Add("x", "http://schemas.microsoft.com/winfx/2009/xaml");
		xmlNamespaceResolver10.Add("calx", "clr-namespace:Caliburn.Micro.Xamarin.Forms;assembly=Caliburn.Micro.Platform.Xamarin.Forms");
		xmlNamespaceResolver10.Add("effect", "clr-namespace:NHL.Views.Effect");
		xmlNamespaceResolver10.Add("c1", "clr-namespace:C1.Xamarin.Forms.Chart;assembly=C1.Xamarin.Forms.Chart");
		xamlServiceProvider10.Add(typeFromHandle20, new XamlTypeResolver(xmlNamespaceResolver10, typeof(StepChartView).GetTypeInfo().Assembly));
		xamlServiceProvider10.Add(typeof(IXmlLineInfoProvider), new XmlLineInfoProvider(new XmlLineInfo(147, 115)));
		label4.SetValue(fontSizeProperty10, ((IExtendedTypeConverter)fontSizeConverter10).ConvertFromInvariantString("Large", (IServiceProvider)xamlServiceProvider10));
		grid5.Children.Add(label4);
		VisualDiagnostics.RegisterSourceInfo(label4, new Uri("Views/StepChartView.xaml", UriKind.RelativeOrAbsolute), 147, 22);
		grid8.Children.Add(grid5);
		VisualDiagnostics.RegisterSourceInfo(grid5, new Uri("Views/StepChartView.xaml", UriKind.RelativeOrAbsolute), 146, 18);
		grid6.SetValue(Grid.RowProperty, 5);
		grid6.SetValue(Grid.ColumnProperty, 3);
		grid6.SetValue(Grid.ColumnSpanProperty, 2);
		grid6.SetValue(Grid.ColumnSpacingProperty, 0.0);
		grid6.SetValue(VisualElement.BackgroundColorProperty, Color.Transparent);
		bindingExtension5.Path = "StepAverage";
		BindingBase binding5 = ((IMarkupExtension<BindingBase>)bindingExtension5).ProvideValue((IServiceProvider)null);
		label5.SetBinding(Label.TextProperty, binding5);
		label5.SetValue(Label.TextColorProperty, Color.Blue);
		label5.SetValue(Xamarin.Forms.View.VerticalOptionsProperty, LayoutOptions.EndAndExpand);
		label5.SetValue(Xamarin.Forms.View.HorizontalOptionsProperty, LayoutOptions.End);
		BindableProperty fontSizeProperty11 = Label.FontSizeProperty;
		FontSizeConverter fontSizeConverter11 = new FontSizeConverter();
		XamlServiceProvider xamlServiceProvider11 = new XamlServiceProvider();
		Type typeFromHandle21 = typeof(IProvideValueTarget);
		object[] array11 = new object[0 + 6];
		array11[0] = label5;
		array11[1] = grid6;
		array11[2] = grid8;
		array11[3] = scrollView;
		array11[4] = grid9;
		array11[5] = stepChartView;
		object service11;
		xamlServiceProvider11.Add(typeFromHandle21, service11 = new SimpleValueTargetProvider(array11, Label.FontSizeProperty, nameScope));
		xamlServiceProvider11.Add(typeof(IReferenceProvider), service11);
		Type typeFromHandle22 = typeof(IXamlTypeResolver);
		XmlNamespaceResolver xmlNamespaceResolver11 = new XmlNamespaceResolver();
		xmlNamespaceResolver11.Add("", "http://xamarin.com/schemas/2014/forms");
		xmlNamespaceResolver11.Add("x", "http://schemas.microsoft.com/winfx/2009/xaml");
		xmlNamespaceResolver11.Add("calx", "clr-namespace:Caliburn.Micro.Xamarin.Forms;assembly=Caliburn.Micro.Platform.Xamarin.Forms");
		xmlNamespaceResolver11.Add("effect", "clr-namespace:NHL.Views.Effect");
		xmlNamespaceResolver11.Add("c1", "clr-namespace:C1.Xamarin.Forms.Chart;assembly=C1.Xamarin.Forms.Chart");
		xamlServiceProvider11.Add(typeFromHandle22, new XamlTypeResolver(xmlNamespaceResolver11, typeof(StepChartView).GetTypeInfo().Assembly));
		xamlServiceProvider11.Add(typeof(IXmlLineInfoProvider), new XmlLineInfoProvider(new XmlLineInfo(150, 129)));
		label5.SetValue(fontSizeProperty11, ((IExtendedTypeConverter)fontSizeConverter11).ConvertFromInvariantString("Large", (IServiceProvider)xamlServiceProvider11));
		label5.SetValue(Label.FontAttributesProperty, new FontAttributesConverter().ConvertFromInvariantString("Bold"));
		grid6.Children.Add(label5);
		VisualDiagnostics.RegisterSourceInfo(label5, new Uri("Views/StepChartView.xaml", UriKind.RelativeOrAbsolute), 150, 22);
		grid8.Children.Add(grid6);
		VisualDiagnostics.RegisterSourceInfo(grid6, new Uri("Views/StepChartView.xaml", UriKind.RelativeOrAbsolute), 149, 18);
		grid7.SetValue(Grid.RowProperty, 5);
		grid7.SetValue(Grid.ColumnProperty, 5);
		grid7.SetValue(Grid.ColumnSpacingProperty, 0.0);
		grid7.SetValue(VisualElement.BackgroundColorProperty, Color.Transparent);
		grid7.SetValue(Xamarin.Forms.View.MarginProperty, new Thickness(0.0, 0.0, 5.0, 3.0));
		label6.SetValue(Label.TextProperty, "歩");
		label6.SetValue(Label.TextColorProperty, Color.Black);
		label6.SetValue(Xamarin.Forms.View.VerticalOptionsProperty, LayoutOptions.EndAndExpand);
		label6.SetValue(Xamarin.Forms.View.HorizontalOptionsProperty, LayoutOptions.Start);
		BindableProperty fontSizeProperty12 = Label.FontSizeProperty;
		FontSizeConverter fontSizeConverter12 = new FontSizeConverter();
		XamlServiceProvider xamlServiceProvider12 = new XamlServiceProvider();
		Type typeFromHandle23 = typeof(IProvideValueTarget);
		object[] array12 = new object[0 + 6];
		array12[0] = label6;
		array12[1] = grid7;
		array12[2] = grid8;
		array12[3] = scrollView;
		array12[4] = grid9;
		array12[5] = stepChartView;
		object service12;
		xamlServiceProvider12.Add(typeFromHandle23, service12 = new SimpleValueTargetProvider(array12, Label.FontSizeProperty, nameScope));
		xamlServiceProvider12.Add(typeof(IReferenceProvider), service12);
		Type typeFromHandle24 = typeof(IXamlTypeResolver);
		XmlNamespaceResolver xmlNamespaceResolver12 = new XmlNamespaceResolver();
		xmlNamespaceResolver12.Add("", "http://xamarin.com/schemas/2014/forms");
		xmlNamespaceResolver12.Add("x", "http://schemas.microsoft.com/winfx/2009/xaml");
		xmlNamespaceResolver12.Add("calx", "clr-namespace:Caliburn.Micro.Xamarin.Forms;assembly=Caliburn.Micro.Platform.Xamarin.Forms");
		xmlNamespaceResolver12.Add("effect", "clr-namespace:NHL.Views.Effect");
		xmlNamespaceResolver12.Add("c1", "clr-namespace:C1.Xamarin.Forms.Chart;assembly=C1.Xamarin.Forms.Chart");
		xamlServiceProvider12.Add(typeFromHandle24, new XamlTypeResolver(xmlNamespaceResolver12, typeof(StepChartView).GetTypeInfo().Assembly));
		xamlServiceProvider12.Add(typeof(IXmlLineInfoProvider), new XmlLineInfoProvider(new XmlLineInfo(154, 112)));
		label6.SetValue(fontSizeProperty12, ((IExtendedTypeConverter)fontSizeConverter12).ConvertFromInvariantString("Default", (IServiceProvider)xamlServiceProvider12));
		label6.SetValue(Label.FontAttributesProperty, new FontAttributesConverter().ConvertFromInvariantString("Bold"));
		grid7.Children.Add(label6);
		VisualDiagnostics.RegisterSourceInfo(label6, new Uri("Views/StepChartView.xaml", UriKind.RelativeOrAbsolute), 154, 22);
		grid8.Children.Add(grid7);
		VisualDiagnostics.RegisterSourceInfo(grid7, new Uri("Views/StepChartView.xaml", UriKind.RelativeOrAbsolute), 153, 18);
		button5.SetValue(Message.AttachProperty, "OnSteDataTapped");
		button5.SetValue(Grid.RowProperty, 7);
		button5.SetValue(Grid.ColumnSpanProperty, 6);
		button5.SetValue(Xamarin.Forms.View.MarginProperty, new Thickness(5.0, 5.0, 5.0, 5.0));
		button5.SetValue(Button.BorderColorProperty, Color.Black);
		button5.SetValue(Button.BorderWidthProperty, 2.0);
		BindableProperty fontSizeProperty13 = Button.FontSizeProperty;
		FontSizeConverter fontSizeConverter13 = new FontSizeConverter();
		XamlServiceProvider xamlServiceProvider13 = new XamlServiceProvider();
		Type typeFromHandle25 = typeof(IProvideValueTarget);
		object[] array13 = new object[0 + 5];
		array13[0] = button5;
		array13[1] = grid8;
		array13[2] = scrollView;
		array13[3] = grid9;
		array13[4] = stepChartView;
		object service13;
		xamlServiceProvider13.Add(typeFromHandle25, service13 = new SimpleValueTargetProvider(array13, Button.FontSizeProperty, nameScope));
		xamlServiceProvider13.Add(typeof(IReferenceProvider), service13);
		Type typeFromHandle26 = typeof(IXamlTypeResolver);
		XmlNamespaceResolver xmlNamespaceResolver13 = new XmlNamespaceResolver();
		xmlNamespaceResolver13.Add("", "http://xamarin.com/schemas/2014/forms");
		xmlNamespaceResolver13.Add("x", "http://schemas.microsoft.com/winfx/2009/xaml");
		xmlNamespaceResolver13.Add("calx", "clr-namespace:Caliburn.Micro.Xamarin.Forms;assembly=Caliburn.Micro.Platform.Xamarin.Forms");
		xmlNamespaceResolver13.Add("effect", "clr-namespace:NHL.Views.Effect");
		xmlNamespaceResolver13.Add("c1", "clr-namespace:C1.Xamarin.Forms.Chart;assembly=C1.Xamarin.Forms.Chart");
		xamlServiceProvider13.Add(typeFromHandle26, new XamlTypeResolver(xmlNamespaceResolver13, typeof(StepChartView).GetTypeInfo().Assembly));
		xamlServiceProvider13.Add(typeof(IXmlLineInfoProvider), new XmlLineInfoProvider(new XmlLineInfo(168, 149)));
		button5.SetValue(fontSizeProperty13, ((IExtendedTypeConverter)fontSizeConverter13).ConvertFromInvariantString("Large", (IServiceProvider)xamlServiceProvider13));
		button5.SetValue(Button.TextProperty, "データ表");
		button5.SetValue(Button.FontAttributesProperty, new FontAttributesConverter().ConvertFromInvariantString("Bold"));
		button5.SetValue(VisualElement.BackgroundColorProperty, Color.White);
		fixedFontSizeButtonEffect5.FixedSize = 8;
		button5.Effects.Add(fixedFontSizeButtonEffect5);
		VisualDiagnostics.RegisterSourceInfo(fixedFontSizeButtonEffect5, new Uri("Views/StepChartView.xaml", UriKind.RelativeOrAbsolute), 171, 26);
		grid8.Children.Add(button5);
		VisualDiagnostics.RegisterSourceInfo(button5, new Uri("Views/StepChartView.xaml", UriKind.RelativeOrAbsolute), 168, 18);
		scrollView.Content = grid8;
		VisualDiagnostics.RegisterSourceInfo(grid8, new Uri("Views/StepChartView.xaml", UriKind.RelativeOrAbsolute), 15, 14);
		grid9.Children.Add(scrollView);
		VisualDiagnostics.RegisterSourceInfo(scrollView, new Uri("Views/StepChartView.xaml", UriKind.RelativeOrAbsolute), 14, 10);
		stepChartView.SetValue(ContentPage.ContentProperty, grid9);
		VisualDiagnostics.RegisterSourceInfo(grid9, new Uri("Views/StepChartView.xaml", UriKind.RelativeOrAbsolute), 13, 6);
		VisualDiagnostics.RegisterSourceInfo(stepChartView, new Uri("Views/StepChartView.xaml", UriKind.RelativeOrAbsolute), 3, 2);
	}

	private void __InitComponentRuntime()
	{
		this.LoadFromXaml(typeof(StepChartView));
		Dates = this.FindByName<Label>("Dates");
		chart = this.FindByName<FlexChart>("chart");
		stepLine = this.FindByName<ChartSeries>("stepLine");
	}
}
