using System;
using System.CodeDom.Compiler;
using System.Reflection;
using C1.Xamarin.Forms.Chart;
using Caliburn.Micro;
using Caliburn.Micro.Xamarin.Forms;
using NHL.Models;
using NHL.Views.Effect;
using Xamarin.Forms;
using Xamarin.Forms.Internals;
using Xamarin.Forms.Xaml;
using Xamarin.Forms.Xaml.Diagnostics;
using Xamarin.Forms.Xaml.Internals;

namespace NHL.Views;

[XamlCompilation(XamlCompilationOptions.Compile)]
[XamlFilePath("Views/TemperatureChartView.xaml")]
public class TemperatureChartView : ContentPage
{
	[GeneratedCode("Xamarin.Forms.Build.Tasks.XamlG", "2.0.0.0")]
	private Label Dates;

	[GeneratedCode("Xamarin.Forms.Build.Tasks.XamlG", "2.0.0.0")]
	private FlexChart chart;

	public TemperatureChartView()
	{
		InitializeComponent();
	}

	public void ChartView(BindableCollection<DisplayTemperatureChartDataModel> data, double max)
	{
		chart.ItemsSource = data;
		chart.AxisY.Max = max;
	}

	[GeneratedCode("Xamarin.Forms.Build.Tasks.XamlG", "2.0.0.0")]
	private void InitializeComponent()
	{
		if (ResourceLoader.CanProvideContentFor(new ResourceLoader.ResourceLoadingQuery
		{
			AssemblyName = typeof(TemperatureChartView).GetTypeInfo().Assembly.GetName(),
			ResourcePath = "Views/TemperatureChartView.xaml",
			Instance = this
		}))
		{
			__InitComponentRuntime();
			return;
		}
		if (XamlLoader.XamlFileProvider != null && XamlLoader.XamlFileProvider(GetType()) != null)
		{
			__InitComponentRuntime();
			return;
		}
		RowDefinition rowDefinition = new RowDefinition();
		RowDefinition rowDefinition2 = new RowDefinition();
		RowDefinition rowDefinition3 = new RowDefinition();
		RowDefinition rowDefinition4 = new RowDefinition();
		RowDefinition rowDefinition5 = new RowDefinition();
		ColumnDefinition item = new ColumnDefinition();
		ColumnDefinition item2 = new ColumnDefinition();
		ColumnDefinition item3 = new ColumnDefinition();
		ColumnDefinition item4 = new ColumnDefinition();
		ColumnDefinition item5 = new ColumnDefinition();
		ColumnDefinition item6 = new ColumnDefinition();
		BindingExtension bindingExtension = new BindingExtension();
		FixedFontSizeLabelEffect fixedFontSizeLabelEffect = new FixedFontSizeLabelEffect();
		Label label = new Label();
		Grid grid = new Grid();
		FixedFontSizeButtonEffect fixedFontSizeButtonEffect = new FixedFontSizeButtonEffect();
		Button button = new Button();
		BindingExtension bindingExtension2 = new BindingExtension();
		ChartStyle chartStyle = new ChartStyle();
		ChartAxis chartAxis = new ChartAxis();
		ChartStyle chartStyle2 = new ChartStyle();
		ChartAxis chartAxis2 = new ChartAxis();
		ChartOptions chartOptions = new ChartOptions();
		ChartStyle chartStyle3 = new ChartStyle();
		ChartSeries chartSeries = new ChartSeries();
		ChartStyle chartStyle4 = new ChartStyle();
		ChartSeries chartSeries2 = new ChartSeries();
		FlexChart flexChart = new FlexChart();
		FixedFontSizeLabelEffect fixedFontSizeLabelEffect2 = new FixedFontSizeLabelEffect();
		Label label2 = new Label();
		Grid grid2 = new Grid();
		Grid grid3 = new Grid();
		FixedFontSizeLabelEffect fixedFontSizeLabelEffect3 = new FixedFontSizeLabelEffect();
		Label label3 = new Label();
		Grid grid4 = new Grid();
		BindingExtension bindingExtension3 = new BindingExtension();
		FixedFontSizeLabelEffect fixedFontSizeLabelEffect4 = new FixedFontSizeLabelEffect();
		Label label4 = new Label();
		Grid grid5 = new Grid();
		FixedFontSizeLabelEffect fixedFontSizeLabelEffect5 = new FixedFontSizeLabelEffect();
		Label label5 = new Label();
		Grid grid6 = new Grid();
		FixedFontSizeButtonEffect fixedFontSizeButtonEffect2 = new FixedFontSizeButtonEffect();
		Button button2 = new Button();
		Grid grid7 = new Grid();
		ScrollView scrollView = new ScrollView();
		Grid grid8 = new Grid();
		TemperatureChartView temperatureChartView;
		NameScope nameScope = (NameScope)(NameScope.GetNameScope(temperatureChartView = this) ?? new NameScope());
		NameScope.SetNameScope(temperatureChartView, nameScope);
		((INameScope)nameScope).RegisterName("Dates", (object)label);
		if (label.StyleId == null)
		{
			label.StyleId = "Dates";
		}
		((INameScope)nameScope).RegisterName("chart", (object)flexChart);
		if (flexChart.StyleId == null)
		{
			flexChart.StyleId = "chart";
		}
		Dates = label;
		chart = flexChart;
		temperatureChartView.SetValue(NavigationPage.HasBackButtonProperty, true);
		temperatureChartView.SetValue(NavigationPage.BackButtonTitleProperty, "戻る");
		temperatureChartView.SetValue(Page.BackgroundImageProperty, "bg.png");
		temperatureChartView.SetValue(Page.TitleProperty, "詳細情報");
		rowDefinition.SetValue(RowDefinition.HeightProperty, new GridLengthTypeConverter().ConvertFromInvariantString("50"));
		((DefinitionCollection<RowDefinition>)grid7.GetValue(Grid.RowDefinitionsProperty)).Add(rowDefinition);
		rowDefinition2.SetValue(RowDefinition.HeightProperty, new GridLengthTypeConverter().ConvertFromInvariantString("300"));
		((DefinitionCollection<RowDefinition>)grid7.GetValue(Grid.RowDefinitionsProperty)).Add(rowDefinition2);
		rowDefinition3.SetValue(RowDefinition.HeightProperty, new GridLengthTypeConverter().ConvertFromInvariantString("Auto"));
		((DefinitionCollection<RowDefinition>)grid7.GetValue(Grid.RowDefinitionsProperty)).Add(rowDefinition3);
		rowDefinition4.SetValue(RowDefinition.HeightProperty, new GridLengthTypeConverter().ConvertFromInvariantString("Auto"));
		((DefinitionCollection<RowDefinition>)grid7.GetValue(Grid.RowDefinitionsProperty)).Add(rowDefinition4);
		rowDefinition5.SetValue(RowDefinition.HeightProperty, new GridLengthTypeConverter().ConvertFromInvariantString("Auto"));
		((DefinitionCollection<RowDefinition>)grid7.GetValue(Grid.RowDefinitionsProperty)).Add(rowDefinition5);
		((DefinitionCollection<ColumnDefinition>)grid7.GetValue(Grid.ColumnDefinitionsProperty)).Add(item);
		((DefinitionCollection<ColumnDefinition>)grid7.GetValue(Grid.ColumnDefinitionsProperty)).Add(item2);
		((DefinitionCollection<ColumnDefinition>)grid7.GetValue(Grid.ColumnDefinitionsProperty)).Add(item3);
		((DefinitionCollection<ColumnDefinition>)grid7.GetValue(Grid.ColumnDefinitionsProperty)).Add(item4);
		((DefinitionCollection<ColumnDefinition>)grid7.GetValue(Grid.ColumnDefinitionsProperty)).Add(item5);
		((DefinitionCollection<ColumnDefinition>)grid7.GetValue(Grid.ColumnDefinitionsProperty)).Add(item6);
		grid.SetValue(Grid.RowProperty, 0);
		grid.SetValue(Grid.ColumnSpanProperty, 5);
		bindingExtension.Path = "DisplaySelectedDates";
		BindingBase binding = ((IMarkupExtension<BindingBase>)bindingExtension).ProvideValue((IServiceProvider)null);
		label.SetBinding(Label.TextProperty, binding);
		label.SetValue(Label.FontAttributesProperty, new FontAttributesConverter().ConvertFromInvariantString("Bold"));
		label.SetValue(Label.TextColorProperty, Color.Blue);
		BindableProperty fontSizeProperty = Label.FontSizeProperty;
		FontSizeConverter fontSizeConverter = new FontSizeConverter();
		XamlServiceProvider xamlServiceProvider = new XamlServiceProvider();
		Type typeFromHandle = typeof(IProvideValueTarget);
		object[] array = new object[0 + 6];
		array[0] = label;
		array[1] = grid;
		array[2] = grid7;
		array[3] = scrollView;
		array[4] = grid8;
		array[5] = temperatureChartView;
		object service;
		xamlServiceProvider.Add(typeFromHandle, service = new SimpleValueTargetProvider(array, Label.FontSizeProperty, nameScope));
		xamlServiceProvider.Add(typeof(IReferenceProvider), service);
		Type typeFromHandle2 = typeof(IXamlTypeResolver);
		XmlNamespaceResolver xmlNamespaceResolver = new XmlNamespaceResolver();
		xmlNamespaceResolver.Add("", "http://xamarin.com/schemas/2014/forms");
		xmlNamespaceResolver.Add("x", "http://schemas.microsoft.com/winfx/2009/xaml");
		xmlNamespaceResolver.Add("calx", "clr-namespace:Caliburn.Micro.Xamarin.Forms;assembly=Caliburn.Micro.Platform.Xamarin.Forms");
		xmlNamespaceResolver.Add("effect", "clr-namespace:NHL.Views.Effect");
		xmlNamespaceResolver.Add("c1", "clr-namespace:C1.Xamarin.Forms.Chart;assembly=C1.Xamarin.Forms.Chart");
		xamlServiceProvider.Add(typeFromHandle2, new XamlTypeResolver(xmlNamespaceResolver, typeof(TemperatureChartView).GetTypeInfo().Assembly));
		xamlServiceProvider.Add(typeof(IXmlLineInfoProvider), new XmlLineInfoProvider(new XmlLineInfo(36, 120)));
		label.SetValue(fontSizeProperty, ((IExtendedTypeConverter)fontSizeConverter).ConvertFromInvariantString("20", (IServiceProvider)xamlServiceProvider));
		label.SetValue(Xamarin.Forms.View.VerticalOptionsProperty, LayoutOptions.CenterAndExpand);
		label.SetValue(Xamarin.Forms.View.HorizontalOptionsProperty, LayoutOptions.CenterAndExpand);
		label.Effects.Add(fixedFontSizeLabelEffect);
		VisualDiagnostics.RegisterSourceInfo(fixedFontSizeLabelEffect, new Uri("Views/TemperatureChartView.xaml", UriKind.RelativeOrAbsolute), 38, 30);
		grid.Children.Add(label);
		VisualDiagnostics.RegisterSourceInfo(label, new Uri("Views/TemperatureChartView.xaml", UriKind.RelativeOrAbsolute), 36, 22);
		grid7.Children.Add(grid);
		VisualDiagnostics.RegisterSourceInfo(grid, new Uri("Views/TemperatureChartView.xaml", UriKind.RelativeOrAbsolute), 35, 18);
		button.SetValue(Message.AttachProperty, "OnCalendarTapped");
		button.SetValue(Grid.RowProperty, 0);
		button.SetValue(Grid.ColumnProperty, 5);
		button.SetValue(Button.TextProperty, "選択");
		button.SetValue(Button.FontAttributesProperty, new FontAttributesConverter().ConvertFromInvariantString("Bold"));
		button.SetValue(Button.TextColorProperty, Color.Blue);
		BindableProperty fontSizeProperty2 = Button.FontSizeProperty;
		FontSizeConverter fontSizeConverter2 = new FontSizeConverter();
		XamlServiceProvider xamlServiceProvider2 = new XamlServiceProvider();
		Type typeFromHandle3 = typeof(IProvideValueTarget);
		object[] array2 = new object[0 + 5];
		array2[0] = button;
		array2[1] = grid7;
		array2[2] = scrollView;
		array2[3] = grid8;
		array2[4] = temperatureChartView;
		object service2;
		xamlServiceProvider2.Add(typeFromHandle3, service2 = new SimpleValueTargetProvider(array2, Button.FontSizeProperty, nameScope));
		xamlServiceProvider2.Add(typeof(IReferenceProvider), service2);
		Type typeFromHandle4 = typeof(IXamlTypeResolver);
		XmlNamespaceResolver xmlNamespaceResolver2 = new XmlNamespaceResolver();
		xmlNamespaceResolver2.Add("", "http://xamarin.com/schemas/2014/forms");
		xmlNamespaceResolver2.Add("x", "http://schemas.microsoft.com/winfx/2009/xaml");
		xmlNamespaceResolver2.Add("calx", "clr-namespace:Caliburn.Micro.Xamarin.Forms;assembly=Caliburn.Micro.Platform.Xamarin.Forms");
		xmlNamespaceResolver2.Add("effect", "clr-namespace:NHL.Views.Effect");
		xmlNamespaceResolver2.Add("c1", "clr-namespace:C1.Xamarin.Forms.Chart;assembly=C1.Xamarin.Forms.Chart");
		xamlServiceProvider2.Add(typeFromHandle4, new XamlTypeResolver(xmlNamespaceResolver2, typeof(TemperatureChartView).GetTypeInfo().Assembly));
		xamlServiceProvider2.Add(typeof(IXmlLineInfoProvider), new XmlLineInfoProvider(new XmlLineInfo(44, 142)));
		button.SetValue(fontSizeProperty2, ((IExtendedTypeConverter)fontSizeConverter2).ConvertFromInvariantString("12", (IServiceProvider)xamlServiceProvider2));
		button.SetValue(VisualElement.BackgroundColorProperty, Color.Transparent);
		button.SetValue(Xamarin.Forms.View.VerticalOptionsProperty, LayoutOptions.CenterAndExpand);
		button.SetValue(Xamarin.Forms.View.HorizontalOptionsProperty, LayoutOptions.EndAndExpand);
		button.Effects.Add(fixedFontSizeButtonEffect);
		VisualDiagnostics.RegisterSourceInfo(fixedFontSizeButtonEffect, new Uri("Views/TemperatureChartView.xaml", UriKind.RelativeOrAbsolute), 46, 26);
		grid7.Children.Add(button);
		VisualDiagnostics.RegisterSourceInfo(button, new Uri("Views/TemperatureChartView.xaml", UriKind.RelativeOrAbsolute), 44, 18);
		flexChart.SetValue(Grid.RowProperty, 1);
		flexChart.SetValue(Grid.ColumnProperty, 0);
		flexChart.SetValue(Grid.ColumnSpanProperty, 6);
		flexChart.SetValue(ChartBase.LegendPositionProperty, ChartPositionType.Bottom);
		flexChart.SetValue(VisualElement.BackgroundColorProperty, Color.White);
		flexChart.SetValue(Xamarin.Forms.View.MarginProperty, new Thickness(3.0, 3.0, 3.0, 3.0));
		bindingExtension2.Path = "DisplaySphygChartData";
		BindingBase binding2 = ((IMarkupExtension<BindingBase>)bindingExtension2).ProvideValue((IServiceProvider)null);
		flexChart.SetBinding(ChartBase.BindingProperty, binding2);
		flexChart.SetValue(FlexChart.BindingXProperty, "Date");
		flexChart.SetValue(Xamarin.Forms.View.HorizontalOptionsProperty, LayoutOptions.FillAndExpand);
		flexChart.SetValue(Xamarin.Forms.View.VerticalOptionsProperty, LayoutOptions.FillAndExpand);
		chartAxis.SetValue(ChartAxis.MinProperty, 32.0);
		chartAxis.SetValue(ChartAxis.FormatProperty, "F1");
		chartAxis.SetValue(ChartAxis.AxisLineProperty, true);
		chartAxis.SetValue(ChartAxis.MajorTickMarksProperty, ChartTickMarkType.Outside);
		chartAxis.SetValue(ChartAxis.MajorUnitProperty, 0.5);
		chartAxis.SetValue(ChartAxis.MajorGridProperty, true);
		chartAxis.SetValue(ChartAxis.TitleProperty, "測定値");
		chartStyle.SetValue(ChartStyle.FontSizeProperty, 13.0);
		chartAxis.SetValue(ChartAxis.StyleProperty, chartStyle);
		VisualDiagnostics.RegisterSourceInfo(chartStyle, new Uri("Views/TemperatureChartView.xaml", UriKind.RelativeOrAbsolute), 56, 34);
		flexChart.AxisY = chartAxis;
		VisualDiagnostics.RegisterSourceInfo(chartAxis, new Uri("Views/TemperatureChartView.xaml", UriKind.RelativeOrAbsolute), 54, 26);
		chartAxis2.SetValue(ChartAxis.AxisLineProperty, true);
		chartAxis2.SetValue(ChartAxis.TitleProperty, "測定日");
		chartAxis2.SetValue(ChartAxis.MajorGridProperty, true);
		chartStyle2.SetValue(ChartStyle.FontSizeProperty, 13.0);
		chartAxis2.SetValue(ChartAxis.StyleProperty, chartStyle2);
		VisualDiagnostics.RegisterSourceInfo(chartStyle2, new Uri("Views/TemperatureChartView.xaml", UriKind.RelativeOrAbsolute), 63, 34);
		flexChart.AxisX = chartAxis2;
		VisualDiagnostics.RegisterSourceInfo(chartAxis2, new Uri("Views/TemperatureChartView.xaml", UriKind.RelativeOrAbsolute), 61, 26);
		chartOptions.SetValue(ChartOptions.InterpolateNullsProperty, true);
		flexChart.SetValue(FlexChart.OptionsProperty, chartOptions);
		VisualDiagnostics.RegisterSourceInfo(chartOptions, new Uri("Views/TemperatureChartView.xaml", UriKind.RelativeOrAbsolute), 68, 26);
		chartSeries.SetValue(ChartSeries.SeriesNameProperty, "体温");
		chartSeries.SetValue(ChartSeries.BindingProperty, "Temperature");
		chartSeries.SetValue(ChartSeries.ChartTypeProperty, new ChartType?(ChartType.LineSymbols));
		chartSeries.SetValue(ChartSeries.SymbolMarkerProperty, ChartMarkerType.Dot);
		chartSeries.SetValue(ChartSeries.SymbolSizeProperty, 10);
		chartStyle3.SetValue(ChartStyle.StrokeProperty, new Color(0.7764706015586853, 0.1568627506494522, 0.1568627506494522, 1.0));
		chartStyle3.SetValue(ChartStyle.FillProperty, new Color(0.7764706015586853, 0.1568627506494522, 0.1568627506494522, 1.0));
		chartSeries.SetValue(ChartSeries.StyleProperty, chartStyle3);
		VisualDiagnostics.RegisterSourceInfo(chartStyle3, new Uri("Views/TemperatureChartView.xaml", UriKind.RelativeOrAbsolute), 74, 34);
		flexChart.Series.Add(chartSeries);
		chartSeries2.SetValue(ChartSeries.BindingProperty, "DefaultValue");
		chartSeries2.SetValue(ChartSeries.ChartTypeProperty, new ChartType?(ChartType.LineSymbols));
		chartSeries2.SetValue(ChartSeries.SymbolSizeProperty, 1);
		chartStyle4.SetValue(ChartStyle.StrokeProperty, Color.Transparent);
		chartStyle4.SetValue(ChartStyle.FillProperty, Color.Transparent);
		chartSeries2.SetValue(ChartSeries.StyleProperty, chartStyle4);
		VisualDiagnostics.RegisterSourceInfo(chartStyle4, new Uri("Views/TemperatureChartView.xaml", UriKind.RelativeOrAbsolute), 79, 34);
		flexChart.Series.Add(chartSeries2);
		grid7.Children.Add(flexChart);
		VisualDiagnostics.RegisterSourceInfo(flexChart, new Uri("Views/TemperatureChartView.xaml", UriKind.RelativeOrAbsolute), 51, 18);
		grid2.SetValue(Grid.RowProperty, 2);
		grid2.SetValue(Grid.ColumnProperty, 0);
		grid2.SetValue(Grid.ColumnSpanProperty, 6);
		grid2.SetValue(Grid.RowSpacingProperty, 0.0);
		grid2.SetValue(VisualElement.BackgroundColorProperty, Color.Transparent);
		grid2.SetValue(Xamarin.Forms.View.MarginProperty, new Thickness(3.0, 3.0, 3.0, 3.0));
		label2.SetValue(Label.TextProperty, " 平均値");
		label2.SetValue(Label.TextColorProperty, Color.Blue);
		label2.SetValue(Xamarin.Forms.View.VerticalOptionsProperty, LayoutOptions.End);
		label2.SetValue(Xamarin.Forms.View.HorizontalOptionsProperty, LayoutOptions.CenterAndExpand);
		BindableProperty fontSizeProperty3 = Label.FontSizeProperty;
		FontSizeConverter fontSizeConverter3 = new FontSizeConverter();
		XamlServiceProvider xamlServiceProvider3 = new XamlServiceProvider();
		Type typeFromHandle5 = typeof(IProvideValueTarget);
		object[] array3 = new object[0 + 6];
		array3[0] = label2;
		array3[1] = grid2;
		array3[2] = grid7;
		array3[3] = scrollView;
		array3[4] = grid8;
		array3[5] = temperatureChartView;
		object service3;
		xamlServiceProvider3.Add(typeFromHandle5, service3 = new SimpleValueTargetProvider(array3, Label.FontSizeProperty, nameScope));
		xamlServiceProvider3.Add(typeof(IReferenceProvider), service3);
		Type typeFromHandle6 = typeof(IXamlTypeResolver);
		XmlNamespaceResolver xmlNamespaceResolver3 = new XmlNamespaceResolver();
		xmlNamespaceResolver3.Add("", "http://xamarin.com/schemas/2014/forms");
		xmlNamespaceResolver3.Add("x", "http://schemas.microsoft.com/winfx/2009/xaml");
		xmlNamespaceResolver3.Add("calx", "clr-namespace:Caliburn.Micro.Xamarin.Forms;assembly=Caliburn.Micro.Platform.Xamarin.Forms");
		xmlNamespaceResolver3.Add("effect", "clr-namespace:NHL.Views.Effect");
		xmlNamespaceResolver3.Add("c1", "clr-namespace:C1.Xamarin.Forms.Chart;assembly=C1.Xamarin.Forms.Chart");
		xamlServiceProvider3.Add(typeFromHandle6, new XamlTypeResolver(xmlNamespaceResolver3, typeof(TemperatureChartView).GetTypeInfo().Assembly));
		xamlServiceProvider3.Add(typeof(IXmlLineInfoProvider), new XmlLineInfoProvider(new XmlLineInfo(87, 115)));
		label2.SetValue(fontSizeProperty3, ((IExtendedTypeConverter)fontSizeConverter3).ConvertFromInvariantString("Large", (IServiceProvider)xamlServiceProvider3));
		label2.SetValue(Label.FontAttributesProperty, new FontAttributesConverter().ConvertFromInvariantString("Bold"));
		label2.SetValue(VisualElement.BackgroundColorProperty, Color.Transparent);
		label2.Effects.Add(fixedFontSizeLabelEffect2);
		VisualDiagnostics.RegisterSourceInfo(fixedFontSizeLabelEffect2, new Uri("Views/TemperatureChartView.xaml", UriKind.RelativeOrAbsolute), 89, 30);
		grid2.Children.Add(label2);
		VisualDiagnostics.RegisterSourceInfo(label2, new Uri("Views/TemperatureChartView.xaml", UriKind.RelativeOrAbsolute), 87, 22);
		grid7.Children.Add(grid2);
		VisualDiagnostics.RegisterSourceInfo(grid2, new Uri("Views/TemperatureChartView.xaml", UriKind.RelativeOrAbsolute), 86, 18);
		grid3.SetValue(Grid.RowProperty, 3);
		grid3.SetValue(Grid.ColumnProperty, 0);
		grid3.SetValue(Grid.ColumnSpanProperty, 6);
		grid3.SetValue(VisualElement.BackgroundColorProperty, Color.White);
		grid3.SetValue(Xamarin.Forms.View.MarginProperty, new Thickness(3.0, 3.0, 3.0, 3.0));
		grid7.Children.Add(grid3);
		VisualDiagnostics.RegisterSourceInfo(grid3, new Uri("Views/TemperatureChartView.xaml", UriKind.RelativeOrAbsolute), 93, 18);
		grid4.SetValue(Grid.RowProperty, 3);
		grid4.SetValue(Grid.ColumnProperty, 0);
		grid4.SetValue(Grid.ColumnSpanProperty, 3);
		grid4.SetValue(VisualElement.BackgroundColorProperty, Color.Transparent);
		grid4.SetValue(Xamarin.Forms.View.MarginProperty, new Thickness(15.0, 0.0, 0.0, 0.0));
		label3.SetValue(Label.TextProperty, "体温");
		label3.SetValue(Label.TextColorProperty, Color.Blue);
		label3.SetValue(Xamarin.Forms.View.VerticalOptionsProperty, LayoutOptions.Center);
		label3.SetValue(Xamarin.Forms.View.HorizontalOptionsProperty, LayoutOptions.StartAndExpand);
		BindableProperty fontSizeProperty4 = Label.FontSizeProperty;
		FontSizeConverter fontSizeConverter4 = new FontSizeConverter();
		XamlServiceProvider xamlServiceProvider4 = new XamlServiceProvider();
		Type typeFromHandle7 = typeof(IProvideValueTarget);
		object[] array4 = new object[0 + 6];
		array4[0] = label3;
		array4[1] = grid4;
		array4[2] = grid7;
		array4[3] = scrollView;
		array4[4] = grid8;
		array4[5] = temperatureChartView;
		object service4;
		xamlServiceProvider4.Add(typeFromHandle7, service4 = new SimpleValueTargetProvider(array4, Label.FontSizeProperty, nameScope));
		xamlServiceProvider4.Add(typeof(IReferenceProvider), service4);
		Type typeFromHandle8 = typeof(IXamlTypeResolver);
		XmlNamespaceResolver xmlNamespaceResolver4 = new XmlNamespaceResolver();
		xmlNamespaceResolver4.Add("", "http://xamarin.com/schemas/2014/forms");
		xmlNamespaceResolver4.Add("x", "http://schemas.microsoft.com/winfx/2009/xaml");
		xmlNamespaceResolver4.Add("calx", "clr-namespace:Caliburn.Micro.Xamarin.Forms;assembly=Caliburn.Micro.Platform.Xamarin.Forms");
		xmlNamespaceResolver4.Add("effect", "clr-namespace:NHL.Views.Effect");
		xmlNamespaceResolver4.Add("c1", "clr-namespace:C1.Xamarin.Forms.Chart;assembly=C1.Xamarin.Forms.Chart");
		xamlServiceProvider4.Add(typeFromHandle8, new XamlTypeResolver(xmlNamespaceResolver4, typeof(TemperatureChartView).GetTypeInfo().Assembly));
		xamlServiceProvider4.Add(typeof(IXmlLineInfoProvider), new XmlLineInfoProvider(new XmlLineInfo(97, 115)));
		label3.SetValue(fontSizeProperty4, ((IExtendedTypeConverter)fontSizeConverter4).ConvertFromInvariantString("Large", (IServiceProvider)xamlServiceProvider4));
		label3.Effects.Add(fixedFontSizeLabelEffect3);
		VisualDiagnostics.RegisterSourceInfo(fixedFontSizeLabelEffect3, new Uri("Views/TemperatureChartView.xaml", UriKind.RelativeOrAbsolute), 99, 30);
		grid4.Children.Add(label3);
		VisualDiagnostics.RegisterSourceInfo(label3, new Uri("Views/TemperatureChartView.xaml", UriKind.RelativeOrAbsolute), 97, 22);
		grid7.Children.Add(grid4);
		VisualDiagnostics.RegisterSourceInfo(grid4, new Uri("Views/TemperatureChartView.xaml", UriKind.RelativeOrAbsolute), 96, 18);
		grid5.SetValue(Grid.RowProperty, 3);
		grid5.SetValue(Grid.ColumnProperty, 3);
		grid5.SetValue(Grid.ColumnSpanProperty, 2);
		grid5.SetValue(Grid.ColumnSpacingProperty, 0.0);
		grid5.SetValue(VisualElement.BackgroundColorProperty, Color.Transparent);
		bindingExtension3.Path = "TemperatureAverage";
		BindingBase binding3 = ((IMarkupExtension<BindingBase>)bindingExtension3).ProvideValue((IServiceProvider)null);
		label4.SetBinding(Label.TextProperty, binding3);
		label4.SetValue(Label.TextColorProperty, Color.Blue);
		label4.SetValue(Xamarin.Forms.View.VerticalOptionsProperty, LayoutOptions.EndAndExpand);
		label4.SetValue(Xamarin.Forms.View.HorizontalOptionsProperty, LayoutOptions.End);
		BindableProperty fontSizeProperty5 = Label.FontSizeProperty;
		FontSizeConverter fontSizeConverter5 = new FontSizeConverter();
		XamlServiceProvider xamlServiceProvider5 = new XamlServiceProvider();
		Type typeFromHandle9 = typeof(IProvideValueTarget);
		object[] array5 = new object[0 + 6];
		array5[0] = label4;
		array5[1] = grid5;
		array5[2] = grid7;
		array5[3] = scrollView;
		array5[4] = grid8;
		array5[5] = temperatureChartView;
		object service5;
		xamlServiceProvider5.Add(typeFromHandle9, service5 = new SimpleValueTargetProvider(array5, Label.FontSizeProperty, nameScope));
		xamlServiceProvider5.Add(typeof(IReferenceProvider), service5);
		Type typeFromHandle10 = typeof(IXamlTypeResolver);
		XmlNamespaceResolver xmlNamespaceResolver5 = new XmlNamespaceResolver();
		xmlNamespaceResolver5.Add("", "http://xamarin.com/schemas/2014/forms");
		xmlNamespaceResolver5.Add("x", "http://schemas.microsoft.com/winfx/2009/xaml");
		xmlNamespaceResolver5.Add("calx", "clr-namespace:Caliburn.Micro.Xamarin.Forms;assembly=Caliburn.Micro.Platform.Xamarin.Forms");
		xmlNamespaceResolver5.Add("effect", "clr-namespace:NHL.Views.Effect");
		xmlNamespaceResolver5.Add("c1", "clr-namespace:C1.Xamarin.Forms.Chart;assembly=C1.Xamarin.Forms.Chart");
		xamlServiceProvider5.Add(typeFromHandle10, new XamlTypeResolver(xmlNamespaceResolver5, typeof(TemperatureChartView).GetTypeInfo().Assembly));
		xamlServiceProvider5.Add(typeof(IXmlLineInfoProvider), new XmlLineInfoProvider(new XmlLineInfo(104, 136)));
		label4.SetValue(fontSizeProperty5, ((IExtendedTypeConverter)fontSizeConverter5).ConvertFromInvariantString("Large", (IServiceProvider)xamlServiceProvider5));
		label4.SetValue(Label.FontAttributesProperty, new FontAttributesConverter().ConvertFromInvariantString("Bold"));
		label4.Effects.Add(fixedFontSizeLabelEffect4);
		VisualDiagnostics.RegisterSourceInfo(fixedFontSizeLabelEffect4, new Uri("Views/TemperatureChartView.xaml", UriKind.RelativeOrAbsolute), 107, 30);
		grid5.Children.Add(label4);
		VisualDiagnostics.RegisterSourceInfo(label4, new Uri("Views/TemperatureChartView.xaml", UriKind.RelativeOrAbsolute), 104, 22);
		grid7.Children.Add(grid5);
		VisualDiagnostics.RegisterSourceInfo(grid5, new Uri("Views/TemperatureChartView.xaml", UriKind.RelativeOrAbsolute), 103, 18);
		grid6.SetValue(Grid.RowProperty, 3);
		grid6.SetValue(Grid.ColumnProperty, 5);
		grid6.SetValue(Grid.ColumnSpacingProperty, 0.0);
		grid6.SetValue(VisualElement.BackgroundColorProperty, Color.Transparent);
		grid6.SetValue(Xamarin.Forms.View.MarginProperty, new Thickness(0.0, 0.0, 5.0, 3.0));
		label5.SetValue(Label.TextProperty, "度");
		label5.SetValue(Label.TextColorProperty, Color.Black);
		label5.SetValue(Xamarin.Forms.View.VerticalOptionsProperty, LayoutOptions.EndAndExpand);
		label5.SetValue(Xamarin.Forms.View.HorizontalOptionsProperty, LayoutOptions.Start);
		BindableProperty fontSizeProperty6 = Label.FontSizeProperty;
		FontSizeConverter fontSizeConverter6 = new FontSizeConverter();
		XamlServiceProvider xamlServiceProvider6 = new XamlServiceProvider();
		Type typeFromHandle11 = typeof(IProvideValueTarget);
		object[] array6 = new object[0 + 6];
		array6[0] = label5;
		array6[1] = grid6;
		array6[2] = grid7;
		array6[3] = scrollView;
		array6[4] = grid8;
		array6[5] = temperatureChartView;
		object service6;
		xamlServiceProvider6.Add(typeFromHandle11, service6 = new SimpleValueTargetProvider(array6, Label.FontSizeProperty, nameScope));
		xamlServiceProvider6.Add(typeof(IReferenceProvider), service6);
		Type typeFromHandle12 = typeof(IXamlTypeResolver);
		XmlNamespaceResolver xmlNamespaceResolver6 = new XmlNamespaceResolver();
		xmlNamespaceResolver6.Add("", "http://xamarin.com/schemas/2014/forms");
		xmlNamespaceResolver6.Add("x", "http://schemas.microsoft.com/winfx/2009/xaml");
		xmlNamespaceResolver6.Add("calx", "clr-namespace:Caliburn.Micro.Xamarin.Forms;assembly=Caliburn.Micro.Platform.Xamarin.Forms");
		xmlNamespaceResolver6.Add("effect", "clr-namespace:NHL.Views.Effect");
		xmlNamespaceResolver6.Add("c1", "clr-namespace:C1.Xamarin.Forms.Chart;assembly=C1.Xamarin.Forms.Chart");
		xamlServiceProvider6.Add(typeFromHandle12, new XamlTypeResolver(xmlNamespaceResolver6, typeof(TemperatureChartView).GetTypeInfo().Assembly));
		xamlServiceProvider6.Add(typeof(IXmlLineInfoProvider), new XmlLineInfoProvider(new XmlLineInfo(112, 112)));
		label5.SetValue(fontSizeProperty6, ((IExtendedTypeConverter)fontSizeConverter6).ConvertFromInvariantString("Default", (IServiceProvider)xamlServiceProvider6));
		label5.SetValue(Label.FontAttributesProperty, new FontAttributesConverter().ConvertFromInvariantString("Bold"));
		label5.Effects.Add(fixedFontSizeLabelEffect5);
		VisualDiagnostics.RegisterSourceInfo(fixedFontSizeLabelEffect5, new Uri("Views/TemperatureChartView.xaml", UriKind.RelativeOrAbsolute), 114, 30);
		grid6.Children.Add(label5);
		VisualDiagnostics.RegisterSourceInfo(label5, new Uri("Views/TemperatureChartView.xaml", UriKind.RelativeOrAbsolute), 112, 22);
		grid7.Children.Add(grid6);
		VisualDiagnostics.RegisterSourceInfo(grid6, new Uri("Views/TemperatureChartView.xaml", UriKind.RelativeOrAbsolute), 111, 18);
		button2.SetValue(Grid.RowProperty, 4);
		button2.SetValue(Grid.ColumnSpanProperty, 6);
		button2.SetValue(Xamarin.Forms.View.MarginProperty, new Thickness(5.0, 5.0, 5.0, 5.0));
		button2.SetValue(Button.BorderColorProperty, Color.Black);
		button2.SetValue(Button.BorderWidthProperty, 2.0);
		BindableProperty fontSizeProperty7 = Button.FontSizeProperty;
		FontSizeConverter fontSizeConverter7 = new FontSizeConverter();
		XamlServiceProvider xamlServiceProvider7 = new XamlServiceProvider();
		Type typeFromHandle13 = typeof(IProvideValueTarget);
		object[] array7 = new object[0 + 5];
		array7[0] = button2;
		array7[1] = grid7;
		array7[2] = scrollView;
		array7[3] = grid8;
		array7[4] = temperatureChartView;
		object service7;
		xamlServiceProvider7.Add(typeFromHandle13, service7 = new SimpleValueTargetProvider(array7, Button.FontSizeProperty, nameScope));
		xamlServiceProvider7.Add(typeof(IReferenceProvider), service7);
		Type typeFromHandle14 = typeof(IXamlTypeResolver);
		XmlNamespaceResolver xmlNamespaceResolver7 = new XmlNamespaceResolver();
		xmlNamespaceResolver7.Add("", "http://xamarin.com/schemas/2014/forms");
		xmlNamespaceResolver7.Add("x", "http://schemas.microsoft.com/winfx/2009/xaml");
		xmlNamespaceResolver7.Add("calx", "clr-namespace:Caliburn.Micro.Xamarin.Forms;assembly=Caliburn.Micro.Platform.Xamarin.Forms");
		xmlNamespaceResolver7.Add("effect", "clr-namespace:NHL.Views.Effect");
		xmlNamespaceResolver7.Add("c1", "clr-namespace:C1.Xamarin.Forms.Chart;assembly=C1.Xamarin.Forms.Chart");
		xamlServiceProvider7.Add(typeFromHandle14, new XamlTypeResolver(xmlNamespaceResolver7, typeof(TemperatureChartView).GetTypeInfo().Assembly));
		xamlServiceProvider7.Add(typeof(IXmlLineInfoProvider), new XmlLineInfoProvider(new XmlLineInfo(119, 111)));
		button2.SetValue(fontSizeProperty7, ((IExtendedTypeConverter)fontSizeConverter7).ConvertFromInvariantString("Large", (IServiceProvider)xamlServiceProvider7));
		button2.SetValue(Message.AttachProperty, "OnTempDataTapped");
		button2.SetValue(Button.TextProperty, "データ表");
		button2.SetValue(Button.FontAttributesProperty, new FontAttributesConverter().ConvertFromInvariantString("Bold"));
		button2.SetValue(VisualElement.BackgroundColorProperty, Color.White);
		button2.Effects.Add(fixedFontSizeButtonEffect2);
		VisualDiagnostics.RegisterSourceInfo(fixedFontSizeButtonEffect2, new Uri("Views/TemperatureChartView.xaml", UriKind.RelativeOrAbsolute), 121, 26);
		grid7.Children.Add(button2);
		VisualDiagnostics.RegisterSourceInfo(button2, new Uri("Views/TemperatureChartView.xaml", UriKind.RelativeOrAbsolute), 119, 18);
		scrollView.Content = grid7;
		VisualDiagnostics.RegisterSourceInfo(grid7, new Uri("Views/TemperatureChartView.xaml", UriKind.RelativeOrAbsolute), 16, 14);
		grid8.Children.Add(scrollView);
		VisualDiagnostics.RegisterSourceInfo(scrollView, new Uri("Views/TemperatureChartView.xaml", UriKind.RelativeOrAbsolute), 15, 10);
		temperatureChartView.SetValue(ContentPage.ContentProperty, grid8);
		VisualDiagnostics.RegisterSourceInfo(grid8, new Uri("Views/TemperatureChartView.xaml", UriKind.RelativeOrAbsolute), 14, 6);
		VisualDiagnostics.RegisterSourceInfo(temperatureChartView, new Uri("Views/TemperatureChartView.xaml", UriKind.RelativeOrAbsolute), 3, 2);
	}

	private void __InitComponentRuntime()
	{
		this.LoadFromXaml(typeof(TemperatureChartView));
		Dates = this.FindByName<Label>("Dates");
		chart = this.FindByName<FlexChart>("chart");
	}
}
