using System;
using System.CodeDom.Compiler;
using System.Reflection;
using Caliburn.Micro.Xamarin.Forms;
using NHL.Views.Effect;
using NHL.Views.Renderer;
using Xamarin.Forms;
using Xamarin.Forms.Internals;
using Xamarin.Forms.Xaml;
using Xamarin.Forms.Xaml.Diagnostics;
using Xamarin.Forms.Xaml.Internals;

namespace NHL.Views;

[XamlCompilation(XamlCompilationOptions.Compile)]
[XamlFilePath("Views/TimeZoneUpdateView.xaml")]
public class TimeZoneUpdateView : ContentPage
{
	public TimeZoneUpdateView()
	{
		InitializeComponent();
	}

	[GeneratedCode("Xamarin.Forms.Build.Tasks.XamlG", "2.0.0.0")]
	private void InitializeComponent()
	{
		if (ResourceLoader.CanProvideContentFor(new ResourceLoader.ResourceLoadingQuery
		{
			AssemblyName = typeof(TimeZoneUpdateView).GetTypeInfo().Assembly.GetName(),
			ResourcePath = "Views/TimeZoneUpdateView.xaml",
			Instance = this
		}))
		{
			__InitComponentRuntime();
			return;
		}
		if (XamlLoader.XamlFileProvider != null && XamlLoader.XamlFileProvider(GetType()) != null)
		{
			__InitComponentRuntime();
			return;
		}
		StaticResourceExtension staticResourceExtension = new StaticResourceExtension();
		Color color = Color.FromHex("#EFEFF4");
		Color color2 = Color.FromHex("#5B9BD5");
		Color color3 = Color.FromHex("#CFCFCF");
		ResourceDictionary resourceDictionary = new ResourceDictionary();
		ColumnDefinition columnDefinition = new ColumnDefinition();
		ColumnDefinition columnDefinition2 = new ColumnDefinition();
		RowDefinition rowDefinition = new RowDefinition();
		RowDefinition rowDefinition2 = new RowDefinition();
		RowDefinition rowDefinition3 = new RowDefinition();
		RowDefinition rowDefinition4 = new RowDefinition();
		RowDefinition rowDefinition5 = new RowDefinition();
		RowDefinition rowDefinition6 = new RowDefinition();
		RowDefinition rowDefinition7 = new RowDefinition();
		RowDefinition rowDefinition8 = new RowDefinition();
		RowDefinition rowDefinition9 = new RowDefinition();
		RowDefinition rowDefinition10 = new RowDefinition();
		RowDefinition rowDefinition11 = new RowDefinition();
		RowDefinition rowDefinition12 = new RowDefinition();
		RowDefinition rowDefinition13 = new RowDefinition();
		StaticResourceExtension staticResourceExtension2 = new StaticResourceExtension();
		Grid grid = new Grid();
		StaticResourceExtension staticResourceExtension3 = new StaticResourceExtension();
		Grid grid2 = new Grid();
		StaticResourceExtension staticResourceExtension4 = new StaticResourceExtension();
		Grid grid3 = new Grid();
		StaticResourceExtension staticResourceExtension5 = new StaticResourceExtension();
		Grid grid4 = new Grid();
		StaticResourceExtension staticResourceExtension6 = new StaticResourceExtension();
		Grid grid5 = new Grid();
		Grid grid6 = new Grid();
		Grid grid7 = new Grid();
		Grid grid8 = new Grid();
		Grid grid9 = new Grid();
		Grid grid10 = new Grid();
		Grid grid11 = new Grid();
		Grid grid12 = new Grid();
		FixedFontSizeLabelEffect fixedFontSizeLabelEffect = new FixedFontSizeLabelEffect();
		Label label = new Label();
		FixedFontSizeLabelEffect fixedFontSizeLabelEffect2 = new FixedFontSizeLabelEffect();
		Label label2 = new Label();
		FixedFontSizeLabelEffect fixedFontSizeLabelEffect3 = new FixedFontSizeLabelEffect();
		Label label3 = new Label();
		FixedFontSizeLabelEffect fixedFontSizeLabelEffect4 = new FixedFontSizeLabelEffect();
		Label label4 = new Label();
		FixedFontSizeLabelEffect fixedFontSizeLabelEffect5 = new FixedFontSizeLabelEffect();
		Label label5 = new Label();
		BindingExtension bindingExtension = new BindingExtension();
		FixedFontSizeLabelEffect fixedFontSizeLabelEffect6 = new FixedFontSizeLabelEffect();
		Label label6 = new Label();
		BindingExtension bindingExtension2 = new BindingExtension();
		FixedFontSizeLabelEffect fixedFontSizeLabelEffect7 = new FixedFontSizeLabelEffect();
		Label label7 = new Label();
		BindingExtension bindingExtension3 = new BindingExtension();
		FixedFontSizeLabelEffect fixedFontSizeLabelEffect8 = new FixedFontSizeLabelEffect();
		Label label8 = new Label();
		BindingExtension bindingExtension4 = new BindingExtension();
		FixedFontSizeLabelEffect fixedFontSizeLabelEffect9 = new FixedFontSizeLabelEffect();
		Label label9 = new Label();
		BindingExtension bindingExtension5 = new BindingExtension();
		FixedFontSizeLabelEffect fixedFontSizeLabelEffect10 = new FixedFontSizeLabelEffect();
		Label label10 = new Label();
		BindingExtension bindingExtension6 = new BindingExtension();
		BindingExtension bindingExtension7 = new BindingExtension();
		FixedFontSizeTextBoxEffect fixedFontSizeTextBoxEffect = new FixedFontSizeTextBoxEffect();
		TimeZonePicker timeZonePicker = new TimeZonePicker();
		BindingExtension bindingExtension8 = new BindingExtension();
		BindingExtension bindingExtension9 = new BindingExtension();
		FixedFontSizeTextBoxEffect fixedFontSizeTextBoxEffect2 = new FixedFontSizeTextBoxEffect();
		TimeZonePicker timeZonePicker2 = new TimeZonePicker();
		BindingExtension bindingExtension10 = new BindingExtension();
		BindingExtension bindingExtension11 = new BindingExtension();
		FixedFontSizeTextBoxEffect fixedFontSizeTextBoxEffect3 = new FixedFontSizeTextBoxEffect();
		TimeZonePicker timeZonePicker3 = new TimeZonePicker();
		BindingExtension bindingExtension12 = new BindingExtension();
		BindingExtension bindingExtension13 = new BindingExtension();
		FixedFontSizeTextBoxEffect fixedFontSizeTextBoxEffect4 = new FixedFontSizeTextBoxEffect();
		TimeZonePicker timeZonePicker4 = new TimeZonePicker();
		BindingExtension bindingExtension14 = new BindingExtension();
		BindingExtension bindingExtension15 = new BindingExtension();
		FixedFontSizeTextBoxEffect fixedFontSizeTextBoxEffect5 = new FixedFontSizeTextBoxEffect();
		TimeZonePicker timeZonePicker5 = new TimeZonePicker();
		FixedFontSizeLabelEffect fixedFontSizeLabelEffect11 = new FixedFontSizeLabelEffect();
		Label label11 = new Label();
		StaticResourceExtension staticResourceExtension7 = new StaticResourceExtension();
		BindingExtension bindingExtension16 = new BindingExtension();
		FixedFontSizeButtonEffect fixedFontSizeButtonEffect = new FixedFontSizeButtonEffect();
		Button button = new Button();
		Grid grid13 = new Grid();
		StackLayout stackLayout = new StackLayout();
		TimeZoneUpdateView timeZoneUpdateView;
		NameScope nameScope = (NameScope)(NameScope.GetNameScope(timeZoneUpdateView = this) ?? new NameScope());
		NameScope.SetNameScope(timeZoneUpdateView, nameScope);
		timeZoneUpdateView.Resources = resourceDictionary;
		VisualDiagnostics.RegisterSourceInfo(resourceDictionary, new Uri("Views/TimeZoneUpdateView.xaml", UriKind.RelativeOrAbsolute), 14, 10);
		resourceDictionary.Add("PageBackgroundColor", color);
		resourceDictionary.Add("ButtonColor", color2);
		resourceDictionary.Add("LineColor", color3);
		timeZoneUpdateView.SetValue(NavigationPage.HasBackButtonProperty, true);
		timeZoneUpdateView.SetValue(NavigationPage.BackButtonTitleProperty, "戻る");
		timeZoneUpdateView.SetValue(Page.TitleProperty, "タイムゾーン設定（血糖）");
		staticResourceExtension.Key = "PageBackgroundColor";
		XamlServiceProvider xamlServiceProvider = new XamlServiceProvider();
		Type typeFromHandle = typeof(IProvideValueTarget);
		object[] array = new object[0 + 1];
		array[0] = timeZoneUpdateView;
		object service;
		xamlServiceProvider.Add(typeFromHandle, service = new SimpleValueTargetProvider(array, VisualElement.BackgroundColorProperty, nameScope));
		xamlServiceProvider.Add(typeof(IReferenceProvider), service);
		Type typeFromHandle2 = typeof(IXamlTypeResolver);
		XmlNamespaceResolver xmlNamespaceResolver = new XmlNamespaceResolver();
		xmlNamespaceResolver.Add("", "http://xamarin.com/schemas/2014/forms");
		xmlNamespaceResolver.Add("x", "http://schemas.microsoft.com/winfx/2009/xaml");
		xmlNamespaceResolver.Add("calx", "clr-namespace:Caliburn.Micro.Xamarin.Forms;assembly=Caliburn.Micro.Platform.Xamarin.Forms");
		xmlNamespaceResolver.Add("renderer", "clr-namespace:NHL.Views.Renderer");
		xmlNamespaceResolver.Add("effect", "clr-namespace:NHL.Views.Effect");
		xamlServiceProvider.Add(typeFromHandle2, new XamlTypeResolver(xmlNamespaceResolver, typeof(TimeZoneUpdateView).GetTypeInfo().Assembly));
		xamlServiceProvider.Add(typeof(IXmlLineInfoProvider), new XmlLineInfoProvider(new XmlLineInfo(11, 14)));
		object obj = ((IMarkupExtension)staticResourceExtension).ProvideValue((IServiceProvider)xamlServiceProvider);
		timeZoneUpdateView.BackgroundColor = (Color)obj;
		VisualDiagnostics.RegisterSourceInfo(obj, new Uri("Views/TimeZoneUpdateView.xaml", UriKind.RelativeOrAbsolute), 11, 14);
		timeZoneUpdateView.Resources = resourceDictionary;
		VisualDiagnostics.RegisterSourceInfo(resourceDictionary, new Uri("Views/TimeZoneUpdateView.xaml", UriKind.RelativeOrAbsolute), 14, 10);
		stackLayout.SetValue(Xamarin.Forms.View.HorizontalOptionsProperty, LayoutOptions.FillAndExpand);
		stackLayout.SetValue(StackLayout.SpacingProperty, 0.0);
		grid13.SetValue(Grid.RowSpacingProperty, 0.0);
		columnDefinition.SetValue(ColumnDefinition.WidthProperty, new GridLengthTypeConverter().ConvertFromInvariantString("*"));
		((DefinitionCollection<ColumnDefinition>)grid13.GetValue(Grid.ColumnDefinitionsProperty)).Add(columnDefinition);
		columnDefinition2.SetValue(ColumnDefinition.WidthProperty, new GridLengthTypeConverter().ConvertFromInvariantString("Auto"));
		((DefinitionCollection<ColumnDefinition>)grid13.GetValue(Grid.ColumnDefinitionsProperty)).Add(columnDefinition2);
		rowDefinition.SetValue(RowDefinition.HeightProperty, new GridLengthTypeConverter().ConvertFromInvariantString("1"));
		((DefinitionCollection<RowDefinition>)grid13.GetValue(Grid.RowDefinitionsProperty)).Add(rowDefinition);
		rowDefinition2.SetValue(RowDefinition.HeightProperty, new GridLengthTypeConverter().ConvertFromInvariantString("Auto"));
		((DefinitionCollection<RowDefinition>)grid13.GetValue(Grid.RowDefinitionsProperty)).Add(rowDefinition2);
		rowDefinition3.SetValue(RowDefinition.HeightProperty, new GridLengthTypeConverter().ConvertFromInvariantString("1"));
		((DefinitionCollection<RowDefinition>)grid13.GetValue(Grid.RowDefinitionsProperty)).Add(rowDefinition3);
		rowDefinition4.SetValue(RowDefinition.HeightProperty, new GridLengthTypeConverter().ConvertFromInvariantString("Auto"));
		((DefinitionCollection<RowDefinition>)grid13.GetValue(Grid.RowDefinitionsProperty)).Add(rowDefinition4);
		rowDefinition5.SetValue(RowDefinition.HeightProperty, new GridLengthTypeConverter().ConvertFromInvariantString("1"));
		((DefinitionCollection<RowDefinition>)grid13.GetValue(Grid.RowDefinitionsProperty)).Add(rowDefinition5);
		rowDefinition6.SetValue(RowDefinition.HeightProperty, new GridLengthTypeConverter().ConvertFromInvariantString("Auto"));
		((DefinitionCollection<RowDefinition>)grid13.GetValue(Grid.RowDefinitionsProperty)).Add(rowDefinition6);
		rowDefinition7.SetValue(RowDefinition.HeightProperty, new GridLengthTypeConverter().ConvertFromInvariantString("1"));
		((DefinitionCollection<RowDefinition>)grid13.GetValue(Grid.RowDefinitionsProperty)).Add(rowDefinition7);
		rowDefinition8.SetValue(RowDefinition.HeightProperty, new GridLengthTypeConverter().ConvertFromInvariantString("Auto"));
		((DefinitionCollection<RowDefinition>)grid13.GetValue(Grid.RowDefinitionsProperty)).Add(rowDefinition8);
		rowDefinition9.SetValue(RowDefinition.HeightProperty, new GridLengthTypeConverter().ConvertFromInvariantString("1"));
		((DefinitionCollection<RowDefinition>)grid13.GetValue(Grid.RowDefinitionsProperty)).Add(rowDefinition9);
		rowDefinition10.SetValue(RowDefinition.HeightProperty, new GridLengthTypeConverter().ConvertFromInvariantString("Auto"));
		((DefinitionCollection<RowDefinition>)grid13.GetValue(Grid.RowDefinitionsProperty)).Add(rowDefinition10);
		rowDefinition11.SetValue(RowDefinition.HeightProperty, new GridLengthTypeConverter().ConvertFromInvariantString("1"));
		((DefinitionCollection<RowDefinition>)grid13.GetValue(Grid.RowDefinitionsProperty)).Add(rowDefinition11);
		rowDefinition12.SetValue(RowDefinition.HeightProperty, new GridLengthTypeConverter().ConvertFromInvariantString("Auto"));
		((DefinitionCollection<RowDefinition>)grid13.GetValue(Grid.RowDefinitionsProperty)).Add(rowDefinition12);
		rowDefinition13.SetValue(RowDefinition.HeightProperty, new GridLengthTypeConverter().ConvertFromInvariantString("Auto"));
		((DefinitionCollection<RowDefinition>)grid13.GetValue(Grid.RowDefinitionsProperty)).Add(rowDefinition13);
		grid.SetValue(Grid.RowProperty, 2);
		grid.SetValue(Grid.ColumnSpanProperty, 2);
		staticResourceExtension2.Key = "LineColor";
		XamlServiceProvider xamlServiceProvider2 = new XamlServiceProvider();
		Type typeFromHandle3 = typeof(IProvideValueTarget);
		object[] array2 = new object[0 + 4];
		array2[0] = grid;
		array2[1] = grid13;
		array2[2] = stackLayout;
		array2[3] = timeZoneUpdateView;
		object service2;
		xamlServiceProvider2.Add(typeFromHandle3, service2 = new SimpleValueTargetProvider(array2, VisualElement.BackgroundColorProperty, nameScope));
		xamlServiceProvider2.Add(typeof(IReferenceProvider), service2);
		Type typeFromHandle4 = typeof(IXamlTypeResolver);
		XmlNamespaceResolver xmlNamespaceResolver2 = new XmlNamespaceResolver();
		xmlNamespaceResolver2.Add("", "http://xamarin.com/schemas/2014/forms");
		xmlNamespaceResolver2.Add("x", "http://schemas.microsoft.com/winfx/2009/xaml");
		xmlNamespaceResolver2.Add("calx", "clr-namespace:Caliburn.Micro.Xamarin.Forms;assembly=Caliburn.Micro.Platform.Xamarin.Forms");
		xmlNamespaceResolver2.Add("renderer", "clr-namespace:NHL.Views.Renderer");
		xmlNamespaceResolver2.Add("effect", "clr-namespace:NHL.Views.Effect");
		xamlServiceProvider2.Add(typeFromHandle4, new XamlTypeResolver(xmlNamespaceResolver2, typeof(TimeZoneUpdateView).GetTypeInfo().Assembly));
		xamlServiceProvider2.Add(typeof(IXmlLineInfoProvider), new XmlLineInfoProvider(new XmlLineInfo(63, 56)));
		object obj2 = ((IMarkupExtension)staticResourceExtension2).ProvideValue((IServiceProvider)xamlServiceProvider2);
		grid.BackgroundColor = (Color)obj2;
		VisualDiagnostics.RegisterSourceInfo(obj2, new Uri("Views/TimeZoneUpdateView.xaml", UriKind.RelativeOrAbsolute), 63, 56);
		grid.SetValue(Grid.RowSpacingProperty, 0.0);
		grid.SetValue(Grid.ColumnSpacingProperty, 0.0);
		grid13.Children.Add(grid);
		VisualDiagnostics.RegisterSourceInfo(grid, new Uri("Views/TimeZoneUpdateView.xaml", UriKind.RelativeOrAbsolute), 63, 18);
		grid2.SetValue(Grid.RowProperty, 4);
		grid2.SetValue(Grid.ColumnSpanProperty, 2);
		staticResourceExtension3.Key = "LineColor";
		XamlServiceProvider xamlServiceProvider3 = new XamlServiceProvider();
		Type typeFromHandle5 = typeof(IProvideValueTarget);
		object[] array3 = new object[0 + 4];
		array3[0] = grid2;
		array3[1] = grid13;
		array3[2] = stackLayout;
		array3[3] = timeZoneUpdateView;
		object service3;
		xamlServiceProvider3.Add(typeFromHandle5, service3 = new SimpleValueTargetProvider(array3, VisualElement.BackgroundColorProperty, nameScope));
		xamlServiceProvider3.Add(typeof(IReferenceProvider), service3);
		Type typeFromHandle6 = typeof(IXamlTypeResolver);
		XmlNamespaceResolver xmlNamespaceResolver3 = new XmlNamespaceResolver();
		xmlNamespaceResolver3.Add("", "http://xamarin.com/schemas/2014/forms");
		xmlNamespaceResolver3.Add("x", "http://schemas.microsoft.com/winfx/2009/xaml");
		xmlNamespaceResolver3.Add("calx", "clr-namespace:Caliburn.Micro.Xamarin.Forms;assembly=Caliburn.Micro.Platform.Xamarin.Forms");
		xmlNamespaceResolver3.Add("renderer", "clr-namespace:NHL.Views.Renderer");
		xmlNamespaceResolver3.Add("effect", "clr-namespace:NHL.Views.Effect");
		xamlServiceProvider3.Add(typeFromHandle6, new XamlTypeResolver(xmlNamespaceResolver3, typeof(TimeZoneUpdateView).GetTypeInfo().Assembly));
		xamlServiceProvider3.Add(typeof(IXmlLineInfoProvider), new XmlLineInfoProvider(new XmlLineInfo(64, 56)));
		object obj3 = ((IMarkupExtension)staticResourceExtension3).ProvideValue((IServiceProvider)xamlServiceProvider3);
		grid2.BackgroundColor = (Color)obj3;
		VisualDiagnostics.RegisterSourceInfo(obj3, new Uri("Views/TimeZoneUpdateView.xaml", UriKind.RelativeOrAbsolute), 64, 56);
		grid2.SetValue(Grid.RowSpacingProperty, 0.0);
		grid2.SetValue(Grid.ColumnSpacingProperty, 0.0);
		grid13.Children.Add(grid2);
		VisualDiagnostics.RegisterSourceInfo(grid2, new Uri("Views/TimeZoneUpdateView.xaml", UriKind.RelativeOrAbsolute), 64, 18);
		grid3.SetValue(Grid.RowProperty, 6);
		grid3.SetValue(Grid.ColumnSpanProperty, 2);
		staticResourceExtension4.Key = "LineColor";
		XamlServiceProvider xamlServiceProvider4 = new XamlServiceProvider();
		Type typeFromHandle7 = typeof(IProvideValueTarget);
		object[] array4 = new object[0 + 4];
		array4[0] = grid3;
		array4[1] = grid13;
		array4[2] = stackLayout;
		array4[3] = timeZoneUpdateView;
		object service4;
		xamlServiceProvider4.Add(typeFromHandle7, service4 = new SimpleValueTargetProvider(array4, VisualElement.BackgroundColorProperty, nameScope));
		xamlServiceProvider4.Add(typeof(IReferenceProvider), service4);
		Type typeFromHandle8 = typeof(IXamlTypeResolver);
		XmlNamespaceResolver xmlNamespaceResolver4 = new XmlNamespaceResolver();
		xmlNamespaceResolver4.Add("", "http://xamarin.com/schemas/2014/forms");
		xmlNamespaceResolver4.Add("x", "http://schemas.microsoft.com/winfx/2009/xaml");
		xmlNamespaceResolver4.Add("calx", "clr-namespace:Caliburn.Micro.Xamarin.Forms;assembly=Caliburn.Micro.Platform.Xamarin.Forms");
		xmlNamespaceResolver4.Add("renderer", "clr-namespace:NHL.Views.Renderer");
		xmlNamespaceResolver4.Add("effect", "clr-namespace:NHL.Views.Effect");
		xamlServiceProvider4.Add(typeFromHandle8, new XamlTypeResolver(xmlNamespaceResolver4, typeof(TimeZoneUpdateView).GetTypeInfo().Assembly));
		xamlServiceProvider4.Add(typeof(IXmlLineInfoProvider), new XmlLineInfoProvider(new XmlLineInfo(65, 56)));
		object obj4 = ((IMarkupExtension)staticResourceExtension4).ProvideValue((IServiceProvider)xamlServiceProvider4);
		grid3.BackgroundColor = (Color)obj4;
		VisualDiagnostics.RegisterSourceInfo(obj4, new Uri("Views/TimeZoneUpdateView.xaml", UriKind.RelativeOrAbsolute), 65, 56);
		grid3.SetValue(Grid.RowSpacingProperty, 0.0);
		grid3.SetValue(Grid.ColumnSpacingProperty, 0.0);
		grid13.Children.Add(grid3);
		VisualDiagnostics.RegisterSourceInfo(grid3, new Uri("Views/TimeZoneUpdateView.xaml", UriKind.RelativeOrAbsolute), 65, 18);
		grid4.SetValue(Grid.RowProperty, 8);
		grid4.SetValue(Grid.ColumnSpanProperty, 2);
		staticResourceExtension5.Key = "LineColor";
		XamlServiceProvider xamlServiceProvider5 = new XamlServiceProvider();
		Type typeFromHandle9 = typeof(IProvideValueTarget);
		object[] array5 = new object[0 + 4];
		array5[0] = grid4;
		array5[1] = grid13;
		array5[2] = stackLayout;
		array5[3] = timeZoneUpdateView;
		object service5;
		xamlServiceProvider5.Add(typeFromHandle9, service5 = new SimpleValueTargetProvider(array5, VisualElement.BackgroundColorProperty, nameScope));
		xamlServiceProvider5.Add(typeof(IReferenceProvider), service5);
		Type typeFromHandle10 = typeof(IXamlTypeResolver);
		XmlNamespaceResolver xmlNamespaceResolver5 = new XmlNamespaceResolver();
		xmlNamespaceResolver5.Add("", "http://xamarin.com/schemas/2014/forms");
		xmlNamespaceResolver5.Add("x", "http://schemas.microsoft.com/winfx/2009/xaml");
		xmlNamespaceResolver5.Add("calx", "clr-namespace:Caliburn.Micro.Xamarin.Forms;assembly=Caliburn.Micro.Platform.Xamarin.Forms");
		xmlNamespaceResolver5.Add("renderer", "clr-namespace:NHL.Views.Renderer");
		xmlNamespaceResolver5.Add("effect", "clr-namespace:NHL.Views.Effect");
		xamlServiceProvider5.Add(typeFromHandle10, new XamlTypeResolver(xmlNamespaceResolver5, typeof(TimeZoneUpdateView).GetTypeInfo().Assembly));
		xamlServiceProvider5.Add(typeof(IXmlLineInfoProvider), new XmlLineInfoProvider(new XmlLineInfo(66, 56)));
		object obj5 = ((IMarkupExtension)staticResourceExtension5).ProvideValue((IServiceProvider)xamlServiceProvider5);
		grid4.BackgroundColor = (Color)obj5;
		VisualDiagnostics.RegisterSourceInfo(obj5, new Uri("Views/TimeZoneUpdateView.xaml", UriKind.RelativeOrAbsolute), 66, 56);
		grid4.SetValue(Grid.RowSpacingProperty, 0.0);
		grid4.SetValue(Grid.ColumnSpacingProperty, 0.0);
		grid13.Children.Add(grid4);
		VisualDiagnostics.RegisterSourceInfo(grid4, new Uri("Views/TimeZoneUpdateView.xaml", UriKind.RelativeOrAbsolute), 66, 18);
		grid5.SetValue(Grid.RowProperty, 10);
		grid5.SetValue(Grid.ColumnSpanProperty, 2);
		staticResourceExtension6.Key = "LineColor";
		XamlServiceProvider xamlServiceProvider6 = new XamlServiceProvider();
		Type typeFromHandle11 = typeof(IProvideValueTarget);
		object[] array6 = new object[0 + 4];
		array6[0] = grid5;
		array6[1] = grid13;
		array6[2] = stackLayout;
		array6[3] = timeZoneUpdateView;
		object service6;
		xamlServiceProvider6.Add(typeFromHandle11, service6 = new SimpleValueTargetProvider(array6, VisualElement.BackgroundColorProperty, nameScope));
		xamlServiceProvider6.Add(typeof(IReferenceProvider), service6);
		Type typeFromHandle12 = typeof(IXamlTypeResolver);
		XmlNamespaceResolver xmlNamespaceResolver6 = new XmlNamespaceResolver();
		xmlNamespaceResolver6.Add("", "http://xamarin.com/schemas/2014/forms");
		xmlNamespaceResolver6.Add("x", "http://schemas.microsoft.com/winfx/2009/xaml");
		xmlNamespaceResolver6.Add("calx", "clr-namespace:Caliburn.Micro.Xamarin.Forms;assembly=Caliburn.Micro.Platform.Xamarin.Forms");
		xmlNamespaceResolver6.Add("renderer", "clr-namespace:NHL.Views.Renderer");
		xmlNamespaceResolver6.Add("effect", "clr-namespace:NHL.Views.Effect");
		xamlServiceProvider6.Add(typeFromHandle12, new XamlTypeResolver(xmlNamespaceResolver6, typeof(TimeZoneUpdateView).GetTypeInfo().Assembly));
		xamlServiceProvider6.Add(typeof(IXmlLineInfoProvider), new XmlLineInfoProvider(new XmlLineInfo(67, 57)));
		object obj6 = ((IMarkupExtension)staticResourceExtension6).ProvideValue((IServiceProvider)xamlServiceProvider6);
		grid5.BackgroundColor = (Color)obj6;
		VisualDiagnostics.RegisterSourceInfo(obj6, new Uri("Views/TimeZoneUpdateView.xaml", UriKind.RelativeOrAbsolute), 67, 57);
		grid5.SetValue(Grid.RowSpacingProperty, 0.0);
		grid5.SetValue(Grid.ColumnSpacingProperty, 0.0);
		grid13.Children.Add(grid5);
		VisualDiagnostics.RegisterSourceInfo(grid5, new Uri("Views/TimeZoneUpdateView.xaml", UriKind.RelativeOrAbsolute), 67, 18);
		grid6.SetValue(Grid.RowProperty, 1);
		grid6.SetValue(Grid.ColumnSpanProperty, 2);
		grid6.SetValue(VisualElement.BackgroundColorProperty, Color.White);
		grid6.SetValue(Grid.RowSpacingProperty, 0.0);
		grid6.SetValue(Grid.ColumnSpacingProperty, 0.0);
		grid13.Children.Add(grid6);
		VisualDiagnostics.RegisterSourceInfo(grid6, new Uri("Views/TimeZoneUpdateView.xaml", UriKind.RelativeOrAbsolute), 70, 18);
		grid7.SetValue(Grid.RowProperty, 3);
		grid7.SetValue(Grid.ColumnSpanProperty, 2);
		grid7.SetValue(VisualElement.BackgroundColorProperty, Color.White);
		grid7.SetValue(Grid.RowSpacingProperty, 0.0);
		grid7.SetValue(Grid.ColumnSpacingProperty, 0.0);
		grid13.Children.Add(grid7);
		VisualDiagnostics.RegisterSourceInfo(grid7, new Uri("Views/TimeZoneUpdateView.xaml", UriKind.RelativeOrAbsolute), 71, 18);
		grid8.SetValue(Grid.RowProperty, 5);
		grid8.SetValue(Grid.ColumnSpanProperty, 2);
		grid8.SetValue(VisualElement.BackgroundColorProperty, Color.White);
		grid8.SetValue(Grid.RowSpacingProperty, 0.0);
		grid8.SetValue(Grid.ColumnSpacingProperty, 0.0);
		grid13.Children.Add(grid8);
		VisualDiagnostics.RegisterSourceInfo(grid8, new Uri("Views/TimeZoneUpdateView.xaml", UriKind.RelativeOrAbsolute), 72, 18);
		grid9.SetValue(Grid.RowProperty, 7);
		grid9.SetValue(Grid.ColumnSpanProperty, 2);
		grid9.SetValue(VisualElement.BackgroundColorProperty, Color.White);
		grid9.SetValue(Grid.RowSpacingProperty, 0.0);
		grid9.SetValue(Grid.ColumnSpacingProperty, 0.0);
		grid13.Children.Add(grid9);
		VisualDiagnostics.RegisterSourceInfo(grid9, new Uri("Views/TimeZoneUpdateView.xaml", UriKind.RelativeOrAbsolute), 73, 18);
		grid10.SetValue(Grid.RowProperty, 9);
		grid10.SetValue(Grid.ColumnSpanProperty, 2);
		grid10.SetValue(VisualElement.BackgroundColorProperty, Color.White);
		grid10.SetValue(Grid.RowSpacingProperty, 0.0);
		grid10.SetValue(Grid.ColumnSpacingProperty, 0.0);
		grid13.Children.Add(grid10);
		VisualDiagnostics.RegisterSourceInfo(grid10, new Uri("Views/TimeZoneUpdateView.xaml", UriKind.RelativeOrAbsolute), 74, 18);
		grid11.SetValue(Grid.RowProperty, 11);
		grid11.SetValue(Grid.ColumnSpanProperty, 2);
		grid11.SetValue(VisualElement.BackgroundColorProperty, Color.White);
		grid11.SetValue(Grid.RowSpacingProperty, 0.0);
		grid11.SetValue(Grid.ColumnSpacingProperty, 0.0);
		grid13.Children.Add(grid11);
		VisualDiagnostics.RegisterSourceInfo(grid11, new Uri("Views/TimeZoneUpdateView.xaml", UriKind.RelativeOrAbsolute), 75, 18);
		grid12.SetValue(Grid.RowProperty, 12);
		grid12.SetValue(Grid.ColumnSpanProperty, 2);
		grid12.SetValue(VisualElement.BackgroundColorProperty, Color.White);
		grid12.SetValue(Grid.RowSpacingProperty, 0.0);
		grid12.SetValue(Grid.ColumnSpacingProperty, 0.0);
		grid13.Children.Add(grid12);
		VisualDiagnostics.RegisterSourceInfo(grid12, new Uri("Views/TimeZoneUpdateView.xaml", UriKind.RelativeOrAbsolute), 76, 18);
		label.SetValue(Grid.RowProperty, 1);
		label.SetValue(Xamarin.Forms.View.MarginProperty, new Thickness(10.0, 5.0, 0.0, 5.0));
		label.SetValue(Label.TextProperty, "起床");
		BindableProperty fontSizeProperty = Label.FontSizeProperty;
		FontSizeConverter fontSizeConverter = new FontSizeConverter();
		XamlServiceProvider xamlServiceProvider7 = new XamlServiceProvider();
		Type typeFromHandle13 = typeof(IProvideValueTarget);
		object[] array7 = new object[0 + 4];
		array7[0] = label;
		array7[1] = grid13;
		array7[2] = stackLayout;
		array7[3] = timeZoneUpdateView;
		object service7;
		xamlServiceProvider7.Add(typeFromHandle13, service7 = new SimpleValueTargetProvider(array7, Label.FontSizeProperty, nameScope));
		xamlServiceProvider7.Add(typeof(IReferenceProvider), service7);
		Type typeFromHandle14 = typeof(IXamlTypeResolver);
		XmlNamespaceResolver xmlNamespaceResolver7 = new XmlNamespaceResolver();
		xmlNamespaceResolver7.Add("", "http://xamarin.com/schemas/2014/forms");
		xmlNamespaceResolver7.Add("x", "http://schemas.microsoft.com/winfx/2009/xaml");
		xmlNamespaceResolver7.Add("calx", "clr-namespace:Caliburn.Micro.Xamarin.Forms;assembly=Caliburn.Micro.Platform.Xamarin.Forms");
		xmlNamespaceResolver7.Add("renderer", "clr-namespace:NHL.Views.Renderer");
		xmlNamespaceResolver7.Add("effect", "clr-namespace:NHL.Views.Effect");
		xamlServiceProvider7.Add(typeFromHandle14, new XamlTypeResolver(xmlNamespaceResolver7, typeof(TimeZoneUpdateView).GetTypeInfo().Assembly));
		xamlServiceProvider7.Add(typeof(IXmlLineInfoProvider), new XmlLineInfoProvider(new XmlLineInfo(79, 65)));
		label.SetValue(fontSizeProperty, ((IExtendedTypeConverter)fontSizeConverter).ConvertFromInvariantString("Large", (IServiceProvider)xamlServiceProvider7));
		label.SetValue(Xamarin.Forms.View.HorizontalOptionsProperty, LayoutOptions.Start);
		label.Effects.Add(fixedFontSizeLabelEffect);
		VisualDiagnostics.RegisterSourceInfo(fixedFontSizeLabelEffect, new Uri("Views/TimeZoneUpdateView.xaml", UriKind.RelativeOrAbsolute), 81, 26);
		grid13.Children.Add(label);
		VisualDiagnostics.RegisterSourceInfo(label, new Uri("Views/TimeZoneUpdateView.xaml", UriKind.RelativeOrAbsolute), 79, 18);
		label2.SetValue(Grid.RowProperty, 3);
		label2.SetValue(Xamarin.Forms.View.MarginProperty, new Thickness(10.0, 5.0, 0.0, 5.0));
		label2.SetValue(Label.TextProperty, "朝食");
		BindableProperty fontSizeProperty2 = Label.FontSizeProperty;
		FontSizeConverter fontSizeConverter2 = new FontSizeConverter();
		XamlServiceProvider xamlServiceProvider8 = new XamlServiceProvider();
		Type typeFromHandle15 = typeof(IProvideValueTarget);
		object[] array8 = new object[0 + 4];
		array8[0] = label2;
		array8[1] = grid13;
		array8[2] = stackLayout;
		array8[3] = timeZoneUpdateView;
		object service8;
		xamlServiceProvider8.Add(typeFromHandle15, service8 = new SimpleValueTargetProvider(array8, Label.FontSizeProperty, nameScope));
		xamlServiceProvider8.Add(typeof(IReferenceProvider), service8);
		Type typeFromHandle16 = typeof(IXamlTypeResolver);
		XmlNamespaceResolver xmlNamespaceResolver8 = new XmlNamespaceResolver();
		xmlNamespaceResolver8.Add("", "http://xamarin.com/schemas/2014/forms");
		xmlNamespaceResolver8.Add("x", "http://schemas.microsoft.com/winfx/2009/xaml");
		xmlNamespaceResolver8.Add("calx", "clr-namespace:Caliburn.Micro.Xamarin.Forms;assembly=Caliburn.Micro.Platform.Xamarin.Forms");
		xmlNamespaceResolver8.Add("renderer", "clr-namespace:NHL.Views.Renderer");
		xmlNamespaceResolver8.Add("effect", "clr-namespace:NHL.Views.Effect");
		xamlServiceProvider8.Add(typeFromHandle16, new XamlTypeResolver(xmlNamespaceResolver8, typeof(TimeZoneUpdateView).GetTypeInfo().Assembly));
		xamlServiceProvider8.Add(typeof(IXmlLineInfoProvider), new XmlLineInfoProvider(new XmlLineInfo(84, 65)));
		label2.SetValue(fontSizeProperty2, ((IExtendedTypeConverter)fontSizeConverter2).ConvertFromInvariantString("Large", (IServiceProvider)xamlServiceProvider8));
		label2.SetValue(Xamarin.Forms.View.HorizontalOptionsProperty, LayoutOptions.Start);
		label2.Effects.Add(fixedFontSizeLabelEffect2);
		VisualDiagnostics.RegisterSourceInfo(fixedFontSizeLabelEffect2, new Uri("Views/TimeZoneUpdateView.xaml", UriKind.RelativeOrAbsolute), 86, 26);
		grid13.Children.Add(label2);
		VisualDiagnostics.RegisterSourceInfo(label2, new Uri("Views/TimeZoneUpdateView.xaml", UriKind.RelativeOrAbsolute), 84, 18);
		label3.SetValue(Grid.RowProperty, 5);
		label3.SetValue(Xamarin.Forms.View.MarginProperty, new Thickness(10.0, 5.0, 0.0, 5.0));
		label3.SetValue(Label.TextProperty, "昼食");
		BindableProperty fontSizeProperty3 = Label.FontSizeProperty;
		FontSizeConverter fontSizeConverter3 = new FontSizeConverter();
		XamlServiceProvider xamlServiceProvider9 = new XamlServiceProvider();
		Type typeFromHandle17 = typeof(IProvideValueTarget);
		object[] array9 = new object[0 + 4];
		array9[0] = label3;
		array9[1] = grid13;
		array9[2] = stackLayout;
		array9[3] = timeZoneUpdateView;
		object service9;
		xamlServiceProvider9.Add(typeFromHandle17, service9 = new SimpleValueTargetProvider(array9, Label.FontSizeProperty, nameScope));
		xamlServiceProvider9.Add(typeof(IReferenceProvider), service9);
		Type typeFromHandle18 = typeof(IXamlTypeResolver);
		XmlNamespaceResolver xmlNamespaceResolver9 = new XmlNamespaceResolver();
		xmlNamespaceResolver9.Add("", "http://xamarin.com/schemas/2014/forms");
		xmlNamespaceResolver9.Add("x", "http://schemas.microsoft.com/winfx/2009/xaml");
		xmlNamespaceResolver9.Add("calx", "clr-namespace:Caliburn.Micro.Xamarin.Forms;assembly=Caliburn.Micro.Platform.Xamarin.Forms");
		xmlNamespaceResolver9.Add("renderer", "clr-namespace:NHL.Views.Renderer");
		xmlNamespaceResolver9.Add("effect", "clr-namespace:NHL.Views.Effect");
		xamlServiceProvider9.Add(typeFromHandle18, new XamlTypeResolver(xmlNamespaceResolver9, typeof(TimeZoneUpdateView).GetTypeInfo().Assembly));
		xamlServiceProvider9.Add(typeof(IXmlLineInfoProvider), new XmlLineInfoProvider(new XmlLineInfo(89, 65)));
		label3.SetValue(fontSizeProperty3, ((IExtendedTypeConverter)fontSizeConverter3).ConvertFromInvariantString("Large", (IServiceProvider)xamlServiceProvider9));
		label3.SetValue(Xamarin.Forms.View.HorizontalOptionsProperty, LayoutOptions.Start);
		label3.Effects.Add(fixedFontSizeLabelEffect3);
		VisualDiagnostics.RegisterSourceInfo(fixedFontSizeLabelEffect3, new Uri("Views/TimeZoneUpdateView.xaml", UriKind.RelativeOrAbsolute), 91, 26);
		grid13.Children.Add(label3);
		VisualDiagnostics.RegisterSourceInfo(label3, new Uri("Views/TimeZoneUpdateView.xaml", UriKind.RelativeOrAbsolute), 89, 18);
		label4.SetValue(Grid.RowProperty, 7);
		label4.SetValue(Xamarin.Forms.View.MarginProperty, new Thickness(10.0, 5.0, 0.0, 5.0));
		label4.SetValue(Label.TextProperty, "夕食");
		BindableProperty fontSizeProperty4 = Label.FontSizeProperty;
		FontSizeConverter fontSizeConverter4 = new FontSizeConverter();
		XamlServiceProvider xamlServiceProvider10 = new XamlServiceProvider();
		Type typeFromHandle19 = typeof(IProvideValueTarget);
		object[] array10 = new object[0 + 4];
		array10[0] = label4;
		array10[1] = grid13;
		array10[2] = stackLayout;
		array10[3] = timeZoneUpdateView;
		object service10;
		xamlServiceProvider10.Add(typeFromHandle19, service10 = new SimpleValueTargetProvider(array10, Label.FontSizeProperty, nameScope));
		xamlServiceProvider10.Add(typeof(IReferenceProvider), service10);
		Type typeFromHandle20 = typeof(IXamlTypeResolver);
		XmlNamespaceResolver xmlNamespaceResolver10 = new XmlNamespaceResolver();
		xmlNamespaceResolver10.Add("", "http://xamarin.com/schemas/2014/forms");
		xmlNamespaceResolver10.Add("x", "http://schemas.microsoft.com/winfx/2009/xaml");
		xmlNamespaceResolver10.Add("calx", "clr-namespace:Caliburn.Micro.Xamarin.Forms;assembly=Caliburn.Micro.Platform.Xamarin.Forms");
		xmlNamespaceResolver10.Add("renderer", "clr-namespace:NHL.Views.Renderer");
		xmlNamespaceResolver10.Add("effect", "clr-namespace:NHL.Views.Effect");
		xamlServiceProvider10.Add(typeFromHandle20, new XamlTypeResolver(xmlNamespaceResolver10, typeof(TimeZoneUpdateView).GetTypeInfo().Assembly));
		xamlServiceProvider10.Add(typeof(IXmlLineInfoProvider), new XmlLineInfoProvider(new XmlLineInfo(94, 65)));
		label4.SetValue(fontSizeProperty4, ((IExtendedTypeConverter)fontSizeConverter4).ConvertFromInvariantString("Large", (IServiceProvider)xamlServiceProvider10));
		label4.SetValue(Xamarin.Forms.View.HorizontalOptionsProperty, LayoutOptions.Start);
		label4.Effects.Add(fixedFontSizeLabelEffect4);
		VisualDiagnostics.RegisterSourceInfo(fixedFontSizeLabelEffect4, new Uri("Views/TimeZoneUpdateView.xaml", UriKind.RelativeOrAbsolute), 96, 26);
		grid13.Children.Add(label4);
		VisualDiagnostics.RegisterSourceInfo(label4, new Uri("Views/TimeZoneUpdateView.xaml", UriKind.RelativeOrAbsolute), 94, 18);
		label5.SetValue(Grid.RowProperty, 9);
		label5.SetValue(Xamarin.Forms.View.MarginProperty, new Thickness(10.0, 5.0, 0.0, 5.0));
		label5.SetValue(Label.TextProperty, "就寝");
		BindableProperty fontSizeProperty5 = Label.FontSizeProperty;
		FontSizeConverter fontSizeConverter5 = new FontSizeConverter();
		XamlServiceProvider xamlServiceProvider11 = new XamlServiceProvider();
		Type typeFromHandle21 = typeof(IProvideValueTarget);
		object[] array11 = new object[0 + 4];
		array11[0] = label5;
		array11[1] = grid13;
		array11[2] = stackLayout;
		array11[3] = timeZoneUpdateView;
		object service11;
		xamlServiceProvider11.Add(typeFromHandle21, service11 = new SimpleValueTargetProvider(array11, Label.FontSizeProperty, nameScope));
		xamlServiceProvider11.Add(typeof(IReferenceProvider), service11);
		Type typeFromHandle22 = typeof(IXamlTypeResolver);
		XmlNamespaceResolver xmlNamespaceResolver11 = new XmlNamespaceResolver();
		xmlNamespaceResolver11.Add("", "http://xamarin.com/schemas/2014/forms");
		xmlNamespaceResolver11.Add("x", "http://schemas.microsoft.com/winfx/2009/xaml");
		xmlNamespaceResolver11.Add("calx", "clr-namespace:Caliburn.Micro.Xamarin.Forms;assembly=Caliburn.Micro.Platform.Xamarin.Forms");
		xmlNamespaceResolver11.Add("renderer", "clr-namespace:NHL.Views.Renderer");
		xmlNamespaceResolver11.Add("effect", "clr-namespace:NHL.Views.Effect");
		xamlServiceProvider11.Add(typeFromHandle22, new XamlTypeResolver(xmlNamespaceResolver11, typeof(TimeZoneUpdateView).GetTypeInfo().Assembly));
		xamlServiceProvider11.Add(typeof(IXmlLineInfoProvider), new XmlLineInfoProvider(new XmlLineInfo(99, 65)));
		label5.SetValue(fontSizeProperty5, ((IExtendedTypeConverter)fontSizeConverter5).ConvertFromInvariantString("Large", (IServiceProvider)xamlServiceProvider11));
		label5.SetValue(Xamarin.Forms.View.HorizontalOptionsProperty, LayoutOptions.Start);
		label5.Effects.Add(fixedFontSizeLabelEffect5);
		VisualDiagnostics.RegisterSourceInfo(fixedFontSizeLabelEffect5, new Uri("Views/TimeZoneUpdateView.xaml", UriKind.RelativeOrAbsolute), 101, 26);
		grid13.Children.Add(label5);
		VisualDiagnostics.RegisterSourceInfo(label5, new Uri("Views/TimeZoneUpdateView.xaml", UriKind.RelativeOrAbsolute), 99, 18);
		label6.SetValue(Grid.RowProperty, 1);
		label6.SetValue(Grid.ColumnProperty, 1);
		bindingExtension.Path = "SelectedTimezone1";
		BindingBase binding = ((IMarkupExtension<BindingBase>)bindingExtension).ProvideValue((IServiceProvider)null);
		label6.SetBinding(Label.TextProperty, binding);
		BindableProperty fontSizeProperty6 = Label.FontSizeProperty;
		FontSizeConverter fontSizeConverter6 = new FontSizeConverter();
		XamlServiceProvider xamlServiceProvider12 = new XamlServiceProvider();
		Type typeFromHandle23 = typeof(IProvideValueTarget);
		object[] array12 = new object[0 + 4];
		array12[0] = label6;
		array12[1] = grid13;
		array12[2] = stackLayout;
		array12[3] = timeZoneUpdateView;
		object service12;
		xamlServiceProvider12.Add(typeFromHandle23, service12 = new SimpleValueTargetProvider(array12, Label.FontSizeProperty, nameScope));
		xamlServiceProvider12.Add(typeof(IReferenceProvider), service12);
		Type typeFromHandle24 = typeof(IXamlTypeResolver);
		XmlNamespaceResolver xmlNamespaceResolver12 = new XmlNamespaceResolver();
		xmlNamespaceResolver12.Add("", "http://xamarin.com/schemas/2014/forms");
		xmlNamespaceResolver12.Add("x", "http://schemas.microsoft.com/winfx/2009/xaml");
		xmlNamespaceResolver12.Add("calx", "clr-namespace:Caliburn.Micro.Xamarin.Forms;assembly=Caliburn.Micro.Platform.Xamarin.Forms");
		xmlNamespaceResolver12.Add("renderer", "clr-namespace:NHL.Views.Renderer");
		xmlNamespaceResolver12.Add("effect", "clr-namespace:NHL.Views.Effect");
		xamlServiceProvider12.Add(typeFromHandle24, new XamlTypeResolver(xmlNamespaceResolver12, typeof(TimeZoneUpdateView).GetTypeInfo().Assembly));
		xamlServiceProvider12.Add(typeof(IXmlLineInfoProvider), new XmlLineInfoProvider(new XmlLineInfo(106, 88)));
		label6.SetValue(fontSizeProperty6, ((IExtendedTypeConverter)fontSizeConverter6).ConvertFromInvariantString("Large", (IServiceProvider)xamlServiceProvider12));
		label6.SetValue(Xamarin.Forms.View.HorizontalOptionsProperty, LayoutOptions.EndAndExpand);
		label6.SetValue(Xamarin.Forms.View.VerticalOptionsProperty, LayoutOptions.CenterAndExpand);
		label6.SetValue(Xamarin.Forms.View.MarginProperty, new Thickness(8.0, 0.0, 12.0, 0.0));
		label6.Effects.Add(fixedFontSizeLabelEffect6);
		VisualDiagnostics.RegisterSourceInfo(fixedFontSizeLabelEffect6, new Uri("Views/TimeZoneUpdateView.xaml", UriKind.RelativeOrAbsolute), 108, 26);
		grid13.Children.Add(label6);
		VisualDiagnostics.RegisterSourceInfo(label6, new Uri("Views/TimeZoneUpdateView.xaml", UriKind.RelativeOrAbsolute), 106, 18);
		label7.SetValue(Grid.RowProperty, 3);
		label7.SetValue(Grid.ColumnProperty, 1);
		bindingExtension2.Path = "SelectedTimezone2";
		BindingBase binding2 = ((IMarkupExtension<BindingBase>)bindingExtension2).ProvideValue((IServiceProvider)null);
		label7.SetBinding(Label.TextProperty, binding2);
		BindableProperty fontSizeProperty7 = Label.FontSizeProperty;
		FontSizeConverter fontSizeConverter7 = new FontSizeConverter();
		XamlServiceProvider xamlServiceProvider13 = new XamlServiceProvider();
		Type typeFromHandle25 = typeof(IProvideValueTarget);
		object[] array13 = new object[0 + 4];
		array13[0] = label7;
		array13[1] = grid13;
		array13[2] = stackLayout;
		array13[3] = timeZoneUpdateView;
		object service13;
		xamlServiceProvider13.Add(typeFromHandle25, service13 = new SimpleValueTargetProvider(array13, Label.FontSizeProperty, nameScope));
		xamlServiceProvider13.Add(typeof(IReferenceProvider), service13);
		Type typeFromHandle26 = typeof(IXamlTypeResolver);
		XmlNamespaceResolver xmlNamespaceResolver13 = new XmlNamespaceResolver();
		xmlNamespaceResolver13.Add("", "http://xamarin.com/schemas/2014/forms");
		xmlNamespaceResolver13.Add("x", "http://schemas.microsoft.com/winfx/2009/xaml");
		xmlNamespaceResolver13.Add("calx", "clr-namespace:Caliburn.Micro.Xamarin.Forms;assembly=Caliburn.Micro.Platform.Xamarin.Forms");
		xmlNamespaceResolver13.Add("renderer", "clr-namespace:NHL.Views.Renderer");
		xmlNamespaceResolver13.Add("effect", "clr-namespace:NHL.Views.Effect");
		xamlServiceProvider13.Add(typeFromHandle26, new XamlTypeResolver(xmlNamespaceResolver13, typeof(TimeZoneUpdateView).GetTypeInfo().Assembly));
		xamlServiceProvider13.Add(typeof(IXmlLineInfoProvider), new XmlLineInfoProvider(new XmlLineInfo(111, 88)));
		label7.SetValue(fontSizeProperty7, ((IExtendedTypeConverter)fontSizeConverter7).ConvertFromInvariantString("Large", (IServiceProvider)xamlServiceProvider13));
		label7.SetValue(Xamarin.Forms.View.HorizontalOptionsProperty, LayoutOptions.EndAndExpand);
		label7.SetValue(Xamarin.Forms.View.VerticalOptionsProperty, LayoutOptions.CenterAndExpand);
		label7.SetValue(Xamarin.Forms.View.MarginProperty, new Thickness(8.0, 0.0, 12.0, 0.0));
		label7.Effects.Add(fixedFontSizeLabelEffect7);
		VisualDiagnostics.RegisterSourceInfo(fixedFontSizeLabelEffect7, new Uri("Views/TimeZoneUpdateView.xaml", UriKind.RelativeOrAbsolute), 113, 26);
		grid13.Children.Add(label7);
		VisualDiagnostics.RegisterSourceInfo(label7, new Uri("Views/TimeZoneUpdateView.xaml", UriKind.RelativeOrAbsolute), 111, 18);
		label8.SetValue(Grid.RowProperty, 5);
		label8.SetValue(Grid.ColumnProperty, 1);
		bindingExtension3.Path = "SelectedTimezone4";
		BindingBase binding3 = ((IMarkupExtension<BindingBase>)bindingExtension3).ProvideValue((IServiceProvider)null);
		label8.SetBinding(Label.TextProperty, binding3);
		BindableProperty fontSizeProperty8 = Label.FontSizeProperty;
		FontSizeConverter fontSizeConverter8 = new FontSizeConverter();
		XamlServiceProvider xamlServiceProvider14 = new XamlServiceProvider();
		Type typeFromHandle27 = typeof(IProvideValueTarget);
		object[] array14 = new object[0 + 4];
		array14[0] = label8;
		array14[1] = grid13;
		array14[2] = stackLayout;
		array14[3] = timeZoneUpdateView;
		object service14;
		xamlServiceProvider14.Add(typeFromHandle27, service14 = new SimpleValueTargetProvider(array14, Label.FontSizeProperty, nameScope));
		xamlServiceProvider14.Add(typeof(IReferenceProvider), service14);
		Type typeFromHandle28 = typeof(IXamlTypeResolver);
		XmlNamespaceResolver xmlNamespaceResolver14 = new XmlNamespaceResolver();
		xmlNamespaceResolver14.Add("", "http://xamarin.com/schemas/2014/forms");
		xmlNamespaceResolver14.Add("x", "http://schemas.microsoft.com/winfx/2009/xaml");
		xmlNamespaceResolver14.Add("calx", "clr-namespace:Caliburn.Micro.Xamarin.Forms;assembly=Caliburn.Micro.Platform.Xamarin.Forms");
		xmlNamespaceResolver14.Add("renderer", "clr-namespace:NHL.Views.Renderer");
		xmlNamespaceResolver14.Add("effect", "clr-namespace:NHL.Views.Effect");
		xamlServiceProvider14.Add(typeFromHandle28, new XamlTypeResolver(xmlNamespaceResolver14, typeof(TimeZoneUpdateView).GetTypeInfo().Assembly));
		xamlServiceProvider14.Add(typeof(IXmlLineInfoProvider), new XmlLineInfoProvider(new XmlLineInfo(116, 88)));
		label8.SetValue(fontSizeProperty8, ((IExtendedTypeConverter)fontSizeConverter8).ConvertFromInvariantString("Large", (IServiceProvider)xamlServiceProvider14));
		label8.SetValue(Xamarin.Forms.View.HorizontalOptionsProperty, LayoutOptions.EndAndExpand);
		label8.SetValue(Xamarin.Forms.View.VerticalOptionsProperty, LayoutOptions.CenterAndExpand);
		label8.SetValue(Xamarin.Forms.View.MarginProperty, new Thickness(8.0, 0.0, 12.0, 0.0));
		label8.Effects.Add(fixedFontSizeLabelEffect8);
		VisualDiagnostics.RegisterSourceInfo(fixedFontSizeLabelEffect8, new Uri("Views/TimeZoneUpdateView.xaml", UriKind.RelativeOrAbsolute), 118, 26);
		grid13.Children.Add(label8);
		VisualDiagnostics.RegisterSourceInfo(label8, new Uri("Views/TimeZoneUpdateView.xaml", UriKind.RelativeOrAbsolute), 116, 18);
		label9.SetValue(Grid.RowProperty, 7);
		label9.SetValue(Grid.ColumnProperty, 1);
		bindingExtension4.Path = "SelectedTimezone6";
		BindingBase binding4 = ((IMarkupExtension<BindingBase>)bindingExtension4).ProvideValue((IServiceProvider)null);
		label9.SetBinding(Label.TextProperty, binding4);
		BindableProperty fontSizeProperty9 = Label.FontSizeProperty;
		FontSizeConverter fontSizeConverter9 = new FontSizeConverter();
		XamlServiceProvider xamlServiceProvider15 = new XamlServiceProvider();
		Type typeFromHandle29 = typeof(IProvideValueTarget);
		object[] array15 = new object[0 + 4];
		array15[0] = label9;
		array15[1] = grid13;
		array15[2] = stackLayout;
		array15[3] = timeZoneUpdateView;
		object service15;
		xamlServiceProvider15.Add(typeFromHandle29, service15 = new SimpleValueTargetProvider(array15, Label.FontSizeProperty, nameScope));
		xamlServiceProvider15.Add(typeof(IReferenceProvider), service15);
		Type typeFromHandle30 = typeof(IXamlTypeResolver);
		XmlNamespaceResolver xmlNamespaceResolver15 = new XmlNamespaceResolver();
		xmlNamespaceResolver15.Add("", "http://xamarin.com/schemas/2014/forms");
		xmlNamespaceResolver15.Add("x", "http://schemas.microsoft.com/winfx/2009/xaml");
		xmlNamespaceResolver15.Add("calx", "clr-namespace:Caliburn.Micro.Xamarin.Forms;assembly=Caliburn.Micro.Platform.Xamarin.Forms");
		xmlNamespaceResolver15.Add("renderer", "clr-namespace:NHL.Views.Renderer");
		xmlNamespaceResolver15.Add("effect", "clr-namespace:NHL.Views.Effect");
		xamlServiceProvider15.Add(typeFromHandle30, new XamlTypeResolver(xmlNamespaceResolver15, typeof(TimeZoneUpdateView).GetTypeInfo().Assembly));
		xamlServiceProvider15.Add(typeof(IXmlLineInfoProvider), new XmlLineInfoProvider(new XmlLineInfo(121, 88)));
		label9.SetValue(fontSizeProperty9, ((IExtendedTypeConverter)fontSizeConverter9).ConvertFromInvariantString("Large", (IServiceProvider)xamlServiceProvider15));
		label9.SetValue(Xamarin.Forms.View.HorizontalOptionsProperty, LayoutOptions.EndAndExpand);
		label9.SetValue(Xamarin.Forms.View.VerticalOptionsProperty, LayoutOptions.CenterAndExpand);
		label9.SetValue(Xamarin.Forms.View.MarginProperty, new Thickness(8.0, 0.0, 12.0, 0.0));
		label9.Effects.Add(fixedFontSizeLabelEffect9);
		VisualDiagnostics.RegisterSourceInfo(fixedFontSizeLabelEffect9, new Uri("Views/TimeZoneUpdateView.xaml", UriKind.RelativeOrAbsolute), 123, 26);
		grid13.Children.Add(label9);
		VisualDiagnostics.RegisterSourceInfo(label9, new Uri("Views/TimeZoneUpdateView.xaml", UriKind.RelativeOrAbsolute), 121, 18);
		label10.SetValue(Grid.RowProperty, 9);
		label10.SetValue(Grid.ColumnProperty, 1);
		bindingExtension5.Path = "SelectedTimezone8";
		BindingBase binding5 = ((IMarkupExtension<BindingBase>)bindingExtension5).ProvideValue((IServiceProvider)null);
		label10.SetBinding(Label.TextProperty, binding5);
		BindableProperty fontSizeProperty10 = Label.FontSizeProperty;
		FontSizeConverter fontSizeConverter10 = new FontSizeConverter();
		XamlServiceProvider xamlServiceProvider16 = new XamlServiceProvider();
		Type typeFromHandle31 = typeof(IProvideValueTarget);
		object[] array16 = new object[0 + 4];
		array16[0] = label10;
		array16[1] = grid13;
		array16[2] = stackLayout;
		array16[3] = timeZoneUpdateView;
		object service16;
		xamlServiceProvider16.Add(typeFromHandle31, service16 = new SimpleValueTargetProvider(array16, Label.FontSizeProperty, nameScope));
		xamlServiceProvider16.Add(typeof(IReferenceProvider), service16);
		Type typeFromHandle32 = typeof(IXamlTypeResolver);
		XmlNamespaceResolver xmlNamespaceResolver16 = new XmlNamespaceResolver();
		xmlNamespaceResolver16.Add("", "http://xamarin.com/schemas/2014/forms");
		xmlNamespaceResolver16.Add("x", "http://schemas.microsoft.com/winfx/2009/xaml");
		xmlNamespaceResolver16.Add("calx", "clr-namespace:Caliburn.Micro.Xamarin.Forms;assembly=Caliburn.Micro.Platform.Xamarin.Forms");
		xmlNamespaceResolver16.Add("renderer", "clr-namespace:NHL.Views.Renderer");
		xmlNamespaceResolver16.Add("effect", "clr-namespace:NHL.Views.Effect");
		xamlServiceProvider16.Add(typeFromHandle32, new XamlTypeResolver(xmlNamespaceResolver16, typeof(TimeZoneUpdateView).GetTypeInfo().Assembly));
		xamlServiceProvider16.Add(typeof(IXmlLineInfoProvider), new XmlLineInfoProvider(new XmlLineInfo(126, 88)));
		label10.SetValue(fontSizeProperty10, ((IExtendedTypeConverter)fontSizeConverter10).ConvertFromInvariantString("Large", (IServiceProvider)xamlServiceProvider16));
		label10.SetValue(Xamarin.Forms.View.HorizontalOptionsProperty, LayoutOptions.EndAndExpand);
		label10.SetValue(Xamarin.Forms.View.VerticalOptionsProperty, LayoutOptions.CenterAndExpand);
		label10.SetValue(Xamarin.Forms.View.MarginProperty, new Thickness(8.0, 0.0, 12.0, 0.0));
		label10.Effects.Add(fixedFontSizeLabelEffect10);
		VisualDiagnostics.RegisterSourceInfo(fixedFontSizeLabelEffect10, new Uri("Views/TimeZoneUpdateView.xaml", UriKind.RelativeOrAbsolute), 128, 26);
		grid13.Children.Add(label10);
		VisualDiagnostics.RegisterSourceInfo(label10, new Uri("Views/TimeZoneUpdateView.xaml", UriKind.RelativeOrAbsolute), 126, 18);
		timeZonePicker.SetValue(Grid.RowProperty, 1);
		timeZonePicker.SetValue(Grid.ColumnProperty, 1);
		bindingExtension6.Mode = BindingMode.TwoWay;
		bindingExtension6.Path = "SelectedTimezone1";
		BindingBase binding6 = ((IMarkupExtension<BindingBase>)bindingExtension6).ProvideValue((IServiceProvider)null);
		timeZonePicker.SetBinding(TimeZonePicker.SelectedValueProperty, binding6);
		timeZonePicker.SetValue(VisualElement.BackgroundColorProperty, Color.Transparent);
		timeZonePicker.SetValue(Xamarin.Forms.View.MarginProperty, new Thickness(0.0, 0.0, 8.0, 0.0));
		bindingExtension7.Path = "IsNetworkEnabled";
		BindingBase binding7 = ((IMarkupExtension<BindingBase>)bindingExtension7).ProvideValue((IServiceProvider)null);
		timeZonePicker.SetBinding(VisualElement.IsVisibleProperty, binding7);
		timeZonePicker.Effects.Add(fixedFontSizeTextBoxEffect);
		VisualDiagnostics.RegisterSourceInfo(fixedFontSizeTextBoxEffect, new Uri("Views/TimeZoneUpdateView.xaml", UriKind.RelativeOrAbsolute), 140, 26);
		grid13.Children.Add(timeZonePicker);
		VisualDiagnostics.RegisterSourceInfo(timeZonePicker, new Uri("Views/TimeZoneUpdateView.xaml", UriKind.RelativeOrAbsolute), 133, 18);
		timeZonePicker2.SetValue(Grid.RowProperty, 3);
		timeZonePicker2.SetValue(Grid.ColumnProperty, 1);
		bindingExtension8.Mode = BindingMode.TwoWay;
		bindingExtension8.Path = "SelectedTimezone2";
		BindingBase binding8 = ((IMarkupExtension<BindingBase>)bindingExtension8).ProvideValue((IServiceProvider)null);
		timeZonePicker2.SetBinding(TimeZonePicker.SelectedValueProperty, binding8);
		timeZonePicker2.SetValue(VisualElement.BackgroundColorProperty, Color.Transparent);
		timeZonePicker2.SetValue(Xamarin.Forms.View.MarginProperty, new Thickness(0.0, 0.0, 8.0, 0.0));
		bindingExtension9.Path = "IsNetworkEnabled";
		BindingBase binding9 = ((IMarkupExtension<BindingBase>)bindingExtension9).ProvideValue((IServiceProvider)null);
		timeZonePicker2.SetBinding(VisualElement.IsVisibleProperty, binding9);
		timeZonePicker2.Effects.Add(fixedFontSizeTextBoxEffect2);
		VisualDiagnostics.RegisterSourceInfo(fixedFontSizeTextBoxEffect2, new Uri("Views/TimeZoneUpdateView.xaml", UriKind.RelativeOrAbsolute), 150, 26);
		grid13.Children.Add(timeZonePicker2);
		VisualDiagnostics.RegisterSourceInfo(timeZonePicker2, new Uri("Views/TimeZoneUpdateView.xaml", UriKind.RelativeOrAbsolute), 143, 18);
		timeZonePicker3.SetValue(Grid.RowProperty, 5);
		timeZonePicker3.SetValue(Grid.ColumnProperty, 1);
		bindingExtension10.Mode = BindingMode.TwoWay;
		bindingExtension10.Path = "SelectedTimezone4";
		BindingBase binding10 = ((IMarkupExtension<BindingBase>)bindingExtension10).ProvideValue((IServiceProvider)null);
		timeZonePicker3.SetBinding(TimeZonePicker.SelectedValueProperty, binding10);
		timeZonePicker3.SetValue(VisualElement.BackgroundColorProperty, Color.Transparent);
		timeZonePicker3.SetValue(Xamarin.Forms.View.MarginProperty, new Thickness(0.0, 0.0, 8.0, 0.0));
		bindingExtension11.Path = "IsNetworkEnabled";
		BindingBase binding11 = ((IMarkupExtension<BindingBase>)bindingExtension11).ProvideValue((IServiceProvider)null);
		timeZonePicker3.SetBinding(VisualElement.IsVisibleProperty, binding11);
		timeZonePicker3.Effects.Add(fixedFontSizeTextBoxEffect3);
		VisualDiagnostics.RegisterSourceInfo(fixedFontSizeTextBoxEffect3, new Uri("Views/TimeZoneUpdateView.xaml", UriKind.RelativeOrAbsolute), 160, 26);
		grid13.Children.Add(timeZonePicker3);
		VisualDiagnostics.RegisterSourceInfo(timeZonePicker3, new Uri("Views/TimeZoneUpdateView.xaml", UriKind.RelativeOrAbsolute), 153, 18);
		timeZonePicker4.SetValue(Grid.RowProperty, 7);
		timeZonePicker4.SetValue(Grid.ColumnProperty, 1);
		bindingExtension12.Mode = BindingMode.TwoWay;
		bindingExtension12.Path = "SelectedTimezone6";
		BindingBase binding12 = ((IMarkupExtension<BindingBase>)bindingExtension12).ProvideValue((IServiceProvider)null);
		timeZonePicker4.SetBinding(TimeZonePicker.SelectedValueProperty, binding12);
		timeZonePicker4.SetValue(VisualElement.BackgroundColorProperty, Color.Transparent);
		timeZonePicker4.SetValue(Xamarin.Forms.View.MarginProperty, new Thickness(0.0, 0.0, 8.0, 0.0));
		bindingExtension13.Path = "IsNetworkEnabled";
		BindingBase binding13 = ((IMarkupExtension<BindingBase>)bindingExtension13).ProvideValue((IServiceProvider)null);
		timeZonePicker4.SetBinding(VisualElement.IsVisibleProperty, binding13);
		timeZonePicker4.Effects.Add(fixedFontSizeTextBoxEffect4);
		VisualDiagnostics.RegisterSourceInfo(fixedFontSizeTextBoxEffect4, new Uri("Views/TimeZoneUpdateView.xaml", UriKind.RelativeOrAbsolute), 170, 26);
		grid13.Children.Add(timeZonePicker4);
		VisualDiagnostics.RegisterSourceInfo(timeZonePicker4, new Uri("Views/TimeZoneUpdateView.xaml", UriKind.RelativeOrAbsolute), 163, 18);
		timeZonePicker5.SetValue(Grid.RowProperty, 9);
		timeZonePicker5.SetValue(Grid.ColumnProperty, 1);
		bindingExtension14.Mode = BindingMode.TwoWay;
		bindingExtension14.Path = "SelectedTimezone8";
		BindingBase binding14 = ((IMarkupExtension<BindingBase>)bindingExtension14).ProvideValue((IServiceProvider)null);
		timeZonePicker5.SetBinding(TimeZonePicker.SelectedValueProperty, binding14);
		timeZonePicker5.SetValue(VisualElement.BackgroundColorProperty, Color.Transparent);
		timeZonePicker5.SetValue(Xamarin.Forms.View.MarginProperty, new Thickness(0.0, 0.0, 8.0, 0.0));
		bindingExtension15.Path = "IsNetworkEnabled";
		BindingBase binding15 = ((IMarkupExtension<BindingBase>)bindingExtension15).ProvideValue((IServiceProvider)null);
		timeZonePicker5.SetBinding(VisualElement.IsVisibleProperty, binding15);
		timeZonePicker5.Effects.Add(fixedFontSizeTextBoxEffect5);
		VisualDiagnostics.RegisterSourceInfo(fixedFontSizeTextBoxEffect5, new Uri("Views/TimeZoneUpdateView.xaml", UriKind.RelativeOrAbsolute), 180, 26);
		grid13.Children.Add(timeZonePicker5);
		VisualDiagnostics.RegisterSourceInfo(timeZonePicker5, new Uri("Views/TimeZoneUpdateView.xaml", UriKind.RelativeOrAbsolute), 173, 18);
		label11.SetValue(Grid.RowProperty, 11);
		label11.SetValue(Grid.ColumnSpanProperty, 2);
		label11.SetValue(Label.TextProperty, "※血糖は起床時間を基準に日付の表示が切り替わります。");
		label11.SetValue(Label.TextColorProperty, Color.Gray);
		label11.SetValue(Xamarin.Forms.View.MarginProperty, new Thickness(10.0, 0.0, 0.0, 0.0));
		label11.Effects.Add(fixedFontSizeLabelEffect11);
		VisualDiagnostics.RegisterSourceInfo(fixedFontSizeLabelEffect11, new Uri("Views/TimeZoneUpdateView.xaml", UriKind.RelativeOrAbsolute), 186, 26);
		grid13.Children.Add(label11);
		VisualDiagnostics.RegisterSourceInfo(label11, new Uri("Views/TimeZoneUpdateView.xaml", UriKind.RelativeOrAbsolute), 184, 18);
		button.SetValue(Grid.RowProperty, 12);
		button.SetValue(Grid.ColumnProperty, 0);
		button.SetValue(Grid.ColumnSpanProperty, 2);
		button.SetValue(Xamarin.Forms.View.MarginProperty, new Thickness(10.0, 10.0, 10.0, 5.0));
		button.SetValue(Button.TextProperty, "保存");
		button.SetValue(Message.AttachProperty, "Update");
		button.SetValue(Xamarin.Forms.View.HorizontalOptionsProperty, LayoutOptions.FillAndExpand);
		button.SetValue(Button.TextColorProperty, Color.White);
		staticResourceExtension7.Key = "ButtonColor";
		XamlServiceProvider xamlServiceProvider17 = new XamlServiceProvider();
		Type typeFromHandle33 = typeof(IProvideValueTarget);
		object[] array17 = new object[0 + 4];
		array17[0] = button;
		array17[1] = grid13;
		array17[2] = stackLayout;
		array17[3] = timeZoneUpdateView;
		object service17;
		xamlServiceProvider17.Add(typeFromHandle33, service17 = new SimpleValueTargetProvider(array17, VisualElement.BackgroundColorProperty, nameScope));
		xamlServiceProvider17.Add(typeof(IReferenceProvider), service17);
		Type typeFromHandle34 = typeof(IXamlTypeResolver);
		XmlNamespaceResolver xmlNamespaceResolver17 = new XmlNamespaceResolver();
		xmlNamespaceResolver17.Add("", "http://xamarin.com/schemas/2014/forms");
		xmlNamespaceResolver17.Add("x", "http://schemas.microsoft.com/winfx/2009/xaml");
		xmlNamespaceResolver17.Add("calx", "clr-namespace:Caliburn.Micro.Xamarin.Forms;assembly=Caliburn.Micro.Platform.Xamarin.Forms");
		xmlNamespaceResolver17.Add("renderer", "clr-namespace:NHL.Views.Renderer");
		xmlNamespaceResolver17.Add("effect", "clr-namespace:NHL.Views.Effect");
		xamlServiceProvider17.Add(typeFromHandle34, new XamlTypeResolver(xmlNamespaceResolver17, typeof(TimeZoneUpdateView).GetTypeInfo().Assembly));
		xamlServiceProvider17.Add(typeof(IXmlLineInfoProvider), new XmlLineInfoProvider(new XmlLineInfo(198, 21)));
		object obj7 = ((IMarkupExtension)staticResourceExtension7).ProvideValue((IServiceProvider)xamlServiceProvider17);
		button.BackgroundColor = (Color)obj7;
		VisualDiagnostics.RegisterSourceInfo(obj7, new Uri("Views/TimeZoneUpdateView.xaml", UriKind.RelativeOrAbsolute), 198, 21);
		bindingExtension16.Path = "IsNetworkEnabled";
		BindingBase binding16 = ((IMarkupExtension<BindingBase>)bindingExtension16).ProvideValue((IServiceProvider)null);
		button.SetBinding(VisualElement.IsEnabledProperty, binding16);
		button.Effects.Add(fixedFontSizeButtonEffect);
		VisualDiagnostics.RegisterSourceInfo(fixedFontSizeButtonEffect, new Uri("Views/TimeZoneUpdateView.xaml", UriKind.RelativeOrAbsolute), 201, 26);
		grid13.Children.Add(button);
		VisualDiagnostics.RegisterSourceInfo(button, new Uri("Views/TimeZoneUpdateView.xaml", UriKind.RelativeOrAbsolute), 191, 18);
		stackLayout.Children.Add(grid13);
		VisualDiagnostics.RegisterSourceInfo(grid13, new Uri("Views/TimeZoneUpdateView.xaml", UriKind.RelativeOrAbsolute), 42, 14);
		timeZoneUpdateView.SetValue(ContentPage.ContentProperty, stackLayout);
		VisualDiagnostics.RegisterSourceInfo(stackLayout, new Uri("Views/TimeZoneUpdateView.xaml", UriKind.RelativeOrAbsolute), 41, 10);
		VisualDiagnostics.RegisterSourceInfo(timeZoneUpdateView, new Uri("Views/TimeZoneUpdateView.xaml", UriKind.RelativeOrAbsolute), 2, 2);
	}

	private void __InitComponentRuntime()
	{
		this.LoadFromXaml(typeof(TimeZoneUpdateView));
	}
}
