using System;
using System.CodeDom.Compiler;
using System.Reflection;
using Caliburn.Micro.Xamarin.Forms;
using NHL.Views.Converters;
using NHL.Views.Effect;
using NHL.Views.Renderer;
using Xamarin.Forms;
using Xamarin.Forms.Internals;
using Xamarin.Forms.Xaml;
using Xamarin.Forms.Xaml.Diagnostics;
using Xamarin.Forms.Xaml.Internals;

namespace NHL.Views;

[XamlCompilation(XamlCompilationOptions.Compile)]
[XamlFilePath("Views/UserInfoRegistView.xaml")]
public class UserInfoRegistView : ContentPage
{
	public UserInfoRegistView()
	{
		InitializeComponent();
	}

	[GeneratedCode("Xamarin.Forms.Build.Tasks.XamlG", "2.0.0.0")]
	private void InitializeComponent()
	{
		if (ResourceLoader.CanProvideContentFor(new ResourceLoader.ResourceLoadingQuery
		{
			AssemblyName = typeof(UserInfoRegistView).GetTypeInfo().Assembly.GetName(),
			ResourcePath = "Views/UserInfoRegistView.xaml",
			Instance = this
		}))
		{
			__InitComponentRuntime();
			return;
		}
		if (XamlLoader.XamlFileProvider != null && XamlLoader.XamlFileProvider(GetType()) != null)
		{
			__InitComponentRuntime();
			return;
		}
		StaticResourceExtension staticResourceExtension = new StaticResourceExtension();
		BirthDayToBisibleConverter value = new BirthDayToBisibleConverter();
		Color color = Color.FromHex("#EFEFF4");
		Color color2 = Color.FromHex("#5B9BD5");
		Color color3 = Color.FromHex("#CFCFCF");
		Color color4 = Color.FromHex("#B4B4B4");
		ResourceDictionary resourceDictionary = new ResourceDictionary();
		ColumnDefinition columnDefinition = new ColumnDefinition();
		ColumnDefinition columnDefinition2 = new ColumnDefinition();
		RowDefinition rowDefinition = new RowDefinition();
		RowDefinition rowDefinition2 = new RowDefinition();
		RowDefinition rowDefinition3 = new RowDefinition();
		RowDefinition rowDefinition4 = new RowDefinition();
		RowDefinition rowDefinition5 = new RowDefinition();
		RowDefinition rowDefinition6 = new RowDefinition();
		RowDefinition rowDefinition7 = new RowDefinition();
		RowDefinition rowDefinition8 = new RowDefinition();
		RowDefinition rowDefinition9 = new RowDefinition();
		RowDefinition rowDefinition10 = new RowDefinition();
		RowDefinition rowDefinition11 = new RowDefinition();
		RowDefinition rowDefinition12 = new RowDefinition();
		RowDefinition rowDefinition13 = new RowDefinition();
		RowDefinition rowDefinition14 = new RowDefinition();
		RowDefinition rowDefinition15 = new RowDefinition();
		RowDefinition item = new RowDefinition();
		StaticResourceExtension staticResourceExtension2 = new StaticResourceExtension();
		Grid grid = new Grid();
		StaticResourceExtension staticResourceExtension3 = new StaticResourceExtension();
		Grid grid2 = new Grid();
		StaticResourceExtension staticResourceExtension4 = new StaticResourceExtension();
		Grid grid3 = new Grid();
		StaticResourceExtension staticResourceExtension5 = new StaticResourceExtension();
		Grid grid4 = new Grid();
		StaticResourceExtension staticResourceExtension6 = new StaticResourceExtension();
		Grid grid5 = new Grid();
		StaticResourceExtension staticResourceExtension7 = new StaticResourceExtension();
		Grid grid6 = new Grid();
		Grid grid7 = new Grid();
		Grid grid8 = new Grid();
		Grid grid9 = new Grid();
		Grid grid10 = new Grid();
		Grid grid11 = new Grid();
		Grid grid12 = new Grid();
		Grid grid13 = new Grid();
		Grid grid14 = new Grid();
		FixedFontSizeLabelEffect fixedFontSizeLabelEffect = new FixedFontSizeLabelEffect();
		Label label = new Label();
		FixedFontSizeLabelEffect fixedFontSizeLabelEffect2 = new FixedFontSizeLabelEffect();
		Label label2 = new Label();
		FixedFontSizeLabelEffect fixedFontSizeLabelEffect3 = new FixedFontSizeLabelEffect();
		Label label3 = new Label();
		FixedFontSizeLabelEffect fixedFontSizeLabelEffect4 = new FixedFontSizeLabelEffect();
		Label label4 = new Label();
		FixedFontSizeLabelEffect fixedFontSizeLabelEffect5 = new FixedFontSizeLabelEffect();
		Label label5 = new Label();
		FixedFontSizeLabelEffect fixedFontSizeLabelEffect6 = new FixedFontSizeLabelEffect();
		Label label6 = new Label();
		BindingExtension bindingExtension = new BindingExtension();
		FixedFontSizeTextBoxEffect fixedFontSizeTextBoxEffect = new FixedFontSizeTextBoxEffect();
		Entry entry = new Entry();
		BindingExtension bindingExtension2 = new BindingExtension();
		FixedFontSizeTextBoxEffect fixedFontSizeTextBoxEffect2 = new FixedFontSizeTextBoxEffect();
		Entry entry2 = new Entry();
		BindingExtension bindingExtension3 = new BindingExtension();
		BindingExtension bindingExtension4 = new BindingExtension();
		BindingExtension bindingExtension5 = new BindingExtension();
		FixedFontSizeTextBoxEffect fixedFontSizeTextBoxEffect3 = new FixedFontSizeTextBoxEffect();
		Picker picker = new Picker();
		StaticResourceExtension staticResourceExtension8 = new StaticResourceExtension();
		StaticResourceExtension staticResourceExtension9 = new StaticResourceExtension();
		BindingExtension bindingExtension6 = new BindingExtension();
		FixedFontSizeLabelEffect fixedFontSizeLabelEffect7 = new FixedFontSizeLabelEffect();
		Label label7 = new Label();
		BindingExtension bindingExtension7 = new BindingExtension();
		FixedFontSizeTextBoxEffect fixedFontSizeTextBoxEffect4 = new FixedFontSizeTextBoxEffect();
		DatePickerView datePickerView = new DatePickerView();
		BindingExtension bindingExtension8 = new BindingExtension();
		Entry entry3 = new Entry();
		BindingExtension bindingExtension9 = new BindingExtension();
		BindingExtension bindingExtension10 = new BindingExtension();
		BindingExtension bindingExtension11 = new BindingExtension();
		FixedFontSizeTextBoxEffect fixedFontSizeTextBoxEffect5 = new FixedFontSizeTextBoxEffect();
		HeightPickerView heightPickerView = new HeightPickerView();
		BindingExtension bindingExtension12 = new BindingExtension();
		FixedFontSizeTextBoxEffect fixedFontSizeTextBoxEffect6 = new FixedFontSizeTextBoxEffect();
		Entry entry4 = new Entry();
		StaticResourceExtension staticResourceExtension10 = new StaticResourceExtension();
		FixedFontSizeButtonEffect fixedFontSizeButtonEffect = new FixedFontSizeButtonEffect();
		Button button = new Button();
		StaticResourceExtension staticResourceExtension11 = new StaticResourceExtension();
		FixedFontSizeButtonEffect fixedFontSizeButtonEffect2 = new FixedFontSizeButtonEffect();
		Button button2 = new Button();
		Grid grid15 = new Grid();
		StackLayout stackLayout = new StackLayout();
		ScrollView scrollView = new ScrollView();
		UserInfoRegistView userInfoRegistView;
		NameScope nameScope = (NameScope)(NameScope.GetNameScope(userInfoRegistView = this) ?? new NameScope());
		NameScope.SetNameScope(userInfoRegistView, nameScope);
		userInfoRegistView.Resources = resourceDictionary;
		VisualDiagnostics.RegisterSourceInfo(resourceDictionary, new Uri("Views/UserInfoRegistView.xaml", UriKind.RelativeOrAbsolute), 16, 10);
		resourceDictionary.Add("BirthDayToBisibleConverter", value);
		resourceDictionary.Add("PageBackgroundColor", color);
		resourceDictionary.Add("ButtonColor", color2);
		resourceDictionary.Add("LineColor", color3);
		resourceDictionary.Add("LabelColor", color4);
		userInfoRegistView.SetValue(NavigationPage.HasBackButtonProperty, true);
		userInfoRegistView.SetValue(NavigationPage.BackButtonTitleProperty, "戻る");
		userInfoRegistView.SetValue(Page.TitleProperty, "ユーザー情報登録");
		staticResourceExtension.Key = "PageBackgroundColor";
		XamlServiceProvider xamlServiceProvider = new XamlServiceProvider();
		Type typeFromHandle = typeof(IProvideValueTarget);
		object[] array = new object[0 + 1];
		array[0] = userInfoRegistView;
		object service;
		xamlServiceProvider.Add(typeFromHandle, service = new SimpleValueTargetProvider(array, VisualElement.BackgroundColorProperty, nameScope));
		xamlServiceProvider.Add(typeof(IReferenceProvider), service);
		Type typeFromHandle2 = typeof(IXamlTypeResolver);
		XmlNamespaceResolver xmlNamespaceResolver = new XmlNamespaceResolver();
		xmlNamespaceResolver.Add("", "http://xamarin.com/schemas/2014/forms");
		xmlNamespaceResolver.Add("x", "http://schemas.microsoft.com/winfx/2009/xaml");
		xmlNamespaceResolver.Add("calx", "clr-namespace:Caliburn.Micro.Xamarin.Forms;assembly=Caliburn.Micro.Platform.Xamarin.Forms");
		xmlNamespaceResolver.Add("renderer", "clr-namespace:NHL.Views.Renderer");
		xmlNamespaceResolver.Add("converter", "clr-namespace:NHL.Views.Converters");
		xmlNamespaceResolver.Add("effect", "clr-namespace:NHL.Views.Effect");
		xamlServiceProvider.Add(typeFromHandle2, new XamlTypeResolver(xmlNamespaceResolver, typeof(UserInfoRegistView).GetTypeInfo().Assembly));
		xamlServiceProvider.Add(typeof(IXmlLineInfoProvider), new XmlLineInfoProvider(new XmlLineInfo(13, 14)));
		object obj = ((IMarkupExtension)staticResourceExtension).ProvideValue((IServiceProvider)xamlServiceProvider);
		userInfoRegistView.BackgroundColor = (Color)obj;
		VisualDiagnostics.RegisterSourceInfo(obj, new Uri("Views/UserInfoRegistView.xaml", UriKind.RelativeOrAbsolute), 13, 14);
		userInfoRegistView.Resources = resourceDictionary;
		VisualDiagnostics.RegisterSourceInfo(resourceDictionary, new Uri("Views/UserInfoRegistView.xaml", UriKind.RelativeOrAbsolute), 16, 10);
		scrollView.SetValue(Xamarin.Forms.View.VerticalOptionsProperty, LayoutOptions.FillAndExpand);
		scrollView.SetValue(Xamarin.Forms.View.HorizontalOptionsProperty, LayoutOptions.FillAndExpand);
		stackLayout.SetValue(StackLayout.OrientationProperty, StackOrientation.Vertical);
		grid15.SetValue(Grid.RowSpacingProperty, 0.0);
		columnDefinition.SetValue(ColumnDefinition.WidthProperty, new GridLengthTypeConverter().ConvertFromInvariantString("Auto"));
		((DefinitionCollection<ColumnDefinition>)grid15.GetValue(Grid.ColumnDefinitionsProperty)).Add(columnDefinition);
		columnDefinition2.SetValue(ColumnDefinition.WidthProperty, new GridLengthTypeConverter().ConvertFromInvariantString("*"));
		((DefinitionCollection<ColumnDefinition>)grid15.GetValue(Grid.ColumnDefinitionsProperty)).Add(columnDefinition2);
		rowDefinition.SetValue(RowDefinition.HeightProperty, new GridLengthTypeConverter().ConvertFromInvariantString("1"));
		((DefinitionCollection<RowDefinition>)grid15.GetValue(Grid.RowDefinitionsProperty)).Add(rowDefinition);
		rowDefinition2.SetValue(RowDefinition.HeightProperty, new GridLengthTypeConverter().ConvertFromInvariantString("Auto"));
		((DefinitionCollection<RowDefinition>)grid15.GetValue(Grid.RowDefinitionsProperty)).Add(rowDefinition2);
		rowDefinition3.SetValue(RowDefinition.HeightProperty, new GridLengthTypeConverter().ConvertFromInvariantString("1"));
		((DefinitionCollection<RowDefinition>)grid15.GetValue(Grid.RowDefinitionsProperty)).Add(rowDefinition3);
		rowDefinition4.SetValue(RowDefinition.HeightProperty, new GridLengthTypeConverter().ConvertFromInvariantString("Auto"));
		((DefinitionCollection<RowDefinition>)grid15.GetValue(Grid.RowDefinitionsProperty)).Add(rowDefinition4);
		rowDefinition5.SetValue(RowDefinition.HeightProperty, new GridLengthTypeConverter().ConvertFromInvariantString("1"));
		((DefinitionCollection<RowDefinition>)grid15.GetValue(Grid.RowDefinitionsProperty)).Add(rowDefinition5);
		rowDefinition6.SetValue(RowDefinition.HeightProperty, new GridLengthTypeConverter().ConvertFromInvariantString("Auto"));
		((DefinitionCollection<RowDefinition>)grid15.GetValue(Grid.RowDefinitionsProperty)).Add(rowDefinition6);
		rowDefinition7.SetValue(RowDefinition.HeightProperty, new GridLengthTypeConverter().ConvertFromInvariantString("1"));
		((DefinitionCollection<RowDefinition>)grid15.GetValue(Grid.RowDefinitionsProperty)).Add(rowDefinition7);
		rowDefinition8.SetValue(RowDefinition.HeightProperty, new GridLengthTypeConverter().ConvertFromInvariantString("Auto"));
		((DefinitionCollection<RowDefinition>)grid15.GetValue(Grid.RowDefinitionsProperty)).Add(rowDefinition8);
		rowDefinition9.SetValue(RowDefinition.HeightProperty, new GridLengthTypeConverter().ConvertFromInvariantString("1"));
		((DefinitionCollection<RowDefinition>)grid15.GetValue(Grid.RowDefinitionsProperty)).Add(rowDefinition9);
		rowDefinition10.SetValue(RowDefinition.HeightProperty, new GridLengthTypeConverter().ConvertFromInvariantString("Auto"));
		((DefinitionCollection<RowDefinition>)grid15.GetValue(Grid.RowDefinitionsProperty)).Add(rowDefinition10);
		rowDefinition11.SetValue(RowDefinition.HeightProperty, new GridLengthTypeConverter().ConvertFromInvariantString("1"));
		((DefinitionCollection<RowDefinition>)grid15.GetValue(Grid.RowDefinitionsProperty)).Add(rowDefinition11);
		rowDefinition12.SetValue(RowDefinition.HeightProperty, new GridLengthTypeConverter().ConvertFromInvariantString("Auto"));
		((DefinitionCollection<RowDefinition>)grid15.GetValue(Grid.RowDefinitionsProperty)).Add(rowDefinition12);
		rowDefinition13.SetValue(RowDefinition.HeightProperty, new GridLengthTypeConverter().ConvertFromInvariantString("1"));
		((DefinitionCollection<RowDefinition>)grid15.GetValue(Grid.RowDefinitionsProperty)).Add(rowDefinition13);
		rowDefinition14.SetValue(RowDefinition.HeightProperty, new GridLengthTypeConverter().ConvertFromInvariantString("Auto"));
		((DefinitionCollection<RowDefinition>)grid15.GetValue(Grid.RowDefinitionsProperty)).Add(rowDefinition14);
		rowDefinition15.SetValue(RowDefinition.HeightProperty, new GridLengthTypeConverter().ConvertFromInvariantString("Auto"));
		((DefinitionCollection<RowDefinition>)grid15.GetValue(Grid.RowDefinitionsProperty)).Add(rowDefinition15);
		((DefinitionCollection<RowDefinition>)grid15.GetValue(Grid.RowDefinitionsProperty)).Add(item);
		grid.SetValue(Grid.RowProperty, 2);
		grid.SetValue(Grid.ColumnSpanProperty, 2);
		staticResourceExtension2.Key = "LineColor";
		XamlServiceProvider xamlServiceProvider2 = new XamlServiceProvider();
		Type typeFromHandle3 = typeof(IProvideValueTarget);
		object[] array2 = new object[0 + 5];
		array2[0] = grid;
		array2[1] = grid15;
		array2[2] = stackLayout;
		array2[3] = scrollView;
		array2[4] = userInfoRegistView;
		object service2;
		xamlServiceProvider2.Add(typeFromHandle3, service2 = new SimpleValueTargetProvider(array2, VisualElement.BackgroundColorProperty, nameScope));
		xamlServiceProvider2.Add(typeof(IReferenceProvider), service2);
		Type typeFromHandle4 = typeof(IXamlTypeResolver);
		XmlNamespaceResolver xmlNamespaceResolver2 = new XmlNamespaceResolver();
		xmlNamespaceResolver2.Add("", "http://xamarin.com/schemas/2014/forms");
		xmlNamespaceResolver2.Add("x", "http://schemas.microsoft.com/winfx/2009/xaml");
		xmlNamespaceResolver2.Add("calx", "clr-namespace:Caliburn.Micro.Xamarin.Forms;assembly=Caliburn.Micro.Platform.Xamarin.Forms");
		xmlNamespaceResolver2.Add("renderer", "clr-namespace:NHL.Views.Renderer");
		xmlNamespaceResolver2.Add("converter", "clr-namespace:NHL.Views.Converters");
		xmlNamespaceResolver2.Add("effect", "clr-namespace:NHL.Views.Effect");
		xamlServiceProvider2.Add(typeFromHandle4, new XamlTypeResolver(xmlNamespaceResolver2, typeof(UserInfoRegistView).GetTypeInfo().Assembly));
		xamlServiceProvider2.Add(typeof(IXmlLineInfoProvider), new XmlLineInfoProvider(new XmlLineInfo(75, 56)));
		object obj2 = ((IMarkupExtension)staticResourceExtension2).ProvideValue((IServiceProvider)xamlServiceProvider2);
		grid.BackgroundColor = (Color)obj2;
		VisualDiagnostics.RegisterSourceInfo(obj2, new Uri("Views/UserInfoRegistView.xaml", UriKind.RelativeOrAbsolute), 75, 56);
		grid.SetValue(Grid.RowSpacingProperty, 0.0);
		grid.SetValue(Grid.ColumnSpacingProperty, 0.0);
		grid15.Children.Add(grid);
		VisualDiagnostics.RegisterSourceInfo(grid, new Uri("Views/UserInfoRegistView.xaml", UriKind.RelativeOrAbsolute), 75, 18);
		grid2.SetValue(Grid.RowProperty, 4);
		grid2.SetValue(Grid.ColumnSpanProperty, 2);
		staticResourceExtension3.Key = "LineColor";
		XamlServiceProvider xamlServiceProvider3 = new XamlServiceProvider();
		Type typeFromHandle5 = typeof(IProvideValueTarget);
		object[] array3 = new object[0 + 5];
		array3[0] = grid2;
		array3[1] = grid15;
		array3[2] = stackLayout;
		array3[3] = scrollView;
		array3[4] = userInfoRegistView;
		object service3;
		xamlServiceProvider3.Add(typeFromHandle5, service3 = new SimpleValueTargetProvider(array3, VisualElement.BackgroundColorProperty, nameScope));
		xamlServiceProvider3.Add(typeof(IReferenceProvider), service3);
		Type typeFromHandle6 = typeof(IXamlTypeResolver);
		XmlNamespaceResolver xmlNamespaceResolver3 = new XmlNamespaceResolver();
		xmlNamespaceResolver3.Add("", "http://xamarin.com/schemas/2014/forms");
		xmlNamespaceResolver3.Add("x", "http://schemas.microsoft.com/winfx/2009/xaml");
		xmlNamespaceResolver3.Add("calx", "clr-namespace:Caliburn.Micro.Xamarin.Forms;assembly=Caliburn.Micro.Platform.Xamarin.Forms");
		xmlNamespaceResolver3.Add("renderer", "clr-namespace:NHL.Views.Renderer");
		xmlNamespaceResolver3.Add("converter", "clr-namespace:NHL.Views.Converters");
		xmlNamespaceResolver3.Add("effect", "clr-namespace:NHL.Views.Effect");
		xamlServiceProvider3.Add(typeFromHandle6, new XamlTypeResolver(xmlNamespaceResolver3, typeof(UserInfoRegistView).GetTypeInfo().Assembly));
		xamlServiceProvider3.Add(typeof(IXmlLineInfoProvider), new XmlLineInfoProvider(new XmlLineInfo(76, 56)));
		object obj3 = ((IMarkupExtension)staticResourceExtension3).ProvideValue((IServiceProvider)xamlServiceProvider3);
		grid2.BackgroundColor = (Color)obj3;
		VisualDiagnostics.RegisterSourceInfo(obj3, new Uri("Views/UserInfoRegistView.xaml", UriKind.RelativeOrAbsolute), 76, 56);
		grid2.SetValue(Grid.RowSpacingProperty, 0.0);
		grid2.SetValue(Grid.ColumnSpacingProperty, 0.0);
		grid15.Children.Add(grid2);
		VisualDiagnostics.RegisterSourceInfo(grid2, new Uri("Views/UserInfoRegistView.xaml", UriKind.RelativeOrAbsolute), 76, 18);
		grid3.SetValue(Grid.RowProperty, 6);
		grid3.SetValue(Grid.ColumnSpanProperty, 2);
		staticResourceExtension4.Key = "LineColor";
		XamlServiceProvider xamlServiceProvider4 = new XamlServiceProvider();
		Type typeFromHandle7 = typeof(IProvideValueTarget);
		object[] array4 = new object[0 + 5];
		array4[0] = grid3;
		array4[1] = grid15;
		array4[2] = stackLayout;
		array4[3] = scrollView;
		array4[4] = userInfoRegistView;
		object service4;
		xamlServiceProvider4.Add(typeFromHandle7, service4 = new SimpleValueTargetProvider(array4, VisualElement.BackgroundColorProperty, nameScope));
		xamlServiceProvider4.Add(typeof(IReferenceProvider), service4);
		Type typeFromHandle8 = typeof(IXamlTypeResolver);
		XmlNamespaceResolver xmlNamespaceResolver4 = new XmlNamespaceResolver();
		xmlNamespaceResolver4.Add("", "http://xamarin.com/schemas/2014/forms");
		xmlNamespaceResolver4.Add("x", "http://schemas.microsoft.com/winfx/2009/xaml");
		xmlNamespaceResolver4.Add("calx", "clr-namespace:Caliburn.Micro.Xamarin.Forms;assembly=Caliburn.Micro.Platform.Xamarin.Forms");
		xmlNamespaceResolver4.Add("renderer", "clr-namespace:NHL.Views.Renderer");
		xmlNamespaceResolver4.Add("converter", "clr-namespace:NHL.Views.Converters");
		xmlNamespaceResolver4.Add("effect", "clr-namespace:NHL.Views.Effect");
		xamlServiceProvider4.Add(typeFromHandle8, new XamlTypeResolver(xmlNamespaceResolver4, typeof(UserInfoRegistView).GetTypeInfo().Assembly));
		xamlServiceProvider4.Add(typeof(IXmlLineInfoProvider), new XmlLineInfoProvider(new XmlLineInfo(77, 56)));
		object obj4 = ((IMarkupExtension)staticResourceExtension4).ProvideValue((IServiceProvider)xamlServiceProvider4);
		grid3.BackgroundColor = (Color)obj4;
		VisualDiagnostics.RegisterSourceInfo(obj4, new Uri("Views/UserInfoRegistView.xaml", UriKind.RelativeOrAbsolute), 77, 56);
		grid3.SetValue(Grid.RowSpacingProperty, 0.0);
		grid3.SetValue(Grid.ColumnSpacingProperty, 0.0);
		grid15.Children.Add(grid3);
		VisualDiagnostics.RegisterSourceInfo(grid3, new Uri("Views/UserInfoRegistView.xaml", UriKind.RelativeOrAbsolute), 77, 18);
		grid4.SetValue(Grid.RowProperty, 8);
		grid4.SetValue(Grid.ColumnSpanProperty, 2);
		staticResourceExtension5.Key = "LineColor";
		XamlServiceProvider xamlServiceProvider5 = new XamlServiceProvider();
		Type typeFromHandle9 = typeof(IProvideValueTarget);
		object[] array5 = new object[0 + 5];
		array5[0] = grid4;
		array5[1] = grid15;
		array5[2] = stackLayout;
		array5[3] = scrollView;
		array5[4] = userInfoRegistView;
		object service5;
		xamlServiceProvider5.Add(typeFromHandle9, service5 = new SimpleValueTargetProvider(array5, VisualElement.BackgroundColorProperty, nameScope));
		xamlServiceProvider5.Add(typeof(IReferenceProvider), service5);
		Type typeFromHandle10 = typeof(IXamlTypeResolver);
		XmlNamespaceResolver xmlNamespaceResolver5 = new XmlNamespaceResolver();
		xmlNamespaceResolver5.Add("", "http://xamarin.com/schemas/2014/forms");
		xmlNamespaceResolver5.Add("x", "http://schemas.microsoft.com/winfx/2009/xaml");
		xmlNamespaceResolver5.Add("calx", "clr-namespace:Caliburn.Micro.Xamarin.Forms;assembly=Caliburn.Micro.Platform.Xamarin.Forms");
		xmlNamespaceResolver5.Add("renderer", "clr-namespace:NHL.Views.Renderer");
		xmlNamespaceResolver5.Add("converter", "clr-namespace:NHL.Views.Converters");
		xmlNamespaceResolver5.Add("effect", "clr-namespace:NHL.Views.Effect");
		xamlServiceProvider5.Add(typeFromHandle10, new XamlTypeResolver(xmlNamespaceResolver5, typeof(UserInfoRegistView).GetTypeInfo().Assembly));
		xamlServiceProvider5.Add(typeof(IXmlLineInfoProvider), new XmlLineInfoProvider(new XmlLineInfo(78, 56)));
		object obj5 = ((IMarkupExtension)staticResourceExtension5).ProvideValue((IServiceProvider)xamlServiceProvider5);
		grid4.BackgroundColor = (Color)obj5;
		VisualDiagnostics.RegisterSourceInfo(obj5, new Uri("Views/UserInfoRegistView.xaml", UriKind.RelativeOrAbsolute), 78, 56);
		grid4.SetValue(Grid.RowSpacingProperty, 0.0);
		grid4.SetValue(Grid.ColumnSpacingProperty, 0.0);
		grid15.Children.Add(grid4);
		VisualDiagnostics.RegisterSourceInfo(grid4, new Uri("Views/UserInfoRegistView.xaml", UriKind.RelativeOrAbsolute), 78, 18);
		grid5.SetValue(Grid.RowProperty, 10);
		grid5.SetValue(Grid.ColumnSpanProperty, 2);
		staticResourceExtension6.Key = "LineColor";
		XamlServiceProvider xamlServiceProvider6 = new XamlServiceProvider();
		Type typeFromHandle11 = typeof(IProvideValueTarget);
		object[] array6 = new object[0 + 5];
		array6[0] = grid5;
		array6[1] = grid15;
		array6[2] = stackLayout;
		array6[3] = scrollView;
		array6[4] = userInfoRegistView;
		object service6;
		xamlServiceProvider6.Add(typeFromHandle11, service6 = new SimpleValueTargetProvider(array6, VisualElement.BackgroundColorProperty, nameScope));
		xamlServiceProvider6.Add(typeof(IReferenceProvider), service6);
		Type typeFromHandle12 = typeof(IXamlTypeResolver);
		XmlNamespaceResolver xmlNamespaceResolver6 = new XmlNamespaceResolver();
		xmlNamespaceResolver6.Add("", "http://xamarin.com/schemas/2014/forms");
		xmlNamespaceResolver6.Add("x", "http://schemas.microsoft.com/winfx/2009/xaml");
		xmlNamespaceResolver6.Add("calx", "clr-namespace:Caliburn.Micro.Xamarin.Forms;assembly=Caliburn.Micro.Platform.Xamarin.Forms");
		xmlNamespaceResolver6.Add("renderer", "clr-namespace:NHL.Views.Renderer");
		xmlNamespaceResolver6.Add("converter", "clr-namespace:NHL.Views.Converters");
		xmlNamespaceResolver6.Add("effect", "clr-namespace:NHL.Views.Effect");
		xamlServiceProvider6.Add(typeFromHandle12, new XamlTypeResolver(xmlNamespaceResolver6, typeof(UserInfoRegistView).GetTypeInfo().Assembly));
		xamlServiceProvider6.Add(typeof(IXmlLineInfoProvider), new XmlLineInfoProvider(new XmlLineInfo(79, 57)));
		object obj6 = ((IMarkupExtension)staticResourceExtension6).ProvideValue((IServiceProvider)xamlServiceProvider6);
		grid5.BackgroundColor = (Color)obj6;
		VisualDiagnostics.RegisterSourceInfo(obj6, new Uri("Views/UserInfoRegistView.xaml", UriKind.RelativeOrAbsolute), 79, 57);
		grid5.SetValue(Grid.RowSpacingProperty, 0.0);
		grid5.SetValue(Grid.ColumnSpacingProperty, 0.0);
		grid15.Children.Add(grid5);
		VisualDiagnostics.RegisterSourceInfo(grid5, new Uri("Views/UserInfoRegistView.xaml", UriKind.RelativeOrAbsolute), 79, 18);
		grid6.SetValue(Grid.RowProperty, 12);
		grid6.SetValue(Grid.ColumnSpanProperty, 2);
		staticResourceExtension7.Key = "LineColor";
		XamlServiceProvider xamlServiceProvider7 = new XamlServiceProvider();
		Type typeFromHandle13 = typeof(IProvideValueTarget);
		object[] array7 = new object[0 + 5];
		array7[0] = grid6;
		array7[1] = grid15;
		array7[2] = stackLayout;
		array7[3] = scrollView;
		array7[4] = userInfoRegistView;
		object service7;
		xamlServiceProvider7.Add(typeFromHandle13, service7 = new SimpleValueTargetProvider(array7, VisualElement.BackgroundColorProperty, nameScope));
		xamlServiceProvider7.Add(typeof(IReferenceProvider), service7);
		Type typeFromHandle14 = typeof(IXamlTypeResolver);
		XmlNamespaceResolver xmlNamespaceResolver7 = new XmlNamespaceResolver();
		xmlNamespaceResolver7.Add("", "http://xamarin.com/schemas/2014/forms");
		xmlNamespaceResolver7.Add("x", "http://schemas.microsoft.com/winfx/2009/xaml");
		xmlNamespaceResolver7.Add("calx", "clr-namespace:Caliburn.Micro.Xamarin.Forms;assembly=Caliburn.Micro.Platform.Xamarin.Forms");
		xmlNamespaceResolver7.Add("renderer", "clr-namespace:NHL.Views.Renderer");
		xmlNamespaceResolver7.Add("converter", "clr-namespace:NHL.Views.Converters");
		xmlNamespaceResolver7.Add("effect", "clr-namespace:NHL.Views.Effect");
		xamlServiceProvider7.Add(typeFromHandle14, new XamlTypeResolver(xmlNamespaceResolver7, typeof(UserInfoRegistView).GetTypeInfo().Assembly));
		xamlServiceProvider7.Add(typeof(IXmlLineInfoProvider), new XmlLineInfoProvider(new XmlLineInfo(80, 57)));
		object obj7 = ((IMarkupExtension)staticResourceExtension7).ProvideValue((IServiceProvider)xamlServiceProvider7);
		grid6.BackgroundColor = (Color)obj7;
		VisualDiagnostics.RegisterSourceInfo(obj7, new Uri("Views/UserInfoRegistView.xaml", UriKind.RelativeOrAbsolute), 80, 57);
		grid6.SetValue(Grid.RowSpacingProperty, 0.0);
		grid6.SetValue(Grid.ColumnSpacingProperty, 0.0);
		grid15.Children.Add(grid6);
		VisualDiagnostics.RegisterSourceInfo(grid6, new Uri("Views/UserInfoRegistView.xaml", UriKind.RelativeOrAbsolute), 80, 18);
		grid7.SetValue(Grid.RowProperty, 1);
		grid7.SetValue(Grid.ColumnSpanProperty, 2);
		grid7.SetValue(VisualElement.BackgroundColorProperty, Color.White);
		grid7.SetValue(Grid.RowSpacingProperty, 0.0);
		grid7.SetValue(Grid.ColumnSpacingProperty, 0.0);
		grid15.Children.Add(grid7);
		VisualDiagnostics.RegisterSourceInfo(grid7, new Uri("Views/UserInfoRegistView.xaml", UriKind.RelativeOrAbsolute), 83, 18);
		grid8.SetValue(Grid.RowProperty, 3);
		grid8.SetValue(Grid.ColumnSpanProperty, 2);
		grid8.SetValue(VisualElement.BackgroundColorProperty, Color.White);
		grid8.SetValue(Grid.RowSpacingProperty, 0.0);
		grid8.SetValue(Grid.ColumnSpacingProperty, 0.0);
		grid15.Children.Add(grid8);
		VisualDiagnostics.RegisterSourceInfo(grid8, new Uri("Views/UserInfoRegistView.xaml", UriKind.RelativeOrAbsolute), 84, 18);
		grid9.SetValue(Grid.RowProperty, 5);
		grid9.SetValue(Grid.ColumnSpanProperty, 2);
		grid9.SetValue(VisualElement.BackgroundColorProperty, Color.White);
		grid9.SetValue(Grid.RowSpacingProperty, 0.0);
		grid9.SetValue(Grid.ColumnSpacingProperty, 0.0);
		grid15.Children.Add(grid9);
		VisualDiagnostics.RegisterSourceInfo(grid9, new Uri("Views/UserInfoRegistView.xaml", UriKind.RelativeOrAbsolute), 85, 18);
		grid10.SetValue(Grid.RowProperty, 7);
		grid10.SetValue(Grid.ColumnSpanProperty, 2);
		grid10.SetValue(VisualElement.BackgroundColorProperty, Color.White);
		grid10.SetValue(Grid.RowSpacingProperty, 0.0);
		grid10.SetValue(Grid.ColumnSpacingProperty, 0.0);
		grid15.Children.Add(grid10);
		VisualDiagnostics.RegisterSourceInfo(grid10, new Uri("Views/UserInfoRegistView.xaml", UriKind.RelativeOrAbsolute), 86, 18);
		grid11.SetValue(Grid.RowProperty, 9);
		grid11.SetValue(Grid.ColumnSpanProperty, 2);
		grid11.SetValue(VisualElement.BackgroundColorProperty, Color.White);
		grid11.SetValue(Grid.RowSpacingProperty, 0.0);
		grid11.SetValue(Grid.ColumnSpacingProperty, 0.0);
		grid15.Children.Add(grid11);
		VisualDiagnostics.RegisterSourceInfo(grid11, new Uri("Views/UserInfoRegistView.xaml", UriKind.RelativeOrAbsolute), 87, 18);
		grid12.SetValue(Grid.RowProperty, 11);
		grid12.SetValue(Grid.ColumnSpanProperty, 2);
		grid12.SetValue(VisualElement.BackgroundColorProperty, Color.White);
		grid12.SetValue(Grid.RowSpacingProperty, 0.0);
		grid12.SetValue(Grid.ColumnSpacingProperty, 0.0);
		grid15.Children.Add(grid12);
		VisualDiagnostics.RegisterSourceInfo(grid12, new Uri("Views/UserInfoRegistView.xaml", UriKind.RelativeOrAbsolute), 88, 18);
		grid13.SetValue(Grid.RowProperty, 13);
		grid13.SetValue(Grid.ColumnSpanProperty, 2);
		grid13.SetValue(VisualElement.BackgroundColorProperty, Color.White);
		grid13.SetValue(Grid.RowSpacingProperty, 0.0);
		grid13.SetValue(Grid.ColumnSpacingProperty, 0.0);
		grid15.Children.Add(grid13);
		VisualDiagnostics.RegisterSourceInfo(grid13, new Uri("Views/UserInfoRegistView.xaml", UriKind.RelativeOrAbsolute), 89, 18);
		grid14.SetValue(Grid.RowProperty, 14);
		grid14.SetValue(Grid.ColumnSpanProperty, 2);
		grid14.SetValue(VisualElement.BackgroundColorProperty, Color.White);
		grid14.SetValue(Grid.RowSpacingProperty, 0.0);
		grid14.SetValue(Grid.ColumnSpacingProperty, 0.0);
		grid15.Children.Add(grid14);
		VisualDiagnostics.RegisterSourceInfo(grid14, new Uri("Views/UserInfoRegistView.xaml", UriKind.RelativeOrAbsolute), 90, 18);
		label.SetValue(Grid.RowProperty, 1);
		label.SetValue(Xamarin.Forms.View.MarginProperty, new Thickness(10.0, 5.0, 0.0, 5.0));
		label.SetValue(Label.TextProperty, "氏名");
		BindableProperty fontSizeProperty = Label.FontSizeProperty;
		FontSizeConverter fontSizeConverter = new FontSizeConverter();
		XamlServiceProvider xamlServiceProvider8 = new XamlServiceProvider();
		Type typeFromHandle15 = typeof(IProvideValueTarget);
		object[] array8 = new object[0 + 5];
		array8[0] = label;
		array8[1] = grid15;
		array8[2] = stackLayout;
		array8[3] = scrollView;
		array8[4] = userInfoRegistView;
		object service8;
		xamlServiceProvider8.Add(typeFromHandle15, service8 = new SimpleValueTargetProvider(array8, Label.FontSizeProperty, nameScope));
		xamlServiceProvider8.Add(typeof(IReferenceProvider), service8);
		Type typeFromHandle16 = typeof(IXamlTypeResolver);
		XmlNamespaceResolver xmlNamespaceResolver8 = new XmlNamespaceResolver();
		xmlNamespaceResolver8.Add("", "http://xamarin.com/schemas/2014/forms");
		xmlNamespaceResolver8.Add("x", "http://schemas.microsoft.com/winfx/2009/xaml");
		xmlNamespaceResolver8.Add("calx", "clr-namespace:Caliburn.Micro.Xamarin.Forms;assembly=Caliburn.Micro.Platform.Xamarin.Forms");
		xmlNamespaceResolver8.Add("renderer", "clr-namespace:NHL.Views.Renderer");
		xmlNamespaceResolver8.Add("converter", "clr-namespace:NHL.Views.Converters");
		xmlNamespaceResolver8.Add("effect", "clr-namespace:NHL.Views.Effect");
		xamlServiceProvider8.Add(typeFromHandle16, new XamlTypeResolver(xmlNamespaceResolver8, typeof(UserInfoRegistView).GetTypeInfo().Assembly));
		xamlServiceProvider8.Add(typeof(IXmlLineInfoProvider), new XmlLineInfoProvider(new XmlLineInfo(93, 65)));
		label.SetValue(fontSizeProperty, ((IExtendedTypeConverter)fontSizeConverter).ConvertFromInvariantString("Large", (IServiceProvider)xamlServiceProvider8));
		label.SetValue(Xamarin.Forms.View.HorizontalOptionsProperty, LayoutOptions.Start);
		label.Effects.Add(fixedFontSizeLabelEffect);
		VisualDiagnostics.RegisterSourceInfo(fixedFontSizeLabelEffect, new Uri("Views/UserInfoRegistView.xaml", UriKind.RelativeOrAbsolute), 95, 26);
		grid15.Children.Add(label);
		VisualDiagnostics.RegisterSourceInfo(label, new Uri("Views/UserInfoRegistView.xaml", UriKind.RelativeOrAbsolute), 93, 18);
		label2.SetValue(Grid.RowProperty, 3);
		label2.SetValue(Xamarin.Forms.View.MarginProperty, new Thickness(10.0, 5.0, 0.0, 5.0));
		label2.SetValue(Label.TextProperty, "氏名（カナ）");
		BindableProperty fontSizeProperty2 = Label.FontSizeProperty;
		FontSizeConverter fontSizeConverter2 = new FontSizeConverter();
		XamlServiceProvider xamlServiceProvider9 = new XamlServiceProvider();
		Type typeFromHandle17 = typeof(IProvideValueTarget);
		object[] array9 = new object[0 + 5];
		array9[0] = label2;
		array9[1] = grid15;
		array9[2] = stackLayout;
		array9[3] = scrollView;
		array9[4] = userInfoRegistView;
		object service9;
		xamlServiceProvider9.Add(typeFromHandle17, service9 = new SimpleValueTargetProvider(array9, Label.FontSizeProperty, nameScope));
		xamlServiceProvider9.Add(typeof(IReferenceProvider), service9);
		Type typeFromHandle18 = typeof(IXamlTypeResolver);
		XmlNamespaceResolver xmlNamespaceResolver9 = new XmlNamespaceResolver();
		xmlNamespaceResolver9.Add("", "http://xamarin.com/schemas/2014/forms");
		xmlNamespaceResolver9.Add("x", "http://schemas.microsoft.com/winfx/2009/xaml");
		xmlNamespaceResolver9.Add("calx", "clr-namespace:Caliburn.Micro.Xamarin.Forms;assembly=Caliburn.Micro.Platform.Xamarin.Forms");
		xmlNamespaceResolver9.Add("renderer", "clr-namespace:NHL.Views.Renderer");
		xmlNamespaceResolver9.Add("converter", "clr-namespace:NHL.Views.Converters");
		xmlNamespaceResolver9.Add("effect", "clr-namespace:NHL.Views.Effect");
		xamlServiceProvider9.Add(typeFromHandle18, new XamlTypeResolver(xmlNamespaceResolver9, typeof(UserInfoRegistView).GetTypeInfo().Assembly));
		xamlServiceProvider9.Add(typeof(IXmlLineInfoProvider), new XmlLineInfoProvider(new XmlLineInfo(98, 69)));
		label2.SetValue(fontSizeProperty2, ((IExtendedTypeConverter)fontSizeConverter2).ConvertFromInvariantString("Large", (IServiceProvider)xamlServiceProvider9));
		label2.SetValue(Xamarin.Forms.View.HorizontalOptionsProperty, LayoutOptions.Start);
		label2.Effects.Add(fixedFontSizeLabelEffect2);
		VisualDiagnostics.RegisterSourceInfo(fixedFontSizeLabelEffect2, new Uri("Views/UserInfoRegistView.xaml", UriKind.RelativeOrAbsolute), 100, 26);
		grid15.Children.Add(label2);
		VisualDiagnostics.RegisterSourceInfo(label2, new Uri("Views/UserInfoRegistView.xaml", UriKind.RelativeOrAbsolute), 98, 18);
		label3.SetValue(Grid.RowProperty, 5);
		label3.SetValue(Xamarin.Forms.View.MarginProperty, new Thickness(10.0, 5.0, 0.0, 5.0));
		label3.SetValue(Label.TextProperty, "性別");
		BindableProperty fontSizeProperty3 = Label.FontSizeProperty;
		FontSizeConverter fontSizeConverter3 = new FontSizeConverter();
		XamlServiceProvider xamlServiceProvider10 = new XamlServiceProvider();
		Type typeFromHandle19 = typeof(IProvideValueTarget);
		object[] array10 = new object[0 + 5];
		array10[0] = label3;
		array10[1] = grid15;
		array10[2] = stackLayout;
		array10[3] = scrollView;
		array10[4] = userInfoRegistView;
		object service10;
		xamlServiceProvider10.Add(typeFromHandle19, service10 = new SimpleValueTargetProvider(array10, Label.FontSizeProperty, nameScope));
		xamlServiceProvider10.Add(typeof(IReferenceProvider), service10);
		Type typeFromHandle20 = typeof(IXamlTypeResolver);
		XmlNamespaceResolver xmlNamespaceResolver10 = new XmlNamespaceResolver();
		xmlNamespaceResolver10.Add("", "http://xamarin.com/schemas/2014/forms");
		xmlNamespaceResolver10.Add("x", "http://schemas.microsoft.com/winfx/2009/xaml");
		xmlNamespaceResolver10.Add("calx", "clr-namespace:Caliburn.Micro.Xamarin.Forms;assembly=Caliburn.Micro.Platform.Xamarin.Forms");
		xmlNamespaceResolver10.Add("renderer", "clr-namespace:NHL.Views.Renderer");
		xmlNamespaceResolver10.Add("converter", "clr-namespace:NHL.Views.Converters");
		xmlNamespaceResolver10.Add("effect", "clr-namespace:NHL.Views.Effect");
		xamlServiceProvider10.Add(typeFromHandle20, new XamlTypeResolver(xmlNamespaceResolver10, typeof(UserInfoRegistView).GetTypeInfo().Assembly));
		xamlServiceProvider10.Add(typeof(IXmlLineInfoProvider), new XmlLineInfoProvider(new XmlLineInfo(103, 65)));
		label3.SetValue(fontSizeProperty3, ((IExtendedTypeConverter)fontSizeConverter3).ConvertFromInvariantString("Large", (IServiceProvider)xamlServiceProvider10));
		label3.SetValue(Xamarin.Forms.View.HorizontalOptionsProperty, LayoutOptions.Start);
		label3.Effects.Add(fixedFontSizeLabelEffect3);
		VisualDiagnostics.RegisterSourceInfo(fixedFontSizeLabelEffect3, new Uri("Views/UserInfoRegistView.xaml", UriKind.RelativeOrAbsolute), 105, 26);
		grid15.Children.Add(label3);
		VisualDiagnostics.RegisterSourceInfo(label3, new Uri("Views/UserInfoRegistView.xaml", UriKind.RelativeOrAbsolute), 103, 18);
		label4.SetValue(Grid.RowProperty, 7);
		label4.SetValue(Xamarin.Forms.View.MarginProperty, new Thickness(10.0, 5.0, 0.0, 5.0));
		label4.SetValue(Label.TextProperty, "生年月日");
		BindableProperty fontSizeProperty4 = Label.FontSizeProperty;
		FontSizeConverter fontSizeConverter4 = new FontSizeConverter();
		XamlServiceProvider xamlServiceProvider11 = new XamlServiceProvider();
		Type typeFromHandle21 = typeof(IProvideValueTarget);
		object[] array11 = new object[0 + 5];
		array11[0] = label4;
		array11[1] = grid15;
		array11[2] = stackLayout;
		array11[3] = scrollView;
		array11[4] = userInfoRegistView;
		object service11;
		xamlServiceProvider11.Add(typeFromHandle21, service11 = new SimpleValueTargetProvider(array11, Label.FontSizeProperty, nameScope));
		xamlServiceProvider11.Add(typeof(IReferenceProvider), service11);
		Type typeFromHandle22 = typeof(IXamlTypeResolver);
		XmlNamespaceResolver xmlNamespaceResolver11 = new XmlNamespaceResolver();
		xmlNamespaceResolver11.Add("", "http://xamarin.com/schemas/2014/forms");
		xmlNamespaceResolver11.Add("x", "http://schemas.microsoft.com/winfx/2009/xaml");
		xmlNamespaceResolver11.Add("calx", "clr-namespace:Caliburn.Micro.Xamarin.Forms;assembly=Caliburn.Micro.Platform.Xamarin.Forms");
		xmlNamespaceResolver11.Add("renderer", "clr-namespace:NHL.Views.Renderer");
		xmlNamespaceResolver11.Add("converter", "clr-namespace:NHL.Views.Converters");
		xmlNamespaceResolver11.Add("effect", "clr-namespace:NHL.Views.Effect");
		xamlServiceProvider11.Add(typeFromHandle22, new XamlTypeResolver(xmlNamespaceResolver11, typeof(UserInfoRegistView).GetTypeInfo().Assembly));
		xamlServiceProvider11.Add(typeof(IXmlLineInfoProvider), new XmlLineInfoProvider(new XmlLineInfo(108, 67)));
		label4.SetValue(fontSizeProperty4, ((IExtendedTypeConverter)fontSizeConverter4).ConvertFromInvariantString("Large", (IServiceProvider)xamlServiceProvider11));
		label4.SetValue(Xamarin.Forms.View.HorizontalOptionsProperty, LayoutOptions.Start);
		label4.Effects.Add(fixedFontSizeLabelEffect4);
		VisualDiagnostics.RegisterSourceInfo(fixedFontSizeLabelEffect4, new Uri("Views/UserInfoRegistView.xaml", UriKind.RelativeOrAbsolute), 110, 26);
		grid15.Children.Add(label4);
		VisualDiagnostics.RegisterSourceInfo(label4, new Uri("Views/UserInfoRegistView.xaml", UriKind.RelativeOrAbsolute), 108, 18);
		label5.SetValue(Grid.RowProperty, 9);
		label5.SetValue(Xamarin.Forms.View.MarginProperty, new Thickness(10.0, 5.0, 0.0, 5.0));
		label5.SetValue(Label.TextProperty, "身長(㎝)");
		BindableProperty fontSizeProperty5 = Label.FontSizeProperty;
		FontSizeConverter fontSizeConverter5 = new FontSizeConverter();
		XamlServiceProvider xamlServiceProvider12 = new XamlServiceProvider();
		Type typeFromHandle23 = typeof(IProvideValueTarget);
		object[] array12 = new object[0 + 5];
		array12[0] = label5;
		array12[1] = grid15;
		array12[2] = stackLayout;
		array12[3] = scrollView;
		array12[4] = userInfoRegistView;
		object service12;
		xamlServiceProvider12.Add(typeFromHandle23, service12 = new SimpleValueTargetProvider(array12, Label.FontSizeProperty, nameScope));
		xamlServiceProvider12.Add(typeof(IReferenceProvider), service12);
		Type typeFromHandle24 = typeof(IXamlTypeResolver);
		XmlNamespaceResolver xmlNamespaceResolver12 = new XmlNamespaceResolver();
		xmlNamespaceResolver12.Add("", "http://xamarin.com/schemas/2014/forms");
		xmlNamespaceResolver12.Add("x", "http://schemas.microsoft.com/winfx/2009/xaml");
		xmlNamespaceResolver12.Add("calx", "clr-namespace:Caliburn.Micro.Xamarin.Forms;assembly=Caliburn.Micro.Platform.Xamarin.Forms");
		xmlNamespaceResolver12.Add("renderer", "clr-namespace:NHL.Views.Renderer");
		xmlNamespaceResolver12.Add("converter", "clr-namespace:NHL.Views.Converters");
		xmlNamespaceResolver12.Add("effect", "clr-namespace:NHL.Views.Effect");
		xamlServiceProvider12.Add(typeFromHandle24, new XamlTypeResolver(xmlNamespaceResolver12, typeof(UserInfoRegistView).GetTypeInfo().Assembly));
		xamlServiceProvider12.Add(typeof(IXmlLineInfoProvider), new XmlLineInfoProvider(new XmlLineInfo(113, 68)));
		label5.SetValue(fontSizeProperty5, ((IExtendedTypeConverter)fontSizeConverter5).ConvertFromInvariantString("Large", (IServiceProvider)xamlServiceProvider12));
		label5.SetValue(Xamarin.Forms.View.HorizontalOptionsProperty, LayoutOptions.Start);
		label5.Effects.Add(fixedFontSizeLabelEffect5);
		VisualDiagnostics.RegisterSourceInfo(fixedFontSizeLabelEffect5, new Uri("Views/UserInfoRegistView.xaml", UriKind.RelativeOrAbsolute), 115, 26);
		grid15.Children.Add(label5);
		VisualDiagnostics.RegisterSourceInfo(label5, new Uri("Views/UserInfoRegistView.xaml", UriKind.RelativeOrAbsolute), 113, 18);
		label6.SetValue(Grid.RowProperty, 11);
		label6.SetValue(Xamarin.Forms.View.MarginProperty, new Thickness(10.0, 5.0, 0.0, 5.0));
		label6.SetValue(Label.TextProperty, "体重(㎏)");
		BindableProperty fontSizeProperty6 = Label.FontSizeProperty;
		FontSizeConverter fontSizeConverter6 = new FontSizeConverter();
		XamlServiceProvider xamlServiceProvider13 = new XamlServiceProvider();
		Type typeFromHandle25 = typeof(IProvideValueTarget);
		object[] array13 = new object[0 + 5];
		array13[0] = label6;
		array13[1] = grid15;
		array13[2] = stackLayout;
		array13[3] = scrollView;
		array13[4] = userInfoRegistView;
		object service13;
		xamlServiceProvider13.Add(typeFromHandle25, service13 = new SimpleValueTargetProvider(array13, Label.FontSizeProperty, nameScope));
		xamlServiceProvider13.Add(typeof(IReferenceProvider), service13);
		Type typeFromHandle26 = typeof(IXamlTypeResolver);
		XmlNamespaceResolver xmlNamespaceResolver13 = new XmlNamespaceResolver();
		xmlNamespaceResolver13.Add("", "http://xamarin.com/schemas/2014/forms");
		xmlNamespaceResolver13.Add("x", "http://schemas.microsoft.com/winfx/2009/xaml");
		xmlNamespaceResolver13.Add("calx", "clr-namespace:Caliburn.Micro.Xamarin.Forms;assembly=Caliburn.Micro.Platform.Xamarin.Forms");
		xmlNamespaceResolver13.Add("renderer", "clr-namespace:NHL.Views.Renderer");
		xmlNamespaceResolver13.Add("converter", "clr-namespace:NHL.Views.Converters");
		xmlNamespaceResolver13.Add("effect", "clr-namespace:NHL.Views.Effect");
		xamlServiceProvider13.Add(typeFromHandle26, new XamlTypeResolver(xmlNamespaceResolver13, typeof(UserInfoRegistView).GetTypeInfo().Assembly));
		xamlServiceProvider13.Add(typeof(IXmlLineInfoProvider), new XmlLineInfoProvider(new XmlLineInfo(118, 69)));
		label6.SetValue(fontSizeProperty6, ((IExtendedTypeConverter)fontSizeConverter6).ConvertFromInvariantString("Large", (IServiceProvider)xamlServiceProvider13));
		label6.SetValue(Xamarin.Forms.View.HorizontalOptionsProperty, LayoutOptions.Start);
		label6.Effects.Add(fixedFontSizeLabelEffect6);
		VisualDiagnostics.RegisterSourceInfo(fixedFontSizeLabelEffect6, new Uri("Views/UserInfoRegistView.xaml", UriKind.RelativeOrAbsolute), 120, 26);
		grid15.Children.Add(label6);
		VisualDiagnostics.RegisterSourceInfo(label6, new Uri("Views/UserInfoRegistView.xaml", UriKind.RelativeOrAbsolute), 118, 18);
		entry.SetValue(Grid.RowProperty, 1);
		entry.SetValue(Grid.ColumnProperty, 1);
		entry.SetValue(Xamarin.Forms.View.MarginProperty, new Thickness(0.0, 5.0, 10.0, 5.0));
		BindableProperty fontSizeProperty7 = Entry.FontSizeProperty;
		FontSizeConverter fontSizeConverter7 = new FontSizeConverter();
		XamlServiceProvider xamlServiceProvider14 = new XamlServiceProvider();
		Type typeFromHandle27 = typeof(IProvideValueTarget);
		object[] array14 = new object[0 + 5];
		array14[0] = entry;
		array14[1] = grid15;
		array14[2] = stackLayout;
		array14[3] = scrollView;
		array14[4] = userInfoRegistView;
		object service14;
		xamlServiceProvider14.Add(typeFromHandle27, service14 = new SimpleValueTargetProvider(array14, Entry.FontSizeProperty, nameScope));
		xamlServiceProvider14.Add(typeof(IReferenceProvider), service14);
		Type typeFromHandle28 = typeof(IXamlTypeResolver);
		XmlNamespaceResolver xmlNamespaceResolver14 = new XmlNamespaceResolver();
		xmlNamespaceResolver14.Add("", "http://xamarin.com/schemas/2014/forms");
		xmlNamespaceResolver14.Add("x", "http://schemas.microsoft.com/winfx/2009/xaml");
		xmlNamespaceResolver14.Add("calx", "clr-namespace:Caliburn.Micro.Xamarin.Forms;assembly=Caliburn.Micro.Platform.Xamarin.Forms");
		xmlNamespaceResolver14.Add("renderer", "clr-namespace:NHL.Views.Renderer");
		xmlNamespaceResolver14.Add("converter", "clr-namespace:NHL.Views.Converters");
		xmlNamespaceResolver14.Add("effect", "clr-namespace:NHL.Views.Effect");
		xamlServiceProvider14.Add(typeFromHandle28, new XamlTypeResolver(xmlNamespaceResolver14, typeof(UserInfoRegistView).GetTypeInfo().Assembly));
		xamlServiceProvider14.Add(typeof(IXmlLineInfoProvider), new XmlLineInfoProvider(new XmlLineInfo(125, 71)));
		entry.SetValue(fontSizeProperty7, ((IExtendedTypeConverter)fontSizeConverter7).ConvertFromInvariantString("Large", (IServiceProvider)xamlServiceProvider14));
		entry.SetValue(Entry.PlaceholderProperty, "必須");
		entry.SetValue(InputView.KeyboardProperty, new KeyboardTypeConverter().ConvertFromInvariantString("Text"));
		bindingExtension.Mode = BindingMode.TwoWay;
		bindingExtension.Path = "Name";
		BindingBase binding = ((IMarkupExtension<BindingBase>)bindingExtension).ProvideValue((IServiceProvider)null);
		entry.SetBinding(Entry.TextProperty, binding);
		entry.Effects.Add(fixedFontSizeTextBoxEffect);
		VisualDiagnostics.RegisterSourceInfo(fixedFontSizeTextBoxEffect, new Uri("Views/UserInfoRegistView.xaml", UriKind.RelativeOrAbsolute), 127, 26);
		grid15.Children.Add(entry);
		VisualDiagnostics.RegisterSourceInfo(entry, new Uri("Views/UserInfoRegistView.xaml", UriKind.RelativeOrAbsolute), 125, 18);
		entry2.SetValue(Grid.RowProperty, 3);
		entry2.SetValue(Grid.ColumnProperty, 1);
		entry2.SetValue(Xamarin.Forms.View.MarginProperty, new Thickness(0.0, 5.0, 10.0, 5.0));
		BindableProperty fontSizeProperty8 = Entry.FontSizeProperty;
		FontSizeConverter fontSizeConverter8 = new FontSizeConverter();
		XamlServiceProvider xamlServiceProvider15 = new XamlServiceProvider();
		Type typeFromHandle29 = typeof(IProvideValueTarget);
		object[] array15 = new object[0 + 5];
		array15[0] = entry2;
		array15[1] = grid15;
		array15[2] = stackLayout;
		array15[3] = scrollView;
		array15[4] = userInfoRegistView;
		object service15;
		xamlServiceProvider15.Add(typeFromHandle29, service15 = new SimpleValueTargetProvider(array15, Entry.FontSizeProperty, nameScope));
		xamlServiceProvider15.Add(typeof(IReferenceProvider), service15);
		Type typeFromHandle30 = typeof(IXamlTypeResolver);
		XmlNamespaceResolver xmlNamespaceResolver15 = new XmlNamespaceResolver();
		xmlNamespaceResolver15.Add("", "http://xamarin.com/schemas/2014/forms");
		xmlNamespaceResolver15.Add("x", "http://schemas.microsoft.com/winfx/2009/xaml");
		xmlNamespaceResolver15.Add("calx", "clr-namespace:Caliburn.Micro.Xamarin.Forms;assembly=Caliburn.Micro.Platform.Xamarin.Forms");
		xmlNamespaceResolver15.Add("renderer", "clr-namespace:NHL.Views.Renderer");
		xmlNamespaceResolver15.Add("converter", "clr-namespace:NHL.Views.Converters");
		xmlNamespaceResolver15.Add("effect", "clr-namespace:NHL.Views.Effect");
		xamlServiceProvider15.Add(typeFromHandle30, new XamlTypeResolver(xmlNamespaceResolver15, typeof(UserInfoRegistView).GetTypeInfo().Assembly));
		xamlServiceProvider15.Add(typeof(IXmlLineInfoProvider), new XmlLineInfoProvider(new XmlLineInfo(130, 71)));
		entry2.SetValue(fontSizeProperty8, ((IExtendedTypeConverter)fontSizeConverter8).ConvertFromInvariantString("Large", (IServiceProvider)xamlServiceProvider15));
		entry2.SetValue(Entry.PlaceholderProperty, "必須");
		entry2.SetValue(InputView.KeyboardProperty, new KeyboardTypeConverter().ConvertFromInvariantString("Text"));
		bindingExtension2.Mode = BindingMode.TwoWay;
		bindingExtension2.Path = "NameKana";
		BindingBase binding2 = ((IMarkupExtension<BindingBase>)bindingExtension2).ProvideValue((IServiceProvider)null);
		entry2.SetBinding(Entry.TextProperty, binding2);
		entry2.Effects.Add(fixedFontSizeTextBoxEffect2);
		VisualDiagnostics.RegisterSourceInfo(fixedFontSizeTextBoxEffect2, new Uri("Views/UserInfoRegistView.xaml", UriKind.RelativeOrAbsolute), 132, 26);
		grid15.Children.Add(entry2);
		VisualDiagnostics.RegisterSourceInfo(entry2, new Uri("Views/UserInfoRegistView.xaml", UriKind.RelativeOrAbsolute), 130, 18);
		picker.SetValue(Grid.RowProperty, 5);
		picker.SetValue(Grid.ColumnProperty, 1);
		picker.SetValue(Xamarin.Forms.View.MarginProperty, new Thickness(0.0, 5.0, 10.0, 5.0));
		bindingExtension3.Mode = BindingMode.TwoWay;
		bindingExtension3.Path = "SelectedSexType";
		BindingBase binding3 = ((IMarkupExtension<BindingBase>)bindingExtension3).ProvideValue((IServiceProvider)null);
		picker.SetBinding(Picker.SelectedItemProperty, binding3);
		bindingExtension4.Path = "SexTypes";
		BindingBase binding4 = ((IMarkupExtension<BindingBase>)bindingExtension4).ProvideValue((IServiceProvider)null);
		picker.SetBinding(Picker.ItemsSourceProperty, binding4);
		bindingExtension5.Path = "Name";
		BindingBase target = (picker.ItemDisplayBinding = ((IMarkupExtension<BindingBase>)bindingExtension5).ProvideValue((IServiceProvider)null));
		VisualDiagnostics.RegisterSourceInfo(target, new Uri("Views/UserInfoRegistView.xaml", UriKind.RelativeOrAbsolute), 135, 159);
		picker.Effects.Add(fixedFontSizeTextBoxEffect3);
		VisualDiagnostics.RegisterSourceInfo(fixedFontSizeTextBoxEffect3, new Uri("Views/UserInfoRegistView.xaml", UriKind.RelativeOrAbsolute), 137, 26);
		grid15.Children.Add(picker);
		VisualDiagnostics.RegisterSourceInfo(picker, new Uri("Views/UserInfoRegistView.xaml", UriKind.RelativeOrAbsolute), 135, 18);
		label7.SetValue(Grid.RowProperty, 7);
		label7.SetValue(Grid.ColumnProperty, 1);
		label7.SetValue(Xamarin.Forms.View.MarginProperty, new Thickness(7.0, 5.0, 10.0, 5.0));
		BindableProperty fontSizeProperty9 = Label.FontSizeProperty;
		FontSizeConverter fontSizeConverter9 = new FontSizeConverter();
		XamlServiceProvider xamlServiceProvider16 = new XamlServiceProvider();
		Type typeFromHandle31 = typeof(IProvideValueTarget);
		object[] array16 = new object[0 + 5];
		array16[0] = label7;
		array16[1] = grid15;
		array16[2] = stackLayout;
		array16[3] = scrollView;
		array16[4] = userInfoRegistView;
		object service16;
		xamlServiceProvider16.Add(typeFromHandle31, service16 = new SimpleValueTargetProvider(array16, Label.FontSizeProperty, nameScope));
		xamlServiceProvider16.Add(typeof(IReferenceProvider), service16);
		Type typeFromHandle32 = typeof(IXamlTypeResolver);
		XmlNamespaceResolver xmlNamespaceResolver16 = new XmlNamespaceResolver();
		xmlNamespaceResolver16.Add("", "http://xamarin.com/schemas/2014/forms");
		xmlNamespaceResolver16.Add("x", "http://schemas.microsoft.com/winfx/2009/xaml");
		xmlNamespaceResolver16.Add("calx", "clr-namespace:Caliburn.Micro.Xamarin.Forms;assembly=Caliburn.Micro.Platform.Xamarin.Forms");
		xmlNamespaceResolver16.Add("renderer", "clr-namespace:NHL.Views.Renderer");
		xmlNamespaceResolver16.Add("converter", "clr-namespace:NHL.Views.Converters");
		xmlNamespaceResolver16.Add("effect", "clr-namespace:NHL.Views.Effect");
		xamlServiceProvider16.Add(typeFromHandle32, new XamlTypeResolver(xmlNamespaceResolver16, typeof(UserInfoRegistView).GetTypeInfo().Assembly));
		xamlServiceProvider16.Add(typeof(IXmlLineInfoProvider), new XmlLineInfoProvider(new XmlLineInfo(140, 71)));
		label7.SetValue(fontSizeProperty9, ((IExtendedTypeConverter)fontSizeConverter9).ConvertFromInvariantString("Large", (IServiceProvider)xamlServiceProvider16));
		staticResourceExtension8.Key = "LabelColor";
		XamlServiceProvider xamlServiceProvider17 = new XamlServiceProvider();
		Type typeFromHandle33 = typeof(IProvideValueTarget);
		object[] array17 = new object[0 + 5];
		array17[0] = label7;
		array17[1] = grid15;
		array17[2] = stackLayout;
		array17[3] = scrollView;
		array17[4] = userInfoRegistView;
		object service17;
		xamlServiceProvider17.Add(typeFromHandle33, service17 = new SimpleValueTargetProvider(array17, Label.TextColorProperty, nameScope));
		xamlServiceProvider17.Add(typeof(IReferenceProvider), service17);
		Type typeFromHandle34 = typeof(IXamlTypeResolver);
		XmlNamespaceResolver xmlNamespaceResolver17 = new XmlNamespaceResolver();
		xmlNamespaceResolver17.Add("", "http://xamarin.com/schemas/2014/forms");
		xmlNamespaceResolver17.Add("x", "http://schemas.microsoft.com/winfx/2009/xaml");
		xmlNamespaceResolver17.Add("calx", "clr-namespace:Caliburn.Micro.Xamarin.Forms;assembly=Caliburn.Micro.Platform.Xamarin.Forms");
		xmlNamespaceResolver17.Add("renderer", "clr-namespace:NHL.Views.Renderer");
		xmlNamespaceResolver17.Add("converter", "clr-namespace:NHL.Views.Converters");
		xmlNamespaceResolver17.Add("effect", "clr-namespace:NHL.Views.Effect");
		xamlServiceProvider17.Add(typeFromHandle34, new XamlTypeResolver(xmlNamespaceResolver17, typeof(UserInfoRegistView).GetTypeInfo().Assembly));
		xamlServiceProvider17.Add(typeof(IXmlLineInfoProvider), new XmlLineInfoProvider(new XmlLineInfo(140, 88)));
		object obj8 = ((IMarkupExtension)staticResourceExtension8).ProvideValue((IServiceProvider)xamlServiceProvider17);
		label7.TextColor = (Color)obj8;
		VisualDiagnostics.RegisterSourceInfo(obj8, new Uri("Views/UserInfoRegistView.xaml", UriKind.RelativeOrAbsolute), 140, 88);
		label7.SetValue(Label.VerticalTextAlignmentProperty, new TextAlignmentConverter().ConvertFromInvariantString("Center"));
		staticResourceExtension9.Key = "BirthDayToBisibleConverter";
		XamlServiceProvider xamlServiceProvider18 = new XamlServiceProvider();
		Type typeFromHandle35 = typeof(IProvideValueTarget);
		object[] array18 = new object[0 + 6];
		array18[0] = bindingExtension6;
		array18[1] = label7;
		array18[2] = grid15;
		array18[3] = stackLayout;
		array18[4] = scrollView;
		array18[5] = userInfoRegistView;
		object service18;
		xamlServiceProvider18.Add(typeFromHandle35, service18 = new SimpleValueTargetProvider(array18, typeof(BindingExtension).GetRuntimeProperty("Converter"), nameScope));
		xamlServiceProvider18.Add(typeof(IReferenceProvider), service18);
		Type typeFromHandle36 = typeof(IXamlTypeResolver);
		XmlNamespaceResolver xmlNamespaceResolver18 = new XmlNamespaceResolver();
		xmlNamespaceResolver18.Add("", "http://xamarin.com/schemas/2014/forms");
		xmlNamespaceResolver18.Add("x", "http://schemas.microsoft.com/winfx/2009/xaml");
		xmlNamespaceResolver18.Add("calx", "clr-namespace:Caliburn.Micro.Xamarin.Forms;assembly=Caliburn.Micro.Platform.Xamarin.Forms");
		xmlNamespaceResolver18.Add("renderer", "clr-namespace:NHL.Views.Renderer");
		xmlNamespaceResolver18.Add("converter", "clr-namespace:NHL.Views.Converters");
		xmlNamespaceResolver18.Add("effect", "clr-namespace:NHL.Views.Effect");
		xamlServiceProvider18.Add(typeFromHandle36, new XamlTypeResolver(xmlNamespaceResolver18, typeof(UserInfoRegistView).GetTypeInfo().Assembly));
		xamlServiceProvider18.Add(typeof(IXmlLineInfoProvider), new XmlLineInfoProvider(new XmlLineInfo(140, 159)));
		object target2 = (bindingExtension6.Converter = (IValueConverter)((IMarkupExtension)staticResourceExtension9).ProvideValue((IServiceProvider)xamlServiceProvider18));
		VisualDiagnostics.RegisterSourceInfo(target2, new Uri("Views/UserInfoRegistView.xaml", UriKind.RelativeOrAbsolute), 140, 159);
		bindingExtension6.Path = "Birthday";
		BindingBase binding5 = ((IMarkupExtension<BindingBase>)bindingExtension6).ProvideValue((IServiceProvider)null);
		label7.SetBinding(VisualElement.IsVisibleProperty, binding5);
		label7.Effects.Add(fixedFontSizeLabelEffect7);
		VisualDiagnostics.RegisterSourceInfo(fixedFontSizeLabelEffect7, new Uri("Views/UserInfoRegistView.xaml", UriKind.RelativeOrAbsolute), 142, 26);
		grid15.Children.Add(label7);
		VisualDiagnostics.RegisterSourceInfo(label7, new Uri("Views/UserInfoRegistView.xaml", UriKind.RelativeOrAbsolute), 140, 18);
		datePickerView.SetValue(Grid.RowProperty, 7);
		datePickerView.SetValue(Grid.ColumnProperty, 1);
		datePickerView.SetValue(Xamarin.Forms.View.MarginProperty, new Thickness(0.0, 5.0, 10.0, 5.0));
		bindingExtension7.Mode = BindingMode.TwoWay;
		bindingExtension7.Path = "Birthday";
		BindingBase binding6 = ((IMarkupExtension<BindingBase>)bindingExtension7).ProvideValue((IServiceProvider)null);
		datePickerView.SetBinding(DatePickerView.NullableDateProperty, binding6);
		datePickerView.SetValue(DatePicker.FormatProperty, "yyyy/MM/dd");
		datePickerView.SetValue(DatePicker.TextColorProperty, Color.Transparent);
		datePickerView.SetValue(VisualElement.BackgroundColorProperty, Color.Transparent);
		datePickerView.Effects.Add(fixedFontSizeTextBoxEffect4);
		VisualDiagnostics.RegisterSourceInfo(fixedFontSizeTextBoxEffect4, new Uri("Views/UserInfoRegistView.xaml", UriKind.RelativeOrAbsolute), 147, 26);
		grid15.Children.Add(datePickerView);
		VisualDiagnostics.RegisterSourceInfo(datePickerView, new Uri("Views/UserInfoRegistView.xaml", UriKind.RelativeOrAbsolute), 145, 18);
		entry3.SetValue(Grid.RowProperty, 9);
		entry3.SetValue(Grid.ColumnProperty, 1);
		entry3.SetValue(Xamarin.Forms.View.MarginProperty, new Thickness(0.0, 5.0, 10.0, 5.0));
		bindingExtension8.Path = "IsNetworkEnabled";
		BindingBase binding7 = ((IMarkupExtension<BindingBase>)bindingExtension8).ProvideValue((IServiceProvider)null);
		entry3.SetBinding(VisualElement.IsEnabledProperty, binding7);
		grid15.Children.Add(entry3);
		VisualDiagnostics.RegisterSourceInfo(entry3, new Uri("Views/UserInfoRegistView.xaml", UriKind.RelativeOrAbsolute), 150, 18);
		heightPickerView.SetValue(Grid.RowProperty, 9);
		heightPickerView.SetValue(Grid.ColumnProperty, 1);
		heightPickerView.SetValue(Xamarin.Forms.View.MarginProperty, new Thickness(0.0, 5.0, 0.0, 5.0));
		bindingExtension9.Mode = BindingMode.TwoWay;
		bindingExtension9.Path = "SelectedHeightItem";
		BindingBase binding8 = ((IMarkupExtension<BindingBase>)bindingExtension9).ProvideValue((IServiceProvider)null);
		heightPickerView.SetBinding(Picker.SelectedItemProperty, binding8);
		bindingExtension10.Path = "HeightList";
		BindingBase binding9 = ((IMarkupExtension<BindingBase>)bindingExtension10).ProvideValue((IServiceProvider)null);
		heightPickerView.SetBinding(Picker.ItemsSourceProperty, binding9);
		bindingExtension11.Path = "Name";
		BindingBase target3 = (heightPickerView.ItemDisplayBinding = ((IMarkupExtension<BindingBase>)bindingExtension11).ProvideValue((IServiceProvider)null));
		VisualDiagnostics.RegisterSourceInfo(target3, new Uri("Views/UserInfoRegistView.xaml", UriKind.RelativeOrAbsolute), 151, 182);
		heightPickerView.SetValue(VisualElement.BackgroundColorProperty, Color.Transparent);
		heightPickerView.Effects.Add(fixedFontSizeTextBoxEffect5);
		VisualDiagnostics.RegisterSourceInfo(fixedFontSizeTextBoxEffect5, new Uri("Views/UserInfoRegistView.xaml", UriKind.RelativeOrAbsolute), 153, 26);
		grid15.Children.Add(heightPickerView);
		VisualDiagnostics.RegisterSourceInfo(heightPickerView, new Uri("Views/UserInfoRegistView.xaml", UriKind.RelativeOrAbsolute), 151, 18);
		entry4.SetValue(Grid.RowProperty, 11);
		entry4.SetValue(Grid.ColumnProperty, 1);
		BindableProperty fontSizeProperty10 = Entry.FontSizeProperty;
		FontSizeConverter fontSizeConverter10 = new FontSizeConverter();
		XamlServiceProvider xamlServiceProvider19 = new XamlServiceProvider();
		Type typeFromHandle37 = typeof(IProvideValueTarget);
		object[] array19 = new object[0 + 5];
		array19[0] = entry4;
		array19[1] = grid15;
		array19[2] = stackLayout;
		array19[3] = scrollView;
		array19[4] = userInfoRegistView;
		object service19;
		xamlServiceProvider19.Add(typeFromHandle37, service19 = new SimpleValueTargetProvider(array19, Entry.FontSizeProperty, nameScope));
		xamlServiceProvider19.Add(typeof(IReferenceProvider), service19);
		Type typeFromHandle38 = typeof(IXamlTypeResolver);
		XmlNamespaceResolver xmlNamespaceResolver19 = new XmlNamespaceResolver();
		xmlNamespaceResolver19.Add("", "http://xamarin.com/schemas/2014/forms");
		xmlNamespaceResolver19.Add("x", "http://schemas.microsoft.com/winfx/2009/xaml");
		xmlNamespaceResolver19.Add("calx", "clr-namespace:Caliburn.Micro.Xamarin.Forms;assembly=Caliburn.Micro.Platform.Xamarin.Forms");
		xmlNamespaceResolver19.Add("renderer", "clr-namespace:NHL.Views.Renderer");
		xmlNamespaceResolver19.Add("converter", "clr-namespace:NHL.Views.Converters");
		xmlNamespaceResolver19.Add("effect", "clr-namespace:NHL.Views.Effect");
		xamlServiceProvider19.Add(typeFromHandle38, new XamlTypeResolver(xmlNamespaceResolver19, typeof(UserInfoRegistView).GetTypeInfo().Assembly));
		xamlServiceProvider19.Add(typeof(IXmlLineInfoProvider), new XmlLineInfoProvider(new XmlLineInfo(156, 54)));
		entry4.SetValue(fontSizeProperty10, ((IExtendedTypeConverter)fontSizeConverter10).ConvertFromInvariantString("Large", (IServiceProvider)xamlServiceProvider19));
		entry4.SetValue(Xamarin.Forms.View.MarginProperty, new Thickness(0.0, 5.0, 10.0, 5.0));
		entry4.SetValue(InputView.KeyboardProperty, new KeyboardTypeConverter().ConvertFromInvariantString("Numeric"));
		bindingExtension12.Mode = BindingMode.TwoWay;
		bindingExtension12.Path = "Weight";
		BindingBase binding10 = ((IMarkupExtension<BindingBase>)bindingExtension12).ProvideValue((IServiceProvider)null);
		entry4.SetBinding(Entry.TextProperty, binding10);
		entry4.Effects.Add(fixedFontSizeTextBoxEffect6);
		VisualDiagnostics.RegisterSourceInfo(fixedFontSizeTextBoxEffect6, new Uri("Views/UserInfoRegistView.xaml", UriKind.RelativeOrAbsolute), 158, 26);
		grid15.Children.Add(entry4);
		VisualDiagnostics.RegisterSourceInfo(entry4, new Uri("Views/UserInfoRegistView.xaml", UriKind.RelativeOrAbsolute), 156, 18);
		button.SetValue(Grid.RowProperty, 13);
		button.SetValue(Grid.ColumnSpanProperty, 2);
		button.SetValue(Xamarin.Forms.View.MarginProperty, new Thickness(10.0, 10.0, 10.0, 5.0));
		button.SetValue(Button.TextProperty, "次へ");
		button.SetValue(Message.AttachProperty, "NextButton");
		button.SetValue(Xamarin.Forms.View.HorizontalOptionsProperty, LayoutOptions.FillAndExpand);
		button.SetValue(Button.TextColorProperty, Color.White);
		staticResourceExtension10.Key = "ButtonColor";
		XamlServiceProvider xamlServiceProvider20 = new XamlServiceProvider();
		Type typeFromHandle39 = typeof(IProvideValueTarget);
		object[] array20 = new object[0 + 5];
		array20[0] = button;
		array20[1] = grid15;
		array20[2] = stackLayout;
		array20[3] = scrollView;
		array20[4] = userInfoRegistView;
		object service20;
		xamlServiceProvider20.Add(typeFromHandle39, service20 = new SimpleValueTargetProvider(array20, VisualElement.BackgroundColorProperty, nameScope));
		xamlServiceProvider20.Add(typeof(IReferenceProvider), service20);
		Type typeFromHandle40 = typeof(IXamlTypeResolver);
		XmlNamespaceResolver xmlNamespaceResolver20 = new XmlNamespaceResolver();
		xmlNamespaceResolver20.Add("", "http://xamarin.com/schemas/2014/forms");
		xmlNamespaceResolver20.Add("x", "http://schemas.microsoft.com/winfx/2009/xaml");
		xmlNamespaceResolver20.Add("calx", "clr-namespace:Caliburn.Micro.Xamarin.Forms;assembly=Caliburn.Micro.Platform.Xamarin.Forms");
		xmlNamespaceResolver20.Add("renderer", "clr-namespace:NHL.Views.Renderer");
		xmlNamespaceResolver20.Add("converter", "clr-namespace:NHL.Views.Converters");
		xmlNamespaceResolver20.Add("effect", "clr-namespace:NHL.Views.Effect");
		xamlServiceProvider20.Add(typeFromHandle40, new XamlTypeResolver(xmlNamespaceResolver20, typeof(UserInfoRegistView).GetTypeInfo().Assembly));
		xamlServiceProvider20.Add(typeof(IXmlLineInfoProvider), new XmlLineInfoProvider(new XmlLineInfo(163, 174)));
		object obj9 = ((IMarkupExtension)staticResourceExtension10).ProvideValue((IServiceProvider)xamlServiceProvider20);
		button.BackgroundColor = (Color)obj9;
		VisualDiagnostics.RegisterSourceInfo(obj9, new Uri("Views/UserInfoRegistView.xaml", UriKind.RelativeOrAbsolute), 163, 174);
		button.Effects.Add(fixedFontSizeButtonEffect);
		VisualDiagnostics.RegisterSourceInfo(fixedFontSizeButtonEffect, new Uri("Views/UserInfoRegistView.xaml", UriKind.RelativeOrAbsolute), 165, 26);
		grid15.Children.Add(button);
		VisualDiagnostics.RegisterSourceInfo(button, new Uri("Views/UserInfoRegistView.xaml", UriKind.RelativeOrAbsolute), 163, 18);
		button2.SetValue(Grid.RowProperty, 14);
		button2.SetValue(Grid.ColumnSpanProperty, 2);
		button2.SetValue(Xamarin.Forms.View.MarginProperty, new Thickness(10.0, 10.0, 10.0, 5.0));
		button2.SetValue(Button.TextProperty, "今はしない");
		button2.SetValue(Message.AttachProperty, "LaterButton");
		button2.SetValue(Xamarin.Forms.View.HorizontalOptionsProperty, LayoutOptions.FillAndExpand);
		staticResourceExtension11.Key = "ButtonColor";
		XamlServiceProvider xamlServiceProvider21 = new XamlServiceProvider();
		Type typeFromHandle41 = typeof(IProvideValueTarget);
		object[] array21 = new object[0 + 5];
		array21[0] = button2;
		array21[1] = grid15;
		array21[2] = stackLayout;
		array21[3] = scrollView;
		array21[4] = userInfoRegistView;
		object service21;
		xamlServiceProvider21.Add(typeFromHandle41, service21 = new SimpleValueTargetProvider(array21, Button.TextColorProperty, nameScope));
		xamlServiceProvider21.Add(typeof(IReferenceProvider), service21);
		Type typeFromHandle42 = typeof(IXamlTypeResolver);
		XmlNamespaceResolver xmlNamespaceResolver21 = new XmlNamespaceResolver();
		xmlNamespaceResolver21.Add("", "http://xamarin.com/schemas/2014/forms");
		xmlNamespaceResolver21.Add("x", "http://schemas.microsoft.com/winfx/2009/xaml");
		xmlNamespaceResolver21.Add("calx", "clr-namespace:Caliburn.Micro.Xamarin.Forms;assembly=Caliburn.Micro.Platform.Xamarin.Forms");
		xmlNamespaceResolver21.Add("renderer", "clr-namespace:NHL.Views.Renderer");
		xmlNamespaceResolver21.Add("converter", "clr-namespace:NHL.Views.Converters");
		xmlNamespaceResolver21.Add("effect", "clr-namespace:NHL.Views.Effect");
		xamlServiceProvider21.Add(typeFromHandle42, new XamlTypeResolver(xmlNamespaceResolver21, typeof(UserInfoRegistView).GetTypeInfo().Assembly));
		xamlServiceProvider21.Add(typeof(IXmlLineInfoProvider), new XmlLineInfoProvider(new XmlLineInfo(168, 160)));
		object obj10 = ((IMarkupExtension)staticResourceExtension11).ProvideValue((IServiceProvider)xamlServiceProvider21);
		button2.TextColor = (Color)obj10;
		VisualDiagnostics.RegisterSourceInfo(obj10, new Uri("Views/UserInfoRegistView.xaml", UriKind.RelativeOrAbsolute), 168, 160);
		button2.SetValue(VisualElement.BackgroundColorProperty, Color.Transparent);
		button2.Effects.Add(fixedFontSizeButtonEffect2);
		VisualDiagnostics.RegisterSourceInfo(fixedFontSizeButtonEffect2, new Uri("Views/UserInfoRegistView.xaml", UriKind.RelativeOrAbsolute), 170, 26);
		grid15.Children.Add(button2);
		VisualDiagnostics.RegisterSourceInfo(button2, new Uri("Views/UserInfoRegistView.xaml", UriKind.RelativeOrAbsolute), 168, 18);
		stackLayout.Children.Add(grid15);
		VisualDiagnostics.RegisterSourceInfo(grid15, new Uri("Views/UserInfoRegistView.xaml", UriKind.RelativeOrAbsolute), 51, 14);
		scrollView.Content = stackLayout;
		VisualDiagnostics.RegisterSourceInfo(stackLayout, new Uri("Views/UserInfoRegistView.xaml", UriKind.RelativeOrAbsolute), 50, 10);
		userInfoRegistView.SetValue(ContentPage.ContentProperty, scrollView);
		VisualDiagnostics.RegisterSourceInfo(scrollView, new Uri("Views/UserInfoRegistView.xaml", UriKind.RelativeOrAbsolute), 49, 6);
		VisualDiagnostics.RegisterSourceInfo(userInfoRegistView, new Uri("Views/UserInfoRegistView.xaml", UriKind.RelativeOrAbsolute), 3, 2);
	}

	private void __InitComponentRuntime()
	{
		this.LoadFromXaml(typeof(UserInfoRegistView));
	}
}
